### DISCUSSION TITLE
Changing the logo ?

### DISCUSSION THREAD

**Discussion by fralau** [squidfunk/mkdocs-material#2167] [Q&A] [answered]
Happy New Year 2020,

Apologies for asking such a dumb question, but for the life of me, I could'nt find the way to change the logo icon, on the status bar.

![Capture d’écran 2021-01-01 à 12 34 00](https://user-images.githubusercontent.com/36767124/103437949-adea8800-4c2d-11eb-856a-3de70c529339.png)

Favicon was easy, though (I followed the [instructions](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/)).

This is what I have:

```
theme: 
  name: material
  language: en
  palette:
    primary: blue
    scheme: settlenext
    accent: blue
  favicon: assets/mylogo.ico
  icon: assets/mylogo.ico
```
Favicon works (it happily appears on my website's tab in the browser), but icon doesn't. Perhaps I'm missing something obvious ?

**Comment by squidfunk** [comment, marked as answer]
You're using an invalid format. As the [documentation](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#logo) states, you can either provide an image or the name of an icon bundled with the theme:

Icon:

``` yaml
theme:
  icon:
    logo: material/test-tube
```

Image:

``` yaml
theme:
  logo: assets/logo.png
```
