### DISCUSSION TITLE
How to change the color of links in my text?

### DISCUSSION THREAD

**Discussion by KaratekHD** [squidfunk/mkdocs-material#2169] [Q&A] [answered]
I am trying to change the link colour using custom css, but I can't get it to work the way I want it to. I only want to change the colour of links inside my articles, not in the sidebar etc. 
```css
a:link {
    color: #09bfdd;
}
```
Does not change the colour in my article, but everywhere else, and 
```css
:root {
    --md-primary-fg-color:        #000000;
    --md-primary-fg-color--light: #000000;
    --md-accent-fg-color:                   #09bfdd;
    --md-accent-bg-color--light:            #09bfdd;
    --md-accent-bg-color:                   #09bfdd;
    --md-accent-fg-color:                   #09bfdd;
    --md-accent-fg-color--light:            #09bfdd;
    --md-accent-fg-color--transparent:      #09bfdd;
}
```

Thanks for your help.

**Comment by squidfunk** [comment, marked as answer]
You need to scope your changes accordingly. To only change the link color, you can use the `--md-typeset-a-color` variable and scope it to the content area:

``` css
.md-content {
  --md-typeset-a-color: #09bfdd;
}
```

For a list of all definitions please see [the color variable definitions](https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/stylesheets/main/_colors.scss).
