### DISCUSSION TITLE
How can I change the font-size of the admonition block

### DISCUSSION THREAD

**Discussion by imflash217** [squidfunk/mkdocs-material#2260] [Q&A] [answered]
Hi,
Great Library. ❤️ 
How can I change the font size of the admonition block. The default font-size of the text inside the admonition block is much smaller than the main text. It gets pretty difficult to read the text inside the admonition block.
Thank you

**Comment by squidfunk** [comment, marked as answer]
This should work:

``` css
.md-typeset .admonition,
.md-typeset details {
  font-size: 16px
}
```
