### DISCUSSION TITLE
Deploying to github User and Organization pages using Actions

### DISCUSSION THREAD

**Discussion by lasarojc** [squidfunk/mkdocs-material#2287] [Show and tell]
I would like to offer an action to publish to gh-pages User and Organization, to complement what is in mkdocs-material/docs/publishing-your-site.md. The following action is probably more convoluted than it needs to be, but is a working example. It builds when you push to the *source* branch and pushes the built site to the *master* branch, which GH will copy to *ghpages* and publish.

```
name: ci
on:
  push:
    branches:
      - source
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: install material
      run: |
           pip install mkdocs-material
           pip install python-markdown-math

    - name: Checkout ref branch
      uses: actions/checkout@v2
      with:
         ref: source
         path: source-branch

    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
         ref: master
         path: master-branch

    - name: Create local changes and commit
      run: |
           cd source-branch
           mkdocs build -d ../master-branch
           cd ../master-branch
           git config --local user.email "github-actions@github.com"
           git config --local user.name "github-actions"
           git add -A
           git commit -m "Add changes"
           git push
```

Improvements welcome.

Caveat: it does not support the draw-io-exporter plugin :(
