### DISCUSSION TITLE
Is the documentation for navigation setup up to date (tabs)?

### DISCUSSION THREAD

**Discussion by dellagustin-sap** [squidfunk/mkdocs-material#2304] [Q&A] [answered]
Hello All,

The documentation for tabs setup states that we should add the following lines to the mkdocs.yml file:
```yml
theme:
  features:
    - navigation.tabs
```

This did not work for me. I have searched for issues related to tabs and so that people were using:
```yml
theme:
  name: material
  features:
    tabs: true
```
The latter worked for me. Is it the correct way?

References:
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
