### DISCUSSION TITLE
Can't make navigation indexes work at all

### DISCUSSION THREAD

**Discussion by dpetroff** [squidfunk/mkdocs-material#2306] [Q&A] [answered]
Hi, I've set up a trivial site while trying to make this work, served by [the docker container](https://hub.docker.com/r/squidfunk/mkdocs-material), and this still doesn't work for me:
```
site_name: MySite
nav:
  - Home: index.md
  - Section:
    - section/index.md
    - section/about.md
theme:
  name: material
  features:
    - navigation.indexes
```

There are no additional plugins or fluff, only the three markdown files listed in the `nav` section exist, there is nothing special in any of the files, just a single word to tell which one is showing, yet the index page is still listed under the Section page:
![image](https://user-images.githubusercontent.com/1384881/108241450-c2ce9c80-7143-11eb-82ca-d9224e6308ff.png)

My impression from the documentation was that with the `- navigation.indexes` feature in a setup like this, clicking the Section would expand it and open the section/index page, which will not be listed under the section in the navigation area on the left. Instead, the only thing that happens is that the section expands, just as if the feature was not enabled.
