### DISCUSSION TITLE
```` markdown not rendering with content tabs

### DISCUSSION THREAD

**Discussion by mdeliw** [squidfunk/mkdocs-material#2379] [Q&A] [answered]
Can someone tell me what I may be missing? 

<img width="529" alt="Screen Shot 2021-03-02 at 9 53 47 PM" src="https://user-images.githubusercontent.com/46644001/109754795-eb25b480-7ba1-11eb-9142-0cc7757218a1.png">
<img width="566" alt="Screen Shot 2021-03-02 at 9 54 13 PM" src="https://user-images.githubusercontent.com/46644001/109754798-ebbe4b00-7ba1-11eb-9319-3a57bf36b4fa.png">

**Comment by facelessuser** [comment, marked as answer]
I'm not sure, can you provide some configuration information?

**Reply by mdeliw** [reply]
Here's the mkdocs.yml:

```yml
site_name: ***
site_description: >-
  ***
theme:
  name: material
  include_search_page: false
  search_index_only: true
  language: en
  features:
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.expand
  palette:
    scheme: slate
    primary: deep blue
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: material/book-open-page-variant

# Plugins

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true

# Customization
extra:
  generator: false

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Platforms:
  ...
  - Journeys:
  ...
  - Reference:
    - Abbreviations: reference/abbreviation.md
    ...
```
