### DISCUSSION TITLE
CSS example in Admonition page doesn't fully work with PyMdown Details

### DISCUSSION THREAD

**Discussion by Andre601** [squidfunk/mkdocs-material#2413] [Q&A] [answered]
Using the following code snippets to apply a "youtube" type details admonition doesn't fully work:
```css
:root {
  --md-admonition-icon--youtube: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path d="M549.655 124.083c-6.281-23.65-24.787-42.276-48.284-48.597C458.781 64 288 64 288 64S117.22 64 74.629 75.486c-23.497 6.322-42.003 24.947-48.284 48.597-11.412 42.867-11.412 132.305-11.412 132.305s0 89.438 11.412 132.305c6.281 23.65 24.787 41.5 48.284 47.821C117.22 448 288 448 288 448s170.78 0 213.371-11.486c23.497-6.321 42.003-24.171 48.284-47.821 11.412-42.867 11.412-132.305 11.412-132.305s0-89.438-11.412-132.305zm-317.51 213.508V175.185l142.739 81.205-142.739 81.201z"/></svg>');
}

.md-typeset .admonition.youtube,
.md-typeset details.youtube {
  border-color: rgb(255, 0, 0);
}
.md-typeset .youtube > .admonition-title,
.md-typeset .youtube > summary {
  background-color: rgba(255, 0, 0, 0.1);
}
.md-typeset .youtube > .admonition-title::before,
.md-typeset .youtube > summary::before {
  background-color: rgb(255, 0, 0);
  -webkit-mask-image: var(--md-admonition-icon--youtube);
          mask-image: var(--md-admonition-icon--youtube);
}
```

The result show the left border of the title field in the default fg color used:
![image](https://user-images.githubusercontent.com/11576465/110282258-778b0980-7fde-11eb-9c12-c0979eb645c4.png)

**Comment by Andre601** [comment, marked as answer]
From what I can gather do you need to also add `border-color: rgb(255, 0, 0);` to
```css
.md-typeset .youtube > .admonition-title,
.md-typeset .youtube > summary {
  background-color: rgba(255, 0, 0, 0.1);
}
```
to work properly with details.
This is partially backed by the fact that the default admonition-types also seem to apply a border-color to those typeset combinations...
