### DISCUSSION TITLE
Instant navigation and mkdocs-redirect do not play well?

### DISCUSSION THREAD

**Discussion by hellt** [squidfunk/mkdocs-material#2517] [Q&A] [answered]
Hi all,
When I had instant navigation enabled and an mkdocs-redirect plugin enabled, I noticed that (at least on the dev server) the redirect was not happening.

The redirect destination was an external resource defined like that:

```yaml
- redirects:
      redirect_maps:
        lab-examples/tls-cert.md: https://some.where
```

Is it expected, considering that the new path is external resource?
