### DISCUSSION TITLE
Language Icon

### DISCUSSION THREAD

**Discussion by lyandr** [squidfunk/mkdocs-material#2553] [Q&A] [answered]
Hello,

if i configured extra.alternate in mkdocs.yml i have a menu where i can choose the language with the material icon "Transtlate". Is it possible to change/configure this icon?

I saw on source of mkdocs material in partials/header.html the following line `{% set icon = config.theme.icon.alternate or "material/translate" %}` but even i configure this mkdocs it seems to not taken into account.

Thanks in advance for your help

Regards
Lyandr

**Comment by squidfunk** [comment]
It's still undocumented, but should work if set from `mkdocs.yml` like this:

``` yaml
theme:
  icon:
    translate: "material/translate"
```

**Reply by lyandr** [reply]
Hello, thank you but it didn't work. I have tried:
```yml
theme:
  icon:
    translate: "material/language"
```

but it is always the material/translate icon. Maybe a conflict with i18n plugin? I have set i18n in order to not add his own langauge menu with `material_alternate: false`

Regards

**Comment by thorstenpeter-sophos** [comment, marked as answer]
Just for reference in case someone gets to this question and wonders why it doesn't work for them:
The configuration given in the answer isn't correct (at least, it didn't work for me). The correct setting name is `theme.icon.alternate`, not `theme.icon.translate`. For example, add the following to `mkdocs.yml` to change the icon to `:octicons-globe-24:`:

``` yaml
theme:
  icon:
    alternate: octicons/globe-24
```
