### DISCUSSION TITLE
How to change bold font color for slate theme

### DISCUSSION THREAD

**Discussion by wizo06** [squidfunk/mkdocs-material#2576] [Q&A] [answered]
I've implemented the color palette toggle on my site, but I noticed that the `slate` theme isn't really up to part to my liking. So I decided to edit some variables as suggested by the documentation
```css
[data-md-color-scheme="slate"] {
  ...
}
```
The bold fonts in the `slate` theme is not very distinct from regular font, so I wanted to change the font color specifically for bold fonts. I looked through the file containing [color definitions](https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/stylesheets/main/_colors.scss) for a list of all CSS varialbes, and realized that there is no variable for bold fonts. My solution was to add these lines
```css
[data-md-color-scheme="slate"] {
  ...
}
strong, .md-nav__title, h2, h3, h4 {
  color: rgba(255, 255, 255, 0.87);
}
```

**What's the problem?**
It affects the font color for bold fonts in BOTH `slate` and `default`(light) theme.

**My question**
Is there a way to change the bold font color *only* for `slate` theme?

**Comment by wizo06** [comment, marked as answer]
I figured it out. I just had to use css child selector pattern
```css
[data-md-color-scheme="slate"] {
  /* variables go in here*/
}

[data-md-color-scheme="slate"] strong, [data-md-color-scheme="slate"] .md-nav__title, [data-md-color-scheme="slate"] h2, [data-md-color-scheme="slate"] h3, [data-md-color-scheme="slate"] h4 {
  color: rgba(255, 255, 255, 0.87);
}
```
