### DISCUSSION TITLE
How to modify font-size for screen width

### DISCUSSION THREAD

**Discussion by xareelee** [squidfunk/mkdocs-material#2583] [General]
I notice that the `font-size` would be changed with screen width.

- `< 1600 px`
- `>= 1600 px`
- `>= 2000 px`

The `font-size` is too large on my 27-inch screen. I want to use a fixed font-size. I find the code in `_base.scss`

```scss
html {
  height: 100%;
  overflow-x: hidden;
  font-size: 125%;

  @include break-from-device(screen medium) {
    font-size: 137.5%;
  }

  @include break-from-device(screen large) {
    font-size: 150%;
  }
}
```

but I'm not familiar with SCSS and any frontend skills. How could I set a fixed `font-size`?

**Comment by squidfunk** [comment]
Well, how about this?

``` css
html {
  font-size: 20px;
}
```
