### DISCUSSION TITLE
Admonition Icons not apperaring on Azure Static Web App (Preview)

### DISCUSSION THREAD

**Discussion by jromal** [squidfunk/mkdocs-material#2608] [Q&A] [answered]
## Overview

I am trying the preview of Azure **Static** Web App, that I think it will be perfect to be used with mkdocs-material.
I am facing a problem, and not sure how to start looking for the problem.

The admonition icons, that appear on the local server or when the site is generated locally, do not appear on the Azure Static Web. I had the same set of documents and configuration files working on github pages (now I have closed it there). Now is on Azure DevOps. 

## Seek for a solution

Any idea where should I start look? I downloaded in the meantime the bootstrap icons hoping that this could solve the problem. But it does not. I could download material or fontawesome or octicons but I prefer to ask before continue testing.

Can it be a problem on the Azure DevOps pipeline? (it just do a pip, so nothing special)
Maybe some package missing? But I do not know where to check if the icons are not available. 
Are they in some folder that I can check the artifact before publishing to the Static Web App?

Can it be that the icons are accessed on the net and it blocks connections? If yes, should the download of icons help or not?

I am not a big expert on markdown or markdown-material, neither on Azure DevOps and therefore what I am asking may be trivial for some of you.

Any idea? Someone that can help? 
I appreciate any hint and comment. In any direction.

Thanks.

## mkdocs.yml file

This is the file I am using now (changing all things I can imagine to find the problem).
The emojy part was the attempt for the bootstrap icons.

``` yaml
# Project information
site_name: CS Documentation 
use_directory_urls: true 
copyright: Copyright &copy; 2021 Henkel &amp; affiliated. All rights reserved.

# Extensions
markdown_extensions:
# Standard extensions 
# --> https://python-markdown.github.io/extensions/
    - admonition    # note, abstract, info, tip, success, question, warning, failure, danger, bug, example, quote
    - abbr          # 
    - attr_list
    - def_list
    - meta  
    - footnotes    
    - toc:
        permalink: "#"
        separator: "_"
        toc_depth: 3
# pydmdown extensions 
# --> https://facelessuser.github.io/pymdown-extensions/
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.smartsymbols
    - pymdownx.tabbed
    - pymdownx.keys
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.snippets
    - pymdownx.tasklist

    # ### Python Mdown emojy
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
        options:
          custom_icons:
            - overrides/.icons

# Plugins (add "search" if you add any other one)
plugins:
    - search
    - awesome-pages:
        # collapse_single_pages: true

# Theme settings
theme:
  name: material
  custom_dir: overrides 
  logo: images/logo.png

  features:
    - navigation.instant
    - navigation.top
    - navigation.tracking
    # - navigation.tabs
    # - navigation.expand
    # - navigation.sections
    # - toc.integrate

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: companydx
      accent: companyred
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: companyred
      accent: companydx
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# Additional CSS styles and Java Scripts
extra_css:
    - stylesheets/extra.css
    - stylesheets/details.css
extra_javascript:
    - javascripts/extra.js
    - javascripts/details.js

```
