### DISCUSSION TITLE
How to customize component files

### DISCUSSION THREAD

**Discussion by kdubb** [squidfunk/mkdocs-material#2646] [Q&A] [answered]
I'm trying to customize the source component (via overriding its `index.ts`). I've followed the docs for overriding files but my override is never recognized.

Here is my directory layout:
```
.
├── docs
│   ├── assets
│   │   └── logo.svg
│   ├── index.md
│   └── stylesheets
│       └── custom.css
├── mkdocs.yml
├── overrides
│   ├── assets
│   │   └── javascripts
│   │       └── components
│   │           └── source
│   │               └── _
│   │                   └── index.ts
│   └── partials
│       └── header.html
```

Here is my mkdocs.yml:
```yaml
site_name: Test

theme:
  name: material
  logo: assets/logo.svg
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides

extra_css:
  - stylesheets/custom.css

nav:
  Home: index.md

```
