### DISCUSSION TITLE
Link color for black or white theme.

### DISCUSSION THREAD

**Discussion by steam3d** [squidfunk/mkdocs-material#2709] [General]
How to setup color of links?
```
theme:
  name: material
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: white
      accent: light blue
      ...
```

I create an extra.css
```
:root {
    --md-typeset-a-color: #EE0F0F;
}
```

It changes only when i remove `primary: white` from mkdocs.yml

**Comment by pierrevano** [comment]
@steam3d

You need to specify the ```extra_css``` in your ```mkdocs.yml``` as such
 
```
theme:
  name: material
  palette: 
...
extra_css:
  - assets/stylesheets/extra.css
```

And then you will be able to use the new root color.
