### DISCUSSION TITLE
Different Logo-Icon for Dark Mode and Light Mode

### DISCUSSION THREAD

**Discussion by SimLowSpec** [squidfunk/mkdocs-material#2729] [Q&A] [answered]
Hi squidfunk,
first of all: I am a big fan, your work is awesome!

I am facing the challenge to use a different logo image for dark mode and light mode. Unfortunately, I don't have a single-colored svg, so [this approach here](https://github.com/squidfunk/mkdocs-material/discussions/2097), won't work for me.
I also tried to override the logo.html but I don't know the syntax on how to decide whether I am currently in dark mode or not, so the only thing I managed to override was using the same icon for light and dark mode.
Can you maybe give me a hint: How can I use a diffent png for the theme "default" and for the theme "slate" as logo?
Thank you in advance!
Simon

**Comment by bradumbaugh** [comment, marked as answer]
Hi @SimLowSpec, I wonder if [this discussion](https://github.com/squidfunk/mkdocs-material/discussions/2097) might help you?

**Reply by SimLowSpec** [reply]
Hi @bradumbaugh ,
no, this doesn't help since it is the discussion that I referenced in my question. I don't have single colored svgs...

**Reply by bradumbaugh** [reply]
Oh, I'm sorry, @SimLowSpec , I don't how how I missed that link! Still, though, that thread contains this comment:

> Note that using this approach, you cannot change multiple colors. For that to work, you'd have to add two logos and toggle the display property dependent on the theme mode using some extra CSS.

I think this might look something like this (didn't test):

`mkdocs.yml`:

```yaml
theme:
  logo_dark_mode: assets/logo-dark-mode.svg
  logo_light_mode: assets/logo-light-mode.svg
palette:
  - media: "(prefers-color-scheme: light)"
    scheme: light-mode
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: dark-mode
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
```

`logo.html`:

```html
<img id="logo_light_mode" src="{{ config.theme.logo_light_mode | url }}" alt="logo">
<img id="logo_dark_mode" src="{{ config.theme.logo_dark_mode | url }}" alt="logo">
```

`extra.css`:

```css
#logo_light_mode {
    display: var(--md-footer-logo-white);
}

#logo_dark_mode {
    display: var(--md-footer-logo-dark-mode);
}

[data-md-color-scheme="light-mode"] {
    --md-footer-logo-dark-mode:         none;
    --md-footer-logo-light-mode:         block;
}

[data-md-color-scheme="dark-mode"] {
    --md-footer-logo-dark-mode:         none;
    --md-footer-logo-light-mode:         block;
}
```
