### DISCUSSION TITLE
Dark Mode toggle not working

### DISCUSSION THREAD

**Discussion by ashnair1** [squidfunk/mkdocs-material#2762] [Q&A] [answered]
Hi,

I'm using this [template](https://github.com/zillionare/cookiecutter-pypackage) for building my package. 

The [mkdocs.yml](https://github.com/zillionare/cookiecutter-pypackage/blob/master/mkdocs.yml) for the project is as follows:

```
site_name: Python Project Wizard (ppw)
repo_url: https://github.com/zillionare/cookiecutter-pypackage
repo_name: Python Project Wizard
nav:
  - Introduction: index.md
  - Tutorial: tutorial.md
  - Console script: console_script_setup.md
  - Release checklist: pypi_release_checklist.md
  - FAQ: faq.md
  - History: history.md
  
theme:
  name: material
  language: en
  #logo: assets/logo.png
  palette:
    primary: light blue
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
plugins:
  - include-markdown
  - search:
      lang: en
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zillionare
      name: Github
    - icon: material/email
      link: "mailto:code@jieyu.ai"
```

I wanted add a dark mode toggle and so I did as per the [mkdocs documentation](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/) by replacing the following in the project's mkdocs.yml

```
   palette:
     primary: light blue
```

with this

```
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
```

![image](https://user-images.githubusercontent.com/32295036/122033462-98cf7300-cde1-11eb-8679-933b0fe0d681.png)

However, this doesn't work and the toggle is not displayed. Do you have an idea as to why this happens?
