### DISCUSSION TITLE
404 for published pages with gitlab cicd runner

### DISCUSSION THREAD

**Discussion by FerdinandZhong** [squidfunk/mkdocs-material#2887] [Q&A] [answered]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [ ] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I have tried publishing the pages with gitlab cicd runner. I have input site_url in the mkdocs.yaml. However, even though the cicd job succeeded the page is shown with 404.
But the page works fine with localhost.
And strangely, for some other repos, there is no issue.

### Expected behaviour

The page is successfully published.

### Actual behaviour

The page is 404

### Steps to reproduce

1. I will provide my mkdocs.yaml
2. Run with gitlab cicd runner

### Package versions

- Python: `3.7.11`
- MkDocs: `1.2.2`
- Material: `7.2.0`

### Configuration

```yaml
site_name: Global Tree Attribute Recommendation Technique Details
site_url: # company's internal url

repo_name: # company's internal repo
repo_url: # company's internal url

theme:
  name: material
  palette:
    primary: deep purple
  features:
    - search.suggest
    - search.highlight

plugins:
  - search:
      lang: en

markdown_extensions:
  - admonition
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: pymdownx.superfences.fence_div_format
  - pymdownx.keys

nav:
  - Introduction: 'index.md'
  - Deployment: 'deploy.md'
  - Attribute: 'attribute.md'
```

### System information

- Operating system: gitlab cicd runner
- Browser: firefox
