### DISCUSSION TITLE
Version selector missing when using Mike

### DISCUSSION THREAD

**Discussion by vinlam292** [squidfunk/mkdocs-material#2907] [Q&A] [answered]
Hi this is similar to #2347

Description:
Hey guys, I'm following https://github.com/squidfunk/mkdocs-material-example-versioning and the version selector doesn't appear for me

![Screenshot 2021-08-04 at 14 38 58](https://user-images.githubusercontent.com/88442033/128190891-5b09067c-cb33-40e4-a0b1-8c06ea784f0c.png)

Steps to reproduce the bug
```
pip install mike
git clone https://github.com/squidfunk/mkdocs-material-example-versioning.git`
cd mkdocs-material-example-versioning
mike deploy --update-aliases 0.1 latest
mike set-default latest
mike deploy --update-aliases 0.2 latest
mike serve 
or
mkdocs serve
```

This is the error I get after running mkdocs serve
```
WARNING  -  [14:42:53] "GET /versions.json HTTP/1.1" code 404
```

Package Versions:
```
Python  3.9.6
mike  1.01
mkdocs-material  7.2.0
mkdocs-material-extensions 1.0.1
```

# Project information
```
site_name: My Docs
site_url: https://squidfunk.github.io/mkdocs-material-example-versioning/
site_author: Martin Donath


repo_name: squidfunk/mkdocs-material-example-versioning
repo_url: https://github.com/squidfunk/mkdocs-material-example-versioning
edit_uri: ""

theme:
  name: material

extra:
  version:
    provider: mike
 ```
System information
OS: MacOS
Browser: Chrome
