### DISCUSSION TITLE
pymdownx.critic not rendering as expected

### DISCUSSION THREAD

**Discussion by tacticz** [squidfunk/mkdocs-material#2913] [Q&A] [answered]
Hello, I'm new to mkdocs-material and currently exploring / practicing with the syntax.
I'm going through the documentation's reference pages and have reached the [formatting section](https://squidfunk.github.io/mkdocs-material/reference/formatting/).

At this point I'm trying to activate the `pymdownx.critic` extension, inserting it in my `mkdocs.yml` configuration file.
Then, adding the example code given in the documentation, I expected it to render as expected. Unfortunately, the code is outputted unformatted.

In my `mkdocs.yml` file I have:
```yml
...
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
```
I also tried adding the `mode: view` option in case it was required but to no avail...
```yml
...
markdown_extensions:
  ...
  - pymdownx.critic:
      mode: view
```

My `index.md` file contains the following markdown code (copy / pasted from the documentation page):
```markdown
Text can be {​--deleted--} and replacement text {​++added++}. This can also be
combined into {​~~one~>a single~~} operation. {​==Highlighting==} is also
possible {​>>and comments can be added inline<<}.

{​==
Formatting can also be applied to blocks, by putting the opening and closing
tags on separate lines and adding new lines between the tags and the content.
==}
```

Which I expected to see rendered as illustrated in the documentation. But, as said earlier, it just outputs "as is", no formatting occurs, the code being outputted to the rendered page: `{​--deleted--}`, `{​++added++}`, ` {​==Highlighting==}` and `{​~~one~>a single~~}` are present.

Does anyone have a hint on what I might be doing wrong here?
All other extensions that I activated earlier are working as expected until now...

Thank you.

PS:
As I go further through the documentation, it appears that I face a similar problem with `pymdownx.betterem`. As a matter of fact, it seems that whenever a secondary argument is required by the extension, it doesn't seem to work. Is it that I am writing it wrong in the `mkdocs.yml` file?

What I currently have in my `mkdocs.yml` file (based on what seems to be prescribed) is:
- a lline with `markdown_extensions:` at "level zero" (i.e. preceded by zero space)
- followed by one line for each extension, starting with two spaces, then a caret, one space then the extension name
- for extensions requiring a secondary argument: one line following the extension name, starting with four spaces, then the argument name followed by a colon, then the argument value
```yml
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - ...
  - pymdownx.betterem:
      smart_enable: all
  - ...
```

Is this the correct way to do it?
Does someone have an idea of where I might be wrong?

Thanks

**Comment by facelessuser** [comment, marked as answer]
There seem to be a lot of questions here, so right now I'll stick to the first. From what I see, the setup looks fine, but the snippet you posted had bad characters in it (invisible white space stuff):

<img width="1032" alt="Screen Shot 2021-08-05 at 7 37 20 AM" src="https://user-images.githubusercontent.com/1055125/128359733-70aba448-db8f-443c-942d-8141ee0840e1.png">

Once removing those, it works fine:

<img width="711" alt="Screen Shot 2021-08-05 at 7 38 17 AM" src="https://user-images.githubusercontent.com/1055125/128359807-a3f5037d-0470-4955-bb25-dcb90013ec97.png">

**Reply by squidfunk** [reply]
@facelessuser this was likely [copied from the docs](https://squidfunk.github.io/mkdocs-material/reference/formatting/#highlighting-changes), where I had to insert those characters in order to prevent the extension from applying the highlighting. It's similar to the problem we had with Snippets. Is there another option to keep the critic extension from applying the highlighting?

**Reply by facelessuser** [reply]
Well, actually yes. I recently created a custom solution that I use in Pymdownx. I don't run critic by default in the docs, but then I have special fences where I create a sandboxed environment via a custom fence. Below I only run critic on the text in this code block which yields what you see over in the second example in the docs: https://facelessuser.github.io/pymdown-extensions/extensions/critic/#usage.

The actual plugin is not released with pymdownx, but just something I source in locally and is found in my tools directory: https://github.com/facelessuser/pymdown-extensions/blob/main/tools/pymdownx_md_render.py.

This doesn't work for me when talking about Snippets only because I use Snippets by default.

````
    === "Output"
        ```md-render
        ---
        extensions:
        - pymdownx.critic
        ---
        Here is some {--*incorrect*--} Markdown.  I am adding this{++ here++}.  Here is some more {--text
        that I am removing--}text.  And here is even more {++text that I
        am ++}adding.{~~

        ~>  ~~}Paragraph was deleted and replaced with some spaces.{~~  ~>

        ~~}Spaces were removed and a paragraph was added.

        And here is a comment on {==some
         text==}{>>This works quite well. I just wanted to comment on it.<<}. Substitutions {~~is~>are~~} great!

        General block handling.

        {--

        * test remove
        * test remove
        * test remove
            * test remove
        * test remove

        --}

        {++

        * test add
        * test add
        * test add
            * test add
        * test add

        ++}
        ```
````

**Reply by tacticz** [reply]
Thank you guys for the swift answers!

@facelessuser YES! That's where the problem came from, thank you! :-D
Removing the invisible characters made the *critics* extension work as expected.

@squidfunk, indeed, I "simply" copy / pasted the example from the docs and never noticed about the invisible characters...

**Reply by squidfunk** [reply]
@facelessuser uh, that sounds like a whole lot of work. I'll consider disabling the Critic extension and use regular markup to show the actual results, same as we did for Snippets.

**Reply by facelessuser** [reply]
Sure, whatever works for you. It's actually not that much work as the work is all done 🤷🏻.

**Reply by squidfunk** [reply]
Hmm, is there an easy way to get the `md-render` fence working with the docs build of Material for MkDocs? How can I source it when building the docs? This would indeed solve a lot of problems once and for all.

**Reply by facelessuser** [reply]
I'll see if I can throw together a pull and see how it works in MkDocs Material.

**Reply by facelessuser** [reply]
I have it working locally:

````
_Example_:

``` markdown
Text can be {--deleted--} and replacement text {++added++}. This can also be
combined into {~~one~>a single~~} operation. {==Highlighting==} is also
possible {>>and comments can be added inline<<}.

{==

Formatting can also be applied to blocks, by putting the opening and closing
tags on separate lines and adding new lines between the tags and the content.

==}
```

_Result_:

``` md-render
---
extensions:
- pymdownx.critic
---
Text can be {--deleted--} and replacement text {++added++}. This can also be
combined into {~~one~>a single~~} operation. {==Highlighting==} is also
possible {>>and comments can be added inline<<}.

{==

Formatting can also be applied to blocks, by putting the opening and closing
tags on separate lines and adding new lines between the tags and the content.

==}
```
````

<img width="742" alt="Screen Shot 2021-08-06 at 7 28 30 AM" src="https://user-images.githubusercontent.com/1055125/128517582-4ba2696e-89a8-4cfb-8ad2-f7a2ee550a9d.png">

To serve locally, you have to do this

```
npm start
python -m mkdocs serve
```

`python -m` will serve local files so we can do this:

```yaml
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: md-render
          class: md-render
          format: !!python/name:tools.pymdownx_md_render.md_sub_render
```

Not sure how that works with your docker image and publishing, but the alternative is that I could stuff it in the `mkdocs-material-extra` package, and you reference it from there as you already install it 🤷🏻.

**Reply by squidfunk** [reply]
> `python -m mkdocs serve`

Wouldn't that also be covered by `pip install -e .`, which I already use for plugin development, so we could keep on using `mkdocs serve`? I think we had it like this for the icon integration before we decided to move the extensions outside of this repository.

**Reply by facelessuser** [reply]
Maybe? I don't think `-e` would install anything in the `tools` folder as we would want to exclude that in setup. Though we could drop it in the package itself maybe. We don't have to document it, but 🤷🏻. I'd have to play with `-e` and confirm.

**Reply by squidfunk** [reply]
I've disabled the Critic extension in 51d4920a2 and replaced the rendered example with plain and simple inline HTML. For now, this seems to be the simplest approach. I've also removed the zero-width whitespace characters from the code example, so it should now work straight away when copied.

**Reply by facelessuser** [reply]
That's what I used to do and is a fine solution.

**Comment by tacticz** [comment]
Nevertheless, I'm still facing a problem with the *betterem* extension. It is activated:
```yml
markdown_extensions:
  - ...
  - ...
  - pymdownx.betterem:
      smart_enable: all
  - ...
```
And I **typed** (no copy paste this time) one example from the  [betterem extension page](https://facelessuser.github.io/pymdown-extensions/extensions/betterem/):
```
***I'm italic and bold* I am just bold.**

***I'm bold and italic!** I am just italic.*
```
But it still renders "as is" (no bold, no italic) :-(
I tried without the `smart_enable: all` option, as well as with the `smart_enable: asterisk` value but nothing seemed to work.
