### DISCUSSION TITLE
Making logo bigger?

### DISCUSSION THREAD

**Discussion by ahojukka5** [squidfunk/mkdocs-material#2933] [Q&A] [answered]
Is there any ways to make logo bigger, to fill the whole header in vertical direction without any gaps? I already figured out that extra css `.md-logo` might be the good starting point, but I didn't manage to find any spells to achieve my actual goals. My attempts so far:

```css
.md-logo {
  /*
  height: 48px;
  width: 48px;
  size: 200%;
  */
  margin: 0px !important;
  padding: 0px !important;
}
```

The actual header is 48 px wide, but svg logo is scaled to 24 px making it tiny.

**Comment by facelessuser** [comment, marked as answer]
Probably something like below to force margin and padding to zero:

```css
.md-header__button.md-logo {
    margin: 0;
    padding: 0;
}
```

Then set the logo to whatever size you want:

```css
.md-header__button.md-logo img, .md-header__button.md-logo svg {
    height: 2.4rem;
    width: 2.4rem;
}
```

<img width="191" alt="Screen Shot 2021-08-13 at 6 38 51 AM" src="https://user-images.githubusercontent.com/1055125/129358346-c6fd23f7-7fcf-47b7-8d72-146ecf2d9631.png">

I don't know if there are side effects to this, but that is basically it. I did this just by using the browser "inspector" to identify what classes to target and the specificity needed for the CSS.

**Reply by ahojukka5** [reply]
This seems to be working. I did the following:

```css
.md-header__button.md-logo {
  margin-top: 0;
  margin-bottom: 0;
  padding-top: 0;
  padding-bottom: 0;
}

.md-header__button.md-logo img,
.md-header__button.md-logo svg {
  height: 70%;
  width: 70%;
}
```

And now the logo is good size. If I try to use "rem" it still preserves the margins.
