### DISCUSSION TITLE
Problem : burger menu triggers a search bar

### DISCUSSION THREAD

**Discussion by glassus** [squidfunk/mkdocs-material#3043] [Q&A] [answered]
Hi everyone,
since this very morning, I experience a problem with my 3 websites running mkdocs (eg : https://glassus.github.io/terminale_nsi/)

When my students open my website on a tiny screen (on their smartphone for instance), the navigation bar becomes a burger menu, as usual.
![Capture d’écran_2021-09-20_17-09-20](https://user-images.githubusercontent.com/54031955/134026525-9df49b43-bb46-44da-ae1f-f24f3d413b2f.png)
But since this morning, a click on this burger triggers a search bar.
![Capture d’écran_2021-09-20_17-10-57](https://user-images.githubusercontent.com/54031955/134026732-74125b95-371b-4ec5-9188-e1af42d5d790.png)
 And this is very, very annoying.
Does anyone here have a clue about what's going on ?

An extract of my yml file  : 
```

theme:
  name: material
  site_url: ""
  custom_dir: my_theme_customizations/
  font: false
  language: fr
  icon:
    logo: material/code-greater-than
    repo : fontawesome/brands/github
  favicon: xtra/favSNT.png

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.integrate
    - header.autohide

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mode sombre

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Mode clair


markdown_extensions:
  - meta
  - abbr
  - admonition
  - def_list
  - attr_list
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tasklist:
      custom_checkbox: false
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: ⚓︎
      toc_depth: 3


plugins:
  - search
  - git-revision-date
  - macros
  - awesome-pages:
      collapse_single_pages: true
 
```
