### DISCUSSION TITLE
Link & Footer background color

### DISCUSSION THREAD

**Discussion by unklsams** [squidfunk/mkdocs-material#3055] [Q&A] [answered]
Trying to change a) link color to blue & b) change the footer background color

Here is my extra-color.css:

:root {
    --md-footer-fg-color:              hsla(0, 0%, 100%, 1);
    --md-footer-fg-color--light:       hsla(0, 0%, 100%, 0.7);
    --md-footer-fg-color--lighter:     hsla(0, 0%, 100%, 0.3);
    --md-footer-bg-color:              hsla(0, 0%, 0%, 0.87);
    --md-footer-bg-color--dark:        hsla(0, 0%, 0%, 0.32);
}

:root > * {
  --md-typeset-a-color: #00BDD6;
}

And my mkdocs.yml:
extra_css:
   - 'extra.css'
   - 'extra-color.css'
( "-" before the 'extra.. though shows as dot when I post here)
Site build is successful but no changes happening to the link & footer background colors!
What am I doing wrong ?

**Comment by squidfunk** [comment]
You're missing a `> *` selector, as it should be:

``` css
:root > * {
  --md-footer-fg-color: hsla(0, 0%, 100%, 1);
  --md-footer-fg-color--light: hsla(0, 0%, 100%, 0.7);
  --md-footer-fg-color--lighter: hsla(0, 0%, 100%, 0.3);
  --md-footer-bg-color: hsla(0, 0%, 0%, 0.87);
  --md-footer-bg-color--dark: hsla(0, 0%, 0%, 0.32);
}
```

**Reply by unklsams** [reply]
Martin,
my priority issue is the link color..my header color is grey and the links are also shown in grey.
This is what I have now (changed color from #00BDD6).However not taking effect...

:root > * {
  --md-typeset-a-color: #90030C;
}

**Reply by unklsams** [reply]
BTW, the footer color didnt work too with your above mentioned updates ! Attaching my requirements.txt used for site build, in case if this will help troubleshoot the problem:
mkdocs==1.1.2
mkdocs-awesome-pages-plugin==2.2.1
mkdocs-git-authors-plugin==0.3.2
mkdocs-git-revision-date-localized-plugin==0.7
mkdocs-material==5.4.0
mkdocs-material-extensions==1.0
mkdocs-mermaid-plugin==0.1.1
mkdocs-minify-plugin==0.3.0
mkdocs-pdf-export-plugin==0.5.6
mkdocs-table-reader-plugin==0.4.1
pymdown-extensions==7.1
markdown-blockdiag==0.7.0
markdown-include==0.5.1
flatten_json
pygments

**Comment by squidfunk** [comment, marked as answer]
It works if you follow [the customization guide](https://squidfunk.github.io/mkdocs-material/customization/#additional-css) and add the following CSS (just verified it again):

``` css
:root > * {
  --md-typeset-a-color: deeppink;
  --md-footer-fg-color: hsla(0, 0%, 100%, 1);
  --md-footer-fg-color--light: hsla(0, 0%, 100%, 0.7);
  --md-footer-fg-color--lighter: hsla(0, 0%, 100%, 0.3);
  --md-footer-bg-color: deeppink;
  --md-footer-bg-color--dark: hotppink;
}
```

![screenshot-localhost-8000-1632817567979](https://user-images.githubusercontent.com/932156/135051685-0833e5c2-ff2a-40da-bbfa-80da15ce9754.png)
