### DISCUSSION TITLE
Mermaid diagrams are rendered randomly

### DISCUSSION THREAD

**Discussion by igeofr** [squidfunk/mkdocs-material#3056] [Q&A] [answered]
Hi,

We have insider status and we try to take full advantage of the mermaid rendering but we get a random rendering. 

``` mermaid
graph LR
  A[Start] --> B{Error?};
  B -->|Yes| C[Hmm...];
  C --> D[Debug];
  D --> B;
  B ---->|No| E[Yay!];
```

If we reload the page several times we get a visual error : 

```
Syntax error in graph
mermaid version 8.8.4
```

And the console shows this error:

```
bundle.e7b111c5.min.js:3 Uncaught Error: Parse error on line 1:
Syntax error in grap
^
Expecting 'open_directive', 'NEWLINE', 'SPACE', 'GRAPH', got 'ALPHA'
    at Xt.parseError (flow.jison:293)
    at Xt.parse (flow.jison:363)
    at xe (flowRenderer.js:291)
    at Object.render (mermaidAPI.js:339)
    at bundle.e7b111c5.min.js:3
    at Object.next (bundle.e7b111c5.min.js:3)
    at t._next (bundle.e7b111c5.min.js:3)
    at t.next (bundle.e7b111c5.min.js:3)
    at bundle.e7b111c5.min.js:3
    at Je (bundle.e7b111c5.min.js:3)
```

The configuration can be viewed here : https://github.com/geotribu/website/blob/features/mermaid/mkdocs.yml#L198-L202

**Comment by squidfunk** [comment]
Thanks for reporting. Can you create a reproducible example? If so, please open a new issue, it’s probably a quick fix then 😊

**Reply by facelessuser** [reply]
Is it several reloads in quick succession? Or is it just several reloads spaced out? Are you using instant mode? Or no instant mode? I could maybe see some kind of race condition if using instant mode with a quick succession of reloads.

I know MathJax has a section in their docs talking about if you are running their process asynchronously: http://docs.mathjax.org/en/latest/web/typeset.html#handling-asynchronous-typesetting. Maybe something similar applies here.

Granted, this is me just dropping some info without knowing exactly how Material is doing what they are doing, but maybe it is helpful.

**Reply by Guts** [reply]
Hi,

As a member of the same team (@geotribu) of @igeofr, I can give some addtional inputs.
This is related to [this PR](https://github.com/geotribu/website/pull/426), where we try to remove the "manual" integration (working quite well in production) of mermaijs in order to take advantage of the out-of-the-box integration of the theme since we are insiders.

> Are you using instant mode? Or no instant mode?

Instant mode is not enabled.

# Two situations can easily be compared

> Can you create a reproducible example?

Yes, using our public repository or comparing the actual situation (in production) with the WIP (on Netlify preview).

To reproduce:

1. Open one of the links below (on preview)
2. If the chart is showing, try to reload the page 2 or 3 times

## Actual setup (production = master)

- [mkdocs.yml configuration](https://github.com/geotribu/website/blob/master/mkdocs.yml#L174-L204):

```yaml
extra_javascript:
  - "theme/assets/javascripts/extra.js"
  - "https://cdn.jsdelivr.net/npm/wa-mediabox@1.0.1/dist/wa-mediabox.min.js"
  - "https://unpkg.com/mermaid@8.6.4/dist/mermaid.min.js"

markdown_extensions:
  - [ ...]
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
```

- example working pages:
  1. https://static.geotribu.fr/articles/2021/2021-08-31_pg2datagouv/#pg2datagouv
  2. https://static.geotribu.fr/contribuer/guides/diagrams/#rendu
  3. https://static.geotribu.fr/articles/2020/2020-09-11_html2markdown/#conclusion

![image](https://user-images.githubusercontent.com/1596222/134820525-be54a75d-ef8c-4821-b107-29bd3ff63669.png)

## WIP setup (we use netlify to build previews on our PRs)

- [mkdocs.yml configuration](https://github.com/geotribu/website/blob/features/mermaid/mkdocs.yml#L170-L203):

```yaml
extra_javascript:
  - "theme/assets/javascripts/extra.js"
  - "https://cdn.jsdelivr.net/npm/wa-mediabox@1.0.1/dist/wa-mediabox.min.js"

markdown_extensions:
  - [...]
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
```

- same pages, but not working:
  1. https://preview-pullrequest-426--geotribu-preprod.netlify.app/articles/2021/2021-08-31_pg2datagouv/#pg2datagouv
  2. https://preview-pullrequest-426--geotribu-preprod.netlify.app/contribuer/guides/diagrams/
  3. https://preview-pullrequest-426--geotribu-preprod.netlify.app/articles/2020/2020-09-11_html2markdown/#conclusion

![Capture d’écran de 2021-09-26 20-52-09](https://user-images.githubusercontent.com/1596222/134820488-f2a31d09-eed3-488f-9004-ca790c2d4e76.png)

## Differences

- `fence_code_format` is used instead of `fence_div_format`, as [recomended in documentation](https://squidfunk.github.io/mkdocs-material/reference/diagrams/#configuration)
- no more MermaidJS listed as `extra_javascript`

> Tested on Firefox and Chromium on Ubuntu 20.04
