### DISCUSSION TITLE
Change language selector icon.

### DISCUSSION THREAD

**Discussion by champsblanc** [squidfunk/mkdocs-material#3143] [Q&A] [answered]
Is there an easy way to change the svg on the language selector? My team doesn't like the default one very much and they'd like something like an earth globe or something like that. I suppose it should be doable by making some theme overriding but I'm not having much success with JS/CSS.

Thanks!

**Comment by champsblanc** [comment, marked as answer]
Nevermind, fixed it.

```
theme:
    name: material
    icon:
      alternate: fontawesome/solid/globe-europe
```

This worked like a charm.


For custom icons, this should work too:
https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#additional-icons
