### DISCUSSION TITLE
Start with specific section expanded

### DISCUSSION THREAD

**Discussion by hhslepicka** [squidfunk/mkdocs-material#3161] [Q&A] [answered]
Hi,

Is it possible to start with a section under my content list expanded by default?
Under my navigation I have a `Plugins` section which I would like it to start as expanded on the menu by default.

Here is an example of my `nav`:
```yaml
...
nav:
    - Home: index.md
    - Plugins:
      - Plugin A: plugins/a.md
      - Plugin B: plugins/b.md
...
```

Sorry if this was asked before but I couldn't find it anywhere.
