### DISCUSSION TITLE
Catch 22? social plugin is not installed

### DISCUSSION THREAD

**Discussion by PEZ** [squidfunk/mkdocs-material#3177] [Q&A] [answered]
I'm trying to set up social cards, disabling them for local builds usingan  environment variable that is only:

```yaml
plugins:
  - social:
      cards: !ENV [MKDOCS_SOCIAL_CARDS, false]
```

This is set to true in CI, and things seems to work. However, building this locally I get this:

```
INFO     -  Building documentation...
ERROR    -  Config value: 'plugins'. Error: The "social" plugin is not installed
Aborted with 1 Configuration Errors!
```

Locally I don't have insiders, since it's an open source project and any contributor should be able to build docs. I don't need social cards then either.

What am I not getting here?
