### DISCUSSION TITLE
Is there a way to define per-page CSS?

### DISCUSSION THREAD

**Discussion by ofek** [squidfunk/mkdocs-material#3220] [Q&A] [answered]
Basically, I'm using [Fira Code](https://github.com/tonsky/FiraCode):

```css
code { font-family: 'Fira Code', monospace; }

@supports (font-variation-settings: normal) {
  code { font-family: 'Fira Code VF', monospace; }
}
```

and on one particular page I need to disable ligatures in order to document the behavior of various version selection operators. Right now I'm doing this:

```css
:root {
  font-variant-ligatures: none;
}
```
