### DISCUSSION TITLE
No admonitions, emoji, and code highlight…

### DISCUSSION THREAD

**Discussion by kierun** [squidfunk/mkdocs-material#3292] [Q&A] [answered]
I tried to get md admonitions, emoji, and code highlight. I added the following to the `mkdocs.yml` file:

```YAML
  markdown_extensions:
    - admonition
    - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight:
      use_pygments: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
    - pymdownx.superfences
```

Running `mkdocs serve` shows none of them on `localhost:8000` as seen here:

![screenshot](https://user-images.githubusercontent.com/3079575/144459289-16219fc0-0230-48a3-b623-e79a6cb327f4.png)

Some version:

```bash
√ ; mkdocs --version
mkdocs, version 1.2.3 from /home/usr/.pyenv/versions/3.10.0/lib/python3.10/site-packages/mkdocs (Python 3.10)
√ ; pip show mkdocs-material
Name: mkdocs-material
Version: 8.0.2
Summary: A Material Design theme for MkDocs
Home-page: https://squidfunk.github.io/mkdocs-material/
Author: Martin Donath
Author-email: martin.donath@squidfunk.com
License: MIT
Location: /home/usr/.pyenv/versions/3.10.0/lib/python3.10/site-packages
Requires: jinja2, markdown, mkdocs, mkdocs-material-extensions, pygments, pymdown-extensions
√ ; python --version
Python 3.10.0
```

What am I doing wrong?

**Comment by facelessuser** [comment, marked as answer]
Indent your extension options by two more spaces.

**Reply by facelessuser** [reply]
I'm not sure about admonitions yet as I don't see example Markdown, just the resultant HTML.

**Reply by kierun** [reply]
No luck I am afraid. Attached is the whole file, in case I really confused something…

```YAML
site_name: My Top Secret stuff™
theme:
  name: material
  font:
    text: "PT Sans Narrow"
  favicon: assets/favicon.png
  palette:
    scheme: slate
    primary: teal
  logo: assets/logo.png
  features:
    - navigation.instant
  markdown_extensions:
    - admonition
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight:
        use_pygments: true
        auto_title: true
        linenums: true
        linenums_style: pymdownx-inline
    - pymdownx.superfences
```

The markdown is written like so:

```
!!! note "optional explicit title within double quotes"
    Any number of other indented markdown elements.

    This is the second paragraph.
```

Just copied from the documentation. And changed `type` to `note`…
