### DISCUSSION TITLE
navigation.indexes and sidebar naming?

### DISCUSSION THREAD

**Discussion by nina-j** [squidfunk/mkdocs-material#3321] [Q&A] [answered]
It looks like navigation.indexes defaults to proper casing the folder name when relying on folder structure rather than a `nav:` specification.

Example:

```yml
site_name: mysite
site_dir: public
use_directory_urls: false

theme:
  name: "material"
  features:
    - navigation.top
    - navigation.tabs
    - navigation.indexes
```

![image](https://user-images.githubusercontent.com/28903001/145023792-ea11b62a-46a7-49b4-acd1-1468306d5069.png)
![image](https://user-images.githubusercontent.com/28903001/145023806-3f4b4480-c57f-4031-8713-207265c0843a.png)

where `http-clients/index.md` has 

```md
---
title: HTTP Client Consistency
---
stuff
```

Is it possible to change this behaviour via e.g. custom JS? We're using a CMS on top of our page that relies on this folder structure.
