### DISCUSSION TITLE
Mermaid Diagram rendering as code block

### DISCUSSION THREAD

**Discussion by aforsythe** [squidfunk/mkdocs-material#3326] [Q&A] [answered]
Apologies if I'm doing something foolish ... An hints on why the mermaid diagram is rendering as a code block would be greatly appreciated.

I'm using the `docker` container and following this :  https://squidfunk.github.io/mkdocs-material/reference/diagrams/

With this `mkdocs.yml` 

```
site_name: Technical Documentation
extra:
  generator: false
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  font:
    text: Pontino Sans
  features:
    - navigation.expand
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/ampas/aces-dev
repo_name: aces-dev
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
```

and this `index.md`

    # Welcome to MkDocs

    For full documentation visit [mkdocs.org](https://www.mkdocs.org).

    ## Commands

    * `mkdocs new [dir-name]` - Create a new project.
    * `mkdocs serve` - Start the live-reloading docs server.
    * `mkdocs build` - Build the documentation site.
    * `mkdocs -h` - Print help message and exit.

    ``` mermaid
    graph LR
      A[Start] --> B{Error?};
      B -->|Yes| C[Hmm...];
      C --> D[Debug];
      D --> B;
      B ---->|No| E[Yay!];
    ```

    ## Project layout

        mkdocs.yml    # The configuration file.
        docs/
            index.md  # The documentation homepage.
            ...       # Other markdown pages, images and other files.
