### DISCUSSION TITLE
Can you override the Code Annotation colour?

### DISCUSSION THREAD

**Discussion by Andre601** [squidfunk/mkdocs-material#3347] [Q&A] [answered]
I want to use the code annotation in some of my code blocks.
The issue here is that the code blocks for the most part only contain comments, which in the end make the code annotations not "stick out" as much as I would like.

Because of this would I like to override the default main colour used for them, but I'm unable to find out what class(es) to override in CSS to achieve a different colour while not affecting other parts of the page itself.

Is that doable?

**Comment by squidfunk** [comment, marked as answer]
Sure, just use CSS:

``` css
/* Inactive annotation */
.md-annotation__index::after {
  background-color: red;
}
/* Focused or hovered annotation */
:where(:focus-within, :hover) > .md-annotation__index::after {
  background-color: blue;
}
```

On a side note, you might want to [strip comments](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#stripping-comments) when using annotations.
