### DISCUSSION TITLE
Change font size only for the footnotes ?

### DISCUSSION THREAD

**Discussion by TRaSH-** [squidfunk/mkdocs-material#3380] [Q&A] [answered]
I'm trying to figure out if it's possible to change the font size only for the footnotes ?

or wouldn't it be possible in how i've set it up?
i've added the text actually in a admonition because the footnotes looked like a part of the main guide.

![image](https://user-images.githubusercontent.com/6155095/147382493-dc4cc2ef-8c33-4376-a643-59f24fb700a0.png)

**Comment by squidfunk** [comment, marked as answer]
Use CSS to do that. Since you're using admonitions inside footnotes, you would need to change the font size for those, too. I haven't tested the following code, but something like the following should work:

``` css
.md-typeset .footnote,
.md-typeset .footnote .admonition {
  font-size: 20px;
}
```

**Reply by thangckt** [reply]
can you show me how to increase font size in tables using CSS? 
Thank.

**Reply by squidfunk** [reply]
You only need super basic CSS:

``` css
.md-typeset table:not([class]) {
  font-size: 16px;
}
```

I recommend learning how to use the [Chrome Dev Tools](https://developer.chrome.com/docs/devtools/).

**Comment by TRaSH-** [comment]
not exactly what it should do.
![image](https://user-images.githubusercontent.com/6155095/147405213-d7d22bab-f3bc-4426-8be4-e3a8f2bf087f.png)
but perhaps if i can make the font smaller i can remove the admonition.
let me try to tinker with it.
or if you know a way i'm open. i'm really a css noob with this

**Comment by TRaSH-** [comment]
Okay adding

```css
/*Change footnotes font size */
.md-typeset .footnote {
  font-size: 12px;
}
```
Does a good result so it doesn't look like it's part of the guide, thnx

![image](https://user-images.githubusercontent.com/6155095/147405808-acd24a1f-de5e-47e5-a007-a6a09dd621ad.png)
