### DISCUSSION TITLE
The title bar and navigation menu aren't rendered markdown.

### DISCUSSION THREAD

**Discussion by epsilon0402** [squidfunk/mkdocs-material#3404] [General]
My H1
`This is **H1**`

**H1** not render in title bar and left table of content. How to fix it, thank you.

**Comment by martinbira** [comment]
What is the actual question? What does your `mkdocs.yml` configuration and the `nav` section look like? What does your `.md`-file look like?

**Comment by epsilon0402** [comment]
![](https://i.ibb.co/19r5CSD/Screenshot-from-2022-01-02-13-41-02.png)

You can see, H1 in content is rendered but in the navigation menu and the title bar, the link doesn't render. 

The mkdocs.yml file.
```
{
# Project information 
site_name: VNCTF Wiki
site_author: VNCTF Team
site_url: 

# Repository
repo_name: 'vnctfwiki/VNCTF-Wiki'
repo_url: 'https://github.com/vnctfwiki/VNCTF-Wiki'

# Copyright 
copyright: Copyright &copy; 2021 - 2022 VNCTF Wiki Team

# Contents
nav:
  - Home:
    - index.md
    - Thư ngỏ: home/about.md
  #   - Introduction: 
  #   - Usage:  
  #   - Contribute: 
  #   - Chat: 
  - Miscellaneous: 
    - misc/misc.md
  - Cryptography:
    - crypto/crypto.md
  - Operating System: 
    - os/os.md
  - Web:
    - web/web.md
  - Pwnable: 
    - pwn/pwn.md
  - Reverse Engineering: 
    - reverse/reverse.md
  - Hardware: 
    - hardware/hardware.md
  - Blockchain: 
    - blockchain/blockchain.md
  - Writeup:
    - writeup/writeup.md

# Themes
theme: 
  name: material
  icon: 
    repo: fontawesome/brands/github
  palette:
    primary: indigo
    accent: deep orange
    scheme: preference
  features:
    - navigation.tabs
    - navigation.top
    # - navigation.tabs.sticky
    # - header.autohide
    - search.suggest
    - search.highlight
    - search.share
    
  font:
    # text: 'SF UI Display'
    text: 'Segoe UI'
    code: 'Monospace'

# Extensions
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - admonition

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/twitter
    - icon: fontawesome/brands/github
      link: https://github.com/vnctfwiki/VNCTF-Wiki
  # alternate:
  #   - name: English
  #     link: /en/ 
  #     lang: en
  #   - name: Vietnamese
  #     link: /vi/
  #     lang: vi
}
```

 Thank you very much.
