### DISCUSSION TITLE
How to reorder pages without specifying the 'nav' attribute?

### DISCUSSION THREAD

**Discussion by christophetd** [squidfunk/mkdocs-material#3482] [Q&A] [answered]
Hello!

First of all, thank you for this _great_ project. I'm using `mkdocs-material` with a mix of manually-written and automatically-generated Markdown files:

```
docs/
  user-guide/
    getting-started.md
    about.md
  automatically-generated/
    automatically-generated-category/
      foo.md
      bar.md
```

The implication of "automatically-generated" is that I can't reference one by one the sections and pages in my `nav` attribute.

With that in mind, **how can I change the order of the pages**? For instance, having `about.md` and `getting-started.md` will place the `About` page before `Getting Started` in the menu, while I'd like the opposite.

Thank you!

**Comment by squidfunk** [comment, marked as answer]
This question is not specific to Material for MkDocs, but MkDocs in general. However, I think the [`mkdocs-awesome-pages-plugin`](https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin) might be what you're looking for. If not, please upstream the question to the MkDocs discussion board.

**Reply by christophetd** [reply]
Thanks! For reference, here's how I solved it:

```yaml
nav:
  - Home: index.md
  - User Guide:
    - Getting Started: user-guide/getting-started.md
  - Auto generated:
    - ... | auto-generated/*/*.md
```
