### DISCUSSION TITLE
tags 'pill' not rendering

### DISCUSSION THREAD

**Discussion by fh2levelgh** [squidfunk/mkdocs-material#3501] [Q&A] [answered]
I have tags setup but the oval/"pill" around the tag name is not rendering so the tags just look like a run on of words instead of individual tags. Not sure if I missed a step, if this is a bug, or if there are additional formatting controls that I can implement.

Regard
![Screen Shot 2022-01-26 at 11 05 35 AM](https://user-images.githubusercontent.com/24487970/151200178-120dcfa4-4908-4979-8ca3-d428099de8f1.png)
s

**Comment by squidfunk** [comment]
Please provide more information, i.e., are you using the built-in tags plugin? Also, which versions are you using + provide the exact Markup that reproduces the error.

**Reply by fh2levelgh** [reply]
mkdocs==1.2.3
mkdocs-material==8.1.7
mkdocs-plugin-tags==1.0.2

I was assuming I was using the built in plugin for tags, but I installed the above mkdocs-plugin-tags==1.02 because when I tried to add `-tags` to the plugins section of the `.yml` it said that the tags plugin was not installed.

mkdocs.yml
```
plugins:
  - search
  - tags:
      tags_file: tags.md
  - mermaid2:
      arguments:
        theme: 'dark'

markdown_extensions:
  - meta
 ```

test_page.md with tags syntax at top of `.md` file for the page.
```
---
tags:
    - tag1
    - tag2
---

# My test page
```
