### DISCUSSION TITLE
Mermaid diagrams not working

### DISCUSSION THREAD

**Discussion by JamesRivers** [squidfunk/mkdocs-material#3511] [Q&A] [answered]
I am running mkdocs-material Version: 8.1.9
I have added 
```yml
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
```
to my mkdocs.yml file.  

In an MD I have
```
```mermaid
graph TD;
A["MXF (example)"] -->|Delivered to Storage Server| B(NAS);
C["WF Manager "]--> |spy and Scrape data from media| B{NAS};
C["WF Manager"]--> |updates| D{ Content Service};
D[" Content Portal"]--> E["PG DataBase"];
```
But the diagrams are not being rendered - what have I missed?

**Comment by squidfunk** [comment]
Mermaid diagram are still exclusively in [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/#5000-aji-panca). When the funding level reaches $5,000, they will be released for everyone. If you want to use them now, you can sponsor @squidfunk with $10/month, and you'll get access to Mermaid diagrams and many other features.

**Reply by chraebslight** [reply]
Is this answer still true? I think with version [0.8.2](https://github.com/squidfunk/mkdocs-material/releases/tag/8.2.0) native support for Mermaid.js was added.

**Reply by squidfunk** [reply, marked as answer]
Mermaid diagrams have since been released and are available in the community edition for free ☺️

**Comment by JamesRivers** [comment]
Thanks Martin, apologies I thought it was in version 8 already. Thanks for confirming, will look at insiders programme.

**Comment by bennypotter** [comment]
I know this issue is pretty old, but Im seeing this problem. I read from the [docs](https://squidfunk.github.io/mkdocs-material/reference/diagrams/#configuration) this should work out of the box with the applied configuration:

```
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
```
What am i missing?

My Mermaid code:

```
```mermaid
graph LR
  A[Start] --> B{Error?};
  B -->|Yes| C[Hmm...];
  C --> D[Debug];
  D --> B;
  B ---->|No| E[Yay!];
```

I'm using:

`mkdocs, version 1.5.3 (Python 3.9)`

```
mkdocs-material==9.4.14
mkdocs-material-extensions==1.3.1
mkdocs-mermaid2-plugin==1.1.1
```

**Reply by kamilkrzyskow** [reply]
Hi @bennypotter,
- you're using an older version of `mkdocs-material`, 
- you're using the mermaid2 plugin that has its own mermaid implementation, which could conflict (?) with the theme's implementation
- the example code blocks is missing \`\`\` at the bottom, but I will assume it was done on purpose here
- you didn't specify how you run the page, with `mkdocs serve` or do you open the `index.html` from the file system

The diagrams are converted with JavaScript, so maybe the mermaid.js gets somehow blocked, by adblock, other extension? Check the console in the browser developer tools.

Best to troubleshoot with a minimal reproduction using the [info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/), and once you have a .zip with the issue then share it here :v:

This is a minimal example not from the info plugin, but works for me with 9.5.11
[mermaid-test.zip](https://github.com/squidfunk/mkdocs-material/files/14495241/mermaid-test.zip)

**Reply by bennypotter** [reply]
Thanks for responding @kamilkrzyskow I think bullet 2 was the problem. I was using the `techdocs-core` plugin, removing that made it work!

**Reply by DarkFM** [reply]
Bullet 2 was the issue for me as well. Since I needed to use both plugins, I added this config inside `markdown_extensions` and that did the trick:
```yaml
- pymdownx.extra:
      pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
```

[SOURCE](https://github.com/johanneswuerbach/backstage-plugin-techdocs-addon-mermaid?tab=readme-ov-file#auto-detection-vs-manual-detection)
