### DISCUSSION TITLE
Force data table to use full width

### DISCUSSION THREAD

**Discussion by Stephen-Gates** [squidfunk/mkdocs-material#3530] [Q&A] [answered]
Is there a way to make the [data table](https://squidfunk.github.io/mkdocs-material/reference/data-tables/) in the screenshot below align with the right edge of the admonition?

<img width="1440" alt="Screen Shot 2022-02-03 at 8 18 40 pm" src="https://user-images.githubusercontent.com/9379524/152323803-5b1adcc7-58a3-42d1-a568-a062cb21fc12.png">

**Comment by squidfunk** [comment, marked as answer]
This should work:

``` css
.md-typeset__table {
  width: 100%;
}

.md-typeset__table table:not([class]) {
  display: table
}
```

Note that I haven't tested it on mobile, so there might be rendering errors. But it should be a starting point at least.
