### DISCUSSION TITLE
GitHub style permalinks

### DISCUSSION THREAD

**Discussion by AshleighAdams** [squidfunk/mkdocs-material#3535] [Show and tell]
So, I much prefer GitHub-style permalinks, where a chain icon floats to the left of the header, instead of the right.

I've looked for an easy solution over the months, hoping for a low hanging fruit, but unfortunately it looked too complex to invest time in, until, I discovered this site: https://facelessuser.github.io/pymdown-extensions/

They have some scss to append the chain from an SVG file, taking that as a base, and with a renewed resolve, I came up with this:

```yml
extra_css:
  - css/github-permalink-style.css
markdown_extensions:
  - toc:
      permalink: ''
```

```css
.headerlink {
	--permalink-size: 16px; /* for font-relative sizes, 0.6em is a good choice */
	--permalink-spacing: 4px;

	width: calc(var(--permalink-size) + var(--permalink-spacing));
	height: var(--permalink-size);
	vertical-align: middle;
	background-color: var(--md-default-fg-color--lighter);
	background-size: var(--permalink-size);
	mask-size: var(--permalink-size);
	-webkit-mask-size: var(--permalink-size);
	mask-repeat: no-repeat;
	-webkit-mask-repeat: no-repeat;
	visibility: visible;
	mask-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg>');
	-webkit-mask-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg>');
}

[id]:target .headerlink {
	background-color: var(--md-typeset-a-color);
}

.headerlink:hover {
	background-color: var(--md-accent-fg-color) !important;
}

@media screen and (min-width: 76.25em) {
	h1, h2, h3, h4, h5, h6 {
		display: flex;
		align-items: center;
		flex-direction: row;
		column-gap: 0.2em; /* fixes spaces in titles */
	}

	.headerlink {
		order: -1;
		margin-left: calc(var(--permalink-size) * -1 - var(--permalink-spacing)) !important;
	}
}
```

Here's how it looks:

![image](https://user-images.githubusercontent.com/182589/153004627-6df3f8e9-c747-4f43-bd62-a8dabaa96c3f.gif)

Full disclosure, I'm not experienced with HTML5/CSS, so I'm probably doing something wrong, so I can only provide the works-on-my-machine guarantee, sorry!

**Comment by squidfunk** [comment]
Thanks for sharing!

**Reply by AshleighAdams** [reply]
Just wondering in terms of that snippet, trying to make it less theme-specific, are you aware of a way to eliminate the magic number in the media query `min-width: 76.25em`?

**Reply by squidfunk** [reply]
Unfortunately, not possible, [`@custom-media`](https://www.w3.org/TR/mediaqueries-5/#custom-mq) is not (widely?) supported.

**Comment by AshleighAdams** [comment]
Updated it so it's mobile friendly, and reposition with flex instead of float on wider screens.

**Reply by MaximilianKohler** [reply]
For me, it changes the icon, but it's still on the right side. I'm not sure what to try/mess with? 

Oh, I see it's a screen-width issue. It'll only do it on wide enough browsers.

**Comment by TRaSH-** [comment]
thank you so much for this, i was trying to figure out how to replace the weird icon to something better looking, need to get used to the option that the link is now before the title, but it's so much better looking then the default weird character

**Comment by santaimpersonator** [comment]
I found a simple workaround to use the built-in 🔗 icon (not sure if this is proper, but it works for me):

1. Add an [admonition type](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#admonition-icons)
  `mkdocs.yml` *(truncated)*
    ``` yml
    # Configuration for webpage theme
    theme:
      # Configures icons of admonition types
      icon:
        repo: fontawesome/brands/github
        admonition:
          # Add custom icon
          link: octicons/link-16
    ```
2. Referencing the icon similar to how it is done for [custom admonition](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#custom-admonitions)
  `<filename>.css`
    ``` css
     -webkit-mask-image: var(--md-admonition-icon--link);
             mask-image: var(--md-admonition-icon--link);
    /* mask-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg>');
    -webkit-mask-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg>'); */
    ```
