### DISCUSSION TITLE
Disable header.autohide

### DISCUSSION THREAD

**Discussion by FernandoBasso** [squidfunk/mkdocs-material#3586] [Q&A] [answered]
I DO NOT have `header.autohide` (as mentined [in the docs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#automatic-hiding) in theme features, but the header still collapses/hides when I scroll the page. Is there any other setting that could be influencing it? How to disable it?

```text
$ pip3 show mkdocs mkdocs-material | grep '\(Name\|Version\)'
Name: mkdocs
Version: 1.2.3
Name: mkdocs-material
Version: 8.1.4
```

This is the relevant `mkdocs.yml` excerpt:

```yml
theme:
  name: material
  palette:
    accent: indigo
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - toc.follow

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: '#'
      baselevel: 1
      separator: '-'
  - admonition
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
```
