### DISCUSSION TITLE
How to use colorised highlights for JSON?

### DISCUSSION THREAD

**Discussion by thim81** [squidfunk/mkdocs-material#3589] [Q&A] [answered]
I wonder what configuration is needed to show JSON code examples in a nicely coloured manner.
Example:

```
### Event data

```json
{
  "data": {
    "owner": {
      "accountId": "3822afb319684af18b9664ee327b7c44",
      "tenantId": "1"
    },
    "route": {
      "localIpPort": 5025
   }
}
```

Results in a page rendered like this:
Current JSON colours:
![2022-02-17 at 16 33 38](https://user-images.githubusercontent.com/952446/154515255-410435e8-6d48-46b1-89ce-2abd6a536cdf.png)

While on the Material documentation website the JSON examples are showing this nice colouring:
![2022-02-17 at 16 33 17](https://user-images.githubusercontent.com/952446/154515133-a8a96d92-5bf3-4a13-9a91-7aceb60b0ad5.png)

**Comment by squidfunk** [comment, marked as answer]
You need to enable a [combination of extensions](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#configuration) in `mkdocs.yml`:

``` yaml
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
```
