### DISCUSSION TITLE
How to add admonitions to an ordered list?

### DISCUSSION THREAD

**Discussion by vjmanda** [squidfunk/mkdocs-material#3763] [Q&A] [answered]
Adding admonitions to ordered list doesn't render properly if its indented under the the list item. Removing the indentation makes it render properly but it breaks the ordered list sequencing.

I am trying to do something like this.

```
1. Step one.

!!! info
    Some info.

1. Step two.

!!! info
    Some more info.

1. Step three.

1. Step four.
```

**Comment by squidfunk** [comment]
List item content must be indented by four spaces:

```
1. Step one.

    !!! info
        Some info.

1. Step two.

    !!! info
        Some more info.
```

**Reply by vjmanda** [reply]
> List item content must be indented by four spaces:
> 
> ```
> 1. Step one.
> 
>     !!! info
>         Some info.
> 
> 1. Step two.
> 
>     !!! info
>         Some more info.
> ```

I agree but the admonitions don't render the blocks properly if you indent them. They show as plain text instead.

**Reply by squidfunk** [reply]
Make sure you have SuperFences enabled. The [recommended configuration](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#configuration) for using admonitions is:

``` yaml
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
```

**Comment by segfaultxavi** [comment]
I am encountering the same issue. No amount of indenting allows me to show the admonition when it's inside a list. It renders as plain text.

My source:
```markdown
1. List item

    !!! info
        Help.
```

Renders as:
![image](https://user-images.githubusercontent.com/10949043/170691956-7fc59069-20d6-4419-9b9c-90036afb18f3.png)

Versions from `requirements.txt`:
``` python
mkdocs==1.2.4
mkdocs-material==8.1.11
mkdocs-material-extensions==1.0.3
mkdocs-git-revision-date-plugin==0.3.1
mkdocs-autolinks-plugin==0.5.0
mkdocs-redirects==1.0.4
mdx-truly-sane-lists==1.2
jinja2==3.1
```

Relevant portion of `mkdocs.yml`:
```yaml
theme:
  name: material
  custom_dir: docs/assets/overrides
  palette:
    scheme: default
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs           # Top-level pages are shown as tabs on the header
    - navigation.tabs.sticky    # Navigation tabs are always visible
    - navigation.top            # "Back to top" button appears upon upward scrolling
    - navigation.indexes        # Allow section headers to have a page (see tech/index.md)
markdown_extensions:
  - admonition                  # Info boxes (in different colors)
  - pymdownx.details            # "
  - pymdownx.superfences        # Info boxes, tabs
  - pymdownx.caret              # Allow superscript and insertion marks (^ and ^^)
  - pymdownx.tilde              # Allow subscript and deletion marks (~ and ~~)
  - pymdownx.keys               # Allow Keyboard marks (++)
  - pymdownx.mark               # Allow selection marks (==)
  - pymdownx.inlinehilite       # Syntax-highlight inline code
  - pymdownx.tabbed:            # Tabbed content
      alternate_style: true
  - toc:                        # TOC control
      permalink: 🖈             # Add permalinks to headers
  - pymdownx.arithmatex:        # Math blocks
      generic: true
  - mdx_truly_sane_lists        # 2-space indented nested lists
  - attr_list                   # { Annotations }
  - md_in_html                  # Markdown inside HTML
  - def_list                    # Definition lists (Glossary)
plugins:
  - search                      # Search box at the top
  - git-revision-date           # Last edit timestamp at the bottom
  - autolinks                   # Use just filenames instead of full or relative paths
```
