### DISCUSSION TITLE
Custom font for menubar / headings ?

### DISCUSSION THREAD

**Discussion by Ishan95014** [squidfunk/mkdocs-material#3806] [Q&A] [answered]
Hello, it says [here](https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/#:~:text=web%20font%20files.-,Customization,-%C2%B6) that "The font can then be applied to specific elements, e.g. only headlines," 
But it is not explained how. Could that explanation be added ? 

Thanks in advance.

**Comment by squidfunk** [comment, marked as answer]
For customizing specific elements, some CSS knowledge is required. The main headline for example can be styled with:

``` css
.md-typeset h1 {
  font-family: "<font>";
}
```

Edited after last comment.

**Reply by Ishan95014** [reply]
Yes, that's what I tried. However it's not working, but I'm not sure why. 
Is it possible to do this using google fonts directly like when defining the typeface in mkdocs.yml ? 
In doubt, I downloaded and linked it locally with @font-face, but it still doesn't apply.
Here's what I have, with the font in the same folder (I'll move it somewhere tidier when I get it to work)

``` css
@font-face {
    font-family: "Staatliches";
    src: "Staatliches-Regular.ttf"}

.md-typeset h1 {
    --md-text-font: "Staatliches";
}
.md-typeset h2 {
    --md-text-font: "Staatliches";
}
```

But everything still displays in the default Ubuntu font.
I feel like I'm missing something obvious.

EDIT: all of that code being in extra.css ; Other modifications, like ```color: green``` work perfectly.

**Reply by Ishan95014** [reply]
In fact, even using web safe fonts doesn't work : 

```css
.md-typeset h1 {
    color: greenyellow;
    --md-text-font: "arial";
}
``` 

<img width="212" alt="image" src="https://user-images.githubusercontent.com/59368580/163729872-38318686-ef55-4a96-a57f-0392443ecaa6.png">

I'm really lost as to what I'm doing wrong here. Additional typefaces aren't marked as being an insider feature, are they ?

**Reply by squidfunk** [reply]
No, typefaces and CSS adjustments are all non-Insiders. I think I must correct my previous code example, and you should just use `font-family: Arial`. You _could_ use `--md-text-font`, but you'd need to use more complicated CSS for that due to how CSS variables work (my mistake), so I guess it's easier to just define `font-family` directly.

**Reply by Ishan95014** [reply]
This works : 
```css
@font-face {
    font-family: "Staatliches";
    src:url(Staatliches-Regular.ttf) ;
}

.md-typeset h1 {
    color: greenyellow;
    font-family: "Staatliches";
}
```
<img width="442" alt="image" src="https://user-images.githubusercontent.com/59368580/163732673-5c021dd3-d234-4aa8-af96-f719189fca41.png">

But only on local using `mkdocs serve` :
I'm using the simple expressJS static server to actually deploy the website and in that case, neither the color (which worked from the start) nor the typeface (which I was just linking to wrong with quotation marks in the `@font-face`) work.
