### DISCUSSION TITLE
Configure security level on mermaid to enable anchor links

### DISCUSSION THREAD

**Discussion by falondarville** [squidfunk/mkdocs-material#3812] [Q&A] [answered]
Hi! I'm using mermaid with mkdocs and trying to successfully anchor link from cells. Right now, anchor links go to `about:blank`.

The solve on the mermaid-side is adding `securityLevel: 'loose'`. See: https://github.com/mermaid-js/mermaid/issues/1218#issuecomment-577893220

I don't see configuration options beyond the following in the mkdocs documentation (in my `mkdocs.yml` file):

```
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
```

Are there additional yml config options? Or have others been using js to workaround this known mermaid issue?
