### DISCUSSION TITLE
Font Awesome Icons Not Appearing

### DISCUSSION THREAD

**Discussion by theory** [squidfunk/mkdocs-material#3828] [Q&A] [answered]
Hi. I'm using the `squidfunk/mkdocs-material:8.2.9` Docker image with emoji enabled like so:

``` yaml
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
```

Emoji like `:thinking:` work fine, but Font Awesome icons like `:fontawesome-regular-face-laugh-wink:` do not. They render as

``` html
<img alt=":fontawesome-solid-database:" class="twemoji" src="https://twemoji.maxcdn.com/v/latest/svg/None.svg" title=":fontawesome-solid-database:">
```

Is there some additional configuration I need to switch on? TIA!

**Comment by squidfunk** [comment]
Possibly related to the recent name changes in FontAwesome v6, see https://github.com/squidfunk/mkdocs-material/discussions/3575

<img width="773" alt="Bildschirmfoto 2022-04-21 um 19 48 35" src="https://user-images.githubusercontent.com/932156/164520353-90ba4214-da8c-494b-a186-9865360f127a.png">

Taken from https://fontawesome.com/docs/web/setup/upgrade/whats-changed#icons-renamed-in-version-6

**Comment by theory** [comment]
Oh is Material using v5? The [docs site](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#using-icons) properly displays  `:fontawesome-regular-face-laugh-wink:`.

**Reply by squidfunk** [reply]
Material is using the [latest version](https://github.com/squidfunk/mkdocs-material/blob/3dfa984248e32bb4c0dd12706435f4adc8ccca36/package.json#L55), so it's an error in the documentation. PR appreciated!

**Reply by theory** [reply]
Very confused. The new v6 `:fontawesome-regular-face-laugh-wink:` syntax works for the Material docs but not for me.

**Comment by squidfunk** [comment, marked as answer]
Wait, I think your configuration is wrong. Try:

``` yaml
- pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg # <- not pymdownx, but materialx
```

Did you copy that somewhere? If so, we should fix the location.
