### DISCUSSION TITLE
github actions not updating gh-pages

### DISCUSSION THREAD

**Discussion by JamesRivers** [squidfunk/mkdocs-material#3858] [Q&A] [answered]
have an action as follows
```
name: versio_grpahics_mkdocs_publish
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install \
              mkdocs-material \
              mkdocs-encryptcontent-plugin \
      - run: mkdocs gh-deploy --force
```
this action is completing no errors. 

items on the gh-pages branch is being updated - but the web pages are not updating at all, cleared caches and waited a few hrs. Why is the gh-pages not reflecting what has recently be edited by a commit?
