### DISCUSSION TITLE
Metatag theme-color not being defined when using the color palette toggle example

### DISCUSSION THREAD

**Discussion by AjaniBilby** [squidfunk/mkdocs-material#3881] [Ideas]
If I just have a static [theme colour](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=palette#primary-color) the correct metatags are generated for every page. However, if you use the [colour palette toggle](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=palette#primary-color) example, no theme colour is generated.

I understand why switching theme colour on the fly based on cached info in the browser could present issues, but it would be nice if the theme colour could be hard set, or if it used the default scheme's primary colour.

**Comment by squidfunk** [comment]
Thanks for reporting. The problem with adding the theme color for the multi-color-palette configuration is that there can only be a single theme color, as it is set during the build (inside HTML). When a user switches to the other color, you would end up with non-matching theme colors. This is the reason why it's not set in this configuration setting and what you already observed.

Additionally, the theme color must be a hex value, and we set color names in `mkdocs.yml`, which makes it even more complicated. We would somehow have to encode both theme colors inside the template, only one being active at a time, somehow tying it to different color palettes. Honestly, nothing I'd want to maintain.

You can use [theme extension](https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme) to add this logic if you feel that it's indispensable for you.

**Reply by AjaniBilby** [reply]
It just seems odd that if I have
```yml
  palette:
    primary: pink
```
It generates the metatag `<meta name="theme-color" content="#e92063">`, so clearly the colour name to hex conversion is in there somewhere, but I presume you're relying on something upstream for that? Otherwise, I don't see why that's an issue worth mentioning.

It just feels like a weird edge case that this doesn't work since the primary colour is the same in both cases
```yml
  palette:
    - scheme: default
      primary: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
```
