### DISCUSSION TITLE
Apply padding to text in ::before admonition object

### DISCUSSION THREAD

**Discussion by Andre601** [squidfunk/mkdocs-material#3905] [Q&A] [answered]
I'm currently adding custom admonition and details for my API docs to mimic the general appearance of the OpenAPI documentation, but in Markdown files for MkDocs.

I'm currently encountering an issue where I would like to add the HTTP method (POST, GET, etc) as the `::before` object of the admonition title, but struggle to get it display properly.
The main issue is that, no matter what I try to set in terms of padding/margin, it has no effect on the `::before` object... At least not on the right side.

This is my current CSS setup:
```css
.md-typeset .admonition.api-post,
.md-typeset details.api-post {
  border-color: rgb(0, 200, 83);
}

.md-typeset .api-post > .admonition-title,
.md-typeset .api-post > summary {
  background-color: rgba(0, 200, 83, 0.1);
}

.md-typeset .api-post > .admonition-title::before,
.md-typeset .api-post > summary::before {
  content: "POST";
  /* These are required to hide the default admonition icon. */
  -webkit-mask-image: none;
          mask-image: none;
  background-color: transparent;
}
```

Example Markdown:
```markdown
!!! api-post "/post"
    Text
```

Result:
![image](https://user-images.githubusercontent.com/11576465/167453487-a5311335-b6cc-461e-80cc-44780c04e5d6.png)

**Comment by Andre601** [comment, marked as answer]
I got a working solution... Not the most pretty or good IMO but it does what I wanted:

```css
.md-typeset .admonition.api-post,
.md-typeset details.api-post {
  border-color: rgb(0, 200, 83);
}

.md-typeset .api-post > .admonition-title,
.md-typeset .api-post > summary {
  background-color: rgba(0, 200, 83, 0.1);
  padding-left: 4rem !important;
  font-size: .9rem;
}

.md-typeset .api-post > .admonition-title::before,
.md-typeset .api-post > summary::before {
  content: "POST";
  -webkit-mask-image: none;
          mask-image: none;
  background-color: transparent;
  top: auto;
}
```

Result:
![image](https://user-images.githubusercontent.com/11576465/167506476-ddae8464-45e8-4636-bf7b-6e6cfef75d73.png)
