### DISCUSSION TITLE
Why does light/dark mode not change when the OS light/dark mode changes?

### DISCUSSION THREAD

**Discussion by erikthiem-immuta** [squidfunk/mkdocs-material#3911] [Q&A] [answered]
I am running into difficulty getting prefers-color-scheme to work based on these directions https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#system-preference

I tried getting this work in an existing app and was not able to see the page change when I switched my computer from light to dark mode. I was, however, able to see many other websites change (such as Google), so I know that my computer is reporting my color scheme preference correctly.

I then thought that maybe the existing app was overriding too many things, so I decided to create a new app with the [getting started instructions](https://squidfunk.github.io/mkdocs-material/getting-started/). I updated the mkdocs.yml file to be this:

```
site_name: My Docs
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo # same as above
      accent: indigo  # same as above
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
```

and I am still not seeing it pick up my system light mode / dark mode preference.

Of note, I am able to manually change the order of those media calls to have the dark mode one first and that _does_ work to set dark mode. So dark mode is working, but automatic detection is not working.

I have used google chrome dev tools to easily toggle my preferences 
![image](https://user-images.githubusercontent.com/88343359/167886988-cf6c6cad-fa2b-4439-af3e-bca8b4d53a42.png)
and I have toggled them via the system preferences. I am using a mac if that matters.

Do you know where I might be going wrong? Thank you!
