### DISCUSSION TITLE
How to render text on new line?

### DISCUSSION THREAD

**Discussion by jaythamke** [squidfunk/mkdocs-material#3913] [Q&A]
Hi,
I want to use markdown flavor of adding new line in our mkdocs pages.
```
This is a text.  \
Text spills on a new line.
```
I expect after two spaces and backslash (`  \`) and return (hitting Enter key) the text on new line should be rendered on the new line in mkdocs pages (as it does in markdown). However it renders on the same line - `This is a text. \ Text spills on a new line.`.

Indeed mkdocs renders a text on new line after two spaces (without backslash) and return, but many IDEs and git pre-commit hooks complains for additional blank spaces at the end of text.

What could be the workaround for this problem? 

Thanks and regards,
Jayesh

**Comment by facelessuser** [comment]
Let's be clear here. The original Markdown spec uses two spaces to put things on a new line, not two spaces and a `\`.

I do have an extension, that I maintain, that can add newlines with `\` called [EscapeAll](https://facelessuser.github.io/pymdown-extensions/extensions/escapeall/). You just need to enable [`hardbreak`](https://facelessuser.github.io/pymdown-extensions/extensions/escapeall/#options), but then you can force newlines when escaping a newline. Maybe that will get you what you want.

**Reply by jaythamke** [reply]
Thanks for the reply, I tried `escapeall` in our documentation. The mkdocs build stage failed. We have following (similar) text.

```
This is some text. The generation (_i\*XX+1_) is a next generation and the newer generation (_i\*XX+2_) will be advance.
```
This failed mkdocs build and serve stage with error `
ERROR    -  '\*' is not a valid escape sequence. Allowed escape sequences are '\', '|'`

Following text without adjustment.
```
This is some text. The generation (_i*XX+1_) is a next generation and the newer generation (_i*XX+2_) will be advance.

Mkdocs Page Rendering:

This is some text. The generation (iXX+1_) is a next generation and the newer generation (_iXX+2) will be advance.
```

I have following config for mkdocs markdown extn in mkdcs.yml
```
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
    - tables
    - footnotes
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.escapeall:
        hardbreak: true
    - pymdownx.tabbed:
        alternate_style: true
```

Could you suggest the fix?
Thanks
