### DISCUSSION TITLE
Search by Japanese language

### DISCUSSION THREAD

**Discussion by js2ymmks** [squidfunk/mkdocs-material#3916] [Q&A]
I am creating a Japanese documentation site, but the search does not work correctly. It seems that I cannot search for more than three consecutive Japanese characters, although two characters are not a problem. The same is true for other Japanese sites that are already open to the public. I would appreciate any comments.

mkdocs, version 1.3.0
mkdocs-material-8.2.14

**Comment by squidfunk** [comment]
Thanks for asking. Please provide a self-contained, reproducible example.

**Reply by js2ymmks** [reply]
Thank you for your reply.
The code is simple, but the search results are not as expected.
I can't search for more than 3 kanji characters.
I would appreciate your comments.

For example.
防御     OK
防御率  NG

mkdocs.yml
```
site_name: My Docs
theme:
  name: material
  language: ja
  features:
    - search.highlight
plugins:  
  - search: 
      lang: ja
```

index.md
```
# Welcome to MkDocs
## Project 日本語検索

6イニング3自責点は ERA (Earned Run Average＝防御率) にすると 4.5 となり、あまり良いとは言えないように見えるが、2010年シーズン以降の MLB 全体の防御率が 4.08 (2010)、3.94 (2011)、4.01 (2012) であることを見れば、現在でも妥当なラインだと思われる。
```
