### DISCUSSION TITLE
configure hidden page (exclude from navigation)

### DISCUSSION THREAD

**Discussion by lin-ycv** [squidfunk/mkdocs-material#3953] [Q&A] [answered]
is is possible to exclude a page from the navigation why setting some meta option or tag in the md files, it seems like the only option is to explicitly configure the navigationt in mkdocs.yml
If possible, I'd prefer not to make any changes to mkdocs.yml, currently my mkdocs looks like this:

``` yaml
site_name: ...
site_author: ...
site_description: ...
site_url: ...

theme:
  name: material

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Noto Sans
    code: Source Code Pro
  favicon: assets/favicon.png
  logo: assets/logo/logo.svg
  palette:
    - scheme: default
      primary: white
      accent: pink
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tracking
    - content.code.annotate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
  - tables
  - meta
plugins:
    - search
extra:
  generator: false
extra_css:
    - assets/css/util.css
```
this will auto populate the navigation when there's a new file, and that's easy to use
