### DISCUSSION TITLE
My MkDocs page build on Jenkins Pipeline starts default in Dark Mode

### DISCUSSION THREAD

**Discussion by ni-dschiller** [squidfunk/mkdocs-material#4008] [Q&A] [answered]
My MkDocs page build on Jenkins Pipeline starts default in Dark Mode how can i influence which Mode the default one is ?

Here is the Yaml file I use:

### mkdocs.yml
``` yaml
site_name: mysite

theme:
  name: material  # default: material, mkdocs, readthedocs
  custom_dir: overrides
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    # - navigation.expand
    # - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.highlight
    - search.share
    # - header.autohide
  palette:  # Is overwriten by the next `palette` expressions
    primary: teal  # yellow, default: indigo
  palette: 
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  font:
    text: Roboto
    code: Robot Mono
  language: en
  icon:
    logo: material/robot-outline
  # favicon: images/favicon.png

extra:
#   alternate:
#     - name: English
#       link: /en/ 
#       lang: en
#     - name: Deutsch
#       link: /de/
#       lang: de
#   version:
#     provider: mike
  social:
    - icon: fontawesome/brands/slack
      link: https://myslack
      name: Me on Slack
    - icon: fontawesome/solid/paper-plane
      link: mailto:me@comp.org
      name: Send Feedback
  generator: true  # Remove `Made with Material for MkDocs` if `false`

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2022 Company

extra_javascript:
  
  # Sortable tables
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

  # MathJax
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - tags:
      tags_file: indices/tags.md
  - mkdocstrings:
      default_handler: python
      # watch:
        # - src/metrics
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("src")

markdown_extensions:
  
  # Metadata
  - meta
  
  # Abbreviations
  - abbr
  - pymdownx.snippets

  # Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # Annotations - Insider only currently - April 2022
  - attr_list
  - md_in_html
  - pymdownx.superfences

  # Buttons
  - attr_list

  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # Content tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

  # Data tables
  - tables

  # Diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # Formatting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  # Grids - Insider only currently - April 2022
  - attr_list
  - md_in_html

  # Lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  
  # MathJax
  - pymdownx.arithmatex:
      generic: true

  # Icons, Emojis
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
```

**Comment by squidfunk** [comment, marked as answer]
Please see https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#system-preference

> When the user first visits your site, the media queries are evaluated in the order of their definition. The first media query that matches selects the default color palette.

**Comment by ni-dschiller** [comment]
I switched the statements and it still starts as Dark mode.

### mkdocs.yml
``` yaml
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
```
