### DISCUSSION TITLE
Why mermaid.js is not working

### DISCUSSION THREAD

**Discussion by nmnmcc** [squidfunk/mkdocs-material#4049] [Q&A] [answered]
I follow the docs and write these in mkdocs.yml, but mermaid.js is not working.

Maybe it is a bug?

```
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - extra
  - tables
  - smarty
  - toc:
      permalink: true
```
