### DISCUSSION TITLE
Is it possible to caption an aligned image?

### DISCUSSION THREAD

**Discussion by Sonosus** [squidfunk/mkdocs-material#4082] [Q&A] [answered]
I have an image aligned like this:
```
![image2](images/image.jpg){ align=right width=300 }
```
which, as expected, gives an output of:
![image](https://user-images.githubusercontent.com/67963676/177008391-9959b092-6448-48a9-bc68-d17f937f4849.png)
I'd like to insert a caption under this image to give more context. I've tried using:
```
<figure markdown>
![image7](images/3340breakout-module-01.jpg){ align=right width=300 } 
<figcaption>An assembled 'base' PCB</figcaption>
</figure>
```
however this ignores the alignment and slaps the image back into the centre of the page:
![image](https://user-images.githubusercontent.com/67963676/177008506-5e53e531-7656-4933-9971-2654c8be825f.png)
Is there any way to insert an aligned caption?

My markdown_extensions are below:
```
markdown_extensions:
    - toc:
        permalink: "%"
        permalink: True
    - tables
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true 
    - admonition
    - pymdownx.details
    - attr_list
    - md_in_html
```

TIA for any advice and thanks for all your work on this amazing project!
