### DISCUSSION TITLE
Navigation Tabs Colors

### DISCUSSION THREAD

**Discussion by andynameistaken** [squidfunk/mkdocs-material#4122] [Q&A] [answered]
Hi is it possible to manually set different color for navigation tabs for light and dark theme?

**Comment by squidfunk** [comment, marked as answer]
Sure, just scope your styles accordingly:

``` css
/* Default, light theme */
.md-tabs {
  background-color: red;
}

/* Slate theme */
[data-md-color-scheme=slate] .md-tabs {
  background-color: green;
}
```
