### DISCUSSION TITLE
Gradient color for header

### DISCUSSION THREAD

**Discussion by chabErch** [squidfunk/mkdocs-material#4123] [Q&A] [answered]
Is it possible to set gradient color to header?

I try to do it through `background-color` variable, but this property doesn't work with gradient

```css
:root > * {
  --md-primary-fg-color: linear-gradient(135deg, #FF007B 0%, #EE82EE 50%, #20F3FA 100%);
}
```

**Comment by squidfunk** [comment, marked as answer]
For what I know, [OpenFaaS](https://docs.openfaas.com/) uses a gradient color for its header. I recommend checking out their custom CSS 😊

**Comment by chabErch** [comment]
```css
.md-header {
    background: linear-gradient(45deg, rgb(53, 112, 227) 0%, rgb(53, 112, 227) 24%, rgb(42, 125, 227) 53%, rgb(27, 141, 226) 78%, rgb(8, 162, 225) 100%);
}
```
