### DISCUSSION TITLE
Cookie banner settings

### DISCUSSION THREAD

**Discussion by syeda-git** [squidfunk/mkdocs-material#4174] [Q&A] [answered]
Hello,
From the documentation, it seems that everyone can use the default cookie settings. If that's not the case, let me know.

I have these settings in my yaml file. However, the cookie banner is not rendered.

```
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HCL-TECH-SOFTWARE
  version:
    provider: mike
  
  consent:
    title: Cookie consent
    description: Hey there! Welcome to my cookie consent banner.
    cookies:
      analytics: 
        provider: google
        property: UA-169645537-2
    actions:
        - accept
        - manage
  ```

**Comment by squidfunk** [comment, marked as answer]
Your configuration is wrong. `analytics` must be on the top-level of `extra`:

``` yaml
extra:
  analytics: 
    provider: google
    property: UA-169645537-2
  consent:
    title: Cookie consent
    description: Hey there! Welcome to my cookie consent banner.
    actions:
      - accept
      - manage
```
