### DISCUSSION TITLE
Extra.css seems to have no effect

### DISCUSSION THREAD

**Discussion by creytensp** [squidfunk/mkdocs-material#4228] [Q&A] [answered]
As described I added a stylesheet dir + extra.css and included in mkdocs.yml.
However adding css does not seem to have any effect coz I want to add a border to the screenshots part of the docu set.
img { display: block;border: 1px solid black;}

I am using version 8.3.9.

Suggestions?

SOLVED: indent in mkdocs.yml

**Comment by squidfunk** [comment]
This is likely a CSS specificity issue. Try something like:

``` css
.md-typeset img {
  display: block;
  border: 1px solid black;
}
```
