### DISCUSSION TITLE
Is there anyway to flat nav level

### DISCUSSION THREAD

**Discussion by NamekMaster** [squidfunk/mkdocs-material#4233] [Q&A] [answered]
Enable tabs make mkdocs render pages from second level. Is is possible if I want it render from third level ?
For example,
```
nav:
  - group1:
     - folder:
        - page1: page1.md
  - group2:
     - folder:
        - page1: page1.md
```
I'd like to override default tabs with multiple level dropdown, and I need mkdocs render start from page1 level.
Totally two things:
1. The tabs become from `group1, group2` to `group1->folder, group2->folder`, that could implement by overriding tabs block.
2. The content of page1 rendered without the `folder` section, I didn't find anyway to do this.
