### DISCUSSION TITLE
Code Block

### DISCUSSION THREAD

**Discussion by prashantdwivedi** [squidfunk/mkdocs-material#4271] [General]
Hi squidfunk,

Please help me to understand to solve that `issue` I use that.
```md
#extenstions
markdown_extensions:
 - pymdownx.superfences
```
to achieve that

<img width="807" alt="CleanShot 2022-08-22 at 18 08 20@2x" src="https://user-images.githubusercontent.com/6306052/185923022-df23e7d9-6ae3-4035-b27b-f2a822df9673.png">

But I do not need to `heading` which shows `bash.`

---
I `Achieve` what I need with `Custom-CSS.` 

<img width="799" alt="CleanShot 2022-08-22 at 18 25 55@2x" src="https://user-images.githubusercontent.com/6306052/185926607-763f4c48-5662-4274-96f1-7954430887a3.png">

```CSS
  /* Codeblock-customize */
  .highlight span.filename {display: none !important;}
  .highlight span.filename+pre>code {margin-top: 1em;}
  .md-clipboard {top: 1.4em;} 
```
Is there any `best way` to to-do without disturbing 😳 `CSS`?
