### DISCUSSION TITLE
Why is the file always in front of the folder in the auto-generated navigation

### DISCUSSION THREAD

**Discussion by shu307** [squidfunk/mkdocs-material#4280] [Q&A] [answered]
I'm trying to organize auto-generated navigation with numbers.

![QQ截图20220826010138](https://user-images.githubusercontent.com/26036149/186727312-5f076dda-39bf-47e1-bb66-b41dd06fd23b.png)
here is my `mkdocs.yml`
--from google translate

``` yaml
site_name: My Docs
theme:
    name: material
    palette:
        primary: white
    font: false
    language: zh
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.expand

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
```
