### DISCUSSION TITLE
Unclear how to reference  icon for admonition

### DISCUSSION THREAD

**Discussion by valhuber** [squidfunk/mkdocs-material#4293] [General]
@squidfunk -- Love your product.  Using it [here](https://valhuber.github.io/ApiLogicServer/).

Working from [admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#custom-admonitions), I created the structure below.  The icon reference is bad - comes up blank..  can you help?

The `mkdocs.yml` files is at same level as api_logic_server_cli..

<img width="1300" alt="Screen Shot 2022-08-28 at 5 44 59 PM" src="https://user-images.githubusercontent.com/5579631/187102522-16d8505b-277d-46f7-b507-75bab5e64840.png">

**Comment by squidfunk** [comment]
As stated in our [documentation](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#__tabbed_3_1), if you add custom admonition icons this way, you need to reference the entire SVG source in the `url(...)` function. This is necessary so Material for MkDocs can change the fill color of SVGs (e.g. for dark mode). __Excerpt__:

``` css
:root {
  --md-admonition-icon--pied-piper: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">...</svg>')
}
```
