### DISCUSSION TITLE
Website is built differently on gitlab

### DISCUSSION THREAD

**Discussion by botkero** [squidfunk/mkdocs-material#4298] [Q&A] [answered]
hello,

I have a strange bug/behaviour that I can't explain and thought I would ask here.

When I build/test my site locally, everthing looks right.
[correct](https://user-images.githubusercontent.com/105428599/187460596-9e7c74ab-b90a-489f-98b2-6a590408bb81.png)
When I push my site to gitlab and host with gitlab pages, then the formatting of my table is broken.
[wrong](https://user-images.githubusercontent.com/105428599/187460996-2e29b5dd-68f3-4570-bd80-16ae2924904f.png)

```yml
image: python:3.10-buster
before_script:
  - pip install -r requirements.txt

test:
  stage: test
  script:
  - mkdocs build -f project/mkdocs.yml --strict --verbose --site-dir test
  artifacts:
    paths:
    - test
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      changes:
        - "project/docs/**/*"
        - "project/docs/*"

pages:
  stage: deploy
  script:
  - mkdocs build -f project/mkdocs.yml --strict --verbose
  - mv project/site public
  artifacts:
    paths:
    - public
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      changes:
        - "project/docs/**/*"
        - "project/docs/*"
```

The difference lies in the html code in these lines:
correct: `<th align="center">`
wrong: `<th style="text-align: center;">`

But I can't explain why the page is created differently on gitlab.  **btw, I work with a table where the borders are not visible.**

Edit: hi again,

I still havent got the problem fixed, but I wanted to give more input. I have trimmed my page down to the bare minimum and link it here as a download. You can try the page locally and find out that it works and via gitlab ci runner somehow not. The table is then suddenly no longer centred and gets a text align instead. I hope that makes it easier.

[projectproject.zip](https://github.com/squidfunk/mkdocs-material/files/9460744/projectproject.zip)

**Comment by squidfunk** [comment]
I'm not a user of GitLab (I host all my stuff on GitHub), maybe somebody else can help!

**Comment by botkero** [comment, marked as answer]
I have found a workaround for me. I have created a css class and center the images using it. 

```css
.image-in-table {
  margin-left: auto;
  margin-right: auto;
}
```
