### DISCUSSION TITLE
How to search for characters in the document, such as ?

### DISCUSSION THREAD

**Discussion by Leopard20** [squidfunk/mkdocs-material#4326] [Q&A]
In my documentations I'd like to search for characters such as `.` and `?`. But when I type those characters in the search bar no results are returned.
Is it possible to enable this somehow?

**Comment by squidfunk** [comment]
I can search for `?` on our documentation. As always, I'm going to need a fully self-contained minimal reproducible example to look into this. You can attach it here as a zip file. Otherwise, I can only guess what's wrong with your configuration.

![screenshot-squidfunk-github-io-mkdocs-material-1662469182822](https://user-images.githubusercontent.com/932156/188641660-f58b84f7-f4be-4768-8bfa-b3e6f047288a.png)

**Comment by Leopard20** [comment]
Thanks for the reply.

It happens with the basic setup too (I simply ran `mkdocs new test` and updated `mkdocs.yml` to add the material theme)
[test.zip](https://github.com/squidfunk/mkdocs-material/files/9497256/test.zip)

This is my `mkdocs.yml`:
```yaml
site_name: My Docs
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences

plugins:
  - search
  ```
  
  And index.md:
  ```md
  # Welcome to MkDocs

For full documentation visit [mkdocs.org](https://www.mkdocs.org).

## Commands

* `mkdocs new [dir-name]` - Create a new project.
* `mkdocs serve` - Start the live-reloading docs server.
* `mkdocs build` - Build the documentation site.
* `mkdocs -h` - Print help message and exit.

`???`

## Project layout ?

    mkdocs.yml    # The configuration file.
    docs/
        index.md  # The documentation homepage.
        ...       # Other markdown pages, images and other files.
```

Here's a screenshot:
![image](https://user-images.githubusercontent.com/16115820/188645800-f0be78a6-f915-4a2d-be76-7542e7b61696.png)
