### DISCUSSION TITLE
Installing Insiders in GitHub workflow

### DISCUSSION THREAD

**Discussion by sccmcca** [squidfunk/mkdocs-material#4350] [Q&A]
I'd like to install MkDocs Material Insiders as part of my deployment workflow. I've set up the token as an environment variable. Here is my code for `deploy.yml`:

```
name: build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
        env:
          MKDOCS_TOKEN: ${{ secrets.MKDOCS_TOKEN }}
      - run: pip install -r requirements.txt
      - run: pip install git+https://${MKDOCS_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
      - run: mkdocs gh-deploy --force --clean --verbose
```

However, the workflow runs with the following error. Any ideas how to get unstuck?

```
Run pip install git+https://${MKDOCS_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
  pip install git+https://${MKDOCS_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/scmcca/gtfs.org/actions/runs/3045839686/jobs/4907899674#step:5:3).10.6/x6[4](https://github.com/scmcca/gtfs.org/actions/runs/3045839686/jobs/4907899674#step:5:4)
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.6/x64/lib
Collecting git+https://****@github.com/squidfunk/mkdocs-material-insiders.git
  Cloning https://****@github.com/squidfunk/mkdocs-material-insiders.git to /tmp/pip-req-build-[5](https://github.com/scmcca/gtfs.org/actions/runs/3045839686/jobs/4907899674#step:5:5)rdwazug
  Running command git clone --filter=blob:none --quiet 'https://****@github.com/squidfunk/mkdocs-material-insiders.git' /tmp/pip-req-build-5rdwazug
  fatal: could not read Username for 'https://github.com/': No such device or address
  error: subprocess-exited-with-error
```
