### DISCUSSION TITLE
Github deployment for dummies?

### DISCUSSION THREAD

**Discussion by nickriches** [squidfunk/mkdocs-material#4353] [Q&A] [answered]
Hi. I am trying to build a course handbook with mkdocs. I have no problem serving and building websites locally, but have spent hours trying to deploy via github. The instructions on mkdocs-material are brief. Has anyone put together a detailed step-by-step guide? Would netlify or gitlab offer a better solution?

Here are my basic steps

(a) Create a repository on github
(b) Clone to my computer (I use github desktop)
(c) Create mkdocs site (e.g. mkdocs new . and mkdocs serve).
(d) Push to origin
(e) Change name of main branch to gh-pages

Thanks.

**Comment by nickriches** [comment, marked as answer]
This site seems helpful: https://blog.elmah.io/hosting-a-mkdocs-driven-documentation-site-on-github-pages/

It suggests running gh-deploy main branch, and a gh-pages branch will automatically be created in github.

**Reply by squidfunk** [reply]
The GitHub Actions workflow in the [publishing guide](https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions) is all that is necessary. I'm constantly using this workflow to deploy sites to GitHub Pages. Here it is for reference – just copy and paste it and [create a new workflow](https://docs.github.com/en/actions/quickstart#creating-your-first-workflow), e.g., called `ci.yml`:

``` yaml
name: ci 
on:
  push:
    branches:
      - master 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force
```

> Change name of main branch to gh-pages

You don't need to do that.

> It suggests running gh-deploy main branch, and a gh-pages branch will automatically be created in github.

Yes, that's what `mkdocs gh-deploy` will do.
