### DISCUSSION TITLE
Underline links with minimal customisation

### DISCUSSION THREAD

**Discussion by SoumayaMauthoorMOJ** [squidfunk/mkdocs-material#4376] [Q&A] [answered]
I can easily change the colour of links using extra_css as explained in this section: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors

Is it possible to underline links using a similar approach?

**Comment by SoumayaMauthoorMOJ** [comment, marked as answer]
``` css
.md-typeset a {
  color: #1d70b8;
  text-decoration: underline;
}
```
