### DISCUSSION TITLE
Remove left border on integrated TOC using extra.css

### DISCUSSION THREAD

**Discussion by SoumayaMauthoorMOJ** [squidfunk/mkdocs-material#4380] [Q&A] [answered]
I have integrated my TOC using: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#__tabbed_6_1

Is it possible to remove the sidebar using extra.css and without overriding partials? By sidebar I mean the line that you get on the left of the TOC

**Comment by squidfunk** [comment, marked as answer]
This should work:

``` css
[dir] .md-nav--integrated > .md-nav__list > .md-nav__item--active .md-nav--secondary {
  border: none;
}
```
