### DISCUSSION TITLE
annotations not working

### DISCUSSION THREAD

**Discussion by ibrahimaljalal** [squidfunk/mkdocs-material#4394] [Q&A] [answered]
I am new to materials. I have just tried most of the examples in the Reference part (in "https://squidfunk.github.io/mkdocs-material/reference/).

they worked fine but for some reason the annotation does not work with me.

This is my index.md file:
```Lorem ipsum dolor sit amet, (1) consectetur adipiscing elit.
{ .annotate }

1.  :man_raising_hand: I'm an annotation! I can contain `code`, __formatted
    text__, images, ... basically anything that can be expressed in Markdown.
```

this is my mkdocs.ymlf file:
```
site_name: My Docs

theme:
  name: material

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
```

Other details:

Python version  3.9.12
mkdocs version 1.3.1
mkdocs-material  version 8.5.3

**Comment by squidfunk** [comment, marked as answer]
[Annotations](https://squidfunk.github.io/mkdocs-material/reference/annotations/) are currently only available as part of [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/). You would need to [become a sponsor](https://squidfunk.github.io/mkdocs-material/insiders/#how-to-become-a-sponsor) to use them.

**Reply by ibrahimaljalal** [reply]
Thank you for the clarification.

**Comment by leoyala** [comment]
@squidfunk is it still the case that annotation sare ain INsiders feature? In the [documentation](https://squidfunk.github.io/mkdocs-material/reference/annotations/#using-annotations) this is now marked as a feature from version 9.2.0.

**Reply by alexvoss** [reply]
Hi @leoyala, you can see which features are part of Insiders in the [Insiders section](https://squidfunk.github.io/mkdocs-material/insiders/benefits/) of the documenation, which also traces [funding goals](https://squidfunk.github.io/mkdocs-material/insiders/benefits/#goals) and [features released](https://squidfunk.github.io/mkdocs-material/insiders/benefits/#goals-completed).

**Reply by leoyala** [reply]
Thank you for the clarification @alexvoss :)

**Reply by squidfunk** [reply]
Annotations are generally available since 9.2.0!

**Reply by leoyala** [reply]
In that case, I don't know why it is not working for me. I am using the example from the website. But it is only rendered as plain text. 
```
Lorem ipsum dolor sit amet, (1) consectetur adipiscing elit.
{ .annotate }

1.  :man_raising_hand: I'm an annotation! I can contain `code`, __formatted
    text__, images, ... basically anything that can be expressed in Markdown.
```
And I have added this plugins: 

```yaml
plugins:
  - search
#  - offline
  - glightbox:
      zoomable: true
      draggable: true
  - mknotebooks:
      execute: false
      allow_errors: false
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true
          options:
            docstring_style: google
            show_bases: true
            show_inheritance_diagram: true
  - git-revision-date-localized:
      enable_creation_date: true
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
```

**Reply by alexvoss** [reply]
You could help us investigate the problem by creating a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/). I don't see anything immediately wrong but then I am not that terribly good at doing that and having a working / not working example to run through usually helps.

**Reply by leoyala** [reply]
Hi @alexvoss I tried generating the minima example. But I am getting the error that the info plugin is not installed, but according to the documentation, it should be bilt-in. I am adding below the configuration I am using in `python3.10` and `mkdocs-material==9.5.30`. 

```yaml
site_name: My Docs
nav: 
  - index.md
plugins:
  - info 
  - offline
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
```
