### DISCUSSION TITLE
Make the blog the default page

### DISCUSSION THREAD

**Discussion by Techbrunch** [squidfunk/mkdocs-material#4437] [Q&A] [answered]
Hello,

How I can make the blog the default page ?

**Comment by squidfunk** [comment, marked as answer]
In order to build a standalone blog, set [`blog_dir`](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#__tabbed_1_2) to `.`:

``` yaml
plugins:
  - blog:
      blog_dir: .

```

I recommend reading [this blog post](https://squidfunk.github.io/mkdocs-material/blog/2022/09/12/blog-support-just-landed/) which provides step-by-step instructions how to set up a standalone blog.

**Reply by Techbrunch** [reply]
Thanks but the thing is that I would like to keep the docs but have the blog as the main entrypoint.

**Reply by squidfunk** [reply]
Well, you can just add your other pages to the `nav` section. Other than that, if that doesn't solve your problem, please provide a precise explanation of what you're trying to achieve.

**Reply by squidfunk** [reply]
... or just move the `Blog` section to the top of `nav`, i.e.:

``` yaml
nav:
  - Blog:
    - blog/index.md
  - Foo: foo.md
  - Bar: bar.md
  - ...
```
