### DISCUSSION TITLE
Unable to export fonts

### DISCUSSION THREAD

**Discussion by koshelekapi** [squidfunk/mkdocs-material#4497] [Q&A] [answered]
Hi dear all,
I have faced the problem I can't solve by myself, so I ask for help.
I try to use our corporate fonts on my Mkdocs site.
My steps:
1. I've uploaded them (the .woff2 files) into the `docs/assets/externals/fonts` folder
2. I edited the CSS respectively, but I don't see any needed changes.
You can see the result here: http://shahid.ru/design/ (sorry for Russian page)

Here are my config files:

extra.css:
```
@font-face {
    font-family: 'TT Norms Pro';
    src: url('../externals/fonts/ttNorms/TT_Norms_Pro_Normal.woff2') format(woff2);
    font-weight: normal;
    font-style: normal;
}

:root {
    --md-text-font: 'TT_Norms_Pro';
    --md-code-font: 'TT_Norms_Pro';
p {
    color: black;
    font-size: 0.875em;
    font-family: TT_Norms_Pro;
    font-weight: normal;
}
```
mkdocs.yml:
```
theme:
  name: material
# font: false
  language: ru
  logo: assets/koshelek.png
  features:
    - navigation.sections # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-sections
    - navigation.indexes
```

Please ask if any additional information needed.

Thanks in advance.
