### DISCUSSION TITLE
Prevent refresh page (Postback)

### DISCUSSION THREAD

**Discussion by mehdihadeli** [squidfunk/mkdocs-material#4552] [Q&A] [answered]
Hi,
Is there any way to prevent refresh page when I click on nav links like [docusaurus.io](https://docusaurus.io/docs)

**Comment by squidfunk** [comment, marked as answer]
Yes, that's what [instant loading](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading) is all about. Add the following to `mkdocs.yml`:

``` yaml
theme:
  features:
    - navigation.instant
```
