### DISCUSSION TITLE
How to modify Mermaid CSS

### DISCUSSION THREAD

**Discussion by Vasperous** [squidfunk/mkdocs-material#4582] [Q&A] [answered]
Apologies but what is probably a basic question but I am having a hard time getting my custom CSS for the Mermaid.js support to take.
Here is what I have done:
1. Added custom css files

``` yml
extra_css:
  - stylesheets/admonitions.css
  - stylesheets/extra.css
  - stylesheets/icons.css
  - stylesheets/mermaid.css
```

2. Based on the [Mermaid CSS](https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/javascripts/components/content/code/mermaid/index.css) I added the classes etc. to my own `mermaid.css`
3. Changes are not taking affect

Looking at the inspector I even tried adding things like:

``` css
#__mermaid_0 .note {
    stroke: #0c1e58 !important;
    fill: #0c1e58 !important;
}
```

Even with that I was unsuccessful.  Any advice would be greatly appreciated.
