### DISCUSSION TITLE
Link color not changing with primary one

### DISCUSSION THREAD

**Discussion by leonardehrenfried** [squidfunk/mkdocs-material#4593] [Q&A] [answered]
I have the following problem: my link colour doesn't change with the primary one. It always remains at `indigo`.

![image](https://user-images.githubusercontent.com/151346/199975806-a6294952-9a53-4e6d-bbc5-dc9a049e0805.png)

Here is what my config looks like:

```
theme:
    name: material
    features:
        - navigation.tabs
        - toc.integrate
    palette:
        primary: "light blue"

extra:
    version:
        provider: mike

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
```

From the docs I get the impression that setting the primary would also change the link colors. Is this correct?

If you want to take a look at the deployed HTML, here it is: https://leonardehrenfried.github.io/OpenTripPlanner/dev/

Many thanks for making this theme!
