### DISCUSSION TITLE
Nord dark theme option

### DISCUSSION THREAD

**Discussion by SilentGlasses** [squidfunk/mkdocs-material#4597] [Ideas]
Was looking at dark themes for another project and came across [Nord](https://www.nordtheme.com/), anyway to get a theme for this styling?

I am not a design expert, was trying to overwrite the default colors to see if I could tweak the base dark them but it ended up so sad. 😢

**Comment by squidfunk** [comment]
You can implement a [custom color scheme](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-color-schemes), as described on our documentation, or override some of the colors on the `slate` scheme, but you're going to need some CSS skills at least. As a starter, this overrides the background color on the `slate` scheme:

``` css
[data-md-color-scheme="slate"] {
  --md-default-bg-color: rgb(46, 52, 64); /* <- taken from the nord theme */
}
```
