### DISCUSSION TITLE
Override the header to add a custom button to the end of nav

### DISCUSSION THREAD

**Discussion by zerenxyz** [squidfunk/mkdocs-material#4612] [Q&A] [answered]
I am trying to add a button to the end of the nav bar (far right) a custom button that redirects to a different page, I added it in my mkdocs.yml nav section like so:
```
# Navigation
nav:
  - Home: 'index.md'
  - News:
    - blog/index.md
  - Tutorials:
    - tutorials/index.md
  - Extra:
    - 'Home': 'extra/home.md'
```
I am trying to have the "Extra" nav button separate from the rest of nav items like this screenshot, where "Download" is to the far right.
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/52886201/200528091-5af2ef18-2597-4209-9639-0dcfc07bbaf4.png">

I know this is possible with overrides and CSS, just not sure where to poke or start to actually do it, I looked up at other discussions and im thinking maybe `header.html` but still confused how to target specifically my "Extra" item as it doesnt have custom ID or something.
