### DISCUSSION TITLE
No "Copy To Clipboard" Icon on Code Blocks

### DISCUSSION THREAD

**Discussion by nixliuxin** [squidfunk/mkdocs-material#4627] [Q&A] [answered]
Hi, after configuring the mkdocs.yml as follows, there is still no "Copy To Clipboard" icon on the code blocks. How can I add this function? Thanks!

Screenshot:

![Screenshot 20221112033610](https://user-images.githubusercontent.com/94869423/201466195-3846ff2e-bc42-4c11-a38e-726c3aed516b.png)

Code:

```

extra_css:
  - stylesheets/extra.css
  - 
site_name: Nix Liu Xin is Making (almost) Anything

theme:
  name: material
  custom_dir: mkdocs-material/material
  # custom_dir: overrides

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  # font: 
    # text: Stanley 

    # code: Stanley
  favicon: assets/favicon.png
  icon:
    logo: logo
  
  palette: 
    
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: black
      accent: light green

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: light green

  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.instant
  - navigation.indexes
  - navigation.expand

  - toc.follow
  # - toc.integrate 
  - navigation.top

  - content.code.annotate 
  - content.tooltips

site_dir: h:\BIGFLATNOW Dropbox\01_WORK\HM\harvardsite\people\Nix
# site_dir: ..\harvardsite\people\Nix

plugins:
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: false
      draggable: false
  - tags
  - search
  - privacy:
      external_assets: bundle

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      linenums: true
      linenums_style: pymdownx-inline
      auto_title: true


  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - attr_list
  - md_in_html
  - tables
  - admonition
  - pymdownx.details





```
