### DISCUSSION TITLE
Adding sub categories to blog categories

### DISCUSSION THREAD

**Discussion by zerenxyz** [squidfunk/mkdocs-material#4642] [Ideas]
Hello,

Not sure if this is a planned feature or is already possible but could it be possible to add sub categories to the already existing categories in blogs?

```
- blog:
      blog_dir: blog
      categories_allowed:
        - General
           - Sub category
        - Events
        - Changelog
```
Something like this in the mkdocs.yml maybe or when declaring a blog post to be able to give category and sub category if needed
