### DISCUSSION TITLE
Use file names as blog slugs?

### DISCUSSION THREAD

**Discussion by StarfallProjects** [squidfunk/mkdocs-material#4679] [Q&A] [answered]
Would it be possible to support using a file name as the slug for blog posts? Generally, the full title of a blog post isn't desirable as the slug - you want a slug that has fewer (more focused) words (for [SEO reasons](https://yoast.com/slug/) as well as aesthetics)

Edit: it looks like this should already be possible?

`slug = meta.get("title", headline or file.name)` 

But I'm not seeing how to tell it to use file name in[ the docs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#posts)?

**Comment by squidfunk** [comment, marked as answer]
Duplicate of #4543 (= already supported). This should work:

``` yaml
plugins:
  - blog:
      post_url_format: "{file}"
```

I've actually forgotten to add it to the [docs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#+blog.post_url_format) 🤦‍♂️

__Edit__: Updated docs in cdfd06860.

**Reply by squidfunk** [reply]
For completeness, note that this can also be combined with `date` and custom date formats:

``` yaml
plugins:
  - blog:
      post_url_date_format: yyyy
      post_url_format: "{date}/{file}"
```

This will generate URLs like `2022/file-name-of-blog-post/`
