### DISCUSSION TITLE
How to disable converting non-english header links to numbers?

### DISCUSSION THREAD

**Discussion by lua-rocks** [squidfunk/mkdocs-material#4682] [Q&A] [answered]
If I have a header like this:

```markdown
# Оглавление
```

the link to this header will be broken:

```markdown
[Link](index.md#оглавление)
```

because MkDocs will convert it to `#_1`.

Is it possible to disable this behavior? Thanks.

**Comment by squidfunk** [comment, marked as answer]
For non-ASCII languages, it's a good idea to use a [Unicode-aware slugify function](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#+toc.slugify):

``` yaml
markdown_extensions:
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
```
