### DISCUSSION TITLE
Organizing Tabs so they don't have to be alphabetical.

### DISCUSSION THREAD

**Discussion by z3thon** [squidfunk/mkdocs-material#4699] [Q&A] [answered]
Trying to organize the navigation on my website. I would like to organize the order of the tabs on my website (not in alphabetical) but I can't seem to get the syntax right under the nav: section of my mkdocs.yml

![68747470733a2f2f66696c65732e6769747465722e696d2f3538663239373432643733343038636534663538613866642f346c71792f7468756d622f53637265656e2d53686f742d323032322d31322d30312d61742d342e32392e32342d504d2e706e67](https://user-images.githubusercontent.com/18201884/205017626-990bb565-23da-4617-be8a-133b20f3d794.png)

As shown in the image above I am doing my best to follow the documentation in https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages

```
nav:
  - Section:
    - section/index.md
    - Page 1: section/page-1.md
    ...
    - Page n: section/page-n.md
```

I can't get my tabs to load in a specific order and still load navigation column on the left hand side of the page.
If I specify an ordering for the tabs then the left-hand column goes away and I can't see it anymore.

I can't figure out I the is a syntax problem or if it's simply not supported without an additional plugin?

**Comment by z3thon** [comment]
![Screen Shot 2022-12-01 at 4 39 51 PM](https://user-images.githubusercontent.com/18201884/205019027-fab61551-3753-462a-8816-541e6a84402c.png)

Even the documentation site has a custom order of the tabs that is not alphabetical but the column nav bar on the left hand side is left in alphabetical order. This is what I would like to achieve.

**Reply by squidfunk** [reply]
The sidebar is almost in alphabetical order. We list them out explicitly in the [`nav`](https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml#L153) section.

**Comment by squidfunk** [comment]
What do you mean with "it goes away"? It doesn't host any content? If there's only a single page behind a tab (e.g. for __Home__), there will be no content, since there's nothing to render. The sidebar only contains the pages that are below the current section/tab.

**Reply by z3thon** [reply]
https://sightline.docs.lztek.io/en/

In the current site I lose all of pages that would normally be on the left hand side when I try to use the feature of organizing my tabs in the nav: part of the .yml document.

**Reply by z3thon** [reply]
![Screen Shot 2022-12-01 at 4 59 39 PM](https://user-images.githubusercontent.com/18201884/205023766-c4e4a821-fd52-4543-9725-18298232bd2b.png)

**Reply by z3thon** [reply]
I'm just trying to get the syntax for the nav: section right. I'm clearly doing something wrong for it to completely remove everything.

Here's my .yml file:

```
site_name: Sightline Docs

# Remove these two to go back to no languages.
docs_dir: '../../docs/en'
site_dir: '../../en'

theme:
  name: material
  custom_dir: '../../overrides'
  favicon: assets/images/favicon.ico
  logo: assets/images/Sightline_SL_Blue.png
  language: en
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: light blue
      toggle: 
        icon: material/brightness-7
        name: Switch to dark mode
      

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: light blue
      toggle: 
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Montserrat

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - toc.follow
    - navigation.top

extra_css:
  - assets/stylesheets/main.min.css
  - assets/stylesheets/palette.min.css

copyright: Copyright &copy; 2022 LZTEK, LLC

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/lzteknology
    - icon: fontawesome/brands/discord
      link: https://discord.gg/zNCZnKNXEv
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/lztek/

# Remove this extra section to go back to no languages.
  alternate:

    # English
    - name: English
      link: /en/ 
      lang: en

    # Spanish
    - name: Español
      link: /es/
      lang: es

plugins:
  - search:
      lang: en

nav:
  - Home:
    - index.md
  - Basics:
    - Basics/0 Welcome.md
    ...
    - Basics/7 Report Field Types.md
  - Setup:
    - Setup/0 Welcome.md
    ...
    - Setup/5 Production.md
  - Permissions:
    - Permissions/0 Welcome.md
    ...
    - Permissions/2 Users.md
  - Plans:
    - Plans/0 | Welcome.md
    ...
    - Plans/5 | Production/Creating Resource Plans.md
```

**Reply by z3thon** [reply]
I'm starting to make some progress. I removed the ... stuff and now I can get some of it to load.
I still don't know how to section the left column with bold letter sections but not add those pieces to the list of tabs up at the top of the page.

**Reply by squidfunk** [reply]
You need to enable [`navigation.sections`](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-sections).

**Reply by squidfunk** [reply]
In general, please read our documentation on [setting up navigation](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/). It contains screenshots with on/off comparisons for all features when they are enabled and disabled. All features are documented...

**Reply by z3thon** [reply]
I think I've got it!
I'm gonna try out a couple different things with the syntax.
Because I'm using multiple languages my deployment time takes a little while so it's hard to test and iterate quickly.

I think I prefer the "drop downs" instead of the bold sections as things grow.

Thanks for the help. The syntax was (and still is) the most confusing part when you have a file tree bigger than a couple files.

**Reply by squidfunk** [reply]
I strongly recommend to set up [configuration validation](https://squidfunk.github.io/mkdocs-material/creating-your-site/#configuration), so you can catch errors more quickly.

**Comment by z3thon** [comment, marked as answer]
Here is the finished product of the formatting that you need to use with the nav: section of your mkdocs.yml to get everything working as intended.

```
nav:
  - Home:
    - index.md #This is the first page you land on when you visit "Home"
  - Basics: #This is a tab on my page as I'm using the tabs feature for navigation.
    - Basics/0 Welcome.md #This is the first page you land on when you visit "Basics"
    - Basics/1 How to Navigate in Quickbase.md
    - Basics/2 Apps & Tables.md
    - Basics/3 Table Reports and Exporting Reports.md
    - Basics/4 Forms and Records.md
    - Basics/5 Dashboards.md
    - Basics/6 Becoming Efficient in QB.md
    - Basics/7 Report Field Types.md
  - Setup: #This is a tab on my page as I'm using the tabs feature for navigation.
    - Setup/0 Welcome.md #This is the first page you land on when you visit "Setup"
    - Setup/1 HR Manager.md
    - Setup/2 Product & Inventory.md
    - Setup/3 Equipment Manager.md
    - Setup/4 Quality Center.md
    - Setup/5 Production.md
    - Users & Permissions: #Drop-Down
      - Users/Adding a User.md #This is a file under the "Users & Permissions" drop-down.
      - Users/User Permissions.md #This is a file under the "Users & Permissions" drop-down.
      - Users/Cost of Each User.md #This is a file under the "Users & Permissions" drop-down.
  - Plans: #This is a tab on my page as I'm using the tabs feature for navigation.
    - Plans/Explore.md #This is the first page that you land on when you visit "Plans"
    - 1 | HR Manager: #Drop-Down
      - Plans/1 | HR Manager/How to Add an Employee.md #This is a file under the "HR Manager" drop-down.
    - 2 | Product & Inventory: #Drop-Down
      - Plans/2 | Product & Inventory/How to Add an Element.md #This is a file under the "Product & Inventory" drop-down.
    - 3 | Equipment Manager: #Drop-Down
      - Plans/3 | Equipment Manager/Equipment Feed KB.md #This is a file under the "Equipment Manager" drop-down.
    - 4 | Quality Center: #Drop-Down
      - Plans/4 | Quality Center/How to Build a Test Template.md #This is a file under the "Quality Center" drop-down.
    - 5 | Production: #Drop-Down
      - Plans/5 | Production/Creating Resource Plans.md #This is a file under the "Production" drop-down.
```
