### DISCUSSION TITLE
After using sections, the original article directory is messed up

### DISCUSSION THREAD

**Discussion by chuycy** [squidfunk/mkdocs-material#4750] [Q&A]
After using sections, my directory groups are mixed together, and the original Chinese title becomes an English title.

**Q1**  Add sections, some directory groups are invalid.
For example: the directory "我是一" has expired, and all the articles contained in it are displayed without grouping.
<img width="665" alt="image" src="https://user-images.githubusercontent.com/110001761/207041741-ce237a36-e9b1-45f6-9722-107dbcd9b456.png">

**Q2**  If my secondary directory is a folder, after adding sections, the Chinese title of the original secondary directory becomes the English title, and the order of the directories is also disrupted.
<img width="692" alt="image" src="https://user-images.githubusercontent.com/110001761/207041991-0b4f87dc-c29e-4739-b33a-30680b7dcf4b.png">

**mkdocs.yml**
<img width="380" alt="image" src="https://user-images.githubusercontent.com/110001761/207042194-79f81b59-a549-49dc-a498-ba05c1d4fc52.png">

**Looking forward to your reply ! Thanks !**

**Comment by squidfunk** [comment]
In order to look into this, I need you to provide a self-contained reproducible example _without_ the awesome-pages-plugin and attach it here as a zip file. It might either be related to the plugin or to Material for MkDocs, which is the first thing we need to understand.

**Reply by chuycy** [reply]
I made two demos for your convenience. But the file size exceeds the upload limit. Is there any other way to send it to you?
Thank you!

**Reply by squidfunk** [reply]
No, we need a _minimal_ example. As I said, you need to remove everything that is not necessary. When giving user support, we don't have the time to look through hundreds of files. Also, you _must_ remove the awesome pages plugin, to make sure it's not caused by the plugin.

**Reply by chuycy** [reply]
got it.Please check the attachment, thanks!
[test-without-sections.zip](https://github.com/squidfunk/mkdocs-material/files/10210947/test-without-sections.zip)

[test-with-sections.zip](https://github.com/squidfunk/mkdocs-material/files/10210946/test-with-sections.zip)

**Reply by squidfunk** [reply]
Again, this is not a minimal example. For comparison, this is your MkDocs config:

``` yaml
site_name: test-with-sections
docs_dir: "./docs/zh"
site_dir: "./site/zh"

theme:
  palette:
    primary: white
  name: material
  custom_dir: overrides/
  favicon: assets/images/favicon.ico
  logo: assets/images/logo.png
  language: zh
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.suggest
    - toc.follow
    - content.tabs.link

markdown_extensions:
  tables: {}
  footnotes: {}
  attr_list: {}
  md_in_html: {}
  toc:
      permalink: True
  meta: {}
  pymdownx.caret: {}
  pymdownx.mark: {}
  pymdownx.tilde: {}
  pymdownx.betterem: {}
  pymdownx.critic: {}
  pymdownx.keys: {}
  pymdownx.snippets: {}
  pymdownx.details: {}
  pymdownx.tabbed:
      alternate_style: true
  pymdownx.highlight:
      anchor_linenums: true
      auto_title: false
      linenums: false
  pymdownx.inlinehilite: {}
  pymdownx.superfences: {}
  pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons


  # 暂时不开放语言切换入口
  # alternate:
  #   - name: 中文
  #     link: /
  #     lang: zh
  #   - name: English
  #     link: /en/
  #     lang: en

plugins:
  awesome-pages: {}
  section-index: {}
  git-authors: {}
  git-revision-date-localized:
    type: custom
    custom_format: '%Y-%m-%d'
    enable_creation_date: true
    fallback_to_build_date: true
  search:
    separator: '[\s\u200b\-]'

extra_css:
  - assets/stylesheets/extra.css
```

I'm afraid with this big of an example, I'm unable to look into it. Please remove _all_ plugins that are not native to Material for MkDocs, all pages that are not necessary, etc. Then, I'm happy to look into it. The reason is that the error can come from anywhere, and I suspect it has to do with the awesome pages plugin, but there's no way to be sure without a minimal example. Thank you.

**Reply by chuycy** [reply]
I'm so sorry.I have cleared unnecessary settings as you suggested. 

This is the new `mkdocs.yml` I submitted this time.Do you see if it is ok? 

Thanks a lot! : )

[question of sections.zip](https://github.com/squidfunk/mkdocs-material/files/10213464/question.of.sections.zip)


```yml
site_name: test-with-sections

theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.sections

plugins:
  awesome-pages: {}
  section-index: {}
```

**Reply by chuycy** [reply]
Without the _awesome-pages-plugin_ , _navigation.sections_ seem to be invalid.
[question of sections-without awesome pages.zip](https://github.com/squidfunk/mkdocs-material/files/10213699/question.of.sections-without.awesome.pages.zip)
```yml
site_name: test-with-sections

theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.sections

plugins:
  section-index: {}
```

**What I effect is:**
<img width="204" alt="image" src="https://user-images.githubusercontent.com/110001761/207212121-a55f3d99-fc7f-4c44-a53d-0194428214f1.png">
<img width="195" alt="image" src="https://user-images.githubusercontent.com/110001761/207212301-99c6f038-4c30-4278-ba83-f0030555a0bf.png">

**But now, with _navigation.sections_ and _awesome-pages-plugin_, it is:**
<img width="402" alt="image" src="https://user-images.githubusercontent.com/110001761/207212586-ca727521-2b34-4f4f-8a2d-6205b2cc6672.png">

**But now, with _navigation.sections_ and without _awesome-pages-plugin_, it is:(_navigation.sections_ seem to be invalid)**
<img width="411" alt="image" src="https://user-images.githubusercontent.com/110001761/207213118-dfeb6524-5d45-4388-a0f6-20a6e124c42b.png">
