### DISCUSSION TITLE
how to make all links open in a new tab

### DISCUSSION THREAD

**Discussion by nh916** [squidfunk/mkdocs-material#4753] [Q&A]
Is there a configuration that I can add that can open all links in a new tab?

**Comment by squidfunk** [comment]
All links? Even internal ones? You probably mean all external links, right? If so, the [privacy plugin](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#built-in-privacy-plugin) supports adding attributes to all external links via the [`external_links_attr_map`](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#+privacy.external_links_attr_map) setting:

``` yaml
plugins:
  - privacy:
      external_links_attr_map:
        target: _blank
```

Note that the privacy plugin is currently reserved to [sponsors](https://squidfunk.github.io/mkdocs-material/insiders/).
