### DISCUSSION TITLE
When using mike for versioning, what should the github actions workflow look like?

### DISCUSSION THREAD

**Discussion by adambirds** [squidfunk/mkdocs-material#4759] [Q&A] [answered]
When using mike for versioning, what should the github actions workflow look like?

I couldn't find this documented anywhere.

**Comment by squidfunk** [comment]
I have no example, since we're not using it for the official docs, but you could just search on GitHub for something like [`mike deploy`](https://github.com/search?l=YAML&q=mike+deploy&type=Code), to learn how other users do that. It shouldn't be too hard, since you basically just have to extract the current tag/release name and use that for publishing instead of `mkdocs gh-deploy`.

Feel free to come back here and share your final GitHub Actions workflow.

**Reply by adambirds** [reply]
Thanks, shared below and marked as answered.

**Reply by squidfunk** [reply]
Thanks for sharing!

**Comment by adambirds** [comment, marked as answer]
I ended up figuring it out and using the below CI files:

**Develop Docs** - Updates on every push to which ever branch contains the latest development, in my case that's main.

```yaml
name: Build/Publish Develop Docs 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
      - name: Install Dependencies
        run: |
          pip install mkdocs-material
          pip install pillow cairosvg mike
      - name: Setup Docs Deploy
        run: |
          git config --global user.name "Docs Deploy"
          git config --global user.email "docs.deploy@example.co.uk"
      - name: Build Docs Website
        run: mike deploy --push develop
```

**Release Docs** - Creates the permanent docs for each release:

```yaml
name: Build/Publish Latest Release Docs

on:
  release:
    types: [published]

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
      - name: Install Dependencies
        run: |
          pip install mkdocs-material
          pip install pillow cairosvg mike
      - name: Setup Docs Deploy
        run: |
          git config --global user.name "Docs Deploy"
          git config --global user.email "docs.deploy@example.co.uk"
      - name: Build Docs Website
        run: mike deploy --push --update-aliases ${{ github.event.release.tag_name }} latest
```
