### DISCUSSION TITLE
How to make linked content tabs work

### DISCUSSION THREAD

**Discussion by xihajun** [squidfunk/mkdocs-material#4788] [Q&A] [answered]
Content tabs are linked based on their label, not offset. This means that all tabs with the same label will be activated when a user clicks a content tab regardless of order inside a container.

**Does the label means the title of the tab for example in here we have C and C++?**
=== "C"

    ``` c
    #include <stdio.h>

    int main(void) {
      printf("Hello world!\n");
      return 0;
    }
    ```

=== "C++"

    ``` c++
    #include <iostream>

    int main(void) {
      std::cout << "Hello world!" << std::endl;
      return 0;
    }
    ```

**Or do we need to set something special?** I cannot find an example from the document page.

**Comment by squidfunk** [comment, marked as answer]
Did you enable [content tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#configuration) and [linked content tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#linked-content-tabs) in `mkdocs.yml`? These settings must be present:

``` yaml
theme:
  features:
    - content.tabs.link
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
```

**Reply by xihajun** [reply]
Thanks for your reply!  Yes, I have them. But I have some additional settings, do you think that would make things different?

```
theme:
  custom_dir: overrides
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - toc.follow
    - content.tabs.link
```


```
markdown_extensions:
- pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.tabbed:
    alternate_style: true 
```
