### DISCUSSION TITLE
blog header modification

### DISCUSSION THREAD

**Discussion by 14mC4** [squidfunk/mkdocs-material#4799] [Q&A]
Anyone got a way to possibly make this below possible? I want to make the header logo bigger and move it to the number 2. I tried a couple CSS modifications w/ Partials but, cant seem to get it correct. Pretty much using most defaults. Any help is appreciated.  
![2022-12-23 22_45_23-Window](https://user-images.githubusercontent.com/25674713/209420144-3e7f8f68-4745-4662-9bbf-435062de3452.png)

**Comment by squidfunk** [comment]
I took the time and fiddled around, and yes, it's possible:

``` css
@media (min-width: 76.25em) {
  .md-header__button.md-logo {
    position: absolute;
    top: 0;
    margin-left: -4.4rem;
  }
  .md-header .md-grid {
    padding-left: 4.8rem;
  }
  .md-header__button.md-logo svg {
    height: 3.6rem !important; /* <-- see comment below */
  }
  .md-header__title {
    margin-left: .8rem !important; /* <-- see comment below */
  }
}
```

__Result__:

<img width="582" alt="Bildschirmfoto 2022-12-27 um 10 11 04" src="https://user-images.githubusercontent.com/932156/209642702-21e1efd4-bd33-4a8e-9901-8c5214d369f0.png">

It doesn't look very nice with our logo, though, but might work for others. Note that I used `!important` to simplify overriding, as this became more complicated in v8. In v9, those `!important` modifiers can be dropped again. It can also be done without them already, but it's more complicated, so using them and dropping them in v9 is simpler.

Also note that for this to work, [`navigation.tabs.sticky`](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#sticky-navigation-tabs) must be enabled. It will not work when tabs are hiding.
