### DISCUSSION TITLE
How to hide buttons for code actions on specific page?

### DISCUSSION THREAD

**Discussion by pulkitkrishna00** [squidfunk/mkdocs-material#4844] [Q&A] [answered]
I want to hide the code actions button on my homepage. How to do so?

**Comment by squidfunk** [comment, marked as answer]
You can use CSS. Include this in your Markdown file for the homepage:

``` css
<style>
  .md-content__button {
    display: none;
  }
</style>
```
