### DISCUSSION TITLE
Can you access data from individual data files, rather than storing data in the mkdocs.yml config?

### DISCUSSION THREAD

**Discussion by chrisdburr** [squidfunk/mkdocs-material#4862] [Q&A] [answered]
Apologies in advance for the beginner question. I have looked through the documentation, and have stumbled my way to a partial solution, but it would be really helpful to get some steer/guidance on this:

I would like to create a simple image gallery, and have set up a template that extends `base.html`. I would like this template to iterate over a set of images stored in a yaml file, but cannot seem to get this to work. 

So far, the closest I have come to the solution I have in mind is the following:

```html
{% extends "base.html" %} 

{% block content %} 
{{ super() }}     

    {% for item in config.images %}
        <h1>{{ item.title }}</h1>
        <figure>
          <img src="{{ item.url }}" style="width:100%">
          <figcaption> {{ item.caption }} </figcaption>
        </figure> 
    {% endfor %}

{% endblock %} 
```

This works, but it requires me to store the data in the mkdocs.yml config, which is not ideal:

```yaml

site_name: Test Site

theme: 
  name: material
  custom_dir: overrides

images:
  - title: "Image Title 1"
    tags:
      - tag 1
      - tag 2
    image_url: "https://example.com"
    caption: "An image caption."
  - title: "Image Title 2"
    tags:
      - tag 1
      - tag 2
    image_url: "https://example.com"
    caption: "An image caption."
```

A couple of questions:

1. Is it possible to move the data to a separate `yaml` file?
2. If so, are there restrictions on where it needs to be located and any adjustements I need to make to the site's config file?
3. And, finally, what variables would I use in the content block instead of the global `config.variable` ones when iterating over the dataset?
