### DISCUSSION TITLE
How can I override the theme style and use the primary or accent color for another element?

### DISCUSSION THREAD

**Discussion by ssbarnea** [squidfunk/mkdocs-material#4891] [Q&A]
I want to add some color the bold (em) elements in order to make them easier to identify in the text but I was not able to identify how I can refer to the theme primary and accent colors in order to achieve that.

Can someone please give an example? For example, the code below works as expected but it does not make use of theme specific colors.

```
em {
    color: red;
}
```

The colors defined in [color-scheme](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=colors#color-scheme) are clearly not official HTML color names and I want to be able to use the ones from the scheme. How can I do this?

**Comment by squidfunk** [comment]
Parametrization is implemented using CSS Variables. You can find all defined colors here:

https://github.com/squidfunk/mkdocs-material/blob/88cfdce580d55f9b0b2ff58bac6449d47979d20f/src/assets/stylesheets/main/_colors.scss#L27-L134

By overriding those variables, you can easily define [custom colors](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors) and use them across your customizations:

``` css
:root {
  --md-primary-fg-color:        #EE0F0F;
  --md-primary-fg-color--light: #ECB7B7;
  --md-primary-fg-color--dark:  #90030C;
}
```

Use it with:

``` css
.md-typeset em {
  color: var(--md-primary-fg-color);
}
```
