### DISCUSSION TITLE
How to enable custom tags sorting?

### DISCUSSION THREAD

**Discussion by jeremy-feng** [squidfunk/mkdocs-material#4968] [Q&A] [answered]
As mentioned in the document:

> You can also define your own comparison function which must return a tag value (as a string) that is used for sorting, and reference it accordingly.

I'm still not quite clear on the implementation of custom tag sorting. It seems that we need to edit some Python scripts.

Can anyone provide a demo for illustration? Thanks a lot!

**Comment by squidfunk** [comment, marked as answer]
I think it's best to ask @facelessuser – how could you call a local python file with a custom sort implementation?

```
plugins:
  - tags:
      tags_compare: ?
```

**Reply by jeremy-feng** [reply]
> I think it's best to ask @facelessuser – how could you call a local python file with a custom sort implementation?
> 
> ```
> plugins:
>   - tags:
>       tags_compare: ?
> ```

Hi @facelessuser , could you please help me? Thank you very much!

**Reply by facelessuser** [reply]
You would just reference your own custom module as described in Material's docs:

```yaml
plugins:
  - tags:
      tags_compare: !!python/name:material.plugins.tags.plugin.casefold
```

Let's say I have a documentation repo with my `mkdocs'yml` in the root of that project. I could create a folder called `plugins` in the root (don't forget your `__init__.py` file. Create another file under `plugins` called `tagsort.py`. Put a function in it called `mysort`, then call.

```yaml
plugins:
  - tags:
      tags_compare: !!python/name:plugins.tagsort.mysort
```

Assuming your special function has the correct function signature for the tag plugin, it should work.
