### DISCUSSION TITLE
How to adjust the max-width of an admonition?

### DISCUSSION THREAD

**Discussion by jeremy-feng** [squidfunk/mkdocs-material#4987] [Q&A] [answered]
When I hide the navigation and TOC, the content width is very large, especially on a large screen.

I want to set the max-width of an admonition, and make it center-aligned. How can I do so?

![image](https://user-images.githubusercontent.com/44312563/216772442-3fba1ce9-a3cf-49d1-a07f-99deff1a539c.png)

**Comment by squidfunk** [comment, marked as answer]
You can adjust Material for MkDocs to your needs with [additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css):

``` css
.md-typeset .admonition {
  max-width: 500px; /* <-- adjust to fit */
  margin-inline: auto;
}
```

**Reply by jeremy-feng** [reply]
Thanks! 

What if I just want this specific admonition to have a limited width? I don't want other admonitions to change their behavior.

**Reply by squidfunk** [reply]
You can scope the styles to an additional class, e.g. `narrow`:

``` css
.md-typeset .admonition.narrow {
  max-width: 500px;
  margin-inline: auto;
}
```

Then use it as follows:

```
!!! note narrow "Phasellus posuere in sem ut cursus"

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et euismod
    nulla. Curabitur feugiat, tortor non consequat finibus, justo purus auctor
    massa, nec semper lorem quam in massa.
```
