### DISCUSSION TITLE
Unexpected margin in `pymdownx.tabbed` when the text is joined with a code block

### DISCUSSION THREAD

**Discussion by reregaga** [squidfunk/mkdocs-material#5001] [Q&A] [answered]
When I write text close to a code block, margin appears between the tab title and the code block, you can see it in the second tab on the gif. I don't know what the problem is here, and I usually leave space in the markdown, I just accidentally noticed it. I think the recommendation would be to leave space around the code block in the markdown, but still I ask, is this expected behavior or does it look like a bug? 🤔

`mkdocs.yml`:
```yml
site_name: Test

theme:
    name: material

markdown_extensions:
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
```

`index.md`:
```md
# Header

=== "One"

    ```js
    one
    ```

    **one**

=== "Two"

    ```
    two
    ```
    **two**
```

>![tabs](https://user-images.githubusercontent.com/76629445/217188744-8813fe68-436d-4e86-a019-0fab9da96f5a.gif)

Code:
[example.zip](https://github.com/squidfunk/mkdocs-material/files/10672931/example.zip)

**Comment by squidfunk** [comment, marked as answer]
Thanks for noting. That's actually by design and resembles the behavior of tabbed fenced code blocks before we had Tabbed. The idea is: if a code block is the first child, the margin is gone. You can override the rule that adds the margin with [additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css) if you don't like the behavior:

``` css
.md-typeset .tabbed-block > .highlight:first-child > pre {
  margin: 1em;
}
```
