### DISCUSSION TITLE
Custom color names?

### DISCUSSION THREAD

**Discussion by wilhelmer** [squidfunk/mkdocs-material#5015] [Q&A] [answered]
Not sure if this has been asked before – I found similar discussions, but none with this particular topic. 

So we can define [custom colors](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=color#custom-colors), and we can define custom [color schemes](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=color#custom-color-schemes). And we can change the primary and accent colors via CSS. 

But we **can't** define custom color names, is that correct? So there's no way to set something like this:

```yml
theme:
  palette:
    primary: mycustomcolor
```

Which would allow changing colors dynamically via JS as shown [here](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=color#primary-color) with the colored buttons.

```js
document.body.setAttribute("data-md-color-primary", "mycustomcolor")
```

**Comment by squidfunk** [comment, marked as answer]
Sure, that's possible, too. You basically just need to craft a rule for the [`data-md-color-primary`](https://github.com/squidfunk/mkdocs-material/blob/48e8b2be30fed05c76dda6bc20ff039ed3e8601f/src/assets/stylesheets/palette/_primary.scss#L53-L56) (or `*-accent`) selector:

``` css
[data-md-color-primary="mycustomcolor"] {
    --md-primary-fg-color: red;
    --md-primary-fg-color--light: green;
    --md-primary-fg-color--dark: blue;
}
```

Please see the [`palette`](https://github.com/squidfunk/mkdocs-material/tree/master/src/assets/stylesheets/palette) folder for all definitions.
