### DISCUSSION TITLE
Possible to limit search preview size?

### DISCUSSION THREAD

**Discussion by HenrikPoulsen** [squidfunk/mkdocs-material#5075] [Q&A] [answered]
I have an issue where the search preview includes entire code blocks if the searched word is present in them.
We have code blocks in some of the documents which are several hundred lines long, so it results in a lot of scrolling to get past these previews.
Would be nice if it would be possible to limit it somehow.
Like to only show a portion of the code block or some other mechanism.
Does this exist or is it something to consider?

**Comment by squidfunk** [comment, marked as answer]
More compact and focused search previews are on the roadmap and tracked in #4278. As a temporary measure, you can limit the height of the search result with the following CSS as mentioned in https://github.com/squidfunk/mkdocs-material/issues/4714#issuecomment-1353575955:

``` css
.md-search-result .md-typeset {
  display: -webkit-box;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;
}
```

This effectively reverts to the pre-9.0.0 behavior.
