### DISCUSSION TITLE
How to setup Navigation expansion

### DISCUSSION THREAD

**Discussion by tusharsonawanes** [squidfunk/mkdocs-material#5118] [General]
I am trying to setup Navigation expansion, I have added all the necessary code as mentioned here. I have all the pages mentioned in mkdocs.yml. As of now, it looks something like this

```
nav:
   - a.md
   - b.md
```

What I want is, the page b.md should be a part of a.md page and should support the collapse scenario. 

Can anyone please help me to achieve the same?

Reference - https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion

**Comment by squidfunk** [comment]
From what you write I think you mean collapsed sections. Try:

``` yaml
nav:
  - a:
    - a/index.md
    - a/b.md
```

Remember to adjust paths accordingly. Then enable [`navigation.indexes`](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages):

``` yaml
theme:
  features:
    - navigation.indexes
```
