### DISCUSSION TITLE
Confusion about Mike support in mkdocs-material

### DISCUSSION THREAD

**Discussion by Andre601** [squidfunk/mkdocs-material#5124] [Q&A]
Not sure if this is intentional behaviour, or if I have to alter something to adjust my docs and make everything work as it should.

Right now I have a single "branch" set up in Mike called `dev` which is updated using the action shared in #4759.

The thing is, that on the actual docs, the Version selector is not visible. The `dev` branch is present and can be accessed by appending `/dev` to the URL itself. However, this causes the "Outdated" banner to show, even tho I doubt that this should be the case as `dev` is by definition the latest push of the documentation.

So I would appreciate some assistance in understanding how Mike works here and if I had to do anything specific to correct all this...

**Comment by squidfunk** [comment]
Did you set `dev` as a [default version](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#setting-a-default-version)?

```
mike set-default --push dev
```

**Reply by Andre601** [reply]
I've set a different branch as default using `set-default`, tho it doesn't redirect when targetting the root.
Could perhaps be that I didn't push using `--push`

What I wonder is how commands in gh action should look like...
Right now I have `mike deploy --push dev` as command.
I assume it should be changed to
```shell
mike deploy dev
mike set-default dev --push
```
to be sure that it keeps the default.

**Reply by squidfunk** [reply]
Related: #4759.

**Reply by Andre601** [reply]
> Related: #4759.

I did mention that issue. Doesn't really answer my point

**Reply by squidfunk** [reply]
Sorry, missed it. I'm answering dozens of questions a day, so sometimes it's hard to keep context all the time. In general, I think it's best to ask the maintainers of mike then.

**Reply by Andre601** [reply]
Yeah, the set-default command doesn't really work here, which is rather strange. I've opened an issue on the Mike repository and will wait for a reply.

In the meantime am I curious how MkDocs-material determines the page to be "old". Is it a check provided from mike or is there some internal logic applied from you using the provided versions.json file?

**Comment by Andre601** [comment]
I now tried to define multiple default branches like this:

```yaml
extra:
  version:
    provider: mike
    default:
      - latest
      - dev
```
But even tho I have `dev` as the default defined is MkDocs Material still giving me the Outdated banner while being on the dev branch.
Could this be related to caching?

GitHub Pages is used to host the content and I update the page on push like this:
```yaml
name: Deploy Site

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'mkdocs-theme/**'
      - 'requirements.txt'
    branches:
      - master
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install -r requirements.txt
      - name: Deploy Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          mike deploy dev
          mike set-default dev --push
```
