### DISCUSSION TITLE
How to enable mindmaps from mermaid library?

### DISCUSSION THREAD

**Discussion by andynameistaken** [squidfunk/mkdocs-material#5125] [Q&A] [answered]
This is what I've tried:
 - added to `mkdocs.yml`
 a)
 ```yml
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
```
b) Because mindmap library [uses the lazy loading](https://mermaid.js.org/syntax/mindmap.html#integrating-with-your-library-website):

```yml
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@9.3.0/dist/mermaid.esm.min.mjs
  - https://cdn.jsdelivr.net/npm/@mermaid-js/mermaid-mindmap@9.3.0/dist/mermaid-mindmap.esm.min.mjs
```
- created [sample page](https://pastebin.com/9teNpdaR)

This is the result I've got (syntax is correct):
![image](https://user-images.githubusercontent.com/15692002/222021560-bfbbcb43-64a7-491d-be58-72e91b09c613.png)
