### DISCUSSION TITLE
Automatic redirects using hooks and the Git history

### DISCUSSION THREAD

**Discussion by kamilkrzyskow** [squidfunk/mkdocs-material#5130] [Show and tell]
> **Disclaimer:** This guide expects a basic understanding of the Python programming language, used in the solution. 
However, I provide a reusable script you can just use without full understanding. [This free course](https://cs50.harvard.edu/python) can also get you up to speed with using Python.

---

# Context
The [mkdocs-redirects](https://github.com/mkdocs/mkdocs-redirects) plugin allows to create _dynamic*_ redirections for older links.

```yaml
plugins:
    - redirects:
        redirect_maps:
            'old.md': 'new.md'
            'old/file.md': 'new/file.md'
            'some_file.md': 'https://external.url.com/foobar'
```

However, they're not fully dynamic, because the user has to maintain the `redirect_maps` manually after each location change. 
The user might forget to update them, or even make a mistake and write the old name with a typo or fat-finger and write a completely wrong destination.

Why not write the redirections automatically then to save time and headaches?

## Solution
Since version [1.4.0](https://github.com... to read more subscribe to my newsl... no no no, it's nothing of that sort.
To read more go to the main post over at the main MkDocs discussions:

https://github.com/mkdocs/mkdocs/discussions/3134

I just don't want to maintain 2 separate posts, and ultimately forget to do so.
I hope such cross-post is OK, the hook should work with any theme, therefore I decided to post the main post there.
