### DISCUSSION TITLE
Does abbreviations support multilanguage?

### DISCUSSION THREAD

**Discussion by Vetrenik** [squidfunk/mkdocs-material#5152] [Q&A] [answered]
Hello everybody!

Pretty new to material and just tried to use https://squidfunk.github.io/mkdocs-material/reference/tooltips/#adding-a-glossary in a multilang style described in https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/ but it seems, that it either does not support multilang, or i'm doing smth wrong

here is my config:
```
site_name: Documentation Prototype
site_url: https://example.com/
nav:
  - Home: index.md
  - Installation Guide: installation/index.md
  - About: 
      - About: about/index.md
      - Architecture: about/architecture.md
  - Glossary: glossary/abbreviations.md
  # - Glossary: abbreviations.md


theme:
  name: material
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.expand
    - navigation.footer
    # - navigation.indexes
    - content.code.copy
    - content.action.edit
    - content.action.view
    - toc.follow
    # - toc.integrate

    - search.suggest
    - search.highlight
    - search.share
  language: fr 
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
extra:
  alternate:
    - name: Français
      link: ./fr/
      lang: fr
    - name: English
      link: ./en/ 
      lang: en
  version:
    provider: mike
plugins:
  - search:
      lang: 
        - en
        - fr
  - i18n:
      default_language: fr
      languages: 
        fr: Français
        en: English
  - mike:
      # These fields are all optional; the defaults are as below...
      # alias_type: symlink
      # redirect_template: null
      # deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
markdown_extensions:
  - toc:
      permalink: true
      # toc_depth: 3
      title: On this page
  - attr_list
  - md_in_html
  - abbr
  
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md  
```

and my dir struct
```
docs
├── about
│   ├── architecture.fr.md
│   └── index.fr.md
├── glossary
│   ├── abbreviations.en.md
│   └── abbreviations.fr.md
├── index.en.md
├── index.fr.md
├── installation
│   ├── index.en.md
│   └── index.fr.md
└── stylesheets
    └── extra.css
```
