### DISCUSSION TITLE
Does toc.follow work with non-latin symbols?

### DISCUSSION THREAD

**Discussion by Vetrenik** [squidfunk/mkdocs-material#5155] [Q&A] [answered]
Enabled toc.follow in config as show in https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-following

Works well with headers in latin symbols
![image](https://user-images.githubusercontent.com/44965799/223104104-c53ce3db-e083-433a-a9bf-7b3273080b16.png)

But seems to not work with non-latin symbols
![image](https://user-images.githubusercontent.com/44965799/223103970-59dd5799-b109-48d7-a9e7-4da581f33ae1.png)

**Comment by squidfunk** [comment, marked as answer]
Not known. If you can provide a [_minimal_ reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/), we can look into it.

**Reply by Vetrenik** [reply]
Tested myself, while building reproduction for you, parameter **percent_encode: true** breaks toc.follow 
```YML
markdown_extensions:
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
          percent_encode: false
```

Here is reproduction
[example.zip](https://github.com/squidfunk/mkdocs-material/files/10901495/example.zip)
