### DISCUSSION TITLE
What front matter property or mkdocs config value will let me control the url?

### DISCUSSION THREAD

**Discussion by sheldonhull** [squidfunk/mkdocs-material#5161] [Q&A] [answered]
I prefer to setup slug on my hugo blog because I can move content around and as long as the slug is unique I never break links.

In mkdocs, I have subdirectories and these are automatically added to the slug.
Is there a way for me to set my url naming to just require unique slugs and not prefix the directory in the url? This would be prevent me from moving files around because I'd be concerned I'd break all the urls.

**Comment by squidfunk** [comment, marked as answer]
This is not natively supported by MkDocs. FWIW, the [`blog` plugin](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/) allows for explicitly setting `slug` in front matter, but I don't know of a plugin that does the same for regular documents. Note that for moving content around, the [`mkdocs-redirects`](https://github.com/mkdocs/mkdocs-redirects) plugin can be used to set up proper redirects for stale URLs. You might also be able to implement this with a few lines of Python as part of a hook.

**Reply by sheldonhull** [reply]
Now that I’ve been trying the new blog plug-in I need to add while the slug can be controlled it still expects the directory and can’t make it flat.  Ie `blog` or such in in the url and not just `site.com/slugofpage`.  I think it’s fundamentally just a restriction of mkdocs as mentioned. You gain some great automatic nav creation and perhaps lose a little control for this convenience. 

Note to future self since I ran across this while searching again. 😆

**Reply by squidfunk** [reply]
If you build a [standalone blog](https://squidfunk.github.io/mkdocs-material/blog/2022/09/12/blog-support-just-landed/#creating-a-standalone-blog), and set [`post_url_format`](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#+blog.post_url_format) there will be no `blog` path in the URL:

``` yaml
plugins:
  - blog:
      blog_dir: .
      post_url_format: "{slug}" # or "{file}" if you want to just use the filename
```

If that doesn't work, please create a new issue and provide a reproduction because it's a case we definitely want to support. Note that you can explicitly set the `slug` front matter property in a blog post (currently not documented, but will be soon).

**Reply by squidfunk** [reply]
For regular pages, you need to create a directory structure that should mirror the slugs produced, or you can create a small custom hook to change the destination path and URL to whatever you like, as we also do it in the blog plugin.

https://github.com/squidfunk/mkdocs-material/blob/de0c5b7719deff6d092dc673e82af701c6f36001/src/plugins/blog/plugin.py#L379-L382

**Reply by sheldonhull** [reply]
@squidfunk ok, so I got stuff published and i see your point about using a plugin to better control.
No expectation of more detail, but if you get time please see if you can shed light on anything here. I did my best to provide thorough info including a fully ready codespace in case that helps. Cheers regardless! 

## My Setup


I created a devcontainer config and branch so if you want to pull this up in codespaces it's 99% automated to run. I understand you are busy so if this isn't helpful disregard, figured though this might be easier to see. 

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](https://codespaces.new/sheldonhull/digital-garden/tree/test%2Fpage-structure)

Once finished loading, from terminal use zsh. ie: `exec zsh -l` 
Then this should setup + spin up everything in localhost serve (dockerized).

```shell
aqua install --tags first
aqua install 
mage init job:up
```


## Other notes

- post: `notes/posts/2023/2023-05-03-how-many-commits-did-you-make-in-last-month.md`
- front matter:
```yaml
date: 2023-05-03
title: How Many Commits Did You Make in Last Month
slug: how-many-commits-did-you-make-in-last-month
```

| Type | Value | Comment | 
| --- | --- | --- | 
| desired url | `localhost:3001/how-many-commits-did-you-make-in-last-month` | even if I move to a new directory I'd like to get this flat with no directories |
| expected url based on my understanding | `http://localhost:3001/posts/how-many-commits-did-you-make-in-last-month/` | Because seems like directories can't be removed from url by default |
| actual url | `http://localhost:3001/posts/2023/2023-05-03-how-many-commits-did-you-make-in-last-month/` | directory, date dir, and date prefix all unexpected |


My mkdocs config:

- Removed `nav` entirely (since I was testing with usage of awesome-pages due to control and flattening feature. 
- my blog config

```yaml
plugins:
  - blog:
      enabled: false
      blog_dir: .
      # post_dir: '{blog}/posts'
      post_dir: '{blog}/posts'
      post_url_date_format: yyyy/MM/dd
      post_url_format: '{slug}'
      blog_toc: true

      categories: false
      archive: false
      archive_name: archive
      archive_date_format: yyyy
      archive_url_date_format: ''
      archive_url_format: '{date}'
      archive_toc: true

      post_excerpt: optional
      post_slugify_separator: '-'
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
```


## The main things 

I want to scope my question mainly to: 

- [ ] Without a plugin, can I get to the _desired_ url structure that's flat? Assuming not but making sure. Your answer above seems to say I need to use python plugin to simulate what you did for blog. Before I untangle blog + awesomepages + plugins and all the mess I might run into with so much magic happening, making sure this is the path I need for that.
- [ ] When my file name has a date in it, the slug field doesn't seem to work. Maybe I'm bringing my Hugo knowledge over and the slug field doesn't work like I expect or something?
- [ ] Is there any combination where I can have my posts by year grouped, or is this getting into custom template territory? My chronological blog posts need this type of format, while the evergreen "docs" don't. 
![CleanShot 2023-09-13 at 14 37 59](https://github.com/squidfunk/mkdocs-material/assets/3526320/e8d12987-cbbc-4469-91f3-94a331dab298)
