### DISCUSSION TITLE
How to display docs without use Page tree?🥲

### DISCUSSION THREAD

**Discussion by HCNtoMoon** [squidfunk/mkdocs-material#5178] [Q&A] [answered]
IF I have a lot of *.md files and want to display them,  I should add every single *.md to _nav_ at _**mkdocs.yml**_
```
nav:
  - home: index.md
  - news:
    - news/news1.md
    - news/news2.md
    - news/news-ss.md
    - news/news-tt.md
  - blog:
    - blog/blog1.md
    - blog/blog2.md
    - blog/blog-ss.md
    - blog/blog-tt.md
```
but there are too many  *.md files, If I have one hundred *.md files, I need to edit one hundred times...🥲I'm tired to add it. 🥲
I want to show all the *.md files under the _**news**_ folder and the _**blog**_ folder, all of it!
How to do this?

**Comment by kamilkrzyskow** [comment, marked as answer]
By default there is no such option. You can either remove the whole `nav` tree and it will automatically create it with all files in alphabetical order. You could change the naming of the files to be more consistent like `0001_News.md` etc. If you want more control you can use the `awesome-pages` plugin, however I'm not sure if it's compatible with the Material theme blog plugin.

After installing it's best to remove the whole `nav` tree from `mkdocs.yml`, and then add a `.pages` file to a given directory where you want to structure the `nav` tree part. I guess in your case you'd use 3 `.pages` files:

In `docs/` root:
```yml
nav:
    - home: index.md
    - news
    - blog
```
In `news` and `blog`:
```
nav:
    - ...
```
The plugin adds multiple ways to change the order of items, use `glob` or `regex` patterns to select a range of files etc.

I've been recently working on introducing this plugin to my team's docs, you can look at the commit as a rough guide. However note that the additional global plugin options are custom from my fork and are currently evaluated to be added to the main project, and that using the `i18n` plugin required me to use glob patterns to catch every file name with a suffix. 👀 Now that I wrote it, I see there are multiple custom things, so maybe the guide from `awesome-pages` plugin's GitHub might be more straight-forward.

https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
https://github.com/Gothic-Modding-Community/gmc/pull/85/commits/4d1b9773d6ee356bd03b465377afbcbf3cd9d457
