### DISCUSSION TITLE
Using custom icons in Markdown

### DISCUSSION THREAD

**Discussion by santaimpersonator** [squidfunk/mkdocs-material#5199] [Q&A] [answered]
I am having trouble using [custom icons with Markdown](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#__codelineno-7-1).

Following, the [additional icons](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#additional-icons) instructions... I can get my custom icons to work as [configurations ](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#icon-bundled) in the `mkdocs.yml` file and as [page icons](https://squidfunk.github.io/mkdocs-material/reference/?h=icon#setting-the-page-icon). However,  the markdown feature seems to fail 😞.

---

**File Organization:**
```
.
├─ overrides/
│  └─ .icons/
│     └─ logoA.svg
│     └─ logoB.svg
│     └─ test/
│        └─ logo1.svg
│        └─ logo2.svg
└─ mkdocs.yml
```

---

**Icon used as a configuration:**
```yml
# Configuration for webpage theme
theme:
  # Theme: https://squidfunk.github.io/mkdocs-material/
  name: material

  # Icon in Browser Tab (must be square img - i.e. 32x32 pixels)
  favicon: img/sfe_logo_sq.png

  # Configures icons
  icon:
    # Sets homepage icon
    logo: logoA

  # Adds overrides for stylesheets, html, etc.
  custom_dir: docs/overrides


# Included MkDocs plugins
# Add the installation of any new plugins to the ./github/workflows/mkdocs.yml file also
plugins:
  - typeset


# Included Markdown extensions
markdown_extensions:
  - admonition
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra:
  # Configures social icons in the footer
  social:
    - icon: test/logo1
      link: https://www.sparkfun.com/
```

Result:
![image](https://user-images.githubusercontent.com/36016723/224981740-f608dc2d-6a2a-4939-86e6-713ee272155a.png) ![image](https://user-images.githubusercontent.com/36016723/224982002-53d69b33-af2c-45a6-b7f4-76cd87d3e033.png)

---

**Icon used in Markdown:**
```md
:logoA:
:logoB:
:test-logo1:
:test-logo2:
```

Result:
![image](https://user-images.githubusercontent.com/36016723/224982528-a1377a55-cf43-4ef3-ba58-a35fc320c63b.png)

**Comment by squidfunk** [comment, marked as answer]
Your `custom_dir` points to `docs/.overrides`, while you point `pymdownx.emoji` to `overrides/.icons`. I think if you change it to `docs/overrides/.icons`, it should work. Nevertheless, never put overrides in the `docs_dir` – they will all be copied and included with the final output.

``` yaml
# Included Markdown extensions
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - docs/overrides/.icons # <-- NOT recommended, see explanation.
```
