### DISCUSSION TITLE
Highlight Lines (hl_lines) didnt match up with Line Numbers (linenums)

### DISCUSSION THREAD

**Discussion by SPyofgame** [squidfunk/mkdocs-material#5234] [Q&A] [answered]
## Context

AFAIK `lines_num` will change the first index of the code block (which is by default 1) to another higher positive integer.

I expect `hl_lines` will be relative to the `lines_num`, but instead, it will just ignore the `lines_num` which might sometimes be confusing to a new user (e.g: new writer joining my project)

## Issue Description

For example I have the code like this

        ```cpp  linenums="6"
        /// Ham tinh quy hoach dong tong tap con | a[0..n-1] voi n = 2^k
        vector<long long> dp_sos(const vector<int> &a, const int n)
        {
            /// Khoi tao mang
            vector<long long> F(n, 0LL);

            /// Duyet qua cac trang thai mask
            for (int mask = 0; mask < n; ++mask) /// O(2^n)
            {
                /// Tinh F[mask] = Sigma(submask) a[submask]
                /// Bai toan khong can tinh a[0] thi gan submask = 1
                for (int submask = 0; submask < n; ++submask) /// O(2^n)
                {
                    /// Neu nhu submask la tap con cua mask
                    if ((mask & submask) == submask)
                    {
                        /// Tinh tong tap con hien tai
                        F[mask] += a[submask];
                    }
                }
            }

            return F;
        }
        ```

for which will be rendered as

![image](https://user-images.githubusercontent.com/62207095/226396582-30d05d62-34c1-46eb-8325-0cd91fe87275.png)

adding the specific highlights `linenums="6" hl_lines="13 17 20"` which will intendedly to do something like this

![image](https://user-images.githubusercontent.com/62207095/226397291-b0825f2d-1fd3-49cb-b274-8ede43b6e32a.png)

instead, the result is a bit different
 
![image](https://user-images.githubusercontent.com/62207095/226396891-92d37bc2-6bf4-462b-bcc7-9cdf6e316081.png)

## Suggestion:

Though I would not say it is demanding as I think this is a **niche unworthy work** that needs not and should not to be prioritized. But if you are interested, I have some ideas that you might wanna expand:

**Relative Highlight:** Using `hl_relines` for **h**igh**l**ight **re**lative **lines**, that will minus the `linenums` for relative

**Code Wrappers:** Wrap a bunch of code that allows the user to toggle collapsible `wrap = 4-10 12-15 21-47 70-85`

**Range RelativeHighlight:** `hl_relines = 4-10 14-19` stuff for a sufficiently long code.

**Dimish Unimportant:** To get rid of those unimportant parts with a shady darker brightness `dimish = 10-16`

**Mouse Coordination:** To know the current position of the mouse on the code (Row, Column) with a vertical and horizontal highlight `coord=true/false`

**Code Pointer:** Toggle for the user to be able to move around the code using arrows keys `pointer=true/false`

**Hover Note:** Like code annotation, but specifies note on sideways upon hovering `hover = A[10-20] B[50-60]` then `A: <def>` then `B: <def>`. This will allow the user to get the simple note and its references for confusing parts of the code (tho it seems rarely we need this over the admonition, eg: code that shouldn't add anything extra like comments).

## Minimal Base Yaml

```yaml
image: python:latest
pages:
  stage: deploy
  script:
    - pip install git<private link>
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
```

```yaml
  features:
    - content.code.select
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      pygments_lang_class: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
```

## Related Links

https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=hl+lines#highlighting-specific-lines
https://facelessuser.github.io/pymdown-extensions/extensions/superfences/?h=hl_lines#highlighting-lines

## Browser 

Chrome

## Before Startings The Discussions

- [X] I have [search for similar discussions](https://github.com/squidfunk/mkdocs-material/discussions?discussions_q=hl_lines)
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.

**Comment by facelessuser** [comment, marked as answer]
The Material theme does control this. I believe this would be a request for https://github.com/facelessuser/pymdown-extensions.

`hl_lines` highlights the line you tell it to. `linenums` is a cosmetic change making the line numbers visible and allowing you to remap them relative to some new start.

This is definitely not a bug but works as intended. Now, it may be that it is desired that enhance this with an optional setting, if so, feel free to create a feature request over at Pymdown Extensions. I'll have to make a decision on whether to add the feature, but I'd at least get an issue created if you are really wanting it.

**Reply by SPyofgame** [reply]
In my opinion, having both absolute and relative is useful for many cases. But I am just afraid that you might gotta end up with more maintenance costs (eg: blended `hl_lines` and `hl_relines` might also cause certain issues under certain customizations or incompatibilities). So I will leave those as suggestions instead of issues (tho I really want it 🥺 )

But I just also notice something, how can I have this `Toogle Line Detection`, seems like `Mouse Coordination` I mentioned earlier

![image](https://user-images.githubusercontent.com/62207095/226415393-1008a445-78df-4373-bca6-703a42b32803.png)

Are there other optional features that I can enable (with certain plugins, features, customizations, ... ?)

**Reply by squidfunk** [reply]
The feature is called [code selection](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-selection-button):

``` yaml
theme:
  features:
    - content.code.select
```
