### DISCUSSION TITLE
[Unintended Unnatural Feature] Tabbed Cause the Page to "jump"

### DISCUSSION THREAD

**Discussion by SPyofgame** [squidfunk/mkdocs-material#5240] [Q&A]
Similar to #4598 

## Context

The tabs have unnatural behavior of jumping with is kinda annoying for certain cases.

## Issue Description

So assume I am reading this

![image](https://user-images.githubusercontent.com/62207095/226797121-4806baa1-7027-457f-aeec-b3b8d30237fd.png)

Clicking the same tab itself doesn't jump me down, but only anchor the link `/path/to/folder/title.html#tab_title`

![image](https://user-images.githubusercontent.com/62207095/226798787-b11b05da-5944-4ba8-aefb-9e8c0c17b800.png)

Clicking the different tab will make me jump down

![image](https://user-images.githubusercontent.com/62207095/226797168-ca16f6d5-d472-4c50-b368-aa863f2f96d2.png)

But it sometimes annoyed me if I just want to open it and then move down slowly, or at least it should have a gliding effect instead of a sudden jump.

It is possible to add attributes to control this behavior or javascript to make it smooth ?

## Minimal Base Yaml

```yaml
image: python:latest
pages:
  stage: deploy
  script:
    - pip install git<private link>
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
```

```yaml
theme:
  features:
    - content.tabs.link

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
```

## Configuration

Latest version mkdocs.
Latest version insider pymdown.

Local-host: Acer Nitro 5 Laptop
Online-host: Gitlab
System: Window
Browser: Chrome

## Suggestion:

`===#` to make it able to jump
`===$` to make it able to glide smoothly
`===` will only open the tab naturally

or

`click` to open
`double click` to close
`quick double click` to jump

or

`click` top open
`hold click` to jump

or 

allow attributes to be added { no.jump }

## Application

Make it less of unintended unnatural jumping

## Related Links

https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions
https://facelessuser.github.io/pymdown-extensions/extensions/tabbed

## Before Startings The Discussions

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and partially agree. I am not good enough to do certain advanced implementations, so I want to start the discussion to get advice on how to do so if it isn't worth being added to `master` (for the sake of overall functionality).
- [X] I have [search for similar discussions](https://github.com/squidfunk/mkdocs-material/discussions?discussions_q=Tasklist)
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure you that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing) before submitting this suggestion report.
- [X] The documentation does not mention anything about my problem
- [ ] There is an open question related to my discussion #4598
