### DISCUSSION TITLE
Git revision date and Git commiters not showing

### DISCUSSION THREAD

**Discussion by FlagHunter01** [squidfunk/mkdocs-material#5258] [Q&A] [answered]
# Git revision date and Git commiters not showing on GitHub pages

## Symptoms

There is a difference between my local preview and GitHub pages.

Here is what I see locally:
![2023-03-25_13h09_27](https://user-images.githubusercontent.com/32909577/227716545-ae5693f0-f91f-43cd-a11d-30ca9a170541.png)

And here is what appears on GitHub Pages:
![2023-03-25_13h10_12](https://user-images.githubusercontent.com/32909577/227716568-ee716c6e-f2fe-4819-8f37-991f00c12168.png)

(Don't mind the color change, it's a browser issue. The source code is identical). 

## Relevant files

Here is my `yml`:

```
  # Revision date info for GitHub repos TODO: uncomment if repo
  - git-revision-date-localized:
      enable_creation_date: true
      #fallback_to_build_date: true
  - git-committers:
      repository: FlagHunter01/school
      branch: main
```

And here are the installs I've added to the workflow:

```
      - run: pip install pillow cairosvg
      - run: pip install lxml
      - run: pip install mkdocs-material
      - run: pip install pillow cairosvg
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-git-committers-plugin-2
      - run: pip install mkdocs-git-authors-plugin
      - run: mkdocs gh-deploy --force
```

I'd like to render the page on GitHub as seen locally. 
*Sorry if it's something obvious, it's my first day here*
