### DISCUSSION TITLE
Tab link for certain keyword only

### DISCUSSION THREAD

**Discussion by SPyofgame** [squidfunk/mkdocs-material#5262] [Ideas]
## Context

I think tab links should be enabled for certain keywords. For certain cases like:
- You want `C++ / C / python / ...` to be tab-linked together, but not the other common sense tabs which might share the same title (eg: different header mentioning the same topic).
- 

## Minimal YAML

```yaml
image: python:latest
pages:
  stage: deploy
  script:
    - pip install git<private link>
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
```

```yaml

theme:
  features:
    - content.tabs.link
    
markdown_extensions:
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
```

## Related Link

[Tabs Link](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/?h=tabs+link#feature-disabled)
[Pymdown Extension](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/?h=tabbed#tabbed)
[Tabbed Configuration](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/?h=tabbed#configuration)
[Tabbed](https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/)

![image](https://user-images.githubusercontent.com/62207095/227764263-463c86e9-bd2c-40d6-919b-d2fcfd1493da.png)

## Configuration

Latest version insider.

Local-host: Acer Nitro 5 Laptop
Online-host: Gitlab
System: Window
Browser: Chrome

## Suggestion

Using an attribute list, for example: 
- `{ .noshare }`          Tab links don't work in this div/span
- `{ share:"title" }`      Tab links only work for those who share the same titles, default = NULL means that its shares globally
- `{ share:"!title" }`    Tab links override ===+ specifications
- `{ scope:"classname" }` Tab links only work in this scope

Using yaml, for example
```
---
noshare: `` # Globally disable tab links
share: `C++`, `C`, `py` # Locally, override noshare 
---
```

## Consideration

- [ ] The new feature is not incompatible with one of the existing features
- [X] The new feature can (ideally) be used together with all existing features `attribute list, tabbed, md to HTML`
- [ ] The new feature can be implemented in a way that is accessible
- [ ] The implementation follows the principle of [progressive enhancement](https://en.wikipedia.org/wiki/Progressive_enhancement)
- [X] The implementation works on all screen sizes (mobile, tablet, desktop) `it doesn't affect content data or styling, but just how they display with user interaction`
- [ ] The implementation works on all modern browsers (nope, not IE)
- [ ] The new feature can be implemented with reasonable effort
- [X] The new feature matches the overall "tone" of this project `Better tab link management`
- [ ] The new feature is useful to the majority of users
- [X] The new feature is easy to use for authors `simple guidelines`

## Application

Better Customization.

Tab Links Management.

## Before starting the discussion

- [X] I've read the [Author Note](https://github.com/squidfunk/mkdocs-material/discussions/2399)
- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and partially agree. I am not good enough to do certain advanced implementations, so I want to start the discussion to get advice on how to do so if it isn't worth being added to `master` (for the sake of overall functionality).
- [X] I have [search for similar discussions](https://github.com/squidfunk/mkdocs-material/discussions?discussions_q=Tasklist)
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure you that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing) before submitting this suggestion report.
- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed ideas that are related to my problem.
