### DISCUSSION TITLE
github deploy error

### DISCUSSION THREAD

**Discussion by berkantsahn** [squidfunk/mkdocs-material#5315] [Q&A] [answered]
Hello everyone,
Thanks already for your help.

My problem occurs when publishing the project on github. I have python 3.11 version installed on my computer. I am creating a yaml file to publish my project, but the process stops automatically during deploy.

The problem is fixed by removing the - run: mkdocs gh-deploy --force line at the end of the yaml file, but when I remove this line the project is not published on github

Yaml file codes;
```
name: ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
```

**Comment by kamilkrzyskow** [comment, marked as answer]
Well, what is the error in your action run log? The CI file looks fine, except for the legacy actions versions.
 `actions/checkout@v3`, `actions/setup-python@v4`, `python-version: 3.11`.
 Also how does your `mkdocs.yml` file look like, maybe you have some additional plugins, which you forgot to install during CI?
 You can run the `mkdocs gh-deploy --force` command from your local PC too :v:

**Reply by berkantsahn** [reply]
Actually there was no clear error. Only at the last stage during deploy was the operation failing. When I ran the code through with vscode terminal, I was able to publish the project on github.
So i edited the ci.yaml file as;
```
name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force
```

and problem solved. Now I can publish my document project without any action on vscode.
