### DISCUSSION TITLE
multi language issue

### DISCUSSION THREAD

**Discussion by berkantsahn** [squidfunk/mkdocs-material#5325] [Q&A] [answered]
Hi there,

I am trying to add multi-language to my test mkdocs document system.
So, my repo link is: https://github.com/berkantsahn/mkdocs-test

I created a 3 yml files. They are mkdocs.tr.yml, mkdocs.en.yml and mkdocs.yml
What I want to do is to open the mkdocs.yml file at startup and call mkdocs.tr.yml or mkdocs.en.yml files according to the selected language.

I took the following project as a sample project: https://github.com/bmeviauac01/datadriven
But when I did the same operations, there was no language change in the sections such as the search bar and the contents.

I don't know where I went wrong. Thank you in advance for your help.

**Comment by berkantsahn** [comment, marked as answer]
I fixed the issue when i add this codes to my ci.yaml file
```
- name: Deploy docs to gh-pages branch
   uses: peaceiris/actions-gh-pages@v3
   with:
     github_token: ${{ secrets.GITHUB_TOKEN }}
     publish_dir: ./site
```

Finally, I couldn't do the routing process in the project. 
What i want to do is when i open the https://berkantsahn.github.io/mkdocs-test link i want to I want to redirect the user to https://berkantsahn.github.io/mkdocs-test/tr/

I tried to add my yaml file this codes but i didn't work.

```
- name: Copy redirect index page
   run: sudo cp /index.html /site
```
