### DISCUSSION TITLE
Use Mermaid diagrams with instant loading navigation

### DISCUSSION THREAD

**Discussion by chraebslight** [squidfunk/mkdocs-material#5387] [Q&A]
I observed that when activating the `navigation.instant` feature, the Mermand.js diagrams do not get rendered anymore.

I like to use both for my documentation. What can I do?

This is related with https://github.com/squidfunk/mkdocs-material/issues/3105#issuecomment-940925584 but I cannot understand that answer.

## Minimal example

`mkdocs.yml`:
```yml
site_name: "mkdocs mermaid with instant navigation"

theme:
  name: material
  features:
    # When navigation.instant feature is activated, Mermaid.js diagrams
    # will not be rendered anymore!
    - navigation.instant

markdown_extensions: 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
```
`docs/Mermaid.md`:
~~~
# Mermaid

``` mermaid
graph LR
  A[Start] --> B{Error?};
  B -->|Yes| C[Hmm...];
  C --> D[Debug];
  D --> B;
  B ---->|No| E[Yay!];
```
~~~

## Setup description
* Windows 10
* Python 3.10
* Firefox

Output of `pip freeze`:
```
...
mkdocs-material==9.1.6
mkdocs-mermaid2-plugin==0.6.0
...
```

## Result
![image](https://user-images.githubusercontent.com/105348467/232724603-555c6f03-4e1d-4fad-afea-3841d31ea14f.png)

## Expected Result
![image](https://user-images.githubusercontent.com/105348467/232724822-fa172b5e-26ab-498a-b01f-3f7d82498730.png)
