### DISCUSSION TITLE
Overrides not taking effect?

### DISCUSSION THREAD

**Discussion by jlipps** [squidfunk/mkdocs-material#5388] [Q&A]
I'm working on migrating docs for [appium/appium-xcuitest-driver](https://github.com/appium/appium-xcuitest-driver) to mkdocs-material. We have some reference docs with lots of `###` and `####` headings in the markdown. I want my TOC to ignore these sections. To make this happen I figured I'd need to create an override for e.g. `toc-item.html`. I've followed the [docs](https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme) for extending the theme, but nothing I've done has enabled any of my changes in the override to have any effect. If there's a better way to cause these lower level headings not to show up in the TOC, I'd love to know about it! But otherwise I'd love to figure out how to get my overrides working.

My structure looks like this:

```
.
├─ docs/
│  ├─ overrides/
│  │  └─ partials/
│  │     └─ toc-item.html
│  ├─ doc-markdowns.md
└─ mkdocs.yml
```

My complete mkdocs.yml looks like this:

```yml
INHERIT: ./node_modules/@appium/docutils/base-mkdocs.yml
site_name: Appium XCUITest Driver
repo_url: https://github.com/appium/appium-xcuitest-driver
repo_name: appium/appium-xcuitest-driver
copyright: Copyright &copy; 2012 OpenJS Foundation
site_url: https://appium.github.io/appium-xcuitest-driver
edit_uri: edit/master/docs
site_description: Documentation for the Appium XCUITest driver for iOS automation
docs_dir: docs
site_dir: site
theme:
  logo: assets/images/appium-logo-white.png
  favicon: assets/images/appium-logo.png
  custom_dir: docs/overrides
  features:
    - navigation.sections
extra_css:
  - assets/stylesheets/extra.css
extra:
  homepage: /appium-xcuitest-driver
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AppiumDevs
nav:
  - index.md
  - setup.md
  - device-preparation.md
  - Reference:
      - server-args.md
      - capabilities.md
      - element-attributes.md
      - security-flags.md
      - settings.md
      - locator-strategies.md
      - ios-predicate.md
      - parallel-tests.md
      - execute-methods.md
      - touch-id.md
      - troubleshooting.md
      - reference/commands/appium-xcuitest-driver.md
  - Guides:
      - real-device-config.md
      - ci-setup.md
      - multiple-xcode-versions.md
      - wda-custom-server.md
      - ios-tvos.md
      - actions.md
      - audio-capture.md
      - ios-xctest-file-movement.md
      - ios-xctest-install-certificate.md
```

The mkdocks yml that this file extends looks like this:

```yml
markdown_extensions:
  - meta
  - attr_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - footnotes

extra:
  generator: false

theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.tabs
```

The content of the override is irrelevant for now. I've replaced the whole html file with e.g. `BLARG` and never saw it anywhere.
