### DISCUSSION TITLE
Navigation sidebar/TOC not showing on right side of the screen

### DISCUSSION THREAD

**Discussion by djgm501** [squidfunk/mkdocs-material#5390] [Q&A]
For some reason I can not get the TOC to show in the navigation side bar (right side of the screen).

I have searched the documentation and stackoverflow for several days trying to find the answer, without luck.  Perhaps someone can help me.

I am using:
- MkDocs 1.4.2 
- Python 3.10 
- Material Theme 8.5.11 
- Windows 10 
- Browsers Firefox and Edge

I created a small test mkdocs directory and a test makedown file.

See below for the resulting web page.

The mkdocs.yml file is:

```
site_name: Test Site
dev_addr: 127.0.0.1:44445
theme:
    name: material
    features:
      - toc.follow
      - toc.integrate
      - navigation.expand
      
markdown_extensions:
    - toc
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - test: 'test/test.md'
```

The test page is:

```
[TOC]

:smile: zxz

:material-fast-forward: Fast forward

# header 1

asdf asf asdf

# header 2

asdf
asdfasdfrrwer

ere
ere

# header 3

fadfs
adsfasdf
adsf

# header 4

sd
dsfasdf

sdff

# header 5

asdf

dfasdf
sdff
fdsfd  fdfd

```
![2023-04-18_14-39-50](https://user-images.githubusercontent.com/131196926/232872727-b146614f-8920-472a-b628-5e0e76e2584b.png)
