### DISCUSSION TITLE
Can you provide the top new function display scrolling function

### DISCUSSION THREAD

**Discussion by qianmoQ** [squidfunk/mkdocs-material#5398] [Ideas]
Can you provide the top new function display scrolling function

**Comment by squidfunk** [comment]
Our documentation explains how to enable the [back-to-top button](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button):

``` yaml
theme:
  features:
    - navigation.top
```
