### DISCUSSION TITLE
Including external YAML in order specified

### DISCUSSION THREAD

**Discussion by jcayouette** [squidfunk/mkdocs-material#5405] [General]
I would like to keep mkdocs.yml file short for a large number of documents.
Can I import specific yaml files with their own navigation and keep the order of the indexes? for example:

```
nav:
  - Docs:
      - Introduction: "index.md"

      # FRONTEND
      - Frontend:
          # HTML
          - HTML:
              - Overview: "html/overview.md"
              - HTTP Messages: "html/HTTP-messages/http-status-messages.md"

          # CSS
          - CSS:
              - Overview: "css/overview.md"
```

So lets say I wanted to have an `html.yaml` file and a `css.yaml` file. How do I split the above content out into individual files to be included in the primary mkdocs.yml nav tree as their own sections while also keeping the specific order of the toc? I am new to mkdocs go easy :)
