### DISCUSSION TITLE
Can't Find Copy to Clipboard Icon in Code Block

### DISCUSSION THREAD

**Discussion by arnold518** [squidfunk/mkdocs-material#5419] [Q&A] [answered]
Hi, I modified the mkdocs.yml file as written in the docs code block section, in order to enable the clipboard button, but it does not seem to appear. Also checked other discussions, but all methods provided do not work.
I just installed mkdocs material, so there are not any css files or other modifications, other than mathjax.js file and ci.yml file.

Those are my mkdocs.yml file.

``` yaml
site_name: Problem Solving Notes

repo_name: arnold518/ps-notes

repo_url: https://github.com/arnold518/ps-notes

theme:
  name: material
  features:
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  language: ko

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
```

And the markdown file.
```` markdown
``` cpp title="asdf.cpp" linenums="1"
#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;
typedef pair<ll, ll> pll;

int main()
{
    printf("Hello World");
}
```

```{: .cpp .copy}
#include <bits/stdc++.h>
using namespace std;

typedef long long ll;
typedef pair<int, int> pii;
typedef pair<ll, ll> pll;

int main()
{
    printf("Hello World");
}
```
````

![image](https://user-images.githubusercontent.com/45283725/234051441-fa023eab-7f60-4ed0-a494-17bb1135205f.png)

If more are needed, you can check [my github](https://github.com/arnold518/ps-notes)

Also, I checked the version using `pip show mkdocs-material`, which showed version 9.1.7, so it should not be a problem with the version.

Thanks in advance!
