### DISCUSSION TITLE
How can I put the list items in bold font?

### DISCUSSION THREAD

**Discussion by hellojinwoo** [squidfunk/mkdocs-material#5429] [Q&A] [answered]
## Q. How can I put the list items on the side tabs in the bold font?

- I'd like to create a list of items, some of which are in bold.
- The example is from the ["Getting Started" tab](https://squidfunk.github.io/mkdocs-material/getting-started/) of the mkdocs material webpage, which can be shown below.

     <img src="https://user-images.githubusercontent.com/34431729/234688586-0bb253e2-bd47-4dff-86ac-65c6030a9beb.png"  width="60%">

- With my code as follows, can I make the `Linear Regression` side tab to be in the 1) bold font and 2) have a little bit longer space away from the Home?
   - As you can see from the screenshot above, `Changelog`, `Contributing` are in the bold font and have more spaces from the side tabs located above, which are licenses and how to upgrade
```
plugins:
  - search
  - mkdocs-jupyter:
      exclude: .ipynb_checkpoints

nav:
  - Home: index.md
  - Linear Regresion: Linear_regression.md
  - Notebook: 01.Maximum_Likelihood_Estimation.ipynb
  - Notebook: 02.Simple_Linear_Regression_Overview.ipynb
```

**Comment by squidfunk** [comment]
Enable [`navigation.sections`](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-sections) and nest the pages in `mkdocs.yml`:

``` yaml
theme:
  features:
    - navigation.sections

nav:
  - Home: index.md
  - Linear Regression:
    - Linear_regression.md
    - Notebook: 01.Maximum_Likelihood_Estimation.ipynb
    - Notebook: 02.Simple_Linear_Regression_Overview.ipynb
```
