### DISCUSSION TITLE
Numpy Docstrings look bad, how can I improve it?

### DISCUSSION THREAD

**Discussion by nh916** [squidfunk/mkdocs-material#5434] [Q&A]
I am generating documentation from docstrings. I've tried both Google style docstrings and Numpy style. I noticed that the Google Style docstrings looks significantly better and has all the nice [widgets](https://squidfunk.github.io/mkdocs-material/reference/admonitions/?h=ad#supported-types) where as the numpy documentation looks bad. Is there any way that I can mess with the configuration to make it look a lot better? Do I have my configurations wrong?

### MKDocs.yaml Configurations
```yaml
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src, docs]
          options:
            show_bases: true
            show_source: true
            docstring_style: numpy
      watch:
        - src/

markdown_extensions:
  - toc:
      baselevel: 2
      permalink: True
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
```
