### DISCUSSION TITLE
Social card doesn't changed with custom config

### DISCUSSION THREAD

**Discussion by ooker777** [squidfunk/mkdocs-material#5464] [Q&A] [answered]
I'm using this setting:
```yml
plugins:
  - social:
      cards_font: Noto Sans SC
      cards_color:
        fill: "#FFFFFF" 
        text: "#ABCDEF" 
```
but the exported cards are still in default:
![Wiki chuyên ngành](https://user-images.githubusercontent.com/6695517/235865703-bd904a46-f47d-4f5b-87ee-c0433d4a0096.png)

Here is [the full mkdocs.yml and full repo](https://github.com/ooker777/mkdocs-hyperlink-bug/blob/main/mkdocs.yml "mkdocs-hyperlink-bug/mkdocs.yml at main · ooker777/mkdocs-hyperlink-bug") if you need more investigation.
