### DISCUSSION TITLE
Missed 'Copy to clipboard' icon in Code Block

### DISCUSSION THREAD

**Discussion by syntezzz1** [squidfunk/mkdocs-material#5471] [Q&A]
Hi!

The button disappeared after upgrading from 8.5.11 to 9.0.0 (and above). I didn't find a solution in a similar topic https://github.com/squidfunk/mkdocs-material/discussions/5419.

Before the update, I had such a `mkdocs.yml` file:

```
use_directory_urls: true
theme:
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  name: material
  #custom_dir: overrides
  features:
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - toc.integrate
    - search.suggest
    - search.highlight
  favicon: favicon.png
  logo: VL_Logo.png    

plugins:
    - awesome-pages:
        collapse_single_pages: false
    - search    
    - img2fig
    - mike:
        version_selector: true   # set to false to leave out the version selector
        css_dir: css             # the directory to put the version selector's CSS
        javascript_dir: js       # the directory to put the version selector's JS
        canonical_version: null  # the version for <link rel="canonical">; `null`

extra:
  version:
    provider: mike
    
markdown_extensions:
    - toc:
        permalink: "#"
        slugify: !!python/name:pymdownx.slugs.uslugify
        toc_depth: 3

extra_css:
  - extra.css
```

I added the following snippet:

```
  features:
    - content.code.copy
```

and I expected the button to appear, but no, it's still not there.

mkdocs version: 1.4.3

Thanks!

**Comment by squidfunk** [comment]
[Please read our upgrade guide when upgrading to a new major version](https://squidfunk.github.io/mkdocs-material/upgrade/#upgrading-from-8x-to-9x). You're missing the [`content.code.copy`](https://squidfunk.github.io/mkdocs-material/upgrade/#contentcodecopy) feature flag:

``` yaml
theme:
  features:
    - content.code.copy

```
