### DISCUSSION TITLE
What is the default order of the navigation?

### DISCUSSION THREAD

**Discussion by hanzckernel** [squidfunk/mkdocs-material#5490] [Q&A]
I am confused in which order the navigation sidebar is arranged? It seems not following alphabetic order nor the alphabetic order in which the files are named. 

<img width="48" alt="Screenshot 2023-05-09 at 10 37 25" src="https://user-images.githubusercontent.com/43314240/237041929-473f9ae1-67f2-49a5-8b97-fcd3242c7e8f.png">

and here is a my `mkdocs.yml` file:

```yaml
theme:
  name: material
  features:
    - toc.integrate
    - navigation.indexes
    - navigation.top
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: cyan

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue
      accent: amber

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.mark
  - attr_list
```
