### DISCUSSION TITLE
Navigation in Material for MkDocs

### DISCUSSION THREAD

**Discussion by Sahith-8055** [squidfunk/mkdocs-material#5561] [General]
Thanks for providing this software and maintaining it with constant improvements.

I have a question for you all. Is there any way to increase the size of the navigation bar to encompass more space (as we see in Docusarus). I might have missed details about the same. If possible, could you point me to the exact location in the documentation (if available)?

Sorry for the mistakes, if any as this is my first question.

**Comment by squidfunk** [comment]
Yes, you can use [additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css). I'm not sure what you mean by "more space", but if you want to make it wider, use:

``` css
.md-sidebar--primary {
  width: 300px;
}
```

You might also want to adjust the overall width then:

``` css
.md-grid {
  max-width: 1400px;
}
```

**Comment by Sahith-8055** [comment]
Thanks for the answer @squidfunk. It partially solves my question. But, my question still remains as to how to increase the length of the navigation bar.

Below is the supposed picture of my question -
<img width="297" alt="Screenshot 2023-05-30 at 3 24 18 PM" src="https://github.com/squidfunk/mkdocs-material/assets/41897310/a61e8fbf-f9a7-42cf-ab6e-47d866908cb9">

Is there anyway of doing this using the extra_css that you had suggested? If so, can you suggest the css for the same?

**Reply by squidfunk** [reply]
I'm not sure I understand what you mean by "Increase the length".

**Reply by Sahith-8055** [reply]
Sorry for not being clear enough @squidfunk. Let me try my luck again.

Currently, navigation bar in mkdocs-material looks like the below one -

<img width="1512" alt="Screenshot 2023-05-30 at 7 46 22 PM" src="https://github.com/squidfunk/mkdocs-material/assets/41897310/5cadda04-ab85-4530-85e4-488205e60427">

My question is how can I ensure the navigation bar in mkdocs-material looks like the below one (If there is any possibility of doing so) -

<img width="1512" alt="Screenshot 2023-05-30 at 7 47 02 PM" src="https://github.com/squidfunk/mkdocs-material/assets/41897310/bf15d0e3-9a61-41a0-87a4-2a2bf477e7b9">

**Reply by squidfunk** [reply]
Material for MkDocs is trivial to customize. You can use [additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css) and modify it to your taste. I currently don't have the time to provide a full implementation, but it is definitely possible to achieve the same layout. As a starter, you can use the following:

``` css
.md-grid {
  max-width: 100%;
}

@media (min-width: 1220px) {
  .md-main__inner {
    margin-top: 0;
  }
  .md-sidebar {
    height: auto;
  }
  .md-sidebar--primary {
    border-right: 1px solid var(--md-default-fg-color--lightest);
  }
  .md-nav {
    font-size: 16px;
  }
  .md-nav .md-nav__title {
    display: none;
  }
  .md-nav__icon {
    width: 1.2rem;
    height: 1.2rem;
    margin-top: -.1rem;
  }
}
```

Result:

![screenshot-localhost-8000-mkdocs-material-getting-started-1685459294992](https://github.com/squidfunk/mkdocs-material/assets/932156/34dfa053-5021-4ec1-9719-7aaabab33027)
