### DISCUSSION TITLE
Light and dark mode images not working

### DISCUSSION THREAD

**Discussion by JavierEscobarOrtiz** [squidfunk/mkdocs-material#5596] [General]
Hello!

We are trying to apply [light and dark mode images](https://squidfunk.github.io/mkdocs-material/reference/images/?h=dark#light-and-dark-mode) to our docs as said in the documentation but something is failing in the **light mode**. We tried to follow the docs because we use a custom color palette, but nothing changes. Before updating mkdocs to 1.4.3 (from version 1.3.1) it works correctly.

Do you have any idea what is happening?

Thank you very much!

![imagen](https://github.com/mkdocs/mkdocs/assets/95030312/773ebfee-b60f-463a-aaf7-a0ea73471ddb)
![imagen](https://github.com/mkdocs/mkdocs/assets/95030312/457f47ec-b3f5-47f3-ab16-b61d698bcad3)

Repo: https://github.com/JoaquinAmatRodrigo/skforecast
Docs: https://skforecast.org/

New requirements_docs.txt:
```bash
mike==1.1.2
mkdocs==1.4.3
mkdocs-jupyter==0.24.1
mkdocs-material==9.1.15
mkdocstrings==0.22.0
mkdocstrings-python==1.1.0
jupyter-contrib-nbextensions==0.7.0
skforecast==0.8.1
```

README.md:

```bash
<img src="img/banner-landing-page-skforecast.png#only-light" align="left"  style="
    margin-bottom: 30px;
    margin-top: 0px;">

<img src="img/banner-landing-page-dark-mode-skforecast.png#only-dark" align="left" style="
    margin-bottom: 30px;
    margin-top: 0px;">
```

mkdocs.yml:

```bash
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
```

extra.css:

```bash
[data-md-color-scheme="light"] {
    --md-primary-fg-color:        #001633;
    --md-primary-fg-color--light: #001633;
    --md-primary-fg-color--dark:  #001633;
    --md-accent-fg-color:        #f79939;
    --md-accent-fg-color--light: #f79939;
    --md-accent-fg-color--dark:  #f79939;
    --md-primary-bg-color:       #f79939;
    --md-typeset-a-color:        #f79939;
  }

  [data-md-color-scheme="slate"] {
    --md-primary-fg-color:        #001633;
    --md-primary-fg-color--light: #001633;
    --md-primary-fg-color--dark:  #001633;
    --md-accent-fg-color:        #f79939;
    --md-accent-fg-color--light: #f79939;
    --md-accent-fg-color--dark:  #f79939;
    --md-primary-bg-color:       #f79939;
    --md-typeset-a-color:        #f79939;
  }
```

**Comment by squidfunk** [comment]
It's likely related to a recent update which fixed some edge cases when using custom colors. Please try to apply the following changes, [as mentioned in our documentation](https://squidfunk.github.io/mkdocs-material/reference/images/#custom-light-scheme):

``` css
[data-md-color-scheme="custom-light"] img[src$="#only-dark"]
[data-md-color-scheme="custom-light"] img[src$="#gh-dark-mode-only"] {
  display: none; /* Hide dark images in light mode */
}

[data-md-color-scheme="custom-dark"] img[src$="#only-light"],
[data-md-color-scheme="custom-dark"] img[src$="#gh-light-mode-only"] {
  display: none; /* Hide light images in dark mode */
}
```
