### DISCUSSION TITLE
How to indent list item with code blocks?

### DISCUSSION THREAD

**Discussion by icefery** [squidfunk/mkdocs-material#5634] [Q&A] [answered]
## Description

I found list item with code blocks, in official docs (and any other markdown editor like VSCode, Typora) works well, but for me, it takes no effect.

I wonder is there some configurations I lost?

## Example

Official documentation render result:

<img width="812" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/61737634/5f5ae4d4-c581-4ade-b33e-9c83b385cc46">

My markdown render result:

<img width="739" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/61737634/b21c9bd7-8292-4b3d-b766-07b11f2304d8">

## Markdown

````markdown
## Chapter 1

- `A.java`

  > hello world in java

  ```java
  public class A {
      public static void main(String[] args) {
          System.out.println("Hello, world!");
      }
  }
  ```

- `a.js`

  > hello world in javascript

  ```javascript
  console.log('Hello, world!')
  ```
````

## Config

```yaml
site_name: 'my site'

docs_dir: docs

theme:
  name: material
  language: zh
  features:
    - navigation.tabs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
```
