### DISCUSSION TITLE
Slugs for content tab anchor links that use headers in slug

### DISCUSSION THREAD

**Discussion by chipsenkbeil** [squidfunk/mkdocs-material#5675] [Q&A]
### Problem

When clicking on the tabs from content tabs that have the same names, I get links like these:

- example.com/#about
- example.com/#value
- example.com/#about_1
- example.com/#value_1

What I'd really like is to have the headers factor into the slug:

- example.com/#log_file-about
- example.com/#log_file-value
- example.com/#log_level-about
- example.com/#log_level-value

Is there any way to achieve this today? I was trying to figure out if I could write my own python function, but I couldn't easily determine that nor could I determine if there was a way to get the header(s) preceding a content tab.

### Yaml Config

My `mkdocs.yml` has readable slugs:

```yaml
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
```

### Markdown

My markdown is using [content tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/) with a header to delineate:

````markdown

#### log_file

=== "About"

    Specifies an alternative path to use when logging information while the
    client is running.

=== "Value"

    String representing the path to the file.

#### log_level

=== "About"

    Specifies the log level used when logging information while the client
    is running.

=== "Value"

    String representing the level. **[default: info]**
    Choices are off, error, warn, info, debug, trace.
````
