### DISCUSSION TITLE
Why is ```console highlighting shell keywords?

### DISCUSSION THREAD

**Discussion by vermiculus** [squidfunk/mkdocs-material#5682] [Q&A] [answered]
From my read of `pygments/lexers/shell.py`, `BashSessionLexer` isn't adding keyword information, so I'm not sure how `.k` is getting applied to `in` (in `foo in bar`).

Example:

````markdown
```console
# After creating your foo in bar, check out baz
$ qux checkout baz
Checking out baz...
Done!
```
````

is getting processed as
```html
<div class="language-console highlight">
  <pre>
    <span></span>
    <code>
      <span class="gp"># </span>
      After
      <span class="w"> </span>
      creating
      <span class="w"> </span>
      your
      <span class="w"> </span>
      foo
      <span class="w"> </span>
      <span class="k">in</span>      <--- oh no!
      <span class="w"> </span>
      bar,
      <span class="w"> </span>
      check
      <span class="w"> </span>
      out
      <span class="w"> </span>
      baz
```

I can't find an exact example, but it doesn't appear this should be the behavior (hashicorp docs [source](https://github.com/hashicorp/consul/blob/7f3446ececa94e0ced687520c41181430dc1c74d/website/content/docs/k8s/crds/index.mdx#L43), [rendered](https://developer.hashicorp.com/consul/docs/k8s/crds#installation)). I would generally expect there to be *no* further lexing after a `$` or `#` is seen and for the entire remaining text to just show up as a single, simple string.

Is this the fault of `_innerLexerCls = BashLexer` in `BashSessionLexer`? Is there a way to get the output I'm expecting (without redefining a BUNCH of classes just for `language-console`)? Or is this a bug in Pygments that I should report upstream?

Here's my config:
```yaml
# ...
markdown_extensions:
  - toc:
      permalink: "#"
      permalink_title: "Link to this section"
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - smarty
  - pymdownx.details
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - docs/glossary.inc.md
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
```
