### DISCUSSION TITLE
Recommended setup for Woodpecker-CI pipelines?

### DISCUSSION THREAD

**Discussion by Andre601** [squidfunk/mkdocs-material#5729] [Q&A] [answered]
In another discussion did I mention my intent to move away from GitHub Pages and over to Codeberg pages.

With that come a few drawbacks I would need to deal with.  
The biggest one being that Codeberg doesn't offer a GitHub Actions-like solution but instead a own Woodpecker-CI instance I can use.

My question now is... What's the recommended setup here?
Woodpecker-CI allows the direct download and usage of docker images, so I could have something like this here:
```yaml
steps:
  build:
    image: squidfunk/mkdocs-material
    commands:
      - ...
```
The issue with that is, that I also have other dependencies than just Material for MkDocs, so I would need a different solution here to work...

I assume I could use the python image and just pip install everything like I do with GitHub Actions right now?
Would apreciate some input on this.

Woodpecker-CI docs in case you're curious what it has... I have no idea what it all offers tbh...
https://woodpecker-ci.org/docs/next/intro

**Comment by Andre601** [comment, marked as answer]
I've gone with this setup here, which works for my personal needs.
I use the `--site-dir` command override because the target repo hosts other stuff (Codeberg pages doesn't seem to support displaying repos with a pages branch as sub-pages of a custom domain (i.e. `example.com/repo`))

```yaml
steps:
  build:
    image: python
    secrets: [cbtoken]
    commands:
      - chmod -R a+w .
      # Setup Git
      - git config --global --add safe.directory /woodpecker/src/codeberg.org/Andre601/blog-source/website
      - git config --global user.email "github@andre601.ch"
      - git config --global user.name "CI Website Builder"
      - git config --global init.defaultBranch pages
      # Clone and move Target Repository
      - git clone -b pages https://codeberg.org/Andre601/pages.git
      - mv pages website
      - chmod -R a+w website
      # Install Jekyll dependencies and build website
      - pip install -r requirements.txt
      - mkdocs build --site-dir website/blog
      # Set remote repo for target
      - cd website
      - git remote set-url origin https://$CBTOKEN@codeberg.org/Andre601/pages.git
      # Commit and push everything
      - git add --all
      - git commit -m "Update Blog ($( env TZ=Europe/Zurich date +"%d.%m.%Y" )) [SKIP CI]"
      - git push
```
