### DISCUSSION TITLE
"search" not working after deploying to azure webapp

### DISCUSSION THREAD

**Discussion by fuhuifang** [squidfunk/mkdocs-material#5737] [General]
Hi, I have some docs with search functionality. When I build and test it locally, search works perfectly fine. However, after deploying to azure webapp, search got stuck at "initializing search". Does anyone know what might go wrong? 

I'm using a github pipeline for the deployment, and the key steps are:
```yml
- name: build docs
  run: |
    mkdocs build

- uses: azure/login@v1
  # if: github.ref == 'refs/heads/main'
  with:
    client-id: ***
    tenant-id: ***
    allow-no-subscriptions: true

- name: deploy docs
  if: github.ref == 'refs/heads/main'
  working-directory: site
  run: |
    az webapp up -n <name> -g <resource-group> --subscription <subscription-id> --html
```
