### DISCUSSION TITLE
Linking to an image file for the avatar in authors.yml

### DISCUSSION THREAD

**Discussion by lionpeloux** [squidfunk/mkdocs-material#5769] [Q&A]
I am having a hard time understanding how to link to a relative image file in the `.authors.yml` as described in the help [here](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/?h=#adding-authors). In the docs, a web url (`avatar: https://github.com/squidfunk.png`) is used so it is not useful to understand in my case how to set up this path.

My  `.authors.yml` file is under `docs/blog/.authors.yml` as suggested in the docs. My avatar is under  `docs/blog/assets/avatar/ldupeloux.jpg`.

I tried many paths in the `.authors.yml` , but never get a chance to make it work for both the blog index and post page, and for both local `mkdocs serve` and `mkdocs build` (I am using build with `offline plugin enabled`).

I also noticed that I have to define the path to the`.authors.yml` as `authors_file: ./blog/.authors.yml`, that is relative to the site root, and not to the `blog_dir` as explained in the docs [here}(https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/?h=authors_file#+blog.authors_file). Indeed, If i define it to `authors_file: ./.authors.yml` mkdocs complains that the author `ldupeloux` could not be found.

How should I specify the avatar path ? Relative to the site root ? Relative to the  `.authors.yml` ? And what about the  `authors_file` ?
Many thanks for your help. I'am quite confused about how it is working, despite all my readings, searching, and tests !

```` yml
ldupeloux:
  name: Lionel du Peloux
  description: Habitat Individuel
  # avatar: ./../../../../../blog/assets/avatar/ldupeloux.jpg
  # avatar: ./blog/assets/avatar/ldupeloux.jpg
  avatar: ./assets/avatar/ldupeloux.jpg
````
