### DISCUSSION TITLE
TOC/Navigation Depth

### DISCUSSION THREAD

**Discussion by pieterhelsen** [squidfunk/mkdocs-material#5801] [Q&A] [answered]
First off, let me say I love MkDocs and the Material framework. It's really made my life a whole lot easier.

That said, I've been trying to get TOC depth (or navigation depth) to work in my Material MkDocs project, but don't seem to be getting far. 

I would like to limit the number of headers shown in the TOC/sidebar navigation, but using the below (as suggested by [MkDocs](https://www.mkdocs.org/user-guide/choosing-your-theme/#overriding-template-blocks)) does not seem to do the trick. 
```
theme: 
  - navigation_depth: 3
```

Does anyone know how I can limit the number of headers in the sidebar navigation to only show level 1 to 3?

For reference, this is (part of) my config:

```
theme: 
  name: material
  navigation_depth: 2
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - toc.integrate
```

**Comment by squidfunk** [comment, marked as answer]
Thanks! If I understand correctly, your exact use case is mentioned in [our documentation](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#+toc.toc_depth):

``` yaml
markdown_extensions:
  - toc:
      toc_depth: 3
```

We'll be reworking our documentation to make it more apparent.
