### DISCUSSION TITLE
Problem with using squidfunk/mkdocs-material within Github Actions

### DISCUSSION THREAD

**Discussion by simondueckert** [squidfunk/mkdocs-material#5814] [General]
I try to use the docker image squidfunk/mkdocs-material within a Github Action and get an error message "". This is the part of the workflow yaml file:

```
   # Create Web Version (mkdocs)
   - uses: docker://squidfunk/mkdocs-material
      with:
          mkdocs_version: 'latest'
          configfile: './de/mkdocs.yml'
```

I suppose there is something wrong with the configfile line? The path and file exists, it is checked out from the github repo? What's wrong?

**Comment by squidfunk** [comment]
I'm not sure what GitHub Action you are using and I've never seen those configuration options – they were not created by us.

**Reply by simondueckert** [reply]
I think I've found it "somewhere on the internet" :) Before I used it without the configfile parameter which I've swiched back now again:

```
      # Create Web Version (mkdocs)
      - uses: docker://squidfunk/mkdocs-material
        with:
          mkdocs_version: 'latest'
```

I still get the same error message `Error: Config file 'mkdocs.yml' does not exist.` (because mkdocs.yml is in ./de/mkdocs.yml. What is the correct configuration in the Github Action for that?
