### DISCUSSION TITLE
Interesting behaviour with Page icons

### DISCUSSION THREAD

**Discussion by Andre601** [squidfunk/mkdocs-material#5911] [Q&A]
I've noticed a interesting behaviour with page icons. This being that a page icon won't be displayed within a Nav tab, even if it was the only page within said tab.
Only when turning this page into a index page, putting it into a folder and then define it in the nav will it work.

Is there a way to display the page icon within the nav, even when the page itself isn't an index page for that tab?

Here's a mkdocs.yml nav setup I have:
```yaml
nav:
  - Home: 
    - index.md # Displays icon in Nav tabs
    - commands.md
  - Profiles:
    - profiles/index.md # Displays icon in Nav tabs
    - Formatting: profiles/formatting.md
    - Placeholders: profiles/placeholders.md
  - API:
    - api/index.md # Displays icon in Nav tabs
    - Changelog: api/changelog.md
  - Examples: examples.md # Won't display icon. Only "Examples: examples/index.md" will.
  - PlaceholderAPI: placeholderapi.md # Won't display icon. Only "Examples: placeholderapi/index.md" will.
```

**Comment by DrVrej** [comment]
I am having this issue as well

**Reply by alexvoss** [reply]
Putting the Markdown file into a folder and calling it `index.md` does not work for you? Seems like a sensible workaround to me. I am not sure the tabs were ever meant to work for anything other than sections. Note [what the description for the `navigation.tabs` feature says](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+tabs#navigation-tabs).

**Reply by DrVrej** [reply]
Yup that would be the simplest solution, was hoping maybe there is a way around it to keep my files organized the way it is right now, thank you for the help though!

**Reply by kamilkrzyskow** [reply]
If the old file structure preservation is a must, then you could use this "hack" @DrVrej, and have both the `other/index.md` file and the `other.md`.

```yaml
site_name: My Docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes

nav:
  - Home:
    - index.md
  - Other:
    - other/index.md

not_in_nav: |
  other.md

markdown_extensions:
  - pymdownx.snippets
```

To not duplicate content use [Snippets](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#snippets) or the macro plugin should also work. There are some limitations, concerning order of execution, but if you run into them then it would be better to use the default approach or setup a custom one with [hooks](https://www.mkdocs.org/user-guide/configuration/#hooks) etc..

`other/index.md`
```md
--8<-- "docs/other.md"
```

---

[example-with-snippets.zip](https://github.com/user-attachments/files/17686564/example-with-snippets.zip)
