### DISCUSSION TITLE
Navigation menu does not scroll

### DISCUSSION THREAD

**Discussion by koshelekapi** [squidfunk/mkdocs-material#5926] [Q&A]
Hello!

We use MM for some time, and we upgraded a version to 9.2.5 yesterday. And the problem is that left navigation menu stop scrolling down( it looks like it is locked. You can find screencast attached.

Our configuration:
```
# Project information
site_name: Koshelek documentation storage
site_url: https://developers.koshelek.app/
docs_dir: 'docs'
site_dir: 'site'
site_description: Koshelek API and integration documentation portal

theme:
  name: material
  language: ru
  logo: assets/koshelekapi.png
  custom_dir: docs/overrides
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    alternate: octicons/globe-16
  features:
  # - navigation.sections # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-sections
    - navigation.indexes
  # - navigation.footer
    - navigation.tracking
    - navigation.expand
    - navigation.top

extra_css:
  - css/extra.css
  - css/extra-swagger-ui.css

extra_javascript:
  - javascripts/extra.js

# Portal Structure
nav:
... our navigation there...
    
# Extensions
markdown_extensions:
  - admonition
  - attr_list # https://squidfunk.github.io/mkdocs-material/reference/images/
  - md_in_html # https://squidfunk.github.io/mkdocs-material/reference/images/
# - plantuml_markdown
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic # https://squidfunk.github.io/mkdocs-material/reference/formatting/#highlighting-changes
  - smarty # https://python-markdown.github.io/extensions/smarty/
  - pymdownx.highlight:
      auto_title: true
      linenums: false
  - pymdownx.tabbed: # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets # https://facelessuser.github.io/pymdown-extensions/extensions/snippets/

extra:
  analytics:
    provider: google
    property: G-3ENGW2T389
  generator: false

# Plugins
plugins:
  - search
  - include-markdown
# - social
  - swagger-ui-tag: # https://github.com/blueswen/mkdocs-swagger-ui-tag
      docExpansion: list
      defaultModelExpandDepth: 7
      defaultModelsExpandDepth: 7
      extra_css: 
        - css/extra-swagger-ui.css
  - build_plantuml:
      render: 'server' # or "local" for local rendering
      bin_path: '/usr/local/bin/plantuml' # ignored when render: server
      server: 'http://www.plantuml.com/plantuml' # official plantuml server
      disable_ssl_certificate_validation: true # for self-signed and invalid certs
      output_format: 'png' # or "png"
      diagram_root: 'docs/diagrams' # should reside under docs_dir
      output_folder: 'out'
      input_folder: 'src'
      input_extensions: '' # comma separated list of extensions to parse, by default every file is parsed
  - i18n:
      default_language: ru
      default_language_only: false
      material_alternate: true
      docs_structure: folder
      fallback_to_default: true
      languages:
        ru:
          name: Русский
          link: /ru
          build: false
          locale: ru
        en: 
          name: English
          link: /en
          build: true
          locale: en
      nav_translations:
        en:
         ... navigation translations there...
      reconfigure_material: true
      reconfigure_search: true
```
