### DISCUSSION TITLE
How to zoom MathJax display math without zooming inline via CSS?

### DISCUSSION THREAD

**Discussion by andynameistaken** [squidfunk/mkdocs-material#5969] [Q&A]
This zooms both
```css
.MathJax {
    zoom: 120%;
}
```

This doesn't work:
```css
.MathJax_Display {
    zoom: 120%;
}
```
