### DISCUSSION TITLE
Faint grey line under horizontal ruler

### DISCUSSION THREAD

**Discussion by rkelleyrtp** [squidfunk/mkdocs-material#5982] [Q&A]
Greetings all,

I am trying to use some custom CSS code to tailor the horizontal ruler using the material theme.  However, I keep seeing a faint grey line at the bottom of the ruler.  How can I disable/remove that line?  I searched the scss files for any reference to horizontal ruler definitions but could not find any.  I am still learning CSS so I probably just missed it somewhere.

As an exaggerated example:
```
hr {
    display: block;
    height: 51px;
    border: 0;
    border-top: 1px solid #ADF;
    margin: 1em 0;
    padding: 0;
}
```

Thank you.

**Comment by squidfunk** [comment]
We use `border-bottom` to style the ruler:

https://github.com/squidfunk/mkdocs-material/blob/2ba35383e2a49264231560d81589627c1864fdf3/src/assets/stylesheets/main/_typeset.scss#L152-L156

Thus, this should do the trick:

``` css
.md-typeset hr {
    display: block;
    height: 51px;
    border: 0;
    border-bottom: 1px solid #ADF;
    margin: 1em 0;
    padding: 0;
}
```

Note that you should scope your rules in `.md-typeset` to match specificity of the base definitions.
