### DISCUSSION TITLE
Problems getting Chinese search to work without warnings

### DISCUSSION THREAD

**Discussion by RonaldLN** [squidfunk/mkdocs-material#5992] [Q&A] [answered]
The following is the information displayed in the terminal

```bash
$ mkdocs gh-deploy --force
INFO    -  Option search.lang 'zh' is not supported, falling back to 'en'
WARNING -  Language 'zh' is not supported by lunr.js, not setting it in the 'plugins.search.lang' option
Building prefix dict from E:\Github\MyPamphlet\jieba_dict\dict.txt.big ...
DEBUG:jieba:Building prefix dict from E:\Github\MyPamphlet\jieba_dict\dict.txt.big ...
```
![无标题](https://github.com/squidfunk/mkdocs-material/assets/120019179/0eda4154-c25b-4d65-9f95-85441968e6bd)

**Comment by squidfunk** [comment]
Not sure without knowing how you configured the project. Please create a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) and attach it to this discussion.

**Reply by RonaldLN** [reply]
Is that it? I don't know if I made a mistake when creating a reproduction
![无标题](https://github.com/squidfunk/mkdocs-material/assets/120019179/6a768f85-f683-4650-ab3e-68ab354da898)
[9.3.1-search-cant-support-chinese.zip](https://github.com/squidfunk/mkdocs-material/files/12583106/9.3.1-search-cant-support-chinese.zip)

**Reply by squidfunk** [reply, marked as answer]
Chinese search support is not implemented via Lunr.js but via a custom impementation that segments text during the build. [Here's an explanation why this is not supported in Lunr.js](https://github.com/mkdocs/mkdocs/issues/2509#issuecomment-882689383). If you just remove the `lang` setting from the search plugin, Chinese search should work correctly, as the search plugin will use `jieba` automatically.

**Reply by RonaldLN** [reply]
Do you mean that I should be like this？
Change 
```yaml
- search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      jieba_dict: jieba_dict/dict.txt.big
      jieba_dict_user: jieba_dict/user_dict.txt
      lang: 
        - zh
        - ja
        - en
```
 to
```yaml
- search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      jieba_dict: jieba_dict/dict.txt.big
      jieba_dict_user: jieba_dict/user_dict.txt
      lang: 
        - ja
        - en
```

**Reply by RonaldLN** [reply]
Oh, I seem to understand. Should it be removing the entire `lang` setting?

**Reply by squidfunk** [reply]
Yes.

**Reply by RonaldLN** [reply]
I just discovered another issue. The site language selector I am using is based on the i18n plugin,
This is part of my configuration
```yaml
plugins:
  - i18n:
      default_language: en
      material_alternate: true
      languages:
        zh:
          name: 简体中文
          build: true
        en:
          name: English labels (英文标签)
          build: false
```
Then it will cause similar errors as before
![无标题](https://github.com/squidfunk/mkdocs-material/assets/120019179/bd86f95a-277a-48c6-94bf-fce69088bcad)
And when I remove this plugin, there won't be this error message.
I use this plugin instead of [this](https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/)
because it allows me to share the same version of `.md` files in both language modes, while setting up versions in both languages for some documents,
for example,
```txt
└─doc
    ├─index.md
    ├─index.zh.md
    ├─doc1.md
    └─doc2.md
```
Like this, the index page will have two language versions, while doc1 and doc2 share the same version in both languages.
So my question is, can functions like this be implemented without the i18n plugin, or can error messages be resolved with using the i18n plugin (thus enabling normal use of Chinese search support)

**Reply by RonaldLN** [reply]
I just found out that the plugin for mkdocs static i18n has been updated to a new version. After 1.0.0, there is an option:
[Setting up search](https://ultrabug.github.io/mkdocs-static-i18n/setup/setting-up-search/)
After I set this option to false, the previous error message disappeared.
But I found another issue, which is that it seems that the search function does not support Chinese?
![a](https://github.com/squidfunk/mkdocs-material/assets/120019179/0e633095-af2b-456b-94c6-5545cd9f234c)

**Reply by squidfunk** [reply]
Please raise this issue to the maintainers of the i18n plugin.

**Reply by squidfunk** [reply]
So, to expand on that: the i18n plugin has to do some tricky hacks to make all of this work, and there have been problems with this plugin and search in the past. Our recommendation is to split you documentation into separate versions, as laid out in #2346

That being said, we've released [the projects plugin](https://squidfunk.github.io/mkdocs-material/setup/building-an-optimized-site/#built-in-projects-plugin) which makes working with multiple adjacent projects simpler, and will add first class support for multi-language documentation in the coming months. [The roadmap is here](https://github.com/squidfunk/mkdocs-material/discussions/5800).

**Reply by squidfunk** [reply]
Additionally, I've justed tested again. The following configuration works:

``` yaml
site_name: My Docs

theme:
  name: material
  language: zh

plugins:
  - search:
      jieba_dict: jieba_dict/dict.txt.big
      jieba_dict_user: jieba_dict/user_dict.txt
```

![screenshot-localhost-8000-1694584950364](https://github.com/squidfunk/mkdocs-material/assets/932156/4b8539a6-39c0-42d1-982b-2ad4330bea91)

**Reply by RonaldLN** [reply]
But I just tried to cancel the configuration of the i18n plugin, and in the end, the Chinese search results also showed no corresponding search results

**Reply by RonaldLN** [reply]
Oh, sorry, I didn't see your last reply. Since you were able to use it successfully, it may be due to some issues with my configuration or usage process. I'll see what the reason is later

**Reply by RonaldLN** [reply]
And, by the way, this is a screenshot of my current webpage using Chinese search
![无标题](https://github.com/squidfunk/mkdocs-material/assets/120019179/fd1ce159-8003-4167-a8df-cc2c84816219)
![无标题1](https://github.com/squidfunk/mkdocs-material/assets/120019179/18a0f46b-18f4-475e-b2e0-e1457373ce5f)
![无标题2](https://github.com/squidfunk/mkdocs-material/assets/120019179/92e2e542-5c06-4c7d-8c7a-17f267acf55d)

**Reply by RonaldLN** [reply]
I just tested it , according to your configuration, if the `theme` is set to `zh`, Chinese search can work normally. 

However, if the `theme` is not set to `zh`, like this,

```yaml
site_name: My Docs

theme:
  name: material
  # language: zh

plugins:
  - search:
      jieba_dict: jieba_dict/dict.txt.big
      jieba_dict_user: jieba_dict/user_dict.txt
```

Chinese search seems to not work properly

**Reply by squidfunk** [reply]
Yes. This is because setting `language: zh` [correctly configures the search separator](https://github.com/squidfunk/mkdocs-material/blob/502a517e2e7774c0518a60f0c8bf502b25671284/src/partials/languages/zh.html#L56), which you would otherwise need to do manually. [I recommend reading our blog article on how to set this up](https://squidfunk.github.io/mkdocs-material/blog/2022/05/05/chinese-search-support/#configuration). Nonetheless, we should better clarify this in the documentation ☺️ If you're using another language, you need to add:

``` yaml
plugins:
  - search:
      separator: '[\s\u200b\-]'
```
