### DISCUSSION TITLE
How can I make the table of content appear for each post in my blog?

### DISCUSSION THREAD

**Discussion by RonaldLN** [squidfunk/mkdocs-material#5998] [Q&A] [answered]
How can I make the table of content appear for each post in my blog like [this](https://squidfunk.github.io/mkdocs-material/blog/2022/09/12/blog-support-just-landed/)?
![无标题](https://github.com/squidfunk/mkdocs-material/assets/120019179/ad440296-5b77-4dd6-afc4-57a2b7eadc88)
This is part of my configuration in `mkdocs.yml` 
```yaml
markdown_extensions:
  - toc:
      permalink: true

plugins:
  - blog:
      blog_dir: .
      blog_toc: true
      post_date_format: full
      archive_toc: true
      categories_toc: true
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
      pagination_keep_content: true
      draft_if_future_date: true
```
