### DISCUSSION TITLE
plugins: optimize is not installed

### DISCUSSION THREAD

**Discussion by Arexils** [squidfunk/mkdocs-material#6035] [Q&A] [answered]
I'm trying to use the plugin that build-in, but I'm getting an error. 

command: `mkdocs serve`
```
ERROR   -  Config value 'plugins': The "optimize" plugin is not installed

Aborted with 1 configuration errors!
```
my snippet code
```yml
plugins:
  - optimize:
      enabled: !ENV [CI, false]
  - minify
  - search
```

my dependencies in poetry:
```toml
mkdocs = "^1.5.2"
mkdocs-material = {extras = ["imaging"], version = "^9.3.1"}
mkdocs-minify-plugin = "^0.7.1"
pymdown-extensions = "^10.3"
```
https://squidfunk.github.io/mkdocs-material/plugins/optimize/#config.enabled
