### DISCUSSION TITLE
Why are icons no longer rendering?

### DISCUSSION THREAD

**Discussion by danielchalef** [squidfunk/mkdocs-material#6055] [Q&A] [answered]
Icons are no longer rendering when used with, I think, the `superfences` extension. I'm seeing this on both our docs site and the Mkdocs Material site.

@squidfunk - fyi this is impacting the Material docs site, too.

Tested on MacOS 13.4.1 with:
- Safari Version 16.5.2 (18615.2.9.11.10)
- Chrome 116.0.5845.187

Below are two examples from https://squidfunk.github.io/mkdocs-material/ 

<img width="813" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/131175/2058b63e-6691-4689-83a3-5af3665e2710">

<img width="706" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/131175/91eab096-9a6a-4120-8ae4-051331e0bbdc">

**Comment by squidfunk** [comment]
Thanks for reporting. We're aware of the issue, see #6054. Please use version 9.3.2, while we fix the issue on `master`.

**Reply by danielchalef** [reply]
Thanks. Is there a new version of Insiders? I've just pulled `mkdocs-material==9.3.2+insiders.4.42.0` and still see the issue.

**Reply by squidfunk** [reply]
Nope, the latest Insiders release should also work. Are you sure that you pulled the correct version and not `master`? The latest version has the old directory structure which works with the current `mkdocs-material-extensions` version, see [here](ree/9.3.2-insiders-4.42.0/src).

**Reply by squidfunk** [reply]
By the way, I'm very close to pushing a fix. We're moving the extension into our repository, see https://github.com/squidfunk/mkdocs-material/commit/00c5fb17662fcf29fe4393ba4df5272bf5b2079d

**Comment by squidfunk** [comment, marked as answer]
This issue does not occur on the latest release, but only on `master`. To fix it, change the configuration of `pymdownx.emoji`:

__Now__:

``` yaml
- pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
```

__Before__:

``` yaml
- pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
```

We're working on an upgrade path that will be part of 9.4.0, so `materialx` will work again in 9.4.0, but print a deprecation message. Going forward, `material.extensions` is the new namespace where our Markdown extensions will live
