### DISCUSSION TITLE
How do Navigation subtitles look?

### DISCUSSION THREAD

**Discussion by Andre601** [squidfunk/mkdocs-material#6100] [Q&A] [answered]
The insiders page lists "Navigation Subtitles" as one of the exclusive features, but there doesn't seem to be an example to look at.

I went through all the doc pages in the hope to see an example, but I couldn't find anything...

So, how do they look like?

**Comment by alexvoss** [comment, marked as answer]
They look like the example below. We are working on creating more examples and have a compiled version so everyone can see the features in action without having to compile them.

<img width="705" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/4134224/2adacb32-72bf-401d-913a-9d2451f137de">

**Reply by Andre601** [reply]
I honestly expected a line under the h1 title... But after thinking about it can I see why this wouldn't be a doable thing...

**Reply by TJohnson93** [reply]
I mean, could be added through custom css. For Example I've added a horizontal line below the H2 and H3 headers like GitHub.

``` css
/* ******************************************************** */
/* Header Overides */
/* ******************************************************** */
h2 { /* Add Line under Header like GitHub */
  margin-bottom: 0px;
  border-bottom: 1px solid var(--md-default-fg-color--lightest);
}

h3 { /* Add Line under Header like GitHub */
  margin-bottom: 0px;
  border-bottom: 1px solid var(--md-default-fg-color--lightest);
}
```

![image](https://github.com/squidfunk/mkdocs-material/assets/6167090/ef53adad-7a0f-4cf9-91e9-0a00c62078ed)

**Reply by TJohnson93** [reply]
Here you go: 

``` css
.md-typeset h1 { /* Add Line under Header like GitHub */
  margin: 0px;
}

.page-subtitle {
  font-style: italic;
  font-size: 0.9em;
  color: rgb(168, 168, 168);
}
```

``` markdown
# Header 1

Subtitle Ipsum
{ .page-subtitle }
```

![image](https://github.com/squidfunk/mkdocs-material/assets/6167090/e47b7abc-417a-4c39-b7af-c3bc97e872d5)
