### DISCUSSION TITLE
Navigation status badge for expandable navigation items

### DISCUSSION THREAD

**Discussion by miciddymac** [squidfunk/mkdocs-material#6126] [Ideas]
Would it be possible to add a navigation status badge to expandable navigation items?

![image](https://github.com/squidfunk/mkdocs-material/assets/130837065/ec1beac4-9e89-4c6a-932d-6ed2d0a39dce)

**Comment by alexvoss** [comment]
Not sure what you mean by a 'navigation status badge'? When would this appear and what would it indicate?

**Reply by miciddymac** [reply]
The navigation status badge was described here 
![image](https://github.com/squidfunk/mkdocs-material/assets/130837065/ba78ba68-abc2-40e2-bc8c-d99b50b17b63)

And can be set per page - described here: https://squidfunk.github.io/mkdocs-material/reference/?h=navigation+status#setting-the-page-status
![image](https://github.com/squidfunk/mkdocs-material/assets/130837065/39f37328-c8dc-44f2-adb5-e218250d3601)

**Reply by alexvoss** [reply]
Ah, ok, now I get you. Am I right to assume that your section headings do not have associated pages? If you use [section index pages](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages) then you can add the statuses to their headers:

```
site_name: My Docs

theme: 
  name: material
  features:
    navigation.indexes

extra:
  status:
    new: Recently Added

nav:
  - "Home":
    - index.md
  - "Section":
    - sect2/index.md
    - "Subpage": sect2/sect21.md
```

Then, in `sect2/index.md`:

```
---
status: new
---
```
