### DISCUSSION TITLE
Social Card not working on Github pages

### DISCUSSION THREAD

**Discussion by gopisaba** [squidfunk/mkdocs-material#6130] [Q&A]
We recently migrated to mkdocs and hosting it on the Github pages.
We are using github actions to build and publish the page.

```yaml
# .github/workflows/docs-release.yml
...
      - name: Install Python Packages
        run: pip install -r requirements.txt

      - name: Build Documentation
        run: mkdocs build

      - name: Upload Github Artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
```

We want to setup the social card. So I configured like, 

```yaml
# mkdocs.yml
...
plugins:
  - search
  - social:
      cache_dir: site/.cache/plugin/social
...
```

I could see the cards and fonts are generated on `site/.cache/plugin/social` but when we share the link, it still shows as github page. Could someone please help me?
