### DISCUSSION TITLE
favicon

### DISCUSSION THREAD

**Discussion by Arexils** [squidfunk/mkdocs-material#6135] [Q&A] [answered]
```
  docs/
  ├─  dir_1           
  ├─  ...        
  ├─  favicon.ico
  └─  assets/
    └─  logo.svg      
```

mkdocs.yml
```yaml
docs_dir: docs
site_dir: site

theme:
  ...
  logo: assets/logo.svg
  favicon: favicon.ico
  ...
```
The problem is that locally it shows the favicon in the browser, but after deploy it doesn't show it anymore.

```dockerfile
...
RUN mkdocs build
ENTRYPOINT ["python", "-m", "http.server", "8008", "--directory"]
CMD ["./site"]
```
<img width="501" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/20801433/a6273f5f-aef4-43b2-9820-857fa1a6c4ee">
