### DISCUSSION TITLE
Status Component like Confluence

### DISCUSSION THREAD

**Discussion by TJohnson93** [squidfunk/mkdocs-material#6165] [Ideas]
A component like the Status component in Confluence. Would be good to see it be similar to the admonitions component in which there are some standard ones but able to be customised for additional options.

![images (22)](https://github.com/squidfunk/mkdocs-material/assets/6167090/2b033323-dfc5-4a5a-b6ed-1cb112a75ebf)

It would also make sense to work inline with text like the `code block`.

Some examples of use cases:

* Display priorities
* Visual display of risk levels
* Implementation status levels (Implemented, Not Implemented, In Progress)
* Documentation status (e.g., Draft, In Progress, Review, Published, Retired)

> Even if it's similar looks to GitHub Labels

I've searched around quite a bit to see if there is any extension or plugin to introduce this component, however have come up short so far.

**Comment by alexvoss** [comment]
Hi, thanks for reaching out. Is this [tags](https://squidfunk.github.io/mkdocs-material/plugins/tags/) but at the level of individual parts of content instead of just the whole page? ([tags are added in the front-matter](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags#adding-tags)) Apologies if I am holding the wrong end of the stick - had minimal exposure to Confluence...

**Reply by TJohnson93** [reply]
This is more of a visual effect than anything else and sits in-line with the documentation content. I've created some custom CSS at the moment to achieve this output but a native feature would be pretty sweet: 

``` css
/* ******************************************************** */
/* Status Pills */
/* ******************************************************** */
.status-pill {
  background-color: rgb(164, 164, 164);
  border: none;
  color: white;
  padding: 2px 7px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  border-radius: 5px;
  font-size: 0.85em;
  margin: 0px 3px;
  text-transform: uppercase;
}

.status-pill-primary {
  background-color: rgb(62, 138, 204);
}

.status-pill-success {
  background-color: rgb(88, 185, 87);
}

.status-pill-info {
  background-color: rgb(86, 192, 224);
}

.status-pill-warning {
  background-color: rgb(242, 174, 67);
}

.status-pill-danger {
  background-color: rgb(219, 82, 75);
}
```

In the markdown file, I use a `<span>` tag and add the classes needed to change the colour.

``` html
<span class="status-pill">:material-bookmark-check: General information</span> <br/>
<span class="status-pill status-pill-primary">General or Key Note</span>  <br/>
<span class="status-pill status-pill-info">Informational</span>  <br/>
<span class="status-pill status-pill-success">Success or Positive</span>  <br />
<span class="status-pill status-pill-warning">Warning or Alert</span>   <br/>
<span class="status-pill status-pill-danger">Danger or Critical</span>  <br/>
```

Results in the following look:

![image](https://github.com/squidfunk/mkdocs-material/assets/6167090/3742dc8b-21df-444d-ac48-c4475af77e74)

Even works with icons
