### DISCUSSION TITLE
The logo does change according to the theme, but sometimes disappears

### DISCUSSION THREAD

**Discussion by Xenepix** [squidfunk/mkdocs-material#6221] [Q&A]
Hello, I would like to change my logo according to the theme,

I want to change my logo according to the theme (black logo for the white theme and white logo for the dark theme).
To do this, I've overwritten the logo.html file:
(I'm not at all sure about my html file, I built it a bit like Frankenstein)
```html
<div class="md-header__logo" data-md-component="palette">
{% for option in config.theme.palette %}
<input class="md-option" data-md-color-media="{{ option.media }}" data-md-color-scheme="{{ scheme | replace(' ', '-') }}" data-md-color-primary="{{ primary | replace(' ', '-') }}" data-md-color-accent="{{ accent | replace(' ', '-') }}" {% if option.toggle %} aria-label="{{ option.toggle.name }}" {% else %} aria-hidden="true" {% endif %} type="radio" name="__logo" id="__logo_{{ loop.index }}">
<label class="md-header__button md-icon" title="{{ option.logo }}" for="__logo_{{ loop.index0 or loop.length }}" hidden>
      {% include "assets/napse_invest_logo_black.svg" %}
    </label>
{% endfor %}
  </div>
```

The logo does change according to the theme, but when I switch sections, the logo disappears (e.g. if I go to "contributing"), and if I click on the section again, the logo appears correctly.

1st click on contributing (from 'home' section)
![image](https://github.com/squidfunk/mkdocs-material/assets/11559668/db702542-c107-41fa-b0d1-a514e3fab22b)
2nd click on contributing (from 'contributing' section)
![image](https://github.com/squidfunk/mkdocs-material/assets/11559668/90ff02bd-69b6-4d2f-95e4-28b985968255)

Here is the "theme" section of [my mkdocs.yml](https://github.com/napse-invest/django-napse/blob/feature/mkdocs/mkdocs.yml) file:
```yml
theme:
  name: 'material'
  custom_dir: theme
  favicon: 'theme/assets/napse_logo_white.svg'
  language: 'en'
  palette:
    # Palette toggle for light mode
    - media: "prefers-color-scheme: light"
      scheme: default
      primary: 'white'
      logo: 'theme/assets/napse_invest_logo_black.svg'
      toggle:
        # icon: material/toggle-switch
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "prefers-color-scheme: dark"
      scheme: slate
      primary: black
      logo: 'theme/assets/napse_invest_logo_white.svg'
      toggle:
        # icon: material/toggle-switch-off-outline
        icon: material/toggle-switch
        name: Switch to light mode
```

Do you have any ideas to help me? I'll take it!

PS:
If you want to go through my code, the repository is open-source: https://github.com/napse-invest/django-napse/tree/feature/mkdocs
