### DISCUSSION TITLE
What CSS needs to be modified to extend the width of a table to full parent?

### DISCUSSION THREAD

**Discussion by Andre601** [squidfunk/mkdocs-material#6320] [Q&A]
I currently encounter a smaller inconvenience where the table doesn't seem to expand to the full width of its parent.

This is noticable when hovering over a table row, which highlights it. The highlight itself does not cover the full width. Here's a screenshot demonstrating this:
![2023-11-11](https://github.com/squidfunk/mkdocs-material/assets/11576465/04ed5480-2b8c-455d-9573-c6aae8b64bf2)

I've tried finding out what CSS is used here to modify it, but so far have not found anything that could help.

The table itself is within a admonition block of a custom type (`wiki`). CSS used so far is this:
```css
.admonition.wiki .md-typeset__table {
    padding: 0;
    width: 100%;
}

.md-typeset .admonition.wiki thead {
  display: none;
}

/* Tried this here, but doesn't work because wrong type 
 * Not sure if I can just change type here or if it would
 * cause problems... */
.md-typeset .admonition.wiki tbody {
  width: 100%;
}

.md-typeset .admonition.wiki table {
  border: 0;
}

.md-typeset .admonition.wiki tr,
.md-typeset .admonition.wiki td {
  border: 0;
  border-top: 0;
  padding-top: 2px;
  padding-bottom: 2px;
}

.admonition.wiki img {
  display: block;
  margin-left: auto;
  margin-right: auto;
  max-width: 75%;
}

.md-typeset .admonition.wiki {
  border-color: var(--md-typeset-table-color);
}

.md-typeset .wiki > .admonition-title,
.md-typeset .wiki > summary {
  background-color: #00000000;
  text-align: center;
  padding-left: .6rem;
}

.md-typeset .wiki > .admonition-title::before,
.md-typeset .wiki > summary::before {
  background-color: #00000000;
  -webkit-mask-image: none;
          mask-image: none;
  top: 0;
  width: 0;
}

.md-typeset img {
  max-width: 45%;
}

.md-nav__item--section > .md-nav > .md-nav__list {
  margin-left: .5rem;
}
```
