### DISCUSSION TITLE
Optimize CSS size

### DISCUSSION THREAD

**Discussion by weeblr** [squidfunk/mkdocs-material#6349] [Q&A] [answered]
Hello,

I have done a simple website with a few pages, with a simple mkdocs.yml (see below) and I'm surprised to find that the compiled main.css file is a massive 126KB (zips down to about 20+K), with another 13KB palette.css file as well.

Looking into it, it appears to include CSS that's not at all used on the site. 

In addition, commenting out all features and markdown_extensions do not change at all the built CSS files, the CSS is exactly the same.

Is there a way to apply purgeCSS or similar as part of the build to get rid of all unused selectors?

Thanks and regards

mkdocs.yml:

```
site_name: Example
site_url: https://www.example.com/
site_dir: public
theme:
  name: material
  custom_dir: overrides/
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: white
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: https://assets.example.com/logo.png
  favicon: _images/favicon-32x32.png
  features:
    # Instant navigation breaks Cloudflare email protection
    #    - navigation.instant
    #    - navigation.instant.progress
    - navigation.tabs
    - navigation.path

plugins: []

extra:
  homepage: https://www.example.com

extra_css:
  - '_assets/fonts.css'
#  - '_assets/styles.css'
#extra_javascript:
#  - '_assets/code.js'

markdown_extensions:
  - tables
  - meta
#  - admonition
  #  - codehilite:
  #      linenums: true
  #  - footnotes
#  - attr_list
  - pymdownx.betterem:
      smart_enable: all
  #  - pymdownx.caret
  #  - pymdownx.critic ## does not play well with blade templates comments syntax
  - pymdownx.details
  #  - pymdownx.inlinehilite
  #  - pymdownx.mark
  #  - pymdownx.superfences
  #  - pymdownx.tasklist:
  #      custom_checkbox: true
  #- pymdownx.tilde

nav:
  - Home: 'index.md'
  - Page 1: 'content/index.md'
  - Page 2: 'content/page-2.md'
  - Page 3: 'content/page-3.md'
  - About: 'about.md'

```
