### DISCUSSION TITLE
Mention "spoilers in the docs where you present "Collapsible blocks"

### DISCUSSION THREAD

**Discussion by couleurm** [squidfunk/mkdocs-material#6400] [Ideas]
When searching spoilers I couldn't find, and it'd be cool to mention the term somewhere so people who search for that

https://squidfunk.github.io/mkdocs-material/reference/admonitions/#collapsible-blocks

**Comment by SPyofgame200** [comment]
I also tried to do something like that, but I found a workaround

```html
#### <p hidden class="fake-toc"> Code </p>
```

combined with `extra_css`

```css
h1:has(.fake-toc),
h2:has(.fake-toc),
h3:has(.fake-toc),
h4:has(.fake-toc),
h5:has(.fake-toc),
h6:has(.fake-toc) {
    float: left;
}

.fake-toc {
    margin: 0;
    padding: 0;
}

.fake-toc+.headerlink {
    float: left;
    margin-left: -1.5em !important;
}
```

that works pretty nice

![image](https://github.com/squidfunk/mkdocs-material/assets/52689671/affd7a7c-ab7d-4bbc-8cbf-71d19e9bf1b8)
