### DISCUSSION TITLE
Custom icons for Tags are not working

### DISCUSSION THREAD

**Discussion by ankithabangar** [squidfunk/mkdocs-material#6432] [Q&A] [answered]
### Contribution guidelines
* [x]  I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree
### I want to suggest an idea and checked that ...
* [x]  ... to my best knowledge, my idea wouldn't break something for other users
* [x]  ... the documentation does not mention anything about my idea
* [x]  ... there are no open or closed issues that are related to my idea

### Description
I followed the instructions to add custom icons for Tags but the feature is not working. I have added icons to all the tags but it is rendering only for one tag even for that only a square box is visible. I tried using the icon elsewhere in the website and I am able to see the icon. Please check the screenshots added. I am also getting weird code along with the icon above the header.

### Related links

- [Setting up tags](https://github.com/squidfunk/mkdocs-material/blob/master/docs/setup/setting-up-tags.md)
- [Changing the logo and icons](https://github.com/squidfunk/mkdocs-material/blob/master/docs/setup/changing-the-logo-and-icons.md#additional-icons)
- [Cant't figure out how to use custom icons](https://github.com/squidfunk/mkdocs-material/discussions/3683)
- [Add tags icons on tags index](https://github.com/squidfunk/mkdocs-material/issues/4100)

### Reproduction

This is my `mkdocs.yml` file
```
site_name: ""
docs_dir: docs/

markdown_extensions:
  - abbr # to add tooltips
  - attr_list # to add annotations, align images.
  - md_in_html # to add annotations
  - pymdownx.arithmatex: # To add Math functionalities
      generic: true
  - pymdownx.emoji: # To add custom icons
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  # This configuration enables syntax highlighting on code blocks and inline code blocks,
  # and allows to include source code directly from other files.
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      # This appends content of abbreviations.md to all markdown files
      auto_append:
        - docs/includes/abbreviations.md
  - pymdownx.superfences: # to add annotations and charts
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
  - pymdownx.tabbed:
      alternate_style: true
  - tables

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

plugins:
  - search
  - tags:
      tags_file: tags.md
      tags_allowed:
        - Bevel gears
        - Cam contacts
        - Cylindrical gears
        - Developer mode
        - Examples
        - GUI
        - Journal bearings
        - Microsim
        - Piston
        - Rolling contacts
        - Thrust bearings
        
  # To add zoom functionality to images
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
  #Plugin for languages
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: de
          name: Deutsch
          build: true
          theme:
            palette:
              #Palette toggle for light mode(default)
              - scheme: default
                toggle:
                  name: In den Dunkelmodus wechseln
              #Palette toggle for dark mode(slate)
              - scheme: slate
                toggle:
                  name: In den Lichtmodus wechseln
          nav_translations:
            Home Page: Startseite
  # - with-pdf:
  #     render_js: true
  #     headless_chrome_path: C:\Program Files\Google\Chrome\Application\chrome.exe
  - charts

extra_css:
  - stylesheets/styles.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra:
  #To remove "Made with Material for MkDocs" notice from footer
  generator: false
  tags:
    Bevel gears: bg
    Cam contacts: cc
    Cylindrical gears: cg
    Developer mode: dm
    Examples: egs
    GUI: gui
    Journal bearings: jb
    Microsim: ms
    Piston: p
    Rolling contacts: rc
    Thrust bearings: tb
    

theme:
  icon:
    annotation: material/plus-circle
    tag:
      bg: tags/Cam2
      cc: tags/Cam2
      cg: tags/Cam2
      dm: tags/Cam2
      egs: tags/Cam2
      gui: tags/Cam2
      jb: tags/Cam2
      ms: tags/Cam2
      p: tags/Cam2
      rc: tags/Cam2
      tb: tags/Cam2
      
  # font:
  #   text: Ubuntu
  #   code: Ubuntu Mono
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/Favicon.ico
  name: material

  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest

  palette:
    #Palette toggle for light mode(default)
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: custom
      accent: custom
    #Palette toggle for dark mode(slate)
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: custom
      accent: custom
```

### Screenshots

Code above the header:
![Screenshot 2023-12-04 120958](https://github.com/squidfunk/mkdocs-material/assets/127078885/bb7e68a2-755f-4aa6-a14b-cdf80657892e)

All tag icons not visible:
![Screenshot 2023-12-04 121031](https://github.com/squidfunk/mkdocs-material/assets/127078885/f0d8fc68-ba0e-4851-823d-1b3856f5ed49)

Icon is visible in markdown but not in tags:
![Screenshot 2023-12-04 121543](https://github.com/squidfunk/mkdocs-material/assets/127078885/3adf99c3-c140-4c52-ba58-eb5044165096)

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. This is definitely a configuration error. Converting to discussion.

**Comment by alexvoss** [comment]
Hi, it might help to produce a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) so we can more clearly see what is going on. There is a lot of other configuration in what you posted. I typed out half an answer that would have gone in the wrong direction before I spotted where your definition of the tag identifiers is. Doing a reproduction would also help with ruling out some weird interactions between plugins or features.

**Comment by ankithabangar** [comment]
I have created a minimal reproduction still facing the same issue.

## Reproduction
The `mkdocs.yml` file

```
site_name: My Docs
docs_dir: docs/


theme:
  name: material
  custom_dir: docs/overrides/
  icon:
    tag:
      html: tags/Cam2
      css: tags/Cam2
      js: tags/BGe

markdown_extensions:
  - pymdownx.emoji: # To add custom icons
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - docs/overrides/.icons

plugins:
  - tags:
      tags_file: tags.md

extra:
  tags:
    HTML5: html
    CSS3: css
    JavaScript: js
```

`index.md` 
```
---
tags:
  - HTML5
  - JavaScript
  - CSS3
---

# Welcome to MkDocs

For full documentation visit [mkdocs.org](https://www.mkdocs.org).

## Commands

* `mkdocs new [dir-name]` - Create a new project.
* `mkdocs serve` - Start the live-reloading docs server.
* `mkdocs build` - Build the documentation site.
* `mkdocs -h` - Print help message and exit.

## Project layout

    mkdocs.yml    # The configuration file.
    docs/
        index.md  # The documentation homepage.
        ...       # Other markdown pages, images and other files.

```

## Screenshots

![Screenshot 2023-12-06 095418](https://github.com/squidfunk/mkdocs-material/assets/127078885/1b020c75-91ef-496e-b4c9-036c9c601077)
![Screenshot 2023-12-06 095608](https://github.com/squidfunk/mkdocs-material/assets/127078885/44c5cb2e-f793-4e4a-9c24-653177f8a172)
