### DISCUSSION TITLE
Tags page

### DISCUSSION THREAD

**Discussion by alanpt** [squidfunk/mkdocs-material#6443] [Q&A] [answered]
Hello, I am using the insider version.  I am using `tags_extra_files` to create a subset of specific tags, and this works great.  What I would like to do is have a tag page that would list the tag contents but grouped by any other tag it may have. 

For example these articles named 

- "how_to_use_the_callcenter.md" tagged `#callcenter` and `#howto`
- "about_the_callcenter.md" tagged `#callcenter` and `#explanation`

Using: 
 ```
  - tags:
      tags_file: tags.md
      tags_extra_files:
        callcentertags.md: 
         - callcenter
 extra:
  tags:
    callcenter: callcenter
 ```
 
 So the callcentertags.md file would show a list like this:

>  ## Callcenter
>  
>  #howto 
>  how_to_use_the_callcenter.md
>  
>  #explanation
>  about_the_callcenter.md

Thanks for any help!
