### DISCUSSION TITLE
Is the content.code.select option the only needed configuration to make code selection working?

### DISCUSSION THREAD

**Discussion by AnastasiaTWW** [squidfunk/mkdocs-material#6458] [Q&A] [answered]
I'm sorry for posting so many questions today :) I try to enable insiders for our docs site and face with the problems I do not know how to deal with, hope it will be helpful for others facing the same.

The current question is related to the code selection button - https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=content+code+copy#code-selection-button. I try to add the content.code.select feature to my mkdocs.yml but it does not work at all. The icon just does not appear.

The minimal reproduction attached. It also includes the "copy" button which displays correctly.

[9.5.0+insiders.4.46.0-select_code_lines.zip](https://github.com/squidfunk/mkdocs-material/files/13602429/9.5.0%2Binsiders.4.46.0-select_code_lines.zip)

This is how I've installed the deps:

```
pip install --upgrade --force-reinstall mkdocs-material
git+https://@github.com/squidfunk/mkdocs-material-insiders.git
```

**Comment by squidfunk** [comment, marked as answer]
No worries, happy to help. [You're missing the recommended base configuration](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#configuration):

``` yaml
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
```
