### DISCUSSION TITLE
How to change the language selector dropdown size?

### DISCUSSION THREAD

**Discussion by ssbarnea** [squidfunk/mkdocs-material#6495] [Q&A] [answered]
Apparently the language selector dropdown is starting to display a scrollbar after ~5 elements and that is making it much harder to user. I tried inspecting the elements in order to find what CSS I need to tune to make it display more elements before going for the scroll but I failed to find it.

![](https://sbarnea.com/ss/Screen-Shot-2023-12-12-17-03-13.86.png)

Hopefully someone else knows the magic CSS class to tune.

**Comment by kamilkrzyskow** [comment, marked as answer]
Hello,
checking in Firefox developer tools I got to:
```css
.md-select:focus-within .md-select__inner, .md-select:hover .md-select__inner {
  max-height: 10rem;
  /* ... */
}
```
You can use extra css to change the `max-height` attribute using this selector:
https://squidfunk.github.io/mkdocs-material/customization/#additional-css

~~Also is the website you're screenshoting public? Would help to be able to just work on the same site you asked for ;p~~
Found it https://ansible.readthedocs.io/projects/dev-tools/
