### DISCUSSION TITLE
Allow the feedback widget when not using Google

### DISCUSSION THREAD

**Discussion by JC5** [squidfunk/mkdocs-material#6501] [Q&A] [answered]
### Context

I want to add the feedback widget to my documentation website. I do not want to use Google Analytics. I can't find a way to use `provider: custom` and the feedback widget.

### Description

See above. If I set "provider: google" I get a feedback widget. If I set "provider: custom" it disappears. I can't make it appear when I set "custom". When I set it to google I get unwanted Google Analytics code that I can't get rid of. 

I can hack something together but I don't want to. 

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
-

### Use Cases

Seems obvious from the context, thanks.

### Visuals

YAML

```yaml
extra:
  analytics:
    provider: google
    property: custom_property
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
```

Changing `provider: google` to `provider: custom` makes the feedback form disappear.

I can handle the events just fine. I need the form to be visible.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.
