### DISCUSSION TITLE
Error: 'GroupPlugin' object has no attribute 'is_serve' when deploying with mike

### DISCUSSION THREAD

**Discussion by shamoon** [squidfunk/mkdocs-material#6520] [Q&A] [answered]
Hi there, really confused as to why I'm getting the above error when trying to deploy via ci. We were previously using mike 1.1.2 and had no issues but have to upgrade to 2.0 for [reasons](https://github.com/jimporter/mike/issues/148). I realize this isnt the mike repository but I think the solution is here (or LMK if Im wrong about that).

Now, when executing
`run: MKINSIDERS=true mike deploy --update --push ${{github.ref_name}}` we hit the above error,
```sh
error: 'GroupPlugin' object has no attribute 'is_serve'
Error: Process completed with exit code 1.
```

mkdocs.yml looks like:
```yaml
...
plugins:
  - group:
      enabled: !ENV MKINSIDERS
      plugins:
        - optimize
        - typeset
        - social
```

Appreciate any help!
