### DISCUSSION TITLE
How to add animations to page icons?

### DISCUSSION THREAD

**Discussion by HotCakeX** [squidfunk/mkdocs-material#6547] [Q&A] [answered]
[This page](https://squidfunk.github.io/mkdocs-material/reference/#setting-the-page-icon) explains how to add icons to page that are rendered in navigation sidebar. [Here](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#with-animations) explains how to add animations to the icons.

But how to use them both?

Page icons need to be set like this

```
---
icon: material/emoticon-happy 
---
```

and doing this doens't work

```
---
icon: material/emoticon-happy:{ .heart }
---
```

**Comment by alexvoss** [comment]
I assume you included the extra CSS? Have you got the [attr_list markdown extension](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/?h=attr+list#attribute-lists) installed so the class gets attached to the icon?

**Reply by HotCakeX** [reply]
Yes I have `attr_list` but the syntax I showed is incorrect that's why it's not working.

**Comment by kamilkrzyskow** [comment]
The `attr_list` markdown extension can only be used in the Markdown content iirc, so you can't use the `{ .heart }` syntax in the file header / front-matter.
Having said that, I'm not sure how one would target that 1 specific icon in the whole navigation list, as there is no unique identifier added to it 🤔

**Reply by HotCakeX** [reply]
I was wondering if it was possible to target the icon's name with CSS in the extra CSS file, even if that means it would change globally.

**Reply by alexvoss** [reply]
The SVG is not referenced in the navigation section (like a JPG or PNG would) but rather inserted there as an `svg` element. I assume you want the animation on only one of the icons? You might need to first match the link with the `md-nav__link` class and the `href` attribute that distinquishes it from all the other links in the navigation, then match the `svg` element inside that. **Edit**: Sorry, btw., for not realizing that `attr_list` will work only in the navigation.

**Reply by kamilkrzyskow** [reply]
**EDIT:** What Alex said is way better, accessing the href and then targeting the child svg node is simply cleaner.

---

Unfortunately the name isn't added when including the SVG html source in the page. You would have to modify the https://github.com/squidfunk/mkdocs-material/blob/master/src/templates/partials/nav-item.html partial. This can be done as a static override that you need check up on after every mkdocs-material update or you could make it more dynamic using hooks https://github.com/squidfunk/mkdocs-material/discussions/5060 and it would inform you of any incompatibilities immediately.

**Reply by HotCakeX** [reply]
I'll try the method @alexvoss suggested, thanks 

Btw, is it possible to add icons to the main navigation? The one that's on top. [This](https://spynetgirl.github.io/Miscellaneous/Create%20Bootable%20USB%20flash%20drive%20with%20no%203rd%20party%20tools/) is my website that I'm working on. I've added heart icons to the sidebar navigation but from the comments it looks like I can add the same icons to the top menu as well?

**Reply by HotCakeX** [reply]
This applies the animation to all of the sidebar navigation icons

```css
@keyframes heart {

    0%,
    40%,
    80%,
    100% {
        transform: scale(1);
    }

    20%,
    60% {
        transform: scale(1.15);
    }
}

.md-nav--primary .md-nav svg {
    position: relative;
    animation: heart 1000ms infinite;
}
```

**Reply by alexvoss** [reply]
The thing you would need to add to be specific would be an [attribute selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors), matching the URL in the `href` attribute. That should work.

**Reply by kamilkrzyskow** [reply]
Tested on https://squidfunk.github.io/mkdocs-material/plugins/ :
```css
.md-nav--primary .md-nav__link[href="social/"] svg {
  animation: heart 1000ms infinite;
}
```
And only the nav item to the social page icon has the animation.

**Reply by kamilkrzyskow** [reply]
As for this @HotCakeX,
> > I'll try the method @alexvoss suggested, thanks
> 
> Btw, is it possible to add icons to the main navigation? The one that's on top. [This](https://spynetgirl.github.io/Miscellaneous/Create%20Bootable%20USB%20flash%20drive%20with%20no%203rd%20party%20tools/) is my website that I'm working on. I've added heart icons to the sidebar navigation but from the comments it looks like I can add the same icons to the top menu as well?

Please read this discussion: https://github.com/squidfunk/mkdocs-material/discussions/6419
Your tabs at the top are only sections, they don't have `index.md` pages attached to them, therefore you can't add icons without modifying the overrides.

On https://squidfunk.github.io/mkdocs-material/plugins/ you can see that the `Plugins` on the left navigation is clickable, this means there is a site attached to it, however the Material docs don't use icons this way. On your page every tab is just a section without a page.

**Comment by HotCakeX** [comment]
> Tested on https://squidfunk.github.io/mkdocs-material/plugins/ :
> 
> ```css
> .md-nav--primary .md-nav__link[href="social/"] svg {
>   animation: heart 1000ms infinite;
> }
> ```
> 
> And only the nav item to the social page icon has the animation.

I can't get it to work on my website. My nav links have spaces and aren't as simple. https://spynetgirl.github.io/

putting `%20` for the spaces isn't doing it. Many pages have different title and link from the name on the left side nav.

**Reply by kamilkrzyskow** [reply, marked as answer]
I'm not sure what you mean, using Firefox or Chromium I got it working for the exact match:
https://spynetgirl.github.io/Miscellaneous/About%20TLS%2C%20DNS%2C%20Encryption%20and%20OPSEC%20concepts/
```css
.md-nav--primary .md-nav__link[href="../Event%20Viewer/"] svg {
  animation: heart 1000ms infinite;
}
```
and as per the linked documentation it doesn't have to be a exact match:
```css
.md-nav--primary .md-nav__link[href*="Event"] svg {
  animation: heart 1000ms infinite;
}
```
and as per the linked documentation case-insensitive ending:
```css
.md-nav--primary .md-nav__link[href$="event%20viewer/" i] svg {
  animation: heart 1000ms infinite;
}
```
IMHO your file and folder names are problematic, as they are case sensitive, contain special characters like commas or spaces, hence the requirement for unicode character escapes.

> putting %20 for the spaces isn't doing it. Many pages have different title and link from the name on the left side nav.

You don't have to guess how to write the character escapes, just look at the rendered href value in the HTML source code of the page. That's the string that is being used for the match lookup.
