### DISCUSSION TITLE
Override language selector svg?

### DISCUSSION THREAD

**Discussion by YozoraXCII** [squidfunk/mkdocs-material#6554] [General]
I am looking to utilize the language selector to allow me to easily flip between three branches of the same docs file that I have.

I have the following in my mkdocs.yml which works as I expect:

```
extra:
  alternate:
    - name: Latest
      link: /en/latest/
      lang: en
    - name: Develop
      link: /en/develop/
      lang: en
    - name: Nightly
      link: /en/nightly/
      lang: en
```

I would now like to override the svg file that is used to instead be `.icons/material/file-document-multiple-outline.svg`

Ideally I could also override the aria-label from `Select language` to `Select docs branch`

**Comment by kamilkrzyskow** [comment]
Hello @YozoraXCII,
you can override the `alternate.html` template partial to edit the `aria-label`:
https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme
https://github.com/squidfunk/mkdocs-material/blob/6b690e9acdf2b4ae10f2299309de231f6796ba30/src/templates/partials/alternate.html#L29
https://github.com/squidfunk/mkdocs-material/blob/6b690e9acdf2b4ae10f2299309de231f6796ba30/src/templates/partials/languages/en.html#L70-L71

As for changing the icon you can do so, by setting the value in the `mkdocs.yml` file:
```yml
theme:
  icon:
    alternate: material/file-document-multiple-outline
```
or replacing another line in the partial override above.

---

You might also opt into another approach of adding the version toggle with branch names via JavaScript.
That's what we're doing on our Gothic Modding Community docs: https://github.com/Gothic-Modding-Community/gmc/blob/4bd4fef7ffa6d644a087e544e0c2078dfec0087a/overrides/assets/javascripts/extra.js#L299-L338
We're recreating the toggle for a `mike` versioning structure, even thought we're not using versioning, just different branches.
