### DISCUSSION TITLE
Search disappears when activating plugins

### DISCUSSION THREAD

**Discussion by El-Gavy** [squidfunk/mkdocs-material#6570] [Q&A] [answered]
Hello,
After two hours of research and testing without success, I resign myself to asking for help: when I try to activate two plugins in this way, the search disappears on all pages: 

```
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors

```
When i comment these lines, search appears again. I installed the said plugins locally and they are also well installed during the CI of my repository, accessible at this address : https://framagit.org/zotero-fr/zotero-fr.frama.io

If anyone could provide assistance I would be really grateful.
