### DISCUSSION TITLE
How to add a top navigation item without index page?

### DISCUSSION THREAD

**Discussion by holgerflick** [squidfunk/mkdocs-material#6600] [General]
I have several pages that are accessible from the top navigation bar but do not have an `index.md` file. The navigation references a list of files. If I set an icon with `icon:` in the first file that is referenced in the navigation, this icon is not shown in the main/top navigation.

How can I achieve this? In the navigation below, only the Home `index.md` is able to deliver an icon for the main nav. It does not work with any of the other pages.

```
nav:
  - Home: index.md
  - Blog:
    - blog/index.md
  - Books:
    - books/book1-2023-12.md   
    - books/book3-2023-4.md    
    - books/book4-2021-7.md    
    - books/book6-2021-3.md    
    - books/book5-2020-5.md   
```

**Comment by kamilkrzyskow** [comment]
Hello @holgerflick,
I believe this question is a duplicate of 
https://github.com/squidfunk/mkdocs-material/discussions/6419
https://github.com/squidfunk/mkdocs-material/discussions/6581
In short you can't do that by default, however you should be able to make a customization to achieve it, though no one has stepped forward from previous questions with a solution.

Also your `books` section seems oddly similar to a blog setup 🤔 Have you thought about using another `blog` plugin entry to manage your books? Minimal example: [icons-home-for-holgerflick.zip](https://github.com/squidfunk/mkdocs-material/files/13836294/icons-home-for-holgerflick.zip)

**Reply by holgerflick** [reply]
This is such an amazing recommendation! I did not know this was possible to have multiple! My courses that I just added will follow the same principle. I generate the book pages in a tool I wrote myself, but to have MkDocs organize it is even better!

**THANK YOU!**

It still would be amazing to have a icon on the navigation for this. I sadly do not have the skills in Python or JavaScript to implement it. My languages are Delphi, Swift, and C#.

**Reply by kamilkrzyskow** [reply]
Sure thing, the multi-instance is documented here: https://squidfunk.github.io/mkdocs-material/plugins/#multiple-instances
Also please explain your "without index page" requirement in more detail. I don't see a particular limitation in this navigation, that would prevent using them.
![image](https://github.com/squidfunk/mkdocs-material/assets/34622465/81d5575f-283f-44a3-8e4e-4d8bb1145749)

**Reply by holgerflick** [reply]
I am able to get an icon in front of the navigation now! It works great. However, that only works, because I have a file `index.md` that is referenced in the navigation. However, my technical articles look like this... and I see no way to get an icon into the navigation as it references snacks/01.md first. It only appears in the navigation if I click "Snacks".  Any hint how can organize these differently? I could use the blog module again thinking about it... with the sections being different categories.

```
- Snacks:
    - Base64 Encoding:
        - snacks/01.md
        - snacks/06.md
        - snacks/05.md
    - Application:
        - snacks/02.md
        - snacks/03.md
        - snacks/07.md
        - snacks/08.md
    - snacks/04.md
    - snacks/09.md
    - snacks/10.md
    - snacks/11.md  
  - Tutorials:
    - tutorials/ngrok.md
    - tutorials/tabular.md
    - tutorials/fnccloud-twitter.md  
```

**Reply by kamilkrzyskow** [reply]
I didn't have an answer at first, but suddenly recalled that there is a `redirect.html` template: 
https://github.com/squidfunk/mkdocs-material/blob/master/src/templates/redirect.html
I even think that someone already proposed this in some other discussion, but you could create an index page for those sections, and if putting content there really doesn't work well, just use that template to redirect to the actual first page in the section, and the icon would still be set to the index page.

Also I would probably be more strict with the paths for snacks like `snacks/base64/01.md` `snacks/application/01.md` and so on to provide context for them from the actual file structure, not just the `nav` in the `mkdocs.yml` file.

**Reply by holgerflick** [reply]
Thank you. These are all great suggestions. With regards to the snacks and other tutorials, in a future with infinite amount of time for hobby projects, I will generate those as well using an app with database... This will then definitely use the directory structure you suggest.

I was unaware that redirect is part of the repo. I used the redirect package before which - of course - did not handle icons well.

Next, I need to look into the font size of the navigation. I would like the font to be a bit bigger and also have a bit more weight. I am sure I can fiddle with a template...

**Reply by holgerflick** [reply]
... also I just found the awesome-pages plugin. That might open up new options as well for tutorial pages!

**Reply by kamilkrzyskow** [reply]
> Next, I need to look into the font size of the navigation. I would like the font to be a bit bigger and also have a bit more weight. I am sure I can fiddle with a template...

This would be a CSS responsibility: https://squidfunk.github.io/mkdocs-material/customization/#additional-css
```css
.md-nav--primary .md-nav {
  font-size: .7rem;
  line-height: 1.3;
}
```
