### DISCUSSION TITLE
[Feature request] Nested navigation tabs

### DISCUSSION THREAD

**Discussion by couleurm** [squidfunk/mkdocs-material#6618] [Q&A] [answered]
Hey, the navigation tab offer quite a bit of horizontal estate to quickly get started, though I'd like to expand further and have them nested, is that something plausible?

![image](https://github.com/squidfunk/mkdocs-material/assets/82747632/299b1458-d7d4-4f36-8507-d30069100667)

Here's how I imagine it *could* be configured (could be prettier):

```yml
nav:

  # ...

  - Video:
    - __nestlevel__: 2
    - Setup: video/index.md
      # ...
    - Content creation: video/index.md
      # ...
    - Video Editing:
      # ...
```
