### DISCUSSION TITLE
New Tags Plugin Listings

### DISCUSSION THREAD

**Discussion by DanielHabenicht** [squidfunk/mkdocs-material#6621] [Q&A] [answered]
I don't know whether I found a bug or if I am using the insiders version wrong: 

1. Setup a new Project with `mkdocs new .`
2. Use the following `mkdocs.yml`: 
    ```
    site_name: My Docs
    
    theme:
      name: material
      palette:
        primary: white
    
    plugins:
      - tags
    ```
3. Setup one page with a tag
```
---
tags: [docker]
---
# Test

test
```
4. Setup an overview page: 
```
# Tags

Following is a list of relevant tags:

<!-- material/tags -->
```

which results in the following page: 
![image](https://github.com/squidfunk/mkdocs-material/assets/13590797/2bc5424a-e628-4aab-a23d-a467aa7418ec)
