### DISCUSSION TITLE
Authors showing as default after mkdocs upgrade

### DISCUSSION THREAD

**Discussion by nitinatgh** [squidfunk/mkdocs-material#6633] [General]
Hi,

I've have recently upgraded the mkdocs-material to `9.5.2` from `8.5.6`, and after doing so I am now getting the authors on every page. 
Is there a way to disable this from happening, as I expect it to only show when using the `{{ git_page_authors }}`  jinja tag

Author plugin:  https://timvink.github.io/mkdocs-git-authors-plugin 

`mkdocs.yaml`
```
site_name: Docs Site
site_url: https://pages.github.example.com/example/docs-site/
docs_dir: "src"
site_dir: "docs"

repo_name: example/docs-site
repo_url: https://github.example.com/example/docs-site
edit_uri: ""

theme:
  name: material
  palette:
    - scheme: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  custom_dir: overrides
  features:
    - navigation.tabs
  
plugins:
  - search
  - tags:
      tags_file: tags.md
  - git-revision-date-localized:
      timezone: Universal
      type: custom
      custom_format: "%d %B %Y, %H:%M"
      enable_creation_date: true
      fallback_to_build_date: !ENV [GIT_DATE, false]
  - git-authors

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3
  - attr_list
  - md_in_html
  - tables

nav:
  - Home:
    - Welcome: index.md
    - Sub Page: sub-page.md
    - Tags Page: tags.md
```

Thanks
