### DISCUSSION TITLE
Unexpected button color change (upgrade from 7.0.5 to 9.5.5)

### DISCUSSION THREAD

**Discussion by dellagustin** [squidfunk/mkdocs-material#6698] [Q&A] [answered]
Hello,

When testing an upgrade from 7.0.5 to 9.5.5, a primary button is now showing the wrong color.

It should be black, but it is showing a blue color.

Before:
![image](https://github.com/squidfunk/mkdocs-material/assets/260113/68e2964e-eaa8-4eb0-a7de-a6f9ef7ed057)

After:
![image](https://github.com/squidfunk/mkdocs-material/assets/260113/487dc3ce-480f-48d6-9c24-4432a4d80040)

Current source code: https://github.com/podStation/podstation.github.io/tree/cef62084112fb1022b763a3f6c15f181ec25015a (before upgrade)

mkdocs.yml:
```yml
theme:
  name: material
  features:
  - navigation.tabs
  palette:
    primary: black
    accent: teal
  icon: 
    logo: fontawesome/solid/rss
  favicon: images/favicon.ico
```

Button:
```markdown
[INSTALL HERE][at-chrome-web-store]{ .md-button .md-button--primary }
```

Is this a bug, or did I miss some non-backwards compatible change?

**Comment by kamilkrzyskow** [comment]
Hello @dellagustin,
~~I believe the color has been changed in [9.4.0](https://github.com/squidfunk/mkdocs-material/releases/tag/9.4.0) as part of the `Improved slate color scheme` commits.~~
You can add extra css to make it black again:
https://squidfunk.github.io/mkdocs-material/customization/#additional-css
```css
[data-md-color-primary=black] .md-button--primary {
    background-color: var(--md-primary-fg-color);
    border-color: var(--md-primary-fg-color);
}
```

EDIT: 
Actually looking at git blame it turned out that the buttons started using the `typeset` color in [8.5.8](https://github.com/squidfunk/mkdocs-material/releases/tag/8.5.8)
https://github.com/squidfunk/mkdocs-material/commit/3c5f94f592aafca8eb6adaed2eb08f6826686b90#diff-cb62b49a7cc534cf5888884165d4957ef93d17dff48f856d37b009e5ff6fc788
