### DISCUSSION TITLE
Increasing font size of Improved tooltips

### DISCUSSION THREAD

**Discussion by paulmmoloney** [squidfunk/mkdocs-material#6757] [Q&A] [answered]
Hi all. I've implemented Improved tooltips[¶](https://squidfunk.github.io/mkdocs-material/reference/tooltips/#improved-tooltips) on my site, but wanted to do two things:

1. Increase the size of the font.
2. If possible, on desktop/wide screens, make the tooltip narrower, as it stretches to the width of the window.

What CSS do I need to add to accomplish this? Thanks,

P.

**Comment by kamilkrzyskow** [comment, marked as answer]
Hello @oceanclub1970,
to change the size of the font you can do it with:

> [!NOTE]
> If you're reading this after April 2024 please see the comment below:
> - https://github.com/squidfunk/mkdocs-material/discussions/6757#discussioncomment-10100386

```css
.md-tooltip__inner,
.md-tooltip--inline .md-tooltip__inner {
  font-size: 0.9rem;
}
```
However, it's position won't be centred to the hovered item, it will be shifted, as the JavaScript calculated the position without using the new font-size.

> If possible, on desktop/wide screens, make the tooltip narrower, as it stretches to the width of the window.

I don't know what you mean, the tooltips stretch on the whole page? Can you do a screenshot on the mkdocs-material documentation page and send it here please?

> Note that positioning of those tooltips has issues and is being reworked AFAIK: https://github.com/squidfunk/mkdocs-material/issues/6488

**Reply by paulmmoloney** [reply]
Thanks for the reply - see the screencap here to show how the tooltip is the width of the screen:

![wide-tooltip](https://github.com/squidfunk/mkdocs-material/assets/57188125/db4642bb-e02e-4a5c-bf4f-3b4312f30d11)

**Reply by kamilkrzyskow** [reply]
Oh, now I understand the issue, the amount of text stretches the content width. Didn't realize this was a thing because the `title` in my opinion should be rather short. The issue is related to the abbreviations and was was reported in: https://github.com/squidfunk/mkdocs-material/issues/6760 you can follow that issue. As for limiting the width, for the time being, you can do so with:
```css
.md-tooltip, .md-tooltip--inline {
  max-width: 10rem;
  word-break: break-all;
  white-space: break-spaces;
}
```

EDIT: Since the base width is `auto`, it's better to use `max-width`, like proposed by [Lexachoc](https://github.com/Lexachoc). Therefore it won't stretch the tooltip for shorter texts.

**Comment by paulmmoloney** [comment]
Would you be able to link me to an example extra.css file? For some reason the above CSS excerpt is not working for me.

Also, what is the difference between specifying as:

```
:root {
  --md-tooltip-width: 10rem;
}

```
and

```
.md-tooltip, .md-tooltip--inline {
  max-width: 10rem;
}
```

**Reply by Lexachoc** [reply]
Below works for me and it's exactly the same css classes from @kamilkrzyskow solution.

Maybe you need to disable the website cache for the extra.css to work? (I can't say why it doesn't work for you)

```css
/*Temporary solution for community version*/
/*see the new tooltip feature: https://squidfunk.github.io/mkdocs-material/reference/footnotes/#footnote-tooltips*/
.md-tooltip, .md-tooltip--inline {
    max-width: 20rem;
    word-break: break-all;
    white-space: break-spaces;
}

.md-tooltip__inner,
.md-tooltip--inline .md-tooltip__inner {
    font-size: 0.6rem;
}
```

By default it won't break words, so 
```css
:root {
  --md-tooltip-width: 10rem;
}
```
won't work. See: https://github.com/squidfunk/mkdocs-material/issues/6760#issuecomment-1937797898
