### DISCUSSION TITLE
Social cards theme behavior

### DISCUSSION THREAD

**Discussion by FlagHunter01** [squidfunk/mkdocs-material#6758] [Q&A] [answered]
Hey!

I didn't want to create an issue as the problem might stem from a lack of understanding on my part. 

When I use the automatic light/dark toggle, social cards are always blue. I can of course override it with `background_color`, but it should be `theme.palette.primary` by default. 

If this is indeed a bug and not a configuration problem on my part, my guess is that the auto toggle removes the `primary` and `accent` attributes from the `palette` field, and the social cards generator doesn't know what color to pick and goes for blue.

**Comment by kamilkrzyskow** [comment]
Hello @FlagHunter01,
the default fallback is to use the `indigo` colors, so the blue tint like you said. However, it does get later overridden with the `theme.palette.primary` if `palette` is defined as a dict key:value pairs, if it's defined as a list it uses the settings from the first entry.

https://github.com/squidfunk/mkdocs-material/blob/a6286ef3ac3407e8b6c985cf0571fc0e2caa6f5b/material/plugins/social/plugin.py#L73

https://github.com/squidfunk/mkdocs-material/blob/a6286ef3ac3407e8b6c985cf0571fc0e2caa6f5b/material/plugins/social/plugin.py#L115-L127

So perhaps your first list entry doesn't have the `primary` setting defined 🤔 
Or perhaps you created the config, then it generated the images with the blue background, then you changed the settings and you didn't clear the cache, and it's still blue.

Working example: [palette-auto.zip](https://github.com/squidfunk/mkdocs-material/files/14229941/palette-auto.zip)

**Reply by FlagHunter01** [reply]
Thanks for the reply!

> So perhaps your first list entry doesn't have the primary setting defined 🤔

Yep, I think that's it. As of my understanding, without the toggle, the palette looks like this:

```yml
palette:
    - primary
```

However, with the toggle enabled, it looks like this:

```yml
palette:
    - media: "(prefers-color-scheme: light)"
        - primary 
    - media: "(prefers-color-scheme: dark)"
        - primary
```

Any attempt to add a "primary" argument in front or behind the "media" arguments are met with an error. So I indeed don't have a "primary" argument listed directly in palette :(

**Reply by kamilkrzyskow** [reply, marked as answer]
Check the example zip:
```yaml
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: white
      accent: yellow
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
```
