### DISCUSSION TITLE
How to make titles for palette translatable?

### DISCUSSION THREAD

**Discussion by dragomano** [squidfunk/mkdocs-material#6790] [Q&A] [answered]
I want to have different palette titles for each language

```
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-3 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
```
