### DISCUSSION TITLE
Please can I confirm a behaviour is intended and not a bug, so that I can rely on it

### DISCUSSION THREAD

**Discussion by StarfallProjects** [squidfunk/mkdocs-material#6808] [Q&A] [answered]
I'm working on better structure for our docs navigation, and I've found a rather nice solution:

- Enable `navigation.sections`
- Enable `navigation.indexes`
- Group sections within 'fake' sections by adding an entry to the `nav` with no `index.md` attached

An example can be seen on this PR: https://github.com/n8n-io/n8n-docs/pull/1920
Preview build here: https://deploy-preview-1920--n8n-docs.netlify.app/ (The 'Using n8n' tab)

I want to confirm that this behaviour is the expected behaviour, and I can rely on it when planning my nav changes. It won't be lost in a future update?

Edit to add: this is an n8n question, not a personal project question.

**Comment by kamilkrzyskow** [comment, marked as answer]
Hello @StarfallProjects,
AFAIK, `navigation.indexes` doesn't require `index.md` it only allows to merge the section heading with it if the index page exists.
The "fake" sections, are just normal sections with inner content, there is nothing fake about them, also the documentation states that `navigation.sections` is compatible with `navigation.tabs`, so this is the expected behaviour.
A similar setup is used by Privacy Guides: https://www.privacyguides.org/en/basics/why-privacy-matters/

**Reply by StarfallProjects** [reply]
Brilliant thank you! I guess I meant fake sections as in there isn't a corresponding directory or place for the URL to go. As long as it's reliably going to keep working that's perfect :-)

**Reply by kamilkrzyskow** [reply]
There is also the example in the MkDocs documentation: https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
```yml
nav:
  - Home: 'index.md'
  - 'User Guide':
    - 'Writing your docs': 'writing-your-docs.md'
    - 'Styling your docs': 'styling-your-docs.md'
  - About:
    - 'License': 'license.md'
    - 'Release Notes': 'release-notes.md'
```
