### DISCUSSION TITLE
Task lists - failed tasks?

### DISCUSSION THREAD

**Discussion by paulmmoloney** [squidfunk/mkdocs-material#6811] [Q&A] [answered]
https://squidfunk.github.io/mkdocs-material/reference/lists/#using-task-lists

Is there a way of specifying a task has failed, does anyone know? (That is, having a red cross rather than a green tick).

P.

**Comment by kamilkrzyskow** [comment]
Hello @oceanclub1970,
since the [Tasklists](https://facelessuser.github.io/pymdown-extensions/extensions/tasklist/#styling-with-css) uses `<input>` checkboxes there are only 2 states, checked and unchecked. However, I think you could override the CSS for a given list entry via [`attr_list`](https://python-markdown.github.io/extensions/attr_list/). You'd add a class `{: .task-failed }` and [override the CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css) to change the appearance of the checked tick.

I didn't try it, but it should be possible.

Additional reference:
- https://github.com/squidfunk/mkdocs-material/discussions/2361
- https://facelessuser.github.io/pymdown-extensions/extensions/tasklist/#styling-with-css-custom-tasklist

**Reply by kamilkrzyskow** [reply]
Hey @oceanclub1970 have you managed to make progress with the idea?

**Reply by paulmmoloney** [reply]
I'm afraid I haven't had a chance yet. Hope to look into it soon.

**Reply by kamilkrzyskow** [reply]
I'll see if I can make an example later today.

**Reply by kamilkrzyskow** [reply, marked as answer]
Here you go @oceanclub1970,
[tasklist-failed.zip](https://github.com/squidfunk/mkdocs-material/files/14517281/tasklist-failed.zip)
```md
- [x] Success state
- [ ] Empty state
- [x] Failed state
{: .task-failed }
```

The theme uses the `:octicons-check-circle-fill-24:` emoji:
https://github.com/squidfunk/mkdocs-material/blob/6b239db64e031efe0399d338d3ce0a748c92a75e/src/templates/assets/stylesheets/main/extensions/pymdownx/_tasklist.scss#L30
So I chose the `:octicons-x-circle-fill-24:` to match it.

```css
:root {
  --md-tasklist-icon--failed: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M1 12C1 5.925 5.925 1 12 1s11 4.925 11 11-4.925 11-11 11S1 18.075 1 12Zm8.036-4.024a.751.751 0 0 0-1.042.018.751.751 0 0 0-.018 1.042L10.939 12l-2.963 2.963a.749.749 0 0 0 .326 1.275.749.749 0 0 0 .734-.215L12 13.06l2.963 2.964a.75.75 0 0 0 1.061-1.06L13.061 12l2.963-2.964a.749.749 0 0 0-.326-1.275.749.749 0 0 0-.734.215L12 10.939Z"/></svg>');
}

.md-typeset .task-failed [type="checkbox"]:checked + .task-list-indicator::before {
  background-color: #ff1744;
  -webkit-mask-image: var(--md-tasklist-icon--failed);
  mask-image: var(--md-tasklist-icon--failed);
}
```
You can change the icon by replacing the `<svg>` part in the CSS after the `charset=utf-8,`, also make sure the whole thing is on 1 code line.
Search for the emoji here, then open the SVG from the search result in a new tab and open the text source view in your browser.
https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/ 

Reference: 
- https://squidfunk.github.io/mkdocs-material/customization/#additional-css

---

<details open>

![image](https://github.com/squidfunk/mkdocs-material/assets/34622465/429faeb5-6814-4227-985d-c6a9b0f845b0)


</details>
