### DISCUSSION TITLE
How to scale an image roughly?

### DISCUSSION THREAD

**Discussion by madjxatw** [squidfunk/mkdocs-material#6813] [Q&A] [answered]
The only way I know by far is setting `width` and `height` in the `attr_list`. Most of the time, I don't care about the accurate size of an image, but only want to scale the image to roughly fit the page. Hence I would rather have a feature that can scale up/down the image by percentage than calculate the accurate pixel size. Any way in mkdocs-material to achieve this?

**Comment by kamilkrzyskow** [comment]
Hello @madjxatw,
by default bigger images are always scaled down to fit the width of the reading viewport, but you can use extra CSS to modify the styling for images: https://squidfunk.github.io/mkdocs-material/customization/#additional-css

```css
/* Scale to fit the page */
/* Small images will become very blurry */
/* Not recommended */

.md-content__inner img {
    width: 100%;
}

/* Scale to fit the page with constraints */
/* Smaller images will be min 25% of the width, so not as blurry */
/* Bigger images will be max 90% of the width, better for centring (?) */


.md-content__inner img {
    min-width: 25%;
    max-width: 90%;
}

/* Center the images */

.md-content__inner img {
    display: block;
    margin: 0 auto;
}

/* Add outline to make them pop */

.md-content__inner img {
    outline: 1px solid var(--md-accent-fg-color);
}
```

Example docs: [scale-images.zip](https://github.com/squidfunk/mkdocs-material/files/14385454/scale-images.zip)
