### DISCUSSION TITLE
How Do i Wind whether the website is using the light theme or the dark theme.

### DISCUSSION THREAD

**Discussion by SohamTilekar** [squidfunk/mkdocs-material#6814] [Q&A] [answered]
How do I Find whether the Hosted website is using the light theme or the dark theme. for the code highlighting.

the below code looks good on the dark theme but not on the light theme.
How do I edit the theme in the detail.
It is not Menson in the Documentation
```css
:root > * {
    --md-code-hl-number-color: #B5CEA8;
    --md-code-hl-special-color: #DCDCAA;
    --md-code-hl-function-color: #DCDCAA;
    --md-code-hl-constant-color: #569CD6;
    --md-code-hl-keyword-color: #C586C0;
    --md-code-hl-string-color: #CE9178;
    --md-code-hl-name-color: #9CDCFE;
    --md-code-hl-operator-color: #D4D4D4;
    --md-code-hl-punctuation-color: #D4D4D4;
    --md-code-hl-comment-color: #6A9955;
    --md-code-hl-generic-color: #9CDCFE;
    --md-code-hl-variable-color: #9CDCFE;
}
```

**Comment by alexvoss** [comment]
The documentation about custom color schemes contains the information about [switching CSS depending on which theme is used](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-color-schemes). Hope this helps.

**Reply by SohamTilekar** [reply]
I rear that part of the doc but I did not understand.

**Comment by alexvoss** [comment, marked as answer]
You can use the [CSS selectors described here](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-color-schemes) to switch the color variables for the code. Note that the default color schemes are called `default` and `slate`. The following switches just one color but you can modify this to your heart's content:

```CSS
[data-md-color-scheme="default"] { 
    --md-code-hl-number-color: #B5CEA8;
    --md-code-hl-special-color: #DCDCAA;
    --md-code-hl-function-color: #DCDCAA;
    --md-code-hl-constant-color: #569CD6;
    --md-code-hl-keyword-color: #C586C0;
    --md-code-hl-string-color: #CE9178;
    --md-code-hl-name-color: #9CDCFE;
    --md-code-hl-operator-color: #D4D4D4;
    --md-code-hl-punctuation-color: #D4D4D4;
    --md-code-hl-comment-color: #6A9955;
    --md-code-hl-generic-color: #9CDCFE;
    --md-code-hl-variable-color: #9CDCFE;
}

[data-md-color-scheme="slate"] {
    --md-code-hl-function-color: #FFFFFF;
} 
```
