### DISCUSSION TITLE
How can i debug my environment where mkdocs and mike cannot find material-extensions even though it is installed?

### DISCUSSION THREAD

**Discussion by ritwika314** [squidfunk/mkdocs-material#6839] [Q&A] [answered]
Hi, 

> [!Note]
> I am adding this question as a discussion rather than an issue because I most likely made a mistake while setting my project up. I can use the deprecated emoji index to unblock my project for now, but i would like to use the updated packages.

I have the following list of extensions in my `mkdocs.yml`:

```
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
     emoji_index: !!python/name:material.extensions.emoji.twemoji
     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  ```

When I run `mkdocs serve` or `mike deploy`, here is the error i run into immediately: 

```
Error: MkDocs encountered an error parsing the configuration file: while constructing a Python object
cannot find module 'material.extensions.emoji' (No module named 'material.extensions')
  in "/Users/ritwika/bodo/docs/mkdocs.yml", line 95, column 19
```

Here's my environment:
```
Package                    Version
-------------------------- ----------
Babel                      2.14.0
certifi                    2024.2.2
charset-normalizer         3.3.2
click                      8.1.7
colorama                   0.4.6
ghp-import                 2.1.0
idna                       3.6
importlib-metadata         7.0.1
importlib_resources        6.1.2
Jinja2                     3.1.3
Markdown                   3.5.2
MarkupSafe                 2.1.5
mergedeep                  1.3.4
mike                       2.0.0
mkdocs                     1.5.3
mkdocs-autorefs            0.5.0
mkdocs-material            9.5.11
mkdocs-material-extensions 1.3.1
packaging                  23.2
paginate                   0.5.6
pathspec                   0.12.1
pip                        24.0
platformdirs               4.2.0
Pygments                   2.17.2
pymdown-extensions         10.7
pyparsing                  3.1.1
python-dateutil            2.8.2
PyYAML                     6.0.1
pyyaml_env_tag             0.1
regex                      2023.12.25
requests                   2.31.0
setuptools                 68.2.0
six                        1.16.0
urllib3                    2.2.1
verspec                    0.1.0
watchdog                   4.0.0
wheel                      0.41.2
zipp                       3.17.0
```

Any ideas on what may be causing this issue and pointers on how I can debug the build process in this environment? Should I try installing `mkdocs-material` and `mike` from source rather than pip?
