### DISCUSSION TITLE
Gradient full lading page

### DISCUSSION THREAD

**Discussion by meroxdotdev** [squidfunk/mkdocs-material#6840] [Q&A] [answered]
Hello, I've used this resource to create my landing pge of mkdocs-material: 
https://github.com/tylerdotrar/mkdocs-coverpage/tree/main

But I want to make the gradient of the landing page to be complete on all page, I don't know how to do this, can you help please ?
See the screenshot 
![homepage](https://github.com/squidfunk/mkdocs-material/assets/35839230/0cf24fa9-f4f8-4cf2-ae57-2926ea3880e8)

That white space it's black when dark mode is enabled, I'm very noob regarding frontend :D

**Comment by facelessuser** [comment, marked as answer]
You can set the following transparent.

```css
tx-container {
    background: transparent;
}
```

And then set the container behind it with a gradient:

```css
.md-container {
    background: linear-gradient(to bottom, var(--md-primary-fg-color), hsla(0deg,47%,55%,1) 99%,#fff 99%);
}
```
