### DISCUSSION TITLE
Can I make it so all code blocks are auto-titled EXCEPT bare no-language ones?

### DISCUSSION THREAD

**Discussion by ryran** [squidfunk/mkdocs-material#6848] [Q&A] [answered]
If this would be better asked somewhere else, please forgive me (and point me in the right direction :innocent:) but ... in my `mkdocs.yml`, I have

``` yaml
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
      linenums_style: pymdownx-inline
```

75% of the time, I love having the auto_title option enabled -- any time we specify a language, I love that the language becomes the title by default and we can change it with `title="xxx"` if we want; however, for those times (or users) where the simplest code block is all that was done ... i.e.:
~~~ md
```
code here
```
~~~

... we get an ugly + unnecessary title that says "**Text Only**".

Obviously, for those in-the-know, it's trivial to add `title=""` to that first line (if you remember), but I'm wondering if anyone here has ideas of how I could achieve this with some hidden option/extension or some custom CSS styling or something.
