### DISCUSSION TITLE
When using content.action.view in theme.features with GitLab, how can I make it go to blob/ instead of raw/?

### DISCUSSION THREAD

**Discussion by ryran** [squidfunk/mkdocs-material#6850] [Q&A] [answered]
Part of my `mkdocs.yml`:
``` yaml
repo_url: https://gitlab.example.com/group/project
repo_name: GitLab

# https://www.mkdocs.org/user-guide/configuration/#edit_uri
edit_uri: edit/main/docs/

# doesn't hurt to try...
view_uri: blob/main/docs/

theme:
  features:
    - content.action.edit
    - content.action.view
```

Out of the box, the edit button works great and takes me straight to the editor; however, the view button takes me to `raw/main/docs/{path}`, which I do not like.

How might I go about tweaking it to instead go to `blob/main/docs/`? (Even better would be `blob/main/docs/{path}?plain=1`.)
