### DISCUSSION TITLE
Can you set a part of a grid card entry to be at the bottom?

### DISCUSSION THREAD

**Discussion by Andre601** [squidfunk/mkdocs-material#6855] [Q&A] [answered]
I currently use the `grid cards` setup with the Div-object aproach and now would like to have the last paragraph of a card to be aligned vertically at the very bottom.

As an example, imagine the following grid cards:
![grafik](https://github.com/squidfunk/mkdocs-material/assets/11576465/f2a13333-956c-427f-9645-28ed382cd47e)

I now would like that "Some Link" is at the same vertical height as "Other Link", maybe even pair it with other elements like a horizontal rule above the link for separation.
What options, if any, are there that I could try?

**Comment by kamilkrzyskow** [comment, marked as answer]
Hello @Andre601,
I'm no CSS expert, but I played a bit with display flex and managed to find a "solution" to your query:

https://squidfunk.github.io/mkdocs-material/customization/#additional-css

https://github.com/squidfunk/mkdocs-material/assets/34622465/5a44f0aa-43f4-4a1d-8940-8fbd59419f4c

```css
.md-typeset .grid.cards > ul > li {
	display: flex;
	flex-direction: column;
	outline: 1px solid green;
}
.grid.cards li p:last-child {
        display: flex;
	flex-grow: 5; /* Probably 2 would be enough, as the grids shouldn't hold too much text to begin with, but to be safe I set it to 5 */
	outline: 1px solid red;	
}
.grid.cards li p:last-child a {
	align-self: flex-end;
}
```

There is a slight increase in the gap around the `<hr>` line at the top, and I don't think I can prevent it with this setup 🤔 
I hope this is a valid approach :v:

**Reply by Andre601** [reply]
That works perfectly, thank you.

**Comment by Andre601** [comment]
I'm back with another situation similar to the one I had before.

The difference here is, that instead of a single link, I want to have an unordered list be put at the bottom of a flex entry.

Here is the markdown:
```markdown
<!-- "hide-list" is used in CSS to hide the dots of nested unordered lists -->
<div class="grid cards hide-list" markdown>

-   ## Example 1
    
    Lorem Ipsum dolor.
    
    - [Another page](https://example.com/another-page)
    - [More](https://example.com)

-   ## Example 2
    
    - [Link](https://link.example.com)

</div>
```
Using this with the following CSS:
```css
.md-typeset .grid.cards.hide-list > ul > li > ul > li {
    list-style-type: none;
}

.md-typeset .grid.cards.hide-list > ul > li {
    display: flex;
    flex-direction: column;
}

.md-typeset .grid.cards.hide-list > ul > li > ul {
    flex-grow: 2;
    display: flex;
}


.md-typeset .grid.cards.hide-list > ul > li > ul > li {
    align-self: flex-end;
}
```
...gives me this output:
![grafik](https://github.com/squidfunk/mkdocs-material/assets/11576465/4a700aad-39db-49ba-8f0c-e85f72ea7e3a)

I tried to do different variations here (Applying attributes flex-grow, display and align-self to different parts) but no real luck here...

What would I need to modify to get a similar outcome to the other situation?

**Reply by kamilkrzyskow** [reply]
So you want the list at the bottom, @Andre601?

<details>
<summary> Image </summary>

![image](https://github.com/squidfunk/mkdocs-material/assets/34622465/c9a30f69-787f-4569-9b95-1db47bcac9da)

</details>

I don't know how exactly your Markdown renders, as without a [minimal runnable example](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/#creating-a-reproduction), I prefer to simply modify the DOM 😅, so the result perhaps isn't accurate.

So I added a `<ul>` inside the `<p>` tag, so instead of the `<a>` tag we should target the `<ul>`, or both with:
```css
.grid.cards li p:last-child :is(a, ul) {
  align-self: flex-end;
}
```
I didn't need to modify anything else, or add display flex to the `li` tag 🤔 So if that doesn't work then the HTML structure isn't the same, as my guess. 

Also the `.hide-list` seems to be unnecessary, as you can just set:
```css
.grid.cards ul li {
  list-style-type: none;
}
.grid.cards ul {
  margin-left: 0 !important;
}
```
if something gets overshadowed by the default theme CSS, then using `!important` is also an option.
