### DISCUSSION TITLE
I would like to ask if there is any explanation about the variables of color configuration css. I can only get some information through ChatGPT.

### DISCUSSION THREAD

**Discussion by w1ndys** [squidfunk/mkdocs-material#6882] [Q&A] [answered]
![image](https://github.com/squidfunk/mkdocs-material/assets/109416673/439ab5f3-5e84-47d0-a011-022b99fde4e6)
![image](https://github.com/squidfunk/mkdocs-material/assets/109416673/34fdb22b-1c68-4d9b-8830-8ced7a81661a)
![image](https://github.com/squidfunk/mkdocs-material/assets/109416673/53e6908a-7f51-441d-bbd3-ad506537b0fc)

**Comment by w1ndys** [comment]
How to connect css parameters to parameters in mkdocs.yml, and where can I find relevant documentation

**Comment by kamilkrzyskow** [comment]
Hello @W1ndys,
I'm not sure what do you mean by "any explanation about the variables of color configuration css". The ChatGPT answers in Chinese don't help either 😓 

On the screenshoted page there is the link to the color definitions: 
https://github.com/squidfunk/mkdocs-material/blob/master/src/templates/assets/stylesheets/main/_colors.scss

As for the palette configuration in mkdocs.yml there is this folder:
https://github.com/squidfunk/mkdocs-material/tree/master/src/templates/assets/stylesheets/palette
The SCSS gets compiled to CSS later into separate configurations:
https://github.com/squidfunk/mkdocs-material/tree/master/material/templates/assets/stylesheets
```css
[data-md-color-accent=pink] {
    --md-accent-fg-color: #f50056;
    --md-accent-fg-color--transparent: #f500561a;
    --md-accent-bg-color: #fff;
    --md-accent-bg-color--light: #ffffffb3
}

[data-md-color-accent=purple] {
    --md-accent-fg-color: #df41fb;
    --md-accent-fg-color--transparent: #df41fb1a;
    --md-accent-bg-color: #fff;
    --md-accent-bg-color--light: #ffffffb3
}
/* ... */
```

The syntax for colors in the SCSS comes from this package: https://www.npmjs.com/package/material-design-color

---

If you're asking about a visual explanation for which variable is used where on the page, I don't think there any guide of that sort. 
You'll have to experiment in the Dev Tools. Best to do it on your own page, because the docs here use a [custom.css](https://github.com/squidfunk/mkdocs-material/tree/master/src/overrides/assets/stylesheets) file, but it still should suffice.


https://github.com/squidfunk/mkdocs-material/assets/34622465/660126c8-7dee-4a41-8bfd-90c4284ee7ff
