### DISCUSSION TITLE
[Navigation] How to extract the title of markdown as the name of the navigation tab?

### DISCUSSION THREAD

**Discussion by icefery** [squidfunk/mkdocs-material#6891] [Q&A]
Is there any configuration that allows the title of the markdown to be the name of the navigation tab?

```
site/
|--docs/
  |--tab1/
    |--a.md
    |--README.md # title is 'Navigation Tab One'
  |--tab2/
    |--b.md
    |--README.md
|--mkdocs.yaml
```

```yaml
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
```
