### DISCUSSION TITLE
Metadata about Markdown

### DISCUSSION THREAD

**Discussion by w1ndys** [squidfunk/mkdocs-material#6920] [Q&A] [answered]
I have a question that may be presumptuous, what parameters can be used in the metadata of Markdown files?
Because I found the configuration parameter `outline: deep` in the file that comes with the framework, but I did not find the relevant configuration instructions in the material, so I wanted to find out if there is any

**Comment by alexvoss** [comment]
Not sure where you have found this. Some more context would help with answering this question.

**Reply by w1ndys** [reply]
Hi, this is my mistake, now I will describe the problem in detail
The general form of Markdown metadata is as follows
```
---
title: "xxxxx"
comments: true
description: "xxxxx"
icon: material/test-tube
status: test
template: test.html
date:
   created: 2021-05-08
   updated: 2022-05-09
outline: deep
---
```
What I want to know is, in addition to parameters such as title, data, icon, etc., are there any other parameter functions that can be supported? I want to find a document that lists all possible supported parameters.
Thank you very much for your reply
the best wishes
