### DISCUSSION TITLE
Increase the usable space for the left sidebar to include more text from page title

### DISCUSSION THREAD

**Discussion by e4rthdog** [squidfunk/mkdocs-material#6936] [Q&A]
I have applied the proposal for increasing the width of the whole page as described here: [#3692](https://github.com/squidfunk/mkdocs-material/discussions/3692).

I would like to use part of the "gained" space and give it to the left sidebar in order to make more of my pages title fit in one line.

![image](https://github.com/squidfunk/mkdocs-material/assets/1651764/75a42619-1383-4e3a-8880-ae2f353b7821)

**Comment by alexvoss** [comment]
If you right-click on the navigation, select `inspect`, and find the outermost element, you will find a `div` that has the classes `.md-sidebar` and `.md-sidebar--primary` and a width definition. You could try:

```css
div.md-sidebar.md-sidebar--primary {
  width: 15rem;
}
```

Adjust the width to taste. Hope this helps.

**Reply by e4rthdog** [reply]
I think i got what i need with below results. I will have to check how it is looking in mobile though, after i add some articles.

![image](https://github.com/squidfunk/mkdocs-material/assets/1651764/bd1a2440-ef2a-4ec2-b1c5-e7bd1a56308a)

The css:

``` css
.md-grid {
	max-width: 95%;
}

div.md-sidebar.md-sidebar--primary,
div.md-sidebar.md-sidebar--secondary {
	width: 15rem;
}

nav.md-nav {
	width: 14rem;
}
```
