### DISCUSSION TITLE
How to make value defined in mkdocs.yaml available in templates

### DISCUSSION THREAD

**Discussion by divSelector** [squidfunk/mkdocs-material#6972] [Q&A] [answered]
I'm trying to do something like this

`mkdocs,yaml`

```yaml
extra:
  hello:
    - world: https://example.com
```

`toc.html`

```html
  {% if toc %}
    ...
  {% else %}
    {% set toc = config.extra.hello %}
    ....
  {% endif %}
```
