### DISCUSSION TITLE
A modern look with round edges

### DISCUSSION THREAD

**Discussion by arv-anshul** [squidfunk/mkdocs-material#6974] [Ideas]
We should implement round edges in `mkdocs-material` because this is the norm now-a-days. I have done same on my website too.

I've used `border-radius` CSS property for this in `stylesheets/customize.css`. My base `border-radius` is `0.5rem`.

<details>
<summary>customize.css</summary>

👀 See full [`customize.css`](https://github.com/arv-anshul/arv-anshul.github.io/blob/main/docs/stylesheets/customize.css)

```css
:root {
  --base-border-radius: 0.5rem;
}

/* Change font family of filename present on top of code block. */
.highlight span.filename {
  border-bottom: none;
  border-radius: var(--base-border-radius);
  display: inline;
  font-family: var(--md-code-font-family);
  border-bottom-left-radius: 0;
  border-bottom-right-radius: 0;
  margin-bottom: 5px;
  text-align: center;
}
.highlight span.filename + pre > code {
  border-radius: var(--base-border-radius);
  border-top-left-radius: 0;
}
.md-typeset pre > code {
  border-radius: var(--base-border-radius);
}

/* Grid Cards */
.md-typeset .grid.cards > ul > li {
  border-radius: var(--base-border-radius);
}
.md-typeset .grid.cards > ul > li:hover {
  box-shadow: 0 0 0.2rem #ffffff40;
}

/* Markdown Button */
.md-typeset .md-button {
  border-radius: var(--base-border-radius);
}

/* Critic, Mark */
ins.critic,
del.critic {
  text-decoration: none;
}

.md-typeset .critic,
.md-typeset mark {
  border-radius: 0.2rem;
  padding: 0 0.2rem;
}

.md-typeset mark {
  box-shadow: 0 0 0 0.1rem var(--md-typeset-mark-color);
}

.md-typeset ins.critic {
  box-shadow: 0 0 0 0.1rem var(--md-typeset-ins-color);
}

.md-typeset del.critic {
  box-shadow: 0 0 0 0.1rem var(--md-typeset-del-color);
}

/* Forms */
.md-search__form {
  border-radius: var(--base-border-radius);
}

[data-md-toggle="search"]:checked ~ .md-header .md-search__form {
  border-top-right-radius: var(--base-border-radius);
  border-top-left-radius: var(--base-border-radius);
}

[dir="ltr"] .md-search__output {
  border-bottom-right-radius: var(--base-border-radius);
  border-bottom-left-radius: var(--base-border-radius);
}

/* Blog - index.md */
.md-post--excerpt {
  background-color: var(--md-accent-fg-color--transparent);
  box-shadow: 0 0 0 1rem var(--md-accent-fg-color--transparent);
  border-radius: var(--base-border-radius);
}

/* Table */
.md-typeset table:not([class]) {
  border-radius: var(--base-border-radius);
}
```

</details>

I have customised Buttons, Search Bar (form), Grid Cards, Critic, Mark, Table, Code Blocks.

😎 **See some samples on my website**

- Table: https://arv-anshul.github.io/blog/learn-docker/#differences-between-gitignore-and-dockerignore
- Code Blocks: https://arv-anshul.github.io/projects/yt-watch-history/channel_reco/#model-overview
- Grid Cards and Button: https://arv-anshul.github.io/#ml-projects
- Critic: https://arv-anshul.github.io/#python
