### DISCUSSION TITLE
Content tabs do not display correctly

### DISCUSSION THREAD

**Discussion by malinwandahl** [squidfunk/mkdocs-material#6975] [Q&A] [answered]
Hi, I have an issue when trying to use content tabs. 

**Mkdocs.yml:**

```
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
```

**Markup:**

```
=== "Windows"

These are some Windows-specific instructions

=== "Linux"

These are some Linux-specific instructions
```

**Output:**
![image](https://github.com/squidfunk/mkdocs-material/assets/164848091/338b6ab9-a89e-42a6-9f44-babbb3e04d4d)

What am I doing wrong? I want the tabs to end up next to each other horizontally.
