### DISCUSSION TITLE
How to put md file in "root" of nav?

### DISCUSSION THREAD

**Discussion by TheCataliasTNT2k** [squidfunk/mkdocs-material#6985] [Q&A] [answered]
Hey,
I really like your nav generator, but how can I put a md file in the "root" of the tree?
Like [this](https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html) page does not show up in the nav on the left, but it exists nevertheless, it is like the "root" object of the nav.
So I have a tree of folders, and I want to have something in the "root" folder which tells the user, which subfolder does what.
This it not a "category" by itself, it just includes everything else.

**Comment by alexvoss** [comment]
Hi, happy to help but I would need a bit more context to give advice. Can you post a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) so I can see how you have set up your navigation so far?

**Comment by stalomeow** [comment]
If your mkdocs >= 1.5, you can directly exclude `index.md` from `nav` and add it to [`not_in_nav`](https://www.mkdocs.org/user-guide/configuration/#not_in_nav) in `mkdocs.yml`. Example:

``` yaml
# Exclude index.md from nav
nav:
  # - index.md
  - other-file.md
 
# Add index.md to not_in_nav
not_in_nav: |
  /index.md
```

Then write the subdirectory information in `index.md`.

**Reply by alexvoss** [reply]
So, how does a user find the page again, other than via their browser history? It is not immediately obvious that the logo has a link to it. IMHO this is not very user friendly.

**Reply by stalomeow** [reply]
But it seems that the questioner doesn't want the page to appear in `nav`.

**Reply by alexvoss** [reply]
Yep. I am just saying that, in my humble opinion, that is not good for usability. Not saying that what you posted does not work.

**Reply by TheCataliasTNT2k** [reply]
The user does not really need to find it.
It is more like a table of contents with brief explanations for each item.
Theoretically, I could put it in its own nav element, but it does not really have to be there.
My idea is, that you will get to it, if you do not access any item.

**Reply by TheCataliasTNT2k** [reply]
![image](https://github.com/squidfunk/mkdocs-material/assets/44349750/3092331e-6ce6-474c-84a7-a9ab7426c365)
I want to use the "Page Name" thing to put my table of contents there, so the user knows, where they find anything.
But I did not find any way to do that yet.

**Reply by alexvoss** [reply]
This combination of features does that but it uses tabs, which you may not want?

```
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes

nav:
  - Overview:
    - index.md
    - Subsection:
      - subsect/index.md
      - subsect/2ndpage.md
```

<img width="741" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/4134224/a3988b1f-5cc8-4244-89c4-54fd1eba34f6">
