### DISCUSSION TITLE
Navigation menu in multilingual site

### DISCUSSION THREAD

**Discussion by msoutopico** [squidfunk/mkdocs-material#7004] [Q&A]
I have a multilingual site, for now only in English and Russian. The main `mkdocs.yml` in the root directory says: 

```yaml
theme:
  language: en
. . .   
extra:
  generator: true
  alternate:
    - name: English
      link: /omegat-guides/en/
      lang: en
    - name: Russian
      link: /omegat-guides/ru/
      lang: ru
```

I have created two new subfolders inside `docs`: `en` and `ru`. I have moved all files in `docs`  to `en` and I'm now translating all contents to create target-language equivalents under `ru`. 

After doing that, I had to update the `nav` section, so that all paths to files start with `en`:

```yaml
nav:
  - Contents: en/index.md
  - Foo section:
      - Foo: en/foo/index.md
      - Bar: en/foo/bar.md
```

The navigation menu English version looks now as before, but the Russian version doesn't have one, see https://capstanlqc.github.io/omegat-guides/ru/translation/.

I was expecting that the navigation menu would be reproduced in all languages, with the theme replacing the language tag (e.g. using `ru` instead of `en` in all paths). 

Since the navigation menu must also be translatable, I have tried adding the `nav` section in a `mkdocs.yml` file inside both `en` and `ru` folders, but it doesn't seem to work. 

Any advice is most welcome.
