### DISCUSSION TITLE
Add icons to show changes

### DISCUSSION THREAD

**Discussion by Amaury123** [squidfunk/mkdocs-material#7011] [Q&A]
Hello, 
I am novice about mkdocs. So I would like to know which plug-in did you use for that line of code: 
`### Footnote tooltips :material-alert-decagram:{ .mdx-pulse title="Added on January 24, 2024" }`

The idea is to use something to identify the changes between 2 documentation updates. So that's why I want to reproduce that.

**Comment by alexvoss** [comment]
Taking it one-by-one, you'd need to:

- [Configure icons](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#configuration) to turn the icon placeholder into the appropriate icon
- [Add CSS](https://squidfunk.github.io/mkdocs-material/customization#additional-css) to make the icon pulse. You can see how this is done[ in the stylesheets for the Material documentation](https://github.com/squidfunk/mkdocs-material/blob/68126abb567ed9f9c5940af5ba31c6005c499596/src/templates/assets/stylesheets/main/components/_tooltip.scss#L28). Make sure to create your own class (like `.pulse`) and make the selector in the CSS specific enough.
- Finally, [turn on tooltips](https://squidfunk.github.io/mkdocs-material/reference/tooltips#configuration) to render the date tooltip.

Hope this helps.

**Reply by alexvoss** [reply]
CSS like this should do the trick. I exaggerated the effect a little:

```css
.md-content .pulse svg {
  animation: pulse 3s infinite;
}
@keyframes pulse {
  0% {
    transform: scale(0.95);
  }

  75% {
    transform: scale(1.5);
  }

  100% {
    transform: scale(0.95);
  }
}
```
