### DISCUSSION TITLE
How to stop font size increasing when increasing window width?

### DISCUSSION THREAD

**Discussion by andygock** [squidfunk/mkdocs-material#7021] [General]
Hello,

The larger I make the width, the font increases automatically and I see less and less content.

This seems counter-intuitive design-wise.

To see more, I need to make my window *smaller*

How can fix this?

Thanks.

**Comment by andygock** [comment]
Never mind, I've made it a bit more dense and fixed the font-size by adding this to a `extra.css`

```css
html {
  font-size: 125% !important;
}
.md-grid {
  max-width: 1920px !important;
}
```
