### DISCUSSION TITLE
Re-direct pages after multilingual enabled

### DISCUSSION THREAD

**Discussion by msoutopico** [squidfunk/mkdocs-material#7032] [Q&A]
Hi there, 

In my site built with mkdocs and material theme, I have enabled the multilingual option and have re-worked the organization, like so: 
```yaml
extra:
  alternate:
    - name: English
      link: /omegat-guides/en/
      lang: en
    - name: Русский
      link: /omegat-guides/ru/
      lang: ru
``` 

The site is bilingual now and users can choose to read the documentation in English or Russian. However, old users who had oringinally been given URLs like [https://capstanlqc.github.io/omegat-guides/translation/accessing-the-project](https://capstanlqc.github.io/omegat-guides/translation/accessing-the-project) cannot now land on the correct page. They get **404 - Not found**. 

Is it possible at all to make a fallback that re-directs all such URLs to the `en` version by default? For example, when the user visits, say, [https://capstanlqc.github.io/omegat-guides/translation/accessing-the-project](https://capstanlqc.github.io/omegat-guides/translation/accessing-the-project), they will end up in [https://capstanlqc.github.io/omegat-guides/en/translation/accessing-the-project](https://capstanlqc.github.io/omegat-guides/en/translation/accessing-the-project), and the same for any other endpoint with doesn't includes either `en` or `ru` in the URL (or any other language, if added in the feature to the language alternate button). 

Thanks.
