### DISCUSSION TITLE
Increase the global font size, at least 10%

### DISCUSSION THREAD

**Discussion by jonaprieto** [squidfunk/mkdocs-material#7041] [Q&A] [answered]
Is it possible to increase the global font size?
I feel the overall font size is quite small. If I type "CTRL" + "+" once on Google Chrome, I get *everything* "10%" bigger, which is enough for me. I want that to be the default. 

<img width="1496" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/1428088/eb8cfe88-6d4a-4689-9ad1-d72bd37bcdda">

**Comment by squidfunk** [comment, marked as answer]
You can add an [additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css) file with the following CSS:

``` css
html {
  font-size: calc(125% * 1.1); /* <- 1.1 equals + 10% – adjust to taste */
}
```
