### DISCUSSION TITLE
Privacy plugin: open (certain) external links in a new window/tab except...

### DISCUSSION THREAD

**Discussion by jonaprieto** [squidfunk/mkdocs-material#7048] [Ideas]
I'd like more control over which URLs should open in a new window using the built-in privacy plugin.

For example, 

```
  - privacy:
      links_attr_map:
        target: _blank
         exclude:
          - domain.io/*
          - another.net/*
```

- https://squidfunk.github.io/mkdocs-material/plugins/privacy/?h=priv#config.links_attr_map
