### DISCUSSION TITLE
Why it's not include all doc file??

### DISCUSSION THREAD

**Discussion by html5syt** [squidfunk/mkdocs-material#7069] [Q&A] [answered]
This is my config file:
```yaml
# Project information
site_name: "Always Bravely Docs"
site_description: "Always Bravely! | 文档"
site_author: "Always Bravely Community Team"
site_url: "https://docs.bravely.pp.ua/"

# Copyright
copyright: "&copy; 2024-Now Always Bravely Community Team"

# Repository
repo_name: "GitHub"
repo_url: "https://github.com/html5syt/Always-Bravely-Docs"
edit_uri: "https://github.com/html5syt/Always-Bravely-Docs/edit/main/docs"

# Configuration
docs_dir: "docs"
theme:
  name: "material"
  custom_dir: "custom"
  language: "zh"
  font:
    text: "Noto Serif Simplified Chinese"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    primary: "light blue"
    accent: "light blue"
  features:
    - tabs
    - content.code.annotate
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top
  # font:
  # text: 'Ubuntu'
  # code: 'Ubuntu Mono'
  # icon:
  logo: 'assets/icon.png'
  favicon: 'assets/icon.png'

# Extensions
markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en

# Customization
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "assets/css/custom.css"

  
# Page tree!!!目录
nav:
  - "开始→": "index.md"
  - "1. 关于社区": "about.md"
  - "2. 基本功能":
      - "basic/basic.md"
      - "2.1 注册&登录": "basic/2.1.注册&登录.md"
      - "2.2 主界面": "basic/2.2.主界面.md"
      - "2.3 发帖页": "basic/2.3.发帖页.md"
      - "2.4 帖子页": "basic/2.4.帖子页.md"
      - "2.5 小黑屋": "basic/2.5.小黑屋.md"
      - "2.6 个人设置": "basic/2.6.个人设置.md"
  - "3. 高级功能":
      - "advanced/advanced.md"
      - "3.1 私密主题": "advanced/3.1.私密主题.md"
      - "3.2 文件&照片上传": "advanced/3.2.文件照片上传.md"
      - "3.3 将社区安装为应用（PWA）": "advanced/3.3.pwa.md"
  - "4. 实用工具&技术信息":
      - "4.1 DNS解析流程图（暂未完成）": "information/4.1.dns解析流程图（暂未完成）.md"
      - "4.2 从微信里转存自定义表情包": "information/4.2.转存表情包.md"
  - "最后←": "end.md"
  - "↹回到社区↹": "https://www.bravely.pp.ua"
```
And I use gh-pages to build it ,and it's my  repository: [https://github.com/html5syt/Always-Bravely-Docs/tree/gh-pages](https://github.com/html5syt/Always-Bravely-Docs/tree/gh-pages)
You can see that gh-pages Branch don't have index.html,and it's only have 404.html(my custom).
Why? I was checked my config file,and I can sure my navigations link was correct, but it's not useful......
Sorry for my question...
