### DISCUSSION TITLE
Remove/Disable "source code in": do not show code

### DISCUSSION THREAD

**Discussion by jcerveto** [squidfunk/mkdocs-material#7083] [Q&A] [answered]
Hi there,

I want to keep my source code private. I don't want the "Source code in" option to be available for viewing my code. I've been removing the HTML tags after building the website to achieve this, but I don't think this is a long-term solution.
Does anyone know if there is an option to prevent my code from being rendered?

![issue-mkdocs](https://github.com/squidfunk/mkdocs-material/assets/98875217/ac28ccd6-d79d-4f1a-bb6e-0c215ec877bf)

Thank you in advance.

**Comment by alexvoss** [comment]
Um, I am afraid I do not recognize what you are showing us. Might be that there are corners of Material for MkDocs I have not yet seen, might be this is produced by a plugin or other extension? Apologies if I am missing something.

**Reply by jcerveto** [reply]
Hi, let me provide more details to clarify my issue.

I want to remove the following option:

![issue-mkdocs](https://github.com/squidfunk/mkdocs-material/assets/98875217/b9c4de3d-3e5d-4432-8a27-6978702da6a7)


Below is my `mkdocs.yml` configuration:


```yaml
site_name: Calculator

theme:
  name: "material"

plugins:
  - mkdocstrings
  - search


nav:
  - Calculator Docs: index.md
  - Getting Started: get-started.md
  - How-To Guides: how-to-guides.md
  - API Reference: reference.md
  - Explanation: explanation.md
  - About: about.md
```

Thank you for your response.
