### DISCUSSION TITLE
How to set dark-mode default to light?

### DISCUSSION THREAD

**Discussion by meysam81** [squidfunk/mkdocs-material#7093] [Q&A]
Hey guys,
It may be too much to ask, but I'm clueless as to how to set the default preference of dark-mode-enabled mkdocs to light.
There is a working example right here: kubernetes-sigs/gateway-api#2896
But it seems like it is not working as I expect it to.

Would you help with this, please?

Thanks.

**Comment by alexvoss** [comment]
It seems that the dark mode was removed from the site? Can you point me at the configuration that was used or, even better, create a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) that we can use to suggest how to do this?

**Reply by meysam81** [reply]
this is the snippet in the config for adding dark-mode:

```yaml
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: (prefers-color-scheme)
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  custom_dir: site-src/overrides
```

Yet even having the light mode at the top, the site is still rendering the system default. The desire is to pick the light mode as the default, which is not happening.
