### DISCUSSION TITLE
Social cards plugin looks for a blog card in a non existing location

### DISCUSSION THREAD

**Discussion by hellt** [squidfunk/mkdocs-material#7115] [Q&A] [answered]
Hey all,
I decided to leverage the social cards plugin (`9.5.19-insiders-4.53.8`) for a new docs site I am building, and during the docs build I see that the GET request failed for the blog posts cards:

```
WARNING:root:Remote image could not been reached: http://0.0.0.0:8000/assets/images/social/blog/posts/2024/launch.png. Trying again with GET and disabling SSL verification. Attempt: 1. Trace: <urlopen error [Errno 111] Connection refused>
```

The config I have is super basic:

```yaml
plugins:
  - blog:
      post_url_format: "{slug}"
      archive: false
      categories: false
      post_excerpt_max_authors: 2
      authors_profiles: true
  - social:
      cards_layout_options:
        font_family: Open Sans
```

My blog dir layout is:

```
❯ tree docs 
docs
├── blog
│   ├── index.md
│   ├── posts
│   │   └── 2024
│   │       └── launch.md
```

And the cards checking function tried to fetch the card via
```
/assets/images/social/blog/posts/2024/launch.png
``` 
path, while it actually doesn't have nor `posts`, nor `date` dirs in the path: 
```
/docs # ls -la /tmp/mkdocs_kvpe8ymm/assets/images/social/blog/eda-launch.png 
-rw-r--r--    1 root     root         45133 Apr 27 18:16 /tmp/mkdocs_kvpe8ymm/assets/images/social/blog/eda-launch.png
```

Was I able to screw this basic config somehow? Or is it an issue?
