### DISCUSSION TITLE
Showing the Author’s Name in the Block Quotations

### DISCUSSION THREAD

**Discussion by lnxpy** [squidfunk/mkdocs-material#7136] [Show and tell]
This quick trick would help you show the author's name in the block quotes. I have done some experiments and proposed using the text-marking feature inside the block quotes to specify the author's name. It needs [`pymdownx.mark`](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#caret-mark-tilde) to be included as a `markdown_extension` though.

```md
> You can define different input types, validations, default assignees, and default labels for your issue forms. ==GitHub Inc.==
```

Result:
<img width="1114" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/36054518/df28e994-cd98-49e2-a5e5-7f0f20793620">

<img width="1114" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/36054518/0e30534a-fcae-4696-9bfc-1b5ec1fc7d72">

### Implementation
Once you have `pymdownx.mark` included in your `markdown_extensions`, use this custom CSS style for the look of your block quotations.

```css
@import url('https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap');

...

.md-main blockquote {
  border: unset !important;
  border-radius: 4px;
  padding: 20px 0 20px 0;
}

.md-main blockquote p {
  display: inline;
}

.md-main blockquote:before {
  opacity: 0.1;
  z-index: -1;
  content: open-quote;
  font-family: manrope;
  font-size: 14em;
  line-height: 0.53em;
  margin-left: -25px;
  position: absolute;
}

.md-main blockquote mark {
    display: block;
    background-color: unset;
    margin: 15px 0 0 20px;
    font-style: italic;
    font-size: 19px;
    font-weight: 150;
}
```

You're welcome! :D
