### DISCUSSION TITLE
how to set `a:hover` color

### DISCUSSION THREAD

**Discussion by copdips** [squidfunk/mkdocs-material#7140] [Q&A] [answered]
Hello,

in my `stylesheets/extra.css` file, I would like to customize the link color with:

```css
a:hover {
  background-color: #dfe7f5;
  color: hotpink;
}
```

It's very strange that `background-color` takes effect, but not for `color`, any clue please?
