### DISCUSSION TITLE
Is it possible to redirect external links in the blog plugin?

### DISCUSSION THREAD

**Discussion by maheshrijal** [squidfunk/mkdocs-material#7151] [Q&A] [answered]
I'm using the blog plugin. Upon clicking the blog title, I want to redirect to an external page rather than the blog content. Is this possible?

**Comment by alexvoss** [comment, marked as answer]
Not sure I understand you right. You want to produce the blog index but when someone clicks through to the actual post you want them to be send to a URL outside your site? There is a `redirect.html` template that you could try using:

```yaml
---
template: redirect.html
location: https://www.example.com
---
```
