### DISCUSSION TITLE
rss plugin to mkdocs/material

### DISCUSSION THREAD

**Discussion by pitosalas** [squidfunk/mkdocs-material#7171] [Q&A] [answered]
I am not able to get it to work. Here's my yml:

```
site_name: Pito Salas' Blog - Today I learned...
site_description: Pito Salas Link Blog and More
site_author: Pito Salas
site_url: https://pitosalas.github.io/wp-convert/
repo_url: https://github.com/pitosalas/wp-convert
copyright: Copyright &copy 2000-2024 Pito Salas
docs_dir: docs
theme:
  name: material
  logo: images/icons/bhslogo.png
  favicon: images/icons/bhslogo.png
  features:
    - navigation.footer
    - navigation.tabs
    - search.suggest
    - navigation.expand
  custom_dir: overrides
  palette:
    primary: grey
    accent: blue
    toggle:
      icon: menu
      name: Menu

plugins:
  - search
  - blog:
      blog_dir: .
      blog_toc: true
  - tags:
      enabled: true
      tags: true
      tags_file: tags.md
  - rss:
      date_from_meta:
        as_creation: date
      categories:
        - tags
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      
nav:
  - Blog:
    - index.md
  - Recommendations: pages/Recommendations.md
  - Independent Study: pages/Independent-Study.md
  - Job Search: pages/Finding-a-job.md
  - Keeping Up: pages/Keeping-Up.md
  - 'Curacao': pages/Curacao-Notes-v2.md
  - 'RiE2024': pages/rie.md
  - tags.md

extra_css:
  - mystyle.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
```

Where is the rss url supposed to be? Can I tell from the site/ directory whether anything was generated? I can't find it.
