### DISCUSSION TITLE
Add banner based on language

### DISCUSSION THREAD

**Discussion by YozoraXCII** [squidfunk/mkdocs-material#7174] [Q&A]
I use the `alternate` feature to switch between different branches of my documentation (latest, develop, nightly).

I want to add a warning banner to every page either above or below the navigation bar highlighting to the user "You are currently viewing the nightly/develop version of the documentation, [click here] to go to the latest version"

Any suggested ways of achieving this?

```
extra:
  alternate:
    - name: Latest Docs
      link: /en/latest/
      lang: en
    - name: Develop Docs
      link: /en/develop/
      lang: en
    - name: Nightly Docs
      link: /en/nightly/
      lang: en
```
