### DISCUSSION TITLE
[Answered] Change font typeface

### DISCUSSION THREAD

**Discussion by Mujina7569** [squidfunk/mkdocs-material#7218] [Q&A] [answered]
I want to change my typeface to 300 in yml file it's possible? If possible how do I code

```yml
font:
    text: Krub
    code: Roboto Mono
```
