### DISCUSSION TITLE
Light/Dark mode toggle is not working

### DISCUSSION THREAD

**Discussion by muddi900** [squidfunk/mkdocs-material#7222] [Q&A] [answered]
I am trying to add dark mode to a site. This is the theme-block for the yaml file:

```yaml
theme:
  name: material
  pallette:
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
```

It is not working:

<img width="1770" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/37051110/830dc179-f275-446d-938d-a9ac5eee5067">

What may be causing this?
