### DISCUSSION TITLE
How to code highlight yaml?

### DISCUSSION THREAD

**Discussion by vekexasia** [squidfunk/mkdocs-material#7243] [Q&A] [answered]
Hello I cant find a way to get yaml highlighted in my documentation.

i have a snippet like:

```
```yaml
esphome:
  name: sample-esp32
  friendly_name: sample-esp32
  platformio_options:
    board_build.flash_mode: dio
```

and mkdocs.yml containing:

```
theme:
  palette:
    primary: deep purple
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - pymdownx.highlight:
        use_pygments: true
    - pymdownx.superfences
```

it seems no highlighting is present

**Comment by kamilkrzyskow** [comment, marked as answer]
Hello @vekexasia,
those are not features of the `theme`:
```
    - pymdownx.highlight:
        use_pygments: true
    - pymdownx.superfences
```
read the docs again, you need to put them in `markdown_extensions`:
```yaml
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
```

https://www.mkdocs.org/user-guide/configuration/#markdown_extensions
