### DISCUSSION TITLE
emoji not being printed/rendered

### DISCUSSION THREAD

**Discussion by Masber** [squidfunk/mkdocs-material#7270] [Q&A] [answered]
### Context

I am learning material mkdocs and trying to create a document with an emoji.
https://github.com/eth-cscs/manta/blob/docs/docs/basics.md?plain=1#L17

When I open this md file in browser in github, I can see the emoji https://github.com/eth-cscs/manta/blob/docs/docs/basics.md
![image](https://github.com/squidfunk/mkdocs-material/assets/722064/174a95b6-7dee-427a-a9ec-806fb2cfa6ad)
https://github.com/eth-cscs/manta/blob/docs/docs/basics.md#set-boot-image

However, the emoji is not rendered when opening the static document rendered by material mkdocs

https://eth-cscs.github.io/manta/basics/

Any idea why?

### Bug description

I can't see emoji in my material mkdocs page

### Related links

- [Reporting a bug](https://eth-cscs.github.io/manta/basics/)
-

### Reproduction

1. Create a md file like below:

```
## List images

## List cluster details/summary

## List hardware information

## Set runtime configuration

## Set boot image

> :warning: **Highly discourage**: only do this if sessions in the system has been deleted

## Set boot configuration

## Set kernel parameters
```

2. Set github workload as below

```
❯ cat .github/workflows/docs.yml
name: docs
on:
  push:
    branches:
      - master
      - main
      - docs
      - gh-pages
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
```

3. git add, git commit and git push

4. wait page to render

5. open link 

https://eth-cscs.github.io/manta/basics/

### Steps to reproduce

above

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [ ] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Converting to discussion, as this is definitely not a bug.

**Comment by kamilkrzyskow** [comment, marked as answer]
Hello @Masber,
GitHub provides their own rendering of icons, but to render icons when building `mkdocs-material` you have to enable the proper markdown_extensions, as per the instructions on the page.

https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#configuration

```yml
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
```

Example in a config file:
https://github.com/squidfunk/mkdocs-material/blob/f4db9de0f018427ceb6bc28d5fb095d6c1468b13/mkdocs.yml#L143-L145
