### DISCUSSION TITLE
Mkdocs navigation configuration always sorted alphabetically

### DISCUSSION THREAD

**Discussion by krystek17** [squidfunk/mkdocs-material#7307] [Q&A]
Hi,

I'm trying sort my pages like so:

```
nav:
    - Home: index.md
    - Docker:
        - docker: docker/intro.md
     - Networking:
        - networking/dns.md
    - Linux:
        - WSL: linux/wsl.md
        - Git: linux/git.md
        - CLI: linux/cli.md
 
```

But whatever I do, I always end up with my folder/page being sorted alphabetically. I do know that there are existing plugins for that but since the `mkdocs.yml` of this repo doesn't contain on of those plugins, I figured out that they must be a builtin way of doing it. 

Thanks in advance.

**Comment by kamilkrzyskow** [comment]
Hello @krystek17,
if it's not working as expected then try breaking it even more or build it up from scratch:

Does this result in only 1 page in the nav?
```yml
nav:
  - Home: index.md
```
you should get a bunch of warning errors about files not being in the navigation.
If you don't get warnings maybe you're editing the wrong file (a copy, or another project).

If everything else fails, create a minimal reproduction we could run and compare:
- https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/#creating-a-reproduction

**Comment by krystek17** [comment]
Hello @kamilkrzyskow ,

Thanks for your quick reply.

After starting from scratch I have noticed the issue, as always with yaml it was an indentation issue.

here was the content of my `mkdocs.yml`
```
site_name: "test site"
theme:
  name: material
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
   nav:
    - Home: index.md
```
`nav` was under `theme` but somehow it did not trigger an error nor a warning. 

Anyway thanks again
