### DISCUSSION TITLE
How do I deploy as an Insider?

### DISCUSSION THREAD

**Discussion by oldmanumby** [squidfunk/mkdocs-material#7336] [Q&A] [answered]
Greetings!

I recently discovered Material for MkDocs; love what I see so far. I've been playing with the installation to GitHub Pages for my hobby site; I think it will work great, so I want to use it for all my hobby sites. As such, I subscribed to the Insider program.

Now that I'm an insider, how do I deploy my GH Pages? How does VS Code and GitHub recognize me as an Insider? 

I'm not a developer, but I do understand some code. When I added the Meta plugin to my YML file, it won't deploy saying that the Meta Plugin is not installed.

I've followed what instructions I could find _(Using Insider > Getting Started)_. I don't use CLI or a local install; I just upload everything to GitHub using VS Code. Everything works except for the Insider plugins are missing for me when I deploy.

I hope my line of reasoning makes sense.

Suggestions?

**Comment by oldmanumby** [comment]
UPDATE: I realized I missed the Insider tab on the "Publishing your site" page. I updated the YML file accordingly and added the token following GiHub Secrets. However, the site will still not deploy; I get the following error ...

ERROR   -  Config value 'plugins': The "meta" plugin is not installed
Aborted with a configuration error!
Error: Process completed with exit code 1.

If however, I remove "meta" from the site (see below), it will deploy, but it doesn't look like it is deploying the Insider edition.

```
plugins:
  - search
  - blog
  - meta
```

**Reply by alexvoss** [reply]
The message that the Meta plugin is missing indicates that you are not using the Insiders Edition there. That plugin is built into Insiders but not the public version, so it can only be missing if you use the latter. Have a look to see if you have pushed the necessary changes to the GitHub workflow.

**Reply by kamilkrzyskow** [reply]
Here is the repo: https://github.com/OldManUmby/material-for-mkdocs-template
The current error concerns the secret:
- https://github.com/OldManUmby/material-for-mkdocs-template/actions/runs/9834535928/job/27146510009#step:7:17

`fatal: could not read Username for 'https://github.com/': No such device or address` 🤔 
I'm not sure if the secret token would ask for an Username 🤔... ahh

```yaml
- run: pip install git+https://${insiderssecret}@github.com/squidfunk/mkdocs-material-insiders.git
env:
  GH_TOKEN: ${{ secrets.insiderssecret }}
```

change it to
```yaml
- run: pip install git+https://$GH_TOKEN@github.com/squidfunk/mkdocs-material-insiders.git
```
or perhaps the `GH_TOKEN` is reserved by GitHub, change the environmental variable name to something like `PRIVATE_KEY` and use `$PRIVATE_KEY` in the URL

---

In another semi-unrelated project I do something like this:
```yaml
env:
  PRIVATE_ACCESS: ${{ secrets.PRIVATE_ACCESS }}
# ...
run: git clone --depth 10 https://$GITHUB_ACTOR:$PRIVATE_ACCESS@github.com/kamilkrzyskow/
```
but I don't think this approach (with Username actor) is viable for general use, or for this `pip install` example.

**Reply by oldmanumby** [reply]
I don't think changing the code is the answer. I followed the instructions located at: [squidfunk.github.io](https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions-insiders). I copy/pasted exactly what is there for Insiders; I only changed the GH_TOKEN according to the instructions. So, if the code is wrong, then everyone should be seeing this issue.

Am I creating the SECRET correctly? The instructions say: "Remember to set the GH_TOKEN environment variable to the value of your [personal access token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) when deploying [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/), which can be done using [GitHub secrets](https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets)."

So, I went to the repo here (see screenshots at the bottom) and put in a new personal access token (classic): https://github.com/OldManUmby/material-for-mkdocs-template/settings/environments

Did I do that correctly?

---

I just tried it again; this time I named the variable "GH_TOKEN" just to make sure.

```
  - run: pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
  - run: mkdocs gh-deploy --force
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
```

I got the same error again:

```
  × git clone --filter=blob:none --quiet 'https://****@github.com/squidfunk/mkdocs-material-insiders.git' /tmp/pip-req-build-edcnbydp did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

SUGGESTIONS?

---

<img width="784" alt="Screenshot 2024-07-08 at 8 52 19 AM" src="https://github.com/squidfunk/mkdocs-material/assets/22547499/12b20b41-2ba8-466b-a6ae-696542163c75">



<img width="792" alt="Screenshot 2024-07-08 at 8 53 03 AM" src="https://github.com/squidfunk/mkdocs-material/assets/22547499/6d0c3929-3441-41c7-a298-0303a58182ef">

**Reply by kamilkrzyskow** [reply]
> I don't think changing the code is the answer. I followed the instructions located at: [squidfunk.github.io](https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions-insiders). I copy/pasted exactly what is there for Insiders; I only changed the GH_TOKEN according to the instructions. So, if the code is wrong, then everyone should be seeing this issue.

Not true since you changed `GH_TOKEN` into `insiderssecret` only in the URL.

The values in red need to match.
![image](https://github.com/squidfunk/mkdocs-material/assets/34622465/a90948da-7098-44ca-92be-1c431c80808e)

> I just tried it again; this time I named the variable "GH_TOKEN" just to make sure.

Good, but notice how you're correctly using the `secrets` context in `${{ secrets.GH_TOKEN }}`, but have set the `GH_TOKEN` as a normal not encrypted variable, which you later blurred out. You're supposed to set the secret above.

![image](https://github.com/squidfunk/mkdocs-material/assets/34622465/db6410c0-5e6b-441e-9786-96e3e847fb12)

**Comment by oldmanumby** [comment]
Ok, I'll give that a try and let you know. If that's the answer, then the instructions are wrong, they specifically state Enviroment Variable, not Enviroment Secret. :)

BRB.

**Reply by oldmanumby** [reply]
So, I removed the ENV Variable and added an ENV Secret with the same "GH_TOKEN" name, then re-ran the action again, but I got the same results.

<img width="940" alt="Screenshot 2024-07-08 at 2 02 21 PM" src="https://github.com/squidfunk/mkdocs-material/assets/22547499/2d7bf3d9-3ea9-4f47-a3ef-65432ff63ec4">

I know I'm either overthinking it or missing something obvious; LOL.

Here is my ci.yml ...

```
name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
      - run: mkdocs gh-deploy --force
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
```

**Reply by kamilkrzyskow** [reply]
The last action I see is from 5 hours ago:
- https://github.com/OldManUmby/material-for-mkdocs-template/actions
is it somewhere else @OldManUmby?

```
on:
  push:
    branches:
      - master
      - main
```
it's only invoked on the push to the repo, so a change to the variable in the backend doesn't trigger a re-run
