### DISCUSSION TITLE
Adding watermarks to markdown pages?

### DISCUSSION THREAD

**Discussion by rachel-rigdon-sp** [squidfunk/mkdocs-material#7365] [Q&A] [answered]
Has anyone been able to apply watermarks or a semi-transparent image/text on markdown pages? I need to share a zipped version of my docs with a confidential watermark, similar to the image I've attached. 

Would this be something we'd use CSS and the content override for, or is this something I should ask in the MkDocs repo instead?

![Draft Watermark Example](https://github.com/user-attachments/assets/5ecf6161-3191-42fd-a984-7f34ccced9bc)

**Comment by alexvoss** [comment]
One option would be to use a background image, which you could create as an SVG, for example, and you could use a drawing program to give it the slant and let CSS deal with the business of repeating it across the page. 

Have a look to see if this would work:
```css
.md-content .md-typeset {
   background-image: url("assets/images/draft.svg");
   background-size: 100%;
}
```

There is a chance that some elements may have a background that covers the image, though. Seems to be the case with admonitions. I am sure it is also possible to cook up some CSS that just places the draft message over everything. That would take a bit of research or deeper CSS skills than I have a the moment.

**Comment by alexvoss** [comment, marked as answer]
Found [a Codepen](https://codepen.io/maheshambure21/pen/mJbWKq) that does a similar things and modified the CSS a bit to get this:

```css
.md-content__inner.md-typeset:before {
  content: "DRAFT";
  -webkit-transform: rotate(331deg);
  -moz-transform: rotate(331deg);
  -o-transform: rotate(331deg);
  transform: rotate(331deg);
  font-size: 20em;
  color: rgba(255, 5, 5, 0.17);
  position: absolute;
}
```

Hope this helps. Might need some refinement.
