### DISCUSSION TITLE
Adding custom icons in custom theme extending Material for MkDocs

### DISCUSSION THREAD

**Discussion by joapuiib** [squidfunk/mkdocs-material#7371] [Q&A] [answered]
I am having trouble adding [custom icons with Markdown](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#additional-icons) inside a custom theme that extends this theme. I'm able to use a custom icon placed in the custom theme `.icons` folder in the configuration, but not in Markdown.

I've looked at #5199, and I seem to have a similar problem, but the structure of the project and the goal is not the same.

---
### File structure
Available at: https://github.com/joapuiib/mkdocs-custom-theme
```
.
├── custom_theme
│   ├── .icons
│   │   └── devicons
│   │       └── java-plain.svg
│   ├── __init__.py
│   └── mkdocs_theme.yml
├── docs
│    └── index.md
├── mkdocs.yml
└── pyproject.toml
```

__`mkdocs.yml`__:
```
site_name: My Docs

theme:
  name: custom-theme
  icon:
    logo: devicons/java-plain # This works
```
---
### Plugin installation
I've installed my plugin via `pip`:
```console
~/mkdocs-custom-theme $ pip install .
```

---
Result:
![image](https://github.com/user-attachments/assets/f204003a-1075-44dd-b8b4-f96be2360a68)

---
### What I've tried
I have tried to configure the plugin in `pymdownx.emoji`in `mkdocs.yml` with a `custom_dir`, and it works (while `mkdocs serve`) on the same project as I have created the custom theme.

```yml
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:          
          - custom_theme/.icons
```
> Note that I have referenced the icons by folder, not hte theme name (`custom_theme/.icons` instead of `custom-theme`).

However, this configuration fails when deploying (https://github.com/joapuiib/mkdocs-custom-theme/actions/runs/9964680935/job/27533499144)

Also, I have tried installing the package locally and using it in another project. I can use the custom icons in the configuration, but not as an emoji.

Thanks in advance!
