### DISCUSSION TITLE
Combine navigation.tabs and sections folding

### DISCUSSION THREAD

**Discussion by yves-chevallier** [squidfunk/mkdocs-material#7376] [Q&A] [answered]
My documentation is composed of several chapters. Each chapter should be displayed on the nav top bar. Then the sections would be rendered on the left toc. 

```
.
└── foo
    └── bar
        ├── baz.md
        └── qux.md
```

### With `navigation.tabs`

![image](https://github.com/user-attachments/assets/c96d6d69-125a-438b-8d2b-f076762c3985)

### Without `navigation.tabs`

![image](https://github.com/user-attachments/assets/dbef279b-bee0-4573-9282-fc5fb8d8d6da)

### How to reproduce

I use `awesome-pages` normally, but without the plugin I get the same result. Here my `mkdocs.yml`:

```yml
site_name: My Docs
nav:
  - Foo:
    - Bar:
      - Baz: foo/bar/baz.md
      - Qux: foo/bar/qux.md
theme:
  name: material
  features:
    - navigation.sections
    - navigation.tabs      # <-- If enabled, no arrows
    - toc.follow
plugins:
  - info
```

To build the project:

```make
all: content
	poetry run mkdocs serve

content: docs/foo/bar/baz.md docs/foo/bar/qux.md | docs/foo/bar
	echo "# Baz" > docs/foo/bar/baz.md
	echo "# Qux" > docs/foo/bar/qux.md

docs/foo/bar:
	mkdir -p $@

.PHONY: all content
```

And here the `pyproject.toml`

```toml
[tool.poetry]
name = "test"
version = "0.1.0"
description = "Test caret"
authors = ["Yves Chevallier <yves.chevallier@heig-vd.ch>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
mkdocs = "^1.6.0"
mkdocs-material = "^9.5.27"
mkdocs-material-extensions = "^1.3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

In my configuration if I enable `navigation.tabs` get the desired result with the top navbar. However I loose the folding/unfolding feature on the left toc. 

Would it be possible to combine both?

If I remove the `md-nav__item--section` from the elements I see the arrows, but then the title isn't bold anymore.
