### DISCUSSION TITLE
How to specify an entire directory to render docs from

### DISCUSSION THREAD

**Discussion by k3yss** [squidfunk/mkdocs-material#7407] [Q&A]
I want to specify an entire directory consisting of ~50 markdown files to render on the sidebar, what I want to the navigation bar to look like is 
- **Languages**
    -  Language1
    - Language2
    - ...
    - Language50
 - **Services**
    -  Service1
    - Service2
    - ...
    - Service50
    
    I tried to specify it this way but it doesn't seem to work
 ```yaml
nav:
  - Home: index.md
  - Usage:
      - languages: reference/autogen/
      - services: reference/autogen/service/
 ```
 
 Here is my entire `mkdocs.yaml` https://github.com/cachix/devenv/blob/main/mkdocs.yml
