### DISCUSSION TITLE
mkdocs gh-deploy starts server in CI job

### DISCUSSION THREAD

**Discussion by fansari1-equinix** [squidfunk/mkdocs-material#7409] [Q&A]
Hi guys.
I am trying to use the [squidfunk/mkdocs-material container](https://hub.docker.com/r/squidfunk/mkdocs-material) to run the command `mkdocs gh-deploy` into my CI.

The idea is to automate the deployment whenever anything changes in the doc application repo so that the `mkdocs gh-deploy` command will automatically deploy the changes on the respective pages.

However, I'm facing issues in the CI where the `mkdocs gh-deploy` command. 
The server starts locally within the CI environment and the job does not pass/fail.

![image](https://github.com/user-attachments/assets/aee179a8-6fd2-4af4-9748-c8940f095c19)

How should I proceed if I just want to execute the `mkdocs gh-deploy` in the CI?
Thanks.

My Buildkite CI for ref.

```
steps:
  - label:  ":shrek: Deploy docs"
    key:  "mkdocs-deploy-docs"
    plugins:
      - docker#v5.9.0:
          image:  "squidfunk/mkdocs-material"
          commands: |
            "mkdocs gh-deploy"
```
