### DISCUSSION TITLE
Media Changes on Palette Doesn't Work

### DISCUSSION THREAD

**Discussion by lnw143** [squidfunk/mkdocs-material#7414] [Q&A] [answered]
![palette](https://github.com/user-attachments/assets/f303c8ce-a40a-4e55-b4b1-80c320193fb4)

Like the picture above shows, when I change the palette, the media didn't change.

I want to solve it because it cause the giscus didn't change theme when I change the palette, and I have removed customizations in `mkdocs.yml`.

Could anyone give me a possible reason or tell me if it's a bug? I'm not really good at English, thanks for reading.

**Comment by lnw143** [comment]
`mkdocs.yml` :

```yaml
theme:
  name: material
  language: 'zh'
  # custom_dir: overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: white
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
```
