### DISCUSSION TITLE
Why does MkDocs Material not use MkDocs standard locale config key?

### DISCUSSION THREAD

**Discussion by yves-chevallier** [squidfunk/mkdocs-material#7446] [Q&A] [answered]
On [MkDocs](https://www.mkdocs.org/user-guide/localizing-your-theme/) documentation, to configure the language you have this: 

```yml
theme: 
   name: mkdocs
   locale: fr
```

On the other hand on MkDocs Material you have this:

```yml 
theme:
  name: material
  language: en
```

So for any multilingual plugins one should test both cases: 

```py
from toolz.dicttoolz import get_in
lang = (
    get_in(["theme", "language"], config)
    or get_in(["theme", "locale"], config)
    or get_in(["plugins", "search", "lang"], config)
    or "en"
)
```

Is there any particular reason why the setting does not follow MkDocs standard?
