### DISCUSSION TITLE
Suggestions for partial builds using exclude patterns

### DISCUSSION THREAD

**Discussion by slhck** [squidfunk/mkdocs-material#7524] [Q&A] [answered]
I have docs set up for different tools, and my nav may look like this:

```yml
nav:
  - Tool1:
    - index.md
    - Introduction: tool1/introduction.md
  - Tool2:
    - index.md
    - Introduction: tool2/introduction.md
```

I usually build the docs with all of these tools, but for some use cases I might want to only build a part of the docs, e.g. for one tool only, or with one removed.

I came across https://github.com/apenwarr/mkdocs-exclude which does part of the job; it removes the files for, say, `tool2` completely for the docs. However, the nav entry is still present.

is there any plugin or solution that could modify the nav in-place so that the exclude patterns are also pruned from the navigation tree?
