### DISCUSSION TITLE
Can I hide the navigation menu altogether?

### DISCUSSION THREAD

**Discussion by lucharo** [squidfunk/mkdocs-material#7528] [General]
My site is super simple, just a home page with a massive grid of articles/posts and a search bar. 

My navigation bar only contains "Home" (accessible via the menu - burger button). So, it's a bit sad and I'd like to remove it and default to just going to the homepage if the user clicks on the page title on the top left.

**Comment by lucharo** [comment]
Oh, I see when the screen is quite wide the menu button does what I want, i.e. it disappears. There must be a media query behind this I'll see if I can switch it off easily

**Comment by lucharo** [comment]
For others interested add this to your extra.css:

```css
@media screen {
    .md-header__button.md-logo {
      display: block;
    }

    .md-header__button.md-icon[for=__drawer] {
        display: none
    }
}
```
