### DISCUSSION TITLE
Instant preview font size

### DISCUSSION THREAD

**Discussion by gelencserzsoltpeter** [squidfunk/mkdocs-material#7606] [Q&A]
Hello everyone!

I’m using instant preview mode in Material for MkDocs, but I’m facing issues with the font size. The text in the preview appears much smaller than intended, while elements like quote blocks retain their original size. Additionally, the tooltips and inline footnotes (when they appear directly within a paragraph) also have a small font size that I can’t seem to increase, despite trying various CSS adjustments. How can I consistently increase the font size for these elements in the instant preview?

Thanks!

**Comment by squidfunk** [comment]
For now, you can use the following additional CSS:

``` css
[role=dialog] > .md-tooltip2__inner {
  font-size: .8rem; /* Adjust to taste */
}
```
