### DISCUSSION TITLE
how to set some pages open toc

### DISCUSSION THREAD

**Discussion by 361way** [squidfunk/mkdocs-material#7609] [Q&A]
if the mkdocs.yaml file setting like this,  i didnot open the toc on the right part of the page. but i want open it in some pages. how can i do it ?

```yaml
theme:
  nav_style: "horizontal"
  nav_levels: 2
  name: material
  highlightjs: true
  title_order: page_title,title,filename
  palette:
    primary: teal
  features:
    - navigation.tabs
    - navigation.path
    # - navigation.expand 
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.top 
    - content.code.copy
    - navigation.footer
    #- toc: true
    - toc.integrate
    - sidebar:
      hide_on_mobile: true
```

i check the document like this in the official website . only have the hide navigation and toc . but i don't know how to open in a single page 

![image](https://github.com/user-attachments/assets/d6ec5785-3a1d-40a4-b621-a144c8bcd1e5)

```yaml
---
title: 
description: 
date: 
tags:
  - test
 features:
  - toc: true
---
```

i am try doing like this in the head of a mardown page, but it is not work.
