### DISCUSSION TITLE
Does mkdocs-material leverage any input validation or content security policy?

### DISCUSSION THREAD

**Discussion by SteveBehm** [squidfunk/mkdocs-material#7649] [Q&A] [answered]
I have created an Material-themed MkDocs site for my company's technical documentation. I am using the search.suggest feature and am wondering if there is any input validation or content security policy employed to protect the search feature from being abused?

My goal is to ensure the search feature is not vulnerable to any type of attack.

**Comment by squidfunk** [comment]
MkDocs generates a static site. Since there's no data sent to a server, not validation is done on our side. What we make sure is that deep linking to search results does not allow for XSS. Content security policy should, in general, be set on the server-side, but you could also add the respective `http-equiv` meta tags if necessary. As a theme, we can't do it, since we do not know what external scripts you want to allow and what not.

**Reply by SteveBehm** [reply]
Okay thanks for the response and information!

If we choose to go the meta tags route, would that go in the theme section of the mkdocs.yml file within an extra section?

```
theme:
  logo: images/gearlogo.png
  favicon: images/gearlogo.png
  name: material
  custom_dir: overrides
  extra:
    - |
      <meta http-equiv="Content-Security-Policy" content="default-src 'self' *.example.com example.com; script-src 'self' *.example.com example.com; style-src 'self' *.example.com example.com; img-src 'self' *.example.com example.com; connect-src 'self' *.example.com example.com; font-src 'self' *.example.com example.com; frame-src 'self' *.example.com example.com; media-src 'self' *.example.com example.com; object-src 'none'; report-uri /csp-violation-report-endpoint;">
```
