### DISCUSSION TITLE
Why root level pages cannot be expanded?

### DISCUSSION THREAD

**Discussion by neo-mashiro** [squidfunk/mkdocs-material#7677] [Q&A] [answered]
![image](https://github.com/user-attachments/assets/b3b428e4-9c67-4603-902a-16a8891a1db7)

```yaml
nav:
  - Home: index.md
  - Getting started:
    - Installation: getting-started.md
    - Creating your site: creating-your-site.md
    ......
    - License: license.md
    - Tutorials:
      - tutorials/index.md
      - "Blogs":
        - tutorials/blogs/basic.md
        - tutorials/blogs/navigation.md
        - tutorials/blogs/engage.md
      - "Social cards":
        - tutorials/social/basic.md
        - tutorials/social/custom.md
```

Hello, I have a simple question. Why are root level pages not expandable? Is this by design?

Here I'm using the `Getting Started` tab as an example. Within this tab, we have a couple root level pages like `Creating your site`, `Customization`. From both YAML and the screenshot, you can see that `Tutorials` is also a root level page (at level 1), which has two child pages `Blogs` and `Social cards` (at level 2), the `Blogs` page then has its own child pages like `Basic blogs` (at level 3).

While level 2 pages have a "expand/collapse" mark on the right to show/hide its child pages at level 3, root level pages don't have such a mark. Instead, level 2 pages are always expanded just like root level pages, there's no way to hide them and they even have the same level of indentation as root pages. I wonder why it behaves like this.

In my case, I have a root level page that contains a bunch of child pages at level 2, I just want to be able to show/hide them using a "expand/collapse" mark on the right, but that doesn't seem to be supported.

**Comment by neo-mashiro** [comment]
```YAML
....
    - License: license.md                  # level 1 (root)
    - Tutorials:                           # level 1 (root)
      - tutorials/index.md
      - "":                                # level 2 <- make a dummy section here
        - "Blogs":                         # level 3 <- move the original level 2 branch one level deeper
          - tutorials/blogs/basic.md       # level 4
          - tutorials/blogs/navigation.md  # level 4
          - tutorials/blogs/engage.md      # level 4
```

Finally I found a workaround. Knowing that level 2 pages behave the same as root level pages, I can just make a dummy empty section `- "":` at level 2 and move the original level 2 branch underneath this level (so that they are now one level deeper). Unfortunately, the empty section `- "":` also introduces some vertical spacing that doesn't look good.

It seems to me that this is a limitation of mkdocs itself which just got carried over to mkdocs-material.

**Comment by neo-mashiro** [comment, marked as answer]
OK I figured out the solution. Once I turned off the `navigation.sections` feature everything works fine.
```YAML
theme:
  features:
    - navigation.sections
```
The documentation clearly states that
> When sections are enabled, top-level sections are rendered as groups in the sidebar...
> If both feature flags [navigation.tabs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs) and [navigation.sections](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-sections) are enabled, sections are rendered for level 2 navigation items.

So this is expected behavior. Sorry for missing that info when reading the documentation.
