### DISCUSSION TITLE
Download button for code blocks

### DISCUSSION THREAD

**Discussion by joapuiib** [squidfunk/mkdocs-material#7694] [Ideas]
Hello!

I am constantly adding files to my documentation in this way:

```md
\```java
--8<-- "docs/path/to/file"
\```
```

I would love to have a __Download button__ in code blocks, similar to [Code Copy Button](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=code+copy#code-copy-button).

**Comment by squidfunk** [comment]
Thanks for suggesting! This is an excellent use case for a third party extension ☺️ The tricky part will be resolving the file URLs, as they can point anywhere in the repository, e.g., outside of the `docs` directory, which means the files need to be explicitly copied to the build directory, or point to a valid URL on GitHub, if the repository is hosted there. It's not trivial, but definitely possible to pull off! If you decide to follow this path, feel free to share your results here! 🚀

**Reply by joapuiib** [reply]
In order to address this, I need to know which would be the best approach.

My initial thought was to add an attribute (`download` in this example, but could be any) telling the relative path of the file using `attr_list`.

```md
\```java
--8<-- "docs/path/to/file"
\```
{download="../../path/to/file"}
```
> [!NOTE]  
> Files should exist in the `docs` directory and the path should be a relative to the current page. AFAIK MkDocs doesn't allow absolute urls.

AFAIK, the Code Copy Button is generated automatically with JavaScript. I thought that maybe this theme could do the same with `<code>` blocks that have a `download` attribute.

It would be nice to have a good integration with this theme, specially in styling the download button and have a tooltip similar to copy button.

---

If this approach is feasible, the next step would be to set the `download` attribute automatically, so it's easier to use.

In that case, I think a MkDocs plugin could do the trick, since it knows the path of each page and can compute the relative path to the file. In this case, also using files outside `docs` could be achieved.

**Reply by facelessuser** [reply]
Do you want to download the file or download the text in the code block? I suspect downloading the content in the code block is sufficient and could be accomplished without worrying about paths.

**Reply by joapuiib** [reply]
In my case, there's no difference between the content of the code block and the content of the file, so it doesn't matter.

A possible use case could be to just show a part of the file in the codeblock, but the whole file is downloaded.

**Reply by facelessuser** [reply]
You can attach a data-* attribute and trigger off that. Use Javascript to add a button to all blocks with that data attribute.

````md
```lang {data-download="1"}
Content
```
````

If you only need the code content, the JS can simply download that.

If you want to link a file, if your file content is not included in your documentation (which quite often is the case) use an full URL and the JS can just create the button as a link with the `download` attribute: https://www.w3schools.com/tags/att_a_download.asp.

````md
```lang {data-download="https://github.com/user/project/blob/main/project/file.ext"}
Content
```
````

You could create a custom fence that injects the button without JS via custom fences in SuperFences. Granted, most of these cases require you to get your hands a little dirty and do some coding. If that's not an option, then you'd have to get someone to add a feature here.

**Reply by kamilkrzyskow** [reply]
I would also go with the code block content approach. The `Highlight` extension also provides the option to add the lang name [`pygments_lang_class`](https://facelessuser.github.io/pymdown-extensions/extensions/highlight/#options), which could be used for deciding on the extension of the downloaded file, or use the `data-download=` as the container to hold the filename containing the extension.

**Comment by joapuiib** [comment]
I like @facelessuser approach:

- `data-download="1"`: Download the code block content:
  - Challenge: Compute the download filename. Maybe we can use [`title`](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#code-block-title-headers) or another `data-*` attribute.
- `data-download=url`: Create a link button with a `download` attribute.

---

This would be achieved with JS, so I guess just an `extra_javascript` is needed.

I'll start to work on a prototype.

**Reply by joapuiib** [reply]
This is what I have at the moment:

## `download-button.js`

- `data-download=1`: Downloads the code block content. Gets the filename from `title`.
- `data-download=url`: Creates a link with `download` attribute.

TODO:

- Language awareness button `title`.
- Render tooltip.

<details>

```js
document$.subscribe(function() {
  var codeblocks = document.querySelectorAll(".highlight[data-download]")
  codeblocks.forEach(function(el) {
    mountDownloadButton(el)
  })
})

function mountDownloadButton(el) {
  var code = el.querySelector('code')
  var data_download = el.getAttribute('data-download')
  var parent = code.closest('pre')

  if (data_download == "1") {
    var filename = el.querySelector('span.filename').textContent
    if (filename) {
      const button = renderDownloadContentButton(parent.id, filename)
      parent.insertBefore(button, code)
    }
  } else {
    const button = renderDownloadFileButton(parent.id, data_download)
    parent.insertBefore(button, code)
  }
}

function renderDownloadContentButton(id, filename) {
  const button = document.createElement("button");
  button.className = "md-download md-icon";
  button.title = "Download";

  // Attach a click event listener to handle the download logic
  button.addEventListener("click", function() {
    const codeElement = document.querySelector(`#${id} > code`);
    if (codeElement) {
      const codeContent = codeElement.textContent;
      const blob = new Blob([codeContent], { type: "text/plain" });
      const url = URL.createObjectURL(blob);

      const a = document.createElement("a");
      a.href = url;
      a.download = filename;
      a.click();

      URL.revokeObjectURL(url); // Clean up the URL after download
    }
  });

  return button;
}

function renderDownloadFileButton(id, filepath) {
  const button = document.createElement("a");
  button.className = "md-download md-icon";
  button.title = "Download";
  button.setAttribute("href", filepath);

  var basename = filepath.replace(/^.*[\\/]/, '')
  button.setAttribute("download", basename);

  return button;
}
```

</details>

## `download-button.css`

<details>

```css
:root {
  --md-download-icon: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M5 20h14v-2H5m14-9h-4V3H9v6H5l7 7z"/></svg>');
}

:hover>.md-download {
    color: var(--md-default-fg-color--light);
}

.md-download,
a.md-download {
    border-radius: .1rem;
    color: var(--md-default-fg-color--lightest);
    cursor: pointer;
    height: 1.5em;
    outline-color: var(--md-accent-fg-color);
    outline-offset: .1rem;
    position: absolute;
    right: 2em;
    top: .5em;
    transition: color .25s;
    width: 1.5em;
    z-index: 1;
}

a.md-download {
    display: flex;
    align-items: center;
}

.md-download:after {
    background-color: currentcolor;
    content: "";
    display: block;
    height: 1.125em;
    margin: 0 auto;
    -webkit-mask-image: var(--md-download-icon);
    mask-image: var(--md-download-icon);
    -webkit-mask-position: center;
    mask-position: center;
    -webkit-mask-repeat: no-repeat;
    mask-repeat: no-repeat;
    -webkit-mask-size: contain;
    mask-size: contain;
    width: 1.125em;
}

.md-download:focus, .md-download:hover {
    color: var(--md-accent-fg-color);
}
```

</details>

## Result

![image](https://github.com/user-attachments/assets/6edb5e88-4cc9-425f-a1ed-635f9fbbe51e)

Demo available at: https://joapuiib.github.io/mkdocs-material-joapuiib/features/code_blocks/#downloadable-block

---

All the code is inspired by [`code.copy`](https://github.com/squidfunk/mkdocs-material/blob/master/src/templates/assets/javascripts/components/content/code/_/index.ts) implementation.

Any fix or improvement is welcome.

---

@squidfunk, do you think this could be a feature shipped in the theme?

I think it would not be difficult to implement it in Material for MkDocs TypseScript source code, since the architecture is already defined.

Also, it would be easier to use functions like `mountInlineTooltip2()` or use `translation()`

Also CSS is already defined. Only a new class `md-download` has to be added.
