### DISCUSSION TITLE
Making social logo bigger

### DISCUSSION THREAD

**Discussion by thomas-saigre** [squidfunk/mkdocs-material#7697] [Q&A] [answered]
In #2933 an answer is provided to change the size of the logo of the website from and `extra.css` file.

I'm looking to do the same transformation for the logo included at the bottom line from the `social` section.
I used this code
```css
.md-social__link img,
.md-social__link svg {
  height: 320px !important;
  width: auto !important;
}
```
Maybe I am mistaken in the class name (that I found with the Firefox inspector).
How could I achieve it ?

Thanks in advance.

**Comment by kamilkrzyskow** [comment, marked as answer]
Hello @thomas-saigre,
the limiting factor when it comes to the size of the SVGs is the parent `a.md-social__link` tag.
Adjust the width/height for it:
```css
.md-social__link {
  height: 2rem;
  width: 2rem;
}
.md-social__link svg {
  max-height: unset;
  max-width: unset;
}
```
![image](https://github.com/user-attachments/assets/cbd1a3b7-880d-43ec-b75a-cfd4ce07b45d)
