### DISCUSSION TITLE
Absolute links from "docs-de." to "docs." lead to the wrong page when using the latest version of MkDocs Material Insiders

### DISCUSSION THREAD

**Discussion by lastzero** [squidfunk/mkdocs-material#7746] [Q&A]
After the recent update to **MkDocs Material v9.5.45+insiders-4.53.14**, links from https://docs-de.photoprism.app/ (de) to https://docs.photoprism.app/ (en) no longer lead to the actual linked page, but to the same page in the English documentation (if it exists), or to the English start page otherwise.

You can test this by clicking e.g. on the first link of this page ([deinem originals Ordner](https://docs.photoprism.app/getting-started/docker-compose/#photoprismoriginals)):

- https://docs-de.photoprism.app/user-guide/backups/

It should take you to `https://docs.photoprism.app/getting-started/docker-compose/#photoprismoriginals`, but instead it loads `https://docs.photoprism.app/user-guide/backups/`.

The corresponding configuration for the alternate languages is as follows

```yaml
# External links.
extra:
  generator: false
  homepage: https://www.photoprism.app/
  alternate:
    - name: 🇬🇧 English
      link: https://docs.photoprism.app/
      lang: en
    - name: 🇩🇪 Deutsch
      link: /
      lang: de
```

Is this a glitch that will be fixed in an upcoming update, or do we need to change something in our configuration to ensure the links work as expected? :thinking:
