### DISCUSSION TITLE
Adjusting position of md-clipboard md-icon (code block copy to clipboard button)

### DISCUSSION THREAD

**Discussion by rmscode** [squidfunk/mkdocs-material#7806] [Q&A] [answered]
I wanted my mkdocs site to be full width, so I added this to extra.css:

```css
.md-grid {
    max-width: 100%;
    /* or 100%, if you want to stretch to full-width */
}
```

As a result, code blocks, among other things, are also full width. I would much rather have codeblocks, admonitions, etc. keep their default widths. 

Anyway, I found the `.md-code__content` class and made my desired adjustments but I don't know how to get the copy button (`.md-clipboard`?) back "inside" the code block.

![image](https://github.com/user-attachments/assets/096986d4-bc80-44b5-8222-0c8937833747)

**Comment by A3Bagged** [comment]
@rmscode 
> Anyway, I found the `.md-code__content` class and made my desired adjustments but I don't know how to get the copy button (`.md-clipboard`?) back "inside" the code block.

Could you check with inspector/DevTools what `position` the codeblock has? If none is applied the icon (with most likely `position: absolute;` applied) will go to the nearest parent with `position: relative;` or `position: aboslute;` If the `.md-code__content` doesn't have position applied it goes outside of this element. To counter this and keep the icon within the codeblock you could add the following:

```
.md-code__content {
    position: relative;
}
```

See if that works :) I also recommend taking a look at the [css position](https://www.w3schools.com/css/css_positioning.asp) property

**Comment by kamilkrzyskow** [comment, marked as answer]
Hello @rmscode,
the `.md-code__content` doesn't include the buttons. At least looking at the example here:
```css
.md-grid {
  max-width: initial;
}
.md-code__content {
  max-width: 50%;
}
```
- https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
![image](https://github.com/user-attachments/assets/4996c5e4-968c-4d6f-af4d-4fca69801ebb)

There is a `pre` element which wraps the output and there is also the `div` wrapper with the `.highlight` class.
So instead of targetting `.md-code__content` target the `highlight` class.
```css
.highlight {
  max-width: 50%;
}
```
