### DISCUSSION TITLE
How do you display the author name in the blog landing post?

### DISCUSSION THREAD

**Discussion by honeyedoasis** [squidfunk/mkdocs-material#7833] [Q&A] [answered]
Sorry if this is already somewhere, I couldn't find any info about this!
When scrolling in the "overview page" it only shows the avatar, like so:

![image](https://github.com/user-attachments/assets/4ad82751-6b3e-493d-8524-5018c4eedd62)

Is there a way to also display the author name here?

**Comment by niclasheinz** [comment]
Hi @honeyedoasis 

As described in our [documentation](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/?h=blog#adding-authors), you need to add a `.authors.yml` in `docs/blog/` as following:

``` yaml
authors:
  niclasheinz:
    name: Niclas Heinz
    description: Author
    avatar: https://secure.gravatar.com/avatar/1ead7255950b0f5469f171c317a16cd5d5e7a2710b44badb6d4f8604de29887d?s=1600&d=identicon
```

and then you need to define the metadata of your blog post:

``` text
---
date: 2024-12-27
authors:
  - niclasheinz
---

# Your blog post ...
```
