### DISCUSSION TITLE
Alternative fonts for headers

### DISCUSSION THREAD

**Discussion by LandonTClipp** [squidfunk/mkdocs-material#7834] [Show and tell]
I wanted to share how I added support in the theme configuration to specify an alternative font for header sections. mkdocs-material currently does not support this and I couldn't find any other discussions on how to do this, so I'm writing this show-and-tell so all future generations can learn! 😄 

This follows the configuration pattern already established [here](https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/?h=font#configuration).

[Overridding](https://squidfunk.github.io/mkdocs-material/customization/?h=over#overriding-blocks) `main.html`
-------------------------

Place a file at `overrides/main.html` and add the following content:

```html
{% extends "base.html" %}

{% block fonts %}
{% if config.theme.font != false %}
{% set text = config.theme.font.get("text", "Roboto") %}
{% set code = config.theme.font.get("code", "Roboto Mono") %}
{% set header = config.theme.font.get("header", text ) %}
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family={{
    text | replace(' ', '+') + ':300,300i,400,400i,700,700i%7C' +
    code | replace(' ', '+') + ':400,400i,700,700i%7C' +
    header | replace(' ', '+') + ':300,300i,400,400i,700,700i'
  }}&display=fallback">
<style>
:root{
    --md-text-font:"{{ text }}";
    --md-code-font:"{{ code }}";
    --md-header-font:"{{ header }}";
}
</style>
{% endif %}
{% endblock %}
```

This is essentially the same as the theme defaults, but it adds the `--md-header-font` variable and modifies the stylesheet URL to grab whatever the `header` jinja variable is set to.

Create [additional CSS](https://squidfunk.github.io/mkdocs-material/customization/?h=extra+css#additional-css)
------------------------

Now that the variable has been added to the root CSS section, you can add more CSS selectors to propagate the font family you've defined. Here is my `extra.css`:

```css
body {
    --md-header-font-family:
      var(--md-header-font, _),
      -apple-system, BlinkMacSystemFont, Helvetica, Arial, sans-serif;
}

h2,
h3,
h4,
h5,
h6 {
    font-family: var(--md-header-font-family);
    font-feature-settings: "kern", "liga";
    color: var(--md-typeset-color);
}

.md-typeset h2,h3,h4,h5,h6 {
    color: var(--md-primary-fg-color);
}

.md-typeset h5 {
    color: var(--md-primary-fg-color);
}

.md-typeset h2 {
    font-weight: bold;
}
```

The theme uses these `--md-{text,code}-font-family` CSS variables to set defaults if the `--md-{text,code}-font` fonts are not available in the deployed site, so we do the same in the `body` selector for the header variable. We then modify the `h2,h3,h4,h5,h6` styles to select the `font-family` from the `--md-header-font-family` variable that was defined.

I also added some additional coloring to the headers, but this is optional.

Apply the configuration in `mkdocs.yml`
---------------------------------------

And voila, we can specify the header font in the theme configuration:

```yaml
theme:
  font:
    header: Press Start 2P
```

You can see the result in my site here:

![Screenshot 2024-12-23 at 3 09 26 PM](https://github.com/user-attachments/assets/63964ac8-407a-41fc-be02-96f5a764db3a)
