### DISCUSSION TITLE
What to put in for custom cookie

### DISCUSSION THREAD

**Discussion by ydkmlt84** [squidfunk/mkdocs-material#7846] [Q&A] [answered]
I have searched and just can't seem to find it. What do I put in for the custom cookie? I am not using Google analytics, using Matomo, and don't really understand what to put in mkdocs.yml

```
analytics:
    provider: matomo
    property: docs
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
      - manage
    cookies:
      analytics: matomo
      custom: WHAT GOES HERE, FOR ME?
```
      
Do I put the name of the cookie that my analytics provider uses? 
      
Do I put the names from the table in this documentation? https://matomo.org/faq/general/faq_146/#:~:text=with%20privacy%20requirements.-,Default%20Cookies,-To%20track%20users
      
If so...do I use one `custom:entry` per cookie, or can I list them like this:

```
custom:
  - one_cookie
  - two_cookie
  - three_cookie
```      
      
Thanks in advance for the help! Right now, my cookies aren't being removed when the consent is rejected, and I am assuming this is why.

**Comment by squidfunk** [comment, marked as answer]
It's basically just an identifier, specifically `custom` that you can query in JavaScript to do whatever you want with it, as mentioned. For instance, you can call it `banana`:

``` yaml
analytics:
    ...
    cookies:
      banana: some_value
```

And then:

``` js
var consent = __md_get("__consent")
if (consent && consent.banana) {
   consent.banana // will contain "some_value"
} else {
   // No cookie for you
}
```
