### DISCUSSION TITLE
[blog plugin] Sorting posts in the Archive section by years and months

### DISCUSSION THREAD

**Discussion by alina-derkach-oaza** [squidfunk/mkdocs-material#7884] [Q&A] [answered]
Hi Community,

Is it possible to configure the Archive section so that the posts are organized by year and month, with each year in its own folder, each year containing subfolders for the months, and each month folder containing the individual posts?

<img width="284" alt="Screenshot 2025-01-08 at 17 34 02" src="https://github.com/user-attachments/assets/105d9be7-1abb-41d7-892f-bb7760961b98" />

**Comment by niclasheinz** [comment]
Hi @alina-derkach-oaza 

I don't think this is possible at the moment, but I can offer you a workaround (I know it's not perfect):
![grafik](https://github.com/user-attachments/assets/bd4b6046-7f74-4ba0-a669-005cc8f5436d)


Here is the config for that:
```
  - blog:
      post_url_format: "{date}/{slug}"
      post_url_date_format: "yyyy/MM"
      archive_url_format: "archive/{date}"
      archive_url_date_format: "yyyy/MM"
      archive_toc: true 
      archive: true  
      archive_name: "Archive"
      archive_date_format: "yyyy/MM" 
```

Unfortunately I could not find out how to use a collapsible archive navigation, Sorry
