### DISCUSSION TITLE
404 page replacement - where am I going wrong

### DISCUSSION THREAD

**Discussion by antnorwe** [squidfunk/mkdocs-material#7888] [Q&A] [answered]
I'm 100% certain this is a PEBKAC error, however I'm also fairly certain I've followed the existing documentation appropriately so I'm looking for a clearer headed person to ride in and validate my imposter syndrome.

[I've referred to this discussion](https://github.com/squidfunk/mkdocs-material/discussions/5018) and the links within, and from what I can see my own setup is the same (apart from the declaration of static_templates in my mkdocs.yml file - maybe this is it?)

Appropriate section of mkdocs.yml

``` yaml
site_name: Fantasy Football - TEST SITE
theme:
  name: material
  logo: assets/american-football.png
  favicon: assets/american-football.png
  palette:
    scheme: slate
  custom-dir: overrides
```

404 page definition:
``` html
{% extends "main.html" %}

{% block content %}
<h1>
    Oops - you shouldn't be here
</h1>
<img src="[blob container]/404.jpg", alt="">

{% endblock %} 
```

Folder structure:

- mkdocs.yml
- docs/
- overrides/
-- 404.html
