### DISCUSSION TITLE
How do I use icons from the simpleicons collection for tags?

### DISCUSSION THREAD

**Discussion by CardboardTurkey** [squidfunk/mkdocs-material#7891] [Q&A] [answered]
I thought, for example, something like

```yaml
theme:
  icon:
    tag:
      ps2: simpleicons/playstation2
```

would work but mkdocs complains

```
jinja2.exceptions.TemplateNotFound: .icons/simpleicons/playstation2.svg
```
