### DISCUSSION TITLE
Running mkdocs-materials with docker/portainer

### DISCUSSION THREAD

**Discussion by ndeschamps-isto** [squidfunk/mkdocs-material#7899] [Q&A] [answered]
Hi all,

I want to create an MkDocs site for my team to write and access documentation. It’s supposed to be simple, but I’ve spent hours on it and just lost track. I would really appreciate some help!

I’ve been using Linux/Docker for a few months, but I’m still a beginner.

My plan is to use [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/getting-started/) to create my website and host it in a Docker container. I already have a VM (Debian) with Docker and Portainer, along with a few apps running. I also have a domain name and Traefik as a proxy. I want the website content to be easily editable via  [GitLab CNRS](https://src.koda.cnrs.fr/) from our institute.

Ideally, I want to run MkDocs in my Docker container with the Portainer interface and access it on the internet under my domain name.

My idea was to bind the Docker volume to my host machine, and then have a .sh routine to update the content from the repository. Is this a good solution?

For now, I’ve created a basic MkDocs structure (/home/ndeschamps/apps/mkdocs) with mkdocs.yml and docs/index.md. I also wrote the following Docker Compose file for my stack in Portainer:

```
services:
  mkdocs:
    image: squidfunk/mkdocs-material
    container_name: mkdocs_container_test
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.wiki-secure.entrypoints=websecure
      - traefik.http.routers.wiki-secure.rule=Host(docs.${_DOMAIN_NAME})
    networks:
      - frontend
      - backend
    volumes:
      - /home/ndeschamps/apps/mkdocs:/mkdocs
    restart: always

volumes:
  data:
    external:
      name: /home/ndeschamps/apps/mkdocs

networks:
  frontend:
    external: true
  backend:
    external: true
 ```
My container is running, but it cannot find my mkdocs.yml. I’m also not sure if it will be easy to update the volume content from the repository afterward...

Is there a better solution?

Can someone guide me?

I’ve spent a day searching for solutions but haven’t a solution.

thank you!
