### DISCUSSION TITLE
Example of nested content tabs?

### DISCUSSION THREAD

**Discussion by AndydeCleyre** [squidfunk/mkdocs-material#7906] [Q&A] [answered]
I'm using:

```yml
markdown_extensions:
  - footnotes
  - pymdownx.superfences
  - pymdownx.blocks.admonition
  - pymdownx.blocks.tab:
      alternate_style: True
```

And am trying to figure out the proper syntax for nested tab content. 

Can anyone provide an example of this?

Here's my closest attempt thus far:

```md
/// tab | parent of three

  /// tab | first child

  content of first child

  ///

  /// tab | second child
      new: false

  content of second child

  ///

  /// tab | third child
      new: false

  content of third child

  ///

///

/// tab | aunt

content of aunt

///

/// tab | uncle

content of uncle

///
```

The result is that the children are indeed nested under the parent, but they are not siblings (part of the same group):

![image](https://github.com/user-attachments/assets/ffd1bc88-2a90-4733-9072-9f0a9c4c3b81)

I also tried indenting the children two more spaces, but that made them a code block.

Over at [the this content tabs reference](https://github.com/squidfunk/mkdocs-material/blob/master/docs/reference/content-tabs.md) it's mentioned that:

> When SuperFences is enabled, content tabs can contain arbitrary nested content, including further content tabs

Any help would be greatly appreciated, thanks! I think the tab docs could do with an example of this.
