### DISCUSSION TITLE
Error but still works?

### DISCUSSION THREAD

**Discussion by guitarguy1685** [squidfunk/mkdocs-material#7949] [Q&A] [answered]
I'm trying to incorporate icons and emojis into my site.  I followed the instructions [here ](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/?h=icons#configuration). The weird thing is that in vscode I'm shown a squiggly underline on this snippet and my document is highlighted red. I assume this tells me there is something wrong in the yml file. However the site still works, even when I build it for offline access.  Is there something obvious wong here that I'm not noticing?  Like it said, it still works, but those warnings are making ane anxious.

![image](https://github.com/user-attachments/assets/d57f476d-8d98-4165-8216-49e103c2db5a)

yml text blow
```yml
site_name: Novum Structures - Technical Services
site_description: Tech Services Handbook
site_url: ""
site_dir: docs-offline
use_directory_urls: false

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  features:
    - content.tabs.link
    - content.tooltips
    #- navigation.instant
    #- navigation.instant.prefetch
    #- navigation.instant.progress
    #- navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

plugins:
  - search
  - offline

markdown_extensions:
  - admonition
  #- pymdownx.details
  #- pymdownx.superfences
  - attr_list
  #- md_in_html
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - toc:
      permalink: true
      title: On this page
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      
extra_css:
  - stylesheets/extra.css

nav:
  - Home:
    - index.md
    - Terms: terms.md
    - Standard Parts: nsp.md

  - CAD:
    - cad/index.md
    - cad/cui.md
    - AutoLISPs:
      - cad/lisp/index.md
    - Tool Palettes:
      - cad/toolpalette/index.md
    - Pen Settings: cad/pens.md

  - Advance Steel: 
    - advs/index.md
    - advs/setup.md
    - DXF Files: advs/dxf.md

  - Fabrication:
    - fab/index.md
    - Bill of Materials: fab/bom.md
    - BoM Tab: fab/tabbom.md
```
