### DISCUSSION TITLE
Changing color schemes in extra css doesn't seem to work

### DISCUSSION THREAD

**Discussion by DeNelo** [squidfunk/mkdocs-material#7970] [Q&A] [answered]
Following the instructions in the [Setup guide](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors-mkdocsyml), I've added an extra stylesheet (which I can verify is loaded) with 
~~~
:root {
  --md-primary-fg-color:        #EE0F0F;
  --md-primary-fg-color--light: #ECB7B7;
  --md-primary-fg-color--dark:  #90030C;
}
~~~
-but it does not take effect. Is the extra.css really loaded last?

**Comment by squidfunk** [comment, marked as answer]
There's indeed an error in the docs. It must be:

``` css
:root  > * {
  --md-primary-fg-color:        #EE0F0F;
  --md-primary-fg-color--light: #ECB7B7;
  --md-primary-fg-color--dark:  #90030C;
}
```

Care to send a PR?
