### DISCUSSION TITLE
Favicon Redirets to root folder on offline site

### DISCUSSION THREAD

**Discussion by guitarguy1685** [squidfunk/mkdocs-material#7986] [Q&A]
1st off, this mkdocs-materials is amazing, thanks so much for all of this.
So far everything is working perfectly, but I noticed that when I click on the logo, instead of taking me to the home page it takes me to the root folder. This only happens when viewing the offline HTML. 
![image](https://github.com/user-attachments/assets/21bd9bea-cba9-4ef8-81c8-ee59fcf2777c)

![image](https://github.com/user-attachments/assets/3f0729c2-de81-4892-ab5a-b8be8b51d323)

I plan to save this on my company server, so this is how it will function there as well. I want the icon to take me to the home page. When viewing this on Netlify it works just fine, not sure why the offline version takes me to the root.

**Comment by niclasheinz** [comment]
Hi @guitarguy1685 

In order to help you better, we need more information about your setup. Could you provide us with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/?h=minimal#minimal-reproduction)?

PS: Material for MkDocs only lives because @squidfunk has wonderful sponsors. If you use Material for MkDocs in a company, please consider [sponsoring](https://github.com/sponsors/squidfunk) @squidfunk. That way he can continue to maintain the project and develop great stuff. He is currently working on [fundamental work](https://squidfunk.github.io/mkdocs-material/blog/2024/08/19/how-were-transforming-material-for-mkdocs/).

**Reply by guitarguy1685** [reply]
I absolutely will!

**Reply by guitarguy1685** [reply]
```
site_name: Handbook
site_description: Handbook
site_url: ""
site_dir: docs-offline
use_directory_urls: false

theme:
  name: material
  custom_dir: material/overrides  
  logo: assets/darkbg.png
  favicon: assets/light.png
  font:
    text: Source Sans Pro
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - content.tabs.link
    - content.tooltips
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - navigation.tracking
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

plugins:
  - blog:
      blog_dir: blog/directive
  - glightbox:
       loop: true
       manual: true
       touchNavigation: true
       zoomable: true
  - offline
  - search
      
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
        auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - md_in_html
  - toc:
      permalink: true
      title: On this page

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
```
