### DISCUSSION TITLE
Share option for blogs plugin

### DISCUSSION THREAD

**Discussion by Andre601** [squidfunk/mkdocs-material#7997] [Ideas]
One feature you can often find in blogs is share buttons that allow you to share the article on social media.

Such an option for the blog plugin would be of great use, as it would allow readers to more easily share a blog post on social media with the least amount of steps required (depending on the social media platform).

## Configuration example

```yaml
plugins:
  - blog:
      # Other settings here
      share:
        - icon: 'simple/x'
          title: 'Tweet on X!' # Defaults to "Share post"
          link: 'https://x.com/?url={url}&text={title}' # Placeholders explained below
          class: 'md-button__social--x' # Adds the provided classes to `.md-button`
        - icon: 'simple/mastodon'
          title: 'Toot on Mastodon!'
          link: 'https://mastodonshare.com?url={url}&text={title}'
          class: 'md-button__social--mastodon'
```

**Placeholders:**
(Placeholder values used in `link` would be URL Encoded)

- `{url}` - Returns the URL to the blog post.
- `{title}` - Returns the title of the Blog post (prioritizing `page.meta.title` if set).
- `{description}` - Returns `page.meta.description` or post excerpt.
- `{author_<value>}` - Returns a matching `<value>` from the post author in the `.authors.yml`. In case of multiple authors would the first one be used (except `{author_name}` where a comma-separated list could be returned?)
- `{tags}` - Returns comma-separated list of tags for the post.
- `{categories}` Returns comma-separated list of categories for the post.

## Result

The result would be buttons added to the bottom of the blog post, or at the bottom of the author sidebar with the `icon` displayed.

As an example, assume the post URL is `https://blog.example.com/2025/01-01-lorem-ipsum` and title is `Lorem Ipsum`.
With the above shown configuration would the following HTML be generated and used:

```html
<a href="https://x.com/?url=https://blog.example.com/2025/01-01-lorem-ipsum&text=Lorem%20Ipsum" class="md-button md-button__social--x" title="Tweet on X!"><!-- SVG of the X Icon from Simple Icons --></a>
<a href="https://mastodonshare/?url=https://blog.example.com/2025/01-01-lorem-ipsum&text=Lorem%20Ipsum" class="md-button md-button__social--mastodon" title="Toot on Mastodon!"><!-- SVG of the Mastodon Icon from Simple Icons --></a>
```

## Current alternatives

Extending the theme and manually adding those options, requiring extra maintenance for the user should the post template change. Also, the effective URL may not even be available nor may there be options to properly URL encode content.
