### DISCUSSION TITLE
Search bar not listing

### DISCUSSION THREAD

**Discussion by busanaboina** [squidfunk/mkdocs-material#8014] [Q&A]
### Description

I have setup the mkdocs project by following the steps explained here: https://www.mkdocs.org/user-guide/
I am able to build the basic docuementation with three input source files(.md). the html output with all the pages and links were existing but the only problem i have is that the search bar doesnt shows up any recomendations!
can you please guide me to make it work!
I am attaching the whole template workspace for reference. 

[mkdocs.zip](https://github.com/user-attachments/files/18845141/mkdocs.zip)

### Related links

- [Reporting a docs issue](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/)
-

### Before submitting

- [x] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [x] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Thanks for reporting. I'm converting this to a discussion.

**Comment by kamilkrzyskow** [comment]
Hello @busanaboina,
if you followed the instructions on https://www.mkdocs.org/user-guide/ then you should be aware that's the page of MkDocs and all issues with their docs should be targeted at their repository:
- https://github.com/mkdocs/mkdocs
- https://github.com/mkdocs/mkdocs/discussions

However, looking at your `mkdocs.yml` file it seems like you're mixing up 2 documentations.
```yaml
theme:
  name: mkdocs  # This is incorrect
  language: en
  features:  # Features are available when using the 'material' theme
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
```

For any `features` available in the docs for this repository:
- https://squidfunk.github.io/mkdocs-material/
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/

You need to enable the `material` theme following the setup guide:
- https://squidfunk.github.io/mkdocs-material/getting-started/
- https://squidfunk.github.io/mkdocs-material/creating-your-site/

The default `mkdocs` theme doesn't come with a search bar at the top and doesn't provide any options to enable it:
- https://www.mkdocs.org/user-guide/choosing-your-theme/#mkdocs
