### DISCUSSION TITLE
search and repo star not show.

### DISCUSSION THREAD

**Discussion by Light-City** [squidfunk/mkdocs-material#8069] [Q&A] [answered]
### Context

When I use mkdocs, version 1.6.1 , I got search and git repo star not show.

### Bug description

why my search and git repo star not show?

mkdocs.yml

```
# Repository
repo_name: Light-City/CPlusPlusThings
repo_url: https://github.com/Light-City/CPlusPlusThings

plugins:
  - material/search:
      enabled: true
```

dir tree is

```
├── config
│   └── zh
│       └── mkdocs.yml
├── docs
│   ├── zh
── overrides
    ├── main.html
    └── partials
        ├── comments.html
        ├── copyright.html
        ├── header.html
        └── search.html
```

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

website: https://light-city.github.io/stories_things/

mkdocs.yml

```
# Repository
repo_name: Light-City/CPlusPlusThings
repo_url: https://github.com/Light-City/CPlusPlusThings

plugins:
  - material/search:
      enabled: true
```

dir tree is

```
├── config
│   └── zh
│       └── mkdocs.yml
├── docs
│   ├── zh
── overrides
    ├── main.html
    └── partials
        ├── comments.html
        ├── copyright.html
        ├── header.html
        └── search.html
```

### Steps to reproduce

just use master version.

### Browser

Chrome

### Before submitting

- [x] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [x] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [x] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [x] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).
