### DISCUSSION TITLE
Running Mermaid support locally

### DISCUSSION THREAD

**Discussion by klausbussekw** [squidfunk/mkdocs-material#8101] [Q&A] [answered]
I have installed the package with ` brew install mkdocs-material` and now try to get Mermaid support up and running.

According to https://squidfunk.github.io/mkdocs-material/reference/diagrams/ this should be the whole setup in my yaml file:

```yaml
site_name: MySite
site_description:
plugins:
  - search
nav:
  - Home: index.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
```
          
While `mkdocs serve` works nicely, all Mermaid code is still just rendered as source.

What am I missing here?
