### DISCUSSION TITLE
Collapse Headers?

### DISCUSSION THREAD

**Discussion by MartinGonzalez** [squidfunk/mkdocs-material#8103] [Q&A] [answered]
Hi there!
I'm trying to create sections something like this picture:

<img width="312" alt="image" src="https://github.com/user-attachments/assets/9746277a-68ec-45ef-8f65-a6879ccde0a2" />

But I would like to collapse or create a division between features. Is it possible to do it?

To have something like this:

<img width="296" alt="image" src="https://github.com/user-attachments/assets/a9ee3c75-8460-4b83-9847-27428bb37001" />

**Comment by MartinGonzalez** [comment]
I just noticed that if I narrow the screen I get this

<img width="319" alt="image" src="https://github.com/user-attachments/assets/ad539563-ffe9-4490-b7ed-91f30360f080" />

This is exactly what I want, but while the sidebar is on all the time.
Also, I would like to expand in the same sidebar instead of moving me to a new one.

**Comment by mocdaniel** [comment]
Not sure if I understood you correctly, but I _think_ this is what you want?

![image](https://github.com/user-attachments/assets/d42fdaa7-5267-42fe-b56e-4bb2886f0b18)


If so, within `mkdocs.yml`, configure the `nav` listing like this and make sure to add the [`navigation.sections`](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-sections) feature.

```yaml
nav:
  - Home: index.md
  - AB Testing:
      - Overview: ab/index.md
      - Unity:
          - ab/unity/page-a.md
          - ab/unity/page-b.md
      - API:
          - ab/api/page-a.md
          - ab/api/page-b.md
  - Remote Configuration:
      - Overview: rc/index.md
      - Unity:
          - rc/unity/page-a.md
          - rc/unity/page-b.md
      - API:
          - rc/api/page-a.md
          - rc/api/page-b.md
  - Purchasing:
      - Overview: buy/index.md
      - Unity:
          - buy/unity/page-a.md
          - buy/unity/page-b.md
      - API:
          - buy/api/page-a.md
          - buy/api/page-b.md
  - Schedule Features:
      - Overview: feats/index.md
      - Unity:
          - feats/unity/page-a.md
          - feats/unity/page-b.md
      - API:
          - feats/api/page-a.md
          - feats/api/page-b.md
```

This will result in the navigation shown in the screenshot above.

If the exact _opposite_ is the case and you actually want to collapse every section completely and this isn't the case right now (it's the default behavior of mkdocs-material), make sure that the `navigation.sections` feature is **not** enabled, as then all sections should collapse completely.

**Reply by MartinGonzalez** [reply]
Thanks for the answer!
That is what I currently have, what I'm looking for is to have the headers like `AB Testing` or `Purchasing` totally collpased so I dont see Overview, unity or API. 

Something like this, but this only happens when the website is narrow
![image](https://github.com/user-attachments/assets/ef2004bf-30eb-49ed-a695-3fd861dcfdb3)

**Reply by mocdaniel** [reply]
Would you mind sharing your current `mkdocs.yaml`? Maybe this helps in identifying your problem, because, as I mentioned, what you describe should be the default behavior of top-level navigation elements.

**Reply by Martin-Gonzalez90** [reply]
Sure, I have this right now

```yml
site_name: PlayOps Documentation
theme:
  name: material
  features:
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand: false
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
  plugins:
    - search
    - toc
    - group
    - nav-ids
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-2
        name: Switch to light mode
extra_css:
    - stylesheets/custom.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - AB Testing: 
    - Overview: ab-testing/overview.md
    - Unity: 
      - Installation: ab-testing/unity/installation.md
      - Getting an AB Test: ab-testing/unity/getting-test.md
    - API: 
      - Get Active AB Tests: ab-testing/api/active-tests.md
  - Remote Configuration:
    - Overview: remote-config/overview.md
    - Unity:
      - Installation: remote-config/unity/installation.md
    - API:
      - Get Configuration: remote-config/api/get-configuration.md
  - Purchasing:
    - Overview: purchasing/overview.md
    - Unity:
      - Installation: purchasing/unity/installation.md
    - API:
      - Get Purchases: purchasing/api/get-purchases.md
  - Schedule Features:
    - Overview: schedule-features/overview.md
    - Unity:
      - Installation: schedule-features/unity/installation.md
    - API:
      - Get Schedules: schedule-features/api/get-schedules.md
  - Notifications:
    - Overview: notifications/overview.md
    - Unity:
      - Installation: notifications/unity/installation.md
    - API:
      - Get Notifications: notifications/api/get-notifications.md
```

**Reply by mocdaniel** [reply]
Remove `navigation.sections` from the feature's list, that should do the trick.

**Reply by MartinGonzalez** [reply]
That did the trick indeed, I guess could be fine for a first iteration

![image](https://github.com/user-attachments/assets/02e76dba-fb3b-45c7-8372-65051faa9d88)

But do you know if there is a way of creating those separations like in the picture below?

![image](https://github.com/user-attachments/assets/c0d055ea-e6a3-45e4-b987-03368820e9cb)

**Reply by mocdaniel** [reply, marked as answer]
Yup - you can use [custom additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css).

Put the following in a file `docs/stylesheets/extra.css` (or extend the file at `docs/stylesheets/custom.css` you already seem to have, according to the config you shared):

```css
nav[data-md-level="0"] > .md-nav__list > .md-nav__item {
  border-bottom: 1px solid;
  border-color: #36383F; /* picked the color from your screenshot */
  padding-bottom: 4px;
}
```

Then reference the file in your `mkdocs.yml`:

```yaml
extra_css:
  - stylesheets/extra.css
```
## Desktop
![image](https://github.com/user-attachments/assets/a9df14ae-2f03-4403-86e8-248e8cf63842)
## Mobile
![image](https://github.com/user-attachments/assets/b67d2a74-cc20-46da-9409-a889bc4e807f)

Regarding the last part of the questions (how not to descend into the subsection menu on mobile devices) - this goes deeper into the inner workings of the `nav` partial and possibly also Javascript, so it's out of scope for this thread imo - maybe you should open a separate discussion for that.
