### DISCUSSION TITLE
Change Annotation Color?

### DISCUSSION THREAD

**Discussion by YozoraXCII** [squidfunk/mkdocs-material#8125] [Q&A]
Trying to find the correct CSS to change the color of the annotation button, let's say to aqua:

This is my current markdown:
```
<div class="annotate" markdown>

Hello world (1)

</div>

1.  :man_raising_hand: Hi!
```

**Comment by kamilkrzyskow** [comment]
Hello @YozoraXCII,
to change the color globally you'd use this CSS:
```css
.md-annotation__index::after {
  background-color: #fff;
}
```

You can also target an annotation based on the parent class, similar to the example from the other discussion:
- https://github.com/squidfunk/mkdocs-material/discussions/8146
```css
.solid-one .md-annotation__index::after {
  background-color: #fff;
}
```

Reference:
- https://squidfunk.github.io/mkdocs-material/customization/#additional-css
