### DISCUSSION TITLE
How do I implement numeric table sorting?

### DISCUSSION THREAD

**Discussion by elliot-100** [squidfunk/mkdocs-material#8151] [Q&A]
Hi, I got string sorting working fine by following the [docs](https://squidfunk.github.io/mkdocs-material/reference/data-tables/#usage), but I can't work out how to get numeric sort working. 

I've added the extra `tablesort` component to `mkdocs.yml`:
```yaml
site_name: My site
theme:
  name: material
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.number.js
  - javascripts/tablesort.js
```
And I have a very simple table:
```md
| Number | Description |
|--------|-------------|
| 1      | C           |
| 10     | B           |
| 2      | A           |
```
My understanding is that this should be sufficient to enable numeric sorting on Column 1, but it uses string sorting 1,10,2 / 2,10,1.

I then read [How to specify the sort method for a column in a sortable table](https://github.com/squidfunk/mkdocs-material/discussions/3577), took the suggestion to use HTML instead of Markdown in order to add the custom attribute, copied the generated HTML and added an explicit sort method on Column 1:

```html
<table>
<thead>
<tr>
<th data-sort-method='number'>Number</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr>
<td>1</td>
<td>C</td>
</tr>
<tr>
<td>10</td>
<td>B</td>
</tr>
<tr>
<td>2</td>
<td>A</td>
</tr>
</tbody>
</table>
```
But this behaves the same way. I can see `tablesort.number.js` is linked in the generated HTML, but I don't know Javascript, so am unsure how to troubleshoot further.

```html
...
<script src="[assets/javascripts/bundle.c8b220af.min.js](http://127.0.0.1:8000/assets/javascripts/bundle.c8b220af.min.js)"></script>
      
        <script src="https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js"></script>
      
        <script src="https://unpkg.com/tablesort@5.3.0/dist/tablesort.number.js"></script>
      
        <script src="[javascripts/tablesort.js](http://127.0.0.1:8000/javascripts/tablesort.js)"></script>
...
```
