### DISCUSSION TITLE
Making tooltips longer?

### DISCUSSION THREAD

**Discussion by paulmmoloney** [squidfunk/mkdocs-material#8152] [Q&A] [answered]
I'm using the improved Tooltip implementation with the following in my extra.css, and entries in an abbreviation file.

[role=tooltip]>.md-tooltip2__inner {
    font-size: 0.7rem;
	color: blue;
	font-weight: normal;
}

Is there a way to make the maximum length of the tooltip longer? Some of my glossary entries are quite length and run out of the tooltip space.

P.

**Comment by kamilkrzyskow** [comment, marked as answer]
Hello @paulmmoloney,
you can add `max-width: <value>` and `max-height` to your CSS selector above to increase the allowed width and height of the tooltip container.

```css
[role=tooltip] > .md-tooltip2__inner {
  font-size: 0.7rem;
  color: blue;
  font-weight: normal;
  max-width: 50vw;
  max-height: 100vw;
}
```

Tough if the content is too long it might still go out of the users view port, and tooltips aren't designed for scrollable content.
In that case consider switching to [footnotes](https://squidfunk.github.io/mkdocs-material/reference/footnotes/) or [annotations](https://squidfunk.github.io/mkdocs-material/reference/annotations/) for providing additional info.
