### DISCUSSION TITLE
How can I enable wikilinks?

### DISCUSSION THREAD

**Discussion by Xenoprimate** [squidfunk/mkdocs-material#8159] [Q&A] [answered]
I've tried to "pip install mkdocs-wikilinks-plugin" and add `- wikilinks` under my `plugins:` header, but whenever I run `mkdocs serve` I get "Config value 'plugins': The "wikilinks" plugin is not installed".

Please note I'm not a python dev and I'm running on Windows so may be some sort of python environment issue?

**Comment by mocdaniel** [comment]
Would you mind sharing the following three outputs with us? That should shed some light on your local environment and what might be wrong:

- output of `pip list`
- output of `ls -la .` if you are using WSL or `ls -Force .` if you are using Powershell, from within your mkdocs directory
- your `mkdocs.yml`

> [!WARNING]
> Make sure to redact sensitive information in your `mkdocs.yml` before sharing

**Reply by Xenoprimate** [reply]
Of course; here's the output:

`pip list`:

```
Package                    Version
-------------------------- -----------
babel                      2.17.0
backrefs                   5.8
certifi                    2025.1.31
charset-normalizer         3.4.1
click                      8.1.8
colorama                   0.4.6
ghp-import                 2.1.0
idna                       3.10
importlib_metadata         8.6.1
importlib_resources        6.5.2
Jinja2                     3.1.6
Markdown                   3.7
MarkupSafe                 3.0.2
mergedeep                  1.3.4
mike                       2.1.3
mkdocs                     1.6.1
mkdocs-get-deps            0.2.0
mkdocs-material            9.6.9
mkdocs-material-extensions 1.3.1
mkdocs-wikilinks-plugin    0.1.0
packaging                  24.2
paginate                   0.5.7
pathspec                   0.12.1
pip                        24.3.1
platformdirs               4.3.7
Pygments                   2.19.1
pygtrie                    2.5.0
pymdown-extensions         10.14.3
pyparsing                  3.2.2
python-dateutil            2.9.0.post0
PyYAML                     6.0.2
pyyaml_env_tag             0.1
requests                   2.32.3
six                        1.17.0
urllib3                    2.3.0
verspec                    0.1.0
watchdog                   6.0.0
zipp                       3.21.0
```

`ls -Force .`:

```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        27/03/2025     16:57                includes
d-----        28/03/2025     13:21                output
d-----        30/03/2025     14:55                source
d-----        27/03/2025     16:21                theme_overrides
-a----        03/04/2025     18:33           4666 documentation_instructions.txt
-a----        11/04/2025     21:04           3257 mkdocs.yml
```

`mkdocs.yml`:

```
docs_dir: source
site_name: redacted
site_url: redacted
site_dir: output
repo_url: redacted
edit_uri: Documentation/source/
site_description: "redacted"
site_author: "redacted"
copyright: "redacted"
extra_css:
  - stylesheets/additional_styles.css
watch:
  - includes
  - theme_overrides

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.betterem
  - pymdownx.blocks.caption
  - pymdownx.caret:
      smart_insert: false
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.superfences 
  - pymdownx.snippets:
      auto_append:
        - includes/acronym_definitions.md
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: 🔗
      title: Page Contents
      toc_depth: 3

extra:
  social:
    - icon: fontawesome/brands/github
      link: redacted
      name: Repository
    - icon: fontawesome/solid/comments
      link: redacted
      name: Discussions

theme:
  name: material
  logo: logo_128.png
  favicon: logo_128.png
  custom_dir: theme_overrides
  icon:
    annotation: material/message-question
  features:
    - navigation.instant
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tooltips
    - content.code.annotate
    - content.code.copy


  font:
    code: Source Code Pro

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

plugins:
  - search
  - meta
  - wikilinks

validation:
  omitted_files: warn
  absolute_links: relative_to_docs
  unrecognized_links: warn
  anchors: warn
strict: true

nav:
  - redacted
```
