### DISCUSSION TITLE
TOC.Integrate not working for small project? See code and sample doc

### DISCUSSION THREAD

**Discussion by Vibemetheus** [squidfunk/mkdocs-material#8177] [Q&A] [answered]
I've tried really pairing back my configuration to test this and nothing seems to work to integrate the TOC into the nav.

```
site_name: name
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    scheme: slate
    primary: blue grey
    features:
    - toc.integrate
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.footer
    # - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
 
  font:
    text: Roboto
    code: Roboto Mono
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      url_download: true
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde



nav:
  - Home: index.md
  - Getting started:
    - Installation: installation.md
    - Getting Started: getting-started.md
```

sample documentation:
```
# Getting Started

## Installation

See [installation guide](installation.md).

---

## Startup

add content here

add content here

### Creating your first channel

add content here
```

When I run this project, no errors occur, but the integration of the table of contents doesn't show up. It still shows up on the right side of the page and no integration with the navigation on the left. I've tried a lot of different configs but nothing changes.
![image](https://github.com/user-attachments/assets/9152b510-1d09-438f-922b-1e0af872a7aa)

**Comment by mocdaniel** [comment, marked as answer]
The formatting of your `mkdocs.yml` isn't correct - the `features` key needs to go under `theme`, not under `palette` in the config file, like this:

```yaml
site_name: My MkDocs Site
site_url: https://example.com
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
```

I'll shamelessly plug my free, open-source tool [materialconfig.dev](https://materialconfig.dev) here that allows you to generate a valid `mkdocs.yml` file in a visual way through an easy-to-use UI. It will also notify you of incompatible settings - e.g. `navigation.expand` can't be used together with `navigation.prune` as you are trying to do in the config you shared.
