### DISCUSSION TITLE
Help with enabling and running search on mkdocs with 100,000 pages

### DISCUSSION THREAD

**Discussion by lshalon** [squidfunk/mkdocs-material#8181] [Q&A]
Right now, when I enable search on mkdocs, it tries to initialize the search live on the website and ends up crashing the page. I'd like to have the bare minimum - ideally something as simple as string search. Is there a better way to configure the search functionality?

When running, the memory object that continuously increases in size until things crash is: `search.f8cc74c7.min.js`

```
site_name: Knowledge
docs_dir: output          # where your Markdown lives
site_dir: site            # build target

theme:
  name: material
  language: en
 
  # Obsidian-like typefaces
  font:
    # macOS, iOS, Windows, Linux & fallback Helvetica
    text: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif"

    # Monospace stack that starts with SF Mono on macOS, Menlo otherwise
    code: "SFMono-Regular, Menlo, Consolas, 'Liberation Mono', monospace"

  # Instant navigation + Obsidian-style search UX
  features:
    - navigation.instant   # fetch pages by XHR, no full reload
    - navigation.top       # keep sidebar header visible
    - search.highlight     # highlight matches in page   :contentReference[oaicite:0]{index=0}
    - search.suggest       # type-ahead suggestions
    - header.autohide      # hide top bar on scroll      :contentReference[oaicite:1]{index=1}

plugins:
  - search:
      indexing: sections      # or titles
      prebuild_index: true    # build once, ship ready-made JSON
      worker: true            # search runs in Web-Worker (no UI jank)
  - redirects:
      redirect_maps:
        index.md: organization/home.md     # <── root → /organization/

nav:
  - Organizations:
      - Home: organization/home.md
  - People:
      - Home: person/home.md
  - Domain Groups:
      - Home: domain_groups/home.md

# Extra styling – make sure the path exists inside docs_dir
extra_css:
  - css/obsidian.css

extra_javascript:
  - js/org-header.js
  # - js/external-links.js

use_directory_urls: false

validation:
  absolute_links: ignore       # or 'error' with mkdocs build --strict
```
