### DISCUSSION TITLE
Only show image when user is/isn't on mobile

### DISCUSSION THREAD

**Discussion by MegAmi24** [squidfunk/mkdocs-material#8218] [Q&A] [answered]
I want to make it so that an image only appears (or more specifically, the image that is shown changes) when the page is or isn't viewed on mobile, similar to how [you can make it so one only appears in light/dark mode](https://squidfunk.github.io/mkdocs-material/reference/images/#light-and-dark-mode). How can I achieve this?

**Comment by kamilkrzyskow** [comment, marked as answer]
Hello @MegAmi24,
you'd use extra CSS with a media query.

https://github.com/squidfunk/mkdocs-material/blob/2e9bd81018958357a3f96457a7251e3d42866c81/src/overrides/home.html#L54-L59

To hide on mobile, the limiter `max-width: 45em` should probably be fine.
Then add a CSS class to your image with `attr_list` like `.hide-on-mobile`
And combine this selector with the media query
```css
.hide-on-mobile {
  display: none;
}
```

References:
- https://squidfunk.github.io/mkdocs-material/customization/#additional-css
- https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#attribute-lists
- https://developer.mozilla.org/en-US/docs/Web/CSS/@media

**Reply by MegAmi24** [reply]
Thank you for this! For reference, this is what I've added to my CSS file:
```css
/* Hide .desktop-only content if on mobile */
@media only screen and (max-width: 600px) { 
    .desktop-only { 
        display: none; 
    } 
}

/* Hide .mobile-only content if not on mobile */
@media only screen and (min-width: 601px) { 
    .mobile-only { 
        display: none; 
    } 
}
```

The only issue I have with this is that the `.desktop-only` images will appear when my phone is in landscape mode. I did try tinkering around to fix that, but ultimately I decided it wasn't that big enough of a problem for my purposes.
