### DISCUSSION TITLE
Does GH Pages not render custom icons?

### DISCUSSION THREAD

**Discussion by 5jt** [squidfunk/mkdocs-material#8220] [Q&A] [answered]
I’m converting the documentation of GitHub repo [Tatin](https://github.com/aplteam/tatin) to Material for MkDocs. The conversion is in my [fork](https://github.com/5jt/tatin), going well, and visible at <https://5jt.github.io/Tatin>. 

The home page includes **two custom icons**, for which the source is in `docs/overrides/.icons/dyalog`. The icons are rendered correctly on my local machine in Live Preview and also in `docs/site/index.html`. 

![live-preview](https://github.com/user-attachments/assets/9ce7450c-7f90-47dc-901d-325d9dd13a9c)

But on GH Pages only the FontAwesome icons are rendered, the custom icons appear as e.g. `:dyalog-tatin-logo:`.

![gh-pages](https://github.com/user-attachments/assets/bf44dede-785a-4601-94b9-5c037fb1cecf)

Is this a known issue? Is there some tweak needed to `.github/workflows/ci.yml`?

If this is new to everyone, I’ll report it with a minimum version to replicate.

**Comment by kamilkrzyskow** [comment, marked as answer]
Hello @5jt,
do you run it locally the same way you do in CI?

In CI you run 
```
mkdocs gh-deploy --force -f docs/mkdocs.yml -v
```

and in your `mkdocs.yml` file I see:
```yaml
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
 ```
 
If I remember correctly, the "paths" input into Python Markdown Extension should be relative to the CWD of the python interpreter, not relative to the `mkdocs.yml` file.
 
 I guess you run it locally with `mkdocs serve` so your CWD is the same as `mkdocs.yml`
 And your CI uses the `-f docs/mkdocs.yml ` flag, so the CWD is different than the `mkdocs.yml` file.
 
 EDIT:
 Ah, as for the fix, you could change the run command `cd docs; mkdocs ...` or use a [hook](https://www.mkdocs.org/user-guide/configuration/#hooks) with [on_config](https://www.mkdocs.org/dev-guide/plugins/#on_config) event to change working directory at runtime.
