### DISCUSSION TITLE
TOC active item out of sync

### DISCUSSION THREAD

**Discussion by therepos** [squidfunk/mkdocs-material#8222] [Q&A]
In some instances, the TOC highlighted (active) item is not reflecting the selected anchor (topic) on the page in the current view. I have included a screenshot to illustrate. In the screenshot, user selected the anchor #font. But the TOC does not highlight "Font", instead it highlights the last anchor "Custom CSS". I have also included a sample of this problem at the link below.

https://gothic-modding-community.github.io/gmc/preferences/#font

![query](https://github.com/user-attachments/assets/a2b900d4-8e95-439e-bd18-93daa53db40a)

In my own setup, I am using the following configuration. I've tried other ways including adding additional content or space under the problematic anchor, but this probably should not be the solution. @squidfunk site also spot short topics but the TOC works perfectly in sync with the selected anchor regardless of how short the topic is. 

How do we sync the anchor and the TOC active item?

```
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.annotate
```
