### DISCUSSION TITLE
Using the official Docker container for CI/CD

### DISCUSSION THREAD

**Discussion by RandomInsano** [squidfunk/mkdocs-material#8224] [Q&A] [answered]
I'm using Gitlab and have taken a look at the following guides:
* https://squidfunk.github.io/mkdocs-material/publishing-your-site/#gitlab-pages
* https://gitlab.com/pages/mkdocs

What's a bit of a surprise is that neither of these use the [official Docker container](https://hub.docker.com/r/squidfunk/mkdocs-material).

Because I'm using Gitlab with Docker for my CI/CD stages I'd like to make use of a docker container to save pulling Python packages every time code is pushed to my Git repository. What's a bit strange is that it seems something within MkDocs is calling out to a shell executable and it's failing.

Here's my CI script thus far (.gitlab-ci.yml):

```yaml
image: squidfunk/mkdocs-material

test:
  stage: test
  script:
  - mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
    - test
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
  - mkdocs build --strict --verbose
  artifacts:
    paths:
    - site
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
```

Here's the error I'm getting from Gitlab's build phase:

```text
Executing "step_script" stage of the job script
Using docker image sha256:0d7e7fec824392360a26bc08bd827ff06b6251d3622bc52386727e60366a5734 for squidfunk/mkdocs-material with digest squidfunk/mkdocs-material@sha256:eb04b60c566a8862be6b553157c16a92fbbfc45d71b7e4e8593526aecca63f52 ...
Usage: mkdocs [OPTIONS] COMMAND [ARGS]...
Try 'mkdocs -h' for help.
Error: No such command 'sh'.

Cleaning up project directory and file based variables
ERROR: Job failed: exit code 2
```

The only thing that's changed here is the Docker image used, where before I was using `python:latest`.

Is there anything specific I need to do?

**Comment by RandomInsano** [comment]
Sorry, I think I've found a reasonable duplicate here:
https://github.com/squidfunk/mkdocs-material/issues/4031#issuecomment-1159474004

Changing the question purpose here for others in the future, is there a reason to not use this Docker image for CI/CD? It seems well updated and I don't intend to serve files from it. Trying `build --strict --verbose --site-dir test` to match the `docker run` hasn't worked but if it's valid to do what I'm doing it would be nice to save the bandwidth.

**Comment by RandomInsano** [comment, marked as answer]
To close off the "how" and leave the "why not" question open, I needed to [override the entrypoint](https://docs.gitlab.com/ci/docker/using_docker_images/#override-the-entrypoint-of-an-image) in Gitlab.

This now works:
```yaml
image: 
  name: squidfunk/mkdocs-material
  entrypoint: [""]

test:
  stage: test
  script:
  - mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
    - test
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
...
```
