### DISCUSSION TITLE
Getting a 404 - not found error

### DISCUSSION THREAD

**Discussion by ArtistYay** [squidfunk/mkdocs-material#8258] [Q&A]
Using Obsidian as my notetaker. Notice I keep getting a 404 - not found error on my website. Using Github actions to build and deploy the site

deploy.yml:

```yaml
 name: Build GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - 'notes-mkdocs/**'
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
 
jobs:
  build_mkdocs:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: pip install \
            mkdocs-material
      - run: mkdocs gh-deploy --config-file notes-mkdocs/mkdocs.yml --force

#      - name: Install MkDocs and plugins
#        run: |
#          pip install mkdocs-material mkdocs-obsidian

      - name: Build MkDocs site
        run: |
          mkdocs build --config-file notes-mkdocs/mkdocs.yml

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: notes-mkdocs/site

  deploy_mkdocs:
      runs-on: ubuntu-latest
      needs: build_mkdocs
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
```

Ran `mkdocs serve` local and I'm seeing the files are hosted. I've added the obsidian plugin in my `mkdocs.yml` file:

```yaml
 plugins:
    - typeset
    - search 
    - pub-obsidian:
      obsidian_dir: .obsidian
```

Not sure what I'm missing...here's my repo for reference https://github.com/ArtistYay/artistuniverse.github.io/tree/main
