### DISCUSSION TITLE
How to support documentation for multiple products on one site?

### DISCUSSION THREAD

**Discussion by eyurtsev** [squidfunk/mkdocs-material#8270] [Q&A]
Is there any easy way to implement a single site with support for multiple products (i.e., search would search across all pages). 

Sample navigation and interpretation:

```yaml
nav:
  - OSS: # Interpret this as a product for a drop down menu
    - Guides: # First tab for the OSS product
      - Get Started: product-a/start.md # First side bar item in Guides tab
      - ... # You can add more items here
    - API Reference: product-a/guide.md # second tab for the OSS product
  - Product 2: # Interpret this as a product for a drop down menu
    - Guides: # First tab for the second product
       - Get Started: product-b/start.md # First side bar item in Guides tab
    - Pricing: # Second tab for the second product
      - Plan Deploy 1: product-b/pricing.md # First side bar item in Pricing tab
      - ... # You can add more items here
    - API Reference: product-b/guide.md
```

Sample screenshot that shows what's rendered when OSS product is active.

![image](https://github.com/user-attachments/assets/39fe55cb-70ae-4b18-94bb-bfcaa43a79fc)

Clicking on the drop down, would allow a user to switch to `Product B` which will show the tabs that correspond to `Product B's` tabs.

I've taken a look at the discussion here: 

https://github.com/squidfunk/mkdocs-material/discussions/5800 

My understanding is that the `projects` plugin is not recommended, and it's too complex for what we need. I'm looking for handling all products as part of a single nav bar and add a drop down for switching between the products.
