### DISCUSSION TITLE
Disable Hover on Grid Cards?

### DISCUSSION THREAD

**Discussion by DennisJDufrene** [squidfunk/mkdocs-material#8274] [Q&A] [answered]
What is the .css element to modify Grid Cards to remove the hover effect?

I tried `.grid.cards>ul>li:hover` to no avail.

Thanks!

**Comment by kamilkrzyskow** [comment, marked as answer]
Hi @DennisJDufrene,

```css
.md-typeset .grid.cards > ul > li:hover {
  box-shadow: none;
  border-color: var(--md-default-fg-color--lightest);
}
```

![image](https://github.com/user-attachments/assets/7944c3c0-96b3-4486-b236-7dff4ac0f889)


Ref:
- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_cascade/Specificity
