### ISSUE TITLE
Add support for highlight.js

### ISSUE THREAD

**Issue by baruchn** [squidfunk/mkdocs-material#1004]
I'm writing code documentation for a multi platform project. This documentation includes a lot of code snippets in several programming languages. The problem is that Pygments very limited in styles and languages. Is it possible to add support for highlight.js like the default theme?

**Comment by squidfunk** [comment]
https://squidfunk.github.io/mkdocs-material/customization/#additional-javascript

**Comment by baruchn** [comment]
I was unable to make it work :(
Is there an example somewhere?

**Comment by squidfunk** [comment]
Create a file, e.g. `init.js` in your `docs` folder and add the following line:

``` js
hljs.initHighlightingOnLoad();
```

Add the following to your `mkdocs.yml`:

``` yml
extra_css:
  - path/to/highlight.css # e.g. a CDN or your docs folder if you include a copy

extra_javascript:
  - path/to/highlight.js
  - path/to/your/init.js
```

Not tested, but this is the general approach to add custom JavaScript and CSS to MkDocs. For further troubleshooting regarding customization, I would kindly ask you to move this to the official Gitter channel.
