### ISSUE TITLE
custom `toc.html` file not copied into `site` from designated custom directory

### ISSUE THREAD

**Issue by craigphicks** [squidfunk/mkdocs-material#1025]
## Description
custom `toc.html` file not copied into `site` from designated custom directory

### Expected behavior
Expected is to be copied because `mkdocs.yml ` contains
```
theme:
    name: mkdocs
    custom_dir: custom/
```
and the file `toc.html` exists as `./custom/toc.html` in the dir structure
```
.
├── custom
├── docs
├── site
```

### Actual behavior

From `./` 
```
# rm -rf site/*
# mkdocs build
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: .../site 
```
But no `toc.html` appears in site.

### Steps to reproduce the bug

As described above

### Package versions

* Python: `python --version`

`Python 3.6.7`

* MkDocs: `mkdocs --version`

`mkdocs, version 1.0.4`

* Material: `pip show mkdocs-material `

*(nothing returned  - IS THIS THE PROBLEM?)*

### Project configuration

``` yaml
site_name: Server and Client side Authentication w/ lighttpd
nav:
-  Home: 'index.md'
-  Privca: 'privca-man.md'
theme:
    name: mkdocs
    custom_dir: custom/

# extension defaults are ['meta', 'toc', 'tables', 'fenced_code']
markdown_extensions:
    - meta
    - tables
    - fenced_code
    - toc:
        title: Table of Contents
        permalink: True
        baselevel: 2
```

### System information

* OS: [Linux ub18 4.18.0-15-generic #16~18.04.1-Ubuntu SMP ]
* Browser: [The browser used, if relevant]
