### ISSUE TITLE
Trying to enter text in comment box, typing `s` causes search to grab focus, eat letter.

### ISSUE THREAD

**Issue by craigphicks** [squidfunk/mkdocs-material#1026]
## Description

I added the "isso" self-administrated/serviced comment function to in place disqus and found the letter 's' (also 'S') can't be entered because that key causes the searchbox to grab the focus, eating the letter in the process.

I couldn't tell you if disqus avoids this because I haven't tried disqus.

I believe this is related to issue #400.  One comment noted that `s` resulted in this behavior.  That same commentator suggested removing attribute `accesskey="s"` from this element:

``
<input type="text" class="md-search__input" name="query" required="" placeholder="Search" accesskey="s" autocapitalize="off" autocorrect="off" autocomplete="off" spellcheck="false" data-md-component="query">
``

Indeed - that `accesskey="s"` attribute is now **gone** from that element, but the old behavior is currently present in this topic's scenario.  My background is weak but I guess it might be getting trapped by some java code.  However I cannot find it.

In issue #398 "Shortcut breaks forms" it the poster was advised to in a "form".  I have tried that but it didn't seem to work - maybe cause it is wrapping a javascript? :

```
<form>
<div>
<script data-isso="https://pindertek.net/isso-2/"
        src="js-isso/embed.dev.js"></script>
<section id="isso-thread"></section>
</div>
</form>
```

I tried this both in the main text and overriding the `{% block disqus %}`, no difference.

As long as I don't type 's' or 'f' (any others?) I can successfully send a message.

Any help would be greatly appreciated.

This really is a great piece of software - kudo to squidfunk and to the whole stack.

### Description of the bug

See "description"

### What you expected to happen

Plain letters typed into a text don't cause another box to grab focus.

### Actual behavior

See "description"

### Steps to reproduce the bug

Go to (https://craigphicks.github.io/privca/) and scroll to bottom.
Try typing 'a' into comment box - it works.
Try typing 's' into comment box - the focus changes.

### Package versions

* Python: `python --version`

`python 3.6.7`

* MkDocs: `mkdocs --version`

`mkdocs, version 1.0.4   (Python 3.6)`

* Material: `pip show mkdocs-material | grep -E ^Version`
```
Name: mkdocs-material
Version: 4.0.2
Summary: A Material Design theme for MkDocs
Home-page: https://squidfunk.github.io/mkdocs-material/
Author: Martin Donath
Author-email: martin.donath@squidfunk.com
License: MIT
Location: /home/craig/github/privca/mkdocs.d/pyenv/lib/python3.6/site-packages
Requires: mkdocs, Pygments, pymdown-extensions
```

### Project configuration

``` yaml
# Project information
site_name: 'Server/Client 2-way Authentication w/ Private CA'
site_description: 'Step by step guide to issuing private certs for Server and Client Side Authentication - specifically *lighttpd* and *Firefox*'
site_author: 'Craig Hicks'
site_url: 'https://craigphicks.github.io/privca'

# Repository
#repo_name: 'craigphicks/privca'
#repo_url: 'https://github.com/craigphicks/privca'

# Copyright
copyright: 'Copyright &copy; Craig Hicks 2019'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
  - type: 'github'
    link: 'https://github.com/craigphicks'
# #   - type: 'twitter'
# #     link: 'https://twitter.com/squidfunk'
# #   - type: 'linkedin'
# #     link: 'https://linkedin.com/in/squidfunk'

# Google Analytics
# google_analytics:
#   - 'UA-XXXXXXXX-X'
#   - 'auto'

# Extensions
markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

#extra:
#  disqus: 'your-shortname'

theme:
  name: 'material'
  custom_dir: 'custom'
```

### System information

* OS: [The operating system you're running]

`Linux ub18 4.18.0-15-generic #16~18.04.1-Ubuntu`

* Browser: [The browser used, if relevant]

*Firefox 65.0*
