### ISSUE TITLE
Snippets + SuperFences Tabs

### ISSUE THREAD

**Issue by tonglil** [squidfunk/mkdocs-material#1029]
## Description

Unable to get Snippets to include a file when making a multiple tabbed ("Grouping code blocks") code block.

### Expected behavior

<img width="781" alt="image" src="https://user-images.githubusercontent.com/3250776/54221209-468ba300-44b0-11e9-861b-66f2ac6b986c.png">

### Actual behavior

<img width="785" alt="image" src="https://user-images.githubusercontent.com/3250776/54221251-61f6ae00-44b0-11e9-9696-9170c29ad9c0.png">

\* note that without the fencing it includes the file correctly

### Steps to reproduce the bug

```
    ```C tab="C"
    
    --8<-- 
    example.c
    --8<-- 
    
    ```
```

### Package versions

`squidfunk/mkdocs-material:latest` pulled today.

### Project configuration

``` yaml
...
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
```
