### ISSUE TITLE
[Feature Request] Add Basic Auth to the Mkdoc Material Tool

### ISSUE THREAD

**Issue by toni-moreno** [squidfunk/mkdocs-material#1041]
## Description

This tool is really great , but we need maintain some documentation password protected. A simple config in the mkdocs.yml

something like:

````
site_name: SomeName
site_url: https://www.mkdocs.org
site_description: SomeDoc
site_author: Some write

username = 'myuser'
password = 'mypassword'

theme:
    name: 'material'
    highlightjs: true
    hljs_languages:
        - yaml
        - django
        - bash
        - go
        - javascript

markdown_extensions:
    - toc:
        permalink: ┴
    - admonition
    - def_list
````
