### ISSUE TITLE
Mobile sidebar in desktop Firefox

### ISSUE THREAD

**Issue by ntnsndr** [squidfunk/mkdocs-material#1064]
## Description

After using the theme without problems for a few days, a strange thing has started happening. On several computers, in Firefox, the left sidebar becomes hidden, as in mobile view, with only the three-bar icon in the top-left. Interestingly, this happens simultaneously on any site using the theme. I would prefer to use the standard desktop view where the sidebar is always visible.

When I use Chromium, the sidebar is visible.

Thanks in advance for your help!

### Expected behavior

When using a desktop browser in full-screen, the sidebar should always be visible.

### Actual behavior

The sidebar is hidden behind the three-bar icon in the top-left, as in mobile view.

### Steps to reproduce the bug

I'm not sure what brings about the change. It appears to happen on its own.

### Package versions

* Python: `python --version` 2.7.15+
* MkDocs: `mkdocs --version` 1.0.4
* Material: `pip show mkdocs-material | grep -E ^Version` 4.1.1

### Project configuration

``` yaml
theme:
  name: 'material' # https://github.com/squidfunk/mkdocs-material/
  custom_dir: 'material'
  font: false # dodges Goog fonts
  palette:
    primary: white
    accent: orange
  logo: 'images/group_work.svg' # from https://material.io/tools/icons/
  favicon: 'images/group_work.svg'

extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - footnotes

extra:
  social:
    - type: globe
      link: https://cmci.colorado.edu/medlab/
    - type: twitter
      link: https://twitter.com/medlabboulder

```

### System information

* OS: Xubuntu 18.10
* Browser: Firefox 66.0.2
