### ISSUE TITLE
Modify appearance of Jupyter notebook output cells

### ISSUE THREAD

**Issue by AtmaMani** [squidfunk/mkdocs-material#1094]
## Description
I use [mkdocs](http://mkdocs.org/) with this material theme and [mknotebooks](https://github.com/greenape/mknotebooks) plugin to render notebook articles as a blog. Everything works good except the appearance of input and output cells are identical. This makes reading code and output hard. 

### Expected behavior
Notebook cells can be markdown or code input or code output. In a notebook, each appear differently as shown below:
![image](https://user-images.githubusercontent.com/6750179/57325254-7b863180-70be-11e9-962e-e1bf852e4ea7.png)

### Actual behavior
All types of cells appear alike. Code cells have code highlighting, however this is not sufficient to distinguish inputs and outputs
![image](https://user-images.githubusercontent.com/6750179/57325151-4548b200-70be-11e9-9cb0-6f3227d91c9a.png)

### Package versions

* Python: `python --version` : `Python 3.7.3`
* MkDocs: `mkdocs --version`:  `mkdocs, version 1.0.4`
* Material: `pip show mkdocs-material | grep -E ^Version`: `Version: 4.2.0`

### Project configuration
```yaml
site_name: Atma Mani's blog
nav:
  - Home: index.md
  - Talks: talks.md
  - Articles: articles/readme.md
  - Cheatsheets: cheatsheets/readme.md
  - Spatial Data Science: spatial-data-science/readme.md
  - Apps: apps.md
  - Resume: resume.md
extra_css: 
  - 'stylesheets/extra.css' # does not work
exta_javascript:
  - 'javascripts/extra.js' # does not work
theme:
  name: 'material'
  palette:
    primary: 'teal'
    accent: 'deep orange'
  logo:
    icon: 'blur_on'
  favicon: 'static/favicon.svg'
  highlightjs: true
  # hljs_languages:
  #   - python
  #   - r
  #   - yaml
copyright: 'Copyright &copy; 2019 - 2020 Atma Mani'

# Plugins
plugins:
 - mknotebooks:
    execute: false
    preamble: ./preamble_script.py # does not work, remove.

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
      noclasses: false
      use_pygments: true
  - toc:
      permalink: true
```
### System information

* OS: Windows 10, MacOSX 10.14
* Browser: Firefox 66.0, Chrome 74.x
