### ISSUE TITLE
Mapping from `nav` in config file to reality

### ISSUE THREAD

**Issue by jfix** [squidfunk/mkdocs-material#1095]
This is not so much a bug report as a polite request to help my understanding of how the `nav` config section in the `mkdocs.yml` is rendered in reality. 

I'm looking at this project's `mkdocs.yml` file and its rendering on the corresponding github.io site and I'm confused:

<img width="713" alt="Screenshot 2019-05-08 at 00 06 20" src="https://user-images.githubusercontent.com/170240/57336141-36491a80-7125-11e9-9872-bd20ed523c37.png">

According to the documentation[1], I would expect not just the top sections `Material` and `Extensions` to appear in the top header section, but also `Getting started`, `Specimen`, `Customization` etc. but this is clearly not the case. What's going on? 🤔 Thanks!

[1] https://squidfunk.github.io/mkdocs-material/getting-started/#tabs

**Comment by squidfunk** [comment]
>  I would expect not just the top sections Material and Extensions to appear in the top header section, but also Getting started, Specimen, Customization etc. but this is clearly not the case.

First, it would be possible to create top-level sections without any nested pages, effectively rendering the menu on the left obsolete. Second, it's a historical decision in part, as tabs was a feature that was introduced _after_ the current navigation was released with the advent of 1.0.0. I wanted to make the transition as smooth as possible, so I decided to follow the current approach.

The docs state this behavior:

> When tabs are enabled, __top-level sections__ will be rendered in an additional layer directly below the header. The navigation on the left side will only include __the pages contained within the selected section__. Furthermore, __top-level pages__ defined inside your project's mkdocs.yml will be __grouped under the first tab__ which will receive __the title of the first page__.

If you feel that the documentation could be improved, I'm happy to merge a PR!

**Comment by squidfunk** [comment]
In fact, the current implementation allows exactly for the behavior you described. If you nest everything under sections:

``` yaml
nav:
  - Material:
    - Material: index.md
    - Getting started: getting-started.md
    - Specimen: specimen.md
    - Customization: customization.md
    - Compliance with GDPR: compliance.md
    - Release notes: release-notes.md
    - Author's notes: authors-notes.md
    - Contributing: contributing.md
    - License: license.md
  - Extensions:
    - Admonition: extensions/admonition.md
    - CodeHilite: extensions/codehilite.md
    - Footnotes: extensions/footnotes.md
    - Metadata: extensions/metadata.md
    - Permalinks: extensions/permalinks.md
    - PyMdown: extensions/pymdown.md
```

The desktop view will look exactly like before, except for the title of the navigation bar being __Material__ (the section title) and not __Material for MkDocs__ (the site title):

<img width="1552" alt="Bildschirmfoto 2019-05-08 um 09 27 06" src="https://user-images.githubusercontent.com/932156/57357566-7df69300-7173-11e9-8619-590f26feec35.png">

When the sidebar is collapsed, the section titles will be nested under their respective sections:

<img width="612" alt="Bildschirmfoto 2019-05-08 um 09 27 13" src="https://user-images.githubusercontent.com/932156/57357585-8bac1880-7173-11e9-84ca-beb5cc60cabe.png">
