### ISSUE TITLE
Unexpected results with search function

### ISSUE THREAD

**Issue by mmourcia** [squidfunk/mkdocs-material#1097]
## Description

Search engine does not return expected results

### Expected behavior

Return pages containing keywords

### Actual behavior

When I search for the word "webhook", auto completion returns the wanted pages.
When I add the final "s" to the search word, auto completion does not return any pages.

![image](https://user-images.githubusercontent.com/3705792/57443339-1a8d6380-724e-11e9-854e-5f84c834990f.png)

And with "s"

![image](https://user-images.githubusercontent.com/3705792/57443382-33961480-724e-11e9-8192-1ce2bd181369.png)

### Steps to reproduce the bug

1. Go to https://doc.canopsis.net
2. Search for "webhook" and look at results containing "webhook" and "webhooks"
3. Search for "webhooks" and see that there are no results

### Package versions

* Python: Python 2.7.13
* MkDocs: mkdocs, version 1.0.4 from python2.7/site-packages/mkdocs (Python 2.7)
* Material: Version: 4.2.0

### Project configuration

``` yaml
site_name: Documentation Canopsis
site_url: https://doc.canopsis.net

repo_url: https://git.canopsis.net/canopsis/canopsis

docs_dir: 
   sources/docs/fr
copyright: Documentation © Canopsis 2018–2019 / CC BY-SA 3.0 FR (https://creativecommons.org/licenses/by-sa/3.0/fr/)

theme:
  name: material
  language: fr
  extra:
    search:
        language: 'fr'
  logo: 'img/canopsis-mkdocs.png'
  palette:
    primary: 'green'
    accent: 'green'
  feature:
    tabs: true

markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: True

plugins:
    - search

```

### System information

* OS: Debian 9
* Browser: Chrome or Firefox

**Comment by squidfunk** [comment]
Sounds like a stemming problem to me, because you set French as a search language and search for an english word. Try setting this __on the top-level__ (not under `theme`):

```
extra:
    search:
        language: 'en, fr'
```

**Comment by mmourcia** [comment]
OK thanks for your anwser.
I've tried it but the problem is still there

````
extra:
  search:
      language: 'en, fr'

theme:
  name: material
  language: fr
  logo: 'img/canopsis-mkdocs.png'
  palette:
    primary: 'green'
    accent: 'green'
  feature:
    tabs: true
````

Note that it's the same with "french word" like "développement".  
But when I set the language theme as 'en' instead of 'fr' (not the extra search one), it works as expected

**Comment by squidfunk** [comment]
> But when I set the language theme as 'en' instead of 'fr' (not the extra search one), it works as expected

If this works, just try setting `extra.search.language: en` (exclude `fr`). Material uses [lunr.js](https://github.com/olivernn/lunr.js/) for search, so if you configured things exactly as noted, there's not much we can do about it. Maybe you could ask on their issue tracker.

**Comment by mmourcia** [comment]
OK.
My final conf is working great like you said.
I don't understand what i'm really loosing by enabling 'en' search only but it's working.

````
theme:
  name: material
  language: fr
  logo: 'img/canopsis-mkdocs.png'
  palette:
    primary: 'green'
    accent: 'green'
  feature:
    tabs: true

extra:
  search:
    language: 'en'
````
