### ISSUE TITLE
Inconsistent search behavior

### ISSUE THREAD

**Issue by connerxyz** [squidfunk/mkdocs-material#1099]
## Description

Search appears to work with beginning of word, but then not when the full word is queried.

### Expected behavior

**Query**: "where"
**Expected preview options**: anything heading/paragraph/etc containing "where"

### Actual behavior

[video](https://youtu.be/K_W118lrvEU)

### Steps to reproduce the bug

1. Create pages containing "which"
2. Create pages containing "where"
3. Create pages containing "what" 
4. Search for "wh" – you get appropriate results
5. Search for "what" – you get appropriate results
6. Search for "which" –  you get no results.
6. Search for "where" –  you get no results.

### Package versions

* Python: Python 3.7.3
* MkDocs: mkdocs, version 1.0.4
* Material: Version: 4.2.0

### Project configuration

``` yaml
site_name: 'DEDocketResearch'
theme: 'material'
extra_css: [extra.css]
extra_javascript: [extra.js]
nav:
  - '': 'index.md'
  - '1-1-DELADocketSurvey': '1-1-DELADocketSurvey/1-1-DELADocketSurvey.md'
  - '1-2-DEJMTScrapeAndSurvey': '1-2-DEJMTScrapeAndSurvey/1-2-DEJMTScrapeAndSurvey.md'
  - '1-3-LAJMTInitialComparison': '1-3-LAJMTInitialComparison/1-3-LAJMTInitialComparison.md'
```

### System information

* OS: macOS Sierra
* Browser: Chrome

---

I've saw the related issues, but couldn't figure if/how this was related exactly.

This project is awesome and @squidfunk is so responsive!
