### ISSUE TITLE
Metadata issue when link to TFS source control

### ISSUE THREAD

**Issue by snelljef** [squidfunk/mkdocs-material#1115]
## Description

We wanted to connect our markdown documents to their source control location which is Microsoft Azure DevOps Server (formerly Team Foundation Server) but the results are not perfect. It does work though which is nice, just not very clean.

In the Markdown file itself, the **path:** tag needs to be completely empty with nothing but a newline character. Otherwise the resulting url contains [''] in it.
The **source:** tag needs to have the full path in it since it's a query string implementation. For example:

path:
source:?path=/docs/markdown_file.md&version=GBmaster

### Expected behavior

A cleaner URL: 
https://onpremisetfsserver.com/Projects/_git/Documentation?path=/docs/markdown_file.md&version=GBmaster

Cleaner **Source** section in the resulting document itself, having the file name instead of the full query string. Perhaps even the branch name if desired.

### Actual behavior

The "Source" section at the bottom of the document ends up looking terrible. Having the full text that was entered from the **source:** tag.

The resulting URL also has an extra slash in it due to omitting the **path:**. For example:

https://onpremisetfsserver.com/Projects/_git/Documentation//?path=/docs/markdown_file.md&version=GBmaster

### Steps to reproduce the bug

Configuration is provided in yaml section below, and summarized in the description above

### Package versions

* Python: `python3 --version`
Python 3.6.7

* MkDocs: `mkdocs --version`
mkdocs, version 1.0.4 from /home/eso/.local/lib/python3.6/site-packages/mkdocs (Python 3.6)

* Material: `pip show mkdocs-material | grep -E ^Version`
Version: 4.3.1

### Project configuration

``` yaml
site_name: Documentation Site
site_url: 'https://ourserver.com/Documentation/'
site_description: 'documentation site'

# Repository
repo_name: 'Azure DevOps Server [TFS]'
repo_url: 'https://onpremisetfsserver.com/Projects/_git/Documentation'


# Copyright
copyright: 'Copyright &copy; 2017 Company name'

# Theme
theme: 
  name: material
  language: 'en'
  logo: 'img/logo.png'
  palette:
    primary: 'blue'
    accent: 'orange'
  feature:
    tabs: true

# Search
extra:
  search:
    language: 'en'

# Custom CSS
extra_css:
  - 'stylesheets/snackbar_material.css'
  - 'stylesheets/snackbar.min.css'
  - 'stylesheets/extra.css'
  - 'stylesheets/zoom.css'
  - 'stylesheets/progress_bar_material.css'

extra_javascript:
  - 'javascripts/jquery.js'
  - 'javascripts/snackbar.min.js'
  - 'javascripts/status.js'
  - 'javascripts/extra.js'
  - 'javascripts/zoom.js'

# Extensions
markdown_extensions:
  - meta
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.keys
```

### System information

* OS: Windows Server 2019, using Ubuntu with Windows Subsystem for Linux
* Browser: FireFox
