### ISSUE TITLE
Using mkdocs-material with Microsoft's pxt-mkdocs

### ISSUE THREAD

**Issue by solbero** [squidfunk/mkdocs-material#1118]
## Description

Rendering of Micro:Bit code graphical blocks in Material using [Microsoft's pxt-mkdocs
](https://github.com/Microsoft/pxt-mkdocs-sample) does not work. I am using MkDocs to write up some Micro:Bit tutorials for my schools district. Material has the features I would like to use for my writing, but this issue is a bit of a show stopper. I have tried, and the blocks render correctly, in mkdocs, writethedocs and bootstrap4 themes.

### Expected behavior

Micro:Bit code blocks written in Markdown should render to graphical code blocks in the browser.

### Actual behavior

No code blocks are rendered in the browser using pxt-mkdocs.

### Steps to reproduce the bug

1. Copy the sample project from pxt-mkdocs
2. Change the theme to Material

### Package versions

* Python: 2.7.16
* MkDocs: 1.0.4
* Material: 4.3.1

### Project configuration

``` yaml
site_name: MakeCode MkDocs
site_description: A documentation website built with MkDocs that supports MakeCode block rendering
theme: material
extra_javascript: [embed.js]
```
### System information

* OS: Fedora 30
* Browser: Chrome 74

**Comment by squidfunk** [comment]
Honestly, it's really hard for anyone to understand your issue without a reproducible case. You should provide one (could also be a link to a repository reproducing the problem), so we could check why it doesn't work.

In general, Material has limited support for third party extensions, but most of them should work out of the box, especially if they don't need custom styling.

**Comment by squidfunk** [comment]
Okay, the extension relies on jQuery being bundles with the theme, which Material does not. If you include jQuery, you should be good to go, i.e.:

``` yml
site_name: MakeCode MkDocs
site_description: A documentation website built with MkDocs that supports MakeCode block rendering
theme: material
extra_javascript:
  - https://code.jquery.com/jquery-3.4.1.min.js
  - embed.js
```

<img width="776" alt="Bildschirmfoto 2019-05-29 um 08 18 36" src="https://user-images.githubusercontent.com/932156/58534013-63e82780-81ea-11e9-9b98-5d0dd96db627.png">

You might want to add some custom styling to remove the background color on code blocks:

``` css
.md-typeset pre {
  background-color: transparent
}
```
