### ISSUE TITLE
Use page.edit_url for repository link in header

### ISSUE THREAD

**Issue by jkinkead** [squidfunk/mkdocs-material#1139]
## Description

Right now, the setting `page.edit_url` is [used for creating an edit icon within a page's body](https://github.com/squidfunk/mkdocs-material/blob/306145cf58fc2a36917a0cefe8ba5349fad2d2af/src/base.html#L296-L301), but the setting [is ignored when creating the header link](https://github.com/squidfunk/mkdocs-material/blob/306145cf58fc2a36917a0cefe8ba5349fad2d2af/src/partials/source.html#L40-L42).

This has been confusing our users, both since it differs from [the default mkdocs theme's behavior](https://github.com/mkdocs/mkdocs/blob/9ae04213b9e2ed6625217ca0d6db2bf69a0c1205/mkdocs/themes/mkdocs/base.html#L140-L149), and because the edit link within the body will scroll off of the top of the page as the user scrolls down.

### Expected behavior

`page.edit_url` is used in the header when present.

### Actual behavior

Only `config.repo_url` is used.

### Package versions

* Python: 3.7.1
* MkDocs: 1.0.4
* Material: 4.4.0

### Project configuration

``` yaml
site_name: My Site
repo_url: https://github.com/jkinkead/doesnotexist
repo_name: Click to Edit (not really)
edit_uri: edit/master/
theme:
  name: material
```
