### ISSUE TITLE
Stuck trying to get Disqus to work...

### ISSUE THREAD

**Issue by arretx** [squidfunk/mkdocs-material#1142]
## Description

Disqus Integration

### Expected behavior

I would think that the Disqus commenting section would appear below each document, except for the site eindex.

### Actual behavior

No Disqus comment section is shown.

### Steps to reproduce the bug

1. Added:

~~~
extras:
  disqus: 'my-disqus-shortname'
~~~

### Package versions

* Python: `2.7.15`
* MkDocs: `1.0.4`
* Material: `4.4.0`

### Project configuration

``` yaml
site_name: 'Chateau De Bleep'
site_description: 'Home Automation with Home Assistant'
site_author: 'Jon Griffith'
site_url: 'https://homeassistant.jongriffith.com'
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'cyan'
  logo:
    icon: 'home'

extras:
  disqus: 'my-home-assistant-setup'

repo_name: 'hassio-chateau-de-bleep'
repo_url: 'https://github.com/arretx/hassio-chateau-de-bleep'

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
```

### System information

* OS: MacOSX Mojave (Latest)
* Browser: Netscape.  Just kidding.  Chrome.
