### ISSUE TITLE
Researchgate social link icon is invisible

### ISSUE THREAD

**Issue by soronpo** [squidfunk/mkdocs-material#1156]
## Description

The `researchgate` social link icon is invisible

### Expected behavior

The icon should appear like other social links

### Actual behavior

The icon is invisible

### Steps to reproduce the bug
set the configuration as mentioned below

### Package versions

* Python: `python --version`
Python 3.7.3
* MkDocs: `mkdocs --version`
mkdocs, version 1.0.4
* Material: `pip show mkdocs-material | grep -E ^Version`
Version: 4.4.0
### Project configuration

``` yaml
extra:
  social:
    - type: 'researchgate'
      link: 'https://www.researchgate.net/profile/Some_Researcher'
```

### System information

* OS:
Windows 7
* Browser:
Firefox
