### ISSUE TITLE
Pygments installed, syntax highlighting not working

### ISSUE THREAD

**Issue by snim2** [squidfunk/mkdocs-material#1204]
## Description

Syntax highlighting not working. 

### Expected behavior

Syntax highlighting to work for all languages covered by Pygments.

### Actual behavior

Most code blocks do not get highlighted. Some Java and `sh` blocks seem to work, but PHP in particular does not.

Pygments is installed, the relevant lines in `mkdocs.yml` are there. `codehilite` seems to be producing correct HTML:

```html
<div class="codehilite"><pre><span></span><span class="x">$user = array(&quot;name&quot; =&gt; &quot;John&quot;, &quot;email&quot; =&gt; &quot;john@mail.com&quot;);</span>
</pre></div>
```

But this isn't coloured. 

Other features of `codehilite` do seem to be working (for example, I can switch line numbers on from the YAML file). 

Viewing from an incognito tab did not resolve the problem.

### Steps to reproduce the bug

1. Set up a new (Python 3) mkdocs project, with a code fenced block of PHP
2. Run `mkdocs serve`
3. Navigate to `127.0.0.1:8888/correct-page`

### Package versions

* Python: `python --version`: `Python 3.7.3`
* MkDocs: `mkdocs --version`: `mkdocs, version 1.0.4`
* Material: `pip show mkdocs-material | grep -E ^Version`: `Version: 4.4.0`

This is the contents of `requirements.txt`:

```yaml
certifi==2019.6.16
chardet==3.0.4
Click==7.0
htmlmin==0.1.12
idna==2.8
Jinja2==2.10.1
jsmin==2.2.2
livereload==2.6.1
Markdown==3.1.1
MarkupSafe==1.1.1
mkdocs==1.0.4
mkdocs-material==4.4.0
mkdocs-minify-plugin==0.2.1
Pygments==2.4.2
pymdown-extensions==6.0
python-gitlab==1.10.0
PyYAML==5.1.2
requests==2.22.0
six==1.12.0
tornado==6.0.3
urllib3==1.25.3
```

### Project configuration

This is the relevant excerpt:

``` yaml
theme:
  name: 'material'
  logo: 'assets/images/logo.png'
  favicon: 'assets/images/favicon.ico'
  palette:
    primary: 'Brown'
    accent: 'Deep Orange'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
extra_css:
  - 'assets/css/...'
extra_javascript:
  - 'assets/javascript/...'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      use_pygments: true
  - toc:
      permalink: true
```

Note that if I comments on the code in the extra CSS and JS files, the bug behaviour doesn't change.

### System information

* OS: [The operating system you're running] Ubuntu 19.04
* Browser: [The browser used, if relevant] Chromium Version 76.0.3809.87 (Official Build) Built (64-bit). Also tried Firefox, same results)
