### ISSUE TITLE
Can't get the admonition body to display when it contains a nested admonition element.

### ISSUE THREAD

**Issue by ParaDiceSolutions** [squidfunk/mkdocs-material#1215]
## Description
I would like to use nested admonitions elements, but I can't get the admonition body to display when it contains a nested admonition element. I have used the example given (see below) on this webpage : https://marketplace.visualstudio.com/items?itemName=jebbs.markdown-extended#overview
------- Example ------
!!! note
    This is the **note** admonition body
    !!! danger Danger Title
        This is the **danger** admonition body

### Expected behavior

I expect to see the "This is the note admonition body" displayed, as per the webpage example.

### Actual behavior

See 
### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Package versions

* Python: Python 3.7.4
* MkDocs: mmkdocs, version 1.0.4 from c:\python37\lib\site-packages\mkdocs (Python 3.7)
* Material: Name: Version: 4.4.0

### Project configuration

``` yaml
# Copyright (c) 2017 INFOLYTIK INC.

# Project information
site_name: Infolytik Documentation
site_description: Infolytik Online Documentation
site_author: Infolytik INC
site_url: https://www.infolytik.com

# NOTES:
# Use ALGOLIA for search...

# Repository
# repo_name: squidfunk/mkdocs-material
# repo_url: https://github.com/squidfunk/mkdocs-material

# Copyright
copyright: 'Copyright &copy; 2018 Infolytik'

theme:
  name: 'material'
  custom_dir: 'lightbox'
  feature:
    tabs: true
  favicon: ../images/favicon.ico
  logo: 'images/metaminer-client-icon.svg'
  palette:
    primary: 'blue'
    accent: 'indigo'
#    icon: 'images/metaminer-client-icon.svg'
#    icon: 'dashboard'
# Options
extra:
  language: en
  palette:
    primary: green
    accent: orange
  social:
    - type: globe
      link: https://www.infolytik.com
    - type: comments-o
      link: https://community.infolytik.com
    - type: twitter
      link: https://twitter.com/infolytik
    - type: linkedin
      link: https://www.linkedin.com/company/635431
extra_css:
  - 'stylesheets/bootstrap.min.css'
  - 'stylesheets/ekko-lightbox.min.css'
  - 'stylesheets/lg-fb-comment-box.min.css'
  - 'css/lg-transitions.min.css'
  - 'css/lightgallery.min.css'
extra_javascript:
  - 'javascripts/jquery.min.js'
  - 'javascripts/bootstrap.min.js'
  - 'javascripts/ekko-lightbox.min.js'
  - 'js/lightgallery.min.js'

# Extensions
markdown_extensions:
  - admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
pages:
  - Getting Started: index.md
  - Download & Installation: download-installation.md
  - Old Documentation: old-metaminer-docs.md
  - MetaMiner Admin:
    - Introduction: metaminer-administrator/index.md
    - Installing New Releases: metaminer-administrator/updating-metaminer.md
    - Resetting Metadata: metaminer-administrator/resetting-metadata.md
    - FAQ - Admin: metaminer-administrator/FAQ-installing-updates.md
  - MetaMiner Client:
    - Introduction: metaminer/index.md
    - MetaMiner DB: metaminer/mmdb-schema.md
    - CMS Explorer: modules/cms-explorer/cms-explorer.md
    - Users: modules/users/businessobjects-user-admin.md
    - Servers: modules/servers/businessobjects-servers-tab.md
    - Visual Diff: modules/visual-diff/object-cms-diff.md
    - Security Diff: modules/security-diff/business-objects-security-compare.md
    - Impact Analysis DB: modules/impact-db/impact-analysis-database-objects.md
    - Alerts: modules/alerts/alerts-workflow.md
    - MetaQuery: modules/metaquery/businessobjects-tableau-repo-analysis.md
    - Backup/Promote: modules/backup-promote/backup-restore-businessobjects.md
# TODO:URGENT : Need a Tableau drop-down thing here
    - Report Validation: modules/report-validation.md
    - Tableau Explorer: modules/tableau-explorer/tableau-explorer.md
    - Tableau Users: modules/tableau-users/tableau-user-admin.md
    - Tableau Finder: modules/tableau-finder/tableau-finder.md
    - Workbook Validation: modules/workbook-validation/tableau-dashboard-testing.md
  - Reports:
    - Overview: reports/overview.md
    - Audit Reports:
      - <font size="2">[MM-A01] Audit - Object Activity Summary</font>: reports/MM-A01.md
      - <font size="2">[MM-A02] Audit - User Activity Summary</font>: reports/MM-A02.md
      - <font size="2">[MM-A03] Audit - Event Details</font>: reports/MM-A03.md
    - Webi IA Reports:
        - <font size="2">[MM-W10] Webi IA - Object Use Overview</font>: reports/MM-W10.md
        - <font size="2">[MM-W11] Webi IA - Object Use Overview (per Object)</font>: reports/MM-W11.md
        - <font size="2">[MM-W12] Webi IA - Object Use Detail</font>: reports/MM-W12.md
        - <font size="2">[MM-W17] Webi IA - Dataprovider SQL</font>: reports/MM-W17.md
    - Crystal IA Reports:
      - <font size="2">[MM-C11] Crystal IA - Business View Use</font>: reports/MM-C11.md
      - <font size="2">[MM-C12] Crystal IA - Business View Data Dictionary</font>: reports/MM-C12.md
      - <font size="2">[MM-C13] Crystal IA - Prompt Group Business Field Use</font>: reports/MM-C13.md
      - <font size="2">[MM-C14] Crystal IA - Table Field Use</font>: reports/MM-C14.md
      - <font size="2">[MM-C15] Crystal IA - DB User Use</font>: reports/MM-C15.md
      - <font size="2">[MM-C16] Crystal IA - Datasource Use</font>: reports/MM-C16.md
      - <font size="2">[MM-C17] Crystal IA - Command Text Use</font>: reports/MM-C17.md
    - General Document Reports:
        - <font size="2">[MM-D01] Documents - Activity & Datasource</font>: reports/MM-D01.md
    - Universe Reports:
        - "[MM-U01] Universe Dictionary": reports/MM-U01.md
        - <font size="2">"[MM-U10] Unused Objects - Summary"</font>: reports/MM-U10.md
        - <font size="2">\[MM-U11\] Unused Objects - UNV</font>: reports/MM-U11.md
        - <font size="2">[MM-U12] Unused Objects - UNX</font>: reports/MM-U12.md
        - <font size="2">[MM-U13] Unused Objects - Detail</font>: reports/MM-U13.md
    - Server Reports:
        - <font size="2">[MM-S01] Server - Overview</font>: reports/MM-S01.md

  - Pulse:
    - Introduction: pulse/index.md
    - Dashboards - SAP: pulse/bobj-server-monitoring-dashboards.md
  - Use Cases: #use-cases/use-cases.md
#    - Impact Analysis: use-cases/impact-analysis-general.md
#    - Unused Universe Objects: use-cases/unused-universe-objects-optimization.md
    - Webi Query Stripping: use-cases/webi-query-stripping.md
    - Crystal Report Bulk DB Config: use-cases/crystal-database-remapping.md
    - Webi Datasource Analysis: use-cases/webintelligence-datasource-analysis.md
  - FAQ:
    - MetaMiner DB: metaminer/mmdb-schema.md
    - Direct MMDB Access: metaminer-tips/direct-access-metaminer-db.md
    - MetaMiner Standard Universe: metaminer-tips/metaminer-universe-sapbi4.md
    - Log files & Diagnostics: metaminer-tips/getting-log-files.md
    - Custom Settings: metaminer-tips/server-custom-settings.md
  - Analysis Catalog:
    - BusinessObjects SQLs: metaminer/scripts-bo/scripts-catalog-businessobjects.md
#    - Audit & Usage: metaminer/scripts-bo/auditing-usage.md
#    - Metadata & Impact Analysis: metaminer/scripts-bo/sap-bi4-metadata-impact-analysis.md
#    - Server Metrics & Configs: metaminer/scripts-bo/server-metrics-configs-monitoring.md
#    - Performance Statistics: metaminer/scripts-bo/report-system-performance.md
#    - User & Group Management: metaminer/scripts-bo/users-groups.md

# Google Analytics
google_analytics:
  - 'UA-11459374-1'
  - 'auto'
```

### System information

* OS: Windows 10
* Browser: Chrome / Firefox / IE 11
