### ISSUE TITLE
Selecting `black` as primary color doesn't change color of links

### ISSUE THREAD

**Issue by mightymackem** [squidfunk/mkdocs-material#1219]
## Description

In the [4.4.1](https://github.com/squidfunk/mkdocs-material/releases/tag/4.4.1) update of the MkDocs-Material theme, the ability to select `black` as the primary color for a theme was added. However, when you select `black` as the primary color for a theme it doesn't change the color of links. If you select any other color as the primary color, the color of links changes to that color.

### Expected behavior

The top navigation bar and all links are black.

### Actual behavior

The top navigation bar is black but links display in the default purple.

### Steps to reproduce the bug

1. Open the `mkdocs.yml` file.
2. Change the `palette: primary:` value to black
3. Open the project folder in a command-line tool.
4. Run the `mkdocs serve` command.

### Package versions

* Python: 2.7.10
* MkDocs: 1.0.4
* Material: 4.4.1

### Project configuration

``` yaml
  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: black
    accent: orange
```
