### ISSUE TITLE
Tabs not available for small screen

### ISSUE THREAD

**Issue by root-ansh** [squidfunk/mkdocs-material#1255]
## Description  

I have 2 tabs in my website. but on changing size of laptop window to a smaller one, it doesn't show 2nd tab or its content. I was hoping that it would show as a collapsed menu item in the navigation drawer that appears for smaller sizes. Attaching some screenshots:   

website  screen, small size:  
![image](https://user-images.githubusercontent.com/31290636/64914568-745ce780-d772-11e9-81ad-0c9bf64c34a9.png)  

![image](https://user-images.githubusercontent.com/31290636/64914572-93f41000-d772-11e9-827c-f103b7f21c4e.png)

website, full screen:  
![image](https://user-images.githubusercontent.com/31290636/64914576-aa01d080-d772-11e9-83a4-9f10c3fe3fd7.png)

Browser: Opera v64.0.3417.11

### Expected behavior  
 tab items would show as a collapsed menu item in the navigation drawer that appears for smaller size devices.

### Actual behavior

![image](https://user-images.githubusercontent.com/31290636/64914568-745ce780-d772-11e9-81ad-0c9bf64c34a9.png)  

### Package versions

* Python: `3.7`
* MkDocs: `1.0.4`
* Material: `v4.4.2`

### Project configuration

``` yaml
site_name: My Test Website # Website name(comes on top left in nav bar)
site_description: Welcome to my test website! #browser tab tooltip text
site_author: Ansh Sachdeva(root-ansh) #don't know where does it show


#Header
repo_name: 'root-ansh/curioustools'
repo_url: 'https://github.com/root-ansh/curioustools'
# Tabs are generated automatically using nav's topmost division and theme's  extras -tabs: true feature

#Footer
extra:
  social:
    - type: 'github'
      link: 'https://github.com/...'
    - type: 'twitter'
      link: 'https://twitter.com/...'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/,,,/'

copyright: Copyright &copy; 2019 <a href="https://www.linkedin.com/in/.../">Ansh Sachdeva</a>

#Theming
theme:
    name: material
    palette:
        primary: 'white'
        accent: 'green'
        #links_color : 'green' #todo, this is not the correct solution
        
    logo: images/logo.svg
    favicon: 'assets/images/favicon.ico'

    feature:
        tabs: true    

    language: 'en'    
    extra:
        search:
            language: 'en'
            tokenizer: '[\s\-\.]+'
    
nav:
    - Welcome:
        - index.md
    - Basics:
        - basic_syntax.md

```

### System information

* OS: [The operating system you're running]
* Browser: [The browser used, if relevant]

**Comment by root-ansh** [comment]
whoops, i just saw pressing the arrow shows us the collapsed  tabs in the way that i want:  
![image](https://user-images.githubusercontent.com/31290636/64914685-d10cd200-d773-11e9-93b8-e93a80d77a9d.png)
 Kinda feel like a bad solution,  some user opening my website and not able to see all tabs at one go, and needs to  press an un-intuitive back button(which would equate to "closing of the site" in user's mind).  

Can something be done to show tabs as  and not that arrow screen?

**Comment by squidfunk** [comment]
The back arrow drawer you‘re referring to is the current layer of navigation. It cannot be shown without fundamentally altering the mechanics of the navigation as it mirrors the expanded state/active on desktop.

However, you're the first person that finds this to be unclear since this mechanic was introduced 2,5 years ago.

**Comment by squidfunk** [comment]
What you could do: put all pages of the first tab on the first level. This is exactly the way it is implemented in the official documentation.

The way navigation and the tabs feature works across resolutions may not be perfect for all use cases but it should be a reasonable default and it’s also limited to how what MkDocs allows to be configured. Furthermore, tabs were introduced later.

**Comment by root-ansh** [comment]
> What you could   
do: put all pages of the first tab on the first level. This is exactly the way it is implemented in the official documentation.

Sorry , i did not understand what you are trying to say.   My current nav structure is this :  
```
nav:
    - Welcome:
        - index.md
    - Basics:
        - basic_syntax.md
```
What can i do to make it more intuitive?  

Also, apologies if i sound rude in my previous comments. I hadn't slept the whole night before. This is a great project of yours and am thankful for this awesome theme!
