### ISSUE TITLE
Search in Russian doesn't work

### ISSUE THREAD

**Issue by sprnza** [squidfunk/mkdocs-material#1287]
I try to configure search language like this:
```
theme:
  name: 'material'
  feature:
    tabs: true
plugins:
  - search:
      lang: ["ru", "en"]
``` 
It works using clear `mkdocs` command installed via pip, but doesn't work using `squidfunk/mkdocs-material` docker image. Search works in English only.
