### ISSUE TITLE
.gif animations are not showing

### ISSUE THREAD

**Issue by Datseris** [squidfunk/mkdocs-material#129]
## Description

A url link to a gif animation is does not show the .gif (i.e. animation) in the compilation of the markdown files.

### Steps to reproduce the bug

1. Go to the documentation page I am mentioning: https://datseris.github.io/DynamicalBilliards.jl/latest/
2. See that instead of a .gif animation showing, there is the text only "Example of a dynamical bill..."
3. The syntax I used to link the gif is: ! [Example of a dynamical billiard with magnetic field] (https://github.com/Datseris/DynamicalBilliardsFigures/blob/master/gifs/plot_example.gif "Evolution of particle in a magnetic field.") , but remove the whitespaces between ! and [] and  ()
4. This syntax works when viewing the github markdown file (the animation is shown)

### Package versions
Did a new installation this week, so probably latest version.

### Project configuration

``` yaml
site_name:           DynamicalBilliards
repo_url:            https://github.com/Datseris/DynamicalBilliards.jl
site_description:    An easy-to-use, modular and extendable Julia package for Dynamical Billiard systems in two dimensions. 
site_author:         George Datseris
theme:               'material'

extra:
  palette:
    primary: 'indigo'
    accent: 'light blue'
  social:
    - type: 'github'
      link: 'https://github.com/Datseris/DynamicalBilliards.jl'
 
markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Introduction: index.md
- Basic Usage: basic/basic_usage.md
- Tutorials:
  - Defining a Billiard Table: tutorials/billiard_table.md
  - Ray-Splitting: tutorials/ray-splitting.md
  - Creating your own Obstacle: tutorials/own_obstacle.md
  - Examples: tutorials/examples.md
- Library: basic/library.md
```
