### ISSUE TITLE
Fixed meta title and description only rendering first character

### ISSUE THREAD

**Issue by StephenTaylor-Kx** [squidfunk/mkdocs-material#1324]
As for #553 and #554 but for `author`

##  Description

    ---
    author: John Doe
    ---

### Expected behavior

    <meta name="author" content="John Doe">

### Actual behavior

    <meta name="author" content="J">

### Steps to reproduce the bug

1. Default MkDocs instance
2. Metadata in `index.md` as shown
3. `mkdocs serve`

### Package versions

* Python: 2.7.10
* MkDocs: 1.0.4
* Material: 4.0.2

### Project configuration

``` yaml
#  MkDocs sandbox for testing features
dev_addr: '0.0.0.0:8009'
site_name: Sandbox
```

### System information

* OS: macOS 10.14.6
* Browser: Chrome 77.0.3865.120 (Official Build) (64-bit)
