### ISSUE TITLE
TOC only for 2 levels

### ISSUE THREAD

**Issue by poturnak** [squidfunk/mkdocs-material#136]
Wanted to ask your help in understanding how I can customize materials these to generate TOC only for 2 levels. Thanks!

**Comment by facelessuser** [comment]
You can do this with CSS if needed.  I believe this should hide TOC entries of 3 or greater.  You would add the CSS in some additional CSS via the MkDocs `extra_css` [option](http://squidfunk.github.io/mkdocs-material/customization/#additional-stylesheets).

```css
label[for="toc"]+.md-nav__list .md-nav__list .md-nav__list {
    display: none;
}
```
