### ISSUE TITLE
how to solve: UndefinedError: 'page' is undefined

### ISSUE THREAD

**Issue by MagicCarpetPilot** [squidfunk/mkdocs-material#137]
Hi

When I try to use _theme: 'material'_ mkdocs stops with the error _'page is undefined'_. Could this be a problem with the version of mkdocs?

Thank you for any tip

### Versions

Python Version: 2.7.10
mkdocs Version: 0.15.3
Material Version: 1.0.3

### OS

Mac OS Sierra (10.12.2)

### Project configuration

``` yaml
site_name: 'DB docs'
theme: 'material'
site_description: 'database docs'
pages:
```
