### ISSUE TITLE
google font url broken

### ISSUE THREAD

**Issue by tsraza** [squidfunk/mkdocs-material#1376]
## Description

The generated url for custom google font doesn't point to a valid endpoint

https://fonts.googleapis.com/css?family=:300,400,400i,700|Source+Code+Pro&display=fallback

The colon (`:`) in the family parameter should not be there

The following url is valid

https://fonts.googleapis.com/css?family=300,400,400i,700|Source+Code+Pro&display=fallback

### Expected behavior

Load the font css from fonts.googleapis.com

### Actual behavior

Get a 400 response

### Steps to reproduce the bug

include the following font config in `mkdocs.yml`

```yaml
theme:
  name: material
  font:
    code: Source Code Pro
```

### Package versions

* Python: Python 3.6.8
* MkDocs: mkdocs, version 1.0.4
* Material: Version: 4.5.1

### Project configuration

minimal

``` yaml
site_name: test

theme:
  name: material
  font:
    code: Source Code Pro
```

### System information

* OS: windows
* Browser: any

**Comment by Stanzilla** [comment]
But `https://fonts.googleapis.com/css?family=Source+Code+Pro:300,400,400i,700&display=fallback` works as well.

**Comment by tsraza** [comment]
@Stanzilla Yep, thats it.  It needs a `text` font entry to fill the missing gap

```yaml
theme:
  name: material
  font:
    text: Roboto
    code: Source Code Pro
```
