### ISSUE TITLE
[Markdown Extensions] - mkdocs.yml could not be loaded

### ISSUE THREAD

**Issue by francis-du** [squidfunk/mkdocs-material#1414]
## Description:

When I configure pymdownx.emoji and then go to Readthedocs to build the documentation, it will report an error,but works fine locally.

`Your mkdocs.yml could not be loaded, possibly due to a syntax error (line 75, column 24)`

## Dependencies and versions
```txt
mkdocs==1.0.4
mkdocs-material==4.6.0
Pygments==2.2.0
pymdown-extensions==6.2.1
mkdocs-git-revision-date-localized-plugin==0.4.5
```

## mkdocs.yml configuration

```yml
markdown_extensions:
  - admonition
  - codehilite
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      emoji_index: !!python/name:pymdownx.emoji.twemoji
```

## Python Version==3.7
