### ISSUE TITLE
PHP Code Highlights Only work when there is PHP Opening Exist

### ISSUE THREAD

**Issue by semplon** [squidfunk/mkdocs-material#1417]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [ ] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

This problem happen when i highlight codes without PHP Opening tags. But when I Add PHP Opening tags the problem is not happen. 
When i highlights php code without opening tag, the code highlighted correctly, but when there is no php opening tag the code not highlighted quite rights. only black color text. 

### Expected behavior

the highlighted color should be same as when there is php opening tag exist. 

![image](https://user-images.githubusercontent.com/3163608/71800705-5bfb3a80-308b-11ea-83fa-14face85550f.png)
``` php
$pubs = array();
```
### Actual behavior

the highlighted color is only black. 
![image](https://user-images.githubusercontent.com/3163608/71800672-438b2000-308b-11ea-97dd-1a8d7de7693b.png)

### Steps to reproduce the bug

1. write simple code with ``` php ```

### Package versions

* Python: `python --version` **3.7.3**
* MkDocs: `mkdocs --version` **1.0.4**
* Material: `pip show mkdocs-material | grep -E ^Version` **4.6.0**

### Project configuration

``` yaml
# Project information
site_name: AGCPress Docs
site_description: Documentation of AGC Press Ebook
site_author: MetalGenix
site_url: https://metalgenix.com/

# Repository
repo_name: semplon/agcpress-docs
repo_url: https://github.com/semplon/agcpress-docs
edit_uri: ""

# edit_uri: edit/docs-revamp/docs/
# edit_uri: blob/docs-revamp/docs/

# remote_name: origin
# remote_branch: gh-pages

# Theme and overrides, i.e. language partial
theme:
  name: material

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  # favicon: images/favicon.ico
  # logo: images/logo.svg

# Copyright
copyright: "Copyright &copy; 2020 MetalGenix"

# Options
extra:
  search:
    languages: "en"
  social:
    - type: globe
      link: https://metalgenix.com/
    - type: github-alt
      link: https://github.com/semplon
    - type: twitter
      link: https://twitter.com/metalgenix

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - AGC Press: index.md
  - License: license.md
  - Configuration: configuration.md
  - Setting Webserver: webserver.md
  
```

### System information

* OS: Windows 10
* Browser: Google Chrome
