### ISSUE TITLE
Exception when setting only logo icon in 5.0.0rc1

### ISSUE THREAD

**Issue by frankie567** [squidfunk/mkdocs-material#1503]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

In the configuration, when specifying a custom icon as `logo`, but not a custom `repo` icon, a `jinja2.exceptions.TemplateNotFound` is raised.

### Expected behavior

The `logo` icon should be set, and the `repo` icon should fallback to the default.

### Actual behavior

A `jinja2.exceptions.TemplateNotFound` is raised. As a workaround, we can set the `repo` icon the configuration.

### Steps to reproduce the bug

1. Start a mkdocs-material project
2. Set this in the theme configuration:

```yaml
theme:
  name: 'material'
  icon:
    logo: fontawesome/solid/microphone
```
3. Run `mkdocs serve`

### Package versions

* Python: 3.7.5
* MkDocs: 1.1
* Material:  5.0.0rc1

### Project configuration

``` yaml
site_name: FastAPI Users
site_description: Ready-to-use and customizable users management for FastAPI

theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'red'
  icon:
    logo: fontawesome/solid/microphone
  favicon: 'favicon.png'

repo_name: frankie567/fastapi-users
repo_url: https://github.com/frankie567/fastapi-users
edit_uri: ""

markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tasklist
```

### System information

* OS: macOS 10.15.2
* Browser: Chrome 80
