### ISSUE TITLE
Instant loading scroll restoration

### ISSUE THREAD

**Issue by ofek** [squidfunk/mkdocs-material#1507]
## Description

Page refreshes do not keep your place but rather take you to the top in v5.x with the following config:

```yaml
theme:
  name: material
  features:
    - instant
```

### Expected behavior

Pressing F5 should maintain your approximate spot on the page

### Actual behavior

Pressing F5 (without an anchor selected) takes you to the top

### Steps to reproduce the bug

1. Scroll down
2. Refresh
3. Notice your view resets

### Package versions

* Python: 3.8
* MkDocs: 1.1
* Material: 5.0.0rc2

### Project configuration

``` yaml
theme:
  name: material
  features:
    - instant
```

### System information

* OS: Windows 10
* Browser: Chrome
