### ISSUE TITLE
HTML issue: attribute "autocomplete" not allowed on checkboxes

### ISSUE THREAD

**Issue by jaimeiniesta** [squidfunk/mkdocs-material#1513]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

The template in MkDocs 5.0.0 RC 2 uses 2 checkboxes at the beginning of the body:

```
<input class="md-toggle" data-md-toggle="drawer" type="checkbox" id="__drawer" autocomplete="off">
<input class="md-toggle" data-md-toggle="search" type="checkbox" id="__search" autocomplete="off">
```

### Expected behavior

No HTML issues found by the W3C validator.

### Actual behavior

W3C validator complains that `autocomplete="off"` is not allowed for `checkbox`:

```
Error: Attribute autocomplete is only allowed when the input type is color, date, datetime-local, email, hidden, month, number, password, range, search, tel, text, time, url, or week.
```

### Steps to reproduce the bug

Go to https://validator.nu/ and check a site using the template, or just this simple HTML document:

```html
<!DOCTYPE html>
<html>
<head>
<title>Test</title>
</head>
<body>
<form>
<input class="md-toggle" data-md-toggle="drawer" type="checkbox" id="__drawer" autocomplete="off">
</form>
</body>
</html>
```

### Package versions

* Python: 3.7.7
* MkDocs: 1.1
* Material: 5.0.0rc2

### Project configuration

``` yaml
site_name: Rocket Validator Documentation
nav:
    - Home: index.md
    - API: api.md
theme:
  name: material
  language: en
  features:
    - instant
  logo: img/rocket-icon-300x300.png
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/rocketvalidator
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rocketvalidator
    - icon: fontawesome/brands/linkedin
      link: https://pr.linkedin.com/company/rocket-validator
google_analytics:
  - UA-81204018-1
  - auto
markdown_extensions:
- admonition
- pymdownx.superfences
- codehilite:
    guess_lang: false
extra_css:
    - css/extra.css
```

### System information

* OS: macOS 10.15.3
* Browser: Chrome 80
