### ISSUE TITLE
Return link of footnote not show after convert to pdf

### ISSUE THREAD

**Issue by lisongmin** [squidfunk/mkdocs-material#1515]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

return link of footnote not show after convert to pdf. It may be a css issue, 
but I don't known how to fix it.

![2020-03-17T23-34-06-screenshot](https://user-images.githubusercontent.com/2513062/76875740-ee019980-68ab-11ea-984d-39959724d4c4.png)

### Expected behavior

The return link should show in pdf.

### Steps to reproduce the bug

1. mkdocs build
2. open site/pdf/combined.pdf

### Package versions

* Python: 3.8.0
* MkDocs: 1.1
* Material: 4.6.3
* mkdocs-export-pdf-plugin: master branch

### Project configuration

``` yaml
---
site_name: test

theme:
    name: material
    font: false

markdown_extensions:
    - footnotes
    - toc:
          slugify: !!python/name:pymdownx.slugs.uslugify

plugins:
    - pdf-export:
          combined: true

nav:
    - test.md
```

test.md 

```
Footnotes[^1] have a label[^@#$%] and the footnote's content.

[^1]: This is a footnote content.
[^@#$%]: A footnote on the label: "@#$%".

```

### System information

* OS: archlinux
* Browser: firefox
