### ISSUE TITLE
Is there a way to pre-download fonts for offline usage

### ISSUE THREAD

**Issue by nelsg** [squidfunk/mkdocs-material#152]
## Description

Is there a way to pre-download fonts for offline usage

### Expected behavior

I generate and serve on a offline server, it trying to download fonts on https://fonts.gstatic.com.
Is there a way to put used font files in a `extra_css` path ?

### Actual behavior

Fonts (and icons) are not used

### Steps to reproduce the bug

I think, switch off you internet connection an try to build/serve

### Package versions

* Python: 2.7.12
* MkDocs: 0.16.1
* Material: 1.0.3

### Project configuration

``` yaml
# ... hidden ...

theme: material

# Options
extra:
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'


# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
 ```

### System information

* OS: Ubuntu 16.04
* Browser: Firefox 51.0.1 (64 bits)
