### ISSUE TITLE
Search bar not working

### ISSUE THREAD

**Issue by RanVargas** [squidfunk/mkdocs-material#1546]
__I checked that...__

- [x ] ... the problem doesn't occur with the default MkDocs template
- [x ] ... the problem is not in any of my customizations (CSS, JS, template)

## Description

When deployed the search bar of the project doesnt work.
### Expected behavior

The search bar should come up with results of something searched.

### Actual behavior

Nothing comes up when anything typed.

### Steps to reproduce the bug

Deploy the project, go to the website and search for something

### Package versions

* Python: `python --version 3.6`
* MkDocs: `mkdocs --version 1.1`
* Material: `pip show mkdocs-material | 4.6`

### Project configuration

my mkdocs.yml text is below:

```
# Project information
site_name: Documentation
site_url: 
site_description: 
site_author: 



# Repository
repo_name: 
repo_url: 



# Copyright
copyright: 'Copyright &copy; 2019 - 2020 Consorcio de Tarjetas Dominicana (CardNET)'



# Configuration
theme:
  favicon: 'assets/images/favicon.png'
  name: null
  custom_dir: 'docs/assets/material'
  logo:
    icon: 'view_quilt'
    
# Don't include MKDocs javascript
  include_search_page: false
  search_index_only: true

  # 404 page
  static_templates:
    - 404.html


  palette:
    primary: 'cyan'
    accent: 'grey'
  font:
    text: 'Montserrat Light'
    code: 'Roboto Mono'
    highlightjs: true
    hljs_languages:
      - yaml
      - django
      - JavaScript
      - Python
      - Java
      - Ruby
      - Php
      - C++
      - SQL
      - C#
      - Go
      - C
      - TypeScript
      - Swift

  language: 'es'
  feature:
    tabs: true


# Customization
extra:
  social:
    - type: 'code-fork'
      link: 
    # - type: 'linkedin'
    #   link: 
    # - type: 'instagram'
    #   link: 
    # - type: 'twitter'
    #   link: 
  global:
    version: 1.0.6


# Navigation
nav:
    pages


plugins:
    - search
    - minify:
        minify_html: true
        minify_js: true
    - markdownextradata: {}
    


# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - meta
```
