### ISSUE TITLE
Incorrect height of AppBar header

### ISSUE THREAD

**Issue by JasMich** [squidfunk/mkdocs-material#1547]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

The `header` has a size of `2.4rem`. This translates into 48px on standard devices. According to the material design guidelines it should be `56px` which is equal to `2.8rem`. Source: https://material.io/components/app-bars-top/#specs

### Expected behavior

A `header` height of `56px`

### Actual behavior

A `header` height of `48px`

### Fixing CSS

This can be fixed by changing the corresponding CSS files to:

```css
.md-header {
    height: 2.8rem;
}

.md-header-nav {
    padding: .2rem;
}

@media only screen and (max-width:59.9375em) {
    .md-search__input {
        height: 2.8rem;
    }
    .md-search__icon[for="__search"] {
        top: .8rem;
    }
    .md-search__icon[type="reset"] {
        top: .8rem;
    }
}
```

### Steps to reproduce the bug

*Bug by default*

### Package versions

* Python: `Python 3.8.2`
* MkDocs: `mkdocs, version 1.1 from $PREFIX/lib/python3.8/site-packages/mkdocs (Python 3.8)`
* Material: `Version: 4.6.3`

### Project configuration

``` yaml
theme: 
  name: material
  palette:
    primary: light blue
    accent: green
  font: false
  feature:
    tabs: true
plugins:
  - search
```

### System information

* OS: Tested on FreeBSD, macOS, Linux 5.6, Android, Windows XP
* Browser: Tested on various browsers

**Comment by squidfunk** [comment]
At some point we decided that `48px` looks better than `56px`. No reason to follow the Material guidelines religiously 😊 if you want to debit to `56px`, you can do it with extra CSS, see the customization guide.

**Comment by squidfunk** [comment]
... so basically you answered your own question.

**Comment by JasMich** [comment]
Ah, okay. I thought you didn't know... Anyway, as a little hint. I agree on desktops `48px` looks better but on mobile devices you did much better using `56px` as the size of the AppBar mey be much more touch-friendly then.

```quote
if you want to set it to 56px, you can do it with extra CSS, see the customization guide.
```

I did. I just wanted to share it to other people who are that religious about Material Design as I am...

**Comment by squidfunk** [comment]
It’s always a matter of taste. This project has so many users - regardless of what you set the values to, there‘ll always be people objecting to them. Visual stuff is always opinionated. Thanks for providing your solution to anyone who wants to set it to that  value!

**Comment by JasMich** [comment]
@squidfunk Would you merge a merge request offering a setting like
```yaml
- theme:
   [...]
   - strictly-follow-material-guidelines: (true|false)
```
providing this change and any other possible inaccurate implementation of the Material.io specs?
