### ISSUE TITLE
5.0.0rc4: inline code containing embeded links doesn't render link color

### ISSUE THREAD

**Issue by Andre601** [squidfunk/mkdocs-material#1559]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description
When you create a inline code text, which also has an embeded link (``[`google`](https://google.com)``) does the theme not render this properly and show the text just as inline code (`google`) rather than inline code with a link ([`google`](https://google.com))

Images:

MkDocs Theme:
![image](https://user-images.githubusercontent.com/11576465/78307504-57d5a080-7546-11ea-98cb-a625b78d94da.png)

Material Theme:
![image](https://user-images.githubusercontent.com/11576465/78307555-78055f80-7546-11ea-9ba9-6d9227349cf2.png)

### Expected behavior
The text should have a visual indication (link color) even when being a inline code

### Actual behavior
Text displays as normal inline code without any visual indicator of it having a link.

### Steps to reproduce the bug

1. Create a text that is both inline code and has a link (``[`text`](link)``)
2. Serve or build the page using mkdocs

### Package versions

* Python: `3.7.6`
* MkDocs: `1.1`
* Material: `5.0.0rc4`

### Project configuration

``` yaml
site_name: MySite
site_description: 'My little MkDocs site'
site_author: 'Andre_601'

docs_dir: docs/

nav:
  - Welcome: index.md

theme:
  name: 'mkdocs'
  logo: 'assets/img/logo.png'
  favicon: 'assets/img/logo.png'
  palette:
    primary: 'cyan'
    accent: 'blue'
  features:
  - tabs
```

### System information

* OS: Windows 10 Pro
* Browser: Chrome 80.0.3987.162 (64-Bit)
