### ISSUE TITLE
Syntax highlight not working

### ISSUE THREAD

**Issue by Tejes** [squidfunk/mkdocs-material#156]
## Description

Using this theme, syntax highlight (for Java) is not working. If I switch to mkdocs or readthedocs theme, it is working. Adding codehilite(guess_lang=false) markdown extension does not solve it.

### Steps to reproduce the bug

1. Create a new project
2. Put a java code block in it
3. Serve

### Package versions

* Python: 3.4.3
* MkDocs: 0.16.1
* Material: 1.0.3

### Project configuration

``` yaml
site_name: Programozás I. gyakorlat
theme: material
pages:
    - 'Kezdőlap': index.md
    - 'Java telepítése': telepites.md
    - '0 .gyakorlat': gyak0.md
    - '1 .gyakorlat': gyak1.md
    - '2 .gyakorlat': gyak2.md
    - '3 .gyakorlat': gyak3.md
    - '4 .gyakorlat': gyak4.md
    - '5 .gyakorlat': gyak5.md
    - '6 .gyakorlat': gyak6.md
    - '7 .gyakorlat': gyak7.md
    - '8 .gyakorlat': gyak8.md
    - '9 .gyakorlat': gyak9.md
    - '10 .gyakorlat': gyak10.md
    - '11 .gyakorlat': gyak11.md
    - '12 .gyakorlat': gyak12.md
    - '13 .gyakorlat': gyak13.md
    - '14 .gyakorlat': gyak14.md
extra:
  palette:
    primary: 'Light Green'
    accent: 'Lime'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
extra_css:
    - css/extra.css
```

### System information

* OS: Windows 7 SP1
* Browser: Firefox 51

**Comment by squidfunk** [comment]
Did you install pygments? http://squidfunk.github.io/mkdocs-material/extensions/codehilite/#installation

**Comment by Tejes** [comment]
Well, no. But it isn't stated in the linked document, that I should've. The other themes work without it. Material does not?

**Comment by gaborantal** [comment]
I had the same issue. After installing pygments, mkdocs serve command is not working for me anymore. 

```
G:\abc>mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory
[I 170215 12:16:43 server:283] Serving on http://127.0.0.1:8000
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\mkdocs.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\mkdocs\__main__.py", line 131, in serve_command
    raise SystemExit('\n' + str(e))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf6 in position 17: ordinal not in range(128)
```

**Comment by squidfunk** [comment]
> Well, no. But it isn't stated in the linked document, that I should've. The other themes work without it. Material does not?

It is stated the linked document:

> CodeHilite parses code blocks and wraps them in `<pre>` tags. If Pygments is installed, which is a generic syntax highlighter with support for over 300 languages, CodeHilite will also highlight the code block.

Material uses Pygments for syntax highlighting by default, as its rendered on the server. This ensures it works without JavaScript. Other themes may use Highlight.js or some other JavaScript-based syntax highlighter. If you have a problem with MkDocs and Pygments, please post it on the MkDocs issue tracker. If you wish to include Highlight.js, you can easily do it with `extra_css`:
http://squidfunk.github.io/mkdocs-material/customization/#additional-javascript

**Comment by Tejes** [comment]
Installing pygments solved the problem, thank you.
By reading the installation docs, it wasn't clear for me, that this is **required** for syntax highlight to work, as it isn't for other themes. I suggest clarifying this different behavior, right on the installation page.

**Comment by squidfunk** [comment]
> By reading the installation docs, it wasn't clear for me, that this is **required** for syntax highlight to work, as it isn't for other themes.

I will add notice.

**Comment by pplonski** [comment]
It was hard for me to find that I need to add `codehilite` in the config file to make highlight work:

```
markdown_extensions:
    - pymdownx.highlight:
        use_pygments: true
    - codehilite
```

Thank you for amazing docs framework!

**Comment by squidfunk** [comment]
@pplonski that shouldn't be necessary. In fact, we don't have `codehilite` in the official docs, only `highlight`:

https://github.com/squidfunk/mkdocs-material/blob/0c40b0a46c5456db261d933091c4a43b960c089d/mkdocs.yml#L104-L141

**Comment by aogier** [comment]
Hi, can confirm that without codehilite there's no code highlighting on a fresh install...

config file:

```yaml
site_name: blah
theme:
  name: material

markdown_extensions:
  - codehilite
  - pymdownx.highlight:
      use_pygments: true

```
