### ISSUE TITLE
No edit icons in Readthedocs.

### ISSUE THREAD

**Issue by hktkzyx** [squidfunk/mkdocs-material#1562]
## Description

No edit icon when the file is built in readthedocs but it is okay when it is built in my computer.

### Package versions

* Python: 3.8.0
* MkDocs: 1.1
* Material: 4.6.3

### Project configuration

```yaml
# Project information
site_name: Auto Depreciation Plugin
site_description: A Beancount plugin for fixed assets depreciation
site_author: hktkzyx
site_url: 'https://auto-depreciation.readthedocs.io/'

# Repository
repo_name: hktkzyx/auto_depreciation
repo_url: 'https://github.com/hktkzyx/auto_depreciation'

# Configuration
nav:
  - Introduction: index.md
  - Depreciation Methods: methods.md
theme: 
  name: material
  
# Extensions
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.b64
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
```
