### ISSUE TITLE
favicon won't work

### ISSUE THREAD

**Issue by Amber1990Zhang** [squidfunk/mkdocs-material#1568]
## Description

I set `favicon` but it won't work.
### Expected behavior

Show the favicon on my site.
### Actual behavior

Nothing shows.
### Steps to reproduce the bug
my site [repo](https://github.com/vesoft-inc/nebula-docs)

### Package versions

* Python: `3.7.3`
* MkDocs: `1.1`
* Material: `4.6.3`

### Project configuration

``` yaml
...
theme:
  name: 'material'
  logo:
    icon: library_books
  favicon: 'assets/images/favicon.ico'
...
```

### System information

* OS: mac
* Browser: Chrome
