### ISSUE TITLE
Code blocks with new pymdownx.tabbed not rendering

### ISSUE THREAD

**Issue by rcastley** [squidfunk/mkdocs-material#1581]
## Description

Using the new `pymdownx.tabbed` extension in v5.0.1 with code blocks is not rendering correctly like it did using superfences. 
### Expected behavior

Using the following markdown:

````
=== "Input"
    ``` bash
    kubectl get pods
    ```

=== "Output"
    ```
    NAME                   READY   STATUS    RESTARTS   AGE
    signalfx-agent-66tvr   1/1     Running   0          7s
    ```
````
### Actual behavior

The above markdown generates the following HTML

```

<div class="tabbed-set" data-tabs="2:2"><input checked="checked" id="__tabbed_2_1" name="__tabbed_2" type="radio" /><label for="__tabbed_2_1">Input</label><div class="tabbed-content">
--
  | <p><code>bash
  | kubectl get pods</code></p>
  | </div>
  | <input id="__tabbed_2_2" name="__tabbed_2" type="radio" /><label for="__tabbed_2_2">Output</label><div class="tabbed-content">
  | <p><code>NAME                   READY   STATUS    RESTARTS   AGE
  | signalfx-agent-66tvr   1/1     Running   0          7s</code></p>
  | </div>
  | </div>

```

### Steps to reproduce the bug

Upgraded to 5.0.1 along with all required depenancies 

### Package versions

* Python: 3.6.9
* MkDocs: 1.1
* Material: 5.0.1

**requirements.txt**
```
markdown>=3.2
mkdocs>=1.1
mkdocs-git-revision-date-localized-plugin>=0.5.0
mkdocs-material>=5.0.1
pymdown-extensions>=7.0.0
Pygments>=2.4
```

### Project configuration

``` yaml
site_name: 'App Dev Workshop'
...
edit_uri: 'edit/master/docs/modules/'
remote_branch: gh-pages
docs_dir: modules
theme:
  name: material
  palette:
    primary: 'black'
  favicon: 'images/favicon.ico'
  logo: images/logo.png
  font:
    text: Roboto
    code: Roboto Mono
  include_search_page: false
  search_index_only: true
  language: en

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.mark

extra_css:
  - "extra.css"

plugins:
  - git-revision-date-localized:
      type: datetime
      locale: en
  - search
  
nav:
  - Overview: index.md
  ...
  - 'Post Workshop Clean Up!': module-support/cleanup.md

```

### System information

* OS: Mac OS
* Browser: Brave/Chrome

Many thanks :-)

**Comment by rcastley** [comment]
Live URL - https://signalfx.github.io/app-dev-workshop/module-support/cleanup/

**Comment by rcastley** [comment]
Closing this as adding `pymdownx.superfences` back in fixes it, sorry!

**Comment by rcastley** [comment]
Closing

**Comment by squidfunk** [comment]
https://facelessuser.github.io/pymdown-extensions/about/release/#upgrading-to-70

**Comment by larsclaussen** [comment]
I have the same issue.  My config looks like this

```
theme:
    name: material
    features:
        - navigation.expand
    palette:
        primary: 'light green'
        accent: 'green'
    custom_dir: pub_docs/

repo_name: API/V3.0
repo_url: hhttps://api.3di.live/v3.0/swagger/
docs_dir: pub_docs


markdown_extensions:
    - markdown.extensions.codehilite:
        guess_lang: false
    - markdown_include.include:
        base_path: pub_docs
    - toc:
        permalink: 💡
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tabbed
    - pymdownx.superfences
    - admonition
    - codehilite
    - extra
    - attr_list
```

The tabbed code blocks are always prefixed with language identifier, pretty much same as described by @rcastley 

Here is the html it produces

```
</div>
<input id="__tabbed_1_2" name="__tabbed_1" type="radio" /><label for="__tabbed_1_2">C++</label><div class="tabbed-content">
<p>``` c++</p>
<h1 id="include_1">include <iostream><a class="headerlink" href="#include_1" title="Permanent link">💡</a></h1>
<p>int main(void) {
  std::cout &lt;&lt; "Hello world!" &lt;&lt; std::endl;
  return 0;
}
```</p>
</div>
``` 
pymdown-extensions version is 8.0.1. 
I run python 3.8. 

I also tried downgrading `pymdown-extensions` to 7.0 and 7.1.
Please let me know we you need additional information.

**Comment by squidfunk** [comment]
Please provide a minimum reproducible example including the Markdown you use to render the HTML you posted.

**Comment by larsclaussen** [comment]
Ok, I [cloned](https://github.com/larsclaussen/tmp-api-user-guide) the original repo and stripped it down to the bare minimum. This should make it fairly easy for you to reproduce.
    
    git clone git@github.com:larsclaussen/tmp-api-user-guide.git

Create a virtual environment using python +3.7
    
     pip3 install -r requirements.txt
     cd docs
     mkdocs serve

Please let me know if need anything else. Thanks in advance for having a look.

**Comment by larsclaussen** [comment]
@squidfunk I was wondering if you were able to reproduce the issue? If not, can I assist in any other way? Thx!

**Comment by squidfunk** [comment]
I'm so sorry – I haven't had the time to investigate. I currently only have time to work on this project on weekends and have a very long list of bug fixes and features. Maybe someone else can chime in to help you.

**Comment by larsclaussen** [comment]
Ok no worries. I'll come up with a workaround for now. Keep up the good work! Cheers

**Comment by facelessuser** [comment]
I may be able to take a look sometime soon. I'll let you know if/when I do.

**Comment by facelessuser** [comment]
@larsclaussen I finally had a chance to look at your issue. There are a couple of things to note.

1. In case you are under any illusions, SuperFences does not depend on CodeHilite. It uses it's own highlight plugin `pymdownx.highlight`. You don't normally need to specify it when using SuperFences unless you need to change something global from the default. This isn't causing issues, but something to note.

2. You specify `codehilte` twice. You should only include an extension once, but still, this isn't your issue.

3. You include `extra`, this is the issue. `extra` includes a number of extensions in one shot. The problem is that it includes extensions that are incompatible with some `pymdownx` extensions. This is documented here: https://facelessuser.github.io/pymdown-extensions/usage_notes/#incompatible-extensions.  I would personally just include the extensions you need one by one, but if you want/need to include them all in one shot, I would use [`pymdownx.extra`](https://facelessuser.github.io/pymdown-extensions/extensions/extra/) instead.

So, in the repo you provided, I fixed your issue by using these settings:

```yaml
markdown_extensions:
    - toc:
        permalink: 💡
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tabbed
    - pymdownx.superfences
    - admonition
    - attr_list
```

If you'd like to include extensions from `extra`, I would use the ones that are compatible with `pymdownx` and use `pymdownx` alternatives for those that are not compatible.
