### ISSUE TITLE
TOC renders <> as &lt; and &gt; when using inline code

### ISSUE THREAD

**Issue by Andre601** [squidfunk/mkdocs-material#1607]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description
When using the `<` and `>` characters in headers with inline code (i.e. `` `My <example>` ``) will the characters be rendered as `&lt;` and `&gt;` respectively in the TOC.
This does not happen when using plain text and escaping the characters (`My <example\>`)

![image](https://user-images.githubusercontent.com/11576465/79460652-68315500-7ff5-11ea-9c43-6eeb15f41c2d.png)

### Expected behavior
The Characters should be rendered normally in the TOC

### Actual behavior
The characters are rendered as `&lt;` and `&gt;`

### Steps to reproduce the bug

1. Create a new MkDocs project using Material
2. Add a header that uses both inline code and `<>` (f.e. `` `mycmd <argument>` ``
3. Render the page either through `mkdocs build` or `mkdocs serve`

### Package versions

* Python: `3.7`
* MkDocs: `1.1`
* Material: `5.0.0`

### Project configuration

``` yaml
site_name: My Docs

theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'cyan'

nav:
- Welcome: index.md

markdown_extensions:
- toc:
    permalink: true
```

### System information

* OS: Windows 10 Pro
* Browser: Google Chrome
