### ISSUE TITLE
Chrome print function is broken for instant feature, print dialog opens and closes directly

### ISSUE THREAD

**Issue by ayeks** [squidfunk/mkdocs-material#1631]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

With versions 5.0.0, 5.1.0, 5.1.1 the Chrome Browsers print functionality is broken when using the `instant` feature. When you are on a docs page and press Ctrl+P the print dialog opens and closes directly. It works fine in Firefox with these versions.

The print dialog with mkdocs-material version 4.6.3 works fine. Probably because the instant feature has no effect there.

### Expected behavior

Expected behavior is that the print dialog of the browser opens and I can configure the print settings.

### Actual behavior

The print dialog opens and closes instantaneously. The print dialog works on any other side.

### Steps to reproduce the bug

1. Setup a completely new mkdocs project: `mkdocs new my-project`
2. Modify the mkdocs.yml file the following:

```yaml
site_name: My Docs
theme:
  name: material

theme:
  name: 'material'
  language: 'en'
  features:
    - instant
    - tabs
```

3. Run `mkdocs serve` and open the page in your browser.
4. Press `Ctrl+P` and the print dialog should open and close again directly.
5. Use the following mkdocs.yml file instead:

```yaml
site_name: My Docs
theme:
  name: material

theme:
  name: 'material'
  language: 'en'
  features:
    # - instant
    - tabs
```

6. Run `mkdocs serve` and open the page in your browser.
7. Press `Ctrl+P` and the print dialog should open.

### Package versions

* Python: `python --version`

```shell
Python 3.8.2
```

* MkDocs: `mkdocs --version`

```shell
mkdocs, version 1.1 from c:\git\docs\venv\lib\site-packages\mkdocs (Python 3.8)
```

* Material: `pip show mkdocs-material | grep -E ^Version`

```shell
Version: 5.1.1
```

### Project configuration

```yaml
site_name: My Docs
theme:
  name: material

theme:
  name: 'material'
  language: 'en'
  features:
    - instant
    - tabs
```

### System information

* OS: Windows 10
* Browser: Chrome Version 81.0.4044.113 (Offizieller Build) (64-Bit)

### Known Chrome Bug

I found a Chrome bug for that bug description: <https://bugs.chromium.org/p/chromium/issues/detail?id=467976>

> The window.print() followed by window.close() is the same problem reported on the bug linked above.

---

Do you have any idea why this bug exists for the instant feature?
Which additional tests can I perform to narrow down the problem?
