### ISSUE TITLE
CSS for improving images in docs

### ISSUE THREAD

**Issue by rcastley** [squidfunk/mkdocs-material#1635]
Hi,

Just want to say absolutely love this theme and putting it to great use. Whilst we have been developing our docs we have come up with a few CSS tweaks to improve image handling in our docs and just wanted to share them for consideration in including them in a future release.

**Support for:**
* Centering images in the page
* Adding shadow to images
* Adding borders to images
* Adding Zoom features to images

To use e.g. the zoom features just add `#zoom` to the end of the image URL

```
img {
    height: auto;
    width: auto;
    border: 1px solid #9f9f9f;
    transition: transform ease-in-out 0.3s;
}

img[src*="#shadow"] {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
}

img:active[src*="#zoom"] {
    cursor: zoom-out;
    transform: scale(2.0);
}

img[src*="#zoom"] {
    cursor: zoom-in;
}

img[src*="#center"] {
    display: block;
    margin-left: auto;
    margin-right: auto;
}

img[src*="#no-border"] {
    border: 0px;
    width: 200px;
}

a.md-logo img {
    border: none;
}
```

Once again thank you :-)

**Comment by squidfunk** [comment]
Thanks, glad to hear that! 😄Those are some pretty cool hacks! I've never seen this technique, but it makes pretty much sense to me. However, I don't whether all users of the theme want those hacks included by default.

Do you have a public deployment where we can see them in action?

**Comment by rcastley** [comment]
@squidfunk 

Zoom - https://signalfx.github.io/app-dev-workshop/module6/hotrod/ - Step 5 hover over NavBar. Click and hold to zoom

Shadow - https://signalfx.github.io/app-dev-workshop/module2/muting/ - modal dialogs

These could _potentially_ be included in default CSS as they are only activated when you append the image url e.g.

```
Open SignalFx in your browser and select the APM tab to open the APM UI.

![select APM](../images/module6/M6-l1-select-apm.png#zoom)
```

**Comment by facelessuser** [comment]
Why do it with odd source paths?  There is already things like `attr_list` extension which allow you to add classes etc.

```
![zoom image](myimage.png){: .zoom}
```

Then instead of creating CSS that triggers off the path, you could go with a slightly more expected convention of triggering on a class.

**Comment by fveauvy** [comment]
Awesome, thanks a lot !

**Comment by squidfunk** [comment]
I guess we could add some more convenience classes via the `attribute-lists` extension. There's already `.md-button` and `.md-button--primary` which can be added to any link to be rendered as a button and which are used on the landing page, but it's not documented. Somebody can open a new issue for us to collect ideas on what other "components" would be useful besides zooming and buttons. We can then document everything under the `Extensions` tab.

**Comment by squidfunk** [comment]
I'm closing this issue with a lookout what's already possible - let's continue the discussion in a new issue!

``` markdown
[Button](#){ .md-button }
[:fontawesome-brands-github: GitHub](#){ .md-button .md-button--primary }
[:smile: Emojis](#){ .md-button }

!!! Buttons in Admonitions

    [Button](#){ .md-button }
    [:fontawesome-brands-github: GitHub](#){ .md-button .md-button--primary }
    [:smile: Emojis](#){ .md-button }
```

<img width="713" alt="Bildschirmfoto 2020-04-24 um 10 51 53" src="https://user-images.githubusercontent.com/932156/80193729-a3e1a580-8619-11ea-83d0-066e8f2c8d24.png">

**Comment by Stephen-Gates** [comment]
As a new mkdocs-material user I've just discovered the .zoom idea above. I think it is really neat and exactly what I was looking for. Perhaps it is worth mentioning in the [Image Attribute list](https://squidfunk.github.io/mkdocs-material/reference/images/#attribute-list) section?

**Comment by squidfunk** [comment]
What would you like to document? The additional CSS for zooming? The problem with this approach is that it is more or less desktop-only. Scaling without a transform origin (or at least some context about the environment) will not work well on mobile. For this reason it’s more or less a hack, which is why it isn’t documented.

**Comment by Stephen-Gates** [comment]
True. I just tried it on my mobile and not pretty. Will try improve and if viable, document.

**Comment by maxcrn** [comment]
I have a problem : when I zoom an image with your CSS. The sides of the images are hidden by the rest of the page. I tried to put "overflow: visible" but it doesn't work. Have you got an idea on how to make the image on the foreground when it is zoomed.

**Comment by rcastley** [comment]
Here is my latest code @maxcrn 

Javascript
```
document.querySelectorAll('img.zoom').forEach(item => {
    item.addEventListener('click', function () {
        this.classList.toggle('image-zoom-large');
    })
});
```

CSS
```
img {
    height: auto;
    width: auto;
    border: 1px solid #ddd;
    border-radius: 6px;
    padding: 4px;
    background-color: #fff;
}

.shadow {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
}

.zoom {
    transition: transform ease-in-out 0.5s;
    cursor: zoom-in;
}

.image-zoom-large {
    transform: scale(1.9);
    cursor: zoom-out;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    z-index: 100;
    position: relative;
}
```

Then in the markdown use
```
![select APM](../images/apm/select-apm.png){: .zoom}
```

**Comment by maxcrn** [comment]
@rcastley Thanks, but I have the same issue with this code. 
Here is the original picture : 
![wpp](https://user-images.githubusercontent.com/32536144/111785337-c6794e80-88bc-11eb-9ed6-f3cf57c2ccc9.jpg)

Here is the problem when I click to zoom on it :
![example](https://user-images.githubusercontent.com/32536144/111785288-b2355180-88bc-11eb-9c97-5f3baa1a9bc9.jpg)

It gets hidden on the sides.
Have you got an idea on how to correct this ? I tried "overflow:visible" but it didn't work.

Thanks for your help !

**Comment by rcastley** [comment]
@maxcrn Confirmed it was also broken in my environment after updating Material theme. Here is the fix:

Javascript
```
document.querySelectorAll('.zoom').forEach(item => {
    item.addEventListener('click', function () {
        this.classList.toggle('image-zoom-large');
    })
});
```

CSS
```
img {
    height: auto;
    width: auto;
    border: 1px solid #ddd;
    border-radius: 6px;
    padding: 4px;
    background-color: #fff;
}

.shadow {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
}

.zoom {
    transition: transform ease-in-out 0.5s;
    cursor: zoom-in;
}

.image-zoom-large {
    transform: scale(1.5);
    cursor: zoom-out;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    z-index: 100;
    position: absolute;
}
```

**Comment by oschusler** [comment]
I have update the CSS slightly, to make the content centered. In my case, I also have the theming on, so I add the bg-color variable to the background as well.

```css
.shadow {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
}

.zoom {
    transition: transform ease-in-out 0.5s;
    cursor: zoom-in;
}

.image-zoom-large {
    transform: scale(1.5);
    cursor: zoom-out;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    z-index: 100;
    position: absolute;

    margin: auto;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;

    height: auto;
    width: auto;
    border: 1px solid #ddd;
    border-radius: 6px;
    padding: 4px;
    background-color: var(--md-default-bg-color);
}
```

Might improve on the JS later (i.e. not pop the image out of the running text, and add an overlay behind the image which you can also click to minimize the image).

**Comment by champagnealexandre** [comment]
> I have update the CSS slightly, to make the content centered. In my case, I also have the theming on, so I add the bg-color variable to the background as well.
> 
> ```css
> .shadow {
>     box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
> }
> 
> .zoom {
>     transition: transform ease-in-out 0.5s;
>     cursor: zoom-in;
> }
> 
> .image-zoom-large {
>     transform: scale(1.5);
>     cursor: zoom-out;
>     box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
>     z-index: 100;
>     position: absolute;
> 
>     margin: auto;
>     left: 0;
>     right: 0;
>     top: 0;
>     bottom: 0;
> 
>     height: auto;
>     width: auto;
>     border: 1px solid #ddd;
>     border-radius: 6px;
>     padding: 4px;
>     background-color: var(--md-default-bg-color);
> }
> ```
> 
> Might improve on the JS later (i.e. not pop the image out of the running text, and add an overlay behind the image which you can also click to minimize the image).

You can replace `position: relative` with `position: fixed` make the images zoom in the center of the user’s *screen*, and not the center of the page. If a page contains a large number of images, the zoomed-in image can appear in odd places otherwise.

**Comment by Sieboldianus** [comment]
Thank you! I did not like the glightbox, but this minimal css was awesome. I removed `position: absolute` and added `max-width: 100vw`:
```css
.image-zoom-large {
    transform: scale(1.5);
    cursor: zoom-out;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
    z-index: 100;
	max-width: 100vw;
    margin: auto;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;

    height: auto;
    width: auto;
    border: 1px solid #ddd;
    border-radius: 6px;
    padding: 4px;
    background-color: var(--md-default-bg-color);
}
```

![Image](https://github.com/user-attachments/assets/78b75967-1fa6-4281-bf60-579a2cfb0297)
