### ISSUE TITLE
Embed content and collapsible blocks

### ISSUE THREAD

**Issue by Amber1990Zhang** [squidfunk/mkdocs-material#1636]
I want to use the `Admonition` extension to embed content and collapsible blocks at the same time. But it just won't work for me. I copied the examples from the [doc](https://squidfunk.github.io/mkdocs-material/extensions/admonition/#embedded-content) but my site looks different.

- mkdocs                        1.1
- mkdocs-material               4.6.3

**How my site actually looks like:**
**The embedded code looks different, the collapsible block is not parsed.**
![image](https://user-images.githubusercontent.com/42762957/80167100-1d759580-8612-11ea-8f9d-b36f9fb66cd2.png)

**`my yaml`:**
```yaml
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      separator: "_"
  - mdx_truly_sane_lists
```
