### ISSUE TITLE
Icons in titles not rendered in navigation

### ISSUE THREAD

**Issue by mrmanc** [squidfunk/mkdocs-material#1637]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- n/a ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem
> #866 was the closest I could find

## Description

When `pymdownx.emoji` is configured as a markdown extension, and `mkdocs-material-extensions` is installed, I would expect a title containing an icon such as `:fontawesome-solid-book:` to be rendered in the navigation with the icon, as it is in the page.

### Expected behavior

The navigation item should have an icon in it

### Actual behavior

The navigation item has `:fontawesome-solid-book:` in it.

### Steps to reproduce the bug

1. Add this code to the `markdown_extensions:` in `mkdocs.yml`
  ```
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  ```
2. Set the title of a page which exists in navigation with an icon in it (without using the front-matter, using an h1 as the first line of the file):
  ```
  # About this handbook :fontawesome-solid-book:
  ```
3. Run the development server and check the navigation, observing the text which should be an icon

### Package versions

* Python: 3.7.7
* MkDocs: 1.1
* Material: 5.1.1

### Project configuration

```yaml
site_name: …
site_description: 
site_author:
site_url: 


repo_name: …
repo_url: …

use_directory_urls: true

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - fontawesome_markdown
  - sane_lists
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

theme:
  name: 'material'
  font:
    text: 'Open Sans'
  logo: 'at_logo.png'
  favicon: 'favicon.ico'
  features:
    - instant

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      locale: en
      type: datetime
      fallback_to_build_date: true
```
### System information

* OS: MacOS v10.15.4
* Browser: Chrome 80.0.3987.163
