### ISSUE TITLE
Show logo even on mobile layouts

### ISSUE THREAD

**Issue by borekb** [squidfunk/mkdocs-material#1676]
## Description

It would be nice if narrow screens / mobile view also displayed the logo – it's often an important part of the site's identity.

### Screenshots / Mockups

Above 1100px:

<img width="268" alt="Screenshot 2020-05-07 at 14 46 25" src="https://user-images.githubusercontent.com/101152/81296591-6990f300-9072-11ea-9b66-ef8e0e2b3364.png">

Below 1100px:

<img width="268" alt="Screenshot 2020-05-07 at 14 46 35" src="https://user-images.githubusercontent.com/101152/81296605-6e55a700-9072-11ea-8844-21de73e7b816.png">

**Comment by squidfunk** [comment]
Just add this extra CSS, and the logo will always be visible:

``` css
@media screen and (max-width: 76.1875em) {
  .md-header-nav__button.md-logo {
    display: block;
  }
}
```
