### ISSUE TITLE
404 page: navigation links are broken (gitlab pages)

### ISSUE THREAD

**Issue by robertsanseries** [squidfunk/mkdocs-material#1689]
## Description

When hitting a missing page (404), the navigation links are not working anymore. (I'm using gitlab pages)

I noticed that a similar problem was fixed in Mkdocs https://github.com/mkdocs/mkdocs/issues/1598. 

**Attention**:

`This problem does not happen in version mkdocs-material 5.1.3.`
 `Error does not occur with the default theme `

### Steps to reproduce the bug

Test mkdocs for error reproduction: [mkdocs-material-error-navigation.zip](https://github.com/squidfunk/mkdocs-material/files/4619303/mkdocs-material-error-navigation.zip)

1 - Navigate to page 2 
2 - Then try to navigate to page 3

#### See attached video >>> [mkdocs-material-error-navigation - 2020-05-12 22.47.29.mp4.zip](https://github.com/squidfunk/mkdocs-material/files/4619362/mkdocs-material-error-navigation.-.2020-05-12.22.47.29.mp4.zip) <<<

![Captura de tela de 2020-05-12 22 36 35](https://user-images.githubusercontent.com/11967501/81761725-115a5680-94a1-11ea-8b61-5afadbdb402e.png)

### Package versions

* Python: `python: 3.8`
* MkDocs: `mkdocs: 1.1`
* Material: `mkdocs-material 5.1.5`

### Project configuration

``` yaml
# Project information
site_name: Mkdocs Material
site_description: A Material Design theme for MkDocs
site_author: squidfunk
#site_url: add your gitpages URL

# Repository
repo_name: squidfunk/mkdocs-material
repo_url: https://github.com/squidfunk/mkdocs-material
edit_uri: ""

# Copyright
copyright: 'Copyright © 2016 - 2020 Martin Donath'

# Configuration
theme:
  name: material
  logo: images/google.jpeg
  favicon: images/favicon.ico
  palette:
    primary: 'blue'
    accent: 'light blue'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - admonition
  - codehilite
  - meta

# Page tree
nav:
  - Visão geral: index.md
  - Test Page 1: test-page-1.md
  - Test Page 2: test-page-2.md
  - Test Page 3: test-page-3.md
```

### System information

**Page navigation works in my localhost environment**

* OS: elementary OS 5.1.4 Hera (Built on Ubuntu 18.04.4 LTS)
* Browser:  Google Chrome - Versão 81.0.4044.138 (Versão oficial) 64 bits
