### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by z3r0x1c** [squidfunk/mkdocs-material#1693]
How can I add this menu to my docs?
https://i.imgur.com/RFUF0qk.png

**Comment by facelessuser** [comment]
https://squidfunk.github.io/mkdocs-material/getting-started/#tabs

**Comment by z3r0x1c** [comment]
thx <3

**Comment by epogrebnyak** [comment]
For some reason tabs do not work for me.

I have the following config file, but no luck, just menu on the left, no menu below the header appears.

```
nav:
 - abc: index.md
 - def: 
   - ggg: process.md

theme:
  name: material
  features:
    - tabs
```
