### ISSUE TITLE
material 5.x does not render Font Awesome icons in mermaid diagrams

### ISSUE THREAD

**Issue by snim2** [squidfunk/mkdocs-material#1698]
## Description

Mermaid diagrams can be embedded in `mkdocs-material` sites, and can contain FA icons. This worked in v4.x of `mkdocs-material` but the icons do not appear when upgrading to v5.x.

### Expected behavior

Nice Font Awesome icons can appear in mermaid diagrams:

![mermaid-fa-working](https://user-images.githubusercontent.com/97674/82043413-754c6d00-96a3-11ea-9359-bb55d5fb7998.png)

### Actual behavior

Nice Font Awesome icons in mermaid diagrams disappear:

![mermaid-fa-broken](https://user-images.githubusercontent.com/97674/82043452-86957980-96a3-11ea-89ed-493edcba452a.png)

### Steps to reproduce the bug

1. Start with a `mkdocs-material` site using version 4.x of `material` that contains a mermaid diagram with Font Awesome icons.
2. Upgrade to version 5.x of `material`
3. Run `mkdocs serve` and notice that the icons in the diagram have vanished

### More information

Using Chrome Inspect, it looks like there is no network traffic with the fontawesome site when `mkdocs-material 5.x` is used. So, I suspect the problem here is maybe something to do with parsing the Markdown and using custom superfences. I appreciate that it's not feasible to make `material` work with every Javascript library that people might want to use, but I wonder whether there's an obvious workaround that I'm missing here?

### Package versions

Working versions:

* Python:  3.7
* MkDocs: 1.0.4
* Material: 4.4.0

Buggy versions:

* Python:  3.8
* MkDocs: 1.1.1
* Material: 5.1.6

Both using mermaid 8.5.0, which can be downloaded from here: [jsdelivr](https://www.jsdelivr.com/package/npm/mermaid).

### Project configuration

``` yaml
site_name: ''
theme:
    name: 'material'
extra_javascript:
    - 'assets/javascript/mermaid.min.js'
markdown_extensions:
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_div_format
nav:
    - Home: index.md
```

### Example test case

`docs/index.md`:

I don't think nested triple ticks are going to play well with GitHub Markdown, so I've turned \` into a single quote mark here:

```
'''mermaid
graph LR
    A["Search icon fa:fa-search"]
    B["List icon fa:fa-list-alt"]
    A --> B
'''
```

### System information

* OS: Ubuntu 20.04
* Browser: Chromium (from snap), also Firefox
