### ISSUE TITLE
Table of contents does not display headers when 2nd H1 header is used

### ISSUE THREAD

**Issue by Andre601** [squidfunk/mkdocs-material#1700]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description
When you use more than one H1 Header in a file does the Toc only display the headers up to the second H1 Header.
All headers following afterwards are not displayed.

### Expected behavior
The headers should be listed as expected

### Actual behavior
Only the headers up to the second H1 header are displayed.

### Steps to reproduce the bug

1. Create a page
2. Add two H1 headers with additional headers (h2, h3, ...) between and after the 2nd h1 header.
3. `mkdocs serve` the page

### Package versions

* Python: `3.7`
* MkDocs: `1.1`
* Material: `5.1.6`

### Project configuration

``` yaml
site_name: MkDocs Template
site_description: 'A template for future MkDocs wikis'
site_author: 'Andre_601'

copyright: |
  &copy; Author

docs_dir: docs/

repo_name: Andre601/mkdocs-template
repo_url: https://github.com/Andre601/mkdocs-template

nav:
  - Welcome: index.md
  - GitHub:
    - Index: github/index.md
    - General: github/general.md

theme:
  name: 'material'
  favicon: 'assets/images/favicon.png'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  features:
    - tabs
  icon:
    logo: 'fontawesome/brands/github'
    repo: 'fontawesome/brands/github'

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/Andre601/mkdocs-template'

markdown_extensions:
  - markdown.extensions.admonition:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.emoji:
  - pymdownx.magiclink:
  - pymdownx.superfences:
  - pymdownx.tabbed:
  - pymdownx.tasklist:
  - pymdownx.tilde:
```

### System information

* OS: Windows 10 64-Bit (10.0.18362)
* Browser: 81.0.4044.138 (64-Bit)
