### ISSUE TITLE
Style all scrollbars in Firefox as they are in Chrome

### ISSUE THREAD

**Issue by facelessuser** [squidfunk/mkdocs-material#1717]
__I checked that...__

- [X] ... the documentation does not mention anything about my idea
- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... there are no open or closed issues that are related to my idea

## Description

Basically we need the equivalent of (obviously just place in the correct places):

```css
.md-typeset__scrollwrap,
.md-sidebar__scrollwrap,
.md-search__scrollwrap,
.md-typeset pre > code {
  scrollbar-color: var(--md-default-fg-color--lighter) transparent;
  scrollbar-width: thin;

  &:hover {
    scrollbar-color: var(--md-accent-fg-color) transparent;
  }
}
```

This also fixes giant scrollbars in table scroll wraps by styling `.md-typeset__scrollwrap`.

I plan on creating a pull request unless someone gets to it before me.

### Use Cases

Create consistent scroll bars across browsers.

### Screenshots / Mockups

Basically it looks like Chrome scrollbars, but in FireFox. Don't really need a picture. Reference #1686.
