### ISSUE TITLE
Microsoft Edge: Transparent header in 5.x

### ISSUE THREAD

**Issue by lukas-koschmieder** [squidfunk/mkdocs-material#1728]
## Description

Microsoft Edge displays a transparent header in mkdocs-material 5.x. In the previous 4.x releases, Microsoft Edge used to display the background color correctly as defined in `theme['palette']['primary']`.

I've noticed that if you inspect the corresponding `md-header` DOM element, it will show you that the CSS attribures `color`/`background-color` are set correctly to `var(--md-primary-fg-color)`/`var(--md-primary-bg-color)`. So my guess is that there is something wrong with the fade-in animation; browser-specific instructions my be needed.

### Expected behavior

Edge renders the header background color as defined in `theme['palette']['primary']`

### Actual behavior

Edge renders a transparent header background

### Steps to reproduce the bug

1. Serve a mkdocs documentation with the mkdocs-material enabled
2. Open documentation in Edge

### Package versions

* Python: 3.7.3
* MkDocs: 1.1.2
* Material: 5.2.1

### Project configuration

``` yaml
theme:
  name: material
  language: en
  features:
    - instant
  palette:
    scheme: default
    primary: grey
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  logo: img/logo.png
```

### System information

* OS: Windows 10
* Browser: Edge 44
