### ISSUE TITLE
Padding/Margin of dictionary elements

### ISSUE THREAD

**Issue by facelessuser** [squidfunk/mkdocs-material#173]
## Description

It seems dictionary elements don't have any padding or margin at their bottom when in normal vieweing mode, but when in mobile view, we get good padding.

Normal wide viewing mode:

![screenshot 2017-02-18 09 07 12](https://cloud.githubusercontent.com/assets/1055125/23094657/5c61631e-f5ba-11e6-8cee-a29b9266f3dc.png)

Mobile viewing (narrow mode).

![screenshot 2017-02-18 09 09 15](https://cloud.githubusercontent.com/assets/1055125/23094661/73faa13e-f5ba-11e6-9448-7d4862ef36c3.png)

### Expected behavior

In normal viewing mode, dictionaries will have good looking margin and/or padding at bottom.

### Actual behavior

During normal viewing mode dictionaries have no padding and/or margin at the bottom.

### Steps to reproduce the bug

1. Create two dictionaries after each other in documents
2. Render documents
3. View in normal, wide viewing and mobile, narrow viewing and compare.

### Package versions

* Python: Any
* MkDocs: 0.16.1
* Material: 1.0.5

### Project configuration

Relevant portion:

``` yaml
markdown_extensions:
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: 
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - pymdownx.extrarawhtml:
  - pymdownx.superfences:
      css_class: codehilite
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite:
      css_class: codehilite
  - pymdownx.magiclink:
      repo_url_shortener: true
      base_repo_url: https://github.com/facelessuser/pymdown-extensions
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
  - pymdownx.mark:
  - pymdownx.plainhtml:
      strip_attributes: ''
  - pymdownx.snippets:
      base_path: docs/snippets
```

### System information

* OS: Don't think it matters, but tested on MacOS
* Browser: Not sure if this is relevant, but Chrome: 56.0.2924.87 (64-bit)
