### ISSUE TITLE
Search does not work in french language

### ISSUE THREAD

**Issue by kevung** [squidfunk/mkdocs-material#1745]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [ ] ... there are no open or closed issues that are related to my problem

## Description

Search word in with mkdocs-material fir french language does not work properly

### Expected behavior

Simple word such as 'plage' should be found.
Accented words are not consistently found.

### Actual behavior

'plag' is found, but not 'plage'

### Steps to reproduce the bug

1. Install mkdocs-material (5.2.2)
2. Use this `mkdocs.yml` file:
```
site_name: My Docs
theme:
  name: material
  language: fr

plugins:
  - search
```
and this `./docs/index.md`
```
Cet été ensoleillé, nous irons à la plage.
```
3. serve mkdocs (`python -m mkdocs serve`) and search for `plage`.

### Package versions

* Python: `3.8.3
* MkDocs: `1.1.2`
* Material: `5.2.2`

### Project configuration

``` yaml
site_name: My Docs
theme:
  name: material
  language: fr

plugins:
  - search
```

### System information

* OS: Linux 5.6.15-arch1-1 x86_64 GNU/Linux
* Browser: firefox

**Comment by squidfunk** [comment]
As already noted in #419, it's very likely related to #1603 and #1675. Please, see the comments on these issues.

**Comment by kevung** [comment]
@squidfunk Thank you very for your reply. I will just put here some simple tests here.
Here are the following tests I made. I use each time the same `./docs/index.md` file:
```
Cet été ensoleillé, nous irons à la plage.
```

I want to search the word `plage`.

- With this `docs.yml`, the search is correct:
```
site_name: My Docs
theme:
  name: material
  language: en

plugins:
  - search
```
- With this `docs.yml`, `plag` is found but `plage` is not found:
```
site_name: My Docs
theme:
  name: material
  language: fr

plugins:
  - search
```

**Comment by squidfunk** [comment]
As noted in the comments, it's not fixable without losing the type-ahead experience.

**Comment by kevung** [comment]
I use each time the same `./docs/index.md` file:
```
Cet été ensoleillé, nous irons à la plage.
```
With this `docs.yml`, the search is correct:
```
site_name: My Docs
theme:
  name: material
  language: en

plugins:
  - search:
      lang:
        - fr
```
the word `ensoleillé`is properly found, but `à` is not. May it is because `à` begins with an accent.
(same result with `language: en`)

**Comment by kevung** [comment]
I use each time the same `./docs/index.md` file:
```
Cet été ensoleillé, nous irons à la plage.
```
With this `docs.yml`:
```
site_name: My Docs
theme:
  name: material
  language: en

plugins:
  - search:
      lang:
        - en
```
the word `irons à` is properly found,
but when activating the french option in search plugin:
```
site_name: My Docs
theme:
  name: material
  language: en

plugins:
  - search:
      lang:
        - fr
```
the word `irons à` is not found any more.

**Comment by squidfunk** [comment]
I took some time on this Sundays and think I have a fix in place as part of 36e1e3db.

It seems like swapping the pipeline initialization and also resetting the search pipeline (something that was added in lunr 2.0) seems to do the trick for most of the languages. I tried to test as many languages as possible and added some fixes to the default initialization.

**Comment by squidfunk** [comment]
Note that search is super tricky to get right for 40 languages. This may have introduced new problems I'm not aware of. I tried to test as many languages as I could, but unfortunately, my time is limited.

**Comment by squidfunk** [comment]
Released as part of 5.2.3

**Comment by kevung** [comment]
@squidfunk Thank you so much for your help, and for your work!
According to [search plugin doc page](https://squidfunk.github.io/mkdocs-material/plugins/search/), the language chosen for the theme sets the language for the search.

I tested a minimal example on the last Mkdocs-material release (5.2.3) with:
```
sudo pip install mkdocs-material --upgrade
```
In this minimal example:
- `./docs/index.md`:
```
Cet été ensoleillé, nous irons à la plage.
```
- `mkdocs.yml`:
```
site_name: My Docs
theme:
  name: material
  language: fr

plugins:
  - search

nav:
  - index.md
```
the word "nous" connot be found.

[screenshot](https://imgur.com/BcznfQm)
