### ISSUE TITLE
Japanese Search problem in 5.2.3

### ISSUE THREAD

**Issue by peaceiris** [squidfunk/mkdocs-material#1753]
## Description

We cannot search in Japanese with `5.2.3`

### Expected behavior

We can search in Japanese.

### Actual behavior

We cannot search in Japanese.

### Steps to reproduce the bug

- With 5.2.2, it works well
- With 5.2.3, it has the problem

```sh
git clone https://github.com/SI-Aizu/documentation.git
cd ./documentation

# 5.2.3
git checkout e55dc69
docker-compose up
# Go to http://localhost:8888
# Search "メンバー", it fails.

# 5.2.2
git checkout 6e359cf
docker-compose up
# Go to http://localhost:8888
# Search "メンバー", it will be found.
```

I am using my Docker image which is managed at [peaceiris/mkdocs-material-boilerplate](https://github.com/peaceiris/mkdocs-material-boilerplate).

### Package versions

* Python: 3.8
* MkDocs: 1.1.2
* Material: 5.2.3

### Project configuration

https://github.com/SI-Aizu/documentation/blob/6e359cf037eb939bde922b677257aecbb18390ef/mkdocs.yml

``` yaml
# Project information
site_name: 'SI-Aizu Documentation'
site_description: 'SI-Aizu Documentation'
site_author: 'SI-Aizu'
site_url: 'https://si-aizu.github.io/documentation'

# Copyright
copyright: '&copy; 2019 SI-Aizu'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/SI-Aizu/documentation'
edit_uri: 'https://github.com/SI-Aizu/documentation/edit/master/docs'

# Configuration
docs_dir: 'docs'
theme:
  name: 'material'
  language: 'ja'
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  palette:
    primary: indigo
    accent: orange
  # features:
  #   - tabs
  #font:
    #text: 'Ubuntu'
    #code: 'Ubuntu Mono'
  #icon:
    #logo: 'images/logo.svg'
  #favicon: 'assets/images/favicon.ico'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: '_'

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - ja

# Customization
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML'
extra_css:
  - 'assets/css/custom.css'
extra:
  # manifest: 'manifest.json'
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/SI-Aizu/documentation'
```

### System information

* OS: macOS, Linux (Ubuntu 18.04)
* Browser: Google Chrome
