### ISSUE TITLE
TOC not appearing by default?

### ISSUE THREAD

**Issue by yosef-elementryx** [squidfunk/mkdocs-material#1754]
__I checked that...__

- [ ] ... the documentation does not mention anything about my problem
- [ ] ... the problem doesn't occur with the default MkDocs template
- [ ] ... the problem is not in any of my customizations (CSS, JS, template)
- [ ] ... there are no open or closed issues that are related to my problem

## Description

The Table of Contents (TOC) doesn't appear by default, even when specifying `toc` in markdown_extensions. The permalinks are shown next to each header, but there is no TOC on the right side.

### Project configuration

``` yaml
site_name: My_Site

theme:
  name: material

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
```

### System information

* OS: Windows Subsystem for Linux
* Browser: Chrome
