### ISSUE TITLE
5.3.1 broke icon references in templates

### ISSUE THREAD

**Issue by mmadson** [squidfunk/mkdocs-material#1764]
works with 5.3.0, broken with 5.3.1

jinja2.exceptions.TemplateNotFound unable to find mail.svg in social.html partial

mkdocs.yml

```
theme:
  name: 'material'
  highlightjs: true
  features:
    - instant

markdown_extensions:
  - admonition
  - meta
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/i
    - icon: fontawesome/brands/slack
      link: https://slack.com/
    - icon: octicons/mail
      link: mailto://redacted@redacted.com
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com

extra_css:
  - css/extensions.css
  - css/root.css
  - css/header.css
  - css/body.css
```
