### ISSUE TITLE
Using nav key toggle off all nested items when navigate

### ISSUE THREAD

**Issue by xhit** [squidfunk/mkdocs-material#1789]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [ ] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

Using `nav` key in mkdocs.yml and using nested items toggle off all nested items when select a page.

If I comment `nav` key configuration, when navigate the items the web keeps the opened nested items.

### Expected behavior

Not toggle off all nested and opened items, like using without `nav` key.

### Actual behavior

All nested items toggle off.

### Steps to reproduce the bug

1. Create a project using `nav`
2. Add some nested nav
3. Navigate the items

File: [test.zip](https://github.com/squidfunk/mkdocs-material/files/4870577/test.zip)

### Package versions

* Python: `3.8.3`
* MkDocs: `1.1.2`
* Material: `5.4.0`

### Project configuration

``` yaml
site_name: My Docs

nav:
  - Home: index.md
  - Group1:
    - Index: folder1/
    - Page1: folder1/page1
    - Page2: folder1/page2
    - Group1.1:
      - Index: folder1/
      - Page1.1: folder1/page1
      - Page2.1: folder1/page2
    - Group2:
      - Page3: folder1/page3
      - Page4: folder1/page4
  - AnotherPage: another.md

theme:
    name: material
```

### System information

* OS: Windows 10 Pro
* Browser: Firefox 77.0.1

**Comment by squidfunk** [comment]
What do you mean exactly by "nested items toggle off all nested items when select a page"? Could you maybe add a screen recording that shows the behavior?

**Comment by xhit** [comment]
Video: https://photos.google.com/share/AF1QipPQzP337pBwROSrh0k6dWyuaoNiO2qRzJndRRQNJQPt5wuCZz88C54V6rZk92OzMw/photo/AF1QipOc8_5F3ru5Yt9U8b8Pk8r29j6AQDoXwCwW3haM?key=YW5DdldWbThjSFBBOV9nZDh4WXhIQ05HUUp5NzZn

**Comment by squidfunk** [comment]
Your navigation:

``` yml
nav:
  - Home: index.md
  - Group1:
    - Index: folder1/
    - Page1: folder1/page1
    - Page2: folder1/page2
    - Group1.1:
      - Index: folder1/
      - Page1.1: folder1/page1
      - Page2.1: folder1/page2
    - Group2:
      - Page3: folder1/page3
      - Page4: folder1/page4
  - AnotherPage: another.md
```

If you specify __the same__ file for multiple entries, MkDocs will always link to the first occurrence. Try specifying separate files/folders.

**Comment by xhit** [comment]
You are correct, I only reproduce with a minimal example configuration. I fixed it and same result.

```yaml
nav:
  - Home: index.md
  - Group1:
    - Index: folder1/index.md
    - Page1: folder1/page1
    - Page2: folder1/page2
    - Group1.1:
      - Index: folder2/index.md
      - Page1.1: folder2/page1
      - Page2.1: folder2/page2
    - Group2:
      - Page3: folder3/page3
      - Page4: folder3/page4
  - AnotherPage: another.md
```

Minimal project: [test.zip](https://github.com/squidfunk/mkdocs-material/files/4870969/test.zip)

The idea is to use the same behavior when opening a page from item inside item using `nav` and not using it.

If I comment `nav` then I can click a item inside a group inside another group and structure in navigator remains instead collapse all.
