### ISSUE TITLE
Heading markdown in Admonition breaks "Table of contents"

### ISSUE THREAD

**Issue by Tset-Noitamotua** [squidfunk/mkdocs-material#179]
## Description

When I use "heading markdown syntax" in Admonition box (example code below) the table of contents (TOC) on the right side is not created correctly.

But TOC is created correctly when I do NOT use `#` heading syntax in Admonition boxes.

### Expected behavior

correct TOC

### Actual behavior

uncomplete TOC

### Steps to reproduce the bug

> NOTE: I have to add one TAB at the beginning of each line to prevent the text from beeing rendered here. So if you want to try it - remove one TAB from each line!

Use this markdown ...

```
    # MarkDown Snippets

    foo bar

    ```markdown
    _MarkDown Syntax_ (is what you type!)
    ```

    !!! SUCCESS ""
        _Rendered HTML_ (is what you get!)

    ## Typography
    ---

    ### Headings

    ```markdown
    # h1. Heading
    ## h2. Heading
    ### h3. Heading
    ##### h4. Heading
    ###### h5. Heading
    ####### h6. Heading
    ```

    !!! SUCCESS ""
        # h1. Heading
        ## h2. Heading
        ### h3. Heading
        #### h4. Heading
        ##### h5. Heading
        ###### h6. Heading

    ### Headings with Subtitle

    ```markdown
    # h1. Heading <small>Subtitle I</small>
    ## h2. Heading <small>Subtitle II</small>
    ### h3. Heading <small>Subtitle III</small>
    #### h4. Heading <small>Subtitle IV</small>
    ##### h5. Heading <small>Subtitle V</small>
    ###### h6. Heading <small>Subtitle VI</small>
    ```

    !!! SUCCESS ""
        # h1. Heading <small>Subtitle I</small>
        ## h2. Heading <small>Subtitle II</small>
        ### h3. Heading <small>Subtitle III</small>
        #### h4. Heading <small>Subtitle IV</small>
        ##### h5. Heading <small>Subtitle V</small>
        ###### h6. Heading <small>Subtitle VI</small>

```

 ... to get a broken TOC like in screenshot below

![image](https://cloud.githubusercontent.com/assets/5635462/23259629/56fc03e4-f9ce-11e6-826d-4c7825407234.png)


### Package versions

* Python: 2.7.12
* MkDocs: 0.16.1
* Material: 1.0.3

### Project configuration

``` yaml
site_name: foo
site_description: foo Software Quality Assurance
site_dir: _foo
docs_dir: PROJECTS
pages:
  - Home: README_foo.md
  - Acceptance Tests:

theme: material
theme_dir: _foo_Source
markdown_extensions:
  - admonition
  - footnotes
  - codehilite(linenums=true)
  - toc(permalink=true)
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

extra_javascript:
  - 'foo_MKDocs_Extensions\javascripts\jenkins.js'
extra_css:
  - 'foo_MKDocs_Extensions\stylesheets\buttons.css'

extra:
  palette:
    primary: 'red'
    accent: 'red'
  social:
    - type: 'github'
   - ...
```

### System information

* OS: Windows 7 (64bit)
* Browser: `chrome://version/` --> 55.0.28
