### ISSUE TITLE
Fail to initialize searching index for languages other than 'en'

### ISSUE THREAD

**Issue by peaceiris** [squidfunk/mkdocs-material#1854]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

Version 5.5.1 and 5.5.2 fails to initialize search index with Japanese search mode but version 5.5.0 works well.

### Expected behavior

`5.5.0` works well.

```
git clone https://github.com/SI-Aizu/documentation.git
cd ./documentation
git checkout cd36072
docker-compose up
```

Open <http://0.0.0.0:8888/>, search with a Japanese word or an English word, it works well.

```console
$ docker-compose run --rm --entrypoint=bash mkdocs
$ python --version
Python 3.8.5
$ mkdocs --version
mkdocs, version 1.1.2 from /usr/local/lib/python3.8/site-packages/mkdocs (Python 3.8)
$ pip show mkdocs-material | grep -E ^Version
Version: 5.5.0
```

### Actual behavior

In 5.5.1 and 5.5.2, it shows only the message `Initializing search` and I cannot search with any word (any language). My browser console (Google Chrome) put the following error.

```sh
git clone https://github.com/SI-Aizu/documentation.git
cd ./documentation
git checkout a654e3b
docker-compose up
```

<img width="376" alt="Screen Shot 2020-08-04 at 17 33 13" src="https://user-images.githubusercontent.com/30958501/89272102-9c9a5100-d678-11ea-8c65-537c90739371.png">

```
Uncaught TypeError: Cannot set property 'stemmerSupport' of undefined    index.ts:63
    at lunr.stemmer.support.min.js:1
    at lunr.stemmer.support.min.js:1
    at lunr.stemmer.support.min.js:1
    at index.ts:63
    at a (index.ts:85)
    at index.ts:109
```

<img width="759" alt="Screen Shot 2020-08-04 at 17 20 11" src="https://user-images.githubusercontent.com/30958501/89270758-c488b500-d676-11ea-933e-121e23fa06b0.png">

```console
$ docker-compose run --rm --entrypoint=bash mkdocs
$ python --version
Python 3.8.5
$ mkdocs --version
mkdocs, version 1.1.2 from /usr/local/lib/python3.8/site-packages/mkdocs (Python 3.8)
$ pip show mkdocs-material | grep -E ^Version
Version: 5.5.1
```

### Steps to reproduce the bug

I already wrote about this above.

### Package versions

I already wrote about this above.

### Project configuration

I am using the same configuration between the 3 versions.

``` yaml
# Project information
site_name: 'SI-Aizu Documentation'
site_description: 'SI-Aizu Documentation'
site_author: 'SI-Aizu'
site_url: 'https://si-aizu.github.io/documentation'

# Copyright
copyright: '&copy; 2020 SI-Aizu'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/SI-Aizu/documentation'
edit_uri: 'https://github.com/SI-Aizu/documentation/edit/main/docs'

# Configuration
docs_dir: 'docs'
theme:
  name: 'material'
  language: 'ja'
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  palette:
    primary: indigo
    accent: orange
  # features:
  #   - tabs
  #font:
    #text: 'Ubuntu'
    #code: 'Ubuntu Mono'
  #icon:
    #logo: 'images/logo.svg'
  #favicon: 'assets/images/favicon.ico'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: '_'

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - ja

# Customization
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML'
extra_css:
  - 'assets/css/custom.css'
extra:
  # manifest: 'manifest.json'
  social:
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/SI-Aizu/documentation'
```

### System information

* OS: macOS Mojave 10.14.6
* Browser:
  * Google Chrome Version 84.0.4147.105 (Official Build) (64-bit)
  * Microsoft Edge Version 84.0.522.52 (Official build) (64-bit)
