### ISSUE TITLE
Unable to display picture of Imgur

### ISSUE THREAD

**Issue by liangjingkanji** [squidfunk/mkdocs-material#1855]
## Description

Unable to display picture of Imgur ,  But it can be opened separately in a browser.  But it'll be fine in a minute.  This every time.

Image:  https://i.imgur.com/qK280BL.jpg

<br>

mkdocs-material : ![image](https://user-images.githubusercontent.com/21078112/89347724-e10c0800-d6dd-11ea-81e8-6f20e3f1233b.png)

Chrome console: ![image](https://user-images.githubusercontent.com/21078112/89347729-e2d5cb80-d6dd-11ea-8dd5-01937c591232.png)

### Expected behavior

Display picture of Imgur

### Steps to reproduce the bug

1. Uploaded Image to Imgur
2. create img html `<img src="https://i.imgur.com/qK280BL.jpg" width="50%" />` at mkdocs 
3. `mkdocs serve`  look up on Chrome `127.0.0.1:8000`

### Package versions

* Python:  3.8.5
* MkDocs:   1.1.2
* Material:  5.5.3

### Project configuration

``` yaml
site_name: BRV
site_author: drake
site_description: BRV框架文档
copyright: Copyright &copy; 2016 - 2020 Drake

repo_name: BRV
repo_url: https://github.com/liangjingkanji/BRV

extra_css:
  - css/extra.css

docs_dir: 'docs'

theme:
  name: material
  custom_dir: docs/material

  palette:
    primary: 'teal'
    accent: 'teal'

  font:
    text: JetBrains Mono
    code: JetBrains Mono
  language: zh

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed

  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - 使用: 'use.md'
  - 多类型: 'multi_type.md'
  - 监听事件: 'listener.md'
  - 头脚布局: 'header_footer.md'
  - 分组: 'group.md'
  - 悬停: 'hover.md'
  - 分割线: 'divider.md'
  - 缺省页: 'state.md'
  - 下拉刷新/上拉加载: 'refresh.md'
  - 拉取更多: 'upfetch.md'
  - 切换模式: 'toggle.md'
  - 选择模式: 'checked.md'
  - 伸缩布局: 'flexbox.md'
  - 拖拽/侧滑: 'drag_swipe.md'
  - 快捷函数: 'ktx.md'
  - 网络请求: 'net.md'
```

### System information

* OS: MacOS Catalina 10.15.6
* Browser: Chrome 84.0.4147.105 (64)
