### ISSUE TITLE
Disqus not loading properly

### ISSUE THREAD

**Issue by TheModdingGuides** [squidfunk/mkdocs-material#1888]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

Disqus is not loading on my site.

### Expected behavior

Disqus to work properly on my site.

### Actual behavior

Disqus is not loading on my site, but instead it's always showing up "We were unable to load Disqus.".
By the way in some 127.0.0.1:8000 pages, I can properly load Disqus.

### Steps to reproduce the bug

1. Add the following to mkdocs.yml:
``` yaml
extra:
    disqus: themoddingguides
```

### Package versions

* `$ python3 --version`:
``` bash
Python 3.7.3
```

* `$ mkdocs --version`
``` bash
mkdocs, version 1.1.2 from /home/$USER/.local/lib/python3.7/site-packages/mkdocs (Python 3.7)
```

* `$ pip show mkdocs-material | grep -E ^Version`
``` bash
Version: 5.5.11
```

### Project configuration

``` yaml
site_name: The Modding Guides

repo_name: The Modding Guides
repo_url: https://github.com/TheModdingGuides/TheModdingGuides.github.io/
edit_uri: ""

nav:
# A lot of navigation stuff

theme:
    font: false
    features:
      - instant
    name: material
    palette:
      primary: red
      accent: red
      scheme: preference
    language: it
    favicon: img/favicon.ico
    custom_dir: overrides

markdown_extensions:
    - toc:
        permalink: true
        toc_depth: 4
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.highlight:
        use_pygments: true
        linenums: true
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.tabbed
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - meta
    - attr_list

plugins:
    - search
    - git-revision-date-localized:
        type: datetime
        locale: it
        # about the following, is always giving me "Warning: ('time_zone', 'Unrecognised configuration name: time_zone')"
        time_zone: Europe/Rome

extra:
    disqus: themoddingguides
    social:
        # Social stuff
```

### System information

* OS: `Debian GNU/Linux 10 (buster) x86_64`
* Browser: `Mozilla Firefox 68.11.0esr (64 bit)` and `Google Chrome Version 85.0.4183.83 (Official build) (64 bit)`

### Additional info

I also added `github.io` to trusted domain but nothing has changed. I also added two screenshots of my disqus admin page, if that could help.
Maybe some configuration is wrong on my side?
I don't understand what could be wrong.

![Disqus_1](https://user-images.githubusercontent.com/67009323/91669473-88c9f980-eb15-11ea-9f2d-624f6f93774a.png)
![Disqus_2](https://user-images.githubusercontent.com/67009323/91669479-92ebf800-eb15-11ea-89c2-86dcc57ca1e4.png)
