### ISSUE TITLE
I can't understand why emoji works, but icons don't 🤨

### ISSUE THREAD

**Issue by winterwolf** [squidfunk/mkdocs-material#1898]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [ ] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

Hello. I have installed and configured mkdocs following the instructions. I enabled a lot of modules, they all works fine. But I don’t understand why the icons are not displayed while the emoji does:

![screenshot-001](https://user-images.githubusercontent.com/42620439/91844052-6fcd5f80-ec5f-11ea-926e-66b3b58a10a7.png)

### Steps to reproduce the bug

In Manjaro I used these commands to install everything:

```bash
sudo -H pip install mkdocs mkdocs-material pymdown-extensions

git clone https://github.com/squidfunk/mkdocs-material.git
pip install -r mkdocs-material/requirements.txt
rm -rf mkdocs-material
```

### Package versions

* Python: `3.8.5`
* MkDocs: `1.1.2`
* Material: `5.5.7`

### Project configuration

``` yaml
markdown_extensions:
    - admonition
    - attr_list
    - footnotes
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - toc:
        permalink: true
```

### System information

```
 ██████████████████  ████████     luarocks@MAINFRAME
 ██████████████████  ████████     OS: Manjaro 20.1 Mikah
 ██████████████████  ████████     Kernel: x86_64 Linux 5.4.60-2-MANJARO
 ██████████████████  ████████     Uptime: 2h 17m
 ████████            ████████     Packages: 1363
 ████████  ████████  ████████     Shell: bash
 ████████  ████████  ████████     Resolution: 1920x1080
 ████████  ████████  ████████     DE: Xfce4
 ████████  ████████  ████████     WM: Xfwm4
 ████████  ████████  ████████     WM Theme: Greybird
 ████████  ████████  ████████     GTK Theme: Greybird [GTK2]
 ████████  ████████  ████████     Icon Theme: elementary-xfce-darker
 ████████  ████████  ████████     Font: DejaVu Sans 10
 ████████  ████████  ████████     Disk: 157G / 397G (42%)
                                  CPU: AMD Phenom II X4 945 @ 4x 3GHz
                                  GPU: GeForce GTX 465
                                  RAM: 2038MiB / 3937MiB
```
