### ISSUE TITLE
Allow explicitly setting repo type in `mkdocs.yml`

### ISSUE THREAD

**Issue by MikeyMJCO** [squidfunk/mkdocs-material#1900]
__I checked that...__

- [x] ... the documentation does not mention anything about my idea
- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea

## Description

Currently `mkdocs-material` autodetects the repo type from the URL. This is very useful and works incredibly well for `github.com`, `gitlab.com` and `gitlab.example.com` and `github.example.com` but it fails to account for the fact that a self-hosted GitLab (or GH Enterprise) instance can be at any domain. `lab.*`, `code.*`, `devops.*` are all ones I've seen/used.

If we could explicitly set the repo type for instances like this and still get the edit links/icon/forks/stars etc. It would be useful as currently we have to maintain a fork of the insiders edition just to tweak the regex on each release (that's the only change we make to the core code).

### Use Cases

Would benefit anyone using self-hosted GitLab or GitHub on a domain that doesn't include the full word.

### Screenshots / Mockups

```yaml
site_name: 'CiviCRM Installation Guide'
site_url: 'https://docs.civicrm.org/installation/en/stable/'
repo_url: 'https://lab.civicrm.org/documentation/docs/installation'
repo_name: GitLab
repo_type: gitlab
site_description: 'This guide is aimed at CiviCRM users and implementors who would like to learn how to install and setup CiviCRM.'
site_author: 'The CiviCRM community'
theme:
  name: material
  icon:
    repo: fontawesome/brands/gitlab

nav:
  - Home: index.md
  - Install CiviCRM on Backdrop: backdrop/index.md
  - Install CiviCRM on Drupal 7: drupal7/index.md
  - Install CiviCRM on Drupal 8: drupal8/index.md
#  - Install CiviCRM on Drupal 9: drupal9/index.md
  - Install CiviCRM on Joomla: joomla/index.md
  - Install CiviCRM on WordPress: wordpress/index.md 
  - General: 
      - Requirements: general/requirements.md
      - Permissions: general/permissions.md
      - Internationalisation: general/i18n_l10n.md
      - TLS for MySQL: general/mysql_tls.md
      - Troubleshooting: general/troubleshooting.md
  - Planning:
      - Identifying your needs: planning/index.md
      - Trying a demo: planning/demo.md
      - Hosting: planning/hosting.md
      - Choosing a CMS: planning/cms.md
      - Transitioning to CiviCRM: planning/transition.md
```
