### ISSUE TITLE
Revision date doesn't work with Instant loading

### ISSUE THREAD

**Issue by danierutu** [squidfunk/mkdocs-material#1918]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

When I set the `instant` feature along with the `git-revision-date-localized` plugin and click in any page from within the site, the XHR reload shows the new page fast, but the revision date won't appear at the end. I can only see it by refresing the site.
This bug doesn't happen when I follow a link to the site; only when I navigate through pages from within the site (XHR reloads).

### Expected behavior

Go to another page, displayed by XHR, and see the revision date at the end.

### Actual behavior

Go to another page, displayed by XHR, and only see "Last update:", without any date.

### Steps to reproduce the bug

1. Enable `instant` and `git-revision-date-localized`:
    ```yml
    plugins:
    - search
    - git-revision-date-localized:
        type: timeago
        fallback_to_build_date: true
    ```
2. Go to any page of your site following an URL from the outside. Revision date shows.
3. Go to any page from within the site (sidebar, prev/next page buttons, etc). Revision date doesn't show.
4. Refresh the site. Revision date shows again.

### Package versions

* Python: 3.8.5
* MkDocs: 1.1.2
* Material: 5.5.12+insiders.1.4.1  
  (although it also happened before using Insider builds)

### Project configuration

``` yaml
# Appearance
theme:
  name: material
  custom_dir: theme
  logo: assets/img/logo.png
  favicon: assets/img/favicon.png
  font:
    text: PT Sans
    code: PT Mono
  palette:
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - instant
    - tabs
    - header.hide # Insiders
    - search.highlight # Insiders

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true

# Extensions
markdown_extensions:
  - admonition
  - def_list
  - meta
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys:
      separator: ' + '
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.striphtml
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      separator: "-"
      permalink: '#'
      toc_depth: 3

# Customization
extra_css:
  - assets/css/tasklist.css
  - assets/css/tabbed.css
  - assets/css/critic.css
  - assets/css/2t1.css
extra_javascript:
  - assets/js/details.js
  - assets/js/tables.js
  - assets/js/2t1.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
```

### System information

* OS: Windows 10 20H1
* Browser: Firefox 80.0.1
