### ISSUE TITLE
No margin at bottom of content.

### ISSUE THREAD

**Issue by facelessuser** [squidfunk/mkdocs-material#192]
## Description

Recent release removes margin (or maybe padding) at bottom of page content:

![screenshot 2017-02-26 10 47 41](https://cloud.githubusercontent.com/assets/1055125/23342097/6f420b84-fc11-11e6-84f6-9975ca1ec787.png)

### Expected behavior

It is expected that a reasonable padding or margin would separate content from the footer.

### Actual behavior

There is no real padding or margin between content and the footer.

### Steps to reproduce the bug

Render pages with mkdocs-material 1.1.1.

### Package versions

* Python: Any
* MkDocs: 0.16.1
* Material: 1.1.1

### Project configuration

I don't think this is applicable, but:

```
markdown_extensions:
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: 
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - pymdownx.extrarawhtml:
  - pymdownx.superfences:
      css_class: codehilite
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite:
      css_class: codehilite
  - pymdownx.magiclink:
      repo_url_shortener: true
      base_repo_url: https://github.com/facelessuser/pymdown-extensions
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
  - pymdownx.mark:
  - pymdownx.plainhtml:
      strip_attributes: ''
  - pymdownx.snippets:
      base_path: docs/snippets
```

### System information

* OS: Any
* Browser: Tested on Firefox and Chrome
