### ISSUE TITLE
Build time significantly increases with overrides/.icons

### ISSUE THREAD

**Issue by kcgthb** [squidfunk/mkdocs-material#1942]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [ ] ... the problem doesn't occur with the default MkDocs template
- [ ] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

The site build time significantly increases (x8) when [additional icons are enabled](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#additional-icons) via `overrides/.icons`.

### Expected behavior

Same, or at least comparable build times with or without additional icons.

### Actual behavior

- without additional icons:
  ```
  $ grep -A3 pymdownx.emoji mkdocs.yml
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
        #    options:
        #  custom_icons:
        #    - overrides/.icons
  $ time mkdocs -q build
  
  real    0m8.947s
  user    0m8.744s
  sys     0m0.645s
  ```

* with additional icons:
  ```
  $ grep -A3 pymdownx.emoji mkdocs.yml
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
        options:
          custom_icons:
            - overrides/.icons
  $ time mkdocs -q build
  
  real    0m57.974s
  user    0m50.919s
  sys     0m7.643s
  ```

The actual icons don't seem to matter, nor the number of icons in `overrides/.icons`.

The issue doesn't seem to be specific to Material for MkDocs, but I couldn't find any reference to `custom_icons` in the [PyMdown Extensions documentation](https://facelessuser.github.io/pymdown-extensions) so I'm not exactly sure where to report this.

What seems to be happening is that with `custom_icons` enabled, `mkdocs` spends more and more time to read each page, as it's progressing through them. In verbose mode you can see that each of the lines:
```
DEBUG   -  Reading: docs/page.md
```
takes longer to process than the previous one, and end up almost crawling to a halt.
Without `custom_icons`, the build process goes through all of then quickly, each page taking the same time to read.

### Steps to reproduce the bug

1. enable custom icons in `mkdocs.yml` as per [the documentation](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#additional-icons)
2. build the pages with `mdocs build` or `mkdocs serve`

### Package versions

* Python: `Python 3.7.8`
* MkDocs: `mkdocs, version 1.1.2`
* Material: `Version: 5.5.12`

### Project configuration

``` yaml
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
```

**Comment by squidfunk** [comment]
What happens when you set the `emoji_generator` to `materialx`?

``` yaml
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg # <-
      options:
        custom_icons:
          - overrides/.icons
```

**Comment by squidfunk** [comment]
Furthermore, have you tried reproducing the problem with a mint installation, only configuring icons for overrides?

**Comment by kcgthb** [comment]
> What happens when you set the `emoji_generator` to `materialx`?

Same thing, apparently: reading .md pages is incrementally longer over the build process, and it ended up taking the same ~57s.

Interestingly, it's just the `Reading` phase that is longer, `Building` pages is still as quick as without `custom_icons`.

> Furthermore, have you tried reproducing the problem with a mint installation, only configuring icons for overrides?

I just tried adding the Bootstrap icons to a straight git clone of Material for MkDocs (exactly like in the example at https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#additional-icons): I cloned the https://github.com/squidfunk/mkdocs-material.git repo, created the `overrides/.icons` directory and added the Boostrap icons in it, then enabling custom icons with:
```
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
```
and the build time went from 5.7s to 32.3s
