### ISSUE TITLE
Tabs structure management

### ISSUE THREAD

**Issue by yacir** [squidfunk/mkdocs-material#195]
## Description

How could i add tabs structure plz ? Should i override the `css` ? 

### Expected behavior

<img width="849" alt="capture d ecran 2017-02-27 a 18 32 22" src="https://cloud.githubusercontent.com/assets/2587473/23372262/2ded51ec-fd1b-11e6-974a-31812faf0d84.png">

### Actual behavior

<img width="790" alt="capture d ecran 2017-02-27 a 18 24 27" src="https://cloud.githubusercontent.com/assets/2587473/23372280/41ed1c9a-fd1b-11e6-919d-34c850a9f102.png">

### Steps to reproduce the bug

The generated `HTML` is: 

```html
<div class="tab-set-container">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
            <a href="#tab-2-obj-c" aria-controls="tab-2-obj-c" role="tab" data-toggle="tab" data-lang="obj-c">Obj-c</a>
        </li>
        <li role="presentation" class="">
            <a href="#tab-2-swift" aria-controls="tab-2-swift" role="tab" data-toggle="tab" data-lang="swift">Swift</a>
        </li>
    </ul>
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active " id="tab-2-obj-c">
            <pre><code class="obj-c">//</code></pre>
        </div>
        <div role="tabpanel" class="tab-pane  " id="tab-2-swift">
            <pre><code class="swift">//</code></pre>
        </div>
    </div>
</div>
```

### Package versions

* Python: `2.7.10`
* MkDocs: `0.16.1`
* Material: `1.1.1`

### Project configuration

``` yaml
site_name: 'Docs'
site_author: 'Yassir'
site_description: ''
theme: 'material'
site_favicon: "assets/img/favicon.ico"

markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - markdown_include.include:
  - toc:
      permalink: "#"
  - BSCodeTabExtension:
      default_lang: 'objc'
      show_all_code_as_folders: False
      animate_tab_transitions: False

extra:
  collapse_toc: true
  toc_depth: 4
  version: 0.1.0
  logo: "assets/img/logo.png"
  logo_retina: "assets/img/logo_retina.png"

copyright: ''

pages: 
  - 'iOS':
      - 'Getting started': 'content/ios/getting-started.md'
      - 'Push': 'content/ios/push.md'
```

### System information

* OS: `Any`
* Browser: `Any`
