### ISSUE TITLE
Edit icon not shown if repo_name provided

### ISSUE THREAD

**Issue by matejvelikonja** [squidfunk/mkdocs-material#196]
## Description

If I do not have `repo_name: 'repo-name'` in `mkdocs.yml` the edit icon (pencil) is shown on every page. If I put repo name the edit button disappears.

Not really sure if this is bug or some kind of feature.

I just wanted to put repo_name into yml file to shown pretty repo name in top right corner.

### Expected behavior

Icon should be shown every time.

### Actual behavior

Same as description.

### Steps to reproduce the bug

Same as description.

### Package versions

* Python: Python 2.7.13
* MkDocs: mkdocs, version 0.16.1
* Material: mkdocs-material-1.1.1

### Project configuration

described above

### System information

* OS: alpine

### MkDocs

```yml
site_name: Example

theme: material

site_description: 'Documentation for Example'
site_author: 'exampler'
site_url: 'https://docs.example.com'

#repo_name: 'Example' # ------> toggle this on/off to see bug
repo_url: 'https://github.com/squidfunk/mkdocs-material'

copyright: 'Copyright &copy; 2017 Example'

extra:
  logo: 'img/example.png'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  palette:
    primary: 'indigo'
    accent: 'light blue'

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - admonition
  - codehilite(guess_lang=false)
  - footnotes
  - meta
  - toc(permalink=true)

pages:
  - Home: index.md
  #- ...
```
