### ISSUE TITLE
Search not working if folder name contains space

### ISSUE THREAD

**Issue by krishansubudhi** [squidfunk/mkdocs-material#1960]
__I checked that...__

- [yes ] ... the documentation does not mention anything about my problem
- [ yes] ... the problem doesn't occur with the default MkDocs template
- [ yes] ... the problem is not in any of my customizations (CSS, JS, template)
- [ yes] ... there are no open or closed issues that are related to my problem

## Description
![image](https://user-images.githubusercontent.com/11926616/94865129-efcb1e80-03f1-11eb-9ea1-91b01ca9c3c3.png)
![image](https://user-images.githubusercontent.com/11926616/94865167-fb1e4a00-03f1-11eb-8e03-6eed3746661f.png)
https://elr-documentation.azurewebsites.net/Blogs/Tenant+Personalization/TenantEmbedding

Latest version replaces spaces with + not %20
Previous 5* versions are not showing this issue

replacing with 
https://elr-documentation.azurewebsites.net/Blogs/Tenant%20Personalization/TenantEmbedding
works

### Expected behavior

URL should not throw error

### Actual behavior

Page not found

### Steps to reproduce the bug

add space to sub folder name. and try to search documents in that folder. open a search result.

### Package versions

mkdocs 1.1
mkdocs-materia 6.0.1
lunr 0.5.8

* Python: `python --version`
* MkDocs: `mkdocs --version`
* Material: `pip show mkdocs-material | grep -E ^Version`

### Project configuration

``` yaml
theme:
    name: "material"
    custom_dir: theme-overrides/
    logo: images/Microsoft.png
    features:
        - navigation.tabs
        - navigation.expand
        - search.highlight
    palette:
        - scheme: default
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
        - scheme: slate
          primary: blue
          accent: blue
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
markdown_extensions:
    - meta
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - toc:
        permalink: ⚓︎
plugins:
    - macros
    - search
    - mkdocstrings:
        handlers:
            python
```

### System information

* OS: Windows 10 
* Browser: Edge browser
