### ISSUE TITLE
navigation tabs not showing

### ISSUE THREAD

**Issue by chaostools** [squidfunk/mkdocs-material#1962]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

I am trying to update my old website to the latest versions of mkdocs/material theme but i can't seem to get navigation tabs to work. I made a clean install of mkdocs-material theme. I have found that the latest version uses a different `mkdocs.yml` syntax and I updated accordingly but it still didn't worked.

current mkdocs.yml :  

```yaml
site_name: Curioustools
site_description: Google certified Associate Android Dev
site_author: Ansh Sachdeva(root-ansh) 
site_url: https://root-ansh.github.io/curioustools/ 



theme:
    name: material
    palette:
        primary: 'white'
        accent: 'green'

    feature:
        - navigation.tabs 
 
    language: 'en'    
    extra:
        search:
            language: 'en'
            tokenizer: '[\s\-\.]+'

    logo: assets/logo/logo.svg
    favicon: 'assets/images/favicon.ico'
   
     
 
markdown_extensions:
    - meta
    - markdown.extensions.admonition
    - pymdownx.superfences
    - pymdownx.emoji
      
extra:
    disqus: ..
    social:
        - icon: fontawesome/brands/github
          link: ...
      ...



copyright: ...

nav:
    - About me: index.md
    
    - Education Details:
        - Education Details: tab_edu/edu_details.md
   
```

current folder structure:  

```

/
/docs
	|-a_index_images/  <images used in index folder>
	|assets
		|-images/fevicon.ico
		|-logo/logo.svg
	|-tab_edu/edu_details.md
	|-tab_edu/img/		<images used in edu_details.md>
/site
/mkdocs.yml

```

i am guessing that recent versions have changed the behavior of how articles stored inside folders are rendered and thus is showing all the tabs as side menu. more details in the attached screenshots

### Expected behavior
![image](https://user-images.githubusercontent.com/32802111/94947653-da5a0100-0492-11eb-8cb6-832e699f42c8.png)

---

### Actual behavior

![image](https://user-images.githubusercontent.com/32802111/94947700-ed6cd100-0492-11eb-9a8a-70081b1027fb.png)

notice how the tabs are coming on the side instead of , well tabs

### Steps to reproduce the bug

1. create a project as per given mkdocs.yml and folder structure

### Package versions

* Python: `3.8.5`
* MkDocs: `1.1.2`
* Material: `6.0.1`

### Project configuration

``` yaml  
<given above>
```

### System information

* OS:  windows 10 home
* Browser: chrome
