### ISSUE TITLE
Support tabbed content on print

### ISSUE THREAD

**Issue by timvink** [squidfunk/mkdocs-material#1974]
__I checked that...__

- [x] ... the documentation does not mention anything about my idea
- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea

## Description

When printing, tabbed content does not display (either tab). Example (slate color theme):

![image](https://user-images.githubusercontent.com/5570380/95501747-11f00e00-09a9-11eb-9245-3966a8e4a2bb.png)

### Use Cases

When printing, content of all tabs should at least display. Ideally, the labels for each tab also move along with it. =

### Screenshots / Mockups

```css
@media print {
    .tabbed-content {
        display: block !important;
        padding-bottom: 1em;
    }
}
```

This provides a fix:

![image](https://user-images.githubusercontent.com/5570380/95502289-e7eb1b80-09a9-11eb-9ccc-fc8c6e61d6e2.png)
