### ISSUE TITLE
Search feature failed after upgrading to 6.02

### ISSUE THREAD

**Issue by lanking520** [squidfunk/mkdocs-material#1993]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

If you try to access: https://djl-ai.s3.amazonaws.com/documentation/nightly/docs/index.html and do the search, it will keep doing search initializing...

I have double checked the search.json file is there and accessable.

This issue is not reproducible locally, only online have the issue.

### Expected behavior

Search should bring related result

### Actual behavior

Search is initializing

### Steps to reproduce the bug

We have an action pipeline that allow you to build https://github.com/awslabs/djl/blob/master/.github/workflows/docs.yml

```
pip3 install nbconvert mkdocs mkdocs-exclude mknotebooks mkdocs-material jupyter Pygments
```

### Package versions

mkdocs, version 1.1.2
Python 3.7.3

* Python: `python --version`
* MkDocs: `mkdocs --version`
* Material: `Version: 6.0.1`

### Project configuration

``` yaml
site_name: Deep Java Library
repo_name: awslabs/djl
repo_url: https://github.com/awslabs/djl/
site_url: https://djl.ai
use_directory_urls: false
markdown_extensions:
  - codehilite
  - toc:
      permalink: true
theme:
  name: material
  logo: website/img/DJL.svg
  favicon: website/img/favicon.png
  features:
    - navigation.tabs
  palette:
    primary: light-blue
    accent: light-blue
google_analytics:
  - UA-159559852-2
  - auto
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/awslabs/djl
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/deepjavalibrary
    - icon: fontawesome/brands/slack
      link: https://deepjavalibrary.slack.com/
    - icon: fontawesome/brands/zhihu
      link: https://zhuanlan.zhihu.com/c_1255493231133417472
docs_dir: '../'
plugins:
  - search
  - mknotebooks
  - exclude:
      regex:
        - '.*\.(symbol|params|pt|jar|gz|zip|txt|json|sh|bat|cmd|puml|g4|java|py|cc|h|pro|properties|xml|gradlew|gradle|Dockerfile|RepositoryFactory|EngineProvider|ZooProvider)$|(docker|integration|testing|tools)/.*$'
nav:
  - HOME: 'README.md'
  - 'docs/quick_start.md'
  - 'docs/interactive_tool.md'
  - 'docs/README.md'
  - 'examples/README.md'
  - 'docs/development/README.md'
  - 'docs/roadmap.md'
  - 'docs/faq.md'
  - User manual:
      - 'docs/development/setup.md'
      - 'docs/model-zoo.md'
      - 'docs/dataset.md'
      - 'docs/load_model.md'
      - 'docs/development/configure_logging.md'
      - 'docs/development/cache_management.md'
      - 'docs/development/memory_management.md'
      - 'docs/development/how_to_use_dataset.md'
      - 'docs/how_to_collect_metrics.md'
      - 'docs/development/troubleshooting.md'
      - 'docs/development/inference_performance_optimization.md'
  - MXNet:
      - Overview: 'mxnet/README.md'
      - MXNet Engine: 'mxnet/mxnet-engine/README.md'
      - MXNet Model Zoo: 'mxnet/mxnet-model-zoo/README.md'
      - MXNet native library: 'mxnet/native/README.md'
      - Import Gluon Model: 'docs/mxnet/how_to_convert_your_model_to_symbol.md'
      - Load a MXNet Model: 'jupyter/load_mxnet_model.ipynb'
  - ONNX Runtime:
      - Overview: 'onnxruntime/onnxruntime-engine/README.md'
      - ONNX runtime Hybrid Engine: 'docs/onnxruntime/hybrid_engine.md'
      - Load a ONNX Model: 'jupyter/onnxruntime/machine_learning_with_ONNXRuntime.ipynb'
  - PyTorch:
      - Overview: 'pytorch/README.md'
      - PyTorch Engine: 'pytorch/pytorch-engine/README.md'
      - PyTorch Model Zoo: 'pytorch/pytorch-model-zoo/README.md'
      - Pytorch native library: 'pytorch/pytorch-native/README.md'
      - Import PyTorch Model: 'docs/pytorch/how_to_convert_your_model_to_torchscript.md'
      - Load a PyTorch Model: 'jupyter/load_pytorch_model.ipynb'
  - TensorFlow:
      - Overview: 'tensorflow/README.md'
      - TensorFlow Engine: 'tensorflow/tensorflow-engine/README.md'
      - TensorFlow Model Zoo: 'tensorflow/tensorflow-model-zoo/README.md'
      - Import TensorFlow Model: 'docs/tensorflow/how_to_import_tensorflow_models_in_DJL.md'
      - Load a TensorFlow Model: 'jupyter/tensorflow/pneumonia_detection.ipynb'
  - Extensions:
      - Android: 'android/README.md'
      - AWS S3 support: 'extensions/aws-ai/README.md'
      - Hadoop support: 'extensions/hadoop/README.md'
```

### System information

Hosted on S3 which runs on a Linux machine
