### ISSUE TITLE
Unnecessary leading empty lines in index.html

### ISSUE THREAD

**Issue by pwwang** [squidfunk/mkdocs-material#2020]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

Unnecessary leading empty lines in index.html causing 404 in GH pages.

### Expected behavior

`<!doctype ...` should be in the first line of the output HTML files.

### Actual behavior

Leading empty lines observed.

### Steps to reproduce the bug

1. mkdocs build
2. head site/index.html

### Package versions

* Python: `python --version` 3.7.3
* MkDocs: `mkdocs --version` 1.1.2
* Material: `pip show mkdocs-material | grep -E ^Version` 6.1.0

### Project configuration

``` yaml
site_name: liquidpy
theme:
    name: 'material'
markdown_extensions:
    - markdown.extensions.admonition
    - pymdownx.superfences:
        preserve_tabs: true
    - toc:
        baselevel: 2
extra_css:
    - style.css
nav:
    - 'Home': 'index.md'
```
And the head of my `index.md` (no leading empty lines):
```markdown
# liquidpy
A port of [liquid][1] template engine for python
```

### System information

* OS: Linux <hostname> 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 11 19:12:04 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux
* Browser: Chrome Version 73.0.3683.86

Also refer to this issue: https://github.com/mkdocs/mkdocs/issues/2180

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md
