### ISSUE TITLE
Admonitions not rendering

### ISSUE THREAD

**Issue by ehguille** [squidfunk/mkdocs-material#2045]
Everything was alright until I tried to use admonitions.

I have this segundo.md page:

```
 ??? optional-class "Summary"
     Here's some content.

 ??? multiple optional-class "Summary"
     Here's some content.
```

And this mkdocs.yml:

```
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: default
    primary: blue grey
    accent: blue
  language: es
  features:
    - search.suggest
    - header.autohide
  markdown_extensions: 
    - pymdownx.highlight
    - pymdownx.superfences
    - admonition
    - footnotes
    - pymdownx.superfences
    - pymdownx.details
    - toc:
      permalink: true
    - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
```

And this is the obteined code after `mkdocs build`:

```
                <p>??? optional-class "Summary"
     Here's some content.</p>
<p>??? multiple optional-class "Summary"
     Here's some content.</p>
```

Thank you for your work.
