### ISSUE TITLE
Cannot get syntax highlighting with fenced_code

### ISSUE THREAD

**Issue by welkie** [squidfunk/mkdocs-material#207]
## Description

When I install the theme using its default settings, I cannot see syntax highlighting on fenced code (like on GitHub). I also cannot get it working by manually including the highlight.js JS and CSS files.

### Expected behavior

Syntax highlighting for fenced code.

### Actual behavior

Fenced code is monospaced but all black.

### Steps to reproduce the bug

1. Create fenced code block, using for example "javascript" or "ruby".
2. Run ```mkdocs serve``` or perform a build and visit the pages.
3. Observe the fenced code.

### Package versions

* Python: 2.7.12
* MkDocs: 0.16.1
* Material: 1.2.0

### Project configuration

``` yaml
site_name: My Docs
pages:
  - Home: index.md
  - Tutorials:
    - AWS: tutorials/aws.md
    - Google Cloud:
      - Main: tutorials/google-cloud.md
      - Some Other: tutorials/google-cloud-some-other.md
  - Documentation: documentation.md
theme: material # custom theme: http://squidfunk.github.io/mkdocs-material
```

### System information

* OS: Ubuntu 16.04
* Browser: Chrome
