### ISSUE TITLE
Table box-shadow does not change with slate theme

### ISSUE THREAD

**Issue by kratsg** [squidfunk/mkdocs-material#2083]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

data tables have scss where the box-shadow color does not change with the theme.

https://github.com/squidfunk/mkdocs-material/blob/b72314d7da0e7c8bd2dda2f45c21d9cf55557706/src/assets/stylesheets/main/_typeset.scss#L475-L486

### Expected behavior

I expected the box shadow to lighten up on a slate theme so that the data tables do not blend in completely with the slate background.

<img width="684" alt="Screen Shot 2020-12-01 at 7 56 43 AM" src="https://user-images.githubusercontent.com/761483/100743798-cf482200-33aa-11eb-8e0c-7b24d11b129c.png">

This could be achieved with the following custom CSS added

```css
/* fix box shadow for dark theme */
body[data-md-color-scheme="slate"] .md-typeset table:not([class]) {
  box-shadow: 0 0.2rem 0.5rem rgba(255,255,255,.05), 0 0 0.05rem rgba(255,255,255,.1);
}
```

### Actual behavior

box-shadow remains dark, even on a slate theme. 
  
<img width="664" alt="Screen Shot 2020-12-01 at 7 51 16 AM" src="https://user-images.githubusercontent.com/761483/100743268-18e43d00-33aa-11eb-8686-86cd6d97a211.png">

### Steps to reproduce the bug

Enable slate theme in `mkdocs.yml`

```yaml
theme:
  palette:
    scheme: slate
```

then build and look at a data table in the docs.

### Package versions

* Python: `python --version`
* MkDocs: `mkdocs --version`
* Material: `pip show mkdocs-material | grep -E ^Version`

```
bash-4.2$ python --version
Python 3.6.9
bash-4.2$ mkdocs --version
mkdocs, version 1.1 from /opt/app-root/venv/lib64/python3.6/site-packages/mkdocs (Python 3.6)
bash-4.2$ pip show mkdocs-material | grep -E ^Version
Version: 5.5.14
```

### Project configuration

```yaml
theme:
  palette:
    scheme: slate
    primary: blue
    accent: light blue
  name: material
  icon:
    logo: octicons/rocket-16
    repo: fontawesome/brands/gitlab

plugins:
  - search
  - mknotebooks:
      execute: false
      write_markdown: false
  - bibtex:
      bib_file: "docs/refs.bib"
      cite_style: "pandoc"
      full_bib_page: "/references"
  - mermaid2:
      arguments:
          theme: 'dark'
```

### System information

* OS: mkdocs docker image
* Browser: Mac OS Chrome Version 86.0.4240.198 (Official Build) (x86_64)

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md
