### ISSUE TITLE
Theme is not deployed with mkdocs gh-deploy

### ISSUE THREAD

**Issue by afaucogney** [squidfunk/mkdocs-material#2104]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

Theme is not deployed with mkdocs gh-deploy

### Expected behavior

Get the theme deployed

### Actual behavior

Theme is not deployed / setup

### Steps to reproduce the bug

- I used mkdocs + dokka to build a static web site : `mkdocs build`
- I serve with : `mkdocs serve`. On local server I can see the site with its them
- When I `mkdocs gh-deploy` the site is theme-less

### Package versions

* Python: `python --version` . 3.9
* MkDocs: `mkdocs --version` 1.1.2
* Material: `pip show mkdocs-material | grep -E ^Version` 6.1.7

### Project configuration

``` yaml
# pip install mkdocs mkdocs-material
# mkdocs serve
# mkdocs gh-deploy

extra:
  flipper_ktp:
    release: '0.1.0'
    next_release: '0.1.1'
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/afaucogney
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/afaucogney
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/questions/tagged/toothpick-di?sort=active

site_name: Flipper Ktp
site_url: https://afaucogney.github.io/flipper-ktp/
repo_name: Flipper-Ktp
repo_url: https://github.com/afaucogney/flipper-ktp
edit_uri: edit/main/docs/
site_description: "A flipper plugin to analyse Toothpick DI runtime scope tree"
site_author: Anthony FAUCOGNET
remote_branch: gh-pages

copyright: 'Copyright &copy; 2020 Anthony Faucogney'

theme:
  name: 'material'
  custom_dir: 'docs/theme'
  logo: 'images/logo.jpg'
  icon:
    repo: fontawesome/brands/github
  favicon: 'images/logo.jpg'
  palette:
    primary: 'light-blue'
    accent: 'deep-amber'
  features:
    - tabs

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.emoji
  - tables
  - admonition

plugins:
  - search
  - markdownextradata: {}

nav:
  - 'Overview': index.md
  - 'Getting Started': getting_started.md
  - 'Fundamentals':
      - 'Introduction': fundamentals.md
      - 'How Flipper works': fundamentals-how-flipper-works.md
      - 'How Ktp works': fundamentals-how-ktp-works.md
      - 'How Flipper-Ktp works': fundamentals-how-flipper-ktp-works.md
  - 'Help & Community':
      - 'Code recipes': recipes.md
      - 'FAQ': faq.md
      - 'Support': support.md
      - 'Stack Overflow ⏏': https://stackoverflow.com/questions/tagged/toothpick-di?sort=active
  - 'Contributing':
#          - 'Code of Conduct': code_of_conduct.md
      - 'Dev Environment': dev-env.md
      - 'Releasing': releasing.md
      - 'How to help': how_to_help.md
  - 'Flipper Ktp Api':
      - 'KtpFlipperPlugin': api/flipper-ktp/index.md
  - 'Change Log': changelog.md
```

### System information

* OS: ...
* Browser: ...

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md
