### ISSUE TITLE
Top-level pages aren't grouped under the first tab

### ISSUE THREAD

**Issue by fveauvy** [squidfunk/mkdocs-material#2125]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

Since I upgraded to mkdocs-material 6.1.7 and mkdocs-material-insiders 1.13.0, it seems that top-level pages aren't grouped under the first tab anymore when I use tab navigation.

### Expected behavior

According to the [navigation tabs doc](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs), all top-level pages defined inside the nav entry of mkdocs.yml should be grouped under the first tab and should receive the title of the first page.

### Actual behavior

Top level pages are defined as tabs.

### Steps to reproduce the bug

1. Create a new mkdocs-material project
2. Add top-levels pages to the nav
3. Enable the feature navigation.tabs
4. Serve

### Package versions

* Python: `python --version` 3.7.7
* MkDocs: `mkdocs --version` 1.1
* Material: `pip show mkdocs-material | grep -E ^Version` 6.1.7+insiders.1.13.0

### Project configuration

``` yaml
site_name: Test Nav
site_description: Test Nav

theme:
  name: material
  features:
    - navigation.tabs

nav:
  - Home: index.md
  - Top Level: top-level.md
  - Nav:
      - nav/second-level-1.md
      - nav/second-level-2.md
```

### System information

* OS: MacOS Catalina 10.15.7 
* Browser: Chrome Version 87.0.4280.88 (Build officiel) (x86_64)

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
That's intended behavior for the latest Insiders release and part of the navigation refactoring. I'm sorry this wasn't clear enough from the changelog. The "group under first tab" behavior seemed like a great idea at start but it led to a lot of confusion among users and doesn't allow to put [single pages](https://github.com/squidfunk/mkdocs-material/issues/2072) or links into the tabs navigation, which is why I simplified the business logic to follow a 1:1 mapping.

You should get the same layout, if you regroup your pages like this:

``` yaml
nav:
  - Your project name:
    - Home: index.md
    - Top Level: top-level.md
  - Nav:
      - nav/second-level-1.md
      - nav/second-level-2.md
```

The only thing where this deviates is that the tab is now not called "Home" anymore but "Your project name", which Material for MkDocs showed as the title of the sidebar with the old grouping behavior. The [section index plugin](https://github.com/squidfunk/mkdocs-material/issues/2060) may help to get rid of this behavior, but it may not yet work with the latest Insiders. When the goal is reached, I'll check how we can integrate a solution to allow index pages, which should give full flexibility again.
