### ISSUE TITLE
Global glossary page shortcode not parsing correctly?

### ISSUE THREAD

**Issue by IronicBadger** [squidfunk/mkdocs-material#2161]
[This feature](https://github.com/squidfunk/mkdocs-material/issues/1919) looks very useful indeed - sorry to necrobump but I'm not able to get it to work. Building in the material docker container. Using `squidfunk/mkdocs-material:6.2.2` via latest tag. Followed docs at [this page](https://squidfunk.github.io/mkdocs-material/reference/abbreviations/#snippets) and have the following relevant sections in config files.

```
# mkdocs.yml
plugins:
  - git-revision-date
  - search
  - minify:
      minify_html: true
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - footnotes
  - meta
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
```

Just `-abbr` and `-pymdownx.snippets` ought to be enough right? You can see below that the theme is not detecting the `--8<--` shortcode used to find the includes file. This feature works if the glossary is defined in the file itself so I'd be grateful for any assistance.

![image](https://user-images.githubusercontent.com/2773080/103163778-9c8a2180-47d0-11eb-99f6-f3084cf042e5.png)

And here is the file structure of the repo - I think I'm doing everything correctly...

![image](https://user-images.githubusercontent.com/2773080/103163833-51244300-47d1-11eb-8aca-3380e915a776.png)
