### ISSUE TITLE
Can't hide ToC if it's integrated in navigation

### ISSUE THREAD

**Issue by danierutu** [squidfunk/mkdocs-material#2162]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

When using the `toc.integrate` feature flag, the Table of Contents can't be hidden per-file using metadata. However, it does work flawlessly without the feature.

### Expected behavior

Hiding the ToC on metadata prevents it from appearing in that page, no matter if `toc.integrate` is being used.

### Actual behavior

Hiding the ToC on metadata prevents it from appearing, only if `toc.integrate` is **not** being used.

### Pictures

Here you have a couple screenshots, both showing the metadata of the test file and the state of the feature.

![disabled](https://user-images.githubusercontent.com/63101447/103325587-a15b0980-4a4c-11eb-9f0e-9e3f0b00a10c.png)
![enabled](https://user-images.githubusercontent.com/63101447/103325619-cf404e00-4a4c-11eb-8c5b-3660b803ed97.png)

### Steps to reproduce the bug

1. Add the [navigation integration](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-integration) feature to `mkdocs.yml`.
2. [Hide the ToC](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#hide-the-sidebars) for a file with some headings. ToC will still be visible.
3. Delete (or comment) the feature and reload the site. ToC will disappear.

### Package versions

* Python: 3.9.0
* MkDocs: 1.1.2
* Material: 6.2.3

### Project configuration

``` yaml
theme:
  name: material
  custom_dir: theme
  logo: assets/img/logo.png
  favicon: assets/img/favicon.png
  palette:
    scheme: preference
    primary: deep purple
    accent: deep purple
  features:
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - toc.integrate
```

### System information

* OS: Windows 10 (20H2)
* Browser: Firefox 84.0.1

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md
