### ISSUE TITLE
Get White page after scroll

### ISSUE THREAD

**Issue by MahdiMajidzadeh** [squidfunk/mkdocs-material#2212]
- [X] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [X] ... the problem doesn't occur with the default MkDocs template
- [X] ... the problem is not in any of my customizations (CSS, JS, template)
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

## Description

in long page and in rtl mode, when scrolling down, page get white and we have a horizontal scroll

### Actual behavior

![image](https://user-images.githubusercontent.com/6115476/104778943-759d8a80-5793-11eb-8653-0bfc2c7755ae.png)
https://ads.basalam.com/help/create-ad/

### Package versions

* Python: `Python 3.8.1`
* MkDocs: `mkdocs, version 1.1.2`
* Material: `Version: 6.2.4`

### Project configuration

``` yaml
site_name: راهنمای سیستم تبلیغات باسلام

site_url: 'https://ads.basalam.com/help/'

copyright: 'تمامی حقوق برای شرکت باسلام و غرفه داران آن محفوظ است.'

google_analytics: ['UA-90601872-8', 'ads.basalam.com']

theme:
    name: material
    custom_dir: 'material'
    language: fa
    font: false
    palette:
        primary: '#ccc'
        accent: red
    features:
        - navigation.expand
        - search.highlight
        - header.autohide
        - navigation.instant
        - toc.autohide
    logo: images/logo.ads.svg
    favicon: images/logo.ads.svg

extra_css: 
    - 'extra/style.css'  

markdown_extensions:
    - attr_list
    - tables
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - admonition
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.smartsymbols
    - pymdownx.tabbed
    - pymdownx.betterem:
        smart_enable: all
    - toc:
        permalink: true
        slugify: !!python/name:pymdownx.slugs.uslugify

plugins:
    - search:
        prebuild_index: true
        lang:
            - en
            - ar
    - minify:
        minify_html: true
```

### System information

* OS: ...
* Browser: ...

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md
