### ISSUE TITLE
Edit button does not respect custom directories

### ISSUE THREAD

**Issue by BD103** [squidfunk/mkdocs-material#2234]
## Description

Hi! I have noticed that the edit button on material sites with repositories linked does not respect custom directories. 

### Expected behavior

When you go to a page on the website, the pencil icon to the right should open an editable version of the file on Github.

### Actual behavior

This works most of the time, but since I used Github Pages, I have to reserve the "docs" directory for the final build of the static site. Because of this, I changed the source markdown files to a directory called "src". The pencil continues to link the to "docs" folder, but the file cannot be found because there are only html files.

### Steps to reproduce the bug

1. Create a standard Material MkDocs website
2. Create a repo and add Github pages, building from the "docs" directory
3. In mkdocs.yml, set the following:

```yml
docs_dir: src
site_dir: docs
```

4. Also link the repository with `repo_url` and `repo_name`.
5. Build the site, and wait for Github Pages to host.
6. Try editing a site, and see it return a 404 error.

### Package versions

* Python: 3.8.7
* MkDocs: 1.1.2
* Material: 6.2.5

### Project configuration

``` yaml
site_name: BD103
site_url: https://bd103.github.io
site_author: BD103
site_description: Personal Blog / Portfolio of BD103
repo_name: bd103.github.io
repo_url: https://github.com/BD103/bd103.github.io
copyright: Copyright &copy; 2020 BD103
docs_dir: src
site_dir: docs
nav:
    - Home: index.md
    - About: about.md
    - Projects:
      - Python Package: https://github.com/BD103/Package/wiki
      - MkDocs Helper: https://mkdocs-helper.bd103.repl.co
      - Image Flipper: projects/image-flipper.md
      - Text Dump Engine: projects/text-dump-engine.md
      - Notepad: projects/notepad.md
    - Tutorials:
      - Make a Rest API with Python: tutorials/rest-api.md
    - Ideas:
      - Waveform: ideas/waveform.md
    - License: license.md
theme:
    name: material
    favicon: imgs/cpu-16.svg
    palette:
      scheme: default
      primary: blue
      accent: light blue
    language: en
    icon:
      logo: octicons/cpu-24
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
extra:
  social:
    - icon: octicons/code-review-16
      link: https://repl.it/@BD103
    - icon: fontawesome/brands/github
      link: https://github.com/BD103
```

You can find more information at https://github.com/BD103/bd103.github.io

### System information

I edit through an online IDE called [Replit](https://repl.it). I'm not quite sure of the stats, but I use a Bash Repl.
