### ISSUE TITLE
Which css element is controlling the position of white background of article part?

### ISSUE THREAD

**Issue by Hitaro** [squidfunk/mkdocs-material#23]
Hi, Because of a Japanese work, I needed to move the 'drawer' sidebar  to right side: `.drawer { float: right; }`. I did it successfully. And I also set other elements to be compatible.

But, I couldn't push the white background (of `article`) to left side; Which element is controlling it?!

Plus: Instead of manipulating original theme css files, is there any option to inject custom css' to the layout via config file (mkdocs.yml)?

Kind regards

**Comment by squidfunk** [comment]
Hi there,

the `backdrop` div is controlling the paper element. You just have to set the left margin as right margin on the `:after` pseudo selector:

``` css
.backdrop-paper:after {
  content: " ";
  display: block;
  height: 100%;
  margin-right: 262px;
}
```

There actually is a possibility of providing extra css and it's documented:
http://squidfunk.github.io/mkdocs-material/customization/#small-tweaks
