### ISSUE TITLE
Adding content below sidebar in customized template results in JavaScript error

### ISSUE THREAD

**Issue by ngtrian** [squidfunk/mkdocs-material#230]
I have an error in console browser when scroll page to footer

```
Uncaught TypeError: Cannot read property 'offsetTop' of undefined
    at t.value (application-3964c0cb56.js:2)
    at update_ (application-3964c0cb56.js:1)

```
Chrome version: 57

**Comment by squidfunk** [comment]
Please use the issue template and provide more information.

**Comment by ngtrian** [comment]
## Description

I have customized the theme, I have added a social share button inside the block block site_nav, located in bottom of the div class **md-sidebar__scrollwrap**

And this is all content in file **main.html**
``` html
{% block site_nav %}
{% if nav %}
    <div class="md-sidebar md-sidebar--primary" data-md-component="navigation">
    <div class="md-sidebar__scrollwrap">
        <div class="md-sidebar__inner">
        {% include "partials/nav.html" %}
        </div>
    </div>
    </div>
{% endif %}
{% if page.toc %}
    <div class="md-sidebar md-sidebar--secondary" data-md-component="toc">
    <div class="md-sidebar__scrollwrap">
        <div class="md-sidebar__inner">
        {% include "partials/toc.html" %}
        </div>
        <div class="share-social">   
            <p class="md-nav md-nav__title">Chia sẻ: </p>
            <a class="share-twitter" href="https://twitter.com/intent/tweet?text={{ page.title }} - {{ config.site_name }}&url={{ page.canonical_url }}&hashtags=nopcommerce,nopviet,nopcommercevietnam&via=nopviet" onclick="window.open(this.href, '_blank', 'width=450, height=300, resizable=yes'); return false;">
                <i class="fa fa-twitter fa-2x md-nav__item" aria-hidden="true" style="color: #1da1f2;"></i>
            </a>
        </div>
    </div>
    </div>
{% endif %}
{% endblock %}
```

### Expected behavior

I checked, if tag a has no href attribute, no error occurs.

### Actual behavior

I have an error in console browser when scroll page to footer
```Uncaught TypeError: Cannot read property 'offsetTop' of undefined
    at t.value (application-3964c0cb56.js:2)
    at update_ (application-3964c0cb56.js:1)
```
### Package versions

* Python: `2.7.12`
* MkDocs: `0.16.2`
* Material: `1.41`

### Project configuration

``` yaml
site_name: nopCommerce Docs
site_url: http://docs.nopviet.com
site_description: Tài liệu nopCommerce | docs.nopviet.com
site_author: nopViet Team
site_favicon: favicon.png
repo_url: http://nopviet.com
repo_name: nopViet.com

theme: material

theme_dir: custom_material
#theme_dir: mkdocs-material/material

extra_css:
  - css/extra.css

extra_javascript:
#  - js/extra.js
#  - https://cdnjs.cloudflare.com/ajax/libs/jquery.colorbox/1.6.4/jquery.colorbox-min.js

extra:
  feature:
    tabs: false
  palette:
    primary: 'indigo'
    accent: 'light blue'
  social:
    - type: globe
      link: http://nopviet.com
    - type: facebook-official
      link: https://www.facebook.com/nopviet/
    - type: twitter
      link: https://twitter.com/nopviet
    - type: skype
      link: skype:ngtrian?chat
    
google_analytics:
  - 'UA-39056872-8'
  - 'auto'

# Copyright
copyright: 'Copyright &copy; 2017 <a href="http://nopviet.com/" title="nopCommerce Vietnam Community"> nopViet | Cộng đồng nopCommerce Việt Nam</a>'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: "#"
      # Xử lý ký tự "đ" khi tạo header id
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  
pages:
    - Giới thiệu: index.md
    - Sử dụng nopCommerce: 
      - Bắt đầu: user-guide/bat-dau-voi-nopcommerce.md
      - Cài đặt nopCommerce: user-guide/cai-dat-nopcommerce.md
      - Thiết lập cửa hàng:
        - Giao diện trang quản trị: user-guide/giao-dien-quan-tri.md
        - Thiết lập cửa hàng:
          - Thiết lập cơ bản: user-guide/thiet-lap-co-ban.md
          - Thiết lập thanh toán: user-guide/thiet-lap-thanh-toan.md
          - Thiết lập thuế: user-guide/thiet-lap-thue.md
          - Thiết lập giao hàng: user-guide/thiet-lap-giao-hang.md
          - Thiết lập khách hàng: user-guide/thiet-lap-khach-hang.md
          - Tất cả thiết lập (nâng cao): user-guide/thiet-lap-nang-cao.md
        - Quản trị hệ thống: user-guide/quan-tri-he-thong.md
        - Giao diện nopCommerce: user-guide/giao-dien-nopcommerce.md
      - Khởi chạy cửa hàng:
        - Quản lý sản phẩm: user-guide/quan-ly-san-pham.md
        - Quản lý đơn hàng: user-guide/quan-ly-don-hang.md
        - Quản lý khách hàng: user-guide/quan-ly-khach-hang.md
        - Lập báo cáo: user-guide/lap-bao-cao.md
      - Tiếp thị cửa hàng:
        - Công cụ quảng cáo: user-guide/cong-cu-quang-cao.md
        - Quản lý nội dung: user-guide/quan-ly-noi-dung.md
      - Tài liệu hướng dẫn cho các version cũ: user-guide/tai-lieu-nopcommerce-khac.md
    - Phát triển nopCommerce: 
      - Tut hướng dẫn phát triển: developer-guide/tut-developer.md
      - Tạo plugin nopCommerce:
        - Cách viết plugin nopCommerce: developer-guide/cach-viet-plugin-nopcommerce.md
        - Cách viết phương thức thanh toán riêng: developer-guide/cach-viet-phuong-thuc-thanh-toan-rieng.md
        - Cách viết phương thức giao hàng riêng: developer-guide/cach-viet-phuong-thuc-giao-hang-rieng.md
        - Plugin với truy cập dữ liệu: developer-guide/plugin-voi-truy-cap-du-lieu.md
        - Cách tạo menu cho plugin trong trang quản trị: developer-guide/cach-tao-menu-plugin.md
        - Thêm CSS và JS vào plugin nopCommerce: developer-guide/them-css-va-js-vao-plugin.md
        - Video hướng dẫn tạo plugin: developer-guide/video-huong-dan-tao-plugin.md
        - Khóa học về phát triển plugin nopCommerce: developer-guide/khoa-hoc-phat-trien-plugin.md
      - Hướng dẫn thiết kế giao diện: developer-guide/huong-dan-thiet-ke.md
    - Các câu hỏi thường gặp (FAQ): faq-nopcommerce.md
```

### System information

* OS: Windows 10
* Browser: Chrome

**Comment by squidfunk** [comment]
Well, this is some issue which happens because of your customization. However, I will look into the code and see if I can make the part that causes the error more robust in regard to additions/customizations. Nevertheless this is a low priority issue.
Maybe you can try putting your stuff inside the `__inner` wrapper. That should work.

**Comment by ngtrian** [comment]
I have move my stuff inside `md-sidebar__inner` , still have an error

**Comment by squidfunk** [comment]
I cannot reproduce your error. Please try the latest version which is 1.5.1. This works for me:

``` yml
# mkdocs.yml
site_name: My Docs
repo_url: http://github.com/mkdocs/mkdocs
repo_name: foobar
edit_uri: /
theme: material
theme_dir: theme
```

``` jinja
<!-- theme/main.html -->
{% extends "base.html" %}

{% block site_nav %}
  {% if nav %}
    <div class="md-sidebar md-sidebar--primary" data-md-component="navigation">
      <div class="md-sidebar__scrollwrap">
        <div class="md-sidebar__inner">
          {% include "partials/nav.html" %}
        </div>
      </div>
    </div>
  {% endif %}
  {% if page.toc %}
    <div class="md-sidebar md-sidebar--secondary" data-md-component="toc">
      <div class="md-sidebar__scrollwrap">
        <div class="md-sidebar__inner">
          {% include "partials/toc.html" %}
        </div>
        <div class="share-social">
          <p class="md-nav md-nav__title">Chia sẻ: </p>
          <a class="share-twitter" href="https://twitter.com/intent/tweet?text={{ page.title }} - {{ config.site_name }}&url={{ page.canonical_url }}&hashtags=nopcommerce,nopviet,nopcommercevietnam&via=nopviet" onclick="window.open(this.href, '_blank', 'width=450, height=300, resizable=yes'); return false;">
            <i class="fa fa-twitter fa-2x md-nav__item" aria-hidden="true" style="color: #1da1f2;"></i>
          </a>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}
```

It also works when putting it into `md-sidebar__inner`
