### ISSUE TITLE
CSS not loading in Github Pages

### ISSUE THREAD

**Issue by k4he1** [squidfunk/mkdocs-material#2311]
Hello, I'm trying to load my documentation website into GitHub pages but the CSS doesn't load. **(Only on Github Pages the website doesn't load property, on the desktop it works properly.)**

### Expected behavior

CSS loading

### Actual behavior

CSS not loading

### Package versions

* Python: 3.9.1
* MkDocs: 1.1.2
* Material: 6.2.8

### Project configuration

``` yaml
site_name: BetterCommands

theme:
  name: material
  favicon: images/icon.png
  logo: images/icon.png
  palette:
    scheme: slate
    primary: blue grey
    accent: blue grey
  font:
    text: Roboto
    code: Ubuntu Mono
  hljs_languages:
    - lua
```

### System information

* OS: Windows
* Browser: Chrome

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md
