### ISSUE TITLE
Go to Top button

### ISSUE THREAD

**Issue by Valdes-Tresanco-MS** [squidfunk/mkdocs-material#2319]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description
I am currently using your theme for my program's documentation and it is excellent. However, when the page is very long, you do not have access to either the tab bar or the footer buttons.

So, I looked through all the issues, documentation, etc., and couldn't find the `Go to top` button.

I implemented a discrete button with the following characteristics:
- Simple and small
- displayed when scroll moves down 30px
- hides when the footer is visible
- is in the lower right corner
- reduced edges and transparent background

Cons:
- In smartphone view, you can overlay body text

I implemented it in the `main.html` template which I override, but it would be great if it becomes a native implementation
I don't have much experience with HTML, CSS, and javascript, but for now, it does what I need. I am convinced that you will do an excellent job ( if you implement it :-) )

Best!
Mario

### Use Cases
Any page in which the header and footer are not visible at the same time

### Screenshots / Mockups
Desktop view

https://user-images.githubusercontent.com/36672242/108635063-03336080-744b-11eb-97c9-dc6a7d4369eb.mp4

Smartphone view

https://user-images.githubusercontent.com/36672242/108635108-67562480-744b-11eb-9098-a04c1a0b6baa.mp4

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by Valdes-Tresanco-MS** [comment]
Hi @squidfunk 
I forgot the code. I hope it helps

Best!

HTML
```html
<button onclick="topFunction()" id="topbtn" title="Go to top"> </button>
```
javascript
```javascript
var topbtn = document.getElementById("topbtn");
var footer = document.getElementsByTagName('footer')

function isScrolledIntoView(el) {
    var elemTop = el.getBoundingClientRect().top;
    var elemBottom = el.getBoundingClientRect().bottom;
    return (elemTop >= 0) && (elemBottom <= window.innerHeight);
}

window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if ((document.body.scrollTop > 30 || document.documentElement.scrollTop > 30) && !(isScrolledIntoView(footer[0])) ) {
    topbtn.style.display = "block";
  } else {
    topbtn.style.display = "none";
  }
}

// Scroll to top
function topFunction() {
  document.body.scrollTop = 0;
  document.documentElement.scrollTop = 0;
}
```
CSS
```css
#topbtn{
    color:black;
    padding-top:1.8em;
    border-color:black;
    text-decoration:none;
    transition:all .3s ease-out;
    display: none;
    position: fixed;
    bottom: 25px;
    right: 25px;
    z-index: 99;
    border: none;
    outline: none;
    background-color: transparent;
    cursor: pointer;
    border-radius: 4px;
}
#topbtn:before{
	content:'⇡';
	font-size:1.2em;
	position:absolute;
	top:0;
	left:50%;
	margin-left:-.7em;
	border:solid .13em black;
	border-radius:5em;
	width:1.4em;
	height:1.6em;
	line-height:1.3em;
	transition:transform .5s ease-in;
}
#topbtn:hover{
	color:pink;
	border-color:pink;
}
#topbtn:hover:before{
	transform: rotate(360deg);
}
```
