### ISSUE TITLE
Version selector missing

### ISSUE THREAD

**Issue by aratare-jp** [squidfunk/mkdocs-material#2347]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description
Hi there. I'm following https://github.com/squidfunk/mkdocs-material-example-versioning and it seems that I can't create the version selector like stated in the doc.

![image](https://user-images.githubusercontent.com/58905307/109169093-0bc0c980-77b2-11eb-92cf-1ae8024a7cda.png)

### Expected behavior
There should be a version selector.

### Actual behavior
There is none.

### Steps to reproduce the bug

```bash
pip install mike
git clone https://github.com/squidfunk/mkdocs-material-example-versioning.git`
cd mkdocs-material-example-versioning
mike deploy --update-aliases 0.1 latest
mike set-default latest
mike deploy --update-aliases 0.2 latest
mike serve
# or
mkdocs serve
```
### Package versions

* Python: `3.9.1`
* MkDocs: `1.1.2`
* Material: `6.2.8`

### Project configuration

``` yaml
# Project information
site_name: My Docs
site_url: https://squidfunk.github.io/mkdocs-material-example-versioning/
site_author: Martin Donath

# Repository
repo_name: squidfunk/mkdocs-material-example-versioning
repo_url: https://github.com/squidfunk/mkdocs-material-example-versioning
edit_uri: ""

# Configuration
theme:
  name: material

# Customization
extra:
  version:
    method: mike
```

### System information

* OS: Windows 10
* Browser: Chrome

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for reporting! The README wasn't up to date, so it's probably related to the fact that `method` was renamed to `provider`:

Before:

``` yaml
extra:
  version:
    method: mike
```

Now:

``` yaml
extra:
  version:
    provider: mike
```
