### ISSUE TITLE
Change Disqus default font color

### ISSUE THREAD

**Issue by pentamorfico** [squidfunk/mkdocs-material#2351]
Hi @squidfunk! 

First of all, thanks a lot for your great work! Enjoying it so much. 

When I enable the "slatte" palette in the theme section, the text font in the Disqus comments does not changes from gray to white and it is pretty hard to read. Is there any way to deal with this without having to "extend" the theme?

My config:

```
markdown_extensions:
  - abbr
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

theme:
  features:
    - navigation.tabs
  name: material
  palette:
    scheme: slate 
    primary: teal
  icon:
    logo: material/robot-happy

plugins:
  - mknotebooks

extra:
  disqus: <my_disqus_name>

```
Images:

![imagen](https://user-images.githubusercontent.com/33562350/109297367-2a66a500-7832-11eb-8e2f-bbf03583849e.png)
![imagen](https://user-images.githubusercontent.com/33562350/109297395-35213a00-7832-11eb-8636-5504ba708823.png)
