### ISSUE TITLE
[BUG(UI)]: Permalink wrapping disrupts typography

### ISSUE THREAD

**Issue by polarathene** [squidfunk/mkdocs-material#2369]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

Technically this might be more of a MkDocs upstream issue, but I'm rather certain the active maintainer there would reject resolving it (based on past threads I've seen their involvement in at least, he would defer it to theme maintainers instead).

Github handles this by floating the symbol to the left (which is a bit more consistent in location predictability tbh). They use the following CSS:

```css
float: left;
padding-right: 4px;
margin-left: -20px;
```

Perhaps supporting that by default isn't desirable without a breaking change release. I'm also aware that you might just suggest I add custom CSS to maintain this myself and close the issue. I'm just sharing this UX issue for the benefit of others since it's obviously not a desirable side-effect to encounter.

### Expected behavior

Ideally would look like this:

![_expected](https://user-images.githubusercontent.com/5098581/109456713-48483a00-7abe-11eb-91da-6094ad01e4a8.png)

This requires the permalink symbol to not contribute to the width which would collapse.

### Actual behavior

Permalink is wrapped to a new line introducing a large blank space, inconsistent with typography of other headings:

![_actual](https://user-images.githubusercontent.com/5098581/109456638-2353c700-7abe-11eb-9c4e-36920cc1a8ab.png)

### Steps to reproduce the bug

1. Enable `toc.permalink`.
2. Have a heading that is roughly the width of the document containers width.
3. Notice that visually there's a big blank line, inconsistent with other headers.
4. Mouse over and realize it's a hidden permalink symbol.

### Package versions

Current Docker image release (7.x)

### Project configuration

Standard instance should do the trick, this is an internal bug. Using the `toc.permalink` extension/feature:

```yaml
markdown_extensions:
  - toc:
      permalink: ⚓︎
```

### System information

Manjaro Linux with Firefox. Present with Docker container build.

**Comment by squidfunk** [comment]
Thanks for reporting. That's an unavoidable consequence of moving the anchor to the right, yes. Positioning them to the left solves this very issues, but comes with new problems. There's insufficient space (especially on mobile and tablet) to do that. You would either have to indent the headlines (which looks very odd) or live with the fact that the link may touch the corner of the viewport.

Also thanks for sharing your solution. I'd regard this as a customization, which is trivial to achieve, if desired. In general, everything that can be achieved with a few lines of extra CSS or JS is often not worth integrating to be configurable.

**Comment by polarathene** [comment]
> There's insufficient space (especially on mobile and tablet) to do that.

This feature is less obvious on touch devices, you've got to tap the heading for it to be revealed.  There is a CSS selector for touch interaction which could be used to animate the heading by sliding it to the right a bit to reveal the permalink icon?

Github renders the readme on mobile with gutters, and due to their approach with CSS, the permalink icon just sits in the gutter, thus doesn't pose any problems. I see that this themes gutters are slimmer and the permalink icon larger, github doesn't scale this with the size of the header font, their permalink glyph remains same size throughout.

An alternative would be to enable the heading itself as being able to retrieve a link and disabling the permalink icon I guess, but this would need some CSS to not adjust the styling (header using link colour).

---

> In general, everything that can be achieved with a few lines of extra CSS or JS is often not worth integrating to be configurable.

I understand this. Just some workarounds as a third-party risk running into breakage/conflict. Especially when overriding existing upstream style classes and targeting those class names or element hierarchies that can't be expected to not be prone to changes.

Another change I'm considering is aligning the nav side bar and ToC menus to their respective screen edges, as well as the nav bar left/right elements. I've got the CSS for this, I'm just concerned how stable that will remain, especially since it's for an open-source community project which I may not remain available for some time in the future (the maintainers aren't web devs and CSS like that would be problematic for them to grok AFAIK).

That change makes sense as third-party risk by overriding styles. The request here however clearly shows a UI bug, as such I feel it should be solvable and upstreamed to this project.

**Comment by polarathene** [comment]
How about just giving the permalink a width of 0?

This seems to work as well, but should be fine so long as there is sufficient gutter (but then left alignment like Github would be fine too tbh).

While the option to have left alignment would be preferred (for consistent placement in the gutter of the interactive permalink glyph), the `width: 0` solution works. If you enabled that and adjusted it to use a fixed size like Github, and possibly increased (or configurable gutters), that'd resolve the UI bug for your users. If you don't want that to be default that'd be understandable.

I'll maintain a CSS workaround in the mean time.

**Comment by squidfunk** [comment]
You can use the `headerlink` option: https://python-markdown.github.io/extensions/toc/

**Comment by polarathene** [comment]
Did you mean `headlink` class?(default) Or the `anchorlink` option? (which requires CSS anyway to avoid the link style being applied)

**Comment by squidfunk** [comment]
Yes, I meant `anchorlink`. I'm sorry, I was answering from my mobile.

**Comment by polarathene** [comment]
For anyone that stumbles across this issue and wants to resolve it, I tried a few approaches, but could not easily get the desired effect with `permalink` active (due to it being placed after heading text, which on multi-line split aligned it to the last line vertically), nor was inserting symbols via `content` and `::before` working well visually due to vertical alignment and/or font-size scaling affecting positioning via this workaround.

---

The most satisfactory solution was to use a thin vertical rectangle with rem units. Seems far more consistent in placement / offsets which wasn't the case for me with a font glyph. Hope it's helpful for others:

`assets/css/custom.css`:

```css
/*
  UX Bugfix for permalink affecting typography in headings.
  Upstream will not fix: https://github.com/squidfunk/mkdocs-material/issues/2369
*/

/* Headings are configured to be links (instead of only the permalink symbol), remove the link colour: */
div.md-content article.md-content__inner a.toclink {
  color: currentColor;
}

/* Positions the permalink symbol to the left of the heading for consistent placement */
/* Due to position order of the anchor link element to the heading content, it was better to replace it */
/* Changed from a symbol to a solid thin rectangle due to vertical alignment and scaling (clipping) issues */
div.md-content article.md-content__inner a.toclink::before {
  display: inline-block;
  margin-right: 0.2rem;
  margin-left: -0.6rem;
  content: '-'; /* not visible, just used as filler to make background-color visible */
  background-color: #73a4d7; /* light blue, could modify theme colour vars to match this instead */

  /* Based on original `.headerlink` styles from `mkdocs-material` theme: */
  color: transparent;
  opacity: 0;
  transition: opacity 125ms;
}

/* Based on original `.headerlink` styles from `mkdocs-material` theme: */
div.md-content article.md-content__inner a.toclink:hover::before,
div.md-content article.md-content__inner :target > a.toclink::before {
  opacity: 1;
  transition: opacity 125ms;
}
```

`mkdocs.yml`:

```yml
extra_css:
  - assets/css/custom.css

markdown_extensions:
  - toc:
      anchorlink: true
```

Looks like:

![Screenshot_20210311_141250](https://user-images.githubusercontent.com/5098581/110720686-e5039800-8273-11eb-9c7a-f32ee85f5bda.png)
![Screenshot_20210311_141018](https://user-images.githubusercontent.com/5098581/110720494-8807e200-8273-11eb-9e08-39627baa5baa.png)
![Screenshot_20210311_141107](https://user-images.githubusercontent.com/5098581/110720544-a372ed00-8273-11eb-86e0-f0555c41ad4e.png)
![Screenshot_20210311_141133](https://user-images.githubusercontent.com/5098581/110720583-b7b6ea00-8273-11eb-9a20-1687b734fec6.png)
![Screenshot_20210311_141220](https://user-images.githubusercontent.com/5098581/110720644-d0270480-8273-11eb-841b-8d96ecf1f6aa.png)
