### ISSUE TITLE
Material v7 breaks mkdocs-localsearch

### ISSUE THREAD

**Issue by wilhelmer** [squidfunk/mkdocs-material#2372]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

See https://github.com/wilhelmer/mkdocs-localsearch/issues/12.

Does not occur with any of the v7 beta versions, only in the release versions.

### Steps to reproduce the bug

1. Create a blank MkDocs project.
2. Install and set up mkdocs-localsearch as described in the [docs](https://github.com/wilhelmer/mkdocs-localsearch/blob/master/README.md).
3. Build.

[Download sample project](https://github.com/squidfunk/mkdocs-material/files/6063775/localsearch-test.zip)

### Project configuration

``` yaml
site_name: My Docs
theme:
  name: material
  custom_dir: theme
use_directory_urls: false
plugins:
  - search
  - localsearch
```

### System information

* OS: macOS
* Browser: Firefox and Chrome, latest
