### ISSUE TITLE
The logo option should link to the configured site_url 

### ISSUE THREAD

**Issue by msudol** [squidfunk/mkdocs-material#238]
## Description

The site logo currently has html source that looks like this

`<a href="../.." title="My Docs" class="md-logo md-header-nav__button">`

### Expected behavior

Expected behavior would be that the yml configuration for site_url would be here if it is configured.

### Actual behavior

The site_url configuration is not made available anywhere within the material theme.

### Steps to reproduce the bug

1. Set a logo in config
2. Set a site_url in config
3. Serve site in material theme

### Package versions

* Python:  3.6.0
* MkDocs: 0.16.2
* Material: 1.5.0

### Project configuration

``` yaml
# Project information
site_name: My Docs Example
site_url: https://www.mysite.com
site_description: My Test Documentation Site
site_author: John Do
repo_name: 'My Docs Example'
repo_url: 'https://www.mysite.com'

# Copyright
copyright: 'Copyright &copy; 2016 - 2017 John Doe'

# Theme
theme: 'material'
theme_dir: 'theme'

extra_css:
  - 'css/extra.css'
  
# Options
extra:
  logo: 'assets/images/logo.svg'
  palette:
    primary: 'blue grey'
    accent: 'deep orange'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Settings
docs_dir: 'docs'
site_dir: 'site'

# Extensions
markdown_extensions:
    - admonition
    - smarty
    - codehilite
    - footnotes
    - meta
    - toc(permalink=true)
    - pymdownx.arithmatex
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist(custom_checkbox=true)
    - pymdownx.tilde  

# Pages    
pages:
    - Home: 'index.md'
    - User Guide: 
        - 'Step 1': 'user-guide/step1.md'
        - 'Step 2': 'user-guide/step2.md'
        - 'Step 3': 'user-guide/step3.md'
    - About:
        - 'License': 'about/license.md'
        - 'Release Notes': 'about/release-notes.md'    
```

### System information

* OS: Windows 10
* Browser: Firefox
