### ISSUE TITLE
"Initializing search" because of a disallowed MIME type (“text/plain”)

### ISSUE THREAD

**Issue by Hulkstance** [squidfunk/mkdocs-material#2384]
I recently set up mkdocs with material. The search is broken. It is stuck at "Initializing search".

This is the error

> Loading Worker from “http://127.0.0.1:8000/assets/javascripts/workers/search.fb4a9340.min.js” was blocked because of a disallowed MIME type (“text/plain”).

### mkdocs.yml

```yml
site_name: Test

nav:
  - Home: index.md
  - FAQ: FAQ.md
  - Extensions: extensions.md
  - SOLID Principles:
    - What are the SOLID principles?: what_are_the_solid_principles.md
    - Single Responsibility Principle: single_responsibility_principle.md
    - Open-Closed Principle: open_closed_principle.md
    - Liskov Substitution Principle: liskov_substitution_principle.md
    - Interface Segregation Principle: interface_segregation_principle.md
    - Dependency Inversion Principle: dependency_inversion_principle.md

theme:
  name: material
  palette:
    scheme: slate
    primary: red
    accent: red

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition

copyright: Copyright &copy; 2021

```
