### ISSUE TITLE
Sidebar scrolling issue in Safari

### ISSUE THREAD

**Issue by vktrrdk** [squidfunk/mkdocs-material#2416]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [ ] ... the problem doesn't occur with the default MkDocs template
- [ ] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

When opening multiple nav-toggles in the sidebar, parts of the sidebar get hidden below the footer (as you can see in the attached screenshot). This problems somehow only occurs when using Safari. I checked the problem with other browsers (e.g. Firefox) and the problem does not occur.
![Bildschirmfoto 2021-03-08 um 12 57 10](https://user-images.githubusercontent.com/43116821/110318494-d87e0600-800d-11eb-99cc-eae91eac1275.png)

### Expected behavior

The sidebar with the navigations should me scrollable.

### Actual behavior

No scrollbar shows up, the sidebar is not scrollable.

### Steps to reproduce the bug

1. Open any documentation within Safari.
2. Open mutliple toggable points in the navbar, so the size of the sidebar exceeds the height of the opened documentation.
3. Scroll to the bottom of the page. The footer should cover elements of the sidebar.

### Package versions

* Python: Python 3.9.2
* MkDocs:  mkdocs==1.1.2
* Material: mkdocs-material==7.0.3

### Project configuration

``` yaml
site_name: "de.NBI Cloud Wiki"
docs_dir: /srv_root/docs/wiki
site_dir: /var/www/html/wiki
theme:
  name: material
  palette:
    primary: 'light blue'
    accent: 'light blue'
  logo: 'img/denbi.svg'
  favicon: 'img/denbi.svg'
repo_name: 'deNBI/cloud-user-docs'
repo_url: 'https://github.com/deNBI/cloud-user-docs'
edit_uri: blob/master/wiki/
plugins:
 - search
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - matomo.js

nav:
  - 'Home' : index.md
  - 'Registration' : registration.md
  - 'Citation and publication': citation_and_publication.md
  - 'Portal' :
    - 'Allocation': portal/allocation.md
    - 'Resource/Lifetime Modifications': portal/modification.md
    - 'Project Overview': portal/project_overview.md
    - 'Profile Page': portal/user_information.md
    - 'Using Vault': portal/vault_user.md
  - 'Simple VM':
      - 'New instance': simple_vm/new_instance.md
      - 'Instance overview': simple_vm/instance_overview.md
      - 'Instance details': simple_vm/instance_detail.md
      - 'New cluster': simple_vm/new_cluster.md
      - 'Cluster overview': simple_vm/cluster_overview.md
      - 'SSH keys and sharing access': simple_vm/keypairs.md
      - 'Volumes': simple_vm/volumes.md
      - 'Images/Snapshots': simple_vm/snapshots.md
      - 'Customization': simple_vm/customization.md
      - 'Concurrent Guacamole Sessions': simple_vm/guacamole.md
  - 'OpenStack Quickstart' : quickstart.md
  - 'Security' : security.md
  - 'Concept' :
    - 'OpenStack Basics' : Concept/basics.md
    - 'OpenStack Components' : Concept/openstack.md
    - 'Flavors' : Concept/flavors.md
    - 'Images' : Concept/images.md
  - 'Workshops':
    - 'Best Practices': workshops/best_practices.md
  - 'Tutorials' :
    - 'Access de.NBI Virtual Machines from Windows 10' : Tutorials/Win10_SSH/index.md
    - 'Access a SimpleVM with Mosh' : Tutorials/Mosh/index.md
    - 'SimpleVM File Transfer' : Tutorials/File_Transfer_Methods/index.md
    - 'Ansible Automation' : Tutorials/Ansible/index.md
    - 'Bibigrid' : Tutorials/BiBiGrid/index.md
    - 'Blast on BiBiGrid' : Tutorials/BlastOnBiBiGrid/index.md
    - 'Install latest CUDA version' : Tutorials/CUDA/index.md
    - 'Object Storage' : Tutorials/ObjectStorage/index.md
    - 'Save FloatingIPs' : Tutorials/SaveFloatingIPs/index.md
    - 'Set up RStudio' : Tutorials/RStudio_Server/index.md
    - 'Theia Web IDE': Tutorials/TheiaIde/index.md
    - 'UserData' : Tutorials/UserData/index.md
  - 'FAQ' : 'FAQ.md'
  - 'Compute Center Specific' :
    - 'Giessen' : Compute_Center/Giessen.md
    - 'Bielefeld' : Compute_Center/Bielefeld.md
    - 'Heidelberg Uni' : Compute_Center/Heidelberg.md
    - 'Heidelberg DKFZ' : Compute_Center/Heidelberg-DKFZ.md
    - 'Tuebingen' : Compute_Center/Tuebingen.md
    - 'Freiburg' : Compute_Center/Freiburg.md
    - 'Berlin' : Compute_Center/Berlin.md
  - 'Cloud Admin':
    - 'Jenkins + Haproxy with JuJu': cloud_admin/juju_jenkins.md
    - 'Configure OpenStack to use Elixir AAI via OpenID Connect': cloud_admin/elixir_OIDC.md
    - 'Register your identity provider for ELIXIR': cloud_admin/identity_provider.md
    - 'News management': cloud_admin/news_management.md
    - 'Vault management': cloud_admin/vault_admin.md
```

### System information

* OS: macOS Big Sur 11.1
* Browser: Safari Version 14.0.2

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for reporting. This does not happen on Safari 14.0 (Catalina):

https://user-images.githubusercontent.com/932156/110325285-6ad6d780-8017-11eb-85a8-7fad6e5dcf3d.mp4

I don't have Big Sur at my disposal. Could you try and reproduce it on Catalina?

**Comment by polarathene** [comment]
Try manipulating the height of sidebar and see if lower value properly crops it:

```css
div.md-sidebar div.md-sidebar__scrollwrap {
  height: 100px;
}
```

Note: Any scrolling will have JS overwrite the height (assuming JS is working in your scenario).

You should be able to inspect via Safari web dev tools and modify the CSS there to see if height is affecting it or any issues with CSS rules like `overflow-y`.
