### ISSUE TITLE
CI builds with mike

### ISSUE THREAD

**Issue by cperkulator** [squidfunk/mkdocs-material#2425]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

When using `mike` to version my documents I can't get my CI system to push the changes.  When I don't use `mike` I don't have a problem.  Related, it would be nice if the standard mkdocs interface could make the `mike` calls for you, rather than having to use the `mike` interface.  I could probably solve this with some git commands but ideally the mkdocs interface could do this without me having to run the git commands first or using `mike`.

Jenkins  Commands:
![image](https://user-images.githubusercontent.com/60443297/110681468-7ce38200-819f-11eb-8906-817ae6f9eb0e.png)

Jenkins Ouput:
![image](https://user-images.githubusercontent.com/60443297/110681266-4574d580-819f-11eb-8e81-194d5412c0ce.png)

Just using ```mkdocs gh-deploy``` works fine.

### Expected behavior

I would expect `mike` to do the rebasing and pushing for me, similar to how mkdocs does it.

### Steps to reproduce the bug

1. Push to gh pages using mike deploy. This works the first time
2. Push to gh pages using mike deploy again (but in a new Jenkins job, so it hasn't fetched all of the branches). This time it will fail because it isn't up to date with the remote.

### Package versions

* Python: `3.8.1`
* MkDocs: `1.1.2`
* Material: `7.0.3`

### Project configuration

``` yaml
docs_dir: doc

markdown_extensions:
    - fenced_code

plugins:
  - macros 
  - search

theme:
  name: material
  logo: assets\images\favicon.png
  features:
    - search.suggest
    - search.highlight
  palette:
    scheme: slate

extra:
  version:
    provider: mike
    
extra_css:
  - stylesheets/extra.css

nav:
  - 'index.md'
  - User Manual: 'usermanual.md'
```

### System information

* OS: Windows
* Browser: ...

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md
