### ISSUE TITLE
Allow configuration of admonition, details, etc. icons via mkdocs.yml

### ISSUE THREAD

**Issue by Andre601** [squidfunk/mkdocs-material#2458]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

It would be a nice addition, if the Material theme could offer a setting for choosing your icon-set. I talk about the icons used in things such as admonition headers.

It could be an `extra` setting:
```yaml
extra:
  icon-set: material # Uses Material icon set

extra:
  icon-set: fontawesome # Uses FontAwesome icon set

extra:
  icon-set: octicons # Uses Octicons icon set
```

### Use Cases

It would allow people without a big CSS knowledge to switch to a different set of icons, if they don't like the default ones used.
I'm well aware of the example on the reference section in the docs, about how to add custom icons. But in such a case like this one here would this create a rather large CSS file for just changing your icons used...

### Screenshots / Mockups

![image](https://user-images.githubusercontent.com/11576465/111135821-63ff1600-857d-11eb-9f72-bd44385d8522.png)

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md
