### ISSUE TITLE
Code strings inside tables should not wrap

### ISSUE THREAD

**Issue by SueChaplain** [squidfunk/mkdocs-material#2462]
- [x] I've read the [contribution guidelines][1] and agree with them

To be honest, I wasn't sure whether to raise this as a bug or enhancement and you might decide it's personal preference and we should add our own CSS. However, given the UX issues that are associated with allowing code elements to wrap, I thought it was worth raising. I could not see any open or closed issues that mentioned anything like this.

## Description

Code strings inside table cells can wrap, leaving them difficult to interpret for the user. For example, consider the following parameter strings for enabling some functionality (we have plenty like this in our project)

`-Xdump:directory=<path>`
`-XX:[+|-]ExitOnOutOfMemoryError`

### Expected behavior

Code shouldn't wrap so that it is easy to read/understand.

### Actual behavior

Here are some examples in our builds, using the latest MkDocs with material:

![image](https://user-images.githubusercontent.com/18395037/111180497-ff57b180-85a4-11eb-8610-56bcba8b2758.png)

![image](https://user-images.githubusercontent.com/18395037/111180362-e18a4c80-85a4-11eb-88a3-d87a74c7a6f8.png)

### Steps to reproduce the bug

Sample table in markdown, which builds with the code elements wrapped, as per the 1st screenshot:

```
| Parameter                                       | Result                                                                                                          |
|----------------------------------|--------------------------------------------------------------------|
| `-Xdump:none`                              | Removes all default dump agents and any preceding dump options. |
| `-Xdump:dynamic`                        | Enable support for pluggable agents                                                      |
| `-Xdump:nofailover`                      | Discards dumps when the default or specified dump location is full. |
| `-Xdump:directory=<path>`        | Specifies a directory for all dump types to be written to. This directory path is prefixed to the path of all non-absolute dump file names, including the file names for the default dump agents.        |
| `-Xdump:suspendwith=<offset>`| Modifies the signal that is used to suspend VM threads while a dump file is being written. Use `<offset>` to change the default signal number. (Linux&reg; only)                                                         |
| `-Xdump:<agent>:<suboptions>`| Provides detailed suboptions per dump agent that provide more granular control.  |
```

(excuse the GitHub render of this table ... it's not so messy in my editor 😄  )

### Package versions

- Python                      3.6.9
- mkdocs                     1.1.2
- mkdocs-material      7.0.3

### Project configuration

``` yaml

site_url: https://www.eclipse.org/openj9/docs  # the canonical URL of the site. This will add a link tag with the canonical URL to the generated HTML header.
repo_name: eclipse/openj9
repo_url : https://github.com/eclipse/openj9  # A link to your GitHub or Bitbucket repository on each page.
edit_uri: ""


site_description: Eclipse OpenJ9 documentation

theme:
  name: material
  custom_dir: theme
  palette:
    primary: teal # deep orange #
    accent:  cyan # orange # 
  font:
    text: Roboto           # 'Segoe Print' 'Kristen ITC' 'Tempus Sans ITC'
    code: Roboto Mono      # 'Consolas'
  logo: cr/openj9_6b.png
  language: en_custom
  icon:
    repo: fontawesome/brands/github
  favicon: cr/openj9-logo.svg
  
docs_dir: 'docs'

site_dir: 'site'

extra_css:
  - 'stylesheets/oj9.css'

extra:
  version: 2.0
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eclipse/openj9
      name: OpenJ9 in GitHub
    - icon: fontawesome/brands/slack
      link: https://openj9.slack.com
      name: OpenJ9 on Slack
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/openj9
      name: OpenJ9 on Twitter
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/search?q=OpenJ9
      name: OpenJ9 on StackOverflow

# Preview controls

dev_addr: '127.0.0.1:8008'

# Formatting options

markdown_extensions:
  - def_list
  - toc
  - sane_lists
  - attr_list
  - pymdownx.emoji:   # enable icons in markdown
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


nav:

    - "About the docs"                                                           : index.md
    - "OpenJ9 builds"                                                            : builds.md
    - "Getting started"                                                          : introduction.md
    - "New to OpenJ9?"                                                           : openj9_newuser.md

```

### System information

* OS: macOS 10.15.7
* Browser: Chrome Version 88.0.4324.192 (Official Build) (x86_64)

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for reporting. This is definitely a matter of taste and can be changed with 2-3 lines of CSS. The reasoning behinds this is that long code strings will extend the table and add large amounts of whitespace.

**Comment by SueChaplain** [comment]
Thanks for the fast response @squidfunk - not unexpected.

**Comment by jeremyabel** [comment]
For anyone else who ends up here, that 2-3 lines of CSS might look like this:
``` css 
td code {
	word-break: inherit !important;
}
```
