### ISSUE TITLE
Material no longer rendering awesome-pages config correctly

### ISSUE THREAD

**Issue by rieger-jared** [squidfunk/mkdocs-material#2472]
## Description

Hi, I've been using awesome-pages for a while now, but only with material docs v4. 
I tried upgrading to v7 but even the latest awesome-pages does not render out like the old way. Is there something wrong with my config or is this a clash with material docs. 

What's interesting is that the ordering is actually still working

I've created a sibling card on awesome-pages https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin/issues/41

.pages
```yaml
nav:
  - index.md
  - ...
  - contributing.md
```

Old material docs
<img width="254" alt="Screenshot 2021-03-18 at 11 06 16 pm" src="https://user-images.githubusercontent.com/52412896/111704060-dc482e80-883e-11eb-9ed9-54434e752651.png">

new
<img width="254" alt="Screenshot 2021-03-18 at 11 06 49 pm" src="https://user-images.githubusercontent.com/52412896/111704068-dce0c500-883e-11eb-8351-75aedc130eb8.png">

all links are tabs now
<img width="1123" alt="Screenshot 2021-03-18 at 11 07 07 pm" src="https://user-images.githubusercontent.com/52412896/111704070-dd795b80-883e-11eb-973a-90bdcb6ad5b7.png">

### Expected behavior

I expect with the supplied .pages config, that my tab are rendered like the first image

### Actual behavior

See image 3, the last image

### Steps to reproduce the bug

1. Set up directory with with the following structure
```txt
docs
├── contributing.md
├── developement\
├── getting-started.md
├── guides\
├── img\
├── index.md
├── office\
├── operations
```
2. place other md files in sub dirs
3. run mkdocs serve

### Package versions

* Python: `Python 3.9.2`
* MkDocs: `mkdocs, version 1.1.2`
* Material: `Version: 7.0.6`

```requirements.txt
mkdocs==1.1.2
mkdocs-awesome-pages-plugin==2.5.0
mkdocs-git-revision-date-plugin==0.3.1
mkdocs-material==7.0.6
mkdocs-material-extensions==1.0.1
```

### Project configuration

``` yaml

static_templates:
  - 404.html

# Don't include MkDocs' JavaScript
include_search_page: false
search_index_only: true

theme:
  icon:
    repo: fontawesome/brands/git-alt
  name: 'material'
  palette:
    scheme: preference
    primary: 'deep orange'
    accent: 'light blue'
  features:
    - navigation.instant
    - navigation.tabs

extra:
  social:
    - icon: fontawesome/brands/github
      link: site
    - icon: fontawesome/brands/slack
      link: site

docs_dir: src

site_dir: 'target/'

plugins:
  - search
  - awesome-pages
  - git-revision-date

# Extensions
markdown_extensions:
  - meta
  - smarty
  - admonition
  - codehilite
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Required to load the MathJax javascript for the mdx_math.py
extra_javascript:
  ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']

```

### System information

* OS: MacOS BigSur 11.2.2
* Browser: Chrome
