### ISSUE TITLE
Hide Latest Release repo info (insiders)

### ISSUE THREAD

**Issue by HendrikK** [squidfunk/mkdocs-material#2481]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

Allow insiders **not** to display the latest release tag in the repo info.

### Use Cases

UI Design choice

### Screenshots / Mockups

![image](https://user-images.githubusercontent.com/4612319/111992082-eb640080-8b0c-11eb-8377-31ea57fb94e0.png)

**Comment by squidfunk** [comment]
Thanks for suggesting. Could you elaborate on the why behind that feature request?

**Comment by squidfunk** [comment]
On a side note, you can just use some extra CSS to hide the release tag:

``` css
.md-source__fact md-source__fact--version {
  display: none;
}
.md-source__fact md-source__fact--stars::before {
  margin-left: 0;
}
```
