### ISSUE TITLE
UndefinedError: 'dict object' has no attribute 'toggle'

### ISSUE THREAD

**Issue by thebino** [squidfunk/mkdocs-material#2511]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

Since the latest release 7.1.0 an error occurred building a site while including the `material/partials/header.html` file

### Expected behavior

Build should not fail with an error

### Actual behavior

 File "/venv/lib/python3.9/site-packages/material/main.html", line 4, in top-level template code
    {% extends "base.html" %}
  File "/venv/lib/python3.9/site-packages/material/base.html", line 118, in top-level template code
    {% block header %}
  File "/venv/lib/python3.9/site-packages/material/base.html", line 119, in block "header"
    {% include "partials/header.html" %}
  File "/venv/lib/python3.9/site-packages/material/partials/header.html", line 36, in top-level template code
    <label class="md-header__button md-icon" title="{{ option.toggle.name }}" for="__palette_{{ loop.index0 or loop.length }}" hidden>
  File "/venv/lib/python3.9/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)

### Steps to reproduce the bug

1. Update any sample to the latest release 7.1.0
2. run mkdocs build

### Package versions

* Python: Python 3.9.2
* MkDocs: mkdocs, version 1.1.2
* Material: Version: 7.1.0

**Comment by squidfunk** [comment]
Thanks for reporting. I can't reproduce it. Both, none-toggle and toggle configurations work as expected:

#### without toggle

``` yaml
theme:
  palette:
    scheme: default
    primary: indigo
    accent: indigo
```

#### with toggle

``` yaml
theme:
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
```

Please provide a reproducible example, your `mkdocs.yml` configuration, and basically everything else that is asked in the issue template, so we can find the root cause 😊

**Comment by julian-alarcon** [comment]
Got the same error, in older version this worked:
```
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: preference
      primary: indigo
      accent: deep purple
```

Now in 7.1.0 I need to remove the minus sign
```
theme:
  name: material
  custom_dir: overrides
  palette:
      scheme: preference
      primary: indigo
      accent: deep purple
```

I'm not using toggle (as it's an insider's feature)

**Comment by squidfunk** [comment]
Thanks for providing your configuration. You’ve got overrides in place - the OP checked the box which says “doesn’t happen in overrides”. Could you remove them and check whether the issue persists?

**Comment by julian-alarcon** [comment]
No overrides, same error result, just removing the minus sign works:

```yaml
theme:
  name: material
  palette:
    - scheme: preference
      primary: indigo
      accent: deep purple
```

```
  File "/usr/local/lib/python3.9/site-packages/material/partials/header.html", line 36, in top-level template code
    <label class="md-header__button md-icon" title="{{ option.toggle.name }}" for="__palette_{{ loop.index0 or loop.length }}" hidden>
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'toggle'
```

**Comment by squidfunk** [comment]
Ok thanks, that syntax was never officially supported. It makes no sense to use the list syntax without defining the toggles. Thus, it’s a configuration error 😊

**Comment by thebino** [comment]
Thanks @julian-alarcon 
Exactly what described solved the issue here as well.

old configuration
```theme:
  name: material
  custom_dir: overrides

  palette:
    - scheme: preference
      primary: blue
      accent: pink
```

new configuration
```
theme:
  name: material
  custom_dir: overrides

  palette:
    scheme: preference
    primary: blue
    accent: pink
```
