### ISSUE TITLE
Text shift if print page with collapsible blocks

### ISSUE THREAD

**Issue by mitpro** [squidfunk/mkdocs-material#2549]
Hi

## Description

after updating to mkdocs-material 7 my pdf export (Chrome pdf-print) went wrong.
Pages with collapsible blocks `??? note` or `???+ note` got a whitespace on first page. 

![2021-04-12 10_39_09-with collapsible blocks - ZNK Dokumentation](https://user-images.githubusercontent.com/12111420/114366621-e8908480-9b7b-11eb-987d-dde268182e49.png)

First line is the Heading:

```` md
# with collapsible blocks 
....
??? note "Issue"
    ....
````

### Expected behavior

No Whitespaces on first page.

Replacing the block with non-collapsible block `!!! note` solves this issue.

![2021-04-12 10_41_20-without collapsible blocks - ZNK Dokumentation](https://user-images.githubusercontent.com/12111420/114366672-f2b28300-9b7b-11eb-9632-eda670410585.png)

```` md
# without collapsible blocks 
....
!!! note "Issue"
    ....
````

### Package versions

Python     3.8.0
mkdocs     1.1.2
mkdocs-material     7.1.1
mkdocs-material-extensions     1.0.1

### Project configuration

``` yaml
site_name: Documentation

use_directory_urls: false

theme:
  name: material 
  font: false
  language: de
  #favicon: assets/images/favicon.png
  favicon: assets/logo/e92063.ico
  logo: assets/logo/white.ico
  custom_dir: theme
  palette:
    # Light mode
    - blue: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.top

markdown_extensions:
  - attr_list
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - footnotes
  - abbr
  - toc:
      toc_depth : "1-4"
      permalink: true

plugins:
  - search:
        min_search_length: 2
        lang: de
        separator: '[\s\-\.]+'
  - localsearch
  - table-reader
  - macros:
      include_dir: include
  - progress

repo_url: xxxx
edit_uri: xxxx
```

### System information

OS: Windows 10 x64 1909
Browser: Chrome 87.0.4280.88
