### ISSUE TITLE
Highlight.js not working properly with `navigation.instant`

### ISSUE THREAD

**Issue by jairbubbles** [squidfunk/mkdocs-material#2569]
## Description

When using instant navigation, `highlight.js` is not reloaded when you change page and the styling is not applied on the code blocks

### Expected behavior

Enabling `navigation.instant` shouldn't have effect on code highlighting.

### Actual behavior

Highlighting works only if you refresh the page.

### Steps to reproduce the bug

- Run this sample: [MkDocsHighlightJs.zip](https://github.com/squidfunk/mkdocs-material/files/6316162/MkDocsHighlightJs.zip)
- Navigate to the "code" page
- Observe that the highlighting is not applied:

![image](https://user-images.githubusercontent.com/15875066/114835487-e7589500-9dd1-11eb-9051-9d44a5bfd889.png)

### Package versions

* Docker image: squidfunk/mkdocs-material:7.0.6

### Project configuration

``` yaml
site_name: Highlight.js example
theme:
  name: material
  features:
    - navigation.instant
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - 'highlighting.js'
```
