### ISSUE TITLE
Inline blocks fail with custom title

### ISSUE THREAD

**Issue by FranckCHAMBON** [squidfunk/mkdocs-material#2606]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

Inline blocks fail with custom title

```markdown
!!! info "my title" inline end
    Lorem ipsum dolor sit amet, consectetur
    adipiscing elit. Nulla et euismod nulla.
    Curabitur feugiat, tortor non consequat
    finibus, justo purus auctor massa, nec
    semper lorem quam in massa.
```

### Expected behavior

A sidebar, just like when `"my title"` isn't set.

### Actual behavior

Broken output.

### Steps to reproduce the bug

1. Use the sample given in documentation
2. Add a custom title
3. Serve or build

### Package versions

* Python: `python --version`
* MkDocs: `mkdocs --version`
* Material: `pip show mkdocs-material | grep -E ^Version`

```console
francky@DUST:~$ python3 --version
Python 3.8.5
francky@DUST:~$ mkdocs --version
mkdocs, version 1.1.2 from /home/francky/.local/lib/python3.8/site-packages/mkdocs (Python 3.8)
francky@DUST:~$ pip show mkdocs-material | grep -E ^Version
Version: 7.1.1
```

### Project configuration

``` yaml
site_name: Expériences

nav:
    - Accueil: index.md

                                    # JUSTIFICATIONS
theme:
    name: material
    font: false                     # RGPD
    language: fr                    # français

markdown_extensions:
    - def_list                      # listes de définition
    - attr_list                     # pour un peu de CSS et des attributs HTML
    - footnotes                     # notes de bas de page
    - admonition                    # blocs colorés
    - pymdownx.details              #   qui peuvent se plier/déplier
    - pymdownx.caret                # pour ^^souligné^^ et ^exposant^
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.snippets
    - pymdownx.highlight:
        linenums: false
    - pymdownx.tasklist:
        custom_checkbox:    false
        clickable_checkbox: true
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.keys
    - pymdownx.tabbed
    - pymdownx.emoji:
        emoji_index:     !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
```

### System information

* OS: Linux Mint 20.1
* Browser: Firefox 88.0

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md
