### ISSUE TITLE
Specifying language for in-text code blocks does not display correctly on mobile/small screens.

### ISSUE THREAD

**Issue by tpbnick** [squidfunk/mkdocs-material#2637]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [ ] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

When I specify the language for code inside normal text (not in code blocks) it does not display correctly on mobile/small screens.  Image below:
![image](https://user-images.githubusercontent.com/49327729/117142364-9e1ab600-ad7d-11eb-85be-4a9de99dae48.png)

I am using the following markdown to specify code: (#!language)

inside (`s)
#!js console.log("help me!");

### Expected behavior

I expect the code to not wrap over other text, like when you use simple code highlighting (`code here`).

### Actual behavior

Code in text, when language is specified, wraps over other text (see image above)

### Steps to reproduce the bug

1. Insert code into documentation using the following: `#!language code here`.
2. Either build docs or serve and open in mobile/shrink browser screen.

### Package versions

* Python: 3.85
* MkDocs: 1.12
* Material: 7.1.3

### Project configuration

```
site_name: Nick's Docs
theme:
  name: material
  logo:  //removed
  favicon:  //removed
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  static_templates:
    - 404.html
  font:
    text: Roboto
    code: Source Code Pro
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - minify:
      minify_html: true
extra_javascript:
  - javascripts/extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
markdown_extensions:
  - pymdownx.arithmatex
  - attr_list
  - codehilite:
      guess_lang: false
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
  - admonition
  - lightgallery
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - toc:
      permalink: false
extra:
  social:
    - icon: fontawesome/solid/images
      link: //removed
    - icon: fontawesome/solid/blog
      link: //removed
    - icon: fontawesome/brands/linkedin
      link: //removed
    - icon: fontawesome/brands/github
      link: https://github.com/tpbnick
    - icon: fontawesome/brands/instagram
      link: //removed
    - icon: fontawesome/regular/envelope
      link: //removed
  extra_css:
    - stylesheets/extra.css
```

### System information

* OS: Windows 10
* Browser: Edge/Chrome

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md
