### ISSUE TITLE
- navigation.tabs is not working properly

### ISSUE THREAD

**Issue by Nthily** [squidfunk/mkdocs-material#2657]
here is my `mkdocs.yml`

```
site_name: Jetpack Compose
site_url: https://docs.compose.net.cn/

repo_name: 'Jetpack Compose 博物馆'
repo_url: 'https://github.com/Compose-Museum/Compose-Tutorial'
edit_uri: 'tree/main/docs/'

theme:
  name: material
  language: zh
  icon:
    repo: fontawesome/brands/github
  logo: assets/logo.png
  feature:
    - navigation.tabs
    - navigation.instant
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

nav:
  - 'Jetpack Compose':
    - '概述': index.md
    - '在开始之前': start.md
    - '基本组件':
      - 'Text': elements/text.md
      - 'Button': elements/button.md
      - 'Card': elements/card.md
      - 'Icon': elements/icon.md
      - 'Image': elements/image.md
      - 'IconButton': elements/iconbutton.md
      - 'TextField': elements/textfield.md
    - '布局': 
      - '概述': layout/overview.md
      - 'Column': layout/column.md
      - 'ModalBottomSheetLayout': layout/modalbottomsheetlayout.md
      - 'Row': layout/row.md
      - 'Spacer': layout/spacer.md
      - 'Scaffold':
        - '概述': layout/scaffold/overview.md
        - '1. topBar': layout/scaffold/topbar.md
        - '2. bottomBar': layout/scaffold/bottombar.md
        - '3. drawerContent': layout/scaffold/drawercontent.md
        - '4. floatingActionButton': layout/scaffold/floatingactionbutton.md
    - '动画':
      - '概述': animation/overview.md
      - 'AnimationVisibility': animation/animationvisibility.md
    - '主题':
      - '初识 MaterialTheme': theme/meet_material_theme.md
      - '深入理解 MaterialTheme 与 CompositionLocal': theme/understanding_material_theme.md
    - '参数':
      - 'Modifier': parameters/modifier.md
    - '代码实验室': codelabs.md
    - '贡献': contributing.md
    - '资源': resources.md
    - '关于投喂': pay.md
  - 'API 文档':
    - '概述': api/index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Compose-Museum/Compose-Tutorial/

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      linenums: false
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list

plugins:
  - search
  - git-revision-date-localized:
      type: date

```

![X8}`YQ ZC8U9N0G2QG0{N@6](https://user-images.githubusercontent.com/31311826/118035070-0a437e00-b36b-11eb-8516-fd5a3cffc001.png)

I have tried many ways but can not solve
