### ISSUE TITLE
Insert image comes with some wired symbol ï¿¼ 

### ISSUE THREAD

**Issue by bkbncn** [squidfunk/mkdocs-material#268]
## Description

I want to Insert image, but it comes with some wired symbol ï¿¼ before every image.

### Package versions

* Python: 2.7.13
* MkDocs: 0.16.3
* Material: cloned, updated

### Project configuration

``` yaml

# Extensions
markdown_extensions:
  - admonition
  - toc(permalink=true)
  - pymdownx.mark
  - pymdownx.arithmatex

# Page tree
pages:
  - EE7325: index.md
  - Setup: 
    - NX Client Setup: nx.md
  - Waveform viewer: 
    - WaveView by Synopsys: wv.md
```

wv.md image part
```
open simulation file by click the button of `Import Waveform File`￼

![wv1](images/wv1.png)

then click **OK** 

![wv2](images/wv2.png)

```

[my webpage link](https://www.utdallas.edu/~xiangyu.xu/wv/)

I don`t know this is issue form theme or mkdocs, thanks for help.
