### ISSUE TITLE
Image files with semi-colon in filename won't show up in website

### ISSUE THREAD

**Issue by akharrou** [squidfunk/mkdocs-material#2732]
## Description

Images with a semi-colon (`;`) in their file name won't show up in the website output.

### Expected behavior

That all included images show up in the website.

### Actual behavior

![image](https://user-images.githubusercontent.com/36056254/120476876-c8c75100-c3b3-11eb-9929-ec662ad0f294.png)

### Steps to reproduce the bug

```plaintext
# File structure
.
├── file.md
└── ;dir;name
    ├── ;img-name.png
    ├── img;name.png
    ├── ;img;name.png
    ├── img-name.png
    └── name.png
```

````md
# file.md

![image-1](;dir;name/;img-name.png) <!-- DOESN'T WORK -->

![image-2](;dir;name/img;name.png) <!-- DOESN'T WORK -->

![image-3](;dir;name/;img;name.png) <!-- DOESN'T WORK -->

![image-4](;dir;name/img-name.png) <!-- WORKS -->

![image-5](;dir;name/name.png) <!-- WORKS -->
````

### Package versions

* Python: `version 3.9.4`
* MkDocs: `version 1.1.2 from /usr/local/lib/python3.9/site-packages/mkdocs (Python 3.9)`
* Material: `version 6.2.8`

### Project configuration

``` yaml
theme:
    name: material

markdown_extensions:
    - toc
    - abbr
    - admonition
    - footnotes
    - def_list
    - attr_list
    - pymdownx.tabbed
    - pymdownx.inlinehilite
    - pymdownx.details
    - pymdownx.tasklist
    - pymdownx.superfences
    - pymdownx.highlight
    - pymdownx.critic
    - pymdownx.betterem
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.smartsymbols
    - pymdownx.keys
    - pymdownx.arithmatex
    - pymdownx.snippets
    - pymdownx.emoji
```

### System information

* OS: macOS 11.2.3 20D91 x86_64
* Browser: Google Chrome: 90.0.4430.212 (Official Build) (x86_64)

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md
