### ISSUE TITLE
Math formulas show scrollbars

### ISSUE THREAD

**Issue by cedricleroy** [squidfunk/mkdocs-material#2733]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [ ] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

## Description

Seems to be similar than https://github.com/squidfunk/mkdocs-material/issues/2048. There are scrollbars appearing in formulas.

### Expected behavior

![image](https://user-images.githubusercontent.com/11164911/120547203-69b70b80-c3b6-11eb-9afe-f5e6bf2df7d2.png)

(version 6.2.8)

### Actual behavior

![image](https://user-images.githubusercontent.com/11164911/120547621-ff529b00-c3b6-11eb-872e-d79f769fa9a5.png)

(version >= 7.0.0)

### Steps to reproduce the bug

Just testing what is in the official doc. Please note that the problem seems to appear with 7.0.0. 

### Package versions

* Python: 3.7.9
* MkDocs: 1.1.2
* Material: >=7.0.0 (Tested with 7.0.0, and 7.1.6)

### Project configuration

``` yaml
site_name: Hello
theme:
  name: material
nav:
  - Home: index.md
extra_javascript:
  - javascript/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
```

`index.md`:
```
$$
\operatorname{ker} f=\{g\in G:f(g)=e_{H}\}{\mbox{.}}
$$
```

### System information

* OS: macOS
* Browser: Tested with Chrome and Safari

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

_P.S. Thanks for the great work!_
