### ISSUE TITLE
Please Add `plantuml-markdown` To The Docker Image

### ISSUE THREAD

**Issue by loganknecht** [squidfunk/mkdocs-material#2767]
Hello!

# Gratitude

Thanks for the wonderful docker image! It has been super helpful in working with my organization's documentation and `GitLab Pages`!

# Existing Discussion

https://github.com/squidfunk/mkdocs-material/discussions/2389

# Description/Use Cases

I'm working with `mkdocs` to generate consistent documentation across my organization's team.

The issue is that we use `GitLab` `Markdown` syntax and by default they support `PlantUML`

I've managed to figure out a way to configure our setup like so

```yaml
markdown_extensions:
    # Code block highlighting
    - pymdownx.highlight
    # Nesting code blocks
    - pymdownx.superfences
    # Insert code from other files
    - pymdownx.snippets
    # Inline code block highlighting
    - pymdownx.inlinehilite
    - plantuml_markdown:
          server: http://www.plantuml.com/plantuml
```

And then I can generate locally like this
```bash
docker run \
		--rm \
		-it \
		--workdir /app \
		--volume $(MAKEFILE_DIRECTORY):/app \
		--entrypoint /bin/sh \
		squidfunk/mkdocs-material \
		-c "pip install plantuml-markdown; mkdocs build --verbose --site-dir documentation_preview"
```

But it would be pretty cool to not obligate me to install pip like this, and instead have an image that allows me to use plantuml with minimal friction.

Because this isn't here I'm obligated to `pip install plantuml-markdown` every-time, whether it's local or in CI/CD.

# Request

Can we please add `plantuml-markdown` to the docker image?
