### ISSUE TITLE
Build error with 'ja' as search plugin lang

### ISSUE THREAD

**Issue by Mopster** [squidfunk/mkdocs-material#2770]
## Description

When building, I get the following error :

```ERROR   -  Config value: 'plugins'. Error: Plugin value: 'lang'. Error: "ja" is not a supported language code. ``` 

It works correctly with mkdocs-material v6.2.8

### Expected behavior

Build with Japanese language without a problem.

### Actual behavior

Unable to build with Japanese language in configuration for the search plugin.
No problem when building with `en` as language settings

### Steps to reproduce the bug

Execute `mkdocs build` with `ja` as the specified language for the search plugin

### Package versions

* Python : 3.9.5
* Mkdocs: version 1.1.2 from /usr/lib/python3/dist-packages/mkdocs (Python 3.9)
* Material: Version: 7.1.8

### Project configuration

``` yaml
site_name: Tamago-DB Documentation
site_author: Tamago-DB
site_description: Tamago-DB ATS documentation and user guide
plugins:
  - search:
      separator: '[\s\-\.]+'
      lang: ja
markdown_extensions:
  - admonition
theme:
  name: material
  language: ja
  logo: img/tamago-db-white-logo.png
  favicon: img/favicon.png
  palette:
    primary: light-green
    accent: light-green
  navigation_depth: 2
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TamagoDB
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/tamago-db-k-k-/
site_dir: ../../web/solutions/ja
docs_dir: ../../docs/solutions/ja
use_directory_urls: false
google_analytics:
  - UA-xxx-8
  - auto
nav:
  - ホーム: 'index.md'
  - ダッシュボード: 'dashboard.md'
#  - グリッド: 'grids.md'
  - 企業: 'company.md'
#  - 求人: 'job.md'
#  - 連絡先: 'contacts.md'
  - ショートリスト: 'shortlist.md'
  - 進捗: 'pipeline.md'
#  - イベント: 'events.md'
  - 請求書: 'invoicing.md'
  - 応募: 'applications.md'
  - タグ: 'tags.md'
  - メモ: 'notes.md'
#  - '文章ビュアー': 'document-viewer.md'
#  - マッチング: 'matching.md'
  - 検索: 'searching.md'
  - アクティビティ: 'activity.md'
#  - レジュメ自動入力: 'parsing.md'
#  - インポート: 'import.md'
  - レポート: 'reporting.md'
#  - 通知: 'notifications.md'
  - ユーザー: 'users.md'
  - 求人掲示板: 'job-board.md'
  - API: 'api.md'
```

### System information

* OS: Ubuntu 20.04
