### ISSUE TITLE
Toc side-bar can't rolling when using mkdocs build

### ISSUE THREAD

**Issue by super6602** [squidfunk/mkdocs-material#2813]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [ ] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

the table of context can't rolling when using mkdocs build, but it worked when using mkdoc serve

### Expected behaviour

the right sidebar of TOC can rolling when using mkdocs serve

![image](https://user-images.githubusercontent.com/32385793/124419322-d2b3e980-dd8f-11eb-9c3e-ac5fe100fc95.png)

### Actual behaviour

the right sidebar of TOC can't rolling when using mkdocs build

![image](https://user-images.githubusercontent.com/32385793/124419423-02fb8800-dd90-11eb-92ad-f27ac729d130.png)

### Steps to reproduce

1. mkdocs build
2. the built site of TOC can't rolling

### Package versions

- Python: 3.9.4
- MkDocs: 1.2.1
- Material: 7.1.9

### Configuration

```yaml
site_name: LE Audio
site_author: Allen Wu
use_directory_urls: false
theme:
    name: "material"
    language: "zh-TW"
extra_css:
    - "stylesheets/extra.css"
    - "stylesheets/theme_dark.css"

markdown_extensions:
    - pymdownx.highlight:
        linenums_style: pymdownx-inline
        linenums: true
    - pymdownx.inlinehilite
    - pymdownx.superfences    
    - toc:
        # permalink: "#"
        toc_depth: 3
    - admonition
    - def_list
    # - codehilite:
    #     linenums: true
plugins:
    - search:
    # - mkdocs-versioning:
    #   version: "1.0"
    # - awesome-pages
    - build_plantuml:
        render: "server"
        bin_path: "/usr/local/bin/plantuml"
        server: "http://www.plantuml.com/plantuml"
        output_format: "svg"
        diagram_root: "docs/diagrams"
        output_folder: "out"
        input_folder: "src"
    # - mkdocs-versioning:
    #     version: "1.0"
```

### System information

- Operating system: win10
- Browser: chrome
