### ISSUE TITLE
Tabbed sets are making separate tab blocks always

### ISSUE THREAD

**Issue by DimitrijeDragasevic** [squidfunk/mkdocs-material#2854]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

HI here is my env :
mkdocs                                     1.2.1
mkdocs-material                      7.1.11
mkdocs-material-extensions  1.0.1
pymdown-extensions               8.2

And here is the code that i am building:
`=== "MySQL"

```sql

delete from ci_summary_audits where created_dtm < ? limit ?

```

=== "SQL Server"

```sql

delete top (?) from ci_summary_audits where created_dtm < ?

````

### Expected behaviour

it should render under one tab set not two.

### Actual behaviour

and these get rendered as this picture :
<img width="722" alt="Screenshot 2021-07-21 at 14 01 16" src="https://user-images.githubusercontent.com/19540608/126485791-3cf3db42-b59a-46f8-8c3a-f984c65b57aa.png">
i think that they should render under one tabbed set not two

### Steps to reproduce

1. add the syntax above to any md page and generate the a site with mkdocs

### Package versions

- Python: `3.9.5`
- MkDocs: `1.2.1 `
- Material: ` 7.1.11
`

### Configuration

```yaml
# NOTE: Do not define the nav structure in this file as it will conflict
# with the .pages files that are contained in each subdirectory.  These
# files define the navigation structure on a per-directory basis using
# the "Mkdocs Awesome Pages" plugin.
#
# See: https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin


site_url: https://developer.identityx-cloud.com
site_name: IdentityX Developer
site_description: IdentityX Developer Resources
site_author: Daon Documentation Team
copyright: "&copy; Copyright 2019-2021 Daon. All rights reserved."
#repo_url: "https://github.com/daon-private/doc-identityx-home/"

# Theme Configuration
#
# We are using the "Material for MkDocs" theme.
#
# See: https://squidfunk.github.io/mkdocs-material/

theme:
  name: material
  logo: images/identityx-logo.png
  favicon: images/favicon.ico
  palette:
      primary: Denim
      accent: teal
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes



  # CSS Tweaks
extra_css:
  - stylesheets/font-awesome.css
  - stylesheets/extra.css


# Markdown Extensions

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - toc:
      permalink: true
  - pymdownx.snippets
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - markdown_include.include:
      base_path: docs

# Daon Social Buttons

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/daoninc
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/daoninc
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/daon/

nav:
  - IdentityX Developer:
    - index.md
    - platform.md
    - y-functional-overview.md
  - ...


plugins:
  - search:
      separator: '[\s\-\.]+'
  - awesome-pages:
      filename: .pages
      collapse_single_pages: false
      strict: true
  - macros
  - pdf-export:
      enabled_if_env: ENABLE_PDF_EXPORT
      verbose: true
      combined: false
```

### System information

- Operating system: ...mac os (latest)
- Browser: ...chrome(latest)
