### ISSUE TITLE
Code highlight not working properly in mobile

### ISSUE THREAD

**Issue by jimlyas** [squidfunk/mkdocs-material#2859]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When opening the documentation in mobile, the highlighting code doesn't work all the way to the end of line.

### Expected behaviour

Code highlighting cover all the line when scrolling horizontal

### Actual behaviour

The code highlighting only cover the first visible threshold
![image](https://user-images.githubusercontent.com/33854739/126855938-43df7a78-2b14-4c12-999a-73ac164ea7cd.png)

### Steps to reproduce

1. open the documentation
2. use chrome tools for viewing in different device type

### Package versions

- Python: 3.8.10
- MkDocs: 1.2.2
- Material: 7.2.0

### Configuration

```yaml

docs_dir: docs/src
theme:
  name: material
  custom_dir: docs/theme
  logo: assets/icon.png
  favicon: assets/icon.png
  icon:
    repo: fontawesome/brands/gitlab
  palette:
     scheme: dracula
     primary: red
     accent: blue
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - toc.integrate
    - search.highlight

extra_css:
  - stylesheets/hint.min.css

plugins:
  - search
  - tooltips
  - minify:
      minify_html: true
      minify_js: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - def_list
  - pymdownx.snippets
  - pymdownx.mark
  - pymdownx.smartsymbols
  - attr_list
  - admonition
  - meta
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      toc_depth: 3
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
```

### System information

- Operating system: Window 10
- Browser: Chrome
