### ISSUE TITLE
Adjust the TOC in the upper-right corner

### ISSUE THREAD

**Issue by ugoproto** [squidfunk/mkdocs-material#286]
## Description

A second TOC shows up in the upper-right corner: "Table of contents". Can we change the title in the .yaml?

### Expected behavior

We can write in any language in MkDocs by customizing the fields. Except that one. I'm building a little doc (a proof-on-concept) for a history professor: https://ugoproto.github.io/ugoNF/

### Actual behavior

We cannot change it as we can do with the TOC:

```
markdown_extensions:
    - toc:
        title: Contenu
        permalink: True
        baselevel: 3
```
