### ISSUE TITLE
When toc.integrate is enabled and toc is hidden in markdown meta then the toc is still visible

### ISSUE THREAD

**Issue by saibotma** [squidfunk/mkdocs-material#2874]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When toc.integrate is enabled and toc is hidden in markdown meta then the toc is still visible.

### Expected behaviour

Toc should not be visible anymore.

### Actual behaviour

Toc is visible on the left side.

### Steps to reproduce

1. Enable `toc.integrate`
2. Add the following to a page:
```
---
hide:
  - toc
---
```

### Package versions

Using `docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material`

### Configuration

```yaml
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.instant
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - toc.integrate
markdown_extensions:
  - meta
  - toc:
      permalink: "#"
```

### System information

- Operating system: MacOS
- Browser: Firefox
