### ISSUE TITLE
Search suggestions are not displayed when the search input box has a custom bg color

### ISSUE THREAD

**Issue by Vegebutcher** [squidfunk/mkdocs-material#2882]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When there is a CSS override for the search input box and the background color is set, the search suggestions won't show up. They're still there, but simply covered with the bg color.

### Expected behaviour

I'd expect the bg color of the input box to be the real background, i.e. the lowest layer.

### Actual behaviour

The background color set for the search input box prevents search suggestions to be visible.

### Steps to reproduce

Set the background color for the search input box:

`.md-search__form,
  .md-search__input {
       background-color: var(--gog-search-bg-color);
}
`
Now the search suggestions won't show up: they are invisible no matter what font color they have.

### Package versions

- Material: 7.2.1

### Configuration

```yaml
Default stylesheet overrides and search suggestions enabled:

extra_css:
  - stylesheets/gog.css

theme:
  name: 'material'
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
```

### System information

- Operating system: macOS 11.5.1
- Browser: Chrome 92.0.4515.107, Firefox 90.0.2
