### ISSUE TITLE
Icons are not rendered consistently when used in document titles

### ISSUE THREAD

**Issue by pavelskipenes** [squidfunk/mkdocs-material#2909]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Icons are not rendered consistently when used in document titles.

![image](https://user-images.githubusercontent.com/38912521/128260817-fe8c0a1c-8b5f-4cd5-ab61-3b3a02923acd.png)
![image](https://user-images.githubusercontent.com/38912521/128261267-7d65080e-81d4-461a-8a57-60413ba7df82.png)

### Expected behaviour

I expected to see the text :material-file-document-multiple: rendered as an icon like it is in the title of the `<article>` section.

### Actual behaviour

The text ":material-file-document-multiple:" is displayed as ":material-file-document-multiple:"

### Steps to reproduce

1. Create a md document with an icon in the title
2. Add emoji and icon support in .yml file 
3. Build the site

### Package versions
```
$ python3 --version
Python 3.9.6
$ mkdocs --version
mkdocs, version 1.2.2 from /usr/local/lib/python3.9/dist-packages/mkdocs (Python 3.9)
$ pip show mkdocs-material | grep -E ^Version
Version: 7.2.2
```
### Configuration

```yaml
site_name: testing site
theme:
    name: material
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
```

### System information

System information above was gathered from the VM / server.
Server:
- Ubuntu Impish Indri (development branch) x86_64 on Virtual box through Vagrant. Kernel: 5.11.0-20-generic

Client:
- Brave Brave Browser 91.1.26.77
- Manjaro with kernel 5.13
