### ISSUE TITLE
FileNotFoundError with social plugin

### ISSUE THREAD

**Issue by barreeeiroo** [squidfunk/mkdocs-material#2910]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Enabling social plugin causes mkdocs build to fail with a `FileNotFoundError`.

### Expected behaviour

mkdocs should build properly.

### Actual behaviour

mkdocs cannot produce a succesfull build, throwing a `FileNotFoundError` related to the logo asset.

### Steps to reproduce

1. Enable the social plugin
2. Specify a logo
3. Try to build

### Package versions

- Python: `3.8`
- MkDocs: `1.2.2`
- Material: `7.2.1-insiders-2.12.1`

### Configuration

```yaml
# Full configuration file available at https://github.com/Kodular/Documentation/blob/master/mkdocs.yml

plugins:
  - social
theme:
  logo: 'assets/logo.png'
```

### System information

- Operating system: Ubuntu 20.04 (_Github Actions_)
