### ISSUE TITLE
Seach not working for numbers , and phrases in large scale projects

### ISSUE THREAD

**Issue by DimitrijeDragasevic** [squidfunk/mkdocs-material#2914]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

So when i type in any number without any letters , or any random phrase from any paragraph it just wont show it in the search box like it does not exist...
<img width="1406" alt="Screenshot 2021-08-05 at 14 18 54" src="https://user-images.githubusercontent.com/19540608/128348751-8f823fb5-776a-415c-8362-a0725b0748dd.png">
<img width="1406" alt="Screenshot 2021-08-05 at 14 19 49" src="https://user-images.githubusercontent.com/19540608/128348760-08598efc-1624-41c6-bdea-5b24f7d9618f.png">

### Expected behaviour

I should be able to search for anything on the site

### Actual behaviour

not being able to find phrases and numbers on the site 

### Steps to reproduce

go the site
serch for random phrase and random number on the site
they wont come up

### Package versions

- Python: `3.9.5`
- MkDocs: `1.2.2 `
- Material: `7.2.2`

### Configuration

```yaml
site_url: https://developer.identityx-cloud.com
site_name: IdentityX Developer
site_description: IdentityX Developer Resources
#repo_url: "https://github.com/daon-private/doc-identityx-home/"

# Theme Configuration
#
# We are using the "Material for MkDocs" theme.
#
# See: https://squidfunk.github.io/mkdocs-material/

theme:
  name: material
  logo: images/identityx-logo.png
  favicon: images/favicon.ico
  palette:
      primary: Denim
      accent: teal
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - search.highlight



  # CSS Tweaks
extra_css:
  - stylesheets/font-awesome.css
  - stylesheets/extra.css


# Markdown Extensions

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.snippets
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - markdown_include.include:
      base_path: docs

# Daon Social Buttons

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/daoninc
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/daoninc
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/daon/

nav:
  - Introduction:
    - index.md
    - platform.md
    - y-functional-overview.md
  - ...


plugins:
  - search:
      separator: '[\s\-\.]+'
      prebuild_index: true
  - awesome-pages:
      filename: .pages
      collapse_single_pages: false
      strict: true
  - macros
  - pdf-export:
      enabled_if_env: ENABLE_PDF_EXPORT
      verbose: true
      combined: false
```

### System information

- Operating system: ...mac os
- Browser: ... chrome
