### ISSUE TITLE
Edit and/or hide nav title

### ISSUE THREAD

**Issue by victorbnl** [squidfunk/mkdocs-material#2936]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

I use navigation sections so I have two sections and I'd like to be able to use the title of the first section as navigation title, so I'd like to hide the main nav title

![bildo](https://user-images.githubusercontent.com/39555268/129489685-5829b68c-4cfb-4956-879d-e7ffccb220b4.png)

You'll surely say "don't use a section for the first links then!" but I can't, because if I do that, "Custom rules" will become a section, which is something I don't want

### Use Cases

As described above, it would help users that use nav sections, or just people that don't want their navigation to have a title

### Screenshots / Mockups

![bildo](https://user-images.githubusercontent.com/39555268/129489733-e9ef911b-c8ad-442f-915a-22a243b8d169.png)

**Comment by victorbnl** [comment]
I found a temporary fix: 
```css
/* Hide main nav title */
label[for="__drawer"] {
    display: none;
}
.md-nav__list>*:first-child {
    margin-top: 0;
}
```

**Comment by squidfunk** [comment]
Thanks for suggesting. However, there's no need, as it's already achievable with the capabilities we have. From the screenshot you posted I tried to reconstruct the structure you defined in `mkdocs.yml` (please share it the next time):

_Example_:

``` yaml
site_name: My site
theme:
  name: material
  features:
    - navigation.sections
    - navigation.tabs

nav:
  - Foo:
    - Foo:
      - Foo 1: ...
      - Foo 2: ...
    - Bar:
      - Bar 1: ...
      - Bar 2: ...
```

_Result_:

<img width="218" alt="Bildschirmfoto 2021-08-16 um 09 49 14" src="https://user-images.githubusercontent.com/932156/129529463-af207a7d-bbb0-43b2-bd38-ef4bff3e4bc0.png">

If you just drop the first nested `Foo` and move the subsections one level higher, it renders exactly like you want:

_Example_:

``` yaml
site_name: My site
theme:
  name: material
  features:
    - navigation.sections
    - navigation.tabs

nav:
  - Foo:
    - Foo 1: index.md
    - Foo 2: index.md
    - Bar:
      - Bar 1: index.md
      - Bar 2: index.md
```

_Result_:

<img width="216" alt="Bildschirmfoto 2021-08-16 um 09 50 57" src="https://user-images.githubusercontent.com/932156/129529760-b8323078-0e90-4481-ac1b-c534130522c0.png">

Thus, no change on the theme is required.
