### ISSUE TITLE
The code block annotations with the title are shown in the index

### ISSUE THREAD

**Issue by ErliSoares** [squidfunk/mkdocs-material#2966]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The code block annotations with the title are shown in the index.

### Expected behaviour

Hidden annotations in the index

### Actual behaviour

Annotations not displayed in index.

![image](https://user-images.githubusercontent.com/2334509/130535021-d12064c6-989f-48e5-b33e-b11e2e723cfe.png)

### Steps to reproduce

File index.md, remove #

``` markdown

#```DART
List<AggregatorField>? aggregators; // (1)
#```
1. Example

    ## Title 1

    ### Title 1.2
```

### Package versions

- Python: 3.9.6
- MkDocs: 1.2.2
- Material: 7.2.4+insiders.2.13.1

### Configuration

```yaml
site_name: Example

copyright: Example

theme:
  name: material
  custom_dir: overrides
  
  include_search_page: false
  search_index_only: true
  
  language: pt
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: green
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Mudar para o modo escuro
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: green
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Mudar para o modo leve
  
plugins:
  - search
  - social
  - git-authors:
      show_contribution: true
  - git-revision-date-localized:
      timezone: America/Sao_Paulo
      locale: pt_BR
      type: timeago
      enable_creation_date: true
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Example: index.md
```

### System information

- Operating system: Windows
- Browser: Google Chrome - 92.0.4515.159
