### ISSUE TITLE
Feature suggestion: Was this page helpful?

### ISSUE THREAD

**Issue by rachel-rigdon-sp** [squidfunk/mkdocs-material#3011]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Is there a way to add a button/selectable element that users can select to show if a page is helpful? 

For example, something like this that will keep track of the number of people who have selected it:
![Screen Shot 2021-09-08 at 4 17 09 PM](https://user-images.githubusercontent.com/60661988/132586826-c70031ac-cfae-4ad3-94ce-9d767d15fde0.png)

Edit: I should note that I do not want to use a full comment system like Disqus.

### Use Cases

It could help documentarians and readers identify which pages are most successful. If several ppl mark a page as helpful, other readers are more likely to spend time on that page.

**Comment by squidfunk** [comment]
Thanks for suggesting. So, in general you can use any third-party vendor that supports this feature and drop some JavaScript into your `mkdocs.yml`. However, a native integration has been on my mind for quite some time, and it could be a great feature. However, where should the data go? What would need to be configurable? One idea would be to use __Google Analytics__ and let the user configure his/her own rating system:

- 👍
- 😊 / 🙁
- ⭐️⭐️⭐️⭐️⭐️

We could wire this up to the icon system, so icons could be rendered as buttons, and each button could have a dedicated value (`data`) and description. This way you could build a little dashboard in Google Analytics that assign the `data` values on those buttons as custom events/values for each page. Configuration could look like this:

``` yaml
extra:
  feedback:
    provider: google
    values:
      - icon: material/emoticon-happy-outline
        name: This page was helpful
        data: good
      - icon: material/emoticon-happy-outline
        name: This page could be improved
        data: bad
```
