### ISSUE TITLE
Weird UI/design bug?

### ISSUE THREAD

**Issue by dmitry-saritasa** [squidfunk/mkdocs-material#303]
# environment
python 3.5 
70:mkdocs==0.16.3
71:mkdocs-material==1.6.1

Fedora 25 / Chrome Version 56.0.2924.87 (64-bit)

I was using readthedocs theme before trying material

# run
docker run --rm -it -p 8000:8000 -v `pwd`:/docs squidfunk/mkdocs-material

# Seing Huge Font
![image](https://cloud.githubusercontent.com/assets/1747653/25404488/08cf4f98-29b5-11e7-8f35-c4590cdd29d1.png)

![image](https://cloud.githubusercontent.com/assets/1747653/25404595/74eaa614-29b5-11e7-9d7a-eb5ba176fca7.png)

and in js console
![image](https://cloud.githubusercontent.com/assets/1747653/25404473/f464be26-29b4-11e7-8da8-80b27220f0f4.png)

**full error dump**: https://gist.github.com/dmitry-saritasa/f98503012d10585b2764e1de769fcb9e

# my mkdocs.yml

```yaml
site_name: inapp
pages:
  - Home: index.md
  - Resources: resources.md
  - General rules about API: general.md
  - Authentication:
      - Regular authentication: 'auth.md'
      - Reseting password: 'reset-password.md'
  - Places: places.md
  - Chats: chats.md
  - Private chats: private-chats.md
  - Images: images.md
  - User's places: me-places.md
  - Push notifications:
      - Devices registration: pns.md
      - Server's push notifications: servers-push-notifications.md
  - Pusher Webhook Events: pusher-webhook-events.md
  - Errors: errors.md
  - Media: media.md
  - Time zones: timezones.md
  - Changelog: changelog.md

markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
    - tables
    - codehilite(guess_lang=false)
    - admonition
    - wikilinks
site_dir: .dev/docs
theme: 'material'
extra:
  feature:
    tabs: true
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

```

**Any ideas what am I doing wrong?**
