### ISSUE TITLE
sticky navigation tabs does not work

### ISSUE THREAD

**Issue by 9uest** [squidfunk/mkdocs-material#3033]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#sticky-navigation-tabs

sticky navigation tabs does not work

      

### Expected behaviour

<img src="https://user-images.githubusercontent.com/932156/102016974-29aa9080-3d64-11eb-87c6-accafcbee5bd.gif" alt="大根标题" style="max-width: 100%;">

### Actual behaviour

![22222](https://user-images.githubusercontent.com/11766504/133777099-98883f00-54c3-4462-903d-717a9f466f38.gif)

### Steps to reproduce

1.pip install mkdocs-material
2.change theme
3.Open the site in your browser

### Package versions

Python 3.9.1
mkdocs, version 1.2.2
mkdocs-material Version: 7.2.6

### Configuration

```yaml
site_name: My Docs

theme:
    name: material
    language: zh
    features:
      - content.code.annotate
      - content.tabs.link
      # - header.autohide
      # - navigation.expand
      - navigation.indexes
      #- navigation.instant
      - navigation.sections
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.top
      - navigation.tracking
      - search.highlight
      - search.share
      - search.suggest
      # - toc.integrate
    palette:
       - scheme: default
         primary: indigo
         accent: indigo
         toggle:
           icon: material/toggle-switch-off-outline
           name: Switch to dark mode
       - scheme: slate
         primary: grey
         accent: red
         toggle:
           icon: material/toggle-switch
           name: Switch to light mode

extra:
  search:
    language: 'jp'

nav:
  - Home:
    - Getting Started: index.md
  - Getting started:
    - Installation: contest/index.md
```

### System information

- Operating system: os 10.15.7 
- Browser: ...chrome 93.0.4577.63
