### ISSUE TITLE
favicon & logo: support fontawesome

### ISSUE THREAD

**Issue by casperdcl** [squidfunk/mkdocs-material#3040]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ~... the problem doesn't occur with the `mkdocs` or `readthedocs` themes~
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

doesn't work:
```yml
theme:
  name: material
  favicon: fontawesome/solid/book-reader
  logo: fontawesome/solid/book-reader
```
works:
```yml
theme:
  name: material
  favicon: https://github.com/squidfunk/mkdocs-material/raw/master/material/.icons/fontawesome/solid/book-reader.svg
  logo: https://github.com/squidfunk/mkdocs-material/raw/master/material/.icons/fontawesome/solid/book-reader.svg
```

given that `material/X` works, it would be expected that `fontawesome/X` & `octicons/X` also work.

### Package versions

- Python: 3.8.10
- MkDocs: 1.2.2
- Material: 7.2.6
