### ISSUE TITLE
Overriding translations via custom language uses English as fallback

### ISSUE THREAD

**Issue by coyoteecd** [squidfunk/mkdocs-material#3044]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I am trying to override translations for a (non-English) language as [documented here](https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/?h=language#customization). The override does work, however it requires that I define all the possible translation keys, because the fallback is always 'en' language. This is obviously not maintainable across mkdocs-material releases.

### Expected behaviour

I expect to be able to override a single translation for a language, while falling back to the built-in translations for the same language (not for en), as described in docs.

### Actual behaviour

It always uses English as fallback

### Steps to reproduce

**mkdocs.yml**
```yml
site_name: Example
theme:
    name: material
    language: ja-custom   
    custom_dir: 'custom-theme/'
nav:
   - index.md
```

**index.md**
```
# Header

This is a test

## Subheader

Sub

## Other
```

In custom-theme/partials/languages, I created a ja-custom.html with the following contents:
```
{% macro t(key) %}{{ {
  "toc.title": "目次"
}[key] }}{% endmacro %}
```

When I run mkdocs, all other theme translations are in English and only the toc.title is translated.

### Package versions

- Python: `python --version` 3.7.9
- MkDocs: `mkdocs --version` 1.2.2
- Material: `pip show mkdocs-material | grep -E ^Version` 7.2.8

### Configuration

```yaml
site_name: Example
docs_dir: docs
theme:
    name: material
    language: ja-custom   
    custom_dir: 'custom-theme/'
```

### System information

- Operating system: Windows
- Browser: Any
