### ISSUE TITLE
Search returning entire page in search box [mkdocs-material insiders] 

### ISSUE THREAD

**Issue by albertkun** [squidfunk/mkdocs-material#3053]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Using `mkdocs-material insiders` search function seems to be returning the entire pages content alongside the paragraph symbol in the search results. This only occurs using deployment on GitHub pages, not locally.

### Expected behaviour

I expect the search function to work the same on deployment as it does locally and not display the entire content of the page in the search tool, as follows:

![image](https://user-images.githubusercontent.com/8574425/134752627-7621172a-0d79-4766-b38b-b4c170d6bc81.png)

### Actual behaviour

The insiders version of mkdocs-material makes the search result return all of the page in its entirety. 
![image](https://user-images.githubusercontent.com/8574425/134752597-ffec7669-87c9-4239-b922-1ed0514f4872.png)

### Steps to reproduce

1. Add `tags` to pages using `mkdocs-material insiders`
2. Commit to GitHub repository
3. Use GitHub actions to deploy: 
``` bash
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
        env:
      - run: pip install git+https://${ALBERT_KEY}@github.com/squidfunk/mkdocs-material-insiders.git
        env:
          ALBERT_KEY: ${{secrets.ALBERT_KEY}}      
```
4. Test out search
5. Search bug appears.

### Package versions

- Python: `Python 3.9.5`
- MkDocs: `mkdocs, version 1.2.2`
- Material: `7.2.8+insiders.3.0.1`

### Configuration

```yaml
site_name: LA Metro Digital Services Team Docs
repo_url: https://github.com/LACMTA/digital-services-team-docs/

theme:
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode  
  font:
    text: Open Sans
  favicon: assets/media/favicon.png
  logo: assets/media/favicon-reverse.png
  name: material
  features:
      - navigation.instant
      - navigation.tabs
      - content.code.annotate
      - search.highlight
      - toc.integrate
      - navigation.indexes
      - navigation.top
      - search.suggest      

  icon:
    repo: fontawesome/brands/github

markdown_extensions:
    - pymdownx.superfences
    - pymdownx.magiclink
    - smarty
    - meta
    - toc:
        permalink: True
        toc_depth: 2
    - sane_lists
    - admonition
    - footnotes
    - attr_list

edit_uri: edit/dev/docs/
plugins:
  - git-revision-date
  - autorefs
  - table-reader
  - macros
  - tags
  - search:
      lang: en
```

### System information

- Operating system: Windows 10
- Browser: Firefox 92.0

**Comment by squidfunk** [comment]
Thanks for the reporting. That looks off indeed. It's weird that it only happens when run from GitHub Actions. Could you please include the Markdown of the page and upload the contents of the `search/search_index.json` file? That could be a great help in finding and isolating the issue.

**Comment by squidfunk** [comment]
The project in question is here, correct?
https://github.com/LACMTA/digital-services-team-docs/

**Comment by squidfunk** [comment]
Okay, here's what I think is happening:

I took a look at your repository and realized that the [`search_index.json`](https://github.com/LACMTA/digital-services-team-docs/blob/dev/site/search/search_index.json) has the old format, meaning that it was not generated by the new search plugin. The old format includes exactly what you're seeing – the contents of the entire page with permalink markers etc. in the main entry of the page:

<details>
<summary>Expand</summary>

``` json
{
  "config":{
    "indexing":"full",
    "lang":[
      "en"
    ],
    "min_search_length":3,
    "prebuild_index":false,
    "separator":"[\\s\\-]+"
  },
  "docs":[
    {
      "location":"",
      "text":"Welcome to LA Metro Digital Design System Docs \u00b6 This repository is an internal resource for the Digital Services Team at Metro. Documentation either does not exist, is outdated, exists on old platforms, or exists across multiple platforms used by different people. There is a need to centralize and keep documentation up-to-date for the entire team to use and reference. Do not put any account credentials or private keys here. Contributing \u00b6 To provide more information on the various Digital Design Projects at LA Metro, people can contribute to this documentation by following these steps: Pre-requisites \u00b6 Software \u00b6 Make sure you have the following installed: - GitSVN - VS Code (or other text based editor) Accounts \u00b6 -GitHub.com account Clone the Repository \u00b6 Open your editor and run in the terminal: git clone https://github.com/albertkun/digital-design-system-docs.git Categories \u00b6 Web Properties Tools/Services (through P-Card or ITS) Processes Shakeup updates Questions \u00b6 Feel free to reach out if you have any questions!",
      "title":"Welcome to LA Metro Digital Design System Docs"
    },
    {
      "location":"#welcome-to-la-metro-digital-design-system-docs",
      "text":"This repository is an internal resource for the Digital Services Team at Metro. Documentation either does not exist, is outdated, exists on old platforms, or exists across multiple platforms used by different people. There is a need to centralize and keep documentation up-to-date for the entire team to use and reference. Do not put any account credentials or private keys here.",
      "title":"Welcome to LA Metro Digital Design System Docs"
    },
    {
      "location":"#contributing",
      "text":"To provide more information on the various Digital Design Projects at LA Metro, people can contribute to this documentation by following these steps:",
      "title":"Contributing"
    },
    {
      "location":"#pre-requisites",
      "text":"",
      "title":"Pre-requisites"
    },
    {
      "location":"#clone-the-repository",
      "text":"Open your editor and run in the terminal: git clone https://github.com/albertkun/digital-design-system-docs.git",
      "title":"Clone the Repository"
    },
    {
      "location":"#categories",
      "text":"Web Properties Tools/Services (through P-Card or ITS) Processes Shakeup updates",
      "title":"Categories"
    },
    {
      "location":"#questions",
      "text":"Feel free to reach out if you have any questions!",
      "title":"Questions"
    }
  ]
} 
```
</details>

This is also (a subset?) of what you've posted in the screenshot – the main entry lists all contents including headlines and permalink markers. My guess is that when you've visited the page, somehow a stale version of the `search_index.json` was loaded. It means that your browser probably hasn't requested the new `search_index.json` due to some cache headers telling it not to, but loaded the new JavaScript and CSS sources, because they include [content hashes](https://github.com/squidfunk/mkdocs-material/blob/ba1f021c7658e54d28f2737d0960f8258abfb320/material/base.html#L228), which the search index doesn't.

I would kindly ask you to verify two things:

1. Please check that the `search_index.json` which is loaded in the browser has the correct format. Please see the [latest blog post](https://squidfunk.github.io/mkdocs-material/blog/2021/search-better-faster-smaller/), which explains in detail how the old and new `search_index.json` differ, and how it should look, and inspect the contents of the `search_index.json` in the developer tools.

2. Try to deploy your project to another domain, and see whether the issue persists. If it goes away, it's very likely related to cache headers, because the cache requests will now miss due to the new domain.

**Comment by albertkun** [comment]
> 
> 
> The project in question is here, correct?
> https://github.com/LACMTA/digital-services-team-docs/

yes, that is correct!

**Comment by albertkun** [comment]
> 
> 
> Okay, here's what I think is happening:
> 
> I took a look at your repository and realized that the [`search_index.json`](https://github.com/LACMTA/digital-services-team-docs/blob/dev/site/search/search_index.json) has the old format, meaning that it was not generated by the new search plugin. The old format includes exactly what you're seeing – the contents of the entire page with permalink markers etc. in the main entry of the page:
> Expand
> 
> This is also (a subset?) of what you've posted in the screenshot – the main entry lists all contents including headlines and permalink markers. My guess is that when you've visited the page, somehow a stale version of the `search_index.json` was loaded. It means that your browser probably hasn't requested the new `search_index.json` due to some cache headers telling it not to, but loaded the new JavaScript and CSS sources, because they include [content hashes](https://github.com/squidfunk/mkdocs-material/blob/ba1f021c7658e54d28f2737d0960f8258abfb320/material/base.html#L228), which the search index doesn't.
> 
> I would kindly ask you to verify two things:
> 
>     1. Please check that the `search_index.json` which is loaded in the browser has the correct format. Please see the [latest blog post](https://squidfunk.github.io/mkdocs-material/blog/2021/search-better-faster-smaller/), which explains in detail how the old and new `search_index.json` differ, and how it should look, and inspect the contents of the `search_index.json` in the developer tools.
> 
>     2. Try to deploy your project to another domain, and see whether the issue persists. If it goes away, it's very likely related to cache headers, because the cache requests will now miss due to the new domain.
> 
> 
> On a side note: a few days ago, somebody also reported this on Gitter, but the problem seems to have just gone away because I didn't hear back from him, which also sounds like a caching problem that has solved itself.

the `search.json` has the incorrect format I believe, here is how it looks in the browser:
![image](https://user-images.githubusercontent.com/8574425/134788350-4285f17a-9fd8-4cbc-8bf6-52390043033c.png)

In addition to the link:
https://lacmta.github.io/digital-services-team-docs/search/search_index.json

Regarding deploying to another domain, how should I approach this using GitHub pages? Should I just clone into a new repository?

Thank you for taking the time to look into this!!

**Comment by squidfunk** [comment]
Thanks for investigating. Yes, that looks broken indeed. If you compare it to the `search_index.json` that you get when you do a local `mkdocs build`, it will be very different. For this reason, the reported behavior can be clearly attributed to a broken deployment or invalid cache headers. As you're using GitHub, the former is more likely to be true, because they use very short  durations (just checked: `cache-control: max-age=600` for JSON).

As the `site` folder is part of `master` branch, it looks like you're using something different from the default behavior of MkDocs. The simplest fix is probably just to use the recommended approach, which will deploy to a dedicated branch called `gh-pages`. If that is not what you're aiming for, you should probably ask a team member or somebody else on your organization with the right privileges to fix the configuration.

I'm closing this issue since this is not an error that is related to Material for MkDocs, but to a deployment misconfiguration.

---

> Regarding deploying to another domain, how should I approach this using GitHub pages? Should I just clone into a new repository?

You could fork the repository and deploy it again, yes.

**Comment by albertkun** [comment]
@squidfunk hmm, working on this a little more... I'm still unable to resolve this, even by forking or using the default github actions... I was able to resolve this by running `mkdocs gh-deploy --force` locally... however this is not ideal since we would like to run github actions to build it.. Here's the current github actions `.yml` file:

```
name: Deploy Documentation 
on:
  push:
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install git+https://${GH_TOKEN}@github.com/LACMTA/mkdocs-material-insiders.git
      - run: mkdocs gh-deploy --force

env:
  GH_TOKEN: ${{secrets.ALBERT_KEY}}          
  METRO_DOCS_PASS: ${{secrets.METRO_DOCS_PASS}}

```
[https://github.com/LACMTA/digital-services-team-docs/blob/dev/.github/workflows/main.yml](https://github.com/LACMTA/digital-services-team-docs/blob/dev/.github/workflows/main.yml)

Any other insights would be appreciated!! Thank you!
