### ISSUE TITLE
Annotations in code blocks are not showing up

### ISSUE THREAD

**Issue by ehguille** [squidfunk/mkdocs-material#3062]
### Contribution guidelines

- [x] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Code annotations are not shown when enabled.

Markdown code (copied from docs).

![image](https://user-images.githubusercontent.com/55703981/135444593-3a84d6b3-831a-4f27-8b73-5964a5558d6e.png)

```

``` js
document$.subscribe(function() { // (1)
  var tables = document.querySelectorAll(/* (2) */ "article table")
  tables.forEach(function(table) {
    new Tablesort(table)
  })
})
\```  slash written to avoid ``` closing the code, not included in the actual code.

1. A comment
2. Another comment

```

### Expected behaviour

Annotation blocks poping up

### Actual behaviour

Annotations are shown like a list.

Result: 

![image](https://user-images.githubusercontent.com/55703981/135444194-15b5ba73-06c7-4318-a8f7-2def18719b7c.png)

### Steps to reproduce

mkdocs serve

### Package versions

Python 3.9.7

mkdocs, version 1.2.2 from c:\users\guillermo\appdata\local\programs\python\python39\lib\site-packages\mkdocs (Python 3.9)

Name: mkdocs-material
Version: 7.2.6

### Configuration

```yaml
theme:
  name: material
  logo: assets/imgs/logo.png
  favicon: assets/imgs/logo.png
 # custom_dir: overrides
  font: false
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: default
    primary: java
    accent: indigo
  language: es
  features:
    - content.code.annotate
    - search.suggest
    - navigation.instant
    - search.highlight
    - header.autohide
    - navigation.tabs 
    - navigation.indexes
    - navigation.top
    - navigation.tracking
   
#extra_javascript:
#  - https://kit.fontawesome.com/8c2d521aaf.js


plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: datetime  

  
#extra_css:
#    - 'assets/stylesheets/extra.css'
  
markdown_extensions: 
    - attr_list
    - abbr
    - admonition
    - pymdownx.caret
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.smartsymbols
    - pymdownx.tilde
    - pymdownx.inlinehilite
    - pymdownx.mark
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.extra
    - pymdownx.magiclink
    - pymdownx.progressbar
    - pymdownx.tasklist
    - pymdownx.tabbed
    - pymdownx.critic
    - markdown.extensions.footnotes
    - markdown.extensions.tables
    - pymdownx.snippets
    - def_list
    - meta
    - lightgallery
    - toc:
       toc_depth: 5
    - smarty:
       smart_angled_quotes: true
       smart_dashes: false
    - pymdownx.emoji:
       emoji_index: !!python/name:materialx.emoji.twemoji
       emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.betterem:
       smart_enable: true
    - pymdownx.tasklist:
       custom_checkbox: true
```

### System information

- Windows 10.
-  Chrome, Firefox.
