### ISSUE TITLE
navigation.indexes incompatible with navigation.sections

### ISSUE THREAD

**Issue by worldtiki** [squidfunk/mkdocs-material#3070]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [x] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

### Description

The documentation says the `navigation.indexes` feature [is compatible with all other feature flags](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages) however it doesn't seem to work if I enable navigation.sections.

When only `navigation.indexes` is enabled this feature works ok.
However when combined with `navigation.sections` then the section indices are no longer clickable.

<img width="1414" alt="nobug" src="https://user-images.githubusercontent.com/1187103/135643828-7ba13210-92dc-4ac1-9797-860a9ec77792.png">

<img width="1370" alt="bug" src="https://user-images.githubusercontent.com/1187103/135643838-e8ae97d5-7113-40b6-a4d2-129679c500af.png">

### Expected behaviour

Both features should be compatible with each other.

### Actual behaviour

Section indices are not clickable when both features are enabled.

### Steps to reproduce

Enable both `navigation.sections` and `navigation.indexes`.

```
theme
  features:
    - tabs
    - navigation.tabs
    #- navigation.sections
    - navigation.indexes
```

### Package versions

Using docker image: squidfunk/mkdocs-material:7.3.0

### Configuration

```yaml
site_name: My website
docs_dir: 'src'
site_dir: 'docs'

theme:
  name: material
  icon:
    logo: octicons/rocket-16
  favicon: 'images/favicon.ico'
  features:
    - tabs
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - instant
    - navigation.tracking
  palette:
    primary: indigo
    accent: blue

plugins:
  - search:
     lang:
        - en

nav:
  - Potato:
      - Foo:
        - 'foo/index.md'
        - Something: 'foo/another_page'
      - Bar:
        - 'bar/index.md'
        - Something: 'bar/another_page'
  - Tomato:
      - Radars: 'something/something.md'

# Repository
repo_name: myrepo
repo_url: https://github.com/myrepo/
edit_uri: edit/master/src/
```

### System information

- Operating system: macOS Big Sur
- Browser: Google Chrome latest
