### ISSUE TITLE
Incorrect path character used when building on Windows 

### ISSUE THREAD

**Issue by seankearon** [squidfunk/mkdocs-material#3077]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

This relates to [this discussion](https://github.com/squidfunk/mkdocs-material/discussions/3074).

When building social cards on Windows, the generated HTML contains some Windows path separators `\`.

### Expected behaviour

Social asset paths should use the 'nix path separator:

``` HTML
<meta name=twitter:image content=assets/images/social/pirform/automation.png>
```

### Actual behaviour

The social asset patch use the Windows path separator:

``` HTML
<meta name=twitter:image content=assets/images/social\pirform\automation.png>
```

### Steps to reproduce

1. Set up a docs site using social cards.
2. Set up a build on a Windows machine (I was using an Azure DevOps pipeline with the agent set to `windows-latest`).
3. Inspect the HTML output and you will see that the Windows separator is used, as above.

### Package versions

- Python: `3.9.4`
- MkDocs: `1.2.2`
- Material: `7.3.0+insiders.3.1.1`

### Configuration

```yaml
site_name: Repro Docs

site_description: >-
  Docs to repro the issue

theme:
  name: 'material'
  favicon: 'favicon.ico'  

plugins:
    - social:
        cards_color:
          fill: "#029fe3"
          text: "#FFFFFF"
    - minify:
        minify_html: true
```

### System information

- Operating system: N/A
- Browser: N/A
