### ISSUE TITLE
Single-line code annotations disappear when printing

### ISSUE THREAD

**Issue by lampensau** [squidfunk/mkdocs-material#3089]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I've noticed that my code annotations only appear with their numbering on the printed output on Firefox 93.0 and Chrome 94 when using the example [provided](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations) in the documentation.

### Expected behaviour

Code annotations should be fully visible and printed below a code block.

![grafik](https://user-images.githubusercontent.com/12431219/136280187-b4f6fc4b-02d8-491e-9859-cc0e4f4414e4.png)

### Actual behaviour

Only the list numbers are visible below a code block.

![grafik](https://user-images.githubusercontent.com/12431219/136279079-5a0d6f72-2c99-40c0-b3d7-a38e2daf3c5f.png)

### Steps to reproduce

1. Create a new mkdocs project `mkdocs new .`.
2. Use the configuration posted below.
3. Edit the index.md:
    ```` markdown
    # Welcome to MkDocs
    
    For full documentation visit [mkdocs.org](https://www.mkdocs.org).
    
    ## Testing
    
    ``` js
    document$.subscribe(function() { // (1)
      var tables = document.querySelectorAll(/* (2) */ "article table")
      tables.forEach(function(table) {
        new Tablesort(table)
      })
    })
    ```
    
    1. Annotation 1
    2. Annotation 2
    ````
4. Build documentation and print index.html

P.S. Workaround seems to be a new-line between the list elements:

```` markdown
# Welcome to MkDocs

For full documentation visit [mkdocs.org](https://www.mkdocs.org).

## Testing

``` js
document$.subscribe(function() { // (1)
  var tables = document.querySelectorAll(/* (2) */ "article table")
  tables.forEach(function(table) {
    new Tablesort(table)
  })
})
```

1. Annotation 1

2. Annotation 2
````

### Package versions

- Python: 3.9.2
- MkDocs: 1.2.2
- Material: 7.3.2+insiders.3.1.2

### Configuration

```yaml
site_name: 'My Docs'

theme:
  name: material
  features:
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
```

### System information

- Operating system: Windows 10
- Browser: Chrome 94.0.4606.71, Firefox 93.0
