### ISSUE TITLE
Better ReadTheDocs integration

### ISSUE THREAD

**Issue by 2bndy5** [squidfunk/mkdocs-material#3104]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

There's 1 feature that hosting from readthedocs.org has over gh-pages: Different built versions of docs based on tagged commits or separate branches. When you browse any docs hosted by RTFD, you will see a added selector menu that looks like
![image](https://user-images.githubusercontent.com/14963867/136911757-e26d2de7-fafc-45a1-bf29-d87bd42e9900.png)
or in the official readthedocs sphinx theme
![image](https://user-images.githubusercontent.com/14963867/136911945-10daef42-0f64-44e8-a38a-a59f932a4e0c.png)

When expanded, the menu looks like 
![image](https://user-images.githubusercontent.com/14963867/136912182-ac91c1fc-3184-4844-ba3d-ce0790b3b4dc.png)

---
I've worked out how to do this on a theme based on this repo, but I think it would be better to have this feature upstream. Please excuse my assumptions based on the repo structure.

<details><summary><i>src/partials/integrations/readthedocs.html</i></summary>

Most of this was copied from the html template used in the readthedocs sphinx theme

```html
{% if READTHEDOCS %}
{# This integration is specially styled to cohesively appear in the nav menu. #}
  <div class="md-nav__rtd-versions" data-toggle="rst-current-version" aria-label="{{ _('Versions') }}">
    <span class="md-nav__rtd-current-version" data-toggle="rst-current-version">
      <span class="md-nav__rtd-fa-book"> Read The Docs</span>
      v: {{ current_version }}
      <span class="md-nav__rtd-fa-caret"></span>
    </span>
  </div>
  <div class="md-nav__rtd-other-versions">
    <dl>
      <dt>{{ _('Versions') }}</dt>
      {% for slug, url in versions %}
        <dd><a href="{{ url }}">{{ slug }}</a></dd>
      {% endfor %}
    </dl>
    {% if downloads|length > 0 %}
    <dl>
      <dt>{{ _('Downloads') }}</dt>
      {% for type, url in downloads %}
        <dd><a href="{{ url }}">{{ type }}</a></dd>
      {% endfor %}
    </dl>
    {% endif %}
    <dl>
      {# Translators: The phrase "Read the Docs" is not translated #}
      <dt>{{ _('On Read the Docs') }}</dt>
        <dd>
          <a href="//{{ PRODUCTION_DOMAIN }}/projects/{{ slug }}">{{ _('Project Home') }}</a>
        </dd>
        <dd>
          <a href="//{{ PRODUCTION_DOMAIN }}/projects/{{ slug }}/builds">{{ _('Builds') }}</a>
        </dd>
    </dl>
  </div>
{% endif %}
```
</details>

```diff
--- src/partials/nav.html
+++ src/partials/nav.html
@@ -53,58 +53,59 @@
   <!-- Repository information -->
   {% if config.repo_url %}
     <div class="md-nav__source">
       {% include "partials/source.html" %}
     </div>
   {% endif %}
+  {% include "partials/integrations/readthedocs.html" %}
```

<details><summary><i>src/assets/stylesheets/main/extensions/readthedocs/_readthedocs.scss</i></summary>

```scss
:root {
  --md-rtd-book-icon: svg-load("fontawesome/solid/book.svg");
  --md-rtd-caret-down-icon: svg-load("fontawesome/solid/caret-down.svg");
  --md-rtd-caret-left-icon: svg-load("fontawesome/solid/caret-left.svg");
}

.md-nav__rtd-versions {
  padding: 12px;
  display: block;
  text-align: right;
  background-color: #272525;
  cursor: pointer;
  color: #fefefe;

  .md-nav__rtd-current-version {
    color: #27ae60;

    .md-nav__rtd-fa-book {
      float: left;
      color: #fefefe;

      &::before{
        display: inline-block;
        width: 0.7rem;
        height: 0.7rem;
        background-color: currentColor;
        mask-image: var(--md-rtd-book-icon);
        mask-repeat: no-repeat;
        content: "";
      }
    }

    .md-nav__rtd-fa-caret {
      color: #fefefe;

      &::before {
        display: inline-block;
        width: 0.5rem;
        height: 0.7rem;
        background-color: currentColor;
        mask-image: var(--md-rtd-caret-left-icon);
        mask-repeat: no-repeat;
        content: "";
      }

      &.expanded {
        color: #fefefe;

        &::before {
          display: inline-block;
          width: 0.5rem;
          height: 0.7rem;
          background-color: currentColor;
          mask-image: var(--md-rtd-caret-down-icon);
          mask-repeat: no-repeat;
          content: "";
        }
      }
    }
  }
}

.md-nav__rtd-other-versions {
  text-align: left;
  display: none;
  background-color: #1f1d1d;
  overflow-y: auto;

  &.expanded {
    display: block;
  }

  a {
    border: 0;
  }

  dl {
    margin: 0 0.3rem;
  }
  dt {
    color: grey;
    padding: .25rem 0;
  }
  dd {
    display: inline-block;
    margin: .25rem;
  }
}
```
</details>

```diff
--- src/assets/stylesheets/main.scss
+++ src/assets/stylesheets/main.scss
@@ -73,75 +73,76 @@
 @import "main/extensions/pymdownx/tasklist";
 
+@import "main/extensions/readthedocs/readthedocs";
```

<details><summary><i>src/assets/javascripts/integrations/readthedocs/index.ts</i></summary>

```ts
/* insert License here */

function toggleReadTheDocsContextDetails(): void {
    var caret = document.getElementsByClassName("md-nav__rtd-fa-caret");
    var contextDetails = document.getElementsByClassName("md-nav__rtd-other-versions");
    caret[0].classList.toggle("expanded");
    contextDetails[0].classList.toggle("expanded");
}

export function setupReadTheDocsVersionSelector(): void {
    var currentVersion = document.getElementsByClassName("md-nav__rtd-versions");
    if (currentVersion.length > 0) {
        currentVersion[0].addEventListener("click", toggleReadTheDocsContextDetails, false);
    }
}
```
</details>

```diff
--- src/assets/javascripts/integrations/index.ts
+++ src/assets/javascripts/integrations/index.ts
@@ -23,26 +23,27 @@
 export * from "./clipboard"
 export * from "./instant"
 export * from "./search"
 export * from "./version"
+export * from "./readthedocs"
```

```diff
--- src/assets/javascripts/bundle.ts
+++ src/assets/javascripts/bundle.ts
@@ --114,117 +114,119 @@
 /* Set up version selector */
 if (config.version?.provider === "mike")
   setupVersionSelector()

+/* setup ReadTheDocs version selector */
+setupReadTheDocsVersionSelector();
+
```

### Use Cases

Literally anyone using readthedocs.org to host their documentation would benefit from this.

I often refer beta testers to a separate set of docs build from a dev branch.

I would like to raise the question, what would happen if the user disables the nav menu? Normally themes that don't have this feature supported have a floating equivalent menu in the lower right corner. However, this alternative menu placement doesn't seem to work with mkdocs themes.

### Screenshots / Mockups

I decided to place the added menu atop all nav menu items. The following mockup results are done from the sphinx-immaterial theme (which is based on the latest release of this repo). These screenshots can be observed live from my project hosted at https://circuitpython-nrf24l01.readthedocs.io/en/rf24-network/

![image](https://user-images.githubusercontent.com/14963867/136918918-547d1f0c-adfd-4d0e-bf61-02446e04abda.png)
expanded this looks like
![image](https://user-images.githubusercontent.com/14963867/136919301-90b274b1-a850-4358-9788-01aee154cf46.png)

Compared to the native feature from screenshots at the top of this post, you'll notice that I left out the search input box (for obvious reasons). The "Downloads" section would show up if the project had additional formats of documentation (such as PDF or EPUB).
