### ISSUE TITLE
Pages that do not render TOC are out of alignment

### ISSUE THREAD

**Issue by jheidecker** [squidfunk/mkdocs-material#3108]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Pages that are too short to generate the right-side TOC are shifted 17px rightward.

I wish I could offer more detail into the issue but CSS is not my jam. I can see that it occurs on your reference [pages site](https://squidfunk.github.io/mkdocs-material/license/) as well so at least it's not my setup!

One thing I did notice was that the md-container div on the License page (no TOC, no content in md-sidebar__inner?) is 1480x953 BUT on most other pages (TOC, md-nav md-nav--secondary) it is 1463x5961.36.

I dunno. It's just one of those little irritating inconsistences. Otherwise amazing work! This won't stop me from using the insiders ver.

Tested with Chromium 94.0.4606.81 and Edge 94.0.992.50

![mkdocs_material](https://user-images.githubusercontent.com/5976429/137549060-17727322-a0b9-4494-985f-367582c2d051.png)

### Expected behaviour

To maintain the size and alignment despite the presence of the TOC on the right.

### Actual behaviour

It doesn't.

### Steps to reproduce

Switch between https://squidfunk.github.io/mkdocs-material/license/ and https://squidfunk.github.io/mkdocs-material/customization/ and watch everything move.

### Package versions

- Python: `3.9.5`
- MkDocs: `1.2.3`
- Material: `mkdocs-material-7.3.3-insiders-3.1.3`

### Configuration

```yaml
site_name: a site
theme:
  name: null
  custom_dir: mkdocs-material-insiders/material
  features:
    - navigation.top
    - navigation.tracking

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

  palette:
    scheme: slate
    primary: red
    accent: light blue

plugins:
    - search
    - pdf-export:
        verbose: true
        media_type: print
    - tags

copyright: Copyright &copy; 2021 Me!
extra:
  generator: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
```

### System information

- Operating system: Windows 10 Pro 21H1 19043.1288 120.2212.3920.0
- Browser: Brave 1.30.89

**Comment by squidfunk** [comment]
Thanks for reporting. Yes, there were some changes in 7.3.3 where I tried to fix some spacing issues with right-to-left languages, so it's very likely related to those changes. I'll check where I got it wrong.

**Comment by squidfunk** [comment]
Ah, so I think now I understand the exact problem you're describing. It's not related to the spacing issues I mentioned, that were partly fixed in 7.3.2, and hopefully fully fixed in f073fb2c25a870889a44f8124206a3a8841b7f90, but comes from the scrollbar that is rendered on the right for pages that exceed the available screen length.

I don't see how we can fix this once and for all, because scrollbars are very different between operating systems and sometimes browsers. For instance, macOS always renders the scrollbar as an overlay over the page, while Windows still seems to render it as part of the window, reducing the available estate which leads to the page moving left, because it's centered.

### Possible mitigations

1. Always show the scrollbar, which can be achieved by setting `overflow-y: scroll` on `html` with some [custom CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css). Note that this is too opinionated to include in `master`, as other users (including me) dislike when scrollbars are always visible, even though the page doesn't include any content to scroll to. It's a matter of taste after all. Possible fix:

    ``` css
    html {
      overflow-y: scroll;
    }
    ```
2. We could maybe set [`scrollbar-gutter`](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter) on `html` to a reasonable value. Sadly, [browser adoption is not that great yet](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter#browser_compatibility), so it's not a portable solution. If you (or somebody else) could test this on Windows and set it to a reasonable value that doesn't break anything else, I'm happy to collaborate on a PR. Possible fix:

     ``` css
    html {
      scrollbar-gutter: 16px; /* is this a good value? – I don't know */
    }
    ```

This also means that this issue is rather an enhancement than a bug, which sadly "won't fix" for the reasons stated. Note that this applies to Material for MkDocs, as well as Insiders regardless of version.
