### ISSUE TITLE
Regression (7.3.2): Left navbar with tabs should not render for tabs with no subpages

### ISSUE THREAD

**Issue by polarathene** [squidfunk/mkdocs-material#3109]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

[A regression via our CI for docs has been noticed](https://github.com/docker-mailserver/docker-mailserver/pull/2244) when updating the docker image version for `squidfunk/mkdocs-material`.

The left nav (DOM node `ul.md-nav__list`) now includes a single link rendered below our tabs when there are no subpages (the tab is a direct markdown file).

HTML has been identified between both, the same node exists, just in the past the nav list has been hidden visually. Presumably a CSS regression?

Example from `mkdocs.yml`:

```yml
nav:
  # These top-level keys with direct page values should not render a redundant left nav:
  - 'Home': index.md
  - 'Introduction': introduction.md
  # Examples tab has subpages, it should render a left nav:
  - 'Examples':
    - 'Tutorials':
      - 'Basic Installation': examples/tutorials/basic-installation.md
      - 'Mailserver behind Proxy': examples/tutorials/mailserver-behind-proxy.md
```

### Expected behaviour

Tabs that have no subpages should have an empty left side-bar.

![Screenshot_20211016_124526](https://user-images.githubusercontent.com/5098581/137564944-ea30ef32-9653-4b6b-86e8-4b95b7dd7356.png)

![Screenshot_20211016_124541](https://user-images.githubusercontent.com/5098581/137564953-c72aa4d7-e258-4e44-a873-9ed32a7d66ff.png)

### Actual behaviour

Tabs that have no subpages are rendering a side-bar with a single link to the same page.

![Screenshot_20211016_124345](https://user-images.githubusercontent.com/5098581/137564870-3144b195-0c44-4047-a51b-77e2769db203.png)

![Screenshot_20211016_124433](https://user-images.githubusercontent.com/5098581/137564906-5cf6dc2b-7b8a-49a8-b0e2-fa17ff49c8dc.png)

### Steps to reproduce

1. Our docs can be built from our repo `docs/` folder, here is the [`mkdocs.yml`](https://github.com/docker-mailserver/docker-mailserver/blob/fb77d3f7210ff4501f454020809a72704a350d48/docs/mkdocs.yml) from that location.
2. We presently build docs via docker image with the tag `7.3.0`, a recent PR to update to `7.3.2` is where regression was noticed via our CI deploy preview.

```bash
docker run \
  --rm \
  -v "${PWD}:/docs" \
  squidfunk/mkdocs-material:7.3.2 build --strict
```

A more minimal reproduction will be identified and this issue updated.

### Package versions

All handled via the official `squiidfunk/mkdocs-material` Docker image. If necessary, this information can be pulled from that, release tag `7.3.2` is a known regression, `7.3.0` a known good state.

---

- Python: `python --version`
- MkDocs: `mkdocs --version`
- Material: `pip show mkdocs-material | grep -E ^Version`

### Configuration

```yaml
[`mkdocs.yml`](https://github.com/docker-mailserver/docker-mailserver/blob/fb77d3f7210ff4501f454020809a72704a350d48/docs/mkdocs.yml). Once a minimal reproduction is done, this will be updated with the minimal `mkdocs.yml` contents to reproduce.
```

### System information

This is for my system, but other users have different OS and browsers. The docs are built via Github CI with the official Docker image.

- Operating system: Linux (Manjaro)
- Browser: Only tested on Brave (Chromium)
