### ISSUE TITLE
Localsearch plugin says not installed after mkdocs upgrade

### ISSUE THREAD

**Issue by shaneholloman** [squidfunk/mkdocs-material#3111]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

`mkdocs build` was not an issue before upgrade to 7.3.3 from 7.2.8

I updated to benefit from the new improved search

These errors are showing after `pip install --upgrade mkdocs-material`

```sh
pip show mkdocs-material
Name: mkdocs-material
Version: 7.3.3
```

- My update was a minor version
- Here is the shell complaint

```sh
mkdocs build
ERROR    -  Config value: 'markdown_extensions'. Error: Failed loading extension "mdx_spanner".
ERROR    -  Config value: 'plugins'. Error: The "localsearch" plugin is not installed
Aborted with 2 Configuration Errors!
```

### Expected behaviour

no errors

### Actual behaviour

```sh
mkdocs build
ERROR    -  Config value: 'markdown_extensions'. Error: Failed loading extension "mdx_spanner".
ERROR    -  Config value: 'plugins'. Error: The "localsearch" plugin is not installed
Aborted with 2 Configuration Errors!
```

### Steps to reproduce

`mkdocs build`

### Package versions

- Python: `Python 3.10.0`
- MkDocs: `mkdocs, version 1.2.3 from C:\Python310\lib\site-packages\mkdocs (Python 3.10)`
- Material: `Version: 7.3.3`

### Configuration

```yaml
---
copyright: Copyright &copy; 2021 Shane Holloman
edit_uri: ""
extra:
  consent:
    title: Cookie consent
    description: >
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shaneholloman/resume
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/shaneholloman
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/shaneholloman/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/shane.holloman.nz
extra_css:
  - assets/css/extra.css
  - assets/css/hint.min.css
extra_javascript:
  - assets/js/tablesort.min.js
  - assets/js/mermaid.min.js
  - assets/js/tables.js
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - mdx_spanner
  - meta
  - toc:
      permalink: ⚓︎
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.escapeall
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.magiclink:
      repo: resume
      repo_url_shorthand: true
      user: shaneholloman
  - pymdownx.tasklist:
      clickable_checkbox: true
      custom_checkbox: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.highlight:
      linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
plugins:
  - search
  - localsearch
  - tooltips
  - progress
  - redirects:
      redirect_maps: null
  - minify:
      minify_html: true
  #- enumerate-headings:
  #    toc_depth: 2
  #- git-revision-date-localized
  #- print-site
repo_name: github.com
repo_url: https://github.com/shaneholloman/resume
site_author: Shane Holloman
site_description: DevOps and Infrastructure
site_name: Oracle
site_url: null
theme:
  admonition:
    abstract: fontawesome/solid/book
    bug: fontawesome/solid/robot
    danger: fontawesome/solid/skull
    example: fontawesome/solid/flask
    failure: fontawesome/solid/bomb
    info: fontawesome/solid/info-circle
    note: fontawesome/solid/sticky-note
    question: fontawesome/solid/question-circle
    quote: fontawesome/solid/quote-left
    success: fontawesome/solid/check
    tip: fontawesome/solid/bullhorn
    warning: fontawesome/solid/exclamation-triangle
  custom_dir: theme
  features:
    - content.tabs.link
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  font:
    code: Roboto Mono
    text: Roboto
  icon:
    logo: alien # material/alien
  favicon: assets/img/alien.svg
  language: en
  name: material
  palette:
    - accent: deep orange
      primary: black
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - accent: deep orange
      primary: deep orange
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
use_directory_urls: false
```

### System information

- Operating system: Win10
- Browser: Any
