### ISSUE TITLE
Allow for palette toggle to include "match system preference"

### ISSUE THREAD

**Issue by jannismain** [squidfunk/mkdocs-material#3123]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [ ] ... there are no open or closed issues that are related to my idea

### Description

Related to: #1732, #2727 

As outlined in #2727, mkdocs material reads the system preference regarding palette (light, dark) once and then persists it.

This means that when switching system color mode (e.g. automatically done in macOS if configured), mkdocs won't update accordingly.

I would like for my documentation to offer multiple palettes (e.g. light, dark) but still respect the current system preference.

## Implementation

I have seen an implementation of this in [pymdown-extensions](https://facelessuser.github.io/pymdown-extensions/) by @facelessuser that requires overriding the header and adding a custom theme toggle + custom javascript. I think this functionality is really nice and users would benefit from having it available without adding custom html and javascript.

Maybe a syntax similar to the following could be used here:

```yml
palette:
    - media: "(prefers-color-scheme: light)"
      scheme: light
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to system preference
    - media: "(prefers-color-scheme: auto)"
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
```

The last toggle would be a special instance that would not actually change the palette but remove the scheme preference from local storage and add an observer to react to an update in `prefers-color-scheme`  ([implemented here](https://github.com/facelessuser/pymdown-extensions/blob/9117b29e31bd52c32dc4437837b20db531a9bee9/docs/src/js/material-extra-theme.js))

### Use Cases

Documentation readers who want to automatically have their system match the current time of day (e.g. switching between day and night mode) would benefit from mkdocs-material based documentations being able to reflect this preference and not assume a static preference (always light / always dark).

Documentation writers would benefit from significantly easier configuration of this behavior.

### Screenshots / Mockups

![2021-10-18 5 09 15 PM](https://user-images.githubusercontent.com/14290527/137758800-56d257fe-7d73-4d1e-84bb-b76bf4c99ed5.gif)

**Comment by squidfunk** [comment]
Thank for suggesting. The current solution uses media queries to test for the color scheme to activate. This means that not only `prefers-color-scheme` can be used, but queries such as `prefers-contrast` or `prefers-reduced-motion` to account for other preferences than color scheme only, e.g. in order to aid visually impaired users.

The solution you proposed uses an invalid value for `prefers-color-scheme`, which we would need to handle separately. That doesn't look like a good idea to me. I understand the wish for automatic adaptation to system preferences, but until now, I couldn't come up with a way that we don't make configuration more complex and still support all cases I just mentioned.

**Comment by jannismain** [comment]
I understand that more than light and dark palettes are supported and media queries doesn't allow to specify to match system preferences yet.
I'm also not convinced that using an invalid value for `prefers-color-scheme` is the best option. Just the first one that came to mind that is most compatible with the current way of configuring this.

But, without a media query for "auto" and in keeping with the current way of configuring it, what don't you like about a "special" case for the palette configuration list that will prioritize system preference over currently used palette (and listen for updates).

I'm sure there is a better syntax for defining that special case. Or are you against any sort of special case for the palette media query config?

**Comment by squidfunk** [comment]
We could certainly change the syntax in `mkdocs.yml`, as long as the current capabilities are retained. However, I'm not for adding special cases for the `media` property, because I don't want to pull in a media query parser for this to handle those.

If you'd like to take this on and spec this out, we can collaborate on this. Maybe reworking the syntax is the key here.

**Comment by jannismain** [comment]
Replacing the existing system with something that allows to cleanly support this use case while retaining existing functionality seems like something above my current skill level...

I'm currently trying to adapt the above-linked implementation in the pymdownx docs to work together with the mkdocs material palette toggle (so there is now need to override the header template). It looks rather hacky but solves my use case with minimal effort (for now). I will share once it's done, so that there is a workaround available for anyone interested in the feature.

**Comment by jannismain** [comment]
I have published my customization [here](https://github.com/jannismain/mkdocs-system-preference-theme-toggle). As already said, my web dev skills are rather limited, so I would appreciate any feedback to make it better, until there is official support for this kind of behavior :-)

**Comment by jrappen** [comment]
### 1. Initial set up

We want the ability to initially set color schemes according to the media query result for `prefers-color-scheme`.

This works and is implemented as expected by the user.

### 2. "automatic switch"

We want the ability to switch color schemes when the system mode changes (and media query results such as `prefers-color-scheme` change accordingly).

This is neither implemented nor works as expected by the user (developer using this theme).

The problem here is, it's implied to work but doesn't as seen in #2727.

### 3. "manual override"

The ability to set a color scheme (overriding the media query result from `prefers-color-scheme`).

This works and is implemented as expected by the user.

---

Problems seem to arrise for people like @facelessuser, @posita in #2727, @jannismain and me in #3244 because:

- the `palette` setting is an array (a list)
- and `media` settings for palette entries are ignored after first entry to a site (i.e. not watched live).

I feel like it should've rather been something like:

```yaml
  palette:
    auto:
      light:
        scheme: ...
        primary: ...
        accent: ...
        toggle:
          icon: ...
          name: ...
      dark:
        scheme: ...
        primary: ...
        accent: ...
        toggle:
          icon: ...
          name: ...
    additional_options:
      - scheme: ...
        primary: ...
        accent: ...
        toggle:
          icon: ...
          name: ...
      - scheme: ...
        primary: ...
        accent: ...
        toggle:
          icon: ...
          name: ...
      - ...
      - ...
```

where `auto` is the mandatory default, `additional_options` is optional, and (end) users have an experience as in the solutions linked above in this issue.
