### ISSUE TITLE
Problem with the new search plugin when I use content tabs

### ISSUE THREAD

**Issue by odysseus1973** [squidfunk/mkdocs-material#3147]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When I use content tabs I have a problem with new search plugin (insiders version)

### Expected behaviour

<img width="620" alt="Screenshot 2021-10-26 141244" src="https://user-images.githubusercontent.com/7000262/138866768-9e14a492-cfc6-446b-b063-2c8078b3d456.png">

### Actual behaviour

<img width="618" alt="Screenshot 2021-10-26 140956_1" src="https://user-images.githubusercontent.com/7000262/138866565-fb90d836-b0e6-4d0b-8f5d-8a4f057f5aab.png">

### Steps to reproduce

1. create new docs with mkdocs material theme and mkdocs.yml from Configuration section
2. paste this code

```
=== "HTTP"

    ``` http
    POST /connect/token HTTP/1.1
    Host: sso.asna.cloud:5000
    Content-Type: application/x-www-form-urlencoded
    Cache-Control: no-cache

    client_id=E45D3491-79EE-4EEA-92B2-22CEBE4BB8B5&client_secret=1234567&grant_type=client_credentials
    ```
=== "C# (RestSharp)"

    ``` csharp
    var client = new RestClient("https://sso.asna.cloud:5000/connect/token");
    client.Timeout = -1;
    var request = new RestRequest(Method.POST);
    request.AddHeader("Content-Type", "application/x-www-form-urlencoded");
    request.AddParameter("client_id", "E45D3491-79EE-4EEA-92B2-22CEBE4BB8B5");
    request.AddParameter("client_secret", "1234567");
    request.AddParameter("grant_type", "client_credentials");
    IRestResponse response = client.Execute(request);
    Console.WriteLine(response.Content);
    ```
=== "CURL"

    ``` bash
    curl --location --request POST 'https://sso.asna.cloud:5000/connect/token' --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'client_id=E45D3491-79EE-4EEA-92B2-22CEBE4BB8B5' --data-urlencode 'client_secret=1234567' --data-urlencode 'grant_type=client_credentials'
    ```
```

3. run command: mkdocs serve
4. try to search "http"


### Package versions

- Python: 3.8.10
- MkDocs: 1.2.3
- Material: 7.3.4+insiders.3.1.4

### Configuration

```yaml
site_name: TEST
nav:
  - Старт: index.md
theme:
  name: material
  language: ru
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
    - content.tabs.link
    - navigation.top  
  font:
      text: Roboto
      code: Roboto Mono
markdown_extensions:
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tabbed:
       alternate_style: true 
  - pymdownx.tilde
  - pymdownx.snippets
plugins:
  - search:
      lang:
        - en
        - ru
  - autolinks
  - section-index
```

### System information

- Operating system: Windows 11
- Browser: Chrome
