### ISSUE TITLE
Integrate clipboard.js for docs

### ISSUE THREAD

**Issue by coliff** [squidfunk/mkdocs-material#315]
Feature request: Integrate clipboard.js for docs - maybe as an optional plugin?
https://clipboardjs.com/

**Comment by squidfunk** [comment]
Are you speaking of integration for the code sections or what in particular?

**Comment by coliff** [comment]
Yes, for code sections (sorry I didn't make that clearer)

**Comment by facelessuser** [comment]
This seems like something that could be done with some custom JavaScript without requiring Material to include this.  I feel like you could just have some JS that targets the code blocks, adds a unique id, and then injects a clipboard button linked to the that unique id.

Having it built-in is fine though if that is the direction that is wanted, but I feel like you could get that functionality now without Material having to intervene.  That's just the impression I get from reading `cliboard.js`'s documentation.  I haven't tried it yet.

**Comment by facelessuser** [comment]
This is just a real quick proof of concept.  This is hunting for code highlighted under `<div class="codehilite"><pre>`.

Some CSS:

```css
.md-typeset div.codehilite {
  position: relative;
  overflow: visible;
  padding: 0;
}
.md-typeset div.codehilite pre{
  overflow-x: auto;
  display: block;
  padding: 1rem 1.2rem .8rem;
}
.md-typeset .btn {
  float: right;
  display: inline-block;
  position: absolute;
  top: 3px;
  right: 3px;
  opacity: 0;
  transition: opacity 0.3s ease-in-out;
  background-color: #eee;
  background-image: linear-gradient(#fcfcfc,#eee);
  border: 1px solid #d5d5d5;
  border-radius: 3px;
  padding: 6px 12px;
  cursor: pointer;
}
.md-typeset .btn:hover {
  opacity: 1;
  transition: opacity 0.3s ease-in-out;
}
```

Some JavaScript to convert these code blocks into clipboard ready blocks. `doc_theme/extra.js`.

```js
(function (document) {
    function clipboard_init() {
        var charts = document.querySelectorAll("div.codehilite"),
            arr = [],
            i, j, maxItem, pre, btn, el;

        // Make sure we are dealing with an array
        for(i = 0, maxItem = charts.length; i < maxItem; i++) arr.push(charts[i]);

        // Find the UML source element and get the text
        for (i = 0, maxItem = arr.length; i < maxItem; i++) {
            el = arr[i];
            pre = el.childNodes[0];

            pre.id = "hl_code" + i.toString();
            btn = document.createElement('button');
            btn.appendChild(document.createTextNode('copy'));
            btn.setAttribute("class", "btn");
            btn.setAttribute("data-clipboard-target", "#hl_code" + i.toString());
            el.insertBefore(btn, pre);
        }
        new Clipboard('.btn');
    };

    function onReady(fn) {
        if (document.addEventListener) {
            document.addEventListener('DOMContentLoaded', fn);
        } else {
            document.attachEvent('onreadystatechange', function() {
                if (document.readyState === 'interactive')
                    fn();
            });
        }
    }

    onReady(function(){
        clipboard_init();
    });
})(document);
```

Add following to `mkdocs.yml`.

```yml
theme_dir: doc_theme
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.6.0/clipboard.min.js
  - extra.js
```

![clip](https://cloud.githubusercontent.com/assets/1055125/25830699/ccbf7c78-341b-11e7-95b7-10934703a462.gif)
