### ISSUE TITLE
Table header color is missing

### ISSUE THREAD

**Issue by jrichardsz** [squidfunk/mkdocs-material#3157]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Header of tables has white color that is almost the same as rows in 7.3.4 version. Prior version 7.1.3 was fine.
 

### Expected behaviour

table looks like table in version: mkdocs-material==7.1.3

![image](https://user-images.githubusercontent.com/3322836/139096372-cab6f076-b4f3-4a4c-aca5-043093a11aef.png)

mkdocs theme

![image](https://user-images.githubusercontent.com/3322836/139098984-a7084cc0-1c68-4815-97dd-d7008a7f5343.png)

readthedocs theme

![image](https://user-images.githubusercontent.com/3322836/139098893-2c7be87b-4920-418c-b69e-2518c67c0e7a.png)

### Actual behaviour

table don't looks like table in latest version: mkdocs-material==7.3.4

![image](https://user-images.githubusercontent.com/3322836/139096864-4fdd740b-1d74-448f-9271-9595dfbe05c9.png)

mkdocs theme (ok)

![image](https://user-images.githubusercontent.com/3322836/139098118-3e167244-701f-4f70-83f6-e0ff16a03b5e.png)

readthedocs theme (ok)

![image](https://user-images.githubusercontent.com/3322836/139098239-d85950be-a0d6-47ce-a221-88ac1e6764b9.png)

### Steps to reproduce

1. clone this template https://github.com/jrichardsz-software-architect-tools/mkdocs-template
2. Add this markdown on any file:
```
|app | user type | option code | option name |
|:------|:-------|:-------|:-------|
| student-web | teacher | OP-103 | Get latest students |
 ```
3. Just run
```
pip install -r requirements.txt
mkdocs serve --dev-addr=0.0.0.0:8000
```

### Package versions

- Python: Python 3.10.0
- MkDocs: mkdocs, version 1.2.3 from /usr/local/lib/python3.10/site-packages/mkdocs (Python 3.10)
- Material: Version: 7.3.4

### Configuration

```yaml
site_name: Self Service Docs
site_description: 'A Login option for MkDocs Material'
site_author: 'JRichardsz'
repo_url: 'https://github.com/jrichardsz-software-architect-tools/mkdocs-template'
nav:
    - Home: index.md
    - Template-es:
      - Manual de Usuario: template-es/Manual-de-Usuario.md
theme:
  name: 'material'
  language: 'es'
  palette:
    primary: 'Teal'
    accent: 'Indigo'
  features:
    # - toc.integrate

# extra_css:
#   - 'assets/css/prism.css'
# extra_javascript:
#   - assets/js/prism.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/giansalex

markdown_extensions:
  - admonition
  - codehilite:
      css_class: code
      use_pygments: false
      guess_lang: false
  - toc:
      permalink: true
```

### System information

- Operating system: ubuntu + docker + python 3
- Browser: firefox & chrome
