### ISSUE TITLE
AttributeError: 'LiveReloadServer' object has no attribute 'watcher'

### ISSUE THREAD

**Issue by AninditaBasu** [squidfunk/mkdocs-material#3162]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

Today, I upgraded `mkdocs` and `mkdocs-material` by running the `pip upgrade` commands. Thereafter, on running `mkdocs serve`, I get this error:

`AttributeError: 'LiveReloadServer' object has no attribute 'watcher'`

On investigation, I found this issue: https://github.com/mkdocs/mkdocs/issues/2448. I've tried downgrading the upgrades, but I still get the same error.

### Expected behaviour

I'd expect the server to be loaded at http://127.0.0.1:8000/

### Actual behaviour

The error message that I get is this:

`INFO     -  Documentation built in 19.50 seconds
←[32m[macros] We will also watch: []←[0m
Traceback (most recent call last):
  File "c:\users\anindita\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\anindita\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Anindita\AppData\Local\Programs\Python\Python38-32\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "c:\users\anindita\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\anindita\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\anindita\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\anindita\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\anindita\appdata\local\programs\python\python38-32\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\anindita\appdata\local\programs\python\python38-32\lib\site-packages\mkdocs\__main__.py", line 173, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, **kwargs)
  File "c:\users\anindita\appdata\local\programs\python\python38-32\lib\site-packages\mkdocs\commands\serve.py", line 78, in serve
    server = config['plugins'].run_event('serve', server, config=config, builder=builder)
  File "c:\users\anindita\appdata\local\programs\python\python38-32\lib\site-packages\mkdocs\plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "c:\users\anindita\appdata\local\programs\python\python38-32\lib\site-packages\macros\plugin.py", line 400, in on_serve
    builder = list(server.watcher._tasks.values())[0]["func"]
AttributeError: 'LiveReloadServer' object has no attribute 'watcher'`

### Steps to reproduce

1.  Run `mkdocs serve`

### Package versions

- Python: 3.8.5
- MkDocs: 1.2
- Material: 7.2.2

### Configuration

```yaml
site_name: Vymo Documentation (internal)
site_description: See how to configure and use the Vymo app
copyright: '&copy; 2020 - 2021 Vymo, Inc. All rights reserved.'

docs_dir: docs

nav:
- Home: 'index.md'
- Another: 'blah.md'

theme:
    name: material
    language: en
    favicon: assets/images/Vymo favicon-01.png
    custom_dir: overrides

markdown_extensions:
  - meta
  - admonition
  - def_list
  - toc:
      title: On this page
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
```

### System information

- Operating system: Windows
- Browser: Edge
