### ISSUE TITLE
optional color option for `extra.social` links in footer

### ISSUE THREAD

**Issue by jrappen** [squidfunk/mkdocs-material#3206]
### Description

I want to assign an **optional** color styling to the `extra.social` links in the footer.

### Use Cases

```yaml
extra:
  social:

    - icon: fontawesome/brands/github
      link: https://github.com/{user}

    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/{user}
      color: '#fca121'
```

**Comment by squidfunk** [comment]
Thanks for suggesting. You can use additional CSS to achieve the same thing:

`mkdocs.yml`

``` yaml
extra:
  social:
    - link: https://twitter.com/squidfunk
      name: Twitter
      icon: fontawesome/brands/twitter
```

`custom.css`

``` css
html .md-footer-social a[title="Twitter"] {
  color: #00acee;
}
```

**Comment by jrappen** [comment]
#### `mkdocs-material` v8.0 and later

`custom.css`

```css
html a[title="Twitter"].md-social__link svg {
    color: #00acee;
}
```
