### ISSUE TITLE
i cant deploy

### ISSUE THREAD

**Issue by pherngpy** [squidfunk/mkdocs-material#3217]
### Contribution guidelines

- [x] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [ ] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

![Screenshot_20211113_083621](https://user-images.githubusercontent.com/77534483/141598809-75a59750-eaba-40be-aba3-f158356b8a6d.JPG)

### Expected behaviour

![Screenshot_20211113_083621](https://user-images.githubusercontent.com/77534483/141598851-492dd20d-6337-458d-90d1-aca95019e9c3.JPG)

### Actual behaviour

![Screenshot_20211113_083621](https://user-images.githubusercontent.com/77534483/141598804-c2a8e9bd-0fe4-480e-bfc6-7caf94dc953f.JPG)

### Steps to reproduce

![Screenshot_20211113_083621](https://user-images.githubusercontent.com/77534483/141598794-a6cf0111-ace2-46f8-90d3-f55db9035f03.JPG)

### Package versions

all lastest

### Configuration

```yaml
site_name: Docs
site_url: https://example.com/
nav:
    - Home: index.md
    - About: about.md
theme: material
features:
    - search.suggest
    - search.highlight
    - search.share
```

### System information

- Operating system: Github
