### ISSUE TITLE
Edge: Crazy background leak

### ISSUE THREAD

**Issue by facelessuser** [squidfunk/mkdocs-material#322]
## Description

I don't use Edge, but when looking to verify general functionality for pull request proposal, I noticed that the Material theme has background leakage everywhere.  Now I will preface this with, I hate IE and Edge and think it is most likely their fault, but nevertheless, a workaround should probably be applied.

![2017-05-12 09_40_09-d __musei-opt990 z_ - clover](https://cloud.githubusercontent.com/assets/1055125/26005844/9352dfb4-36f7-11e7-9ec7-1cf2d8f497d2.png)

Almost any element's background turns orange on hover.

### Expected behavior

Orange should not be bleeding through every background.

### Actual behavior

Every background turns orange on hover.

### Steps to reproduce the bug

1. Check out current current Material Documentation in Edge.  Though I am not sure if this is version specific, and my work computer is kind of locked down on updates.  I only get updates when they push them through IT.

### Package versions

* Python: Any
* MkDocs: Any
* Material: 1.6.1

### System information

* OS: Windows 10
* Browser: Microsoft Edge 25.10586.672.0
Microsoft EdgeHTML 13.10586.

**Comment by facelessuser** [comment]
Seems related to #154.  I will try to work out more specifics.

**Comment by facelessuser** [comment]
I'll let you decide whether to keep this open.  Edge is terrible.  Its not just the background.  Maybe the recent Edge isn't bad, I can't tell as work locks me down from updates on my Windows 10 machine so they can use an outdated anti-virus.  I would assume with results this bad more people would be complaining...or maybe no one is using Edge :slightly_smiling_face:.

I personally will never use Edge.

**Comment by mtik00** [comment]
FWIW, this does not appear to be an issue with the latest Edge browser.
![image](https://cloud.githubusercontent.com/assets/1509355/26026692/67c5082e-37bd-11e7-9c97-58b2f298ef44.png)

**Comment by facelessuser** [comment]
Perfect, that's all I needed to have confirmed.  I had a feeling I was locked down to an old version.  I wish our IT would get their stuff together.

**Comment by squidfunk** [comment]
Can you check the Edge version so I can reproduce it? Probably 13?

**Comment by facelessuser** [comment]
We both posted or edge versions.  Mine was Edge HTML 13. It's in the opening post.

**Comment by squidfunk** [comment]
Ah sorry, my fault!

**Comment by squidfunk** [comment]
I can reproduce it with Edge 13, but I have no f**kin' clue what is causing the issue. I cannot find anything related to this on the Internet - do you have a reference? Otherwise I currently have no idea how to fix this.

Edge is an evergreen browser, so Edge 13 should be no big deal for most users, but it would be great to solve the problem to serve users that are locked to older versions. However, no idea at the moment.

**Comment by facelessuser** [comment]
Maybe the solution is to use Edge 14 :smile:.  Things looked so bad I started figuring it was a lost cause.  From what I researched about Edge, or at least people's impressions of edge, is that it is a work in progress. There seems to be a general understanding with people that it renders some websites terribly.  Though I imagine recent iterations seem to be getting better as 14 looks much better.

**Comment by squidfunk** [comment]
Okay, so I will close this issue for now and mark is as not-fixable. If someone comes up with an idea what the problem is, I'm happy to include a fix.

**Comment by makshh** [comment]
```css
[data-md-color-accent=yellow] .md-sidebar__scrollwrap::-webkit-scrollbar-thumb:hover {
    background-color: #ffd600
}
```

This kind of styles causes this behavior in Edge 13.

**Comment by squidfunk** [comment]
Ah thanks for the note. How did you isolate this?

**Comment by makshh** [comment]
I marked :hover state on body in Edge dev tools.

**Comment by squidfunk** [comment]
Great, thank you. I will look into it. Strange that Edge interprets this rule.

**Comment by squidfunk** [comment]
Out of this selector:

``` css
[data-md-color-accent="deep-orange"] .md-sidebar__scrollwrap::-webkit-scrollbar-thumb:hover {}
```

Edge parses this:

``` css
:hover {}
```

This is why every element is turning orange on hover - deep orange is the last color defined in the file `application.palette.css`, so it actually makes sense, but Edge parsing this in such a strange way makes no sense. I have no idea how to fix this and I can only emulate Edge through SauceLabs which makes debugging a real pain.

I'm happy to include a fix if somebody can manage to fix the parsing bug, I don't how to mitigate this at the moment.

Quickfix: do not define the colors in `mkdocs.yml`, then `application.palette.css` will not get included. However, Edge also suffers from some layout bugs but probably not worth pursuing.

**Comment by makshh** [comment]
```css
[data-md-color-accent=deep-orange] .md-typeset .codehilite::-webkit-scrollbar-thumb:hover,
[data-md-color-accent=deep-orange] .md-typeset pre::-webkit-scrollbar-thumb:hover {
    background-color: #ff6e40
}
[data-md-color-accent=deep-orange] .md-search__scrollwrap::-webkit-scrollbar-thumb:hover {
    background-color: #ff6e40
}
[data-md-color-accent=deep-orange] .md-sidebar__scrollwrap::-webkit-scrollbar-thumb:hover {
    background-color: #ff6e40
}
```

I think only last two selector are applied as `:hover {}`. Maybe try to add some selector before scrollbar?

```css
[data-md-color-accent=deep-orange] .md-search .md-search__scrollwrap::-webkit-scrollbar-thumb:hover {
    background-color: #ff6e40
}
[data-md-color-accent=deep-orange] .md-sidebar .md-sidebar__scrollwrap::-webkit-scrollbar-thumb:hover {
    background-color: #ff6e40
}

```

**Comment by squidfunk** [comment]
Well, as I said, I'm currently not able to debug it efficiently. If someone could do it, I would be happy to validate and merge.

**Comment by makshh** [comment]
Yeah, I'm also limited, I'm using VirtualBox/Win10 on my Mac and it's not easy to debug here.

**Comment by squidfunk** [comment]
I would like to debug it using VirtualBox, but Microsoft doesn't provide Edge 13 anymore :-/

**Comment by makshh** [comment]
Ok, I checked my "fix" and it doesn't work. (I have Edge 12)

**Comment by makshh** [comment]
But... It worked when I combined two separate selectors into one... strange...

```css
[data-md-color-accent=deep-orange] .md-sidebar__scrollwrap::-webkit-scrollbar-thumb:hover,
[data-md-color-accent=deep-orange] .md-search__scrollwrap::-webkit-scrollbar-thumb:hover {
    background-color: #ff6e40
}
```

After combining them, I don't see `:hover {}` in dev tools anymore.

**Comment by squidfunk** [comment]
Hmm okay, good to know, thanks for investigating. Seems some bug with the parser. However, this will blow up the palettes CSS. I will keep this in mind when looking into Edge 13, because there are several more issues with the layout.

**Comment by makshh** [comment]
Yes, this is my screenshot from Edge 12 FYI:

![screenshot at may 16 22-05-09](https://cloud.githubusercontent.com/assets/5025950/26125881/d218599c-3a83-11e7-8502-7dec1e2eb9b0.png)

**Comment by squidfunk** [comment]
Thanks. IE9-11 doesn't know the `main` tag, could be related to that, but I though Edge was different.

**Comment by makshh** [comment]
It's something different.

Somehow in Edge these styles are not applied:

```css
@media only screen and (min-width: 76.25em) {
  .md-content {
    margin-left: 24.2rem;
  }
}
```

```css
@media only screen and (min-width: 76.25em) {
  .md-sidebar--secondary {
    margin-left: 122rem;
  }
}
```
