### ISSUE TITLE
Automatic switch of dark mode / light mode

### ISSUE THREAD

**Issue by jrappen** [squidfunk/mkdocs-material#3244]
### Description

With this config:

```yaml
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark-mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/theme-light-dark
        name: Switch to light-mode
```

or this config:

```yaml
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: indigo
      # toggle:
      #   icon: material/theme-light-dark
      #   name: Switch to dark-mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: red
      accent: red
      # toggle:
      #   icon: material/theme-light-dark
      #   name: Switch to light-mode
```

...

### Expected behaviour

... I would have assumed that MkDocs Material:

- [x] applies the color scheme for dark or light mode according to the system
- [ ] switches back and forth following the system when it changes

### Actual behaviour

... but it doesn't switch after the initial set up when changing the color scheme of the sytem.

### Package versions

- Python: `3.9.8`
- MkDocs: `1.2.3`
- MkDocs Material: `7.3.6`
