### ISSUE TITLE
Protocol relative font link doesn't work with file protocol

### ISSUE THREAD

**Issue by DenisKolodin** [squidfunk/mkdocs-material#33]
Fonts don't loads when `site\index.html` opens locally. That's because relative protocol link usesd in [base.html](https://github.com/squidfunk/mkdocs-material/blob/master/src/base.html#L101) and there is no `file://fonts.googleapis.com/...` data exists.

How about to use `https` explicitly?

**Comment by squidfunk** [comment]
We could do that, sounds reasonable. But, how did you manage to serve it locally anyway? This shouldn't be a problem at all.

**Comment by DenisKolodin** [comment]
I've put documentation with desktop application and want to add os-link to `index.html`, but when user opens local file fonts don't load.

I've found appropriate solution: use system fonts by additional stylesheets:

```css
body, input {
   font-family: 'Segoe UI', Helvetica, Arial, sans-serif;
}
pre, code {
   font-family: 'Consolas', 'Courier New', 'Courier', monospace;
}
```

It works ok and I think It's also better, because external fonts can be unavailable and unwanted for desktop (offline) applications.
