### ISSUE TITLE
Error: The "tags" plugin is not installed

### ISSUE THREAD

**Issue by dgoosens** [squidfunk/mkdocs-material#3322]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

running in Docker with latest `squidfunk/mkdocs-material` image and insider `material` theme  
suddenly getting an error inidicating the tags plugin is not installed  
am using the built in plugin, which is available in the theme `material/plugins/tags`

### Expected behaviour

no additional plugin should be installed

### Actual behaviour

```bash
INFO     -  Building documentation...
ERROR    -  Config value: 'plugins'. Error: The "tags" plugin is not installed
Aborted with 1 Configuration Errors!
```

### Steps to reproduce

Dockerfile:

```
FROM squidfunk/mkdocs-material
RUN pip install mkdocs-git-revision-date-plugin \
	&& pip install mkdocs-minify-plugin
```

process:
```bash
docker pull squidfunk/mkdocs-material`
docker build -t squidfunk/mkdocs-material .
docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material
```

### Package versions

- Python: see squidfunk/mkdocs-material
- MkDocs: latest

### Configuration

```yaml
site_name: AE Doc
site_description: This is wherer we centralize our documentation
site_author: author
site_dir: public

copyright: Copyright &copy; 2016

repo_name: ae-doc
repo_url: https://gitlab.com/...
edit_uri: https://gitlab.com/...

theme:
  name: material
  custom_dir: overrides

  logo: ../../../assets/images/logo.svg

  font:
    text: Lato
    code: Roboto Mono

  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  features:
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share
    - navigation.top
    - content.code.annotate
    - toc.integrate
    # - navigation.instant
    # - navigation.sections

  palette: 
    - scheme: ae
      primary: ae
      accent: ae
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search:
      separator: "[\\s\\-,:!=\\[\\]()\"/]+|\\.(?!\\d)|&[lg]t;|(?!\\b)(?=[A-Z][a-z])"
  - git-revision-date
  - minify:
      minify_html: true
  - tags:
      tags_file: tags.md

extra:
  generator: false

markdown_extensions:
  - admonition
  - footnotes
  - meta
  - attr_list
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  # - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  # - tables

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
```

### System information

Docker
