### ISSUE TITLE
Search in new version 8.0.x not working

### ISSUE THREAD

**Issue by ladisone** [squidfunk/mkdocs-material#3324]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

If I write to the search form no results are displayed.

### Expected behaviour

Show results as you type in the search form.

### Actual behaviour

If I write to the search form no results are displayed.

### Steps to reproduce

Write to the search form.

### Package versions

- Python: 3.9.7 
- MkDocs: 1.2.3
- Material: 8.0.5

### Configuration

```yaml
theme:
  name: 'material'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
    - abbr
    - admonition
    - codehilite
    - attr_list
    - def_list
    - pymdownx.details:
    - pymdownx.magiclink:
    - pymdownx.mark:
    - pymdownx.superfences:
    - pymdownx.inlinehilite:
    - pymdownx.tasklist:
        clickable_checkbox: True
        custom_checkbox: True
    - pymdownx.snippets:
    - pymdownx.tabbed:
    - pymdownx.keys:
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
```

### System information

- Operating system: Fedora release 34 (Thirty Four)
- Browser: Chrome Version 96.0.4664.45 (Official Build) (64-bit)
