### ISSUE TITLE
Search and menu scroll broken when using pymdownx.tabbed content

### ISSUE THREAD

**Issue by svenhofstede** [squidfunk/mkdocs-material#3327]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When using `pymdownx.tabbed` content, an javascript error is thrown after version `8.0.0` onwards

Related issue is #3324 but I'm providing steps to reproduce here.

### Expected behaviour

Search should work. Scrolling menu on the left should work

### Actual behaviour

- Clicking on search or typing does not result in search results popdown. 
- Menu bar on left losing ability to scroll
- Javascript error in console

```
index.ts:77 Uncaught ReferenceError: Missing element: expected ".tabbed-labels" to be present
    at z (index.ts:77)
    at $o (index.ts:97)
    at index.ts:98
    at Array.map (<anonymous>)
    at Po (index.ts:98)
    at bundle.ts:202
    at Array.map (<anonymous>)
    at bundle.ts:202
    at e._subscribe (defer.ts:53)
    at e._trySubscribe (Observable.ts:244)
```

### Steps to reproduce

`mkdocs.yaml`

```yaml
site_name: example
theme:
  name: material
plugins:
  - search
nav:
  - example: example.md
markdown_extensions:
  - pymdownx.tabbed
```

`docs/example.md`

```
=== "Some block one"

    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.
    
=== "Some other block"

    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.
```

✅ 
```
docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material:7.3.6
```

🔴 
```
docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material:8.0.0
```

### Package versions

- Python: `Python 3.9.2`
- MkDocs: `1.2.3`
- Material: `8.0.0`

### Configuration

```yaml
site_name: example
theme:
  name: material
plugins:
  - search
nav:
  - example: example.md
markdown_extensions:
  - pymdownx.tabbed
```

### System information

- Operating system: Tested on Mac OS and Windows
- Browser: Tested on Chrome, Safari, Edge
