### ISSUE TITLE
Abbreviation's not working?

### ISSUE THREAD

**Issue by ianderrington** [squidfunk/mkdocs-material#3352]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Following the guidelines [here](https://squidfunk.github.io/mkdocs-material/reference/abbreviations/#configuration) 
Produces only an underlined text and a '?' that the curser changes to when rolling over. 

### Expected behaviour

Rolling over a definition should produce an expand definition, not just a '?'. 

### Actual behaviour

As found on this self-same [rendered website](https://squidfunk.github.io/mkdocs-material/reference/abbreviations/#configuration) the defined terms only produce a '?' when cursoring over them. 

### Steps to reproduce

Follow the instructions [here](https://squidfunk.github.io/mkdocs-material/reference/abbreviations/#configuration) that render that website. I also find it locally bugging out.  

### Package versions

- Python: 3.9
- MkDocs: 1.2.3
- Material: 8.1.1

### Configuration

```yaml
# Project information
site_name:  test
site_url: https://website
site_author: Ian Derrington
site_description: >-
 stuff

# Repository
repo_name: repo-name
repo_url: "https://repo_url"
edit_uri: ""

# Copyright
copyright: Copyright &copy; None

# Configuration
theme:
  name: material

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - include_dir_to_nav
  - include-markdown
  - awesome-pages
  - tags
  - section-index
  - table-reader:
      data_path: "docs"




# Extensions
markdown_extensions:
  - admonition
  - abbr
  - pymdownx.snippets

  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  #- pymdownx.emoji:
      #emoji_index: !!python/name:materialx.emoji.twemoji
      #emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          #format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
```

### System information

- Operating system: OS-X
- Browser: Chrome Version 96.0.4664.93 (Official Build) (x86_64)
