### ISSUE TITLE
Section index pages seems not work

### ISSUE THREAD

**Issue by aborruso** [squidfunk/mkdocs-material#3361]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I have set these features [here](https://github.com/ondata/guidaPraticaPubblicazioneCSV/blob/main/mkdocs.yml#L33-L40):

```
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - search.share
    - search.suggest
    - navigation.tracking
 ```

And this is [my navigation](https://github.com/ondata/guidaPraticaPubblicazioneCSV/blob/main/mkdocs.yml#L47-L57):

```
nav:
    - Home: README.md
    - Guida:
      - Introduzione: introduzione/README.md
      - Formato di dati tabellari: formato_dati_tabellari/README.md
      - Dizionario: dizionario_dati/README.md
      - Linee guida pubblicazione:
          - linee_guida_pubblicazione_file/index.md
          - Singola riga intestazione: linee_guida_pubblicazione_file/P01_unica_riga_intestazione.md
    - Partecipa: partecipa.md
    - Note: note_redazione.md
```

Why `Linee guida pubblicazione` is not linked to the section index file, and I have the index file below the section name in the tree?

![image](https://user-images.githubusercontent.com/30607/146643377-0d88cfbc-7fa6-4c54-9525-0a07561fbbb3.png)

### Expected behaviour

To have the section in tree linked to index file

### Actual behaviour

The section is not linked to the index file

### Steps to reproduce

I have inserted all my source file.

This is the repo https://github.com/ondata/guidaPraticaPubblicazioneCSV

### Package versions

- Python: `python --version` 3.9.2
- MkDocs: `mkdocs --version` 1.2.3
- Material: `pip show mkdocs-material | grep -E ^Version` 8.1.0

### Configuration

```yaml
site_name: Guida per la pubblicazione di CSV
site_url:  https://ondata.github.io/guidaPraticaPubblicazioneCSV/
site_description: Guida pratica per la pubblicazione di dati tabellari in formato CSV


repo_url: https://github.com/ondata/guidaPraticaPubblicazioneCSV
repo_name: guidaPubblicazioneCSV
edit_uri: edit/main/docs/

copyright: 'Questa guida è un progetto dell''<a href="https://twitter.com/ondatait" target="_blank">associazione onData</a> | licenza <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.it" target="_blank">CC BY-SA 4.0</a>'

theme:
  name: material
  icon:
    logo: material/table
  highlightjs: true
  custom_dir: overrides
  favicon: imgs/favicon.ico
  palette:
    - scheme: preference
      primary: deep purple
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  language: it
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - search.share
    - search.suggest
    - navigation.tracking
  font:
    text: Montserrat
    #code: Cutive Mono
    code: Fira Code


nav:
    - Home: README.md
    - Guida:
      - Introduzione: introduzione/README.md
      - Formato di dati tabellari: formato_dati_tabellari/README.md
      - Dizionario: dizionario_dati/README.md
      - Linee guida pubblicazione:
          - linee_guida_pubblicazione_file/index.md
          - Singola riga intestazione: linee_guida_pubblicazione_file/P01_unica_riga_intestazione.md
    - Partecipa: partecipa.md
    - Note: note_redazione.md

extra:
 social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ondatait

# foglio di stile personalizzato
extra_css:
  - stylesheets/style.css

plugins:
  - search:
      lang: it
  - mkdocstrings
  - mermaid2

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
  - javascripts/varie.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js

markdown_extensions:
- admonition
- md_in_html
- attr_list
- footnotes
- meta
- mkdocs-click
- pymdownx.keys
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.critic:
      mode: view
- pymdownx.details
- pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.highlight
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
- pymdownx.tabbed
- pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
- pymdownx.tilde
- toc:
      permalink: true
      toc_depth: 3

```
```


### System information

- Operating system:  win10
- Browser: Version 96.0.4664.110 (Official Build) (64-bit)
