### ISSUE TITLE
Mermaid rendering but not appearing within Content Tabs

### ISSUE THREAD

**Issue by mlevit** [squidfunk/mkdocs-material#3377]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Rendered Mermaid diagrams are not appearing within content tabs. As you can see below, the diagram is rendered, but the content tab is not expanding to show the diagram itself:

![image](https://user-images.githubusercontent.com/233717/147177936-f59111af-f115-4f3a-a87d-90e924525a65.png)

### Expected behaviour

Mermaid diagrams are able to be nested within content tabs.

### Actual behaviour

Contents tabs do not resize to the nested Mermaid diagrams.

### Steps to reproduce

1. Create content tab
2. Nest a Mermaid diagram within it

### Package versions

- Python: `3.9.7`
- MkDocs: `1.2.2`
- Material: `8.12`

### Configuration

```yaml
# Project information
site_name: Test

# Configuration
theme:
  name: material
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  icon:
    logo: material/book-open-page-variant
    repo: material/gitlab
docs_dir: docs
site_dir: site
use_directory_urls: true

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

plugins:
  - search:
      separator: '[\s\-\.\_]'

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js

# Page tree
nav:
  index.md
```

### System information

- Operating system: macOS 11.6
- Browser: Chrome 96.0.4664.110
