### ISSUE TITLE
highlight.scss not loading in some browsers (was: Change in syntax highlighting >v7.3.6)

### ISSUE THREAD

**Issue by 2e0byo** [squidfunk/mkdocs-material#3402]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Syntax highlighting appears not to work with versions > 7.3.6 using what I think (doubtless incorrectly) is the correct bare minimum mkdocs.yml.

### Expected behaviour

Code should be syntax highlighted (with pygments) in the output.

### Actual behaviour

With versions <=v7.3.6 highlighting works as expected.  With versions >v7.3.6 it doesn't, and I can't get it running. 

### Steps to reproduce

- create a new empty dir
- create the minimal mkdocs.yml below
- put
  ```js
  a = "78"
  ```
  in `docs/index.md`
- put
  ```toml
  [tool.poetry]
  name = "hl"
  version = "0.1.0"
  description = ""
  authors = ["me"]

  [tool.poetry.dependencies]
  python = "^3.10"
  mkdocs = "^1.2.3"
  mkdocs-material = "v7.3.6"
  ```
  in `pyproject.toml`
- run `poetry install` followed by `mkdocs serve` -> correctly highlighted 
- run `poetry install mkdocs-material=latest` -> no highlighting

### Package versions

- Python: `python --version`: Python 3.10.1
- MkDocs: `mkdocs --version`:  1.2.3
- Material: `pip show mkdocs-material | grep -E ^Version`: 7.3.6 / > 8

### Configuration

```yaml
site_name: Highlight test

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
```

### System information

- Operating system: Arch Linux
- Browser: qutebrowser
