### ISSUE TITLE
Search Highlight Timeout

### ISSUE THREAD

**Issue by Vasperous** [squidfunk/mkdocs-material#3409]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

The current `search.highlight` feature is extremely helpful however in some cases it might be ideal to support for the highlighting of the searched content when the page is loaded and then after X number of seconds removing the highlighting format from the page.  Something like:

``` yaml
- search.highlight:
  - fade: 10000 # milliseconds
```

### Use Cases

In some cases the search function is used to open a page that could be inconvenient to access manually, using the search function to get there quickly is much more efficient.  In this case the user may not want the text they search for to be highlighted.

This is especially true for the use case above when the user is trying to access a search boosted page from a completely different section of the documentation.

**Comment by squidfunk** [comment]
Thanks for suggesting. Search highlighting definitely needs some work and a timeout may be a good idea before I dive into more advanced controls. I'll investigate support as soon as I can allocate some time to do so.

**Comment by Vasperous** [comment]
Thank you and looking forward to what you have in the works!

**Comment by squidfunk** [comment]
I've added the possibility for fading out search highlighting in 07f736687532080ee47292f7bd1874f4834b46e5, but then decided to revert the commit as it is trivial to achieve with custom CSS, which the author would have to provide any way to configure the duration. Add it yourself with:

``` css
@keyframes fade {
  100% {
    background-color: transparent;
  }
}
.md-typeset mark[data-md-highlight] {
  animation: fade 10s forwards; /* Change time to your liking */
}
```

You can also "keep" the highlight and remove it "abruptly" by tuning the keyframes, e.g.:

``` css
@keyframes fade {
  0%, 99% {
    background-color: var(--md-typeset-mark-color);
  }
  100% {
    background-color: transparent;
  }
}
```

For this reason, this can be considered customization for now. I may re-evaluate this as I already wrote when I get to work on improving the search UI/UX one more time, and hope that this works for you.
