### ISSUE TITLE
The codeblock copy button and comments are not shown

### ISSUE THREAD

**Issue by ehguille** [squidfunk/mkdocs-material#3420]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The codeblock copy button and comments are not shown.

### Expected behaviour

There should be an icon to copy the codeblock and the comments should be shown as popups

### Actual behaviour

The icon is missing and the comments don't render as popups

### Steps to reproduce

mkdocs serve (or build).

![image](https://user-images.githubusercontent.com/55703981/148045733-fee3880d-c25c-4f94-97bf-2b6a7378263e.png)

Sorry I can't copy the code.

![image](https://user-images.githubusercontent.com/55703981/148046063-e155bf56-386b-4279-9a68-dfae2b73de27.png)

### Package versions

Python 3.10.0
mkdocs, version 1.2.3
Version: 8.1.4+insiders.4.5.1

### Configuration

```yaml
site_name: Programación

theme:
  name: material
  logo: assets/imgs/logo-programacion.png
  favicon: assets/imgs/logo-programacion.png
#  custom_dir: overrides
  font: false
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: default
    primary: java
    accent: indigo
  language: es
  features:
    - content.code.annotate
    - search.suggest
    - navigation.instant
    - search.highlight
    - header.autohide
    - navigation.tabs 
    - navigation.indexes
    - navigation.tracking
    - announce.dismiss
   
#extra_javascript:
#  - https://kit.fontawesome.com/8c2d521aaf.js
  
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: datetime  

extra:
  generator: false
   consent:
    title: Consentimiento de cookies
    description: > 

      Esta página usa cookies para ver qué apartados resultan más interesantes a los usuarios y así poder ser mejorada. Puedes gestionar el acceso a estas cookies en el siguiente botón.
      
#extra_css:
#    - 'assets/stylesheets/extra.css'

markdown_extensions: 
    - meta
    - attr_list
    - abbr
    - admonition
    - pymdownx.caret
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.smartsymbols
    - pymdownx.tilde
    - pymdownx.inlinehilite
    - pymdownx.mark
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.extra
    - pymdownx.magiclink
    - pymdownx.progressbar
    - pymdownx.tasklist
    - pymdownx.tabbed
    - pymdownx.critic
    - markdown.extensions.footnotes
    - markdown.extensions.tables
    - pymdownx.snippets
    - def_list
    - lightgallery
    - toc:
       toc_depth: 5
    - smarty:
       smart_angled_quotes: true
       smart_dashes: false
    - pymdownx.emoji:
       emoji_index: !!python/name:materialx.emoji.twemoji
       emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.betterem:
       smart_enable: true
    - pymdownx.tasklist:
       custom_checkbox: true
```

### System information

Windows 10 21H2
Firefox and Chrome at least
