### ISSUE TITLE
Support Centering Tables

### ISSUE THREAD

**Issue by johnthagen** [squidfunk/mkdocs-material#3430]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Support a way to center rendered Markdown tables.

### Use Cases

Often times tables do not fill up the entire width of the page, and look awkward when left justified. Images can be aligned using the [`attr_list`](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#attribute-lists) extension and referencing custom CSS. Having a similar solution for tables would allow them to also be centered.

### Screenshots / Mockups

In the following screenshot, support a way for the table to be centered in the page.

<img width="1241" alt="Screen Shot 2022-01-05 at 11 18 45 AM" src="https://user-images.githubusercontent.com/10340167/148251505-9f09aa65-305f-4e56-a739-e44206a1d125.png">

**Comment by johnthagen** [comment]
This worked in my browser, but `<center>` is deprecated:

```md
<center>

|  Method  |   Description   |
|:--------:|:---------------:|
|  `GET`   | Fetch resource  |
|  `PUT`   | Update resource |
| `DELETE` | Delete resource |


</center>
```

https://stackoverflow.com/a/24639508

**Comment by squidfunk** [comment]
I'll consider it customization, so no, not for now, unless several users land on this issue and vote on my answer.

**Comment by lampensau** [comment]
We have customized the existing CSS for `.md-typeset__table` and `table` to always force tables with 100% width. This is definitely not what you're asking for but was a valid solution for us. It saves you wrapping your tables in a custom HTML element.

```yaml
# mkdocs.yml
extra_css: extra-styles.css
```

```css
/* extra-styles.css */
.md-typeset__table {
    display: block;
}
.md-typeset__table table:not([class]) {
    display: table;
}
```

**Comment by johnthagen** [comment]
@squidfunk I tried your example solution above in a minimal Mkdocs Material project, anad the table rendering broke 🤔 .


```yml
site_name: My Docs
strict: true
theme:
  name: material
markdown_extensions:
  - tables
extra_css:
  - stylesheets/extra.css
```

```md
# Welcome to MkDocs

## Heading 1

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et euismod nulla. 
Curabitur feugiat, tortor non consequat finibus, justo purus auctor massa, nec semper lorem quam in
massa.

<div class="center-table" markdown>

|  Method  |   Description   |
|:--------:|:---------------:|
|  `GET`   | Fetch resource  |
|  `PUT`   | Update resource |
| `DELETE` | Delete resource |

</div>

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et euismod nulla. 
Curabitur feugiat, tortor non consequat finibus, justo purus auctor massa, nec semper lorem quam in
massa.

## Heading 2
```

<img width="1240" alt="Screen Shot 2022-01-05 at 1 15 58 PM" src="https://user-images.githubusercontent.com/10340167/148267991-12ea8c2c-6565-4aef-be05-76756e5f41c4.png">

Perhaps I'm missing something?

### Environment

Python 3.9.8

```
pip list
Package                    Version
-------------------------- -------
click                      8.0.3
ghp-import                 2.0.2
importlib-metadata         4.10.0
Jinja2                     3.0.3
Markdown                   3.3.6
MarkupSafe                 2.0.1
mergedeep                  1.3.4
mkdocs                     1.2.3
mkdocs-material            8.1.4
mkdocs-material-extensions 1.0.3
packaging                  21.3
pep517                     0.12.0
pip                        21.3.1
pip-tools                  6.4.0
Pygments                   2.11.1
pymdown-extensions         9.1
pyparsing                  3.0.6
python-dateutil            2.8.2
PyYAML                     6.0
pyyaml_env_tag             0.1
setuptools                 56.0.0
six                        1.16.0
tomli                      2.0.0
watchdog                   2.1.6
wheel                      0.37.1
zipp                       3.7.0
```

**Comment by lampensau** [comment]
you need to have `md_in_html` enabled under your `markdown_extensions`

```yaml
# mkdocs.yml
markdown_extensions:
  - md_in_html
 ```

**Comment by johnthagen** [comment]
For those looking for a fully self-contained solution (Thanks @squidfunk @lampensau):

```yml
site_name: My Docs
strict: true
theme:
  name: material
markdown_extensions:
  - tables
  - md_in_html
extra_css:
  - stylesheets/extra.css
```

```css
.center-table {
  text-align: center;
}
.md-typeset .center-table :is(td,th):not([align]) {
  text-align: initial; /* Reset alignment for table cells */
}
```

```md
# Welcome to MkDocs

## Heading 1

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et euismod nulla. 
Curabitur feugiat, tortor non consequat finibus, justo purus auctor massa, nec semper lorem quam in
massa.

<div class="center-table" markdown>

|  Method  |   Description   |
|:--------:|:---------------:|
|  `GET`   | Fetch resource  |
|  `PUT`   | Update resource |
| `DELETE` | Delete resource |

</div>

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et euismod nulla. 
Curabitur feugiat, tortor non consequat finibus, justo purus auctor massa, nec semper lorem quam in
massa.

## Heading 2
```
