### ISSUE TITLE
Underline does not link when linked content tab is set.

### ISSUE THREAD

**Issue by btbf** [squidfunk/mkdocs-material#3440]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Underline does not link when linked content tab is set.
(The text inside is linked.)

### Expected behaviour

I'd like to see a link to underline as well.

### Actual behaviour

https://user-images.githubusercontent.com/37224549/148435866-844ad419-132c-4c21-86e4-c1bc68a838c3.mp4

### Steps to reproduce

1. Add "- content.tabs.link" to mkdocs.yml

### Package versions

- Python: 3.8.10
- MkDocs: 1.2.3
- Material: 8.1.4+insiders.4.5.1

### Configuration

```yaml
site_name: My Docs
theme:
  language: ja
  font:
    text: Noto Sans Japanese
  name: material
  palette:
    primary: indigo
  features:
    - content.tabs.link
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant




markdown_extensions:
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

extra_javascript:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js


#extra_css:
  - stylesheets/extra.css

nav:
    - Home: '../'
    - 'Pool Setup':
      - '0.はじめに': './pool-setup/start-guide.md'
      - '1.Ubuntu初期設定': './pool-setup/ubuntu-setup.md'
      - '2.ノードセットアップ': './pool-setup/node-setup.md'
```

### System information

- Operating system: Ubuntu 20.04
- Browser: Google Chrome 96.0.4664.110
