### ISSUE TITLE
Vertical size limit for code blocks

### ISSUE THREAD

**Issue by smarie** [squidfunk/mkdocs-material#3444]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

It would be very useful to have an optional `max-nb-lines` property on code blocks allowing to limit the number of lines actually displayed, letting users scroll down if they need to see the rest.

### Use Cases

In [mkdocs-gallery](https://smarie.github.io/mkdocs-gallery/) I try to reproduce what is provided in [sphinx-gallery](sphinx-gallery.github.io/) but using `mkdocs` instead of `sphinx`. For this I am leveraging as much as possible `mkdocs-material` so that example scripts are transformed into markdown source documents with as little as possible raw html (separation of concerns).

There is one feature of sphinx-gallery for which it does not seem possible with mkdocs-material [code blocks](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/) as of today: the ability to limit displayed line numbers. This capability is demonstrated in 

 - [this example](https://sphinx-gallery.github.io/stable/auto_examples/no_output/plot_strings.html#sphx-glr-auto-examples-no-output-plot-strings-py) in sphinx gallery: you see that there are 20 lines displayed entirely and the rest can be see by scrolling down
 - [this example](https://smarie.github.io/mkdocs-gallery/generated/gallery/no_output/plot_strings/) in mkdocs-gallery : you see that currently I cannot provide the equivalent

Is there an obvious trick that I would have missed ? In which case I would be happy to propose a documentation PR so that other users find it easily too. Otherwise, could this be a feature for a future version ? Maybe obtained by setting an `max-nb-lines` attribute on the code block.

For reference, the associated issue in mkdocs-gallery is https://github.com/smarie/mkdocs-gallery/issues/7

*Note: issue #2171 seems related but only talks about width if I am not mistaken.*

### Screenshots / Mockups

![image](https://user-images.githubusercontent.com/3236794/148518508-9f13f1b9-e99f-4a23-abcc-6eb0152702eb.png)

**Comment by lampensau** [comment]
While there is no configuration option that allows you to limit the height, you could achieve a fixed height with a bit of custom css:

```yaml
# mkdocs.yml
extra_css: custom-styles.css
```

```css
/* custom-styles.css */
.md-typeset pre > code {
    max-height: 5rem;
}
```

If you need more specifity for your css selector you could add a custom class to your code block(s) using the extension [attr_list](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#attribute-lists).

**Comment by squidfunk** [comment]
Thanks @lampensau - great customization! It’s trivial to add with CSS.

**Comment by smarie** [comment]
Nice, thanks to you both ! I'll use this solution

**Comment by binooetomo** [comment]
Hi.
I tried to use @squidfunk solution, but it didn't work

here is my mkdocs.yaml
```
...

theme:
  name: material
  features:
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - mkdocs-custom-styles.css

markdown_extensions:
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
```

Here is snip off my code block```

``` { .yaml style="--md-codeblock-height: 200px" linenums="1" title="vi cert-manager.yaml" hl_lines="5200 5258 5335"}

...
 more then 5000 line
 
 ```

``` 
Its still show 5000 more lines.

I tried to remove linenums, title, and hl_lines and still didn't work

Sincerely
-bino-
