### ISSUE TITLE
Lunr JS Search Internationalization

### ISSUE THREAD

**Issue by monarci** [squidfunk/mkdocs-material#345]
## Description

Am building a mkdocs site with this theme, but need to be able to search through Japanese text. I know this is an issue with lunr.js and there is a plug-in ([here](https://github.com/MihaiValentin/lunr-languages)) to work around the issue and would love to see it integrated with this theme by default. Apparently all we need to do is load the plug-in after lunr itself and then set the language when creating the search index. If you could point me in the direction as to how to build your source to the compiled versions found in the `mkdocs-material` package I'll get right to work.

### Expected behavior

Search through Japanese/non-latin text.

### Actual behavior

Only latin characters hit on search, ignoring everything else.

### Steps to reproduce the bug

1. Create a page with non-latin characters
2. Search for said text

### Package versions

* Python: 2.7.5
* MkDocs: 0.16.3
* Material: 1.6.4

### Project configuration

``` yaml
site_name: test
theme: material
copyright: Test
site_author: Test
use_directory_urls: false
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
pages:
  - Home: index.md
  - About: about.md
```

### System information

* OS: CentOS 7
