### ISSUE TITLE
Custom `edit_url` in front-matter of Markdown files

### ISSUE THREAD

**Issue by HonkingGoose** [squidfunk/mkdocs-material#3454]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

In our project we have two repositories:

- `renovatebot/renovate`[^source-repo] <-- Nearly all docs content lives here + some autogenerating `*.md` files based on our code
- `renovatebot/renovate.github.io` [^publish-repo] <-- Builds and publishes the docs

I've set up our publishing repository's `mkdocs.yml` like this, so that we get a edit butotn that works for _most_ but not all pages:

```yaml
# Upstream Git repository information
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
repo_name: renovatebot/renovate
repo_url: https://github.com/renovatebot/renovate
edit_uri: edit/main/docs/usage/
```

Unfortunately some of pages don't have a working "Edit/pencil" button that takes you to the right place to edit the source file.

@viceice had the idea to put a `edit_uri` override in the front-matter of the markdown files that are not working properly for us now, like this: [^comment]

```markdown
---
edit_uri: edit/main/lib/manager/ansible/readme.md
---

Supports Docker-type dependency extraction from Ansible configuration files.

If you need to change the versioning format, read the [versioning](https://docs.renovatebot.com/modules/versioning/) documentation to learn more.

...
```

[^comment]: https://github.com/renovatebot/renovatebot.github.io/pull/130#discussion_r783854415
[^publish-repo]: https://github.com/renovatebot/renovatebot.github.io
[^source-repo]: https://github.com/renovatebot/renovate

### Use Cases

Allow the edit button/pencil to work for all files, when the global `edit_url` [^docs] settings do not work.

[^docs]: https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=repo+edit#edit-button
