### ISSUE TITLE
Config validation warns about `scheme:default` and `scheme:slate`

### ISSUE THREAD

**Issue by HonkingGoose** [squidfunk/mkdocs-material#3523]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Config validation warns about matching multiple schemas when only one must validate.

Related to #3508, but slightly different.

### Expected behaviour

Config validates, as its working properly in our production site. 😉 

### Actual behaviour

4 warnings all like this:

```
Matches multiple schemas when only one must validate. yaml-schema: Color scheme
```

### Steps to reproduce

1. Install `mkdocs-material==8.1.9` and `mkdocs==1.2.3`
1. Create a `mkdocs.yml` file, and put this in it:
    ```yaml
    theme:
      name: 'material'
    
      palette:
        - media: '(prefers-color-scheme: light)'
          scheme: default
          toggle:
            icon: material/weather-sunny
            name: Switch to dark mode
          primary: 'blue'
          accent: 'blue'
        - media: '(prefers-color-scheme: dark)'
          scheme: slate
          toggle:
            icon: material/weather-night
            name: Switch to light mode
          primary: 'cyan'
          accent: 'cyan'
    ```
1. See warnings in VSCode editor.

## Where the warnings are:

To help visualize the problem, here are the places where VSCode complains:

```yaml
theme:
  name: 'material'

  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default <-- WARNING
      toggle:
        icon: material/weather-sunny <-- WARNING
        name: Switch to dark mode
      primary: 'blue'
      accent: 'blue'
    - media: '(prefers-color-scheme: dark)'
      scheme: slate <-- WARNING
      toggle:
        icon: material/weather-night <-- WARNING
        name: Switch to light mode
      primary: 'cyan'
      accent: 'cyan'
```

### Package versions

- Python: `Python 3.8.12`
- MkDocs: `mkdocs, version 1.2.3`
- Material: `Version: 8.1.9`

### Configuration

```yaml
theme:
  name: 'material'

  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: 'blue'
      accent: 'blue'
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: 'cyan'
      accent: 'cyan'
```

### System information

- Operating system: Gitpod
- Browser: doesn't matter
