### ISSUE TITLE
tracking selects wrong anchor when adding header inside tabs

### ISSUE THREAD

**Issue by Jellyfrog** [squidfunk/mkdocs-material#3527]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Tracking selects wrong anchor when adding header inside tabs,
When visiting the site it appends `#toc-in-secondsub2` instead of nothing, or `#first`.

I added a full example here; https://github.com/Jellyfrog/materials-issue

### Expected behaviour

Not appending any anchor, or the first one

### Actual behaviour

Appending the last anchor

### Steps to reproduce

1. Run https://github.com/Jellyfrog/materials-issue
2. Observe it adding  #toc-in-secondsub2 in the url

### Package versions

- Python: `3.10.2`
- MkDocs: `1.2.3`
- Material: `8.1.9`

### Configuration

```yaml
site_name: My Docs
theme:
  name: material
  features:
    - navigation.tracking

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
```

### System information

- Operating system: ...
- Browser: Latest Firefox and chrome
