### ISSUE TITLE
Feature suggestion: add prev/next indicators to content tabs

### ISSUE THREAD

**Issue by Vasperous** [squidfunk/mkdocs-material#3531]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

After upgrading with the new tabbed solution the user is unable to access tabs on the left side after the user has scrolled to the right.  This means they need to reload the page to get the left tabs to appear again.

### Expected behaviour

With longer tabs the user should be able to scroll back to the left after scrolling to the right.

Tabs before the user clicks on "Hello World 7":
![image](https://user-images.githubusercontent.com/8703632/152348596-6c02c25f-3305-4dc3-9953-6517e43709e5.png)

Tabs after the user clicks on "Hello World 7":
![image](https://user-images.githubusercontent.com/8703632/152348715-f5f340f9-15ee-4dbb-93fc-dbf493a026d0.png)

Tabs after the user clicks on "Hello World 3" (note that user cannot access "Hello World 2"):
![image](https://user-images.githubusercontent.com/8703632/152348815-b55b6179-a284-4c90-80da-956cdffd507a.png)

### Actual behaviour

The left tabs are hidden and cannot be accessed by the user.

### Steps to reproduce

1. Create a page with more tabs then horizontal space available
2. Serve the page
3. Click on the right most tab

### Package versions

- Python: `Python 3.10.0`
- MkDocs: `mkdocs, version 1.2.3`
- Material: `Version: 8.1.9+insiders.4.7.1`

### Configuration

```yaml
site_name: 'Page Test'
site_description: 'Test'
site_author: 'Test'
site_url: ''

# Copyright
copyright: 'Copyright &copy; 2021'

# If serving from a website you would want 'true', for offline you want false
use_directory_urls: false

nav:
  - Home:
    - Introduction: index.md

theme:
  name: 'material'
  palette:
    primary: black
    accent: cyan
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - content.tabs.link
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.autohide

extra:
  generator: false

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      base_path: ext_md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      permalink: '#'
      toc_depth: 5

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
```

### System information

- Operating system: Mac OS 12.1
- Browser: Brave
