### ISSUE TITLE
Codeblock Annotations not being rendered properly

### ISSUE THREAD

**Issue by michael-nok** [squidfunk/mkdocs-material#3562]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I'm seeing a few issues in testing code annotations.

1. If there is a single open quote inside the codeblock, comments inside that section are ignored by the annotation sequence.

2. Annotated codeblocks specified within an ordered list prevents the rest of the list from appearing.

### Expected behaviour

1. I expected the annotations to be rendered by the system.
2. I expected to see the remainder of the numbered list.

### Actual behaviour

1. The comments are displayed verbatim within the codeblocks.
2. The remaining steps disappear from the HTML output.

### Steps to reproduce

# Issue 1

Here items 2, 3 and 4 are not rendered into clickable buttons.

````
````yaml
name: egress-router-redirect  # (1)
config: '{
        "name": "egress-router",
        "ip": {
        "addresses": [
                "192.168.12.99/24"    # (2)
                ],
        "destinations": [
                "192.168.12.91/32"    // (3)
                ],
        "gateway": "192.168.12.1" # (4)
        }
        }'
```

1. Hi
2. Mom
3. Love
4. You
````
**Actual output:**

![image](https://user-images.githubusercontent.com/67281799/152996024-f526ef73-c5d9-46a0-b05c-ae8bd606efb3.png)

# Issue 2

Here steps two and three after the codeblock are not appearing in the HTML output.  

````
## Nested codeblock testing

1. This is another test of nested codeblocks

   ```yaml
   name: egress-router-redirect  # (1)
   config: {
       "name": "egress-router",
       "ip": {
       "addresses": [
           "192.168.12.99/24"    # (2)
           ],
       "destinations": [
           "192.168.12.91/32"    # (3)
           ],
       "gateway": "192.168.12.1" # (4)
       }
       }
   ```

   1. Hi
   2. Mom
   3. Love
   4. You


1. This is the second step.

1. This is the third step.
````

**Actual output:**

![image](https://user-images.githubusercontent.com/67281799/152996273-e6e133d6-d76d-4153-a4c7-bac135c72202.png)

Digging into the source code, I'm seeing the following HTML code:

```
<ol hidden="">
<li></li>
<li></li>
<li></li>
<li></li>
<li>
<p>This is the second step.</p>
</li>
<li>
<p>This is the third step.</p>
</li>
</ol>
```

**Output from Firefox**

Firefox doesn't seems to render this content at all (protected mode by default), perhaps this sheds some light on what's going on.

![image](https://user-images.githubusercontent.com/67281799/152997380-a2ae342b-57e4-443d-970c-ef3295a1d098.png)

### Package versions

- Python: 3.6.8
- MkDocs: mkdocs, version 1.2.3 
- Material: Version: 8.1.8+insiders.4.7.0

### Configuration

```yaml
site_name: Testing
theme:
    name: material
    features:
        - navigation.instant
        - navigation.tabs
        - search.highlight
        - search.suggest
        - content.code.annotate
```

### System information

- Operating system: Windows 10
- Browser: Chrome and Edge.  Firefox doesn't seem to render this content correctly.
