### ISSUE TITLE
Dark mode on Firefox needs to be turned on for every single page

### ISSUE THREAD

**Issue by LuizFarias** [squidfunk/mkdocs-material#3570]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I have been using the material to write a manual, and we realized with the build of the generated site that we need to activate the dark mode for each page in Firefox. 

It happens when I open the generated HTML directly on Firefox. When I use mkdocs serve, the dark theme persists on all pages.

### Expected behaviour

It is expected that the dark theme persists on the entire site after being turned on on any page.

### Actual behaviour

It is necessary to turn on the dark theme on every single page.

![material_dark_firefox](https://user-images.githubusercontent.com/11771556/153469231-894e2821-96d8-4305-b8a2-c4875e9ee0fd.gif)

### Steps to reproduce

1. Build the site with `mkdocs build ...`
2. Go to the folder and open the HTML page on the Firefox
3. Turno on the dark theme
4. Change to another page and see that the other page is still on the light theme

### Package versions

- Python: `3.8.0`
- MkDocs: `1.2.3`
- Material: `8.1.7`

### Configuration

```yaml
site_name: 'placeholder'
docs_dir: '../../docs/en'
site_dir: '../../generated/en'
use_directory_urls: false

theme:
  name: material
  logo: assets/placeholder.png
  favicon: assets/favicon.png
  custom_dir: '../../overrides'
  font:
    text: placeholder
    code: placeholder
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle: 
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.tabs

plugins:
  - search:
      lang: en
  - localsearch
  - with-pdf:
      author: placeholder
      cover: true
      cover_title: placeholder
      cover_subtitle: placeholder
      exclude_pages: 
        - placeholder.html

extra_css:
  - stylesheets/extra.css

extra:  
  social:
    - icon: placeholder
      link: placeholder
    - icon: placeholder
      link: placeholder

markdown_extensions:
  - admonition
  - meta
  - attr_list

copyright: placeholder      

nav:
  - nav1: placeholder.md
  - nav2: placeholder.md
  - nav3: placeholder.md
  - nav4: placeholder.md
```

### System information

- Operating system: Linux (Ubuntu 20), Windows 10
- Browser: Firefox version 96
