### ISSUE TITLE
scrollable content tabs display exception when upgrade 8.x

### ISSUE THREAD

**Issue by Karenlrx** [squidfunk/mkdocs-material#3579]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

![image](https://user-images.githubusercontent.com/38199201/153806196-5e9b71fb-4450-4aee-b3f8-fb041d20a771.png)

when upgrade mkdocs-material from 7.x to 8.x , read the changlog and already [changes to mkdocs.yml](https://squidfunk.github.io/mkdocs-material/upgrade/#changes-to-mkdocsyml),how to solve this problem?

### 

### Expected behaviour

scrollable content tabs display exception display corectlly

### Actual behaviour

![image](https://user-images.githubusercontent.com/38199201/153806196-5e9b71fb-4450-4aee-b3f8-fb041d20a771.png)

### Steps to reproduce

1. mkdocs bulid
2. mkdocs serve

### Package versions

- Python: 3.9.7
- MkDocs: 1.2.2
- Material: 8.1.8

### Configuration

```yaml
extra_css:
  - stylesheets/extra.css
theme:
  logo: assets/logo.png
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
  font:
    # text: Roboto
    code: Roboto Mono
  palette:
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   primary: black
    #   accent: blue
    #   toggle:
    #     icon: material/weather-sunny
    #     name: Switch to night mode
    # - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
edit_uri: edit/master/docs/docs

extra:
  version:
    provider: mike

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
```

### System information

- Operating system: macos
- Browser: chrome
