### ISSUE TITLE
macos livereloadjs can't loaded，mermaid graph render failed

### ISSUE THREAD

**Issue by phygerr** [squidfunk/mkdocs-material#3596]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

macos livereloadjs can't loaded，always loading... so the mermaid graph render failed。
![image](https://user-images.githubusercontent.com/42068889/154790780-80ff1b52-e936-4e60-8482-db34c1a02dce.png)

OS：mac Monterey
Python Version：3.8.9
I use chrome and safari , they all can't 

mermaid code

``` mermaid
sequenceDiagram
  Alice->>John: Hello John, how are you?
  loop Healthcheck
      John->>John: Fight against hypochondria
  end
  Note right of John: Rational thoughts!
  John-->>Alice: Great!
  John->>Bob: How about you?
  Bob-->>John: Jolly good!
```

web page

![image](https://user-images.githubusercontent.com/42068889/154790948-db7c92e0-b732-4a07-8aea-a9e47279af7e.png)

### Expected behaviour

mermaid graph render success

### Actual behaviour

mermaid graph render failed

### Steps to reproduce

mkdocs new demo
config mermaid 
mkdocs serve to preview

### Package versions

- Python: 3.8.9
- MkDocs: 1.2.3
- Material: 8.2.1

### Configuration

```yaml
site_name: My Docs
theme:
  name: material
  language: zh

  features:
    - navigation.tabs
    - content.code.annotate

  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16


  palette:
    - media: "(prefers-color-scheme: light)"
      primary: deep purple
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: grey
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
extra:
  alternate:
    - name: 本站仅支持中文
      link: /
      lang: zh

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
```

### System information

- Operating system: mac Monterey
- Browser: chrome 98.0.4758.80（正式版本） (x86_64)
