### ISSUE TITLE
Bug: List and sublist does not work as expected

### ISSUE THREAD

**Issue by murugappanrm** [squidfunk/mkdocs-material#3612]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I created a list and sublist under one of the list. the output did not result as expected.
Please help.

### Expected behaviour

```
1. **Application** - Enter the full name of the application (max 200 chars). The application may use this field in their headings
2. **Status** - select one of the following options:
   1. ***Active*** - If the application has been installed and available
   2. ***Inactive*** - if the application is yet to be available. EmasApiServer will only deliver active items
```

### Actual behaviour

[https://prnt.sc/1UPKRdg1NTcz](url)

### Steps to reproduce

Create md file with the following:

`![eMAS Logo](assets/images/standard/emasdoclogo.png){ width="300" } ![Doc Logo](assets/images/standard/emasauth_logo.png){ width="200" }

# User Guide Version 01.00 {: .tophead }

Application Parameter Definition (***Appslist***) 
{: .parahead }

## Description
Use the appslist menu to define an application and its parameters. Except for the application name and application code, all others fields are for documentary prposes and can be used as inventory

## List
On selecting this menu item, the system initially presents a list of applications previously defined:

![API Resouce](assets/images/appslist/Itemslist.png){ width="900" }

1. Click the **Create Applist** button to create a new application definition.
2. Click any **left box** to select the item and click the **Actions** to perform a number of action e.g remove (delete).
3. Click the **Application Name** of an item to update the application parameters.

### Input Screen
On selecting for creation or edit the following input will be presented:

![API Resouce](assets/images/appslist/applist_fields.png){ width="900" }

### Input Fields

1. **Application** - Enter the full name of the application (max 200 chars). The application may use this field in their headings
2. **Status** - select one of the following options:
   1. ***Active*** - If the application has been installed and available
   2. ***Inactive*** - if the application is yet to be available. EmasApiServer will only deliver active items

*[Authenticator]: Emas Authentication System (emasauthcrm)
*[EmasApiServer]: eMAS Api Server V2
*[CRUD]: Create,Read,Update,Delete
`

### Package versions

- Python Version: 3.10.1
- MkDocs: 1.2.3
- Material: latest

### Configuration

```yaml
site_name: eMAS Authentication System - User Guide
site_url: ''
copyright: Copyright 2022 Emas Sdn Bhd (version 02.01)

      linenums_style: pymdownx-inline
      # linenums: true
      use_pygments: true
      # anchor_linenums: true
  - pymdownx.inlinehilite
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: true
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.betterem
  - pymdownx.saneheaders
  - pymdownx.caret:
      smart_insert: true
      insert: true
      superscript: true
```

### System information

Windows 10
Firefox
VS Code for editing
