### ISSUE TITLE
Can't use custom icons in the social footer part

### ISSUE THREAD

**Issue by AmoebeLabs** [squidfunk/mkdocs-material#3629]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Specifying an custom icon for the social footer doesn't seem to work.

I had to check the "the problem doesn't occur with the mkdocs or readthedocs themes", as I can't find the social icon feature.

### Expected behaviour

Just as with the documentation itself, I would expect to be able to specify a custom icon from the `overrides` folder.

### Actual behaviour

MkDocs can't build the documentation anymore in that case: it seems to look only in its own `.icons` folder.

It shows the custom icon in the log, without any error, and keeps building the documentation:

`.icons/custom/my-logo.svg`

### Steps to reproduce

1. Add custom logo to extra/social in mkdocs.yml
2. Save and see the error

### Package versions

- Material: 8.1.10 (Docker container)

### Configuration

```yaml
extra:
  social:
    - icon: custom/my-logo
      link: https://custom-site/page
```

### System information

- Operating system: W10
- Browser: Chrome 98.x

**Comment by AmoebeLabs** [comment]
Sorry, I forgot to include that part of my `mkdocs.yml`.

I already use custom icons (which work), but the reference in the social stuff doesn't.

```yaml
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - docs/overrides/.icons
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
```

**Comment by squidfunk** [comment]
Thanks for providing the rest of `mkdocs.yml`. You specified:

``` yaml
- pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - docs/overrides/.icons
```

This means that the extension will look inside the `docs` directory. It's recommended to __not__ put custom icons or any theme overrides in the `docs` directory, but in a directory adjacent to `docs`, e.g. `overrides`, [exactly as explained in the documentation](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#additional-icons). If you follow the guide and use the correct folder structure, the theme will find the icons:

``` yaml
- pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
```

Then use the following structure:

```
.
├─ overrides/
│  └─ .icons/
│     └─ custom/
│        └─ my-logo.svg
└─ mkdocs.yml
```

**Comment by squidfunk** [comment]
Okay, thanks. You can use the icon in regular Markdown? so if you use `:m3-m3-logo:`, it renders correctly? @facelessuser do you have any idea what could be wrong so that the icon cannot be used from partials?

**Comment by facelessuser** [comment]
@squidfunk, how do you handle social icons? I'm not quite sure how the emoji extension is supposed to process non Markdown icons indicated in the social config. Maybe I'm missing something?

**Comment by squidfunk** [comment]
Oh man, I messed up 🤦‍♂️ You're absolutely right, the Emoji extension has nothing to do with this. Sorry for the confusion.

@AmoebeLabs I think if you use theme extension, the theme should find the icons, so basically:

``` yaml
theme:
  name: material
  custom_dir: overrides

extra:
  social:
    - icon: custom/my-logo
```

The `custom_dir` is the essential part here, as it tells MkDocs to also look for template files and partials in this folder. This was likely the missing part. As you did not provide your entire `mkdocs.yml` configuration, I can only guess that this is missing though. Then, use this structure:

```
.
├─ overrides/
│  └─ .icons/
│     └─ custom/
│        └─ my-logo.svg
└─ mkdocs.yml
```
