### ISSUE TITLE
Code annotations at the bottom of a page add additional space

### ISSUE THREAD

**Issue by Wilfried71** [squidfunk/mkdocs-material#3639]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When I have a code annotation at the bottom of the page, there is blank space after the footer.

### Expected behaviour

We shall have something like that :

![image](https://user-images.githubusercontent.com/54243696/155979654-47231ad7-cce9-4f89-b555-876c59b93229.png)

### Actual behaviour

![image](https://user-images.githubusercontent.com/54243696/155972340-49d21d68-d7ca-4102-a523-c597ba70511d.png)

### Steps to reproduce

Write this in index.md (remove backslash before sql quotes): 

```markdown
## A - Lorem ipsum
---

Non sint qui consequat velit duis occaecat laboris Lorem magna excepteur excepteur id commodo. Eu fugiat laborum in cillum ea duis minim. Culpa reprehenderit adipisicing esse aliquip. Sit cupidatat esse ullamco ullamco sint nisi quis nisi in minim ut do culpa non. Voluptate adipisicing do et exercitation exercitation Lorem minim Lorem dolor eu duis ut.

Velit aliquip culpa minim anim minim culpa ut est tempor cillum. Et ea officia quis ea aliqua enim cillum minim laboris. Lorem deserunt deserunt duis culpa est non sint consectetur sit voluptate irure commodo qui eu. Officia ex amet eiusmod incididunt pariatur reprehenderit voluptate eiusmod eu incididunt eu. Eu dolore ipsum non elit sit mollit in adipisicing dolore nostrud mollit cupidatat. Commodo elit adipisicing quis duis pariatur anim cupidatat ex tempor duis nisi laboris do.

Minim reprehenderit consectetur cillum sunt veniam aliquip qui sint consequat. Velit nisi sint aliquip magna ut laboris elit id consectetur. Nostrud ullamco cillum Lorem Lorem exercitation exercitation sit sint Lorem dolore sint. Elit mollit quis duis magna incididunt velit et adipisicing. Commodo qui cupidatat enim commodo est magna sint. Magna mollit aliquip dolor ad deserunt magna ullamco proident magna ad nisi occaecat.

## C - Test code annotations
---

\```java
public class MyClass extends MyParent { 
    public Object sendHttpRequest() {
        // (1)
    }
}
\```

1.  An **HTTP** request is a request from a **client** and a **server** (also named service). 
    Here is a request :
    ``` mermaid
    sequenceDiagram
        participant user
        participant service

        user->>service: HTTP Request
        service->>user: Return
    ```
```

### Package versions

- Python: **3.8.10**
- MkDocs: **1.2.3**
- Material: **8.2.1**

### Configuration

```yaml
site_name: My Docs
theme:
  name: material
  features:
    - content.code.annotate 

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tabbed:
      alternate_style: true
```

### System information

- Operating system: Windows 10
- Browser: Chrome 98.0.4758.102
