### ISSUE TITLE
Mermaid gantt charts in dark mode

### ISSUE THREAD

**Issue by timvink** [squidfunk/mkdocs-material#3640]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The following mermaid diagram:

```mermaid
gantt
    dateFormat  YYYY-MM-DD
    title       Adding GANTT diagram functionality to mermaid
    excludes    weekends
    %% (`excludes` accepts specific dates in YYYY-MM-DD format, days of the week ("sunday") or "weekends", but not the word "weekdays".)

    section A section
    Active task               :active,  des2, 2020-02-01, 2021-01-31
```

Renders as:

<img width="522" alt="image" src="https://user-images.githubusercontent.com/5570380/156006421-48c84670-ace0-4750-b0db-c6f5a006df61.png">

But in dark mode it renders as:

<img width="519" alt="image" src="https://user-images.githubusercontent.com/5570380/156006475-aef2de31-e496-4aca-8041-20902d29cc53.png">

The [docs](https://squidfunk.github.io/mkdocs-material/reference/diagrams/?h=mermaid) mention:

> Support for both, light and dark color schemes – try it on this page!

But they do not include an example of a gantt chart. If that's something you want to include, then this issue might be something worth fixing.

### Expected behaviour

Proper color handling when switching to dark mode

### Actual behaviour

Some colors are not switching to a dark mode variant 

### Steps to reproduce

In a markdown page:

```mermaid
gantt
    dateFormat  YYYY-MM-DD
    title       Adding GANTT diagram functionality to mermaid
    excludes    weekends
    %% (`excludes` accepts specific dates in YYYY-MM-DD format, days of the week ("sunday") or "weekends", but not the word "weekdays".)

    section A section
    Active task               :active,  des2, 2020-02-01, 2021-01-31
```

### Package versions

- Python: `python --version` 3.9.5
- MkDocs: `mkdocs --version` 1.2.3
- Material: `pip show mkdocs-material | grep -E ^Version` 8.2.1

### Configuration

```yaml
theme:
    favicon: assets/images/favicon.ico
    name: material
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
          primary: blue
          accent: blue
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
          primary: blue
          accent: blue

markdown_extensions:
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
```

### System information

- Operating system: Ubuntu
- Browser: Chrome
