### ISSUE TITLE
Insiders privacy plugin failing on build (with malformed Google fonts stylesheets links?)

### ISSUE THREAD

**Issue by villeodell** [squidfunk/mkdocs-material#3642]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I'm hoping to use the very useful privacy feature of insiders, but the mkdocs build fails when it's enabled and a custom Google font is specified.

### Expected behaviour

External script plus stylesheets are successfully bundled by the privacy plugin during build without error as described at https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/?h=privacy#built-in-privacy-plugin

### Actual behaviour

With
```
privacy:
      externals: bundle
      externals_directory: assets/externals
```
Result is:
```
ERROR    -  Error building page 'index.md': 'text/html'
File "/mkdocs-material-insiders/material/plugins/privacy/plugin.py", line 111, in on_post_page
    value.replace(raw, self.__fetch(url, page)),
  File "/mkdocs-material-insiders/material/plugins/privacy/plugin.py", line 193, in __fetch
    extension = extensions[name]
KeyError: 'text/html'
```
With
```
privacy:
      externals: report
      externals_directory: assets/externals
```
It seems like stylesheet links 

### Steps to reproduce

Specify

```
theme:
  font:
    text: Roboto
```

with 

```
plugins:
  - privacy:
      externals: bundle
      externals_directory: assets/externals
```

If I leave out the custom Google font, the site is built fine.

If I set 
```
plugins:
  - privacy:
      externals: report
      externals_directory: assets/externals
```

The external asset for Roboto is reported as:
```
WARNING  -  External asset in 'index.html':
            https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i%7C:400,400i,700,700i&display=fallback
```

Following the link results in a 404 error, which may be why the privacy plugin fails? 

### Package versions

- Python: Python 3.9.10
- MkDocs: mkdocs, version 1.2.3 from /usr/local/lib/python3.9/site-packages/mkdocs (Python 3.9)
- Material: 8.2.3+insiders.4.10.0

### Configuration

```yaml
site_name: Test
plugins:
  - search
  - macros
  - minify:
      minify_html: true
  - privacy:
      externals: bundle
      externals_directory: assets/externals
theme:
  name: material
  font:
    text: Roboto
```

### System information

- Operating system: ...
- Browser: ...
