### ISSUE TITLE
Text runs out of box in Mermaid diagrams (Firefox only)

### ISSUE THREAD

**Issue by btbf** [squidfunk/mkdocs-material#3670]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The way mermaid is specified in mkdocs.yml, the layout is broken in firefox.
Font size does not fit within the box

### Expected behaviour

Font size fits within the box

### Actual behaviour

This phenomenon occurs when you specify the following in mkdocs.yml.
```
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
```

In the following cases, css is applied normally, But js doesn't apply until refresh browser.
```
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
```

### Steps to reproduce

1.Put the following in mkdocs.yml
```
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
```

2.Describe the following in the markdown
```
mermaid
    graph LR
        A[エアギャップ] -->|stakepoolid_bech32.txt / stakepoolid_hex.txt| B[BP];
```

3.View in Firefox

### Package versions

- Python: `python --version`
Python 3.8
- MkDocs: `mkdocs --version`
- Material: `pip show mkdocs-material | grep -E ^Version`
Version: 8.2.5+insiders.4.11.0

### Configuration

```yaml
- pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
```

### System information

- Operating system: ...Windows10
- Browser: ...Fiewfox
