### ISSUE TITLE
IE 11 rendering issue

### ISSUE THREAD

**Issue by mdd41** [squidfunk/mkdocs-material#368]
## Description

An Mkdocs site with the material theme does not render properly in IE.

IE 11 reports  "'App' is undefined." error.  Browser screenshot below.

Works well on Chrome 58 and Firefox 53.

This is a known issue with IE 11. Please refer to the MKDocs https://github.com/mkdocs/mkdocs/pull/786/files. 

 <meta http-equiv="X-UA-Compatible" content="IE=edge"> needs to be added to base.html 

### Package versions

* Python: `python --version`  - Python 2.7.13
* MkDocs: `mkdocs --version`  - mkdocs, version 0.16.3
* Material: `pip show mkdocs-material | grep -E ^Version` - Version: 1.7.3

### Project configuration

``` yaml
site_name: ""
docs_dir: 'content'
theme: 'material'
theme_dir: 'theme'
use_directory_urls: true
site_description: 'Description'
site_author: 'Author'
site_favicon: 'images/favicon.ico'

pages:
- Reference Hub: 'index.md'

extra:
  logo: 'images/Logopng'
  palette:
    primary: 'red'
    accent: 'light green'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

extra_css:
  - '_css/extra.css'

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - fenced_code
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
```

### System information

* OS: Deployed to Cloud Foundry using the static buildpack
* Browser: IE11, Chrome 58, Firefox 53

### Browser screenshot

![image](https://user-images.githubusercontent.com/19415267/27115923-bf3b36c2-5082-11e7-859f-fee253c8fdb0.png)

![image](https://user-images.githubusercontent.com/19415267/27115934-cf9d2e94-5082-11e7-82b0-6f5e921dc473.png)
