### ISSUE TITLE
Disqus integration not working.

### ISSUE THREAD

**Issue by julien-sarazin** [squidfunk/mkdocs-material#371]
Tried to integrate disqus on my documentation : [https://julien-sarazin.github.io/Idylle/](https://julien-sarazin.github.io/Idylle/)

Result when checking the Disqus integration :
`We were unable to load Disqus. If you are a moderator please see our troubleshooting guide.`

### Package versions
Python  2.7.13
mkdocs 0.16.3
material: 1.7.3

### Softwares Versions
* OS: MAC OS Sierra
* Browser: Chrome

``` yaml
# Project information
site_name: 'Idylle'
site_description: 'Presentation and Documentation of the micro-framework'
site_author: 'Julien Sarazin'
site_url: 'https://julien-sarazin.github.io'

# Repository
repo_name: 'julien-sarazin/Idylle'
repo_url: 'https://github.com/julien-sarazin/Idylle'

# Copyright
copyright: 'Copyright &copy; 2016 - 2017'

# Documentation and theme
theme: 'material'

# Options
extra:
  logo: 'images/logo.svg'
  palette:
    primary: 'Pink'
    accent: 'Amber'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/julien-sarazin'
    - type: 'twitter'
      link: 'https://twitter.com/julien-sarazin'
    - type: 'linkedin'
      link: 'https://de.linkedin.com/in/julien-sarazin'
  disqus: 'jsarazin'
  
# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false,linenums=true)
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

# Content
pages:
    - Introduction: index.md
    - Getting Started: getting-started.md
    - Architecture: architecture.md
    - Dependencies: dependencies.md

```

My Disqus username is `jsarazin` and added as trusted domain `github.io` and `julien-sarazin.github.io`.
