### ISSUE TITLE
How to shift to UTF-16

### ISSUE THREAD

**Issue by krishyadav007** [squidfunk/mkdocs-material#3710]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

![image](https://user-images.githubusercontent.com/44264836/156877830-d9a448d9-3665-4ea8-be27-55a758ccd506.png)

The markdown files in my docs are written in native languages which is part of Unicode 16. 

But MKdocs doesn't support UTF 16, is there a way to shift to UTF 16?

### Expected behaviour

Should render Mkdocs of native language like this
![image](https://user-images.githubusercontent.com/44264836/156877830-d9a448d9-3665-4ea8-be27-55a758ccd506.png)

### Actual behaviour

Error
![image](https://user-images.githubusercontent.com/44264836/156877830-d9a448d9-3665-4ea8-be27-55a758ccd506.png)

### Steps to reproduce

Write UTF-16 characters in md files

### Package versions

- Python: `3.6`
- MkDocs: `mkdocs --version`
- Material: `pip show mkdocs-material | grep -E ^Version`

### Configuration

```yaml
site_name: BhashaX docs
site_url: https://bhashax.krishyadav.com/
site_description: "The official documentation of Bhasha X"
site_author: "Krish Yadav, Creator of BhashaX"
copyright: "Copyright © The BhashaX Project 2021"

nav:
    - Home: index.md
    - Basic:
      - About us: /en/about.md
    - English:
        - Documentation: en.md


theme: 
  name: material
  logo: https://github.com/krishyadav007/BhashaX/raw/main/Logo/Logo.png?raw=true
  favicon: images/favicon.png
  palette: 
  - scheme: default
    toggle:
      icon: material/weather-sunny 
      name: Switch to dark mode
  - scheme: slate 
    toggle:
      icon: material/weather-night
      name: Switch to light mode
```

### System information

- Operating system: Ubuntu 20
- Browser: Chrome
