### ISSUE TITLE
Setting the page icon doesn't work

### ISSUE THREAD

**Issue by L00PBACK** [squidfunk/mkdocs-material#3722]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

Hello, I am encountering a bug when i put inside my markdown file no icon show up in my navigation sidebar
```
---
tags:
  - terraform 
  - iaas
icon: material/terraform
---

# Terraform 

```
Of course, i have my markdown-extensions meta enable.

### Expected behaviour

Getting an icon on my navigation sidebar

### Actual behaviour

Nothing show up

### Steps to reproduce

1. Here there is my configuration https://etyy.gitlab.io/etydocs/tools/terraform/ link 1 
2. And here https://etyy.gitlab.io/etydocs/tools/ansible/ link 2

### Package versions

- Python: `3.10.2`
- MkDocs: `version 1.2.3`
- Material: `8.2.5`

### Configuration

```yaml
theme:
  name: material
  icon:
    repo: fontawesome/brands/gitlab
    logo: octicons/terminal-16
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    code: Roboto Mono
    text: Roboto  
  features:
    - navigation.tracking # Anchor tracking
    - navigation.tabs # Menu dans la nav
    - toc.follow 
    - navigation.top # Page UP Button
    - navigation.indexes
    - content.code.annotate

plugins:
  - search:
      lang:
        - fr
        - en
  - tags
  - git-revision-date-localized:
      type: datetime

markdown_extensions:
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.emoji: # Emoji https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences: # Diagrams https://squidfunk.github.io/mkdocs-material/reference/diagrams/
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Tools: 
    - Ansible: tools/ansible.md
    - Terraform: tools/terraform.md
```

### System information

- Operating system: macOs 12.2.1 Montserey
- Browser: Chrome Version 99.0.4844.51
