### ISSUE TITLE
How to remove footer: powered by MkDocs and Material for MkDocs

### ISSUE THREAD

**Issue by bearpear** [squidfunk/mkdocs-material#373]
## Description

How to remove footer? I tried but I could not.

### Expected behavior

How to remove it?

### Actual behavior

I must remove footer for my project.

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Package versions

* Python: `3.6.1`
* MkDocs: `0.16.3`
* Material: `1.7.3`

### Project configuration

``` yaml
site_name: Eko Bilim Ar-Ge Lab
pages:
    - Ana Sayfa: index.md
theme: material
theme_dir: theme
```

### System information

* OS: [Windows 8.1]
* Browser: [Chrome]
