### ISSUE TITLE
I can't chance language.

### ISSUE THREAD

**Issue by bearpear** [squidfunk/mkdocs-material#376]
## Description

I can't change my language. Please help me! 
My language.html:
```
{% macro t(key) %}{{ {
  "language": "tr",
  "edit.link.title": "Bu sayfayı düzenle",
  "footer.previous": "Önceki",
  "footer.next": "Sonraki",
  "meta.comments": "Yorumlar",
  "meta.source": "Kaynak",
  "search.languages": "tr",
  "search.placeholder": "Arama",
  "search.result.placeholder": "Aramak için birşeyler yaz",
  "search.result.none": "Eşleşen döküman bulunamadı.",
  "search.result.one": "1 eşleşen döküman",
  "search.result.other": "# eşleşen dökümanlar",
  "source.link.title": "Depoya git",
  "toc.title": "İçerik tablosu"
}[key] }}{% endmacro %}
```

### Expected behavior

[How to change it?]

### Actual behavior

[My language is not working]

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Package versions

* Python: `3.6.1`
* MkDocs: `0.16.3`
* Material: `1.7.3`

### Project configuration

``` yaml
site_name: Eko Bilim Ar-Ge Lab
pages:
    - Ana Sayfa: index.md
    - Baba Sayfa: 2.txt
theme: material
theme_dir: material
copyright: Copyright © 2017 eko.science
extra:
  disqus: 'ekoscience'
  social:
    - type: 'website'
      link: 'https://discord.gg/c8H4GKU'
```

### System information

* OS: [Windows 8.1]
* Browser: [Chrome]
