### ISSUE TITLE
Tabs are not working as expected.

### ISSUE THREAD

**Issue by harishjangam6979** [squidfunk/mkdocs-material#3767]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

Tabs are not showing the content underneath them. I've tried several ways but not able to figure out. I think it is something wrong with my personal css file. 

Here are my markdown_extensions:

```
markdown_extensions:
- attr_list
- pymdownx.snippets
- codehilite:
    linenums: true
- admonition
- pymdownx.inlinehilite
- pymdownx.superfences
- pymdownx.details
- attr_list
- def_list
- footnotes
- pymdownx.caret
- pymdownx.smartsymbols
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tilde
- toc:
    permalink: true
    title: "<big>📌  Table of Contents</big>"
- markdown_include.include:
    base_path: docs
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
 ```

### Expected behaviour

Tabs should show content that is written underneath it. 

### Actual behaviour

Conents under pymdownx.tabbed are not showing up. 

### Steps to reproduce

Look at my [github hosted page](https://harishjangam6979.github.io/mkdocs/topics/harish/).

Here is my [GITHUB uRL](https://github.com/harishjangam6979/mkdocs)

### Package versions

Hosting in on github using `mkdocs gh-pages`

### Configuration

```yaml
site_name: Harish Docs
site_url: https://harishjangam6979.github.io/mkdocs/topics/harish/

Please find my [GITHUB uRL](https://github.com/harishjangam6979/mkdocs)
```

### System information

- Operating system: MACos
- Browser: Chrome

**Comment by squidfunk** [comment]
Thanks for reporting. I looked at your site and the source of error is clearly in your customization – you are hiding the content container with the following rule in an extra CSS file, so if you remove that you should be fine:

``` css
.tabbed-set .tabbed-content {
    display: none;
    order: 99;
    width: 100%;
}
```

Thus, the error stems not from Material for MkDocs itself, but from your customization. Unfortunately, we cannot offer support to help users figure out their customizations – we need to budget the time to work on bugs and features.
