### ISSUE TITLE
Mermaid doesn't render when network is not available

### ISSUE THREAD

**Issue by gyund** [squidfunk/mkdocs-material#3781]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

If you are writing documentation and you lose access to the internet, mermaid diagrams render as code blocks instead of the diagrams.

### Expected behaviour

Mermaid diagrams are rendered

### Actual behaviour

Mermaid does not display the diagram as an image when network access is unavailable. 

### Steps to reproduce

1. Follow these directions for setting up mermaid support: https://squidfunk.github.io/mkdocs-material/reference/diagrams/
2. Create a mermaid codeblock in a markdown file (take any example from the link above)
3. run `mkdocs serve` and verify the diagram is displayed
5. Disable your network adapter (or unplug your network cable)
6. Refresh the page. The diagram is now rendered as a codeblock

### Package versions

- Python:  Python 3.8.10
- MkDocs: mkdocs, version 1.3.0
- Material:  Version: 8.2.8

### Configuration

```yaml
site_name: My Docs
theme: material

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
```

### System information

- Operating system: Ubuntu 20.04
- Browser: Chrome / Firefox
