### ISSUE TITLE
Config value: 'plugins'. Error: The "tags" plugin is not installed Aborted with 1 Configuration Errors!

### ISSUE THREAD

**Issue by dileep-ehr** [squidfunk/mkdocs-material#3786]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

Upgraded mkdocs & mkdocs-material 

The site-packages folder contains the following 
```
mkdocs-1.1.2.dist-info
mkdocs-1.3.0.dist-info
mkdocs_gitbook
mkdocs_gitbook-0.0.1.dist-info
mkdocs_git_revision_date_localized_plugin
mkdocs_git_revision_date_localized_plugin-0.8.dist-info
mkdocs_git_revision_date_plugin
mkdocs_git_revision_date_plugin-0.3.1.dist-info
mkdocs_material-6.2.3.dist-info
mkdocs_material-8.2.8.dist-info
mkdocs_material_extensions-1.0.1.dist-info
mkdocs_material_extensions-1.0.3.dist-info

```

$ pip3 show mkdocs-material given the following output
```
Name: mkdocs-material
Version: 8.2.8
Summary: A Material Design theme for MkDocs
Home-page: https://squidfunk.github.io/mkdocs-material/
Author: Martin Donath
Author-email: martin.donath@squidfunk.com
License: MIT
Location: /home/dileep/.local/lib/python3.6/site-packages
Requires: pygments, mkdocs-material-extensions, mkdocs, pymdown-extensions, markdown, jinja2
```

$mkdocs serve/build aborts with error when tags plugin is added. I have not added any tags to pages metadata and still getting error.

### Expected behaviour

Should build without error

### Actual behaviour

$mkdocs serve/build aborts with error when tags plugin is added. I have not added any tags to pages metadata and still getting error.

It works file if 

`- tags `

is removed

### Steps to reproduce

$mkdocs serve

### Package versions

- Python: `python3 --version` - Python 3.6.9
- MkDocs: mkdocs, version 1.3.0
- Material: Version: 8.2.8

$python -- version  shows -  Python 2.7.17. All installations done using pip3 and so, I assume they should be using python3

### Configuration

```yaml
site_name: EHR.Network Documentation
site_url: https://docs.ehr.network/site
site_description: Developer documentation for EHR.Network.
copyright: Copyright &copy; 2020 - 2022 Healthelife ventures

nav:
    - About:
      - Overview: index.md
      - Building blocks: building_blocks.md
    - Developer resources:
      - Overview: implementor_guide.md
      - Learning resources: learning_resources.md
      - Howtos: howtos.md
    - FAQs:
      - General: faq_general.md
      - Privacy & security: faq_privacy_security.md
      - Developer: faq_developer.md
      - openEHR: faq_openehr.md
      - CDSS: faq_cdss.md
    - API docs(OpenAPI 3):
      - Overview: api_documentation.md 
      - SAAS APIs: saas_apis.md
      - Box APIs: box_apis.md      
      - Terminology APIs: https://docs.ehr.network/apidocs/terminology.html
      - Git repository: https://gitlab.com/healthelife/ehr.network/api-specs
    - Developer tools: 
      - Overview: ehr.network_developer_tools.md
      - EHR: https://gitlab.com/healthelife/ehr.network/ehrnetwork-developer-tools/-/tree/master/EHR
      - Terminology: https://gitlab.com/healthelife/ehr.network/ehrnetwork-developer-tools/-/tree/master/terminology%20service


theme: 
  name: material
  palette:
    scheme: default
  favicon: img/favicon.ico
  logo: img/ehrnetwork_icon192.png
  features:
    - navigation.sections
    - navigation.instant

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ehrnetwork
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ehrnetwork
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/healthelife_ventures_llp/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/ehrnetwork

plugins:
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true
  - search
  - tags

markdown_extensions:
  - pymdownx.critic
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - abbr
  - footnotes
  - meta
```

### System information

- Operating system: Ubuntu
- Browser: Firefox
