### ISSUE TITLE
Instant loading does not work with section anchors in Safari

### ISSUE THREAD

**Issue by ybizeul** [squidfunk/mkdocs-material#3797]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Beginning with version 7.0.0 anchors defined on headings do not work with Safari 15.4 macOS

### Expected behaviour

Clicking the the link on the TOC should jump to the section in the main content
Using a URL with # anchor should open the page at the location.

### Actual behaviour

Page stays on top

### Steps to reproduce

Run website and click on a H3 link on the right side

### Package versions

- Python: `Python 3.8.7`
- MkDocs: `mkdocs, version 1.1.2 from /usr/local/lib/python3.8/site-packages/mkdocs (Python 3.8)`
- Material: `7.0.0`

### Configuration

```yaml
site_name: Test Site
nav:
  - Home: /
theme:
  name: material
  features:
     - navigation.instant
markdown_extensions:
  - toc:
      permalink:
```

### System information

- Operating system: macOS 12.3.1
- Browser: Safari 15.4
