### ISSUE TITLE
Can't add CSS class to icons

### ISSUE THREAD

**Issue by warriotox** [squidfunk/mkdocs-material#3798]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Adding the custom CSS suffix to the icon doesn't add it as a HTML CSS class, but actually renders it as HTML.
![image](https://user-images.githubusercontent.com/5864114/161515763-beefa94b-ec0f-4622-b24f-976c1ef58310.png)

### Expected behaviour

Adding the custom suffix will apply the string as an HTML CSS class on the element. Same as in the demo - https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#using-icons

### Actual behaviour

Adding the custom suffix results in it being rendered in the HTML output

### Steps to reproduce

1. In config, ensure you have the following enabled under markdown_extensions:
```
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
```
2. Add `:fontawesome-brands-twitter:{ .twitter }` to one of you markdown pages
3. Go to the page and observe that the twitter icon is followed by text `{ .twitter }`

### Package versions

- Python: 3.10.4
- MkDocs: 1.3.0
- Material: 8.2.8

### Configuration

```yaml
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
```

### System information

- Operating system: Windows
- Browser: Edge
