### ISSUE TITLE
Table of Content is NOT generated when the feature navigation.indexes is enabled

### ISSUE THREAD

**Issue by vuquangtrong** [squidfunk/mkdocs-material#3819]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Table of Content is not generated in the left-side expandable navigation bar when the feature `navigation.indexes` is enabled.

### Expected behaviour

The ToC with headers should be shown:
![image](https://user-images.githubusercontent.com/843536/163675601-aab7569d-d204-43cd-bf8c-499f30709928.png)

### Actual behaviour

There is no Table of Content list generated:
![image](https://user-images.githubusercontent.com/843536/163675630-06873c1c-bb02-44b5-8b96-1136bfa9d82e.png)

### Steps to reproduce

1. Start new python folder and install `mkdocs-material`
2. Set up new mkdocs projects and use minial config file:
    ``` yaml
    site_name: My Docs
    theme:
      name: material
      features:
        - navigation.indexes
    ```
3. Create a new page, e.g. `docs/blog/topic/index.md` and use some headers 
4. Run the project and go to see preview
5. Change the browser view to a smaller size to activate mobile view
6. Go through the navigation bar to see that the table of content does not appear

### Package versions

- Python: 3.10.0
- MkDocs:  .3.0
- Material: 8.2.9

### Configuration

```yaml
site_name: My Docs
theme:
  name: material
  features:
    - navigation.indexes
```

### System information

- Operating system: MS Windows 10 21H2 OS build 19044.1586
- Browser:  MS Edge 100.0.1185.44 (Official build) (64-bit)
