### ISSUE TITLE
Mermaid Pie Chart Broken

### ISSUE THREAD

**Issue by OmarTawfik** [squidfunk/mkdocs-material#3827]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I was looking into using pie charts with the native mermaid support. I identified the following issues with the current implementation:

1. Legend text does not have the correct font or color, which makes it almost invisible when using custom colors.

I investigated a little bit, and it looks to me we can easily fix it by adding the following lines to `src/assets/javascripts/components/content/code/mermaid/index.css`:

```css
/* ----------------------------------------------------------------------------
 * Rules: pie  charts
 * ------------------------------------------------------------------------- */

/* Legend */
.legend > text {
  font-family: var(--md-mermaid-font-family);
  fill: var(--md-mermaid-label-fg-color);
}
```

2. The pie chart size is not responsive, as it actually renders smaller on wider screens, and larger on smaller screens.

I looked into it, and I'm not sure where the problem is. I'm happy to send a PR to add the missing support, but any pointers would be appreciated.

### Expected behaviour

1. It would scale linearly with the width of the content, instead of the opposite.
2. It should have no relationship with the full page width. As it keeps getting smaller, even when we reach the maximum content width.

### Actual behaviour

The pie chart size is not responsive, as it actually renders smaller on wider screens, and larger on smaller screens.

### Steps to reproduce

Using the following code:

```mermaid
%%{
   init: {
      'themeVariables': {
         'pie1': '#00944f',
         'pie2': '#ff9c07'
      }
   }
}%%
pie
   "Green Part" : 70
   "Orange Part" :  30
```

For large screens, it renders really small:

![image](https://user-images.githubusercontent.com/15987992/164478931-8ce2e81e-4f4f-4d9f-8e21-2e532c40ba0a.png)

For small screens, it renders much larger:

![image](https://user-images.githubusercontent.com/15987992/164479146-57d213a2-dee5-4e87-9de9-f3ef3f73a880.png)

### Package versions

- Python: `3.8.9`
- MkDocs: `1.3.0`
- Material: Commit 3dfa984248e32bb4c0dd12706435f4adc8ccca36 from master

### Configuration

```yaml
Material's base configuration on master.
```

### System information

- Operating system: MacOS (latest)
- Browser: Chrome (latest)
