### ISSUE TITLE
"#" + number renders a link to an issue in this repo

### ISSUE THREAD

**Issue by Vegebutcher** [squidfunk/mkdocs-material#3830]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When I use something like `in step #5`, the `#5` part is rendered as a hyperlink to `https://github.com/squidfunk/mkdocs-material/issues/#`, where `#` is replaced with the provided number, e.g.: `https://github.com/squidfunk/mkdocs-material/issues/5`:

<img width="711" alt="steps" src="https://user-images.githubusercontent.com/907743/164716076-29d7175e-e782-46f5-90f5-953e7c8ee29a.png">

### Expected behaviour

The `#x` part should be left as it is. I know I can escape it with a backslash, but why does it render into a link to a GH issue?

### Actual behaviour

`step #1` in a MD file = step [#1](https://github.com/squidfunk/mkdocs-material/issues/1) in a rendered page

### Steps to reproduce

1. Use `#1` somewhere in your source MD file.
2. Run mkdocs with material template.
3. Check the rendered page.

### Package versions

- Python: latest
- MkDocs: 1.3.0
- Material: 8.2.9

### Configuration

```yaml
theme:
  name: material
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Lato
    code: Roboto Mono
  favicon: assets/favicon.jpg
  logo: assets/logo.svg

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
```

### System information

- Operating system: macOS Monterey 12.3.1
- Browser: latest Ff, Chrome and Edge
- project deployed on GL Pages

**Comment by squidfunk** [comment]
Thank for reporting. This is sue to the [`pymdownx.magiclink`](https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/) extension, which you have enabled. If you remove the following lines from ` mkdocs.yml`, hash + number will not be converted anymore:

``` yaml
- pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
```
