### ISSUE TITLE
1.7.4 results in broken application*.css and application.*js links

### ISSUE THREAD

**Issue by daviddenton** [squidfunk/mkdocs-material#384]
## Description
We upgraded from 1.7.3 to 1.7.4 and when we regenerated our site, links in the resulting HTML pointed to non-existent CSS and JS files. We're not sure if this is an mkdocs issue or an issue with theme, but we thought we'd start here since it was the theme that we upgraded. 

Specifically, from: https://github.com/http4k/http4k.github.io/blob/c6de2407241e1c57aa6883af7874e6b3389dc151/index.html
```  <link rel="stylesheet" href="./assets/stylesheets/application-acc56dad49.css">```
The generated CSS file has a different fingerprint version:
https://github.com/http4k/http4k.github.io/blob/c6de2407241e1c57aa6883af7874e6b3389dc151/assets/stylesheets/application-769c285a91.css

### Expected behavior
The links to be valid!

### Actual behavior

Broken CSS and JS links (in the browser networking tab)

### Steps to reproduce the bug

1. Build a site with 1.7.3 - use `mkdocs gh-pages`
2. Build the site with 1.7.4 - use `mkdocs gh-pages`

### Package versions

* Python: `python --version` >> Python 2.7.13
* MkDocs: `mkdocs --version` >> mkdocs, version 0.16.3
* Material: `pip show mkdocs-material | grep -E ^Version` >> Version: 1.7.4

### Project configuration

``` yaml
site_name: http4k
site_url: http://www.http4k.org
site_description: Documentation site for the http4k web framework written in Kotlin
site_author: David Denton (@daviddenton), IvanSanchez (@s4nchez)
copyright: 'Copyright &copy; 2017 - David Denton (@daviddenton), IvanSanchez (@s4nchez)'
remote_branch: master
repo_url: https://github.com/http4k/http4k/
theme: 'material'
theme_dir: ./docs/theme
google_analytics: ['UA-69281315-11', 'http4k.org']
markdown_extensions:
  - meta
  - codehilite
extra_css:
  - ./css/site.css
extra:
  palette:
    primary: 'indigo'
    accent: 'blue'
  logo: img/logo_1100x200_white_on_blue_trans.png
edit_uri: edit/master/src/docs/
strict: true
pages:
  - Introduction: index.md
  - Rationale & Concepts: rationale/index.md
  - Installation:  installation/index.md
  - Getting started: quickstart/index.md
  - Developer Guide:
    - Modules:
      - Core: guide/modules/core/index.md
      - Server Backend: guide/modules/servers/index.md
      - HTTP Client: guide/modules/clients/index.md
      - Message Formats: guide/modules/message_formats/index.md
      - Templating: guide/modules/templating/index.md
      - Typesafe Contracts: guide/modules/contracts/index.md
      - AWS: guide/modules/aws/index.md
    - Application Testing: guide/testing/index.md
    - Worked TDD Example:
      - Introduction: guide/example/index.md
      - 1. Building a walking skeleton: guide/example/_1_building_a_walking_skeleton/index.md
      - 2. Adding an endpoint: guide/example/_2_adding_the_first_endpoint/index.md
      - 3. Adding another endpoint: guide/example/_3_adding_the_second_endpoint/index.md
      - 4. An external dependency: guide/example/_4_adding_an_external_dependency/index.md
  - Cookbook:
    - Server as a function: cookbook/server_as_a_function/index.md
    - Client as a function: cookbook/client_as_a_function/index.md
    - Container integration: cookbook/container_integration/index.md
    - Simple routing: cookbook/simple_routing/index.md
    - Nestable routes: cookbook/nestable_routes/index.md
    - Using JSON: cookbook/using_json/index.md
    - Using templates: cookbook/using_templates/index.md
    - Generating data classes from JSON: cookbook/generating_data_classes_from_json/index.md
    - Typesafe HTTP contracts: cookbook/typesafe_http_contracts/index.md
    - Typesafe HTTP requests with lenses: cookbook/typesafe_http_requests_with_lenses/index.md
    - Test driven apps: cookbook/test_driven_apps/index.md
  - Performance: performance/index.md
  - In action: in_action/index.md
  - Changelog: changelog/index.md
  - Contributers' Guide: contributing/index.md
  - Help & Support: support/index.md
```

### System information
Same behaviour on both Linux (travis) and OSX Sierra. All browsers affected
