### ISSUE TITLE
Weird symbols in table of contents

### ISSUE THREAD

**Issue by DimanNe** [squidfunk/mkdocs-material#3848]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [ ] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Here is how table of contents gets rendered for the following md:

```
title: Kubernetes

## **Setup** {>>Intro<<}
```

![image](https://user-images.githubusercontent.com/279056/165141015-e92f03eb-b9a6-4bf4-9a18-168e91b69f46.png)

### Expected behaviour

I would expect table of contents to have this item:
> Setup Intro

### Actual behaviour

Instead it has:
> Setup czjqqkd:0

### Steps to reproduce

See above

### Package versions

- Python: `python --version`: `Python 3.9.5`
- MkDocs: `mkdocs --version`: `mkdocs, version 1.3.0 from /usr/local/lib/python3.9/dist-packages/mkdocs (Python 3.9)`
- Material: `pip show mkdocs-material | grep -E ^Version`: `Version: 8.2.8+insiders.4.12.0`

### Configuration

```yaml
site_name: Internal Docs


theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - content.tabs.link
    - content.code.annotate
  icon:
    admonition:
      # note: octicons/tag-16
      # abstract: octicons/checklist-16
      # info: octicons/info-16
      # tip: octicons/squirrel-16
      # success: octicons/check-16
      # question: octicons/question-16
      # warning: octicons/alert-16
      failure: octicons/x-circle-16
      # danger: octicons/zap-16
      bug: octicons/bug-16
      # example: octicons/beaker-16
      # quote: octicons/quote-16


markdown_extensions:
    - toc:
        permalink: True
    - smarty
    - sane_lists
    - abbr
    - pymdownx.snippets
    - admonition
    - pymdownx.details
    - attr_list
    - md_in_html
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - tables
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.arithmatex:
        generic: true


extra_css:
  - stylesheets/extra.css


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


plugins:
  - offline
```

### System information

- Operating system: docker image with based on ubuntu:
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 21.04
Release:        21.04
Codename:       hirsute
```
- Browser: Google Chrome | 101.0.4951.41 (Official Build) beta (64-bit)
