### ISSUE TITLE
Annotation: Annotations cannot be enabled anyway

### ISSUE THREAD

**Issue by sakurayun** [squidfunk/mkdocs-material#3859]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Annotations cannot be enabled anyway
Even if all settings are cleared, only the following are retained:
```
site_name: Vup Live Wiki
theme:
  name: material
  language: 'zh'
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
```
It still doesn't work!

### Expected behaviour

It should work normally!
![image](https://user-images.githubusercontent.com/30366696/165879786-86859a69-6756-44ba-9939-543aabddf2af.png)

### Actual behaviour

But his actual situation is as follows:
![image](https://user-images.githubusercontent.com/30366696/165879855-736a80d0-2b1d-4df7-9505-cad34328c10b.png)

### Steps to reproduce

```
site_name: Vup Live Wiki
theme:
  name: material
  language: 'zh'
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
```

### Package versions

- Python: `python --version`
- MkDocs: `mkdocs --version`
- Material: `pip show mkdocs-material | grep -E ^Version`

### Configuration

```yaml
site_name: Vup Live Wiki
theme:
  name: material
  language: 'zh'
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
```

### System information

- Operating system: Debian 11
- Browser: ...
