### ISSUE TITLE
Search index for gh_pages not updating

### ISSUE THREAD

**Issue by jicowan** [squidfunk/mkdocs-material#3861]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

I am hosting mkdocs/material theme on GitHub. The search index no longer is being updated. When I type a search in the search bar, it only returns results for old content. None of the new content appears in the search results. 

### Expected behaviour

I would expect the index to be update with each rebuild of the documentation. 

### Actual behaviour

No search results appear in the search bar results

### Steps to reproduce

1. Update content
2. Publish content
3. Search content

### Package versions

Using image squidfunk/mkdocs-material:8.2.6 to build docs

### Configuration

```yaml
site_name: EKS Best Practices Guides
repo_url: "https://github.com/aws/aws-eks-best-practices"
docs_dir: "content"
theme: 
  name: material
  icon: 
    repo: fontawesome/brands/github
  features: 
    - tabs
nav:
  - Guides: 
    - Introduction: 'index.md'
  ...
markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - codehilite
plugins: 
    - search
        indexing: 'full'
extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX
```

### System information

- Operating system: OSX
- Browser: Chrome
