### ISSUE TITLE
[Bug] tabs get nested

### ISSUE THREAD

**Issue by Realvincentyuan** [squidfunk/mkdocs-material#3880]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [ ] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Below code can render tabbed content, but the tabs will stay on one line, if the list of tabs is very long, and users click the last a few tabs, it does not allow to scroll back.

```
=== "C"

    ``` c
    #include <stdio.h>

    int main(void) {
      printf("Hello world!\n");
      return 0;
    }
    ```

=== "C++"

    ``` c++
    #include <iostream>

    int main(void) {
      std::cout << "Hello world!" << std::endl;
      return 0;
    }
    ```

```

### Expected behaviour

I recalled in the prior versions, the tab list is not folded in one line, meaning they will all be listed, so that uses can click wherever they want to go. I think this is a good idea.

### Actual behaviour

Tabs stay on one line, if the list of tabs is very long, and users click the last a few tabs, it does not allow to scroll back.

### Steps to reproduce

1. Create long tabbed content, say 10 tabs
2. Click the last a few tabs
3. It cannot scroll back to the first a few tabs

### Package versions

- Python: 3.6.9
- MkDocs: 1.3.0
- Material: 8.2.8

### Configuration

```yaml
Only relevant configs are pasted: 
 
 - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
```

### System information

- Operating system: Win10
- Browser: chrome
