### ISSUE TITLE
Grid cards won't work

### ISSUE THREAD

**Issue by YunfeiZHAO** [squidfunk/mkdocs-material#3887]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

I followed document to install material.
<img width="409" alt="Capture" src="https://user-images.githubusercontent.com/27081428/166969321-8f1ef2b0-5d15-4b44-b148-f8bbc950609a.PNG">

### Expected behaviour

expected to show blocks

### Actual behaviour

just a list of items

### Steps to reproduce

just test the document

### Package versions

- Python:3.9.7
- MkDocs: 1.3.0
- Material: 8.2.13

### Configuration

```yaml
site_name: Yunfei's Workplaces
docs_dir: source
site_dir: docs
site_url: https://yunfeizhao.github.io/

theme:
  name: material
  feature:
    tabs: true
    
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
```

### System information

- Operating system: wsl2 
- Browser: chrome
