### ISSUE TITLE
Feature: Display full article path in search results

### ISSUE THREAD

**Issue by lupupitkanen** [squidfunk/mkdocs-material#389]
## Description

In large MkDocs sites there could be multiple pages with similar title residing under different navigation paths or sections. It is difficult to see from the search results in which section the particular article is located in.

### Expected behavior

Search results should display the full navigation path to the pages just like in the header of the website, for example:

- My First Section / My Page
- My Second Section / My Page

This could be an optional configurable feature, toggled on or off.

### Actual behavior

Only title is displayed in the search results:

- My Page
- My Page

### Steps to reproduce the bug

1. Search for a term which appreas in multiple pages with similar name
2. Multiple pages with same title appear in the search results with no apparent clue in which section the page resides

### Package versions

* Python: `2.7.5`
* MkDocs: `0.16.3`
* Material: `1.6.4`

### Project configuration

``` yaml
site_name: My Test Docs
site_description: Test documentation
copyright: 'Copyright &copy; 2017 My Company'
theme: material
repo_url: https://git.mytestcompany.com/tech/docs
edit_uri: edit/master/docs/
site_favicon: 'img/favicon.ico'
theme_dir: 'theme'
markdown_extensions:
   - admonition
   - codehilite:
       linenums: False
       guess_lang: True
       pygments_style: 'native'
       noclasses: True
   - toc:
       permalink: True
       separator: "_"
extra:
  feature:
    tabs: true
  logo: 'img/logo.png'
  palette:
    primary: 'light blue'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
pages:
- 'Start': 'index.md'
- 'FAQ': 'faq.md'
- My First Section:
    - 'My Page': 'section1/mypage.md'
    - 'Some Page': 'section1/somepage.md'
- My Second Section:
    - 'My Page': 'section2/mypage.md'
    - 'Other Page': 'section2/otherpage.md'
```

### System information

* OS: not relevant
* Browser: not relevant
