### ISSUE TITLE
[Insiders] Light (default) theme styles override (extra css) are by-passed

### ISSUE THREAD

**Issue by jmaneyrol69** [squidfunk/mkdocs-material#3904]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I am not sure whether this is a bug, but there seems to be a slight change with CSS in Insiders compared with mainstream: any style overriding for the default (light theme), such as `--md-primary-fg-color`, are ignored if user follow the documentation (https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors).

So far, we have been using the following rules in our custom CSS:

```css
:root {
  --md-primary-fg-color: #e6195e;
  --md-primary-fg-color--light: #ecb7b7;
  --md-primary-fg-color--dark: #fb005f;
  --md-accent-fg-color: #a11242;
  --md-header-bg-color: #ffffff;
...
```

and it is working with the latest mainstream material for mkdocs (8.2.14), but after switching to Insiders, this is ignored. After having a look at the code, I have noticed that our custom CSS is overruled by a selector named `:root [data-md-color-scheme="default"]`

So, I tried to use the following in our CSS :

```css
[data-md-color-scheme="default"] {
  --md-primary-fg-color: #e6195e;
  --md-primary-fg-color--light: #ecb7b7;
  --md-primary-fg-color--dark: #fb005f;
  --md-accent-fg-color: #a11242;
  --md-header-bg-color: #ffffff;
...
```

And it worked.

### Expected behaviour

Either switch back to the old behavior or document the change with a note in the documentation?

### Actual behaviour

See description

### Steps to reproduce

Use a custom CSS and change the default (light) theme color variables. For example:

```css
:root {
  --md-primary-fg-color: #e6195e;
  --md-primary-fg-color--light: #ecb7b7;
  --md-primary-fg-color--dark: #fb005f;
  --md-accent-fg-color: #a11242;
  --md-header-bg-color: #ffffff;
}
```

### Package versions

- Python: 3.8.10
- MkDocs: 1.3.0
- Material: 8.2.13+insiders.4.13.2

### Configuration

```yaml
site_name: Device image User Guide
site_url: https://docs.genymotion.com/paas/

plugins:
  - search

theme:
  name: material
  custom_dir: overrides/
  font:
    text: Lato
    code: Roboto Mono
  favicon: assets/favicon.png
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-6
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-6
        name: Switch to light mode
  logo: assets/icon-logo-device-image.png
  features:
    - navigation.top
    - navigation.indexes
    - navigation.tabs
    - navigation.sections

nav:
  - Home:
    - Home: 'index.md'
  - Get Started:
    - Requirements: '01_Requirements.md'
    - Quick Start:
      - '02_Getting_Started/index.md'
      - '02_Getting_Started/021_AWS.md'
      - '02_Getting_Started/022_GCP.md'
      - '02_Getting_Started/023_Alibaba.md'
      - '02_Getting_Started/024_Azure.md'
      - '02_Getting_Started/025_Oracle.md'
    - Advanced:
      - Create Pre-configured Images: '06_Create_preconfigured_images.md'
      - Root access: '10_Using_root_access.md'
  - Basic Steps:
    - Accessing Instances:
      - Accessing Instances: 'Access/index.md'
      - 'Access/Change_auth.md'
      - 'Access/Certificate.md'
      - Connect to ADB: 'Access/04_ADB.md'
      - SSH: 'Access/SSH.md'
      - PuTTY: 'Access/Putty.md'
      - Private or NAT Network: 'Access/040_Accessing_a_virtual_device_from_an_enterprise_network.md'
    - Deploying Applications: '041_Installing_applications.md'  
  - Features:
    - Emulated Features and Sensors: '042_Emulated_sensors.md'
    - Share and Embed an instance: '051_Share.md'
    - Other Features: '05_Other_features.md'
    - External Storage:
      - '05_External_storage/index.md'
      - '05_External_storage/0501_External_sd_AWS.md'
      - '05_External_storage/0502_External_sd_GCP.md'
      - '05_External_storage/0503_External_sd_Alibaba.md'
      - '05_External_storage/0504_External_sd_Azure.md'
      - '05_External_storage/0505_External_sd_Oracle.md'
    - Data Backup: '061_Data_backup.md'
  - Automate instance parameters:
    - User data Parameters: 'Userdatas/userdata.md'
    - 'Userdatas/usage.md'
  - APIs and CI:
    - Genymotion HTTP API: '07_Genymotion_HTTP_API.md'
    - Genymotion Java API: '08_Genymotion_Java_API.md'
    - Running Tests with Appium: '09_Appium.md'
  - Help and other information:
    - Technical Support: '12_Support.md'
    - Open-source Licenses: '11_Getting_list_open_source_licenses.md'

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - attr_list
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.tilde

copyright: "&copy; Genymobile 2014 - 2022. All Rights Reserved | Created with ❤️ in Paris and Lyon"

extra_css:
  - stylesheets/paas.css

extra_javascript:
  - javascripts/external_links.js
  - javascripts/theme_sync.js

extra:
  analytics:
    provider: google
    property: UA-25570812-5
```

### System information

- Operating system: Ubuntu 20.04LTS
- Browser: Mozilla Firefox, Google Chrome, Chromium

**Comment by squidfunk** [comment]
Thanks for reporting! Indeed, the semantics are a little different between Insiders and the community edition due to some recent changes, mainly for the landing page, so I checked how CSS variables can be safely set in both editions:

``` css
:root > * {
  --md-primary-fg-color: #e6195e;
  --md-primary-fg-color--light: #ecb7b7;
  --md-primary-fg-color--dark: #fb005f;
  --md-accent-fg-color: #a11242;
  --md-header-bg-color: #ffffff;
}
```

I've updated the documentation to reflect the change in behavior in 770b1b908.
