### ISSUE TITLE
Tabbed Panes - Use index rather than first

### ISSUE THREAD

**Issue by warmfusion** [squidfunk/mkdocs-material#391]
## Feature/Bug - Tabbed panes should goto index.md if exists

I've enabled tabs on my documentation site, but the tabs goto the first (alpha sorted) subpage within the group, however, i have an index.md in those sub-directories and I'd have expected the pane window to open that page instead.
### Steps to reproduce the bug

```
mkdir -p docs/foo
echo "This is selected on the foo section" > docs/foo/about.md
echo "But this should be selected with priority" > docs/foo/index.md
echo "I'm a homepage" > docs/index.md
```

### Package versions

* Python: 3.4
* MkDocs: `mkdocs, version 0.16.3`
* Material: `Version: 1.7.4`

### Project configuration

``` yaml
# http://www.mkdocs.org/

site_name: My Site Title
site_description: My Site Description
site_author: @warmfusion

repo_url: https://REDACTED
repo_name: 'REDACTED'

#-------------------
# The following configuration is not required for an mkdocs site, but is included
# here as it adds some nice features to the `material` theme we're using
#-------------------
markdown_extensions:
  - codehilite
  - admonition
  - toc(permalink=true)
  - footnotes
  - pymdownx.emoji: # https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#emoji
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.tilde
  - pymdownx.tasklist

theme: material

extra:
  feature:
    tabs: true


# This makes the mermaid-js stuff work
# see docs/engineering/about/advanced_features.md for information and examples
extra_css:
  - https://unpkg.com/mermaid@7.0.3/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@7.0.3/dist/mermaid.min.js

```

### System information

* OS: docker container with python:3.4
