### ISSUE TITLE
Chinese search support: Improve query segmentation

### ISSUE THREAD

**Issue by justinliu1985** [squidfunk/mkdocs-material#3915]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Using the new search plugin,  there are a lot of omissions in Chinese results, and the highlight includes irrelevant content.

### Expected behaviour

Fix Chinese segmentation bug

### Actual behaviour

I add the code below，entering the chinese keywords “起诉”，and find only10+ results, also the  entire paragraph where the keyword is located is highlighted.
```
plugins:
  - search:
        separator: '[\\s\\u200b\\-]'
```
When I remove the above code , the number of hit results increased to 200+ and highlighting are correct too, but I cannot find any results with keywords more than two Chinese characters.

### Steps to reproduce

1. clone the insiders repo to local folder
2. enter into the folder and pip install -e .
3. mkdocs serve 
4. try search
5. modify the parameters and search again

### Package versions

- Python: 3.9
- MkDocs: 1.3.0
- mkdocs-material: 8.2.14+insiders.4.15.0

### Configuration

```yaml
site_name: DIGLAWS
site_url: https://example.com/
theme: 
  name: material
  language: zh
  logo: assets/logo.png
  features:
    - navigation.instant
    - navigation.tabs
    - toc.follow
    - navigation.top
markdown_extensions:
  - toc:
      toc_depth: 6
plugins:
  - search:
        separator: '[\\s\\u200b\\-]'
  - awesome-pages
```

### System information

- win10
- edge
