### ISSUE TITLE
disqus integration issue

### ISSUE THREAD

**Issue by rcnotebook** [squidfunk/mkdocs-material#394]
## Description

I'm trying to set up a github blog using the mkdocs-material, but don't seem to be able to get disqus working with it. I've tried both with and without cloning the squidfunk/mkdocs-material repository and pointing the mkdocs.yml file appropriately.

Here's my site: https://rcnotebook.github.io/testblog/
The mkdocs.yml file is [here](https://github.com/rcnotebook/testblog/blob/master/mkdocs.yml) and shown below.

### Expected behavior
I was expecting to see a "Comments" section added to the table of contents as explained [here](http://squidfunk.github.io/mkdocs-material/getting-started/#disqus-integation).

### Actual behavior
I don't see the Comments section.

### Steps to reproduce the bug
Not sure, but I've left the repo as is after my last attempt at fixing this.
Any suggestions to fix this is greatly appreciated!

### Package versions

* Python: `python --version`
```
Python 3.6.1 :: Continuum Analytics, Inc.
```
* MkDocs: `mkdocs --version`
```
mkdocs, version 0.16.3
```
* Material: `pip show mkdocs-material | grep -E ^Version`
```
Version: 1.7.4
```
### Project configuration

``` yaml
# Project information
site_name: 'Blog Test'
site_description: 'Test blog with mkdocs material theme'
site_author: 'RC'
site_url: 'https://rcnotebook.github.io/testblog/'

# Repository
repo_name: 'rcnotebook/testblog'
repo_url: 'https://github.com/rcnotebook/testblog'

# Copyright
copyright: 'Copyright &copy; 2017 RC'

# Documentation and theme
theme: 'material'
#theme_dir: 'mkdocs-material/material'

# Options
extra:
#  logo: 'images/logo.svg'
  palette:
    primary: 'red'
    accent: 'orange'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/rcnotebook'
#    - type: 'twitter'
#      link: 'https://twitter.com/john-doe'
#    - type: 'linkedin'
#      link: 'https://de.linkedin.com/in/john-doe'
  disqus: 'rctestblog'

# Google Analytics
#google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
```

### My Disqus settings:
![image](https://user-images.githubusercontent.com/29688554/28251223-aa6029c8-6a46-11e7-81cc-200ad089a8ad.png)

### System information

* OS: Windows 10
* Browser: Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by squidfunk** [comment]
See #371 - this has most likely to do with your setup.

**Comment by rcnotebook** [comment]
Thanks for the response. My issue here was different from #371.

When I include the html below at the location where I want the comments, the commenting feature shows up. However, this doesn't add the "Comments" link to the table of contents.

I was under the impression that this was automatically taken care of by `mkdocs build` and `mkdocs gh-deploy`.
Was I mistaken or am I still implementing this incorrectly?
Thanks!

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = https://rcnotebook.github.io/testblog/;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = rctestblog; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://rctestblog.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

**Comment by squidfunk** [comment]
How is the HTML you insert manually different than what the Material theme inserts when you specify the `extra.disqus` variable?

**Comment by rcnotebook** [comment]
I removed the above HTML from my `index.md` file to compare what the HTML generated by mkdocs looks like. Although I have the following in my `mkdocs.yml`, the Material theme doesn't seem to be inserting the above HTML automatically.
```
extra:
#  logo: 'images/logo.svg'
  palette:
    primary: 'red'
    accent: 'orange'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/rcnotebook'
  disqus: 'rctestblog'
```
Please let me know if you need me to try anything else...
