### ISSUE TITLE
To much Space around mermaid diagrams

### ISSUE THREAD

**Issue by mhubig** [squidfunk/mkdocs-material#3947]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The is too much space around mermaid diagrams.

<img width="828" alt="Bildschirmfoto 2022-05-24 um 12 53 12" src="https://user-images.githubusercontent.com/219704/170018838-531c12b4-aa35-4c2d-8780-abd0a3ba26c2.png">

### Expected behaviour

There should be no more space around mermaid diagrams than around regular images or code blocks.

### Actual behaviour

Too much space around the diagrams.

### Steps to reproduce

````md
# Test

```mermaid
sequenceDiagram
    participant Client Service
    participant Authorisation Server
    participant API Gateway
    participant Ressource Service
    autonumber

    Client Service->>+Authorisation Server: Authenticate with Client ID + Client Secret to /token;
    Authorisation Server->>-Authorisation Server: Validate Client ID + Client Secret;
    Authorisation Server->>+Client Service: Access token;
    Client Service->>+API Gateway: Requests protected resource route with access token;
    API Gateway->>-API Gateway: Validates access token signature;
    API Gateway->>+Ressource Service: Requests protected resource with client access token;
    Ressource Service->>-Ressource Service: Validates access token signature;
    Ressource Service->>+API Gateway: Protected resource response;
    API Gateway->>+Client Service: Forwards protected resource response;
```
````

### Package versions

- Python: `3.9.12`
- MkDocs: `1.3.0`
- Material: `8.2.15`

### Configuration

```yaml
site_name: test
site_dir: public
theme:
  name: material
nav:
  - api-gateway.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
```

### System information

- Operating system: macOS
- Browser: Safari
