### ISSUE TITLE
"Initializing search" appears repeatedly even with navigation.instant

### ISSUE THREAD

**Issue by ms2art** [squidfunk/mkdocs-material#3951]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Each time I navigate to a new page in my documentation and then click Search, "Initializing search" appears below the search field. The string displays for a longer time as the number of words in the documentation increases.

### Expected behaviour

Each time I navigate to a new page in my documentation and then click Search, "Type to start searching" should appear immediately. I can accept initialization on the first search in my content set, but not on subsequent searches.

### Actual behaviour

Each time I navigate to a new page in my documentation and then click Search, "Initializing search" appears below the search field. The string displays for a longer time as the number of words in the documentation increases.

### Steps to reproduce

1. Create a content set.
2. Build the content.
3. View a topic in a server (for example, "Open with Live Server" in Visual Studio Code).
4. Click in the Search field.
5. Time the persistence of the "Initializing Search" message.
6. View another topic and repeat steps 4 and 5.
7. Add more topics and repeat steps 1 through 6.

Note that I created several very long topics in order to get the problem to appear. My actual topics would never be as long as these samples, but I have over 7,000 topics in my content set, so I think my sample topics are a fair test.  

[initializing-search.zip](https://github.com/squidfunk/mkdocs-material/files/8772285/initializing-search.zip)

### Package versions

- Python: Python 3.10.2
- MkDocs: version 1.2.3
- Material:  8.1.11

### Configuration

```yaml
site_name: My site

theme:
  name: material
  features:
    - navigation.instant

plugins:
  - search
  
nav:
    - My Product Documentation:
      - Topic One: topic_1.md
      - Topic Two: topic_2.md
      - Topic Three: topic_3.md
      - Topic Four: topic_4.md
      - Topic Five: topic_5.md
```

### System information

Windows 10
Firefox 100.0.2 (64-bit), Chrome 102.0.5005.62 (Official Build) (32-bit)
