### ISSUE TITLE
Items in the left sidebar are being decomposed (NFD or NFKD)

### ISSUE THREAD

**Issue by bcdavasconcelos** [squidfunk/mkdocs-material#3960]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hi, thanks for making this beautiful template available.

It seems that some items are going through a canonical (or non-canonical) decomposition **in the left sidebar only**. This, in turn, causes font rendering issues.

<img width="879" alt="image" src="https://user-images.githubusercontent.com/35749099/170804082-bf15a9ab-68c3-4794-918b-031231b24ddb.png">

<img width="1369" alt="image" src="https://user-images.githubusercontent.com/35749099/170804087-f45f4c6f-6b89-48e4-aca7-3827460408ea.png">

### Expected behaviour

All items are treated equally with some control over the normalization of strings.

### Actual behaviour

Strings with diacritical marks are being decomposed.

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/35749099/170804148-b449a5cf-9038-41d4-8bc7-f5387fdacfe5.png">

### Steps to reproduce

Insert page name with diacritical marks (e.g. `áéíóúàèìòùçãõ`) to the topmost position in the sidebar.

### Package versions

- Python: `Python 3.9.6`
- MkDocs: `mkdocs, version 1.3.0`
- Material: `Version: 8.2.15`

### Configuration

```yaml
site_name: xxxx
copyright: xxx
site_description: >-
  lorem

repo_name: bcdavasconcelos/gdct_mkdocs
repo_url: https://github.com/bcdavasconcelos/gdct_mkdocs
edit_uri: edit/main/docs/
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  language: pt-BR
  font:
    text: Alegreya # /setup/changing-the-fonts/
    code: Inconsolata
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.tabs
  - navigation.indexes
  - navigation.top
  - content.code.annotate
  - content.tooltips
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  - content.tabs.link
  - header.autohide

plugins:
  - roamlinks
  - git-revision-date-localized:
      type: iso_date
      locale: pt
      timezone: America/Sao_Paulo
  - search:
      lang: pt
  - tags:
      tags_file: tags.md
  - minify:
     minify_html: true
  - redirects:
      redirect_maps:
        reference/abbreviations.md: reference/tooltips.md
        reference/meta-tags.md: reference/index.md

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: bcdavasconcelos
      repo: gdct_mkdocs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {normalize: NFC, case: lower, percent_encode: false}}
      separator: "-"
nav:
  - Home: README.md
  - GDCT:
    - Referências:
      - bib-refs/README.md
```

### System information

- Operating system: macOS 12.3
- Browser: Safari 15.4
