### ISSUE TITLE
Improve Accessibility

### ISSUE THREAD

**Issue by JoeUser78** [squidfunk/mkdocs-material#4006]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The theme needs some improvements to make it (more) accessible to all.

### Expected behaviour

No errors or alerts in at least the https://wave.webaim.org/ accessibility validotor.

### Actual behaviour

See for example https://wave.webaim.org/report#/https://squidfunk.github.io/mkdocs-material/getting-started/

### Steps to reproduce

Install and configure the theme as officially documented.
Create some docs and nested navs.
Run the published site through https://wave.webaim.org/

### Package versions

- Python: 3.8.13
- MkDocs: 1.3.0
- Material: 8.3.3

### Configuration

```yaml
site_name: FooBar
site_url: https://www.example.com/
site_description: Some describtion
copyright: Copyright © 2022 FooBar

theme:
    name: null
    locale: de
    language: de
    custom_dir: theme/material
    static_templates:
        - 404.html
    include_search_page: false
    search_index_only: true
    icon:
        logo: material/book-open-page-variant
        repo: fontawesome/brands/github
    favicon: assets/favicons
    palette:
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: amber
          accent: indigo
          toggle:
            icon: material/weather-sunny
            name: Switch to light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: amber
          accent: indigo
          toggle:
            icon: material/weather-night
            name: Switch to dark mode
    font:
        text: Roboto
        code: Roboto Mono
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.indexes
        - navigation.sections
        - navigation.top

extra:

plugins:
    - search:
        lang:
            - de

markdown_extensions:
    - markdown.extensions.abbr:
    - markdown.extensions.admonition:
    - markdown.extensions.attr_list:
    - markdown.extensions.def_list:
    - markdown.extensions.footnotes:
    - markdown.extensions.meta:
    - markdown.extensions.md_in_html:
    - markdown.extensions.smarty:
        smart_quotes: false
    - markdown.extensions.tables:
    - markdown.extensions.toc:
        permalink: true
        permalink_title: Anchor link to this section for reference
        slugify: !!python/name:pymdownx.slugs.uslugify
        toc_depth: 3
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret:
    - pymdownx.mark:
    - pymdownx.tilde:
    - pymdownx.details:
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight:
        use_pygments: true
        auto_title: true
        linenums: true
        linenums_style: pymdownx-inline
    - pymdownx.inlinehilite:
    - pymdownx.superfences:
        preserve_tabs: true
    - pymdownx.keys:
        separator: "\uff0b"
    - pymdownx.smartsymbols:
    - pymdownx.snippets:
        base_path:
            - docs/.snippets
        check_paths: true
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.magiclink:
    - pymdownx.saneheaders:
    - pymdownx.striphtml:

nav:
    - Home: 'index.md'
    - Category 1:
        - 'cat_1/doc_1.md'
        - Subcategory 1:
            - 'cat_1/sub_1/doc_1.md'
        - Subcategory 2:
            - 'cat_1/sub_2/doc_2.md'
        - Subcategory 3:
            - 'cat_1/sub_3/doc_3.md'
            - SubSubcategory 3:
                - 'cat_1/sub_3/sub_3/doc_3.md'
    - Category 2:
        - 'cat_2/doc_1.md'
        - Subcategory 1:
            - 'cat_2/sub_1/doc_1.md'
        - Subcategory 2:
            - 'cat_2/sub_2/doc_2.md'
        - Subcategory 3:
            - 'cat_2/sub_3/doc_3.md'
            - SubSubcategory 3:
                - 'cat_2/sub_3/sub_3/doc_3.md'
    - About:
        - 'about/terms.md'
        - 'about/privacy.md'
    - 'about/imprint.md'
```

### System information

- Operating system: FreeBSD 13.1
- Browser: Firefox, Chrome
