### ISSUE TITLE
Admonitions inside content tabs

### ISSUE THREAD

**Issue by kulttuuri** [squidfunk/mkdocs-material#4025]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hi!

I'm trying to add admonition inside a content tab, but that doesn't seem to work that way around. I have tried with collapsible and non-collapsible admonitions. I've tried for example this:

```
=== "View All Elements"
      ```py
      print("Hello World")
      ```
      
      ???+ example "Example Output"
          > Hello World
```

### Expected behaviour

The expected behavior is for the admonition to render correctly.

### Actual behaviour

This is what renders in the browser:
<img width="769" alt="image" src="https://user-images.githubusercontent.com/3810422/173764190-b4af4342-4ed7-4204-b1bc-2c6e67651b9b.png">


### Steps to reproduce

1. Create the block with this code:

```
=== "View All Elements"
      ```py
      print("Hello World")
      ```
      
      ???+ example "Example Output"
          > Hello World
```

2. Does not render correctly.

### Package versions

- Python: 3.9.10
- MkDocs: 1.3.0
- Material: 8.3.5+insiders.4.18.1

### Configuration

```yaml
site_name: Test Site
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
```

### System information

- Operating system: MacOS
- Browser: Chrome
