### ISSUE TITLE
Tooltip doesn't appear on links with ellipsis when inside collapsed nav sections

### ISSUE THREAD

**Issue by wilhelmer** [squidfunk/mkdocs-material#4026]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

https://user-images.githubusercontent.com/2234833/173786194-042af9c3-7664-4cac-b2a4-11faf8368b59.mov

### Expected behaviour

When enabling `content.tooltips`, tooltips should appear on all links that are shortened with ellipsis.

### Actual behaviour

Navigation items that are shortened with ellipsis inside collapsed sections don't have tooltips.

After reloading the page with the section expanded, the tooltip appears. See video.

### Steps to reproduce

See video.

### Package versions

- Python: 3.9.13
- MkDocs: 1.3.0 
- Material: 8.3.4+insiders.4.18.0

### Configuration

```yaml
site_name: Test Project
theme:
    name: material
    features:
        - content.tooltips
use_directory_urls: false
plugins:
  - offline
nav:
  - Welcome: index.md
  - Section:
      - Subsection:
        - VeryVeryVeryVeryVeryVeryLongTopicTile: second.md
```

### System information

- Operating system: macOS Monterey
- Browser: Firefox
