### ISSUE TITLE
Theme toggle is invisible

### ISSUE THREAD

**Issue by savchenko** [squidfunk/mkdocs-material#4033]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

For some wicked reason theme toggle is not displayed when MkDocs Material is built on Windows.
I have suspected caching to be a problem, but re-installation of `mkdocs-material` hasn't helped.
There is nothing suspicious in the Console or Network requests from Dev. Tools.

### Expected behaviour

Toggle is shown.

### Actual behaviour

![image](https://user-images.githubusercontent.com/300146/174472473-d948275e-2fc0-4146-a7d2-14c26a45eb96.png)

### Steps to reproduce

1. Install the following:
    ```
    mkdocs                                    1.3.0
    mkdocs-exclude                            1.0.2
    mkdocs-git-authors-plugin                 0.6.4
    mkdocs-git-revision-date-localized-plugin 1.0.1
    mkdocs-macros-plugin                      0.7.0
    mkdocs-material                           8.3.6+insiders.4.18.2
    mkdocs-material-extensions                1.0.3
    ```
1. Execute `mkdocs.exe serve`

### Package versions

- Python: `Python 3.9.12`
- MkDocs: `mkdocs, version 1.3.0 from C:\Users\user\AppData\Roaming\Python\Python39\site-packages\mkdocs (Python 3.9)`
- Material: `Version: 8.3.6+insiders.4.18.2`

### Configuration

```yaml
site_name: MkDocs sandbox

theme:
  name: material
  theme:
    palette:
      - scheme: default
        primary: indigo
        accent: indigo
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode
      - scheme: slate
        primary: blue
        accent: blue
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
```

### System information

- Operating system: Windows 10 21H2
- Browser: Firefox ESR and MS Edge extended channel branch

**Comment by squidfunk** [comment]
Thanks for reporting. Your configuration is invalid. You double-nested `theme`. Try:

```
site_name: MkDocs sandbox

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
```
