### ISSUE TITLE
Mermaid.js generated SVG pictures with too many blank spaces taking up space.

### ISSUE THREAD

**Issue by huangyinhaow** [squidfunk/mkdocs-material#4068]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

If the block of code for mermaid is so long that it exceeds the height of the SVG that the target is generating, the upper and lower parts of the generated SVG will take up a lot of invalid space.

### Expected behaviour

SVG just happens to appear below the text

### Actual behaviour

![image](https://user-images.githubusercontent.com/64564727/175859490-b3f86486-0f59-4dab-804d-609d1ec223c0.png)

### Steps to reproduce

1. Write a markdown file
2. Insert a long block of mermaid code

### Package versions

- Python: 3.10
- MkDocs: 1.3.0
- Material: 8.3.6

### Configuration

```yaml
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
```

### System information

- Operating system: Windows 11 
- Browser: Edge 102
