### ISSUE TITLE
Potential Bug: ToC names are cut-off if they are too long

### ISSUE THREAD

**Issue by Kigstn** [squidfunk/mkdocs-material#4078]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Entries in the ToC can overflow if they are too long. This results in them being cut off.
![image](https://user-images.githubusercontent.com/38250010/176875483-995c4ab6-95a8-48c1-a803-9511f702dda4.png)
![image](https://user-images.githubusercontent.com/38250010/176875498-1a32d5a2-dedc-4ccb-9b01-8f663ae093da.png)

[See the bug live](https://bungio.readthedocs.io/en/latest/API%20Reference/HTTP/Bungie%20Routes/community_content/)

### Expected behaviour

Either
1) A scroll wheel appears
2) The name is cut-off with dots -> ` CommunityContentRouteHttp...`

Option 2 feels the best from a UX standpoint IMO.

### Actual behaviour

The name is cut-off after the maximum display width is reached, as can be seen in the above screenshots.
The full name is still visible when inspecting the HTML element.
![image](https://user-images.githubusercontent.com/38250010/176875898-2ffc9fbb-68f4-48c2-8c0f-f76c52c5cfcc.png)

### Steps to reproduce

1) Give a class / method / attr a very long name
2) Look at the ToC entry
3) The ToC entry is cut-off

### Package versions

- Python: `3.10.3`
- MkDocs: `1.3.0`
- Material: `8.3.8`

### Configuration

```yaml
site_name: BungIO
repo_url: https://github.com/Kigstn/BungIO
docs_dir: docs/src

theme:
  name: material

plugins:
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          options:
            show_root_toc_entry: false
```

### System information

- Operating system: Win10
- Browser: Firefox 102.0
