### ISSUE TITLE
Documentation errors when entered the build, serve of gh-deploy command

### ISSUE THREAD

**Issue by SyntalDev** [squidfunk/mkdocs-material#4095]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When I run either one of these commands on the material theme, a bunch of errors (as seen below) appear.

![image](https://user-images.githubusercontent.com/99213873/177403745-58c0615a-665d-4077-acbd-b3315c15237f.png)

### Expected behaviour

The website to serve, deploy or build with the material theme

### Actual behaviour

A bunch of errors appear 

### Steps to reproduce

I am not entirely sure how this happened, however for me it only happens when the material theme is selected so I would say, use the material theme in the mkdocs.yml 

![image](https://user-images.githubusercontent.com/99213873/177404267-5311ddbd-dc72-42b1-a4e8-fd3129afe5fd.png)

### Package versions

- Python: `3.10`
- MkDocs: `1.2.3`
- Material: `8.3.9`

### Configuration

```yaml
repo_url: "https://github.com/Uranium-Framework/Uranium-Core"
repo_name: "UraniumFramework/Uranium-Core"
site_name: Uranium Documentation
site_url: https://uranium-framework.github.io/docs/site
copyright: Copyright &copy; 2022 Black Magic Studios and Uranium Development Team



nav:
  - Home: index.md
  - Documentation: 
      - Setup: Documentation/Setup.md
      - Usage: Documentation/Usage.md
      - RESTful API: Documentation/RESTAPI.md
  - API References: 
          - Introduction: API/Introduction.md
          - Server:
              - ProfileService: API/Server/profileService.md
          - Client: 
              - UraniumGUI: 
                   - Icon: API/Client/GUI/icon.md
                   - UI: API/Client/GUI/ui.md
              - Bezier: API/Client/bezier.md

  - Releases: Releases.md

markdown_extensions:
  - abbr
  - admonition
  - meta
  - attr_list
  - md_in_html
  - toc:
      permalink: true
theme: 
  icon:
    admonition:
      <type>: <icon>
  palette:
   scheme: slate
   primary: red
   accent: deep orange
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - toc.follow
  logo: assets/favicon.png
  favicon: assets/favicon.png
plugins:
  - search
```

### System information

- Operating system: Linux Ubuntu(I have also tested this on Windows, as I run Ubuntu on a vm, however issue still persists)
- Browser: Firefox(Ubuntu) OperaGX(Windows)

**Comment by squidfunk** [comment]
Thanks for reporting.

``` yaml
theme: 
  icon:
    admonition:
      <type>: <icon>
```

[This is not a valid value](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#admonition-icons). The idea is to replace `<type>` with .  valid admonition type and `<icon>` with a valid icon. Try:

``` yaml
theme:
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
```
