### ISSUE TITLE
`tags_extra_files` throws an exception

### ISSUE THREAD

**Issue by SaltyAimbOtter** [squidfunk/mkdocs-material#4114]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The new `tags_extra_files` feature seems to not work at all. An exception is thrown whenever this feature is used. The "old" `tags_file` still works, though.

### Expected behaviour

Tag indexes are rendered on two pages.

### Actual behaviour

This [stacktrace](https://github.com/squidfunk/mkdocs-material/files/9086662/stacktrace.txt) is thrown.

### Steps to reproduce

1. `git clone https://github.com/SaltyAimbOtter/material-mkdocs-tags-bug.git`
2. `mkdocs serve`

### Package versions

- Python: `3.10.0`
- MkDocs: `1.3.0`
- Material: `8.3.9+insiders.4.20.1`

### Configuration

```yaml
site_name: My Docs
theme:
  name: material

plugins:
  - tags:
      tags_extra_files:
        index.md:
          - docs2
        anotherTagsIndex.md:
          - docs1

extra:
  tags:
    docs1: docs1
    docs2: docs2


markdown_extensions:
  - meta
```

### System information

- Operating system: Windows 10
- Browser: Firefox 102
