### ISSUE TITLE
Docker image >8 cannot render tabbed content

### ISSUE THREAD

**Issue by lewis-anderson** [squidfunk/mkdocs-material#4124]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When I try to use [content tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/) when building mkdocs using the docker image, they do not render correctly on any version after 8.0.1.

```shell
> docker run -it -v ${PWD}:/docs --entrypoint /bin/sh  squidfunk/mkdocs-material:7.3.6
> mkdocs build --clean
```

Produces the following results as expected in my test file `./docs/index.md`: 

![Screenshot 2022-07-13 at 11 49 35](https://user-images.githubusercontent.com/61019758/178717512-a7e5e115-0085-4b3e-89c4-ea15532d7442.png)

However when I use 8.0.1 (or any later version of 8+) the following html is rendered:

![Screenshot 2022-07-13 at 12 03 04](https://user-images.githubusercontent.com/61019758/178719077-045982d9-8211-45ed-a078-d29c22ec9597.png)

### Expected behaviour

Expected the tab to render correctly.

### Actual behaviour

Tabs not rendered correctly.

### Steps to reproduce

1. run `docker run -it -v ${PWD}:/docs --entrypoint /bin/sh -e 8000:8000 squidfunk/mkdocs-material:8.3.9`
2. In the container run `mkdocs build --clean`
3. Inspect `index.html` in the browser (I'm using Chrome)

Content of `./docs/index.md`:

```markdown
# Test tabs

=== "Python"

    ```python
    foo = 1
    ```

=== "Web UI"

    Click foo, set to 1.

=== "CLI"

    ```sh
    foo --bar=1
    ```

```

### Package versions

- Python: 3.9.2
- MkDocs: 1.3.0
- Material: 8.3.9

### Configuration

```yaml
site_name: 'My Docs'
site_author: 'Me'
repo_url: 'https://github.com'

theme:
  name: 'material'
  favicon: "assets/logo.png"
  logo: "assets/logo_white.png"
  palette:
    primary: 'blue'
    accent: 'deep-orange'
  features:
    - content.tabs.link


# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
         - name: mermaid
           class: mermaid
           format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
```

### System information

- Operating system: Using Docker image - Alpine Linux Base
- Browser: Chrome
