### ISSUE TITLE
Error with markdown_extensions after installing updates

### ISSUE THREAD

**Issue by SilentGlasses** [squidfunk/mkdocs-material#4129]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Trying to build my local site after recent update and get configuration errors.

### Expected behaviour

Site should build normally with no issues.

### Actual behaviour

After installing latest updates, I am now getting this error:

```
mkdocs serve
INFO     -  Building documentation...
ERROR    -  Config value: 'markdown_extensions'. Error: Failed loading extension "fontawesome_markdown".
Aborted with 1 Configuration Errors!
```

### Steps to reproduce

1. installed latest versions of mkdocs, mkdocs-material and plugins
2. Tried to launch site and now am getting errors

### Package versions

- Python: `python --version`
- Python 3.10.5
- MkDocs: `mkdocs --version`
- mkdocs, version 1.3.0 from /usr/local/lib/python3.10/site-packages/mkdocs (Python 3.10)
- Material: `pip show mkdocs-material | grep -E ^Version`
- Version: 8.3.9

### Configuration

```yaml
# Project information
site_name: Site Name
site_description: Documentation for Team ABC
site_url: internal_url
repo_url: internal_url

# Navigation
nav:
  - Home: index.md

# ↓↓ ---------------- DO NOT EDIT ANYTHING BELOW THIS LINE ---------------- ↓↓ #
# ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓ #

theme:
  name: 'material'
  custom_dir: docs/overrides
  features:
    - announce.dismiss
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share

  logo: 'images/techops_icon.png'
  favicon: 'images/siteicon.png'
  font:
    text: 'IBM Plex Sans'
    code: 'IBM Plex Mono'

  palette:
    primary: 'blue'
    accent: 'deep orange'
  icon:
    repo: fontawesome/brands/github
extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.js

# Plugins and Extensions
plugins:
  - search
  - autolinks
  - git-revision-date-localized:
      type: timeago
      locale: en
      fallback_to_build_date: true
      exclude:
        - index.md
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - codehilite:
      guess_lang: true
      use_pygments: true
  - def_list
  - fontawesome_markdown
  - footnotes
  - markdown_include.include:
      base_path: .
  - md_in_html
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.pathconverter
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: .
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - toc:
      permalink: false
      toc_depth: 4
```

### System information

- Operating system: macOS Monterey 12.4
- Browser: Firefox 102.0.1

Please let me know if you need more information.
