### ISSUE TITLE
Ordered lists don't seem to be processed within admonitions

### ISSUE THREAD

**Issue by EDIflyer** [squidfunk/mkdocs-material#4132]
### Contribution guidelines
- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that...
- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description
Lists don't appear to be properly parsed when occurring within an admonition

### Expected behaviour
Lists to parse as they would outwith an admonition
![image](https://user-images.githubusercontent.com/13610277/179398109-bfc99d93-92b2-4071-ab1a-b85bd22df068.png)

### Actual behaviour
Just appears as plain text
![image](https://user-images.githubusercontent.com/13610277/179398125-282c7caf-3633-4dbe-bd63-4806e87b71fe.png)

### Steps to reproduce
1. Create list in usual way
2. Place within admonition

Example code:
``` markdown
??? abstract "configuration files"
    Remember to change the `username` from default and replace the `password` .
    A number of items need to be replaced in the configuration file:
    1. Set the `jwt_secret` with a 128-bit key (e.g. from https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx)
    1. Set the `default_redirection_url` with the one for this domain
    1. Under `access_control` set the policy for different subdomains
```

### Package versions
(Running latest Docker container)
- Python: `Python 3.9.2`
- MkDocs: `version 1.3.0`
- Material: `Version: 8.3.9`

### Configuration
```yaml
site_name: Test

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    admonition:
      example: fontawesome/solid/file-code
      quote: fontawesome/solid/terminal
      tip: fontawesome/solid/lightbulb

plugins:
  - search
  - git-revision-date-localized:
      type: custom
      custom_format: "%d/%m/%Y %T"
      timezone: Europe/London
      locale: en
      fallback_to_build_date: false
      enable_creation_date: true
      exclude:
          - index.md
      enabled: true
  - glightbox

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo: "linux-notes"
      user: "EDIflyer"
      repo_url_shorthand: true
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
```

### System information
- Operating system: Debian GNU/Linux 11 (bullseye) x86_64
- Browser: Chrome
