### ISSUE TITLE
Feedback Input Hidden by Default

### ISSUE THREAD

**Issue by SudoSpartanDan** [squidfunk/mkdocs-material#4151]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I believe this line is the issue. It's automatically hiding the feedback, regardless of page settings.

https://github.com/squidfunk/mkdocs-material/compare/8.3.9...8.4.0rc1#diff-b79958934dd5a12225ab2f225333d66a850a08bf32a560cfe44288fae02e2cdbR37

### Expected behaviour

Feedback is visible

### Actual behaviour

Feedback is hidden with no option to show

### Steps to reproduce

1. Add feedback.js to extra javascript
2. Upgrade to newest version
3. Add configuration below
4. View page on site

### Package versions

- Python: `3.9.13`
- MkDocs: `8.4.0rc1`

### Configuration

```yaml
extra:
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target=_blank>feedback form</a>.
```

### System information

- Operating system: Windows
- Browser: Chrome
