### ISSUE TITLE
Recent changes break whole word search

### ISSUE THREAD

**Issue by nebulade** [squidfunk/mkdocs-material#419]
## Description

The latest release (1.7.5) breaks some search patterns for whole words. In this case typing `restor` in the search field correctly shows matches for the whole word `restore` while when the whole word is typed into the search field, the search results are empty.

This can be tested with a small md file with the following contents:
```
## Restore

Apps can be restored to a previous backup by clicking on the `Restore` button.
```
The previous version (1.7.4) does not have this issue.

**Comment by squidfunk** [comment]
This has to do with the default stemming by lunr, fixed in `master` which disabled stemming, and about to be released.

**Comment by nebulade** [comment]
Thats awesome. Thanks!

**Comment by squidfunk** [comment]
Fixed in 1.8.0

**Comment by kevung** [comment]
Hello everybody,
I encounter the same problem as @nebulade  with mkdocs-material-5.2.2. 
Are there other people noticing this regression?

**Comment by kevung** [comment]
The problem I encounter seems to be a problem from Mkdocs-Material.
The search is fully working when the language is in english, but fails in french, for example.

The search is fine with a `mkdocs.yml`:
```
site_name: test

theme:
  language: en
  name: material

plugins:
  - search

use_directory_urls: false
nav:
  - Intro: index.md
```
but does not work with this `mkdocs.yml`
```
site_name: technique/trajectoire

theme:
  language: fr
  name: material

plugins:
  - search

nav:
  - Intro: index.md
```
