### ISSUE TITLE
"Initializing search" message affects search performance; maybe folder structure related?

### ISSUE THREAD

**Issue by ms2art** [squidfunk/mkdocs-material#4199]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

An "Initializing search" message is displaying regularly and frequently, resulting in a poor customer experience.

### Expected behaviour

I should not see the "Initializing search" message when I click each new topic and immediately try to search. I should be able to type a search string immediately and see results.

### Actual behaviour

Each time I click a new topic in my TOC and immediately click in the search field, I see an "Initializing search" message, and cannot search until it disappears.

Note: The attached file set contains only five md files, but, except for index.md, they are all very large. This is deliberate, because search initialization appears to take longer with larger content. The sample files are just large enough to display the unwanted message very briefly (less than a second), so that you can tell when the problem is occurring. My actual file set is much larger--roughly 6 Gb of  HTML--but comprising many much smaller files.

[search-initialization-delay-test-case.zip](https://github.com/squidfunk/mkdocs-material/files/9236542/search-initialization-delay-test-case.zip)

In mkdocs.yml, I have listed a number of working and non-working permutations of folder structures, to try to help isolate the cause. They are all commented out, with brief descriptions of the folder structure before each permutation.

### Steps to reproduce

1. Unzip the attached zip file to a convenient location.
2. Edit mkdocs.yml and uncomment the DEFAULT SCENARIO.
3. Build with mkdocs.yml.
4. Open index.html in a server.
5. Click the search field. (You may not see an "Initializing search" message at this point.)
6. Click another topic in the TOC.
7. Immediately click the search field.
8. Observe that the "Initializing search" message displays briefly.
9. Click other topics, and repeat the search field click each time, to confirm that the message appears each time.
10. Optionally, uncomment other scenarios in mkdocs.yml and modify the location of the test md files accordingly, to test other folder structures.

### Package versions

- Python: Python 3.10.2
- MkDocs: version 1.2.3
- Material: Version: 8.1.11

### Configuration

```yaml
site_name: My site
site_url: http://127.0.0.1:5500/
docs_dir: source
site_dir: docs
use_directory_urls: false
theme:
  name: material
  features:
    - navigation.instant
plugins:
  - section-index
  - search
nav:
   - My Product Documentation:
     - docs/documentation/index.md
     - Topic One: docs/documentation/Foundry/2waysms_quick_start_guide/Content/topic_1.md
     - Topic Two: docs/documentation/Foundry/2waysms_quick_start_guide/Content/topic_2.md
     - Topic Three: docs/documentation/Iris/iris_user_guide/Content/topic_3.md
     - Topic Four: docs/documentation/Iris/iris_user_guide/Content/topic_4.md
```

### System information

- Operating system: Windows 10
- Browser: Firefox 103.0
