### ISSUE TITLE
Error: Config file 'mkdocs.yml' does not exist

### ISSUE THREAD

**Issue by syedshadab19** [squidfunk/mkdocs-material#4234]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

HI I am using the docker version of material for mk docs when I run this docker command **"docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material"** I am getting the below error 

INFO - Building documentation...
Error: Config file 'mkdocs.yml' does not exist.

### Expected behaviour

The Docker of material for mkdocs to run

### Actual behaviour

when I  run **"docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material"** command on linux/ubuntu os you will get below error 

INFO - Building documentation...
Error: Config file 'mkdocs.yml' does not exist.

### Steps to reproduce

Step 1 run **"docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material"** command on linux/ubuntu os you will get below error 

INFO - Building documentation...
Error: Config file 'mkdocs.yml' does not exist.

### Package versions

- Python: `python --version`
- MkDocs: `mkdocs --version`
- Material: `pip show mkdocs-material | grep -E ^Version`

### Configuration

```yaml
site_name: Test CMS Documentation
site_author: TEst 


# Repository
# repo_name: squidfunk/mkdocs-material2
# repo_url: https://github.com/squidfunk/mkdocs-material

# Copyright
# copyright: Copyright &copy; 2016 - 2022 Martin Donath

# Configuration
theme:
  name: null
  custom_dir: !ENV [THEME_DIR, "material"]

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    # - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  icon:
    logo: logo

  #    favicon: assets/favicon.png
  # icon:
  #   logo: logo

# Plugins
plugins:
  - search
  - redirects:
      redirect_maps:
        changelog/insiders.md: insiders/changelog.md
        conventions.md: philosophy.md
        reference/abbreviations.md: reference/tooltips.md
        reference/meta-tags.md: reference/index.md
        reference/variables.md: https://mkdocs-macros-plugin.readthedocs.io/
        sponsorship.md: insiders/index.md
        upgrading.md: upgrade.md
  - minify:
      minify_html: true

# Customization
# extra:
#   analytics:
#     provider: google
#     property: !ENV GOOGLE_ANALYTICS_KEY
  # social:
  #   - icon: fontawesome/brands/github
  #     link: https://github.com/squidfunk
  #   - icon: fontawesome/brands/gitter
  #     link: https://gitter.im/squidfunk/mkdocs-material
  #   - icon: fontawesome/brands/docker
  #     link: https://hub.docker.com/r/squidfunk/mkdocs-material/
  #   - icon: fontawesome/brands/python
  #     link: https://pypi.org/project/mkdocs-material/
  #   - icon: fontawesome/brands/twitter
  #     link: https://twitter.com/squidfunk

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - mdx_truly_sane_lists:
      nested_indent: 2
      truly_sane: True
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
```

### System information

- Operating system: ... Linux/unbuntu
- Browser: ... chrome
