### ISSUE TITLE
navigation.instant breaks rendering of Arithmatex expressions

### ISSUE THREAD

**Issue by PhilippSalvisberg** [squidfunk/mkdocs-material#4246]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When I enable the feature [navigation.instant](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+instant#instant-loading) pages containing arithmatex classes originally expressed via [Arithmatex Markdown input format](https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/#input-format) are not rendered correctly when:

- navigating to the page via navigation menu
- navigating to the page via `n` or `p` keys
- navigating to the page via search result

Rendering works when 

- navigating to the page by entering the complete URL in the browser address bar
- refreshing the page

### Expected behaviour

arithmatex classes should be rendered correctly regardless of the navigation method.

### Actual behaviour

see description.

### Steps to reproduce

1. create a site with at least two pages, page one contains no arithmatex, page two contains at least one arithmatex expression
2. run `mkdoks serve`
3. navigate to page two via key `n` (arthimatex expression is not rendered)
4. reload page (artimatex expression is rendered)

### Package versions

- Python: Python 3.9.7
- MkDocs: mkdocs, version 1.3.1 from /usr/local/lib/python3.9/site-packages/mkdocs (Python 3.9)
- Material: Version: 8.3.9

### Configuration

```yaml
site_name: PL/SQL & SQL Coding Guidelines
site_url: https://trivadis.github.io/plsql-and-sql-coding-guidelines/

repo_name: trivadis/plsql-and-sql-coding-guidelines
theme:
  name: 'material'
  features:
    - navigation.instant

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
  - pymdownx.arithmatex

plugins:
  - search
```

### System information

- Operating system client: macOS 12.5
- Browser: Chrome 104.0.5112.79
- Operating system to build site (via Docker): Oracle Linux Server 8.6
