### ISSUE TITLE
Python code block render fails

### ISSUE THREAD

**Issue by athrvvvv** [squidfunk/mkdocs-material#4251]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hey there, iam writting an documentation with help of mkdocs and readthedocs.
I have got into an problem

Iam currently using **python 3.9** on **windows**

When I try to render python code block via `pymdownx.superfences` extension it **converts whole code block into single-single inline code block**

---

### I have this in my `mkdocs.yml`
![image](https://user-images.githubusercontent.com/98272709/184622615-c236f0b4-0743-4688-916d-892ad62f1230.png)

---

### **I tried**
![image](https://user-images.githubusercontent.com/98272709/184622706-5ce1d41f-0e9c-4d9b-9b29-cfaf5afec7f3.png)

### **This gives output as**

![image](https://user-images.githubusercontent.com/98272709/184622801-d103e84b-786d-4377-ab99-579b6ba544bc.png)

---

### **I also tried**

![image](https://user-images.githubusercontent.com/98272709/184622918-08bebd81-e53f-46e8-8b8f-fc8de8e42cc0.png)

**but problem remains the same**

Please suggest me some solutions. waiting for answer 🙏

### Expected behaviour

`pymdownx.superfences` extension should render python code block

### Actual behaviour

`pymdownx.superfences` extension converts it into single-single inline code block 

### Steps to reproduce

1. add pymdownx.superfences in mkdocs.yml
2. add following 
![image](https://user-images.githubusercontent.com/98272709/184624429-eb324378-2ab1-4f8c-b6f7-e11ceb1b09d7.png)
3. See output
![image](https://user-images.githubusercontent.com/98272709/184624483-938162a2-b3a6-4b4f-b758-36dbf7e977cd.png)

### Package versions

- Python: `python 3.10.5`
- MkDocs: `mkdocs 1.3.1`
- Material: `latest version`

### Configuration

```yaml
site_name: AppOpener
site_url: https://pypi.org/project/AppOpener
nav:
- Home: 'index.md'
- User Guide:
    - 'Overview': 'overview.md'
    - 'Examples': 'examples.md'
- Devs Guide:
    - 'Mechanism': 'mechanism.md'
- About:
    - 'About': 'about.md'
    - 'License': 'license.md'
    - 'Release Notes': 'release-notes.md'
theme:
    name: readthedocs
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - tables
  - pymdownx.details
  - pymdownx.superfences
copyright: Copyright &copy; 2022 - 2022 LABS CREATION
```

### System information

- Operating system: Windows 10 
- Browser: Chrome, Brave
