### ISSUE TITLE
Custom feedback widget not displayed

### ISSUE THREAD

**Issue by wandri** [squidfunk/mkdocs-material#4255]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hi, I'm testing the feedback widget with a custom javascript file and the widget is hidden.

### Expected behaviour

The feedback widget is displayed when the feedback analytics settings are set in the `mkdocs.yml`.

### Actual behaviour

The feedback widget is not displayed. It's hidden (in the source code).

If I force the display of the widget with:

```
.md-feedback{
  display: block !important;
}
```
 I have new issues:

* Notes are not displayed when I click on one feedback icon but I recieve well the feedback log in my console.

### Steps to reproduce

1. Really simple configuration
<img width="239" alt="Screenshot 2022-08-16 at 11 01 16" src="https://user-images.githubusercontent.com/15016833/184840923-341ea651-0055-4628-9818-a1a1aa031da5.png">

The file `mkdocs.yml` contains:

```
site_name: Documentation
nav:
  - page 1: page_1.md
  - page 2: page_2.md
extra_javascript:
  - javascripts/feedback.js
extra:
  analytics:
      feedback:
          title: Was this page helpful?
          ratings:
            - icon: material/emoticon-happy-outline
              name: This page was helpful
              data: 1
              note: >-
                Thanks for your feedback!
            - icon: material/emoticon-sad-outline
              name: This page could be improved
              data: 0
              note: >-
                Thanks for your feedback! Help us improve this page by using our <a href="..." target=_blank>feedback form</a>.
``` 

The file `javascripts/feedback.js` contains the default content from the documentation:

``` 
const feedback = document.forms.feedback
console.log(feedback)
feedback.addEventListener("submit", function(ev) {
  console.log(ev)
  ev.preventDefault()

  /* Retrieve page and feedback value */
  const page = document.location.pathname
  const data = ev.submitter.getAttribute("data-md-value")

  /* Send feedback value */
  console.log(page, data)
})
```

The pages `page_1.md` and `page_2.md` have this content:

```
# Page 1

This is the page 1
``` 

2. I run the command `docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material:latest`
3. I open page 1 or page 2
4. No feedback widget is displayed

### Package versions

- Docker image: `squidfunk/mkdocs-material:latest` 
- MkDocs: `8.4`

### Configuration

```yaml
mkdocs:


site_name: Documentation
nav:
  - page 1: page_1.md
  - page 2: page_2.md
extra_javascript:
  - javascripts/feedback.js
extra:
  analytics:
      feedback:
          title: Was this page helpful?
          ratings:
            - icon: material/emoticon-happy-outline
              name: This page was helpful
              data: 1
              note: >-
                Thanks for your feedback!
            - icon: material/emoticon-sad-outline
              name: This page could be improved
              data: 0
              note: >-
                Thanks for your feedback! Help us improve this page by using our <a href="..." target=_blank>feedback form</a>.
```
```


### System information

- Operating system: Mac
- Browser: Chrome
