### ISSUE TITLE
Markdown issue with list within a list

### ISSUE THREAD

**Issue by sbowman** [squidfunk/mkdocs-material#4260]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I have a list within a list that looks like this:

```
1. Hello
2. Goodbye
3. Item 3
  * Sub list should be bullets
  * Another bullet
4. This should be 4
```

### Expected behaviour

GitHub Markdown formats this correctly:

1. Hello
2. Goodbye
3. Item 3
  * Sub list should be bullets
  * Another bullet
4. This should be 4

### Actual behaviour

Mkdocs produces this:

1. Hello
2. Goodbye
3. Item 3
4. Sub list should be bullets
5. Another bullet
6. This should be 4

### Steps to reproduce

Create a Markdown doc with the lists formatted as above.

### Package versions

Using the latest Dockerized `squidfunk/mkdocs-material`

### Configuration

```yaml
site_name: Team Documentation

theme:
  name: material
  features:
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: default
      accent: blue
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: blue
      accent: blue

extra_css:
  - css/custom.css

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.tilde
  - tables
  - meta
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.betterem:
      smart_enable: all

plugins:
  - search
```

### System information

macOS Monterey
Firefox & Safari
