### ISSUE TITLE
Feature suggestion: Cross-references in navigation

### ISSUE THREAD

**Issue by wilhelmer** [squidfunk/mkdocs-material#4270]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

In large documentation projects, you sometimes want to include a page multiple times in the nav to tell the user "the information you're looking for does exist, but it's located in a different section". In other words, you want cross-references in the navigation.

```yml
nav:
    - Getting Started:
        - Overview: getting-started.md
        - Creating your site: creating-your-site.md
        - API Reference: api-reference.md # Cross reference 1
    - Setup:
        - Overview: setup.md
        - Installation: installation.md
        - API Reference: api-reference.md  # Cross reference 2
    - API Reference: api-reference.md # Origin
```

This works, with the limitiation that when a page is referenced multiple times, MkDocs always sets the **last** occurrence in the nav as the origin of the page. 

So the above works, but this doesn't:

```yml
nav:
    - API Reference: api-reference.md # We want to add cross-references to this page
    - Getting Started:
        - Overview: getting-started.md
        - Creating your site: creating-your-site.md
        - API Reference: api-reference.md 
    - Setup:
        - Overview: setup.md
        - Installation: installation.md
        - API Reference: api-reference.md # Origin. Cross-references will point to this page, 
        # which is not what we want 
```

Anyway, that's something for MkDocs to address, not for Material. What I want to suggest here is to include functionality that highlights cross-references in the navigation, for those who can live with the above limitation.

Something like this:

<img width="348" alt="Screenshot 2022-08-22 at 10 11 36" src="https://user-images.githubusercontent.com/2234833/185872456-5534f684-6e56-4abd-9613-4e8ca09530ae.png">

I managed to do that using Jinja and a "-->" marker in `mkdocs.yml`, but there's probably a better and cleaner solution:

mkdocs.yml

```yml
nav:
    - Getting Started:
        - Overview: getting-started.md
        - Creating your site: creating-your-site.md
        - --> API Reference: api-reference.md 
    - Setup:
        - Overview: setup.md
        - Installation: installation.md
        - --> API Reference: api-reference.md
    - API Reference: api-reference.md
```

nav-item.html

```jinja
{% macro render_content(nav_item, title) %}
  ...
  <span class="md-ellipsis">
    {% if nav_item.title %}
      {% set title = nav_item.title %}
    {% endif %}
    {% if title.startswith("-->") %}
      <span class="twemoji">
        {% include ".icons/material/arrow-right.svg" %}
      </span>
      <em>{{ title.replace("-->", "") }}</em>
    {% else %}
      {{ title }}
    {% endif %}
  </span>
{% endmacro %}
```

### Use Cases

See above

**Comment by wilhelmer** [comment]
PS: You can work around the above limitation by using `.html` instead of `.md` in cross-references:

mkdocs.yml 

```yml
nav:
    - API Reference: api-reference.md # Origin
    - Getting Started:
        - Overview: getting-started.md
        - Creating your site: creating-your-site.md
        - --> API Reference: api-reference.html # Use .html instead of .md
    - Setup:
        - Overview: setup.md
        - Installation: installation.md
        - --> API Reference: api-reference.html # Use .html instead of .md 
```
