### ISSUE TITLE
forked outdated version example is not working on firefox (the original is)

### ISSUE THREAD

**Issue by MartinRoth** [squidfunk/mkdocs-material#4283]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hi,

as this i my first issue, I want to first thank you for the great work!

The outdated hint is not shown in a recent version of firefox.

As my issue is based on a fork of https://github.com/squidfunk/mkdocs-material-example-versioning and explicitly relies on the custom_dir, I consider the first bullets checked. Moreover, there are closed issues e.g. https://github.com/squidfunk/mkdocs-material/issues/3653, but to me it seems that the odd behavior is reintroduced.

### Expected behaviour

The outdated hint should be shown.

### Actual behaviour

The outdated hint should is not shown on firefox.

### Steps to reproduce

To reproduce, I first forked the repo and then used pip-tools to get the latest versions of the requirements:

- mike
- mkdocs
- mkdocs-material
- mkdocstrings[python]

Which yield the following exact pins:

- mike==1.1.2
- mkdocs==1.3.1 
- mkdocs-autorefs==0.4.1   
- mkdocs-material==8.4.1    
- mkdocs-material-extensions==1.0.3  
- mkdocstrings[python]==0.19.0  
- mkdocstrings-python==0.7.1  

If I follow now the instructions and push the documentation twice firefox is not able to show the outdated hint (chrome is). On the other hand my firefox version  (91.12.0esr) is able to show the hint on the original [webpage](https://squidfunk.github.io/mkdocs-material-example-versioning/0.1/). So it's not *only* a browser issue, it could be dependent on specific versions of some packages. 

If it's possible to obtain the original requirements, I could check this.

### Package versions

- Python: 3.7.5
- MkDocs: 1.3.1
- Material: 8.4.1

### Configuration

```yaml
# Project information
site_name: My Docs
site_url: https://squidfunk.github.io/mkdocs-material-example-versioning/
site_author: Martin Donath

# Repository
repo_name: squidfunk/mkdocs-material-example-versioning
repo_url: https://github.com/squidfunk/mkdocs-material-example-versioning
edit_uri: ""

# Configuration
theme:
  name: material
  custom_dir: overrides

# Customization
extra:
  version:
    provider: mike
```

### System information

- Operating system: wsl1 ubuntu 18.04 on windows
- Browser: firefox 91.12.0esr
