### ISSUE TITLE
404 page is not working as expected

### ISSUE THREAD

**Issue by renardeinside** [squidfunk/mkdocs-material#4301]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

Hi team, 
trying to debug and understand the issue with 404 page.
Although I've clicked "..the problem doesn't occur with the mkdocs or readthedocs themes" I cannot really test it since it would require changing the public doc and releasing a new version (issue cannot be reproduced locally). 

### Expected behaviour

In a local `mkdocs serve` the 404 page is rendered as expected:

<img width="971" alt="Screenshot 2022-08-31 at 20 31 53" src="https://user-images.githubusercontent.com/4979594/187753275-f9f44c44-4f8c-42ce-93ad-c83019f7d9a0.png">

### Actual behaviour

However when deployed with read the docs, it's not rendered as expected, for instance:

https://dbx.readthedocs.io/non-existent

<img width="1216" alt="Screenshot 2022-08-31 at 20 32 51" src="https://user-images.githubusercontent.com/4979594/187753430-0a097661-7762-47e3-b9d7-f721470b2df5.png">

### Steps to reproduce

The source code for docs is located here - https://github.com/databrickslabs/dbx

I'm not using anything specific except custom_overrides with one css:

```
.nowrap {
    white-space: nowrap ;
}
```

### Package versions

- Python: `Python 3.9.12`
- MkDocs: `mkdocs, version 1.3.1`
- Material: `Version: 8.4.0`

### Configuration

```yaml
site_name: dbx
site_description: 🧱Databricks CLI eXtensions - aka dbx is a CLI tool for development and advanced Databricks workflows management.
site_url: https://dbx.readthedocs.io/
copyright: © Copyright 2022, Databricks Inc.

theme:
  name: material
  font:
    text: DM Sans
    code: DM Mono
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: black
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  features:
    - content.code.annotate
    - content.tabs.link
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - navigation.sections
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github
  logo: img/logo.svg
  favicon: img/logo.svg
  language: en

repo_name: databrickslabs/dbx
repo_url: https://github.com/databrickslabs/dbx

plugins:
  - glightbox
  - search

extra_css: [ custom/custom.css ]

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: "#"
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.smartsymbols
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem:
      smart_enable: all
  - mkdocs-click

nav:
  - Home: index.md
  - Concepts:
      - Place of dbx in the ecosystem: concepts/ecosystem.md
      - DevOps for workflows: concepts/devops.md
      - Testing workflows: concepts/testing.md
      - Cluster types for various flows: concepts/cluster_types.md
  - Guides:
      - Python:
          - Python quickstart: guides/python/python_quickstart.md
          - Development loop:
              - Mixed-mode development loop for Python projects: guides/python/devloop/mixed.md
              - Development loop for Python package-based projects: guides/python/devloop/package.md
          - DevOps:
              - DevOps for Python package-based projects: guides/python/devops/package.md
              - DevOps for Notebooks-based projects: guides/python/devops/notebook.md
              - DevOps for Mixed-mode projects: guides/python/devops/mixed.md
          - Packaging arbitrary files: guides/python/packaging_files.md
          - Running integration tests: guides/python/integration_tests.md
      - JVM:
          - Development loop for JVM-based projects: guides/jvm/jvm_devloop.md
          - DevOps for JVM-based projects: guides/jvm/jvm_devops.md
  - Features:
      - Assets-based deployment and launch: features/assets.md
      - File references: features/file_references.md
      - Build management: features/build_management.md
      - Jinja support: features/jinja_support.md
      - Named properties: features/named_properties.md
      - Permissions management: features/permissions_management.md
  - Reference:
      - CLI Reference: reference/cli.md
      - Deployment file reference: reference/deployment.md
      - Project file reference: reference/project.md
  - Migration: migration.md
  - Frequently Asked Questions: faq.md
```

### System information

- Operating system: I assume that readthedocs are running on some kind of Linux.
- Browser: Google Chrome, but issue is same in Safari.
