### ISSUE TITLE
How do I change the graduate cap logo in the top left

### ISSUE THREAD

**Issue by therelaxist** [squidfunk/mkdocs-material#433]
I want to replace the logo that in the top left like here http://squidfunk.github.io/mkdocs-material/ with my own custom logo.

**Comment by therelaxist** [comment]
nvm found it

**Comment by Serafijn** [comment]
What was your solution?

**Comment by therelaxist** [comment]
The solution is adding 
```yml
extra:
  logo: 'logo.jpg'
```
to mkdocks.yml

**Comment by timrobertson100** [comment]
I am not sure this works with the latest version. Can anyone confirm please?

**Comment by facelessuser** [comment]
@timrobertson100, are you saying it used to work for you and now it doesn't?  Or that you just can't get it to work?

I have multiple projects that use the icon replacing feature, and it works in tall of them, both when replacing with png or font icon.

- Replacing with font icon: http://facelessuser.github.io/pymdown-extensions/  
    Config (Using Material font icon name): https://github.com/facelessuser/pymdown-extensions/blob/master/mkdocs.yml#L18

- Replacing with PNG icon: https://facelessuser.github.io/Rummage/  
    Config (path to PNG -- some styling for size done separately in CSS): https://github.com/facelessuser/Rummage/blob/master/mkdocs.yml#L17

If you are having issues, opening an issue with some details may help.

**Comment by martinbira** [comment]
It is now
```
theme:
  logo: 'logo.jpg'
```
see https://squidfunk.github.io/mkdocs-material/release-notes/#material-1x-to-2x

**Comment by timrobertson100** [comment]
Thank you @martinbira  - that is what I had overlooked

The following works

```
site_name: Pipelines Specification
theme: 
  name: 'material'
  logo: 'https://images.contentful.com/q553fnlofhvs/5kTViDSohOKAokEIy48M04/7f35eec668f5c716308c9a49810820aa/GBIF-2015-mark.png'
```
