### ISSUE TITLE
Using both folding menus in a sidebar, and tabs

### ISSUE THREAD

**Issue by claresloggett** [squidfunk/mkdocs-material#435]
## Description

This is not a bug but a feature request (unless what I want is already possible!)

If I turn on the tabs feature with 

```yaml
theme: 'material'
extra:
    feature:
        tabs: true
```

then I get tabs along the top of the page, instead of a sidebar menu.

Is it possible to have tabs *as well as* the sidebar menu? If not I would find this a useful feature.

### Package versions

* Python: Python 3.6.1 :: Anaconda custom (x86_64)
* MkDocs: 0.16.3
* Material: 1.7.5

### Project configuration

Relevant bit is probably only

```yaml
theme: 'material'
extra:
    feature:
        tabs: true
```

vs

```yaml
theme: 'material'
extra:
    feature:
        tabs: false
```

### System information

(Probably not relevant)

* OS: OSX 10.12.1
* Browser: Chrome

**Comment by squidfunk** [comment]
The sidebar is not missing, it's actually there. When you active tabs, two things happen:

1. Every directory (that is a page that contains other pages) is listed inside the tabs navigation. When you click on that tab, the sidebar on the left side shows the subpages of that directory.

2. An additional entry is added to the beginning of the tabs navigation, which is the name of the first page, as it is assumed to be the landing page of your documentation. All other pages on the root level are shown within the sidebar, thus automatically assigned to your root page.

Example:

``` yaml
pages:
  - Landing page, automatically first tab: ...
  - Second tab: ...
    - First page under second tab: ...
    - Second page unde second tab: ...
  - First page under first tab: ...
  - Second page under first tab: ...
  - Third tab
    - First page under third tab: ...
    - Second page unde third tab: ...
  - Third page under first tab: ...
```

In my opinion, this is the only way it makes sense, as directory-less pages have to be grouped somehow and the first page on the root level is assumed to be the logical candidate for that.

However, things should be cleared up in the docs how things are layed out, so I can understand your inquiry. Regarding your inquiry: it's not possible and not planned to show the same navigation in the sidebar as in the tabs navigation, as this would render the tabs navigation obsolete. The tabs feature makes the sidebar navigation relative from the second level on.
