### ISSUE TITLE
Primary navigation is missing. Where did it go?

### ISSUE THREAD

**Issue by ben519** [squidfunk/mkdocs-material#4369]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Here's a look at the most recent deploy preview of my site in Netlify.

<img width="1262" alt="Screen Shot 2022-09-16 at 10 39 56 AM" src="https://user-images.githubusercontent.com/723099/190678064-221c55ab-d844-4dc2-99d8-bad1af857d8a.png">

As you can see, the navigation section (on the left) is completely gone. Here's what the same exact code renders on my local machine.

<img width="1164" alt="Screen Shot 2022-09-16 at 10 44 37 AM" src="https://user-images.githubusercontent.com/723099/190678305-f880654f-53f3-40b3-8320-f26f5255ab61.png">

## What's the difference?
The code is the same. The main difference is that, 

- locally I use `mkdocs-material @ commit 62d4e1caac3cca088cce4c16ed399fa25f958fe3` (older)
- my deploy preview uses `mkdocs-material @ commit c70dcb54465092f7f527a04385c79597e990133e` (newer)

So, clearly something in the newer version of Material is not compatible with my nav. See my `mkdocs.yml` below.

### Expected behaviour

The navigation section should not be missing.

### Actual behaviour

The navigation section is missing (as shown in the image).

### Steps to reproduce

Create a nav similar to mine in `mkdocs.yml` and I suspect you will see the same behavior.

### Package versions

I don't have direct access to the Netlify machine, but from inspecting the deploy logs I see the following

- Python: `3.8`
- MkDocs: `https://****@github.com/squidfunk/mkdocs-material-insiders.git to commit c70dcb54465092f7f527a04385c79597e990133e`
- Material: `mkdocs-1.3.1`

### Configuration

```yaml
site_name: Practice Probs

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.png
  features:
    - announce.dismiss
    - navigation.tabs
    - navigation.indexes
    - content.code.annotate
    - navigation.expand
    - 401.html
    - 404.html

extra:
  site_image: ""
  generator: true
  header_items:
    - Home
    - Pricing
    - Promote
    - Contributors
    - Contact
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/practice_probs
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/practiceprobs
    - icon: fontawesome/brands/discord
      link: https://discord.gg/uYF2ZuASvW
  social_share:
    twitter: true
    reddit: true
    hackernews: true
    linkedin: true

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/sharer.js@latest/sharer.min.js

plugins:
  - tags:
      tags_file: tags.md
  - search
  - social:
      cards_color:
        fill: "#6130a2"
        text: "#ffffff"

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Pricing: pricing.md
  - Promote: promote.md
  - Contributors: contributors.md
  - Contact: contact.md
  - Tags: tags.md
  - Legal:
      - legal/terms-of-service.md
      - legal/privacy-policy.md
      - legal/subscription-agreement.md
  - Evaluation Metrics & Loss Functions:
    - problemsets/evaluation-metrics-and-loss-functions/index.md
    - Precision And Recall:
      - Precision And Recall: problemsets/evaluation-metrics-and-loss-functions/precision-and-recall/index.md
      - Plant Eater:
        - Plant Eater: problemsets/evaluation-metrics-and-loss-functions/precision-and-recall/plant-eater/index.md
        - Solution: problemsets/evaluation-metrics-and-loss-functions/precision-and-recall/plant-eater/solution.md
      - Perfect Brownies:
        - Perfect Brownies: problemsets/evaluation-metrics-and-loss-functions/precision-and-recall/perfect-brownies/index.md
        - Solution: problemsets/evaluation-metrics-and-loss-functions/precision-and-recall/perfect-brownies/solution.md
      - Only Child:
        - Only Child: problemsets/evaluation-metrics-and-loss-functions/precision-and-recall/only-child/index.md
        - Solution: problemsets/evaluation-metrics-and-loss-functions/precision-and-recall/only-child/solution.md
      - A-Eye:
        - A-Eye: problemsets/evaluation-metrics-and-loss-functions/precision-and-recall/a-eye/index.md
        - Solution: problemsets/evaluation-metrics-and-loss-functions/precision-and-recall/a-eye/solution.md
      - Misconception:
        - Misconception: problemsets/evaluation-metrics-and-loss-functions/precision-and-recall/misconception/index.md
        - Solution: problemsets/evaluation-metrics-and-loss-functions/precision-and-recall/misconception/solution.md
```
```


### System information

NA
