### ISSUE TITLE
Social cards image URL

### ISSUE THREAD

**Issue by kkrypt0nn** [squidfunk/mkdocs-material#4402]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When using and generating social cards, it seems like the image is not put correctly.

### Expected behaviour

When using social cards I expect it to be visible on, for example, Discord.

### Actual behaviour

When sending the website URL it doesn't appear. When going on `https://www.opengraph.xyz` it sees the image as:
```html
<meta property="og:image" content="https://<domain>assets/images/social/index.png">
```
and is therefore missing a `/` between the domain and the assets folder.

### Steps to reproduce

1. Install the socials plugin
2. Deploy the website to GitHub pages with `mkdocs gh-deploy`

### Package versions

- Python: `Python 3.10.6`
- MkDocs: `mkdocs, version 1.3.1 from /opt/homebrew/lib/python3.10/site-packages/mkdocs (Python 3.10)`
- Material: `Version: 8.5.3`

### Configuration

```yaml
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
plugins:
  - social:
      cards_color:
        fill: "#9C84EF" 
        text: "#FFFFFF"
```

### System information

- Operating system: macOS Monterey 12.6
- Browser: Edge Version 107.0.1387.2 (Official build) Dev(arm64)
