### ISSUE TITLE
Slugify blog post examples fail

### ISSUE THREAD

**Issue by ofek** [squidfunk/mkdocs-material#4452]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

- https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#+blog.post_slugify
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#+blog.categories_slugify

### Expected behaviour

Docs build

### Actual behaviour

Build errors

### Steps to reproduce

`mkdocs build`

### Package versions

- Python: `3.8.10`
- MkDocs: `1.4.0`
- Material: `8.5.6`

### Configuration

```yaml
INHERIT: mkdocs.yml

plugins:
  blog:
    post_slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
    categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
```

### System information

- Operating system: Windows 10
- Browser: Chrome
