### ISSUE TITLE
SimpleIcons emojis do not work

### ISSUE THREAD

**Issue by artemptushkin** [squidfunk/mkdocs-material#4455]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

SimpleIcons emojis do not work or documentation is wrong though documentation says all the emojis that we can _search_ are available

### Expected behaviour

Using `:simple-gradle:` leads to the Gradle icon appear in the HTML

### Actual behaviour

The emoji is not rendered

<img width="313" alt="image" src="https://user-images.githubusercontent.com/22632802/193865218-f9a44013-8822-4d7f-bbf6-5e48b8747e1b.png">

### Steps to reproduce

Copy-paste `:simple-gradle:` to you mkdocs.yml having the provided configuration

### Package versions

- Python: 3.9.13
- MkDocs: 1.3.0
- Material: 8.3.9

### Configuration

```yaml
markdown_extensions:
  - mdx_truly_sane_lists
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml # PlantUML server, for remote rendering
      # other global options
      cachedir: /tmp # set a non-empty value to enable caching
      base_dir: docs # where to search for diagrams to include
      format: png # default diagram image format
      title: UML diagram # default title (tooltip) for diagram images
      alt: UML diagram image # default `alt` attribute for diagram images
      priority: 100
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
```

### System information

- Operating system: Mac OS Monterey 12.6
- Browser: Google Chrome
