### ISSUE TITLE
PHP code blocks are not highlighted properly

### ISSUE THREAD

**Issue by joseluisq** [squidfunk/mkdocs-material#4547]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [ ] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Recently I tested the latest `squidfunk/mkdocs-material` Docker image using the config attached with PHP code blocks but they are not displayed correctly.

### Expected behaviour

Highlight PHP code block correctly similar to how Pygments does it.

**Note:** I dived a bit into the problem and looks like the issue is somewhat related to `pymdownx.superfences` markdown extension since Pygments can highlight the exact PHP code block correctly.

![image](https://user-images.githubusercontent.com/1700322/197733732-33ea7de0-b4a2-4494-91c1-969e10116b45.png)
https://pygments.org/demo/ 

### Actual behaviour

PHP code block used in a simple page:

```php
<?php

// PNG image (600x199)
$url = 'https://i.imgur.com/G5MR088.png';

$arch = new Image();
$arch
	// Load from URL
	->load($url)
	// Scale to 50% (300x99)
	->scale(0.5)
	// Change the format to JPG
	->toJPG()
	// Saving in local path
	->save('arch.jpg');
```

**mkdocs-material** results after build:

![image](https://user-images.githubusercontent.com/1700322/197731861-88bc6c0a-edb3-48e9-9694-c98cba8893e2.png)

### Steps to reproduce

1. Run the dev server: `docker run -it --rm -p 8000:8000 -v $PWD/docs:/docs squidfunk/mkdocs-material` (or build)
2. Then just navigate to the code block page

### Package versions

```sh
$ docker run -it --rm squidfunk/mkdocs-material --version
# mkdocs, version 1.4.1 from /usr/local/lib/python3.9/site-packages/mkdocs (Python 3.9)
```

### Configuration

```yaml
# Project information
site_name: Project
site_description: 'Example project'
site_author: 'John Doe'
site_url: http://localhost/
dev_addr: 0.0.0.0:8000

# Repository
repo_name: localhost
repo_url: https://localhost/
edit_uri: edit/master/docs/content/

docs_dir: 'content'
site_dir: '/tmp/docs'

# Theme
theme:
  name: 'material'
  language: en
  include_sidebar: true
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.prune
    # - navigation.instant
    # - navigation.sections
    # - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: 'Open Sans'
    code: 'Droid Sans Mono'

markdown_extensions:
  - admonition
  - abbr
  - def_list
  - md_in_html
  - codehilite
  - admonition
  - meta
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - markdown.extensions.tables
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      provider: "github"
      user: "facelessuser"
      repo: "pymdown-extensions"
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.tasklist
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.tabbed:
      alternate_style: true

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Content Navigation
nav:
  - 'Introduction': 'index.md'
```

### System information

- Operating system: Arch Linux
- Browser: Chrome 106.0
