### ISSUE TITLE
javascript custom scripts are triggered with Instant navigation

### ISSUE THREAD

**Issue by wandri** [squidfunk/mkdocs-material#4548]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hi!

I have a project with the following specs

```
theme:
  features:
    - navigation.instant
...
extra_javascript:
  - javascripts/tracking.js
```

I have built this project with docker `docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material build`
 and I check in the console when my tracking file is triggered

### Expected behaviour

Because we work with a Single Page Application I'm expecting the extra_javascript just to be triggered at the beginning.

### Actual behaviour

The extra_javascript files are triggered with every navigation with the build of the project.

But it works in local without the `build` in `docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material` 

### Steps to reproduce

1. Create a project with 
```
theme:
  features:
    - navigation.instant
extra_javascript:
  - javascripts/example.js
...

2. Build your project in local with `docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material build`
3. Open the built project and add a breakpoint in the extra jaavascript file.
4. Navigate to a new page

### Package versions

- MkDocs: `8.5.7`

### Configuration

```yaml
theme:
  features:
    - navigation.instant
extra_javascript:
  - javascripts/example.js
```

### System information

- Operating system: Mac
- Browser: Chrome
