### ISSUE TITLE
ModuleNotFoundError: No module named 'material.plugins'

### ISSUE THREAD

**Issue by llucps** [squidfunk/mkdocs-material#4554]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [ ] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

### Description

Compiling with mkdocs build with fails because:

```
  module = import_module(match.group('module'))
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'material.plugins'
Build step 'Execute shell' marked build as failure
```

### Expected behaviour

It should successfully compile with the latest mkdocs-material release without forcing the the installation of mkdocs-material=="8.1.11"

### Actual behaviour

I see that on [mkdocs-material 8.2.1](https://github.com/squidfunk/mkdocs-material/releases/tag/8.2.1) says:

`Fixed module material.plugins not being found (8.2.0 regression)`

So if I install pip install mkdocs-material=="8.1.11" it actually compiles without any errors.

### Steps to reproduce

Steps launching a Jenkins job:
```
- cd ./apps/vericast-admin-docs
- python3 -m venv venv
- . venv/bin/activate
- pip install wheel
- pip install markdown
- pip install mkdocs-glightbox
- pip install mkdocs-material
- python -m mkdocs build
```

### Package versions

```
mkdocs 1.4.1 has requirement markdown<3.4,>=3.2.1, but you'll have markdown 3.4.1 which is incompatible.
Installing collected packages: MarkupSafe, jinja2, click, six, python-dateutil, ghp-import, pyyaml, pyyaml-env-tag, watchdog, mergedeep, pyparsing, packaging, mkdocs, mkdocs-material-extensions, pymdown-extensions, pygments, urllib3, certifi, charset-normalizer, idna, requests, mkdocs-material

Successfully installed MarkupSafe-2.1.1 certifi-2022.9.24 charset-normalizer-2.1.1 click-8.1.3 ghp-import-2.1.0 idna-3.4 jinja2-3.1.2 mergedeep-1.3.4 mkdocs-1.4.1 mkdocs-material-8.5.7 mkdocs-material-extensions-1.1 packaging-21.3 pygments-2.13.0 pymdown-extensions-9.7 pyparsing-3.0.9 python-dateutil-2.8.2 pyyaml-6.0 pyyaml-env-tag-0.1 requests-2.28.1 six-1.16.0 urllib3-1.26.12 watchdog-2.1.9
```

### Configuration

```yaml
site_name: 'XXXXX Admin Docs'
site_dir: 'faq'
theme:
  name: material

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font: false
  favicon: assets/images/favicon.ico
  logo: assets/images/logotype.png

  features:
    - navigation.expand
    - navigation.indexes

extra_css:
  - assets/stylesheets/extra.css

nav:
    - Customers: 'index.md'
    - Channels: 'channels.md'

plugins:
  - glightbox
  - search 

markdown_extensions:
  - meta
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.critic:
      mode: view
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
```

### System information

- Operating system: Debian 10 (Buster)
- Browser: Firefox 106.0.1
