### ISSUE TITLE
blog plugin does not support Chinese in categories and tags

### ISSUE THREAD

**Issue by ZhiyuanChen** [squidfunk/mkdocs-material#4569]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

blog plugin does not support Chinese in categories and tags

### Expected behaviour

work

### Actual behaviour

```
ERROR    -  Error reading page 'posts/file.md': '类别'
Traceback (most recent call last):
  File "/home/codespace/.python/current/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/mkdocs/__main__.py", line 234, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 114, in serve
    server.serve()
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/mkdocs/livereload/__init__.py", line 156, in serve
    self._build_loop()
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/mkdocs/livereload/__init__.py", line 178, in _build_loop
    func()
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 75, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/mkdocs/commands/build.py", line 308, in build
    _populate_page(file.page, config, files, dirty)
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/mkdocs/commands/build.py", line 177, in _populate_page
    page.markdown = config.plugins.run_event(
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/mkdocs/plugins.py", line 517, in run_event
    result = method(item, **kwargs)
  File "/usr/local/python/3.10.4/lib/python3.10/site-packages/material/plugins/blog/plugin.py", line 389, in on_page_markdown
    file = files.get_file_from_path(self.category_name_map[name])
KeyError: '类别'
```

### Steps to reproduce

```
---
title: Some Title
summary: Some Summary
date: 2021-02-26
categories:
    - 大类
    - 小类
tags:
    - 标签
---
```

### Package versions

- Python: 3.10.4
- MkDocs: mkdocs, version 1.4.1 from /usr/local/python/3.10.4/lib/python3.10/site-packages/mkdocs (Python 3.10)
- Material: 8.5.7+insiders.4.26.1

(Though the output of `pip show mkdocs-material | grep -E ^Version` is as follows:
```
grep: docs copy: Is a directory
mkdocs.yml:      bib_file: "docs/references.bib"
grep: overrides: Is a directory
requirments.txt:mkdocs
requirments.txt:mkdocs-material
requirments.txt:mkdocs-awesome-pages-plugin
requirments.txt:mkdocs-bibtex
requirments.txt:mkdocs-git-revision-date-localized-plugin
requirments.txt:mkdocs-git-committers-plugin
requirments.txt:mkdocs-rss-plugin
requirments.txt:mkdocs-static-i18n
requirments.txt:mkdocstrings
requirments.txt:mkdocstrings[python]
ERROR: Pipe to stdout was broken
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

### Configuration

```yaml
nav:
  - index.md

theme:
  name: material
  custom_dir: overrides
  language: 'zh'
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  logo: 'assets/images/logo.png'
  favicon: 'assets/images/logo.ico'
  features:
    - announce.dismiss
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  font: false

extra_javascript: 
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/shortcuts.js

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - mdx_math
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - smarty
  - tables
  - toc:
      permalink: true

plugins:
  - meta
  - blog:
      blog_dir: .
      post_date_format: full
      post_url_format: "{slug}"
  - bibtex:
      bib_file: "docs/references.bib"
      csl_file: "https://raw.githubusercontent.com/citation-style-language/styles/master/ieee.csl"
      cite_inline: true
  # - git-revision-date-localized:
  #     type: iso_datetime
  # - git-committers
  - privacy:
      externals_exclude:
        - cdn.jsdelivr.net/npm/mathjax@3/*
        - giscus.app/*
        - github-readme-stats.vercel.app/*
  - rss:
      match_path: .* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - search:
      separator: '[\s\u200b\-]'
  - tags
```

### System information

github codespaces

**Comment by ZhiyuanChen** [comment]
hmmmm, it see

**Comment by ZhiyuanChen** [comment]
the issue needs to be further investigated, closing for now but will probably be reopened in the future.

**Comment by ZhiyuanChen** [comment]
I have dig into it a little bit, `self.category_name_map` looks like this:
```
{'category': 'category/category',
 '类别': 'category/.md',}
```

This is related to line 656 of blog plugin, specifically `self.config.categories_slugify` is in ascii encoding

**Comment by ZhiyuanChen** [comment]
also, it seems `slugify` would convert upper case letters to lower case, resulting same `KeyError` in `files.get_file_from_path(self.category_name_map[name])`

**Comment by ZhiyuanChen** [comment]
also also, special texts in categories such as `+` will be removed by `slugify`, resulting same error

**Comment by squidfunk** [comment]
Please provide a self-contained reproducible example and attach it here as a zip file. Thanks!

**Comment by ZhiyuanChen** [comment]
[demo.zip](https://github.com/squidfunk/mkdocs-material/files/10187756/demo.zip)
This should be a MWE

**Comment by ZhiyuanChen** [comment]
> also, it seems specified case to `lower` would results in same `KeyError` in `files.get_file_from_path(self.category_name_map[name])`

This only happens if there are same categories that has different cases. For example, if all files have `Algorithms` or all have `algorithms`, they work fine. But if some have `Algorithms` while others have `algorithms`, it brakes

**Comment by squidfunk** [comment]
Thanks for providing the example. Your configuration is wrong, you're missing `categories_slugify`:

``` yaml
- blog:
      blog_dir: .
      post_date_format: full
      post_url_format: "{file}"
      post_readtime_words_per_minute: 100
      archive_url_date_format: yyyy/MM
      archive_date_format: MMMM yyyy
      categories_slugify: !!python/object/apply:pymdownx.slugs.slugify # <-- you used post_slugify
        kwds:
          case: lower
```

With that added, your docs build fine:

![screenshot-localhost-8000-category-E6-95-B0-E5-AD-A6-1670524654243](https://user-images.githubusercontent.com/932156/206539134-99e569ef-fb57-46fd-929a-895dfaae85b5.png)
