### ISSUE TITLE
After deployment javascript error: Uncaught TypeError: Cannot read properties of undefined (reading 'enable')     at window.onload ((index):2030:39)

### ISSUE THREAD

**Issue by MircoBabin** [squidfunk/mkdocs-material#4611]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The navigation is acting weird. In the javascript console this error pops up:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'enable')
    at window.onload ((index):2030:39)
worker.js:57 All search scripts loaded, building Lunr index...
worker.js:84 Lunr index built, search ready
```

### Expected behaviour

No javascript error and navigation working properly.

### Actual behaviour

It seems ``` SphinxRtdTheme.Navigation.enable(true); ``` is executed before the script(s) are loaded.

---

![image](https://user-images.githubusercontent.com/8981285/200512926-648ba4e8-c74a-46ab-acf2-5cb940b6e58d.png)

### Steps to reproduce

1. mkdocs build
2. deploy the website to a real webserver connected to the internet
3. browse the website. I observed the navigation was acting weird, with sometimes to much whitespace. I observed the javascript error in the javascript console

### Package versions

- Python: `Python 3.10.7`
- MkDocs: `mkdocs, version 1.4.2 from C:\Python310\lib\site-packages\mkdocs (Python 3.10)`
- Material: `'grep' is not recognized as an internal or external command, operable program or batch file.`

### Configuration

```yaml
site_name: Trip API
theme: readthedocs
extra_css: [extra.css]
nav:
- Introduction: 'index.md'
- Javascript Route calculation library: 'TripSoftwareModuleKm_v2.md'
- Portal Orderrequest (price): 'portal-orderrequest.md'
- Trip Touroperating: 'trip-touroperating.md'
- Requests [general]: 'request.md'
- Responses [general]: 'response.md'
```

### System information

- Operating system: `Windows/11 latest`
- Browser:  `Google Chrome, Chrome is up-to-date, Versie 107.0.5304.88 (Officiële build) (64-bits)`
