### ISSUE TITLE
Critic highligthing breaks code block highlighting in unrelated lines

### ISSUE THREAD

**Issue by yuyukey** [squidfunk/mkdocs-material#4618]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The highlighting applied using Critic's `{==text==}` syntax breaks code block highlighting in unrelated lines.

### Expected behaviour

I can use YAML highlighting without it being influenced by Critic highlighting in other lines.

### Actual behaviour

When using the `{==text==}` syntax to highlight an entire line, the next line has the wrong color.
The first code block in this image shows the wrong behaviour, the second the desired YAML highlighting. Therefore, the `value` option in the first code block should also be blue.
![image](https://user-images.githubusercontent.com/51208438/200887581-b8ec0337-209a-405b-b0cd-2fcdd0a403cc.png)

### Steps to reproduce

1. Clone the example from https://github.com/yuyukey/Material-for-Mkdocs-Critic-Bug
2. `mkdocs serve`

### Package versions

- Python: `3.10`
- MkDocs: `1.4.2`
- Material: `8.5.8+insiders.4.26.2` also confirmed on `8.3.9+insiders.4.21.0`

### Configuration

```yaml
site_name: My Docs
theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
```

### System information

- Operating system: Windows 10
- Browser: Reproduced on Chrome and Firefox
