### ISSUE TITLE
Tags are not shown on the tags page and in the search

### ISSUE THREAD

**Issue by tardar** [squidfunk/mkdocs-material#4629]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hey  together,

for me in my gitlab pages deployed instance the tags are not shown with the [TAGS]  on the tags page and set up in  the insiders  config.

### Expected behaviour

I  can see the tags i added to every doc subfolder  .meta.yml on every doc page at the top to search and find stuff with the  tags.
Secondly i expect that the Tags  "Cloud"  is generated on  my tags page which i configured in the configfile and setup  in the navbar.

### Actual behaviour

Actually my  tags page is look like this:
<img width="175" alt="tagspage" src="https://user-images.githubusercontent.com/40645000/201487380-7b940494-e30a-4514-b4b5-a3c57dcce4fe.png">

On my pages  i can't see the tags (look like the tags page - only ma content is visible).

So i added a .meta.yml to every subfolder in my docs folder where i generally like to see and use the tags on all their pages which are included  in that folders.

### Steps to reproduce

1. config it  in the configfile
2. upload  it to gitlab
3. runner creates pages deployment
4. open the site but it won't work  with all that mentioned  features

### Package versions

- Python: `3.9.2`
- MkDocs: `1.4.2`
- Material: `Version: 8.5.9+insiders.4.26.2`

### Configuration

```yaml
INHERIT: mkdocs.yml
site_name: ***
theme:
  language: de
  logo: images/ha_logo.png
  name: material
  features:
  - navigation.sections
  - navigation.indexes
  - toc.follow
  - search.suggest
  - search.highlight
  - header.autohide
  - announce.dismiss
  - navigation.prune
  plugins:
    - search:
        lang: de
        separator: '[\s\-\.]'
    - blog:
        blog_dir: blog
        post_url_date_format: dd/MM/yyyy
        post_readtime_words_per_minute: 265
    - tags:
        enabled: true
        tags_file: tags.md
    - social
    - privacy:
        external_links: true
        external_links_attr_map:
          target: _blank
        external_links_noopener: true
    - glightbox
    -  meta:
         meta_file: '**/.meta.yml'
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Light Mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Dark-Mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra:
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - header.autohide
    - content.code.annotate
  generator: false
  consent:
    title: Cookie consent
    actions:
      - accept
      - manage
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  version:
    provider: mike
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
nav:
  - Home: index.md
  - Tags: tags.md
```

### System information

- Operating system: windows10
- Browser: chrome, firefox, brave
