### ISSUE TITLE
Apostrophe rendering as left smart-quote instead of right, when the possessive noun has a tooltip.

### ISSUE THREAD

**Issue by feasgal** [squidfunk/mkdocs-material#4651]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

If `Word` is defined as an abbreviation using the `*[Word]:` syntax, then `Word's` (e.g., `this Access Group's permissions`) renders with a left smart-quote instead of an apostrophe.

### Expected behaviour

I would expect this markdown source:

```
Each section of the editor controls an access group's ability to view, and actions within, the listed pages.
Select the checkboxes to allow the appropriate actions.

*[access group]: Access groups allow admin users to<br>assign custom permissions to all<br>users assigned to that group.
```

To render wie so:

![image](https://user-images.githubusercontent.com/97999520/202267595-bd6dcfae-17be-47fd-9a95-b5b6fbeedc31.png)

### Actual behaviour

It is rendering like this instead:

![image](https://user-images.githubusercontent.com/97999520/202267775-eee15f8f-7697-4a92-9e9b-eefd61999a57.png)

### Steps to reproduce

1. Put the above markdown source in a file.
2. Use the below configuration.
3. `mkdocs serve`

### Package versions

- Python: `3.10.0`
- MkDocs: `1.4.0`
- Material: `8.5.6+insiders.4.25.2`

### Configuration

```yaml
site_name: My Documentation
site_url: ""

plugins:
    - search:
        separator: '[\s\-\./\\]+'
    - offline

theme:
  name: material
  font:
    text: Montserrat
    code: Noto Sans Mono
  language: en

extra_javascript:
  - assets/mathjax/mathjax.js
  - assets/mathjax/tex-mml-chtml.js

markdown_extensions:
    - abbr: {}
    - smarty: {}
    - toc: {}
    - tables: {}
    - attr_list: {}
    - pymdownx.tabbed: {}
    - pymdownx.snippets: {}
    - meta: {}
    - md_in_html: {}
    - admonition: {}
    - pymdownx.details: {}
    - pymdownx.superfences: {}
    - def_list: {}
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.caret: {}
    - pymdownx.mark: {}
    - pymdownx.tilde: {}
    - pymdownx.keys: {}
    - footnotes: {}
    - pymdownx.arithmatex:
        generic: true
```

### System information

- Operating system: macOS Monterey 12.6
- Browser: Chrome 107.0.5304.110, Safari 15.6.1, Firefox 106.0.2
