### ISSUE TITLE
edit_uri is using `master` by default

### ISSUE THREAD

**Issue by DarkaMaul** [squidfunk/mkdocs-material#4657]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The edit button is using `master` branch name by default. Clicking the edit button leads to a 404

I'm unsure it's a bug since it is easily fixable with this simple line:
```yml
edit_uri: edit/main/docs/
```

### Expected behaviour

We would like to get the edit page.

### Actual behaviour

We get a 404 page not found

### Steps to reproduce

1. Create a repository with a default branch named `main`

You can find a reproduction from a repo simply forked from  `mkdocs-material/examples.git`

- https://quokka-project.github.io/mkdocs-demo
- https://quokka-project.github.io/mkdocs-demo/
- https://github.com/quokka-project/mkdocs-demo/edit/master/docs/index.md

### Package versions

- Python: 3.10
- MkDocs: 1.3.1
- Material: 8.5.2

### Configuration

```yaml
site_name: Example
# site_url: https://example.com/
site_author: Martin Donath
site_description: >-
  This project lists all options that are supported by Material for MkDocs
  and can be used as a basis for new projects or reproductions.

# Repository
repo_name: mkdocs-material/examples
repo_url: https://github.com/quokka-project/mkdocs-demo
```

### System information

- Operating system: Linux
