### ISSUE TITLE
Mermaid sequence diagram not allowing links in participant

### ISSUE THREAD

**Issue by fidel-ruiz** [squidfunk/mkdocs-material#4658]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When clicking the participant `test` it should open up the actor popup menu. that event is not trigger. I'm using the native support with mermaid with plain mkdocs the rendering was different using html and pre, it was working as expected.

Sharing this simple diagram to showcase the issue
```mermaid
sequenceDiagram
    participant  test
    participant  test2
    link test: github @ https://github.com
    test->>test2: talk to
```

### Expected behaviour

On click of the actor box should display the menu item.
![image](https://user-images.githubusercontent.com/17907582/202770518-e82a4127-c115-4187-8383-515c98307c33.png)

### Actual behaviour

Actor Menu are not displayed, they are in the shadowDOM of the svg but the click event is not triggered.

### Steps to reproduce

1. Create a diagram using mkdocs-material with the config explained above 

### Package versions

- Python: 3.10.8
- MkDocs:  1.4.2
- Material: 8.5.10

### Configuration

```yaml
site_name: IBM Cloud Monitoring Regulated
nav:
  - Home: index.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant

plugins:
  - search

markdown_extensions:
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          securityLevel: loose
          logLevel: 1
          format: !!python/name:pymdownx.superfences.fence_code_format
```

### System information

- Operating system: MAC
- Browser: Firefox, Chrome
