### ISSUE TITLE
Back to top button doesn't change with theme colour

### ISSUE THREAD

**Issue by EDIflyer** [squidfunk/mkdocs-material#4663]
I appreciate fairly minor but couldn't see it mentioned elsewhere and hopefully not too tricky to fix? 😃 

### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The ['back to top' button](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button) works as intended, but after [changing the site colour](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button) in mkdocs.yml I've found it remains the default blue.

### Expected behaviour

Change colour to match the site colour

### Actual behaviour

![image](https://user-images.githubusercontent.com/13610277/202914827-9d6e73de-0d91-485e-8f29-a7cececf019d.png)
![image](https://user-images.githubusercontent.com/13610277/202915152-0ea9c9f6-d10e-4ec6-a08e-1a7fd30c5da1.png)
![image](https://user-images.githubusercontent.com/13610277/202915185-423fecc1-0586-4917-aabe-71f2160a5c0c.png)

### Steps to reproduce

1. Change default site colour in `mkdocs.yml`
2. Enable back-to-top button in `mkdocs.yml`
3. Note default blue colour remains on button

### Package versions

- Python: `Python 3.9.2`
- MkDocs: `mkdocs, version 1.4.2 from /usr/local/lib/python3.9/site-packages/mkdocs (Python 3.9)`
- Material: `Version: 8.5.10`

### Configuration

```yaml
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: red
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.top
```

### System information

- Operating system: Windows 10
- Browser: Chrome 107

**Comment by EDIflyer** [comment]
PS I guess there could also be a case made for switching edit and navigation anchors to match too although they're much smaller areas of colour so not quite as noticeable...
![image](https://user-images.githubusercontent.com/13610277/202915364-9a45ddc4-a9e2-44f6-90da-8d7807569d7e.png)
![image](https://user-images.githubusercontent.com/13610277/202915366-f0234dbf-38e7-4542-a29a-366371a36aff.png)

**Comment by squidfunk** [comment]
Thanks for reporting. In fact, it changes with the theme color. You have the back-to-top button selected, and no specific `accent` color set, which means that the accent button will use the [`indigo` accent color](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color) when selected. Try the following:

``` yaml
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: red
      accent: green
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
```
