### ISSUE TITLE
Bug in Safari on how menu is only sized to main content

### ISSUE THREAD

**Issue by alkemann** [squidfunk/mkdocs-material#468]
## Description

See comparison screenshots between Safari and Firefox bellow. Desired outcome is that the sidebar get maximum height.

### Expected behavior
Firefox 55.0.3 ("good behaviour"):
![30209280-8bcf16c4-9497-11e7-9c6f-359b0c120f31](https://user-images.githubusercontent.com/48854/30540936-6d5f485a-9c79-11e7-8f97-37e80401f4b2.png)

### Actual behavior
Safari 10.1.2 ( "buggy behaviour" ):
![30209255-7b7f1b84-9497-11e7-9cd4-94bad37181c7](https://user-images.githubusercontent.com/48854/30540946-78d7cc3e-9c79-11e7-923e-e8c80c10c310.png)

### Steps to reproduce the bug

1. Look at a page with short content page while having a sidemeu with many options.

### Package versions
* Python:  version 2.7.13
* Mkdocs: version 0.16.3
* Material: Version: 1.6.3

### Project configuration

``` yaml
site_name: Documentation
theme: material
extra_css:
  - custom.css
extra:
  logo: "cc-logo.png"
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false, linenums=true)
  - toc(permalink=true)
```

### System information
* Browser: Safari

**Comment by squidfunk** [comment]
Can you update to 1.10.1 and check if the error still persists?

**Comment by squidfunk** [comment]
Also, try removing your custom CSS as it might cause the behavior.

**Comment by squidfunk** [comment]
Confirmed, Safari doesn't correctly apply `min-height`.

**Comment by alkemann** [comment]
Maybe this?
```css
.md-container>.md-main>.md-main__inner {
    height: inherit;
    position: relative;
}
```
