### ISSUE TITLE
Mermaid Tooltips are not working

### ISSUE THREAD

**Issue by joskfg** [squidfunk/mkdocs-material#4686]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Mermaid.js is not rendering the Tooltips

### Expected behaviour

I'd expect to see the tooltip when I put the cursor over the node with tooltip.

### Actual behaviour

The tooltip is now shown when you put the cursor over the node with tooltip.

I think it is because it uses this code for render:
```
mermaid.mermaidAPI.render(id, el.textContent, (svg: string) => {

      /* Create a shadow root and inject diagram */
      const shadow = host.attachShadow({ mode: "closed" })
      shadow.innerHTML = svg

      /* Replace code block with diagram */
      el.replaceWith(host)
    })
```

So it just recover the SVG data and not the div that is needed to show the tooltip.

### Steps to reproduce

Create a simple flowchart diagram like
```
```mermaid
flowchart LR
    TEST
    click TEST callback "I should be able to see this"
```
```

### Package versions

Using image: squidfunk/mkdocs-material:8.5.8

### Configuration

```yaml
site_name: 'my docs'
site_url: 'http://127.0.0.1'
# Extensions
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
```

### System information

- Operating system: any
- Browser: any
