### ISSUE TITLE
Unable to set configurations for `git-revision-date-localized`

### ISSUE THREAD

**Issue by alelom** [squidfunk/mkdocs-material#4697]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

While `git-revision-date-localized` works when no settings are assigned in the `mkdocs.yml` file, i.e.:

```yml
plugins:
  - git-revision-date-localized
```

as soon as I add any custom setting, e.g.:

```yml
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
```

The build fails, and this error is returned:

```
ERROR    -  Config value 'plugins': Invalid Plugins configuration
Aborted with 1 Configuration Errors!
```

For me this happens consistently regardless of any other plugin/extension/custom css/etc.

Note that this happens even if you set a configuration to its own default value, e.g.:

```yml
plugins:
  - git-revision-date-localized:
      type: date
```

which may indicate an incorrect parsing of the configurations for this extension.

I am adding the whole YML file I'm testing with just for completeness -- see "Configuration" below for the minimal.

<details>

```yml
site_name: BHoM documentation
copyright: Copyright &copy; 2018 - 2022 BHoM
site_url: https://bhom.xyz/documentation/
repo_url: https://github.com/BHoM/documentation
edit_uri: edit/main/docs/

theme:
  name: material
  logo: _images/logos/logo.png
  favicon: _images/logos/favicon.ico
  palette:
    primary: white
    accent: pink

  features:
    - navigation.tracking
    - navigation.top

plugins:
  - search
  - awesome-pages #allows to customise the ordering of pages
  - git-revision-date-localized:
    # fallback_to_build_date: false
    # enable_creation_date: true
    #type: date

markdown_extensions:
  - attr_list # allows to add HTML/CSS attributes to almost every Markdown element, useful for e.g. aligning an image to the left/right (can't do centre though! use md_in_html instead)
  - md_in_html # allows to add markdown within HTML elements, useful for e.g. adding image captions or centering an image
  
  - pymdownx.betterem # Wider support to markdown symbols
  
  # Code syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # Mathjax support
  - pymdownx.arithmatex:
      generic: true

  # Call-outs and note boxes ('admonition')
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript: 
  # Also required for Mathjax support
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/BHoM
      name: BHoM on Github
```

</details>

### Expected behaviour

Configurations should be settable and the build should successfully complete.

### Actual behaviour

The build fails as soon as an

### Steps to reproduce

1. Install `git-revision-date-localized` via pip
2. Configure it in the yml file without any configuration
3. Build the website locally
4. Verify that it builds
5. Add any configuration to `git-revision-date-localized` in the yml file
6. Verify that build fails

### Package versions

- Python: 3.10.8
- MkDocs: 1.4.2 
- Material: 8.5.10 (I'm on Windows and running `grep` is not an option -- just noting it 😄)

### Configuration

```yaml
site_name: BHoM documentation
site_url: https://bhom.xyz/documentation/
repo_url: https://github.com/BHoM/documentation
edit_uri: edit/main/docs/

theme:
  name: material

plugins:
  - git-revision-date-localized: #uncommenting any of the lines below makes the build fail.
    # fallback_to_build_date: false
    # enable_creation_date: true
    # type: date
```

### System information

- Operating system: Windows 10
- Browser: Chrome
