### ISSUE TITLE
Search box - no longer searching... 

### ISSUE THREAD

**Issue by JamesRivers** [squidfunk/mkdocs-material#4720]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I have long had the mkdocs material theme with the search plugin and it has worked great for a long time. However in the past week the search box is not listing any results. 

### Expected behaviour

Search for items and list to be populated with results. 

### Actual behaviour

Type in search item, no results. 

### Steps to reproduce

1. type in search item 

### Package versions

- Python: 3.11.0
- MkDocs:  1.4.2
- Material: 8.5.11

### Configuration

```yaml
markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format

theme:
    name: material
    logo: assets/logo.png
    favicon: assets/images/favicon.png
    palette:
      - scheme: default
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
      - scheme: slate
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode
    features:
      # - navigation.tabs
      # - naviagtion.tabs.sticky
      #- navigation.expand
      - navigation.indexes
      - navigation.instant
      - toc.follow
      - search.highlight
      - search.share
      - search.suggest
      # - navigation.top

  plugins:
      - tags:
          tags_file: tags.md
      - search: {}
      - encryptcontent:
          global_password: 'password'
          remember_password: True
          default_expire_dalay: 12
          password_button: True
          password_button_text: 'login'
```

### System information

- Operating system: ... any 
- Browser: ... chromium
