### ISSUE TITLE
JSON schema: allow single string for pymdownx.emoji and pymdownx.tasklist

### ISSUE THREAD

**Issue by pawamoy** [squidfunk/mkdocs-material#4735]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Similarly to https://github.com/squidfunk/mkdocs-material/issues/4081, we should allow the "attribute-less" versions of `pymdownx.emoji` and `pymdownx.tasklist`. I didn't check if other extensions are impacted: just those two that I configure this way and trigger validation errors :slightly_smiling_face: 

I can open a PR if needed!

### Expected behaviour

```yaml
markdown_extensions:
- pymdownx.emoji
- pymdownx.tasklist
```

...should not trigger validation errors.

### Actual behaviour

![jsonschema](https://user-images.githubusercontent.com/3999221/206916190-4334ff74-122c-4046-acc6-35628b29b7e3.png)

### Steps to reproduce

Add this to mkdocs.yml:

```yaml
# mkdocs.yml
markdown_extensions:
- admonition
- callouts
- pymdownx.details
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist
- toc:
    permalink: "¤"
```

And configure VSCode with this:

```json
{
    "yaml.schemas": {
        "https://squidfunk.github.io/mkdocs-material/schema.json": "mkdocs.yml"
    },
    "yaml.customTags": [ 
        "tag:yaml.org,2002:python/name:materialx.emoji.to_svg",
        "tag:yaml.org,2002:python/name:materialx.emoji.twemoji",
        "tag:yaml.org,2002:python/name:pymdownx.superfences.fence_code_format"
    ]
}
```

### Package versions

- Python: N/A
- MkDocs: N/A
- Material: N/A

### Configuration

```yaml
site_name: Yo
site_url: https://example.com

markdown_extensions:
- admonition
- callouts
- pymdownx.details
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.tasklist
- toc:
    permalink: "¤"
```

### System information

- Operating system: linux
- Browser: firefox
