### ISSUE TITLE
The view button and footer (previous and next buttons) doesn't show up

### ISSUE THREAD

**Issue by krahets** [squidfunk/mkdocs-material#4760]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I've updated the package to 9.00b4. The new search is awesome, thanks!

The view button and footer (previous and next buttons) don't show up after setting the arguments described in #4714.

Do I miss anything?

```
theme:
  features:
    - content.action.edit
    - content.action.view
    - navigation.footer
```

### Expected behaviour

The view button and footer (previous and next buttons)

### Actual behaviour

Not showed up

### Steps to reproduce

mkdocs serve

### Package versions

- Python: 3.7
- MkDocs: `1.4.2`
- Material: `9.0.0b4`

### Configuration

```yaml
# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  language: zh
  features:
    # - announce.dismiss
    - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
```

### System information

- Operating system: macOS
- Browser: Chrome

**Comment by squidfunk** [comment]
I've verified. The following configuration definitely works on the latest beta:

``` yaml
site_name: My Docs
repo_url: http://github.com/squidfunk/mkdocs-material
theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
```

Closing as not reproducible.
