### ISSUE TITLE
Documentation has wrong feature flag code.action.edit/view instead of content.action.edit/view

### ISSUE THREAD

**Issue by mburuckercSO** [squidfunk/mkdocs-material#4818]
### Bug description

The Documentation at https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions

tells you to add the flags

```
theme:
  features:
    - code.action.edit 

theme:
  features:
    - code.action.view
```

Those do not work and should be

```
theme:
  features:
    - content.action.edit 

theme:
  features:
    - content.action.view
```

### Related links

- [Bug reporting](https://squidfunk.github.io/mkdocs-material/bug-report/)
-https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions

### Reproduction

Is this needed for this small bug can provide if wanted

### Steps to reproduce

Use Documentation to add code edit and view button.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) or [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/bug-report/#remove-customizations) before submitting this bug report.
- [X] I have attached a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/).
