### ISSUE TITLE
Page language selector instead of Site language selector

### ISSUE THREAD

**Issue by KusakabeShi** [squidfunk/mkdocs-material#4835]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

At this doc: https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language-selector

This config always redirect to the homepage of another language:
```
extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Deutsch
      link: /de/
      lang: de
```

Assume I'm in the https://example.com/de/IXP page, click the "English" Button will be redirect to https://example.com/en/

Is it possible to set it like this
```
extra:
  alternate:
    - name: English
      link: /en/{page.name} 
      lang: en
    - name: Deutsch
      link: /de/{page.name}
      lang: de
```

So that I'm in the https://example.com/de/IXP page, click the "English" Button will be redirect to https://example.com/en/IXP page ?

### Use Cases

Switching languages without leaving the current page.

I'm in the https://example.com/de/IXP page, click the "English" Button will redirect to https://example.com/en/IXP instead of https://example.com/en/

**Comment by squidfunk** [comment]
Thanks for suggesting. I've had this idea a while ago, but never followed up on it. However, I definitely think it is useful, as it would also mirror behavior of versioning, which will try to stay on the same page, as long as there is one in the version that is switched to. We could implement similar behavior for the language selector, but this would mean that the path must stay the same between versions. If that is given, it should work.

**Comment by KusakabeShi** [comment]
By the way, is it possiable to use variable in the nav path like this?

```md
nav:
  - Poema IX: {lang}/index.md
  - Virtual IXP: {lang}/Virtual-IXP.md
  - Members: {lang}/members.md
  - Route Server: {lang}/RS.md
```
In this example, the redirect target will follow the current language like `en/Virtual-IXP.md` or  `zh/Virtual-IXP.md`

So that I can hendle multi language in one site.

**Comment by squidfunk** [comment]
> So that I can hendle multi language in one site.

It may be possible through some third-party plugin, but not in Material for MkDocs itself.

**Comment by vedranmiletic** [comment]
This would be far more useful if it could be expanded with `language_maps` in spirit of `redirect_maps`, e.g.

``` yaml
plugins:
    - languages:
        language_maps:
            hr:
                'en/example.md': 'hr/primjer.md'
            de:
                'en/example.md': 'de/exempel.md'
```
