### ISSUE TITLE
Navigation Path (Breadcrumbs) render bug

### ISSUE THREAD

**Issue by adminradio** [squidfunk/mkdocs-material#4865]
### Bug description

I’m trying the new navigation paths feature, but stumbled over a visual hickup. The following mkdocs.ymlgenerates the output in the screenshot (the red line shows the problem):

```yaml
site_name: My Docs

theme:
  name: material
  features:
    - navigation.path

nav:
  - Start:
    - index.md
    - Level 1:
      - l1/index.md
      - Level 1.1: l1/l1.1/index.md
```
<img width="505" alt="Bildschirm­foto 2023-01-15 um 17 40 40" src="https://user-images.githubusercontent.com/2880143/212569080-8422a2c2-7cab-4f92-b421-70fc9071e148.png">

### Related links

- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+path#navigation-path

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/10421337/example.zip)

### Steps to reproduce

1. init a new mkdocs project
2. add nested nav items with content on section item, like so:

```
nav:
  - Start:
    - index.md
    - Level 1:
      - l1/index.md
      - Level 1.1: l1/l1.1/index.md
```

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) or [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/bug-report/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/).

**Comment by wilhelmer** [comment]
I can confirm this. The bug occurs whenever there's no topic at root level.

So this works:

```yml
nav:
  - Start: index.md # This is our root level topic
  - Level 1:
    - l1/index.md
    - Level 1.1: l1/l1.1/index.md
```

But this doesn't:

```yml
nav:
  - Start: # No root level topic here
    - index.md 
    - Level 1:
      - l1/index.md
      - Level 1.1: l1/l1.1/index.md
```
