### ISSUE TITLE
Collapsible blocks stopped to work

### ISSUE THREAD

**Issue by AndreWin** [squidfunk/mkdocs-material#489]
Hello!

I tried the following from material-design docs:

```
??? note "Phasellus posuere in sem ut cursus"
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et euismod
    nulla. Curabitur feugiat, tortor non consequat finibus, justo purus auctor
    massa, nec semper lorem quam in massa.
```

This worked before, but today it doesn't work.
When I replace ??? to !!! block begin to work.

I tested this on two independent sites &mdash; the same problem

How can I fix this?

Best regards, Andrey.

**Comment by squidfunk** [comment]
Just tested it and it works for me:
http://squidfunk.github.io/mkdocs-material/extensions/admonition/#collapsible-blocks

Please use the issue template and provide some more details.

**Comment by facelessuser** [comment]
Works for me as well and I have generated mine with the most recent Material release and pymdown-extensions release: http://facelessuser.github.io/pymdown-extensions/extensions/details/#examples.

**Comment by AndreWin** [comment]
I just removed `mkdocs` and `mkdocs-material`, cleared pip cache and installed them again.

This didn't help me.

Please, help me to check: is the following true?

```
markdown_extensions:
    - toc:
        permalink: True
        baselevel: 1
    - attr_list
    - admonition
    - footnotes
    - codehilite:
        guess_lang: False
    - smarty:
        smart_angled_quotes: True
        smart_dashes: True
        smart_quotes: False
        smart_ellipses: True
```
