### ISSUE TITLE
Mermaid diagrams not rendered in new rich search preview

### ISSUE THREAD

**Issue by mbelangergit** [squidfunk/mkdocs-material#4892]
### Bug description

When searching, if the preview contains a Mermaid diagram, it is rendered as a regular code block instead of the diagram.

![image](https://user-images.githubusercontent.com/56379077/213798353-9c67f02c-fb4d-4fed-b471-44ca188b2e2d.png)

### Related links

- https://squidfunk.github.io/mkdocs-material/reference/diagrams/#diagrams
- https://squidfunk.github.io/mkdocs-material/blog/2021/09/13/search-better-faster-smaller/?h=ri#search-better-faster-smaller

### Reproduction

`mkdocs.yml`:

``` yml
site_name: MySite

theme:
  name: material

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - index.md
```

`index.md`:

~~~ markdown
# Diagrams

``` mermaid
graph LR
  A[Start] --> B{Error?};
  B -->|Yes| C[Hmm...];
  C --> D[Debug];
  D --> B;
  B ---->|No| E[Yay!];
```
~~~

[mermaid-in-search.zip](https://github.com/squidfunk/mkdocs-material/files/10470068/mermaid-in-search.zip)

### Steps to reproduce

1. Run `mkdocs new .`
1. Create a basic site using above `mkdocs.yml` and `index.md`.
1. Run `mkdocs serve`
1. Search for `Diagrams`

Using:

- mkdocs-material 9.0.5
- mkdocs 1.4.2

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) or [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/bug-report/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/).
