### ISSUE TITLE
Can't enable line numbers at specific code blocks when line number globally disalbled

### ISSUE THREAD

**Issue by coanor** [squidfunk/mkdocs-material#4909]
### Bug description

I'm globally disabled line numbers in my *mkdocs.yml*:

```yaml
markdown_extensions:
   pymdownx.highlight:
     anchor_linenums: true
     auto_title: false
     linenums: false  # <--- here
```

but some code sample need to show line number, so I checked the [docs](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-line-numbers), and add:

    ```py linenums="1"
    print "hello world"
    ```

and there is no number displayed. How to enable line number at specific positon when mkdocs.yml globally disabled?

### Related links

-  [ docs about line number](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-line-numbers)

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/10485722/example.zip)

### Steps to reproduce

1. Run `mkdocs serve`
2. Visit http://localhost:8000
3. Click Home page

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) or [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/bug-report/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/).

**Comment by facelessuser** [comment]
> Enable line numbers globally for block code. This will be ignored for inline code. If set to False line numbers will be disabled globally and can not be turned on, not even per code block.

Per the documentation. If you want line numbers off by default, but want to be able to turn them on per block, do not enable them globally, do not disable them globally, just set them per block as needed.

**Comment by squidfunk** [comment]
Thanks, @facelessuser! For completeness, the configuration must be changed to:

``` yaml
markdown_extensions:
   pymdownx.highlight:
     anchor_linenums: true
     auto_title: false
```
