### ISSUE TITLE
Adding videos: Youtube

### ISSUE THREAD

**Issue by philkunz** [squidfunk/mkdocs-material#492]
Would be super cool if there was a standard way for adding youtube videos in the spec and by that in the official docker image ;)

**Comment by facelessuser** [comment]
Isn't there already an easy way?

1. Just select share in youtube.
2. Select embed
3. Copy and paste HTML into your Markdown.

I don't think there needs to be a special syntax when Youtube makes it easy to get exactly what you need.

**Comment by makshh** [comment]
You can also use wrapper `div` for the `iframe` to keep aspect ratio:

For example:

```html
<div class="video-wrapper">
  <iframe width="1280" height="720" src="https://www.youtube.com/embed/vZNyjuNLhIk" frameborder="0" allowfullscreen></iframe>
</div>
```

```css
.video-wrapper {
  position: relative;
  display: block;
  height: 0;
  padding: 0;
  overflow: hidden;
  padding-bottom: 56.25%;
}
.video-wrapper > iframe {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  width: 100%;
  height: 100%;
  border: 0;
}
```
