### ISSUE TITLE
Minor style regression in left menu navigation

### ISSUE THREAD

**Issue by jmcx** [squidfunk/mkdocs-material#4985]
### Bug description

We are running mkdocs-material-8.5.8.

Our current left-menu looks like this:

![left-menu-orig](https://user-images.githubusercontent.com/5730842/216656055-0b1e350b-8782-4931-99ac-44b7fe1ae883.png)

When upgrading to 9.0.3, we're seeing a bad style in left menu navigation, with some entries greyed out. It appears that greyed out entries are those that don't have any content (are only containers for more menu items). 

![left-menu-issue](https://user-images.githubusercontent.com/5730842/216656356-37a09c83-862c-40ea-bc38-ddc5e23e17c2.png)

Could this be related to "Improved discernability of section index pages in navigation" in 9.0.3? 

We are using the index pages feature, but not all of the entries have an index page. 

Here is the relevant mkdocs.yaml section

```yaml
theme:
  name: material
  favicon: assets/images/favicon.ico
  logo: assets/images/tmLogo-white.png
  custom_dir: docs/overrides
  analytics:
    gtag: G-V4SM2FT345
  features:
  - content.code.annotate
  - content.tabs.link
  - navigation.indexes
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking

```

In fact we are open source, you can see our entire docs source here: https://github.com/triggermesh/docs/blob/main/mkdocs.yml

I have tried deactivating any custom styling, that didn't solve it either. 

Do you know if there are any workarounds to avoid this? We'd love to update to latest. 

### Related links

- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages

### Reproduction

...

### Steps to reproduce

...

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/reproduction/).
