### ISSUE TITLE
Less confusing edit_uri implementation

### ISSUE THREAD

**Issue by tyleraharrison** [squidfunk/mkdocs-material#5014]
### Context

(I'm actually unsure if this is intended behavior or not because the way it is implemented is so wacky)

## Summary

When setting the `edit_uri` to something like: `edit/main/docs/`, it looks like the word `edit` in the URI is automatically being parsed to the word `raw` for viewing. Generally, its probably bad practice to replace the string `edit` with `raw`. If someone is using a Git repo that has edit and view functionality but the URI does not have the word `edit` in it (or the viewing URI isn't `raw`), they will not be able to use the `content.action.view` feature. Below are some test results of trying different values for `edit_uri`:

| Test | edit_uri | Edit Link | View Link | Notes |
| --- | --- | --- | --- | --- |
| No `edit_uri` | Not set | `repo/edit/master/docs/` | `repo/raw/master/docs/` | Expected behavior |
| Include `edit` | `edit/main/docs/` | `repo/edit/main/docs/` | `repo/raw/main/docs/` | Expected behavior |
| Replace `edit` | `lorem_ipsum/main/docs/` | `repo/lorem_ipsum/main/docs/` | `repo/lorem_ipsum/main/docs/` | Generates the same URL |
| Omit `edit` | `main/docs/` | `repo/main/docs/` | `repo/main/docs/` | Generates the same URL |
| Move `edit` | `lorem_ipsum/edit/main/docs/` | `repo/lorem_ipsum/edit/main/docs/` | `repo/lorem_ipsum/raw/main/docs/` | Expected behavior (?) |

## Details

- Platform: I've tested with the following:
  - `Ubuntu 22.04.1 LTS, Linux kernel 5.17.5, x86_64` with Python `3.10.6`
  - Docker `python:3.9-alpine` image

- MkDocs version: `9.0.11`

- MkDocs-Material version: `1.4.2`

- `mkdocs.yml`:

```yaml
site_name: ...
site_url: ...
site_description: ...
site_author: ...
repo_url: https://github.com/(author name)/(repo name)
repo_name: (repo name)
remote_branch: main
edit_uri: 'edit/main/docs/'

nav:
    - Home: index.md

theme:
    name: material
    features:
        - content.action.edit
        - content.action.view
```

## Recommendations

I think the easiest way to do this is to allow the user to specify a `view_uri` and an `edit_uri`. Keeping the old `edit_uri` behavior should be fine, but in addition allow the use of `view_uri` to fix any mismatch in URIs.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)

### Use Cases

- Use other Git systems properly

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.
