### ISSUE TITLE
No php syntax hightlighting

### ISSUE THREAD

**Issue by tonoslav** [squidfunk/mkdocs-material#506]
For example in default template I get for

```
```php

...some random php code...
```
![image](https://user-images.githubusercontent.com/3399021/31783167-9fc026b0-b4fd-11e7-9072-793e3befd63c.png)

and in material

![image](https://user-images.githubusercontent.com/3399021/31783192-b2f1afd8-b4fd-11e7-8689-b11ddb24182a.png)

and in github

```php

class ProductName extends PzpProduct implements GeneralProductInterface
{
    /**
     * Required fields to get price
     *
     * @var array
     */
    protected $requiredForPrice = [];

    /**
     * Required fields to make contract
     *
     * @var array
     */
    protected $requiredForConctact = [];
```

If you somehow could make it at least GIT version I would be really grateful

btw really good job done with this template

**Comment by squidfunk** [comment]
Please see https://github.com/squidfunk/mkdocs-material/issues/138

**Comment by tonoslav** [comment]
Sorry

**Comment by squidfunk** [comment]
No worries. You can achieve it without the `<?php` tag when using PyMdown extensions, see thread.

**Comment by facelessuser** [comment]
In short, you'll have to migrate to using `pymdownx.highlight` instead of `markdown.extensions.codehilite`, but to save yourself some pain, configure it to use the `.codehilite` class as Material still has some corner cases that aren't fully supported for the default `.highlight` class that it uses. One of these days I plan to do a pull to fix those 😉 .

**Comment by tonoslav** [comment]
@facelessuser, @squidfunk 

Thank you,
I am not very good in Python, can you help me? 
Do I need to install something or ?

I have found that I should add 
```
markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
```

but after that it shows me errors when I run `mkdocs serve` and I am not even good at debuging python errors

So what should I do please?
