### ISSUE TITLE
Consider adding instructions for GitHub Actions deployment on other cloud platforms eg Azure

### ISSUE THREAD

**Issue by pacharanero** [squidfunk/mkdocs-material#5166]
### Description

The documentation shows instructions for GitHub and GitLab, but one limitation of GitHub Pages is that you can only have one site. If you want to deploy multiple branches to 'review' sites, you need to use a different platform. After some experimentation I have a GitHub Action which works for multiple deployments from PRs and branches on GitHub, to an Azure Static Web App.

### Related links

- https://squidfunk.github.io/mkdocs-material/publishing-your-site/

### Proposed change

I admit that you probably don't want to get into listing instructions for _every single_ cloud platform. But perhaps having some examples for more advanced setups is helpful.

In this case I have an Azure Static Web App set up to deploy all branches and PRs as a staging deployment. It means that we can preview any PRs or branches in a deployment before we merge into the live site.

(Note that the following is based on the CI Action which Azure automatically writes into the repo when you set up a Static Web App running from GitHub Actions, but with `actions/checkout` and `actions/setup-python` updated to v3 and v4 respectively, and the section for MkDocs installation and build inserted).

None of this is super hard to figure out but I just thought it might make a helpful addition to the docs, because it did take a little while to get it right.

```yaml
name: ALL-BRANCHES-ALL-PRs-build-and-deploy-to-azure.yml

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
permissions:
  contents: write
  pull-requests: write  # this permission is required in order to allow PR comment with staging URL
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy to Azure
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install git+https://${{ secrets.MATERIAL_FOR_MKDOCS_ACCESS_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
      - run: pip install -r requirements.txt
      - run: mkdocs build
      - name: Upload to Azure
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: "upload"
          production_branch: "main"
          app_location: "" # App source code path relative to repository root
          api_location: "" # Api source code path relative to repository root - optional
          output_location: "site" # Built app content directory, relative to app_location - optional

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
```
The user will need to insert their `AZURE_STATIC_WEB_APPS_API_TOKEN` into the repo Secrets in GitHub.

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)
