### ISSUE TITLE
Footnots extension take no effect

### ISSUE THREAD

**Issue by Roy-Kid** [squidfunk/mkdocs-material#5423]
### Bug description

I add `footnotes` to the `markdown_extension` fields and add `[^1]` to the markdown, but it take no effect

### Related links

- [footnotes](https://squidfunk.github.io/mkdocs-material/reference/footnotes/)

### Reproduction

Here is how I use it:

```
Two popular project layouts are used in python project, each one with its own set of pros and cons[^1]
```

Here is my yml file and I dont change any thing. To be honest that this problem is to simple that I don't know how to debug it.

```
site_name: Roy's Secret Garden

repo_name: Roy-Kid
repo_url: https://github.com/Roy-Kid

theme:
  name: material

  icon:
    repo: fontawesome/brands/github
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  language: en

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - header.autohide

plugins:
    - awesome-pages:
        filename: .index
        collapse_single_pages: true
        strict: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - footnotes

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Roy-Kid
      name: Roy's Github
  generator: false

copyright: Copyright &copy; 2023 Roy Kid

nav:
    - Home: 
      - Welcome: index.md
      - Curriculum Vitae: cv.md

    - ...
```

envs info:
```
ubuntu 20 @ WSL
latest chrome
Requirement already satisfied: mkdocs-material-extensions>=1.1  (1.1.1)
Requirement already satisfied: mkdocs>=1.4.2  (1.4.2)
```

### Steps to reproduce

1. add "footnotes" to yml
2. write a markdown
3. mkdocs build serve

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).
