### ISSUE TITLE
Update Changing the Colors section for Custom colors 

### ISSUE THREAD

**Issue by stevejr** [squidfunk/mkdocs-material#5427]
### Description

Update the Changing the Colors documentation so that it details how to use a custom color for the primary and accent settings.

Please refer to https://github.com/squidfunk/mkdocs-material/discussions/5424#discussioncomment-5731708 for the discussion behind this issue.

### Related links

- https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
- https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Amended documentation in 4006b4f04.

**Comment by odysseu** [comment]
Hi,
I am still having issues customiszing colors for my instance.
regarding the [custom-color-schemessection](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=green#custom-color-schemes) I am not sure what I should do if I want to toggle between a custom light mode and a custom dark mode:

```css
[data-md-color-scheme="youtube"] {
  --md-primary-fg-color:        #EE0F0F;
  --md-primary-fg-color--light: #ECB7B7;
  --md-primary-fg-color--dark:  #90030C;
}

[data-md-color-scheme="youtube-dark"] {
  --md-primary-fg-color:        #410404;
  --md-primary-fg-color--light: #5E4848;
  --md-primary-fg-color--dark:  #2E0104;
}
```

with 

```yaml
theme:
  palette:
    - media: "(prefers-color-scheme: light)" # when system pref is Light mode
          scheme: youtube
          toggle:
            icon: material/weather-sunny
            name: Passer en mode sombre
          primary: custom # to use custom palette
          accent: custom # to use custom palette
        - media: "(prefers-color-scheme: dark)" # when system pref is Dark mode
          scheme: insee-slate
          toggle:
            icon: material/weather-night
            name: Passer en mode clair
          primary: custom # to use custom palette
          accent: custom # to use custom palette
extra_css:
  - stylesheets/extra.css
```
