### ISSUE TITLE
Document changes in tags_compare option

### ISSUE THREAD

**Issue by wilhelmer** [squidfunk/mkdocs-material#5491]
### Description

In the latest Insiders version, the syntax for comparing tags irregardless of casing (using `tags_compare`) has changed.

Before:

```yml
plugins:
  - tags:
      tags_compare: !!python/name:material.plugins.tags.plugin.casefold
```

After:

```yml
plugins:
  - tags:
      tags_compare: !!python/name:material.plugins.tags.config.casefold
```

The [documentation](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/#+tags.tags_compare) should reflect this.

### Related links

https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/#+tags.tags_compare

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by Kojitaru** [comment]
I agree that something about the usage has changed, but it's not clear to me that the proposed change resolves it. Instead I see an error about a missing module, instead of missing content within an available module. Can you confirm the suggested update resolves errors for you?

**Comment by squidfunk** [comment]
[`abcc3f02b`](https://github.com/squidfunk/mkdocs-material-insiders/commit/abcc3f02b1d287ed3fbd984a453f8aaf71001ddc) moves the `casefold` function to the top of the plugin, and adds downward compatibility so that it can be imported from `.config` and `.plugin` as well. Honestly, this should've been a breaking change, but I haven't considered this when moving around the configuration files, so my fault. Now, all three sources will work, but the canonical way now is:

``` yaml
plugins:
  - tags:
      tags_compare: !!python/name:material.plugins.tags.casefold
```

I'll adjust the documentation in a sec.
