### ISSUE TITLE
only-light & only-dark for custom color schemes

### ISSUE THREAD

**Issue by ZachChristensen28** [squidfunk/mkdocs-material#5497]
### Description

I recently updated to the latest version of [9.1.11](https://github.com/squidfunk/mkdocs-material/releases/tag/9.1.11) and noticed that I now have both the light and dark images displayed for my light mode (dark mode was working as usual). After some investigation, I found this was due to my custom color scheme. Once I switched it back to the "default" color scheme, the images worked as before. 

**Example** - after upgrading

![Incorrect](https://github.com/squidfunk/mkdocs-material/assets/23529374/629e2376-feec-4cc2-a074-09b11d3a93c6)

**Expected** - this was the condition before upgrading

![Correct](https://github.com/squidfunk/mkdocs-material/assets/23529374/8661b79b-79b6-4a1b-8b68-05fe6a095c0c)

It took some digging, but I found in the [colors.scss](https://github.com/squidfunk/mkdocs-material/blob/1b3b8a719db8209c2bd9e6ee9ddaef5c78420fc7/src/assets/stylesheets/main/_colors.scss#LL51C3-L56C2) that the display was set to none when #only-dark is present. 

Once I added the following to my `extra.css` file, it returned the functionality to what was expected.

``` CSS
[data-md-color-scheme="my-color-scheme"] img[src$="#gh-dark-mode-only"],
[data-md-color-scheme="my-color-scheme"] img[src$="#only-dark"] {
    display: none;
}
```

### Related links

- [Image only light and only dark mode](https://squidfunk.github.io/mkdocs-material/reference/images/?h=dark#light-and-dark-mode)
- [Custom Color Schemes](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-color-schemes)

### Proposed change

I couldn't find anything in the docs to help fix this issue, and it may be worth mentioning to save others some time. 

My method that fixed it, but there may be a better one:

extra.css

``` CSS
[data-md-color-scheme="my-color-scheme"] img[src$="#gh-dark-mode-only"],
[data-md-color-scheme="my-color-scheme"] img[src$="#only-dark"] {
    display: none;
}
```

Where `my-color-scheme` is the custom color scheme.

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)
