### ISSUE TITLE
background_image for social plugin is not working

### ISSUE THREAD

**Issue by moizhassankh** [squidfunk/mkdocs-material#5510]
### Bug description

I am trying to add the background_image for the social card in the mkdocs.yml file but it is not working. the image is not used however, the card with all the text and logo is generated and populated correctly.

``` yml
plugins:
  - social:
      cards_layout_options:
        font_family: Open Sans
        color: "#FFFFFF"
        background_color: "#00000000"
        background_image: layouts/background.jpg
``` 

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Documentation ref for adding background image](https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/?h=background_image#+social.cards_layout_options.background_image)

### Reproduction

...

### Steps to reproduce

1. adding social plugin
2. installing the required frameworks such as pip install pillow cairosvg
3. adding the required params for the social cards, such as site title, description, and site url.
4. build the project, the card is there but the image is not used int he social card process.
(tried both with a jpg and png)

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).
