### ISSUE TITLE
Changing theme colors is broken

### ISSUE THREAD

**Issue by facelessuser** [squidfunk/mkdocs-material#552]
## Description

Changing palette colors is broken, and no matter what color you select, you get indigo.

```yaml
extra:
  palette:
    primary: blue
    accent: blue
```

### Expected behavior

Colors specified in palette to be applied.

### Actual behavior

No matter what color is defined, you get indigo.

### Steps to reproduce the bug

1. Try to apply a custom color via the mkdocs config above.
2. Run mkdocs serve.

### Package versions

* Python: python 3.6
* MkDocs: 0.17.1
* Material: 2.0.1

### Project configuration

Relevant options:

```yaml
extra:
  palette:
    primary: blue
    accent: blue
```

### System information

* OS: Any
* Browser: Any

**Comment by facelessuser** [comment]
Figured it out.  2.0.0 changes.

**Comment by KelSolaar** [comment]
Hi,

I have same issue with:

- mkdocs-0.17.3
- mkdocs-material-2.7.3

**Comment by squidfunk** [comment]
Colors now need to be defined using the `theme` options, see: [this link](https://squidfunk.github.io/mkdocs-material/getting-started/#color-palette). Does this fix your problem?

**Comment by KelSolaar** [comment]
@squidfunk : It did, thanks! Here is what I used for reference:

``` yaml
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue'
```
