### ISSUE TITLE
Pymdown extensions dependency issue

### ISSUE THREAD

**Issue by nvuillam** [squidfunk/mkdocs-material#5526]
### Context

Since pymdown-extensions v 10.0, it is not possible to refer to a markdown file located in a parent folder

https://github.com/facelessuser/pymdown-extensions/releases/tag/10.0

Would it be possible to define `restrict_base_path` to `false` by default, so we are not forced to downgrade pymdown-extensions to 9.11 so mkdocs-material works ? 

### Bug description

```sh
  File "/usr/local/lib/python3.11/site-packages/pymdownx/snippets.py", line 349, in parse_snippets
    raise SnippetMissingError("Snippet at path '{}' could not be found".format(path))
pymdownx.snippets.SnippetMissingError: Snippet at path '../CHANGELOG.md' could not be found
```

The folder structure is the following:

- CHANGELOG.md
- docs
  - CHANGELOG.md

The CHANGELOG.md located in the docs folder contains the following content

`--8<-- "../CHANGELOG.md"`

### Related links

- Failing Github Actions Job : https://github.com/oxsecurity/megalinter/actions/runs/5007402541/jobs/8973972701

### Reproduction

See bug description

### Steps to reproduce

See bug description

### Browser

Chrome, Safari, Edge, Firefox, Opera, Other

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by facelessuser** [comment]
If you have a few files outside of your `doc` folder, you can specify them in `base_path`. I do this myself.

```yaml
  - pymdownx.snippets:
      base_path:
      - docs/src/markdown/.snippets
      - LICENSE.md
      - SECURITY.md
```

**Comment by nvuillam** [comment]
My config is the following

```yaml
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
  - mdx_truly_sane_lists
  - attr_list
```

**Comment by facelessuser** [comment]
Okay, please see my earlier post: https://github.com/squidfunk/mkdocs-material/issues/5526#issuecomment-1552134945

**Comment by nvuillam** [comment]
I tried that but I have the same error :/

```yaml
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
      base_path: 
      - docs
      - CHANGELOG.md
      check_paths: true
  - mdx_truly_sane_lists
  - attr_list
```

**Comment by facelessuser** [comment]
Are you still using a relative path? Just use

```
--8<-- " CHANGELOG.md"
```

**Comment by facelessuser** [comment]
The amount of people who require `restrict_base_path` to be set to `False` should be very small, and even then, they can probably solve their issues by specifying better base paths. If they are doing really wacky things, and are adamant on that path, `restrict_base_path` can be disabled.

**Comment by nvuillam** [comment]
I tried updating the config, no crash anymore, but empty generated page :/

![image](https://github.com/squidfunk/mkdocs-material/assets/17500430/5d76ebbf-c5ad-4ffb-8505-8db0b9e35d79)

I'm probably not the only one to have such issue... could we consider adding an option to mkdocs-material so the legacy mode can be activated ?

```yaml
  - pymdownx.snippets:
      base_path: 
      - docs
      - CHANGELOG.md
      - LICENSE
      - .github/CONTRIBUTING.md
      check_paths: true
```

**Comment by facelessuser** [comment]
This does work. I'm literally doing this in my documentation. I do it for our licensing and have no issues. I am the maintainer of the snippets plugin. Double check your syntax, and if there is a real bug, I'm happy to fix it, but material is not the right place.

**Comment by facelessuser** [comment]
To be clear, here is a real world example:

- https://github.com/facelessuser/pymdown-extensions/blob/main/mkdocs.yml#L163
- https://github.com/facelessuser/pymdown-extensions/blob/main/docs/src/markdown/about/license.md

And the working rendered file:

- https://facelessuser.github.io/pymdown-extensions/about/license/

If you are truly having issues, please create a minimal, reproducible example, and I'd be happy to take a look.

**Comment by nvuillam** [comment]
I trust you have a working use case, but on [mine](https://github.com/oxsecurity/megalinter/blob/main/mkdocs.yml) it does not ^^

It might be related to something else in my configuration... I'll investigate, meanwhile I'll remain downgraded

Thanks again for your time :)

**Comment by facelessuser** [comment]
@nvuillam Your issue is related to the fact that you place `docs` in your `base_path` which has a `CHANGELOG.md` and then you add `../CHANGELOG.md` to your `base_path` as well. Snippets will look for the first base that has the specified file, which in your case is `CHANGELOG.md`. So the target tries to include itself. You don't seem to be sourcing any snippets from `docs`, so you can just remove it.

**Comment by facelessuser** [comment]
I wanted to nip this in the bud before people start thinking everything is broken. We can see it working locally here:

<img width="859" alt="Screenshot 2023-05-17 at 6 05 29 PM" src="https://github.com/squidfunk/mkdocs-material/assets/1055125/6f165b05-6365-46ac-94d8-e12b5f3a2cda">

**Comment by facelessuser** [comment]
An alternative to specifying all of your files individually may simply be to use the default `base_path` (which is `.`) And then make all of your snippets relative to that:

`CHANGELOG.md`, `.github/CONTRIBUTING.md`, `LICENSE`.

Anyways, hope this all helps for anyone running into similar issues.

**Comment by squidfunk** [comment]
Thanks for reporting. However, the functionality you're mentioning is not related to Material for MkDocs but to Pymdown Extensions, and thus impacts all MkDocs themes. We can't do anything about it here. Please take this upstream.

**Comment by TJohnson93** [comment]
> I trust you have a working use case, but on mine it does not ^^
> 
> It might be related to something else in [my configuration](https://github.com/oxsecurity/megalinter/blob/main/mkdocs.yml)... I'll investigate, meanwhile I'll remain downgraded
> 
> Thanks again for your time :)

Did you ever solve mate, I'm actually getting the same:

**Folder Structure**
```
- mkdocs.yml
- docs
    - includes
        - abbr.md 
```

**mkdocs.yml**
``` yaml
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets:
      check_paths: True
      # restrict_base_path: False
      base_path: docs/includes
      auto_append:
        - abbr.md
```

**Terminal**
``` bash
mkdocs  |   File "/usr/local/lib/python3.12/site-packages/pymdownx/snippets.py", line 351, in parse_snippets
mkdocs  |     raise SnippetMissingError("Snippet at path '{}' could not be found".format(path))
mkdocs  | pymdownx.snippets.SnippetMissingError: Snippet at path 'abbr.md' could not be found
mkdocs  | ERROR   -  [01:44:17] An error happened during the rebuild. The server will appear stuck until build errors are resolved.
```

**Comment by facelessuser** [comment]
@TJohnson93  I have no idea what you are doing exactly as you have not provided a minimal example, but here is a simple example that works. Use it as a guide.

[mkdocs_example.zip](https://github.com/squidfunk/mkdocs-material/files/12876200/mkdocs_example.zip)

**Comment by TJohnson93** [comment]
Thanks for your response @facelessuser, no idea what's going on either, everything in that minimal example I've got in my configuration. I've even run your example in a docker environment exactly as is and still receive the same error in terminal.

So in other words ran your example with the only additions being a 

**Dockerfile**
``` dockerfile
FROM python:3

RUN pip install --upgrade pip

COPY requirements.txt /tmp/
RUN pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org -r /tmp/requirements.txt
RUN ls
RUN mkdocs new mkdocs

EXPOSE 8000

WORKDIR / 

VOLUME /docs

ENTRYPOINT [ "mkdocs" ]

CMD [ "serve", "--dev-addr=0.0.0.0:8000" ]
```

**docker-compose.yml**
``` yaml
version: "3"

services:
  mkdocs-test:
    container_name: mkdocs-test
    build: .
    volumes:
      - C:\Users\[PATH]:/docs
      - C:\Users\[PATH]\mkdocs.yml:/mkdocs.yml
    ports:
      - "8124:8000"
```

**requirements.txt**
``` txt
mkdocs
mkdocs-material
mkdocs-material-extensions
mkdocs-swagger-ui-tag
fontawesome-markdown
mkdocs-git-revision-date-plugin
mkdocs-pdf-export-plugin
mkdocs-render-swagger-plugin
```
