### ISSUE TITLE
Custom color scheme problem: in dark mode, the link color is always indigo.

### ISSUE THREAD

**Issue by tamasg** [squidfunk/mkdocs-material#5537]
### Context

Hello,

sorry I can't remove the customization because that's the problem.

The following is my problem. Last year, I spent a lot of time with a graphic designer to understand how the material mkdocs work, to adapt the colors to our own image as recommended in the documentation. Everything worked last year, now I updated the insider to the lastest version and I found that in dark mode the color of the link is always indigo. Can't be customized.

Everything works in light mode and also in dark mode, only the ```--md-typeset-a-color:``` does not work. And own CSS colors also use Material MkDocs CSS variables for consistency.

There might have been a change that messed this up, because I see the documentation hasn't changed and everything else works. Maybe this is the issue: #5206

### Bug description

In dark mode, the link color is always indigo. It is not customizable, it worked correctly before.

```CSS
[data-md-color-scheme="slate"] {
  --md-typeset-a-color:  #CD3739 ;  // not work
}
```

![Snag_1eae5da6](https://github.com/squidfunk/mkdocs-material/assets/5910815/1aa41b5a-5593-4a1b-b78d-c18abbfbd801)

### Related links

- [Custom color schemes](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-color-schemes)
- [color definitions](https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/stylesheets/main/_colors.scss)
- Issue: #5206

An earlier sample that still works by accident is still available here:
[Sample](https://testmaterial.astrowo.com/samples/buttons/)

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/11526251/example.zip)

### Steps to reproduce

```mkdocs serve```

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by tamasg** [comment]
In the meantime, I checked, created a virtual environment and installed the last version before the PR #5206  (April 7 mkdocs-material-9.1.6-insiders-4.32.5), it still works correctly here. I hope this helps a bit.

Tamas

**Comment by tamasg** [comment]
Ahh, I found it.

https://github.com/squidfunk/mkdocs-material/discussions/5424
and
https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors

Only after a lot of reading did I realize that slate also needs ```custom```. If I understand the current new settings correctly (this really confused me), in the case of a custom color scheme it is not necessary to set it to ```custom```, because it is already custom. However, it must still be set for the slate.

It works here now.. I hope it saves someone else several hours, so custom color scheme config::

```yml
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: my-custom-color-scheme
      # primary: custom
      # accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
```

Martin, if I understand this correctly (it works for me now), please close the ticket. Thanks!

Tamas
