### ISSUE TITLE
[Question] Opening first subpage on click rather than expanding tree

### ISSUE THREAD

**Issue by johnmccabe** [squidfunk/mkdocs-material#563]
## Description

Been trying to figure out if the following expected behaviour is possible, it *seems* like it isn't, just wanted to confirm.

### Expected behaviour

Clicking on a Parent page in the doc outline on the left should expand the tree *and* open the first page in the list of sub pages.

### Actual behaviour

Current behaviour is that clicking expands the tree, but doesn't move to a new page.

![mkdocs_expand](https://user-images.githubusercontent.com/83862/32293039-d4099f50-bf39-11e7-9d16-b0ac5b31b6a9.gif)

### Steps to reproduce the bug

1. Create a doc with sub pages
2. Click on the parent item
3. You don't change page, only the tree expands

### Package versions

Using Docker: `squidfunk/mkdocs-material:2.0.2` 

### Project configuration

``` yaml
# Project information
site_name: Test Site
site_description: Test Site Description
site_author: Me

# Theme and overrides, i.e. language partial
theme: material

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

# Page tree
pages:
  - Home: getting-started/index.md
  - Architecture: getting-started/index.md
  - Parent Item:
    - Sub Item 1: getting-started/subitem1.md
    - Sub Item 2: getting-started/subitem2.md
    - Sub Item 3: getting-started/subitem3.md
  ```

### System information

* OS: Docker 17.09.0-ce on OSX 10.12.6
* Browser: Chrome 61.0.3163.100 on OSX 10.12.6
