### ISSUE TITLE
🥳 Material for MkDocs 9.2 – Beta

### ISSUE THREAD

**Issue by squidfunk** [squidfunk/mkdocs-material#5686]
__With the help of our awesome sponsors, I'm happy to announce that the '[Piri Piri](https://squidfunk.github.io/mkdocs-material/insiders/#12000-piri-piri)' funding goal has been reached, which means that amongst other awesome features, [the built-in blog plugin](https://squidfunk.github.io/mkdocs-material/blog/2022/09/12/blog-support-just-landed/) is finding its way into the community edition!__

__If you experience any problems, for now, please report them as a comment in this issue__.

## Installation

```
pip install mkdocs-material==9.2.0b3
```

> **Note** – This is a beta release, so please test thoroughly before deploying to production.

### Beta 0

- [x] Added blogging support via built-in blog plugin
- [x] Added Chinese language support to built-in search plugin
- [x] Added support for annotations (outside of code blocks)
- [x] Added support for navigation icons
- [x] Added support for navigation pruning
- [x] Added support for navigation status
- [x] Added support for customizing site icons
- [x] Improved rendering of (code) annotation markers
- [x] Improved print styles for (code) annotations
- [x] Improved customizability of navigation tabs
- [x] Removed Universal Analytics integration
- [x] Removed ancient polyfills to reduce size of bundled JavaScript by 20%

### Beta 1

- [x] Automatically download `ResizeObserver` polyfill when necessary – 54bef7bfe
- [x] Removed necessity for `Array.flat` and `Array.flatMap` polyfill – b37c668a9
- [x] Fixed announcement bar button being visible when JavaScript is not available – 320c85256
- [x] Added support for customizing (code) annotation icons –  f64d8658d
- [x] Added focus outline to admonitions and details – 3e34f6c72

### Beta 2

- [x] Fixed rendering of tags when announcement bar is present – ef448ed94
- [x] Improved plugin inter-op with external tools like mike – ab178b2bc221603321bfdbf88ea5baa347d1fd63
- [x] Updated MkDocs to 1.5.0 – 571f12978
 
### Beta 3

- [x] Added support for adding date of last update to blog posts
- [x] Fixed [#5599](https://github.com/squidfunk/mkdocs-material/issues/5599): Insufficient contrast for default link color

### Unreleased

- [x] Fixed [#5826](https://github.com/squidfunk/mkdocs-material/issues/5826): Blog post drafts with tags show up in tags index – https://github.com/squidfunk/mkdocs-material/commit/15c024cbbfd1ed747df1ca20a81c8b2860c7da8c
- [x] Tags index renders links to excluded pages – https://github.com/squidfunk/mkdocs-material/commit/15c024cbbfd1ed747df1ca20a81c8b2860c7da8c
- [x] Switched info plugin to importlib to mitigate deprecations – 0be617276
- [x] Automatically focus and bring up keyboard on touch devices – 50f455ec0
- [x] Added prompt for bug report name to info plugin – 554976f90
- [x] Added Luxembourgish translations – 245278b7

### Changes to `mkdocs.yml`

None.

### Changes to customizations

If you've customized Material for MkDocs with theme overrides, and added your own partials, you need to update the following partials, as they got updated with new functionality. If you don't update them, you'll not be able to use some of the new features:

- [`footer.html`](https://github.com/squidfunk/mkdocs-material/pull/5683/files#diff-af930b4baa9b1ea53b5a05513c58b1abb5af7848d4c53394bf752c55455d86b2)
- [`header.html`](https://github.com/squidfunk/mkdocs-material/pull/5683/files#diff-70a179faf78bd9f0688cfb1feae409bd13411145b6a1fd63069ca5f7412136c1)
- [`language.html`](https://github.com/squidfunk/mkdocs-material/pull/5683/files#diff-051727c72bfe4c13c312723820b5a669491762194ce74f66062ae25cf8b3d2ce)
- [`nav-item.html`](https://github.com/squidfunk/mkdocs-material/pull/5683/files#diff-fa37d36fb2ba3d0b185c0a8a05606472170b05c2bb97a2829bd8f3682c865252)
- [`nav.html`](https://github.com/squidfunk/mkdocs-material/pull/5683/files#diff-39e05314d54106afb967405bee50adf1c3d23fd9a59c01dd4a345efd92bd3086)
- [`search.html`](https://github.com/squidfunk/mkdocs-material/pull/5683/files#diff-a1457f75c3b127808b3061d13ae786fab6985cc76d1499c172d84d230fe5e6a9)
- [`tabs-item.html`](https://github.com/squidfunk/mkdocs-material/pull/5683/files#diff-402ef5e72304d83e9b23301b9adfafb43b852b43f6224838fb70fb39022b7f1c)
- [`tabs.html`](https://github.com/squidfunk/mkdocs-material/pull/5683/files#diff-5a9c33947e82e57b191d9870b958a73238986ef51f303964a30629db475f7a5b)

You can check the full list of changes here:
https://github.com/squidfunk/mkdocs-material/pull/5683/files

## Closing thoughts

We're super happy to finally give the built-in blog plugin into the hands of all users, so we can improve it even more. Before issuing the final release, we'll take the opportunity to refactor some edges that need a little polishing and incorporate your feedback.

❤️ ❤️ ❤️

Thanks again to all of our awesome sponsors for making our work on this project possible in the first place! Without you, all of those features would not exist. We hope for your continued support, as it allows us to ship more useful and unique features, like for example the latest improved social plugin, which allows to [build entirely custom social cards](https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/#customization).

**Comment by HonkingGoose** [comment]
> - Added support for navigation pruning

I tried the 9.2 beta on my simple Git Gosling site, and enabled navigation pruning. The beta "feels slower to load new pages" compared to the production deployment, which uses the latest non-beta. To confirm the new beta slowed things down, I had the beta in production for a short while, which _still_ felt slower than normal.

I don't know how I can quantify this slowdown, or if there really is a slowdown. Or maybe navagation pruning slows down the instant page loading feature.

**Comment by squidfunk** [comment]
@HonkingGoose Thanks for the feedback. That's surprising and "feels slower" is hard to quantify. However, there might always be side effects between features, and given that Material for MkDocs has a gazillion of them, anticipating all possible side effects is quite an impossible task. If you deploy the beta without enabling any new features, does it also "feel slower"? Could you try to quantify the slowness? Does the side load longer? Also, what version did you have in production before? I read that you have instant loading enabled, which got a complete rewrite 4 months ago in 9.1.4. Without knowing exactly what changes you applied, we can only guess – as always 😊

If you find the time, a side-by-side comparison with runnable examples would be amazing. I'm sure we can mitigate the issues that you now observe. Additionally, Beta 1 will ship a 20% smaller JavaScript bundle, so our general expectation is that 9.2.0 will feel faster than before. Furthermore, navigation pruning should not impact instant loading in any way. It should actually even speed it up, because the pages to download are smaller due to reduced navigation. Finally, you should measure if navigation pruning is actually benefiting your site, as it hugely depends on your navigation structure.

**Comment by HonkingGoose** [comment]
> @HonkingGoose Thanks for the feedback. That's surprising and "feels slower" is hard to quantify. However, there might always be side effects between features, and given that Material for MkDocs has a gazillion of them, anticipating all possible side effects is quite an impossible task. If you deploy the beta without enabling any new features, does it also "feel slower"? Could you try to quantify the slowness? Does the side load longer? Also, what version did you have in production before? I read that you have instant loading enabled, which got a complete rewrite 4 months ago in 9.1.4. Without knowing exactly what changes you applied, we can only guess – as always 😊

Production is currently using these dependencies:

```
mkdocs-material==9.1.18
mkdocs==1.4.3
```

<details><summary>Select me to see production <code>mkdocs.yml</code> file</summary>

```yaml
# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Git Gosling

strict: true

repo_name: HonkingGoose/git-gosling
repo_url: https://github.com/HonkingGoose/git-gosling
edit_uri: edit/main/docs/

theme:
  name: material

  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.top
    - navigation.instant
    - toc.integrate
    - toc.follow
    - content.action.edit
    - navigation.footer

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - abbr
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

nav:
  - Home: "index.md"
  - Git Basics:
      - "git_basics/short_introduction_to_git.md"
  - Getting Started:
      - "getting_started/conventions.md"
      - "getting_started/installing_git.md"
      - "getting_started/create_a_github_account.md"
      - "getting_started/configuring_git.md"
      - "getting_started/getting_help_with_git.md"
  - The Nano text editor:
      - "the_nano_text_editor/introduction_to_the_nano_text_editor.md"
  - Git Sandbox:
      - "git_sandbox/setup_your_git_sandbox.md"
      - "git_sandbox/shell_expansion.md"
      - "git_sandbox/explore_your_git_sandbox.md"
      - "git_sandbox/introduction_to_git_status.md"
      - "git_sandbox/create_a_new_file_and_track_it.md"
      - "git_sandbox/making_your_first_commit.md"
      - "git_sandbox/add_extra_lines_to_file.md"
      - "git_sandbox/use_git_restore_to_undo_things.md"
      - "git_sandbox/create_a_new_branch.md"
      - "git_sandbox/switching_between_branches.md"
      - "git_sandbox/your_first_merge.md"
      - "git_sandbox/create_your_first_github_repo.md"
      - "git_sandbox/editing_a_file_on_github.md"
      - "git_sandbox/merge_pull_request.md"
      - "git_sandbox/fetching_changes_merging_git_pull.md"
      - "git_sandbox/check_the_repository_history_with_git_log.md"
  - Recommendations:
      - "recommendations/use_a_gitignore_file.md"
      - "recommendations/split_up_your_commits.md"
      - "recommendations/write_good_commit_messages.md"
      - "recommendations/git_aliases.md"
      - "recommendations/use_a_linter.md"
      - "recommendations/dealing_with_merges.md"
      - "recommendations/use_a_dependency_bot.md"
      - "recommendations/testing_and_github_actions.md"
  - Advanced Topics:
      - "advanced_topics/working_with_large_files.md"
      - "advanced_topics/advanced_git_configuration.md"
      - "advanced_topics/contribute_to_a_project_by_forking.md"
      - "advanced_topics/clean_up_your_git_history.md"
      - "advanced_topics/use_git_bisect_to_find_bugs.md"
      - "advanced_topics/github_cli.md"
  - Further Resources:
      - "further_resources/recommended_reading.md"
  - License: "license.md"
```

</details>

I created three branches on my [`git-gosling` repository](https://github.com/HonkingGoose/git-gosling):

1. `reproduction/current-production-frozen-branch`, this is my current production site with `mkdocs-material==9.1.18`
2. `reproduction/material-for-mkdocs-beta-nine-two` where I only upgrade to `9.2.0b0`
3. `reproduction/upgrade-and-navigation-pruning` with the upgrade to `9.2.0b0` plus enabling navigation pruning

The easiest way to test is to use GitHub Codespaces or Gitpod, or you may use a local environment.

Run `make` to install the dependencies, then after run `make serve` to get the preview site. You may also combine both steps with `make && make serve`.

**Comment by squidfunk** [comment]
Thanks for the reproductions.

> Have you tried measuring the performance via the Network tab in Firefox/Chrome developer tools?

Jup, this is exactly what we need. Some numbers would be amazing, because "feels slow" is not really quantifiable for us. Happy to help, and Material for MkDocs should feel fast at all times, but we need more data 😊

**Comment by Valastiri** [comment]
> Thanks for the reproductions.
> 
> > Have you tried measuring the performance via the Network tab in Firefox/Chrome developer tools?
> 
> Jup, this is exactly what we need. Some numbers would be amazing, because "feels slow" is not really quantifiable for us. Happy to help, and Material for MkDocs should feel fast at all times, but we need more data 😊

I'm unsure if this would be immediately helpful since it's an entirely different project but did a test in a local env using `9.1.18` and `9.2.0b0` with network tab just as a sanity check. 

Anecdotally i didn't experience any difference in navigation even on our staging build on vercel. Although I figured a local test would be better to showcase.

```
Local System

W10
Python 3.10.0 
```

## Network tab in Chrome

---

**9.1.18 Local Build**
![reg-speed](https://github.com/squidfunk/mkdocs-material/assets/1619968/92af1492-2855-4cdc-8878-887321af311a)

**9.2.0b0 Local Build**
![beta-speed](https://github.com/squidfunk/mkdocs-material/assets/1619968/f8139066-b6c4-4b18-a8ab-c821c7e631c9)

---

No Cache 

**9.1.18 Local Build**
![reg-nch-speed](https://github.com/squidfunk/mkdocs-material/assets/1619968/47a6575b-4447-493e-8f02-4d68c22a7fce)

**9.2.0b0 Local Build**
![beta--nch-speed](https://github.com/squidfunk/mkdocs-material/assets/1619968/214ae356-4daf-48e7-820d-5838e30bcc9f)

**Comment by squidfunk** [comment]
@Valastiri thanks for the benchmarks! What I read from that (no cache case):

- `DOMContentLoaded` is faster: 343ms -> 317ms (-8%)
- `Load` is faster: 493ms -> 417ms (-16%)

> We are using awesome-pages plugin for our navigation though.

That is only relevant during build time, since it assemble your `nav` entry automatically, but shouldn't have any penalty when navigating in the browser.

**Comment by Valastiri** [comment]
Yes apologies I forgot to summarize! It does indeed have better performance based on my tests and I couldn't replicate any perceived slowdowns. 

Great to feature to have looking forward to release!

**Comment by johnthagen** [comment]
@squidfunk Excited for the new page `icon` support.

Is it possible to use a custom icon? We have a bunch of custom SVG icons that we use in our application and mirror in the user guide.

What I'm imaging is passing a relative path to a small SVG file:

```md
---
icon: ../static/icons/icon.svg
---
```

Thanks for the consideration!

**Comment by squidfunk** [comment]
@johnthagen yes, of course, just set up [additional icons](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#additional-icons) and you're good to go!

**Comment by johnthagen** [comment]
@squidfunk Some more feedback, we used to host our custom SVG icons as static files, and we could use them both in the body and page titles so that they would show up at the top of the page next to the title.

When we moved to `overrides`, we to change the image path from a path to a `static` folder within `docs` to the new `overrides`:

```md
![][custom_icon]{ width=36 } Title

[custom_icon]: ../../overrides/.icons/custom/icon.svg
```

But this produces a warning:

```
WARNING  -  Documentation file 'pages/page.md' contains a link to '../overrides/.icons/custom/icon.svg' which is not found in the documentation files.
```

If we change to 

```yaml
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
```

```md
# :custom-icon: Title
```

Then the page renders properly (the emoji is in the Title block), but the emoji identifier is in the navigation bar:

<img width="225" alt="Screen Shot 2023-07-11 at 9 14 40 AM" src="https://github.com/squidfunk/mkdocs-material/assets/10340167/4ea516aa-437e-4a2d-bb08-27e27889f479">

Should emoji identifiers be stripped from the navigation bar?
