### ISSUE TITLE
Code highlighting colours the whole line in --md-code-hl-color

### ISSUE THREAD

**Issue by mocdaniel** [squidfunk/mkdocs-material#6017]
### Context

I'm working on a freshly setup instance of Material for MkDocs and code highlighting seems to be off, compared to the results [shown in the docs](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#highlighting-specific-lines).

<img width="693" alt="strange code highlighting" src="https://github.com/squidfunk/mkdocs-material/assets/28064429/2434b4d4-350e-4879-bc93-937db90c5983">

### Bug description

Compared to the example from the docs, the result rendered on my end is

a) yellowish instead of blue

b) renders the whole line in `--md-code-hl-color` instead of just the left border and the remainder in `--md-code-hl-color` according to my dev tools:

```css
.highlight .hll {
    background-color: var(--md-code-hl-color);
    display: block;
    margin: 0 -1.1764705882em;
    padding: 0 1.1764705882em;
}
```

My related configuration looks like this, I went by the book, i.e. the docs, if not mistaken:

```yaml
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      line_spans: __span
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
```

### Related links

I took a good look at the `pygments`/`Highlight` configuration:
- [https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight)

as well as the docs regarding how to do highlighting and how to theme it:
- [https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#highlighting-specific-lines](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#highlighting-specific-lines)
- [https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#custom-syntax-theme](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#custom-syntax-theme)

I managed to get the bluish highlight working this way, but it still covered the whole line in the darker variant and omitted the `--light` variant altogether.

### Reproduction

[9.3.1-highlight-wrong-css.zip](https://github.com/squidfunk/mkdocs-material/files/12611942/9.3.1-highlight-wrong-css.zip)

### Steps to reproduce

1. Enable code highlighting as per my example and the documentation linked above
2. Run `mkdocs serve` or `mkdocs build`
3. Open the result and see code highlighting be different from the examples in the docs linked above

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).
