### ISSUE TITLE
Document use of Chinese language in search (Japanese stemmer)

### ISSUE THREAD

**Issue by cyent** [squidfunk/mkdocs-material#613]
## Description

There are not found any words if search Simplified Chinese(zh) words

### Package versions

* Python: 2.7.10
* MkDocs: 0.16.3
* Material: 1.10.1

### Project configuration

``` yaml
site_name: Go语言学习 - cyent笔记
site_description: 关于Go语言学习，包含许多个人理解
site_author: cyent
site_url: https://cyent.github.io/golang/

repo_name: 'cyent/golang'
repo_url: 'https://github.com/cyent/golang'

theme: material

extra:
  palette:
    primary: 'Blue Grey'
    accent: 'Pink'
  feature:
    tabs: false
  social:
    - type: github
      link: https://github.com/cyent

markdown_extensions:
    - admonition
    - codehilite(guess_lang=false,linenums=false)
    - toc(permalink=true)
    - footnotes
    - meta
    - def_list
    - pymdownx.arithmatex
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_png
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde
```

### System information

I build the docs with mkdocs serve/build in MacOS、CentOS7.3，and test the search in MacOS Safari、chrome、firefox、IE 10.
