### ISSUE TITLE
Full width of screen custom css

### ISSUE THREAD

**Issue by mogthesprog** [squidfunk/mkdocs-material#619]
Hi,

Love the theme, definitely the best one for use with mkdocs. Great work.

I'm trying to see if it's possible to make the theme full width, instead of the central column that you see on regular monitors. 

I've tried adding custom css to modify `.md-main` and `.md-main__inner`, to remove the width, but i'm not having much luck. It seems that when i change `.md-main` and set `width: 100%`, the right sidebar is now in the middle of the central column of content.

Is there a simple way to achieve what i'm after (few lines in `extra.css`) or is this likely to consume lots of time getting the CSS right? 

Cheers,

**Comment by squidfunk** [comment]
Nope, that's not easily possible due to the sidebars, I'm sorry.

**Comment by mogthesprog** [comment]
No worries. Thanks for the quick response! 

Cheers,

**Comment by makshh** [comment]
@mogthesprog I don't know if you are looking for something like that but you can try this:

```css
@media only screen and (min-width: 76.25em) {
  .md-sidebar--secondary {
    right: 0;
    margin-left: 0;
    -webkit-transform: none;
    transform: none;   
  }
  .md-sidebar--primary {
    left: 0;
  }
  .md-main__inner {
    max-width: none;
  }
}
```
