### ISSUE TITLE
KaTeX not rendering correctly

### ISSUE THREAD

**Issue by letian-w** [squidfunk/mkdocs-material#6276]
## Bug

KaTeX does not render array environment correctly.

The following is rendered correctly.

```
$$
\begin{array}{rcl}
E(X) & = & \displaystyle\sum_{k=0}^n k \cdot ({}_n C_k) p^k q^{n-k}\\\\
     & = & \displaystyle\sum
\end{array}
$$
```

The following results in the entire math section being rendered as raw code in a paragraph.

```
$$
\begin{array}{rcl}
E(X) & = & \displaystyle\sum_{k=0}^n k \cdot ({}_n C_k) p^k q^{n-k}\\\\
     & = & \displaystyle\sum_{k=0}
\end{array}
$$
```

Note the only difference is that I added `_{k=0}` to the second line of the equation.

## Expecting

Copy and paste the following code into [this KaTeX demo tool](https://sixthform.info/katex/examples/demo.html) to see how it should be rendered.

```
\[
\begin{array}{rcl}
E(X) & = & \displaystyle\sum_{k=0}^n k \cdot ({}_n C_k) p^k q^{n-k}\\\\
     & = & \displaystyle\sum_{k=0}
\end{array}
\]
```

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [How it should look like](https://sixthform.info/katex/examples/demo.html)

### Reproduction

[bug.zip](https://github.com/squidfunk/mkdocs-material/files/13234393/bug.zip)

### Steps to reproduce

1. get the right dependencies
    ```
    mkdocs==1.5.3
    mkdocs-material-insiders==9.4.2
    ```
3. run `mkdocs serve`

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by letian-w** [comment]
Turns out the following works, where the underscore must be escaped following empty curly braces. This is NOT the default behavior of KaTeX. Guessing it has something to do with your parsing.

```
$$
\begin{array}{rcl}
E(X) & = & \displaystyle\sum_{k=0}^n k \cdot ({}_n C_k) p^k q^{n-k}\\\\
     & = & \displaystyle\sum_{k=0}
\end{array}
$$
```

$$
\begin{array}{rcl}
E(X) & = & \displaystyle\sum_{k=0}^n k \cdot ({}\_n C_k) p^k q^{n-k}\\\\
     & = & \displaystyle\sum_{k=0}
\end{array}
$$

The following also works.

```
$$
\begin{array}{rcl}
E(X) & = & \displaystyle\sum_{k=0}^n k \cdot ({}^n C_k) p^k q^{n-k}\\\\
     & = & \displaystyle\sum_{k=0}
\end{array}
$$
```

**Comment by facelessuser** [comment]
The docs have a section on [KaTeX](https://squidfunk.github.io/mkdocs-material/reference/math/?h=katex#katex), but unfortunately it doesn't make it very clear that you need something like [Arithmatex](https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/#loading-katex) to preserve the content so that it doesn't get parsed by the Markdown parser. I think it is mentioned in MathJax, but not KaTeX. Try enabling it in your config:

```yaml
site_name: Test
site_url: https://example.com

theme:
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - assets/javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
````

<img width="883" alt="Screenshot 2023-11-01 at 11 26 58 PM" src="https://github.com/squidfunk/mkdocs-material/assets/1055125/afd6e11c-01fd-486f-8d19-a236b5bcdfcf">
