### ISSUE TITLE
New .admonition/.details injects padding into *any* last-child

### ISSUE THREAD

**Issue by facelessuser** [squidfunk/mkdocs-material#630]
## Description

Currently Material is assigning any element that is a *last-child* with padding.  This is bad.  So the math elements have some children who or *last-child* to their parent even if they are not direct children. of `.admonition`.  Since they are descendants, they inherit the padding.

Something like `.admonition>:last-child` and `details>:last-child` would be more appropriate. as it would limit the padding the last *direct* child.

Please see issue: https://github.com/facelessuser/pymdown-extensions/issues/187.

### Expected behavior

Padding should *only* be applied to the last direct descendant of `.admonition` or `details`.

### Actual behavior

Any element that qualifies as a *last-child* is inheriting bottom padding.

### Steps to reproduce the bug

1. NA

### Package versions

* Material: 2.2.1 &amp; 2.2.2

### Project configuration

https://github.com/facelessuser/pymdown-extensions/blob/master/mkdocs.yml

### System information

* OS: NA
* Browser: NA

**Comment by facelessuser** [comment]
On a side note, I also question this case as it is also very aggressive, but I don't think I see any side effects of it, but maybe should be evaluated.

```css
.md-typeset .admonition :first-child, .md-typeset details :first-child {
    margin-top: 0;
}
```

**Comment by facelessuser** [comment]
I'll probably try and throw together a pull this week.  I figure the `first-child` should probably be `parent>:nth-child(2)` and `last-child` should probably be `parent>:last-child`.

**Comment by makshh** [comment]
```css
.md-typeset .admonition :first-child,
.md-typeset details :first-child {
  margin-top: 0;
}
```

Is this necessary at all?
