### ISSUE TITLE
add a docker compose section to your documentation on hub.docker.com

### ISSUE THREAD

**Issue by TimChaubet-I4U** [squidfunk/mkdocs-material#6357]
### Description

Please add a base docker compose script to the readme.md on the docker hub, for the next guy needing it.
As I cannot find it it your github repo, I assume you maintain this readme.md elsewhere.
May I suggest this:
```
version: "3.8"

x-volume-localtime:
  &etclocaltime
  type: 'bind'
  source: /etc/localtime
  target: /etc/localtime
  read_only: true
x-volume-mkdocs:
  &mkdocs
  type: 'bind'
  source: /path/on/host/mkdocs
  target: /docs
  bind:
    create_host_path: true

services:
  mkdocs:
    image: squidfunk/mkdocs-material
    restart: unless-stopped
    environment:
      - TZ=Europe/Brussels
      - UID=0
      - GID=0
    volumes:
      - <<: *etclocaltime
      - <<: *mkdocs
    entrypoint: sh -c
    ports:
      - 8000:8000
    command: ["if [ ! -d '/docs/docs' ]; then mkdir /docs/docs; mkdocs build; fi; mkdocs serve -v --watch-theme --dev-addr=0.0.0.0:8000;"]
```

### Related links

- [Reporting a docs issue](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/)

### Before submitting

- [X] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)
