### ISSUE TITLE
Add the ability to hide a comment in a block code

### ISSUE THREAD

**Issue by Fredouye** [squidfunk/mkdocs-material#6358]
### Description

Hi !

I'm using [Gitleaks](https://github.com/gitleaks/gitleaks) to scan Markdown files before they are processed by Material for MkDocs. When a secret is found, pipeline is halted and HTML output is not built.

Gitleaks can ignore secrets by adding this [comment](https://github.com/gitleaks/gitleaks#gitleaksallow) :

```
class CustomClass:
    discord_client_secret = '8dyfuiRyq=vVc3RRr_edRk-fK__JItpZ'                 #gitleaks:allow
```

It works as expected, however when this comment is placed inside a block code, it gets rendered in the HTML output :

```
```yaml
services:
  netbox:
    environment:
      REMOTE_AUTH_ENABLED: "True"
      REMOTE_AUTH_BACKEND: "netbox.authentication.LDAPBackend"
      AUTH_LDAP_SERVER_URI: "ldap://dc01.demo.corp"
      AUTH_LDAP_BIND_DN: "CN=Bind,CN=Users,DC=demo,DC=corp"
      AUTH_LDAP_BIND_PASSWORD: "XXXXXXXXXX"                                           #gitleaks:allow
```

Would it be possible to hide comments in a block code ?

Thanks in advance.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
-

### Use Cases

Add an hidden comment in a block code.

### Visuals

<img width="707" alt="Capture d’écran 2023-11-18 à 08 05 39" src="https://github.com/squidfunk/mkdocs-material/assets/22211821/283d558b-cb3f-4f7b-945a-d1a01ba25915">

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.
