### ISSUE TITLE
Include Admonition "example" qualifier

### ISSUE THREAD

**Issue by harveyslash** [squidfunk/mkdocs-material#646]
## Description

The docs say admonition allows for custom qualifier, and mkdocs-material adds a few of its own. 
There is no example to use a custom icon and color for the blocks. 

I would like to use 5 new icons for documenting a RESTful api(and access them with my own qualifier), but couldn't find any documentation on how to do so

**Comment by facelessuser** [comment]
I just took a look at the Material style to figure out how to add my own: https://github.com/facelessuser/pymdown-extensions/blob/master/docs/src/scss/_admonition.scss.  Also, details should inherit the same stuff: https://github.com/facelessuser/pymdown-extensions/blob/master/docs/src/scss/_details.scss.

I'm no web developer, so if you see a better approach, feel free to chime in, but it seems to work for my purposes:  https://facelessuser.github.io/pymdown-extensions/extensions/details/

**Comment by harveyslash** [comment]
thanks for replying so quickly. 
I am not familiar with this, so I am not sure how to add your file. 
Right now I have just a docs folder, and the yml config file.

How can I configure it like you have?

**Comment by facelessuser** [comment]
Probably you avoid use SCSS and just use CSS to avoid having to transpile it over to CSS.  I just ran my theme through an unminifier: https://github.com/facelessuser/pymdown-extensions/blob/master/docs/theme/extra-4e53a56959.css.

You would be particularly interested in the following.  Just an explanation, I am adding something called `settings` and `example`.

```css
.md-typeset .admonition.settings, .md-typeset details.settings {
    border-left: .4rem solid #a0f;
}
.md-typeset .admonition.settings>.admonition-title, .md-typeset details.settings>.admonition-title, .md-typeset details.settings>summary {
    border-bottom: .1rem solid rgba(170, 0, 255, .1);
    background-color: rgba(170, 0, 255, .1);
}
.md-typeset .admonition.settings>.admonition-title:before, .md-typeset details.settings>.admonition-title:before, .md-typeset details.settings>summary:before {
    color: #a0f;
    content: "settings"}
.md-typeset .admonition.example, .md-typeset details.example {
    border-left: .4rem solid #6200ea;
}
.md-typeset .admonition.example>.admonition-title, .md-typeset details.example>.admonition-title, .md-typeset details.example>summary {
    border-bottom: .1rem solid rgba(98, 0, 234, .1);
    background-color: rgba(98, 0, 234, .1);
}
.md-typeset .admonition.example>.admonition-title:before, .md-typeset details.example>.admonition-title:before, .md-typeset details.example>summary:before {
    color: #6200ea;
    content: "format_list_numbered"}
```

You can use that as an example and put it in your own CSS file and use the `extra_css` in your `mkdocs.yml` file to add the changes like I do: https://github.com/facelessuser/pymdown-extensions/blob/master/mkdocs.yml#L116.
