### ISSUE TITLE
FR: Parity with GitHub Admonitions

### ISSUE THREAD

**Issue by matchavez** [squidfunk/mkdocs-material#6667]
### Description

Parity with GitHub Admonitions
---
GitHub has adopted Admonitions that are effectively backwards-compatible blockquotes. These differ from `!!!` python-style Admonitions.

The request is that for each of the blockquotes that render as Admonitions, MfM renders them in the same output as current Admonitions for compatibility.

```
> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!TIP]
> Optional information to help a user be more successful.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

> [!CAUTION]
> Negative potential consequences of an action.
```

> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!TIP]
> Optional information to help a user be more successful.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

> [!CAUTION]
> Negative potential consequences of an action.

### Related links

- [Github Admonitions](https://github.com/orgs/community/discussions/16925)

### Use Cases

The use case for this additional rendering is to allow direct copy-paste reuse of raw markdown without losing formatting. 

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. This is essentially about adding new Markdown syntax, which we consider upstream for the most part. Material for MkDocs tries to limit itself to post-processing of the HTML originating from Markdown parsing, and to the presentation of this HTML, the actual theme.

Thus, we consider it out of scope. Note that there are several alternative extensions for callouts/admonitions, most notably [markdown-callouts](https://oprypin.github.io/markdown-callouts/index.html). Maybe you can ask the authors if they would like to support your proposed use case.

**Comment by wanghaoyucn** [comment]
Hi guys. I also want to use GFM admonition and I think I made it.
Here is a python markdown extension [markdown-gfm-admonition](https://github.com/dahlia/markdown-gfm-admonition). 
I just add `pip install markdown-gfm-admonition` into the github actions script and then add config below into `mkdocs.yml`. Then I achieve this feature. Hope it can help.

```yaml
markdown_extensions:
  - markdown_gfm_admonition
```

**Comment by wanghaoyucn** [comment]
> Hi guys. I also want to use GFM admonition and I think I made it. Here is a python markdown extension [markdown-gfm-admonition](https://github.com/dahlia/markdown-gfm-admonition). I just add `pip install markdown-gfm-admonition` into the github actions script and then add config below into `mkdocs.yml`. Then I achieve this feature. Hope it can help.
> 
> ```yaml
> markdown_extensions:
>   - markdown_gfm_admonition
> ```

I must point out that it only support Note Tip Important Warning Caution, in another word, only types that github supports.

**Comment by jayqi** [comment]
markdown-callouts ended up adding this in v0.4.0: https://github.com/oprypin/markdown-callouts/releases/tag/v0.4.0

It would be great if mkdocs-material could point to these extensions in the admonitions documentation.

**Comment by mihaigalos** [comment]
These work well for Note, Tip and Warning. Important and Caution's styles are the same as Note - why? Can you reproduce?

```
> [!NOTE]  
> Highlights information that users should take into account,
> even when skimming.

> [!TIP]
> Optional information to help a user be more successful.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

> [!CAUTION]
> Negative potential consequences of an action.
```

Result:
<img width="1017" alt="Screenshot 2024-06-12 at 22 53 32" src="https://github.com/squidfunk/mkdocs-material/assets/16443090/15d44d77-8bb0-4e17-8b3f-5f2c59a221d1">

I don't think this is a markdown-gfm-admonition bug but a mkdocs-material bug, since that generates a `div` of different types:
<img width="357" alt="Screenshot 2024-06-12 at 22 56 28" src="https://github.com/squidfunk/mkdocs-material/assets/16443090/2e29ad30-1fd7-4ecf-890d-3c6e6e05035f">

**Comment by alexvoss** [comment]
This is not a bug since there never was a promise to support these admonition types. There is a [list of supported admonition types](https://squidfunk.github.io/mkdocs-material/reference/admonitions/?h=admoni#supported-types) in the documentation and there are [instructions for custom types](https://squidfunk.github.io/mkdocs-material/reference/admonitions/?h=admoni#custom-admonitions). So, you should be able to add the `important` and `caution` types yourself.

**Comment by mihaigalos** [comment]
This is awesome, thanks a lot! Works now.

**Comment by squidfunk** [comment]
As a side note. our admonition types predate what GitHub now supports by several years. We might look into harmonizing it in the future, but in the past, when we tried to do that and removed `seealso` and several other redundant types/qualifiers, there was some push back.

**Comment by mihaigalos** [comment]
Yes, that certainly makes sense.

I've reexported the SVG paths from GH and reencoded them in CSS and could render correctly. I'm leaving them here if you want to use to extend this project:

```css
.md-typeset .admonition {
  display: block;
  max-width: fit-content;
  margin: 10px;
}

:root {
  --md-admonition-icon--important: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M0 1.75C0 .784.784 0 1.75 0h12.5C15.216 0 16 .784 16 1.75v9.5A1.75 1.75 0 0 1 14.25 13H8.06l-2.573 2.573A1.458 1.458 0 0 1 3 14.543V13H1.75A1.75 1.75 0 0 1 0 11.25Zm1.75-.25a.25.25 0 0 0-.25.25v9.5c0 .138.112.25.25.25h2a.75.75 0 0 1 .75.75v2.19l2.72-2.72a.749.749 0 0 1 .53-.22h6.5a.25.25 0 0 0 .25-.25v-9.5a.25.25 0 0 0-.25-.25Zm7 2.25v2.5a.75.75 0 0 1-1.5 0v-2.5a.75.75 0 0 1 1.5 0ZM9 9a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z"/></svg>');
  --md-admonition-icon--caution: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M4.47.22A.749.749 0 0 1 5 0h6c.199 0 .389.079.53.22l4.25 4.25c.141.14.22.331.22.53v6a.749.749 0 0 1-.22.53l-4.25 4.25A.749.749 0 0 1 11 16H5a.749.749 0 0 1-.53-.22L.22 11.53A.749.749 0 0 1 0 11V5c0-.199.079-.389.22-.53Zm.84 1.28L1.5 5.31v5.38l3.81 3.81h5.38l3.81-3.81V5.31L10.69 1.5ZM8 4a.75.75 0 0 1 .75.75v3.5a.75.75 0 0 1-1.5 0v-3.5A.75.75 0 0 1 8 4Zm0 8a1 1 0 1 1 0-2 1 1 0 0 1 0 2Z"/></svg>');

}

.md-typeset .admonition.important,
.md-typeset details.important {
  border-color: rgb(152, 110, 226);
}
.md-typeset .important > .admonition-title,
.md-typeset .important > summary {
  background-color: rgba(152, 110, 226, 0.1);
}
.md-typeset .important > .admonition-title::before,
.md-typeset .important > summary::before {
  background-color: rgb(152, 110, 226);
  -webkit-mask-image: var(--md-admonition-icon--important);
          mask-image: var(--md-admonition-icon--important);
}

.md-typeset .admonition.caution,
.md-typeset details.caution {
  border-color: rgb(229, 83, 75);
}
.md-typeset .caution > .admonition-title,
.md-typeset .caution > summary {
  background-color: rgba(229, 83, 75, 0.1);
}
.md-typeset .caution > .admonition-title::before,
.md-typeset .caution > summary::before {
  background-color: rgb(229, 83, 75);
  -webkit-mask-image: var(--md-admonition-icon--caution);
          mask-image: var(--md-admonition-icon--caution);
}
```
Result:
![Screenshot 2024-06-13 at 10 59 54](https://github.com/squidfunk/mkdocs-material/assets/16443090/96b3591b-6247-4580-bfb9-f0591ae08ef8)

**Comment by cdwilson** [comment]
FYI, in case somebody runs across this in the future like I did:

Here's an update to the "Caution" and "Important" CSS from @mihaigalos with updated icon SVG and colors that more closely match the style of the other icons used in the material theme (i.e. filled in instead of the outline style used on GitHub).

```css
:root {
  --md-admonition-icon--important: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M 1.75,1.5 A 0.25,0.25 0 0 0 1.5,1.75 v 9.5 c 0,0.138 0.1120001,0.25 0.25,0.25 h 2 a 0.75,0.75 0 0 1 0.75,0.75 v 2.189453 l 2.7207031,-2.71875 A 0.749,0.749 0 0 1 7.75,11.5 h 6.5 A 0.25,0.25 0 0 0 14.5,11.25 V 1.75 A 0.25,0.25 0 0 0 14.25,1.5 Z M 7.8339844,3.0195313 A 0.75,0.75 0 0 1 8.75,3.75 v 2.5 a 0.75,0.75 0 0 1 -1.5,0 V 3.75 A 0.75,0.75 0 0 1 7.8339844,3.0195313 Z M 8,8 A 1,1 0 0 1 9,9 1,1 0 0 1 7,9 1,1 0 0 1 8,8 Z"/></svg>');
  --md-admonition-icon--caution: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path d="M 5.3105469,1.5 1.5,5.3105469 V 10.689453 L 5.3105469,14.5 H 10.689453 L 14.5,10.689453 V 5.3105469 L 10.689453,1.5 Z M 8,4 a 0.75,0.75 0 0 1 0.75,0.75 v 3.5 a 0.75,0.75 0 0 1 -1.5,0 V 4.75 A 0.75,0.75 0 0 1 8,4 Z m 0,6 a 1,1 0 0 1 0,2 1,1 0 0 1 0,-2 z"/></svg>');

}

.md-typeset .admonition.important,
.md-typeset details.important {
  border-color: #7c4dff;
}

.md-typeset .important>.admonition-title,
.md-typeset .important>summary {
  background-color: #7c4dff1a;
}

.md-typeset .important>.admonition-title::before,
.md-typeset .important>summary::before {
  background-color: #7c4dff;
  -webkit-mask-image: var(--md-admonition-icon--important);
  mask-image: var(--md-admonition-icon--important);
}

.md-typeset .admonition.caution,
.md-typeset details.caution {
  border-color: #ff1744;
}

.md-typeset .caution>.admonition-title,
.md-typeset .caution>summary {
  background-color: #ff17441a;
}

.md-typeset .caution>.admonition-title::before,
.md-typeset .caution>summary::before {
  background-color: #ff1744;
  -webkit-mask-image: var(--md-admonition-icon--caution);
  mask-image: var(--md-admonition-icon--caution);
}
```

When using this markdown:

> [!NOTE]
> Useful information that users should know, even when skimming content.

> [!TIP]
> Helpful advice for doing things better or more easily.

> [!IMPORTANT]
> Key information users need to know to achieve their goal.

> [!WARNING]
> Urgent info that needs immediate user attention to avoid problems.

> [!CAUTION]
> Advises about risks or negative outcomes of certain actions.

the result (when used with [markdown-gfm-admonition](https://github.com/dahlia/markdown-gfm-admonition)) looks like this:

<img width="710" alt="image" src="https://github.com/user-attachments/assets/38d772fa-3f51-4c6d-98aa-a1040f4193fa">
