### ISSUE TITLE
Tags listing is empty

### ISSUE THREAD

**Issue by normandy7** [squidfunk/mkdocs-material#6679]
### Context

We have been using a relatively simple tags setup in which we

1. tag each page individually,
2. have a `tags.md` index page that simply lists all the tags.

For now, we just want to keep our current setup after the tags plugin was redone.

### Bug description

Since the tags plugin was redone, I can't get the tags listing to display. Nothing renders where `<!-- material/tags -->` is called.

Out of the extra configuration options, we only use `tags_allowed`. As far as I can tell, the only necessary adjustment should be to change the tags marker from `[TAGS]` to `<!-- material/tags -->`.

It does not matter whether we keep or remove the `tags_file` property and reference the `tags.md` page in the nav -- the tags listing is not rendered either way.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags
- https://squidfunk.github.io/mkdocs-material/plugins/tags/

### Reproduction

I can't provide a reproduction because we build with Insiders and I don't have "manual" access to it.

I did, however, remove all customizations as prescribed in the guidelines, but it did not affect the tags issue.

### Steps to reproduce

`mkdocs.yml` snippet:

```
plugins:
  - meta
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|\.(?!\d)'
  - tags:
      tags_allowed:
        - admin
        - collaboration
        - comparison
        - debugging
        - model-registry
        - platform
        - reproducibility
        - versioning
        - source-code
        - time-series
        - computer-vision
        - nlp
        - tabular-data
  - typeset

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      base_path: ["./reuse/"]
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: "#"
      permalink_title: Link to section
      toc_depth: 3
```

### Browser

- Chrome
- Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).
