### ISSUE TITLE
Search doesnt work with specific locale

### ISSUE THREAD

**Issue by majkinetor** [squidfunk/mkdocs-material#678]
## Description

I am entering documentation on Serbian latin and cyrilic. Latin contains only few non-englih letters, cyrilic on the other hand is completelly different. 

Search works on latin, but not for words containing those few letters. Search on cyrillic doesnt work at all.

### Package versions

* Python: ` 3.6.4`
* MkDocs: `0.17.2`
* Material: `2.5.2`

### Project configuration

``` yaml
site_name: [removed]
site_url:  [removed]
site_description: [removed]

                            
theme: 
    name: material
    custom_dir: custom_theme

extra_css:
    - _css/extra.css

extra:
    doc_version: 2018-01-24 23:55

markdown_extensions:
    # https://pythonhosted.org/Markdown/extensions/index.html
    - toc:
        permalink: ↵
    - admonition
    - footnotes
    - codehilite
    - meta
    - abbr
    - sane_lists
    - def_list
    #https://facelessuser.github.io/pymdown-extensions/    
    - pymdownx.snippets
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist(custom_checkbox=true)
    - pymdownx.tilde
    - pymdownx.keys
    - pymdownx.details
pages:
   ....
```

### System information

* OS: Windows 10
* Browser: Any

**Comment by squidfunk** [comment]
Please try using the Russian Stemmer:

```
extra:
  search:
    language: ru
```

**Comment by majkinetor** [comment]
No changes.

**Comment by squidfunk** [comment]
Please post some example text from your docs that is not searchable.

**Comment by majkinetor** [comment]
Here is the [gist](https://gist.github.com/majkinetor/b9e493a9aa4fb0216439e945a285a7dd) with screen details and page that is shown in the sample.

Notice that latin seems to works even when **ž** is there (word not underlined tho), but if the word starts with it, it returns nothing, like **žena (women)**.

**Comment by squidfunk** [comment]
Well, there's no stemmer for the serbian language in lunr-languages, so the only thing you can do is to try other stemmers. I thought Russian would be the closest, but maybe another stemmer works better.

**Comment by majkinetor** [comment]
Ok. Thanks a lot for explanation.

**Comment by squidfunk** [comment]
Try the turkish stemmer:

``` yaml
extra:
  search:
    language: tr
```

It works with the example you provided
