### ISSUE TITLE
Instant Preview w/ Content Tab

### ISSUE THREAD

**Issue by santaimpersonator** [squidfunk/mkdocs-material#6875]
### Bug description

When enabling the instant preview feature, the rendering of a linked content tab only show the tabs and not the content below:
![image](https://github.com/squidfunk/mkdocs-material/assets/36016723/0e528139-19d0-47f2-9169-df0da626d75f)

### Related links

- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-previews
- https://github.com/squidfunk/mkdocs-material/issues/6704

### Reproduction

Unfortunately, the build file for the reproduction was 80MB (and too big); probably due to all the images stored. _(*I'll work on processing my commits to the project, so I can submit a reproduction later this week)_

However, the site can be reproduced from our repository:
https://github.com/sparkfun/SparkFun_GNSS_mosaic-X5

*Just enable the instant preview feature globally*:
```yml
# Configuration for webpage theme
theme:
  # Features to Include (ref. theme documentation)
  features:
    # Enables instant previews globally, for all internal links
    - navigation.instant.preview
```

### Steps to reproduce

1. Clone our repo: https://github.com/sparkfun/SparkFun_GNSS_mosaic-X5
2. Enable the instant preview feature globally in the `mkdocs.yml` file
    ```yml
    # Configuration for webpage theme
    theme:
      # Features to Include (ref. theme documentation)
      features:
        # Enables instant previews globally, for all internal links
        - navigation.instant.preview
    ```
2. Install the mkdocs-material _v9.5.12_ + insiders _v4.53.0_
3. Install the required plugins (or disable them in the `mkdocs.yml` file)
    ```bash
    sudo apt-get install pngquant
    pip install mkdocs-monorepo-plugin mkdocs-redirects mkdocs-git-authors-plugin mkdocs-git-revision-date-localized-plugin mkdocs-git-committers-plugin-2 Pillow 'mkdocs-material[imaging]'
    ```
4. Serve the site locally
    ```bash
    mkdocs serve
    ```
5. Navigate to a section, where the `PPS Output` section is linked and hover over it
    - For example: http://127.0.0.1:8000/SparkFun_GNSS_mosaic-X5/hardware_overview/#status-leds
        ![image](https://github.com/squidfunk/mkdocs-material/assets/36016723/c5b2d43d-b121-4026-be4e-81c3d2bc7cc8)
    - It should produce a preview of this part of the documentation: http://127.0.0.1:8000/SparkFun_GNSS_mosaic-X5/hardware_overview/#pps-output
        ![image](https://github.com/squidfunk/mkdocs-material/assets/36016723/7808d1d9-6592-409b-8293-dfd567ea0922)

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [x] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [x] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).
