### ISSUE TITLE
Add urls in the navbar

### ISSUE THREAD

**Issue by diegoferigo** [squidfunk/mkdocs-material#707]
How can I add an entry in the navbar linking to an external resource (e.g. a doxygen documentation)? I'd like to do something like this:

```yaml
pages:
- Home: index.md
- Documentation: http://website.com/doc/index.html
```

Or, if the doxygen page is inside the same repository:

```yaml
pages:
- Home: index.md
- Documentation: ../doc/index.html
```

Where the path is relative to the `docs_dir` folder.
