### ISSUE TITLE
codeblock inside a !!! note

### ISSUE THREAD

**Issue by franckl** [squidfunk/mkdocs-material#718]
I would like the code block that you can see here inside the note. Is it possible ?

![image](https://user-images.githubusercontent.com/3875803/36678826-10770e94-1b12-11e8-99fc-9e9c46a4a7c9.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/3875803/36678787-f4801e06-1b11-11e8-93eb-605b10bba41d.png)

### Steps to reproduce the bug

!!! note
	Borders are evaluated only at the time `plot` or `buildmesh` is called so the global variable are defined  at this time andhere since $r$ is changed between the two border calls the following code will not work because the first border will be computed with r=0.3:

	```cpp
	   real r=1;    border a(t=0,2*pi){ x=r*cos(t); y=r*sin(t);label=1;}
	   r=0.3    ;   border b(t=0,2*pi){ x=r*cos(t); y=r*sin(t);label=1;}
	   mesh Thwithhole   = buildmesh(a(50)+b(-30)); // bug (a trap) because
	   // the two circle have the same radius = $0.3$
	```
### Package versions

Python 2.7.10
mkdocs, version 0.17.2
* Material: 2.6.0

### Project configuration

``` yaml
site_name: mysite
pages:
  - Introduction: index.md
theme:
  feature:
    tabs: true
  name: 'material'
  favicon: 'images/favicon.png'
  logo: 'images/favicon.png'

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML
  - mathjax-config.js

markdown_extensions:
  - codehilite:
      guess_lang: false
      linenums: true
  - mdx_math
  - pymdownx.tasklist
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  - toc:
      permalink: '#'
  - admonition

```
