### ISSUE TITLE
Annotation doesn't work inside markdown tables

### ISSUE THREAD

**Issue by adhadse** [squidfunk/mkdocs-material#7195]
### Context

I'm trying with latest mkdoks-material (9.5.23) and following the reference for adding annotation. I know annotation doesn't work inside katex, so I tried adding it outside, and since tables also can't add the annotation with `{ .annotate }` I tried wrapping the table inside inside a `<div class="annotate">`.
![image](https://github.com/squidfunk/mkdocs-material/assets/56764399/74b0a8b6-3627-41f3-bc5d-c96d7ffbb6be)

- Currently it appears at the top left of the page and sticks there, instead of sticking to the annotation button.

### Bug description

I tried something like this:

```markdown
<div class="annotate" markdown>
| $P$                                 | $Q$                                 | $P \implies Q$                         |
| ----------------------------------- | ----------------------------------- | -------------------------------------- |
| $\textcolor{#f56c42}{\text{false}}$ | $\textcolor{#f56c42}{\text{false}}$ | $\textcolor{#07fc03}{\text{true}}$ (1) |  
| $\textcolor{#f56c42}{\text{false}}$ | $\textcolor{#07fc03}{\text{true}}$  | $\textcolor{#07fc03}{\text{true}}$ (2) |
| $\textcolor{#07fc03}{\text{true}}$  | $\textcolor{#f56c42}{\text{false}}$ | $\textcolor{#f56c42}{\text{false}}$    |
| $\textcolor{#07fc03}{\text{true}}$  | $\textcolor{#07fc03}{\text{true}}$  | $\textcolor{#07fc03}{\text{true}}$     |
</div>

1. The formula doesn't state when $P$ is _not true_, it's assumed maybe the robot has antenna, maybe it doesn't.
2. The formula doesn't state when $P$ is _not true_, it's assumed maybe the robot has antenna, maybe it doesn't.
```
This does produce the annotation button, but upon clicking it doesn't show the annotation text.

### Related links

- [Annotations](https://squidfunk.github.io/mkdocs-material/reference/annotations/)

### Reproduction

[9.5.23-annotation-inside-table-does-not-appear.zip](https://github.com/squidfunk/mkdocs-material/files/15372256/9.5.23-annotation-inside-table-does-not-appear.zip)

### Steps to reproduce

1. The above zip file includes all the required things to reproduce the above bug.
2. Install mkdocs-material 9.5.23
3. Set `mkdocs.yaml` as :

```yaml
site_name: My Docs

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.details
  - admonition
  - footnotes
  - attr_list
  - tables
  - md_in_html

plugins:
  - info
```
4. add table content as:
```markdown

<div class="annotate" markdown>
| hello | world|
| ---   | --- |
| i     | text (1)|
</div>

1. a text should be shown test 1
```

### Browser

Edge

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).
