### ISSUE TITLE
Tag Replacements

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [squidfunk/mkdocs-material#7363]
### Context

This- is a use-case to assist with normalization of projects involving logs of tags.

The idea is to add functionality which would allow replacing specific tags, with other tag(s).

### Description

.

### Related links

[Setting up tags](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/)

### Use Cases

1. The ability to basically add a replacement feature for existing tags. (lets say, you have multiple tags which are extremely similar, you can use this functionality to coalesce them into a single tag)
2. The ability to define a single tag, which would then be replaced with a group of tags. This- can be useful for when you are commonly working on pages, docs, etc, which may span multiple topics, and instead of needing to define multiple tags for each of the topics spanned- you can define a single tag, which will be automatically replaced/aggregated.

### Visuals

Inside of the existing tags configuration, I would imagine something like this:

``` yaml
plugins:
  - tags:
    replacements:
        # This example would replace any tags named "project a stuff", with only "project a"
      - tag: project a stuff
        replacements:
          - project a
        # This example would replace any tags named "stuff", with "organized-stuff", but, would also retain the "stuff" tag
      - tag: stuff
        replacements:
          - organized-stuff
        retain_original: true
        # This example, would replace "complex-tag" with two additional tags.
      - tag: complex-tag
        replacements:
          - ProjectX/ProjectXSubCategory
          - AnotherTag
```

Example schema:

``` yaml
plugins:
  - tags:
      replacements:
        - tag: string
          replacements:
            - string
          retain_original: boolean (optional) # Should the original tag be retained?
```

Essentially, the TLDR; is a feature to centrally replace and aggregate tags.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for reporting! We're currently considering this feature request an edge case. However, you can easily add the functionality yourself with a hook and `config.extra` ☺️ Something like the following should work (untested):

``` py
def on_page_markdown(self, markdown, *, page, config, files):
    for item in config.extra.get("tag_replacements", []):
        if item.tag in page.meta.tags:
            page.meta.tags.extend(item.replacements)
            if not item.retain_original:
                page.meta.tags.remove(item.tag)
```

Then, in `mkdocs.yml`:

``` yaml
extra:
  tag_replacements:
    - tag: complex-tag
      replacements:
        - ProjectX/ProjectXSubCategory
        - AnotherTag
      retain_original: true
```

Closing as resolved via customization.
