### ISSUE TITLE
Missing Sidebar

### ISSUE THREAD

**Issue by Shdwfx** [squidfunk/mkdocs-material#741]
## Description

Many thanks for this beautiful theme. I can not see the headings 1 I marked with # on sidebar.

``` markdown
lorem ipsum

# sidebar menu 1

lorem...
``` 

### Expected behavior

I expected to see the sidebar.

### Actual behavior

sidebar is missing. There is only "home" and site "site_name" in the sidebar section.

### Steps to reproduce the bug

1. Installed mkdocs
2. installed material theme.
3. Edit .md files typora
4. serve with mkdocs

### Package versions

Python 3.6.4
mkdocs, version 0.17.3
Material Version: 2.7.0

### Project configuration

``` yaml
# Project information
site_name: Service Documentation
site_description: 'Configuration Doc'
site_author: 'shdwfx'
site_url: 'https://www.example.com'
# Copyright
copyright: 'copyright text.'
# Configuration
theme:
  name: 'material'
  language: 'en'
  show_sidebar: true
  palette:
    primary: 'orange'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
# Customization
extra:
    feature:
        tabs: true
  social:
    # - type: 'github'
      # link: 'https://github.com/squidfunk'
    - type: 'twitter'
      link: 'https://twitter.com/shdwfx'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/shdwfx/'
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
# Installed theme
    # amelia
    # cerulean
    # cosmo
    # cyborg
    # flatly
    # journal
    # readable
    # simplex
    # slate
    # spacelab
    # united
    # yeti
    # material

```

### System information

* OS: Wndows 10
* Browser: Firefox 59.01
