### ISSUE TITLE
scroll issue when link anchor is in a table header

### ISSUE THREAD

**Issue by franckl** [squidfunk/mkdocs-material#746]
## Description
An html pointing to an anchor inside a table will scroll the page at the wrong position. The anchor text is hidden behing the top navigation bar.

### Expected behavior
The scroll should take into account the height of the top navigation bar

### Steps to reproduce the bug
![kapture 2018-03-28 at 23 41 28](https://user-images.githubusercontent.com/3875803/38057995-970e0fde-32e1-11e8-924a-4707b20dc600.gif)

### Package versions
* Python: `2.7.10`
* MkDocs: `0.17.2`
* Material: `2.6.0`

### Project configuration
``` yaml
theme:
  feature:
    tabs: true
  name: 'material'
  favicon: 'images/favicon.png'
  logo: 'images/favicon.png'

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML
  - mathjax-config.js

markdown_extensions:
  - codehilite:
      guess_lang: false
      linenums: true
  - mdx_math
  - pymdownx.tasklist
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  - toc:
      permalink: '#'
  - admonition
  - pymdownx.superfences
  - pymdownx.progressbar
```

### System information

* OS: osx 10.13.3
* Browser: chrome v64
