### ISSUE TITLE
How to add Toggle line selection in code blocks?

### ISSUE THREAD

**Issue by asibhossen897** [squidfunk/mkdocs-material#7483]
### Description

Hello there!
I was exploring mkdocs-material to setip a project of myself. I wanted to add the `Toggle line selection` option to my code blocks.
But I didn't find how to do that. I've also searched in the documentaion. Could you please specify?

![image](https://github.com/user-attachments/assets/dfd1d498-5e8b-4a8f-a4f9-a8cae3fb374a)

This is my `mkdocs.yml` file.

```yaml
site_name: Python Mastery
site_url: https://python-mastery.github.io/
theme:
  name: material
  highlightpy: true
  font:
    code: JetBrains Mono
    text: Hind Siliguri
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/lightbulb-auto
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to system preference
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  extra:
    -css: css/extra.css
  
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en
repo_name: python-mastery/python-mastery.github.io
repo_url: https://github.com/python-mastery/python-mastery.github.io
nav:
  - Home: index.md
  - Tutorials: tutorials/index.md
  - Python: tutorials/python/index.md

plugins:
- search
- mkdocstrings
- include-markdown

extra:
  generator: false

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
```

### Related links

- [Reporting a docs issue](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/)
- https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-selection-button

### Before submitting

- [X] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)
