### ISSUE TITLE
can not set favicon.ico myself

### ISSUE THREAD

**Issue by wangliang1989** [squidfunk/mkdocs-material#754]
## Description

I put the file of favicon.ico in docs/img/,and write "site_favicon: img/favicon.ico" in mkdocs.yml

### Expected behavior

see myself favicon

### Actual behavior

I can not see myself favicon(If I use the default theme, it works)

### Steps to reproduce the bug

1. put favicon.ico file in docs/img/
2. write "site_favicon: img/favicon.ico" in mkdocs.yml
3. mkdocs serve

### Package versions

* Python: `Python 3.6.2 :: Anaconda custom (x86_64)`
* MkDocs: `mkdocs, version 0.17.3`
* Material: `Version: 2.7.1`

### Project configuration

``` yaml
site_name: Oh My CAP
pages:
    - 引言: index.md
    - 写给初学者: intro.md
    - 安装: install.md
    - 快速开始: quick-start.md
    - 流程:
        - 流程介绍: procedures/intro-to-procedures.md
        - 计算格林函数: procedures/gflib.md
        - 数据预处理: procedures/preprocess.md
        - 反演: procedures/inversion.md
    - 修订历史: changelog.md
    - 代码差异: code-diffs.md
theme: material
site_favicon: img/favicon.ico

markdown_extensions:
    - admonition
    - codehilite(guess_lang=false,linenums=false)
    - toc(permalink=true)
    - footnotes
    - meta
    - def_list
    - pymdownx.arithmatex
    - pymdownx.betterem(smart_enable=all)
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_png
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde
extra_javascript:
    - 'js/extra.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
```

### System information

* OS: Mac
* Browser:Chrome

https://seismology.xyz/docs/
https://github.com/wangliang1989/docs
