### ISSUE TITLE
Can't display the code block with continuous gray line in the quote environment.

### ISSUE THREAD

**Issue by walkccc** [squidfunk/mkdocs-material#758]
## Description

Can't display the code block with continuous gray line in the quote environment.

### Expected behavior

Something like this(other theme):

<img width="994" alt="screen shot 2018-04-12 at 19 00 41" src="https://user-images.githubusercontent.com/14782909/38673436-e2f485ce-3e83-11e8-84af-4b3ea2d5446b.png">

### Actual behavior

1.
<img width="683" alt="screen shot 2018-04-12 at 19 01 26" src="https://user-images.githubusercontent.com/14782909/38673469-fa585722-3e83-11e8-87c4-10661393d7e4.png">

2.
<img width="722" alt="screen shot 2018-04-12 at 19 01 40" src="https://user-images.githubusercontent.com/14782909/38673471-fa843ec8-3e83-11e8-984e-e8635a5b6d4d.png">

### Steps to reproduce the bug

Here I paste my codes:

1.
    > given the coefficients $a\_0, a\_1, \ldots, a\_n$ and a value of $x$:
    >
    > ```cpp
    >     y = 0
    >         for i = n down 0
    >         y = ai + x * y
    > ```
    >
    > **a.** In terms of $\Theta$-notation, what is the running time of this code fragment for Horner's rule?

2.
    > given the coefficients $a\_0, a\_1, \ldots, a\_n$ and a value of $x$:
    >
    ```cpp
        y = 0
            for i = n down 0
            y = ai + x * y
    ```
    >
    > **a.** In terms of $\Theta$-notation, what is the running time of this code fragment for Horner's rule?

### Package versions

* Python: 3.6
* MkDocs: 0.17.3
* Material: 2.7.2

### Project configuration

``` yaml
site_name: CLRS Solutions
theme:
  name: 'material'

repo_name: walkccc/CLRS
repo_url: https://github.com/walkccc/CLRS

extra_javascript:
  - 'javascripts/extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML'

pages:
  - Preface: index.md
  - I Foundations:
    - 1 The Role of Algorithms in Computing:
      - 1.1 Algorithms: Chap01/1.1.md
      - 1.2 Algorithms as a technology: Chap01/1.2.md
      - Chap 1 Problems:
        - Problem 1-1: Chap01/Problems/1-1.md
    - 2 Getting Started:
      - 2.1 Insertion sort: Chap02/2.1.md
      - 2.2 Analyzing algorithms: Chap02/2.2.md
      - 2.3 Designing algorithms: Chap02/2.3.md
      - Chap 2 Problems:
        - 2-1 Insertion sort on small arrays in merge sort: Chap02/Problems/2-1.md
        - 2-2 Correctness of bubblesort: Chap02/Problems/2-2.md
        - 2-3 Correctness of Horner's rule: Chap02/Problems/2-3.md
        - 2-4 Inversions: Chap02/Problems/2-4.md

```

### System information

* OS: macOS High Sierra Version 10.13.4
* Browser: I think it's not relevant.

By the way, the theme is awesome, thank you!
