### ISSUE TITLE
Can't link to the correct website by clicking the fontAwesome icon in the footer.

### ISSUE THREAD

**Issue by walkccc** [squidfunk/mkdocs-material#759]
## Description

Can't link to the correct website by clicking the fontAwesome icon in the footer.
I guess this is because they're in the same domain.

### Expected behavior

Link to the website I specified.

### Actual behavior

It refreshed the page.

### Steps to reproduce the bug

First, specify the link in the `mkdocs.yml`.
Second, click the fontAwesome icon. It can't link to the correct website.

### Package versions

* Python: 3.6.3
* MkDocs: 0.17.3
* Material: 2.7.2

### Project configuration

``` yaml
extra:
  social:
    - type: 'github'
      link: 'https://github.com/walkccc'
    - type: 'gamepad'
      line: 'https://walkccc.github.io/MemoryGame'
```

The link to `github` works properly, but the link to `gamepad` doesn't (it just refresh the page.)

### System information

* OS: macOS High Sierra Version 10.13.4
* Browser: Safari, Chrome
