### ISSUE TITLE
Add support for dark syntax highlighting

### ISSUE THREAD

**Issue by Akkadius** [squidfunk/mkdocs-material#768]
Not so much an issue as it is for anyone else who finds it useful

Saw a few other threads that posted about this but not one that had it 100% - made a few tweaks on my own including the clipboard highlighter

Make sure in your mkdocs.yml you have the following

```
markdown_extensions:
  - codehilite:
      guess_lang: false
      use_pygments: true
      noclasses: true
      pygments_style: monokai
```

And then use an extra.css file as such

```
extra_css:
  - css/extra.css
```

In that file use

```css
pre { color: white !important; }

.md-clipboard:before {
    color: rgb(255, 255, 255);
}

.codehilite:hover .md-clipboard:before,.md-typeset .highlight:hover .md-clipboard:before,pre:hover .md-clipboard:before {
    color: rgba(255, 255, 255, 0.54) !important
}
```

Yields

![image](https://user-images.githubusercontent.com/3319450/39166160-dce0ccec-474d-11e8-8197-2000d5dc0212.png)
