### ISSUE TITLE
The default tag icon does not take effect

### ISSUE THREAD

**Issue by Xiaokang2022** [squidfunk/mkdocs-material#7688]
### Bug description

When I configure the content of the configuration file as follows, the default icon of the tag does not take effect:

```yaml
site_name: My Docs

theme:
  name: material
  icon:
    tag:
      default: material/tag

plugins:
  - tags
```

This is what *index.md* is about:

```markdown
---
tags:
  - tag1
  - tag2
  - tag3
---

# Welcome to MkDocs
```

![image](https://github.com/user-attachments/assets/fc333ed3-9843-43ac-b947-9f531a5739f8)

I had to add something that looked meaningless to get the default icon to work:

```yaml
site_name: My Docs

theme:
  name: material
  icon:
    tag:
      default: material/tag

extra:
  tags:
    _: _

plugins:
  - tags
```

![image](https://github.com/user-attachments/assets/f9bea064-2a60-4edf-9cd2-c33f55a8b67b)

According to the documentation, the `tags` in `extra` are meant to associate tags with the icons, but I don't want to do that, I just want the default icons. It doesn't make sense for me to add `tags` in `extra` at this point.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- https://squidfunk.github.io/mkdocs-material/plugins/tags/
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/

### Reproduction

[9.5.44-default-tag-icon-bug.zip](https://github.com/user-attachments/files/17692953/9.5.44-default-tag-icon-bug.zip)

### Steps to reproduce

Just run it according to the above configuration to see the results.

### Browser

Edge

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).
