### ISSUE TITLE
Unable to Override Heading Font Weight

### ISSUE THREAD

**Issue by superjax** [squidfunk/mkdocs-material#771]
## Description

I'm trying to make the headings bold - I added to my `extra.css` 

``` css
h2 {
  color: green;
  font-weight: bold;
}
```

I don't actually think the green looks good - I just did it to ensure that the color is being applied, however the font weight is not.

Disclaimer - I'm a complete novice at CSS.  This could be completely trivial, sorry if it is.

### Expected behavior

I expected the `h2` class to now be bold and green

![image](https://user-images.githubusercontent.com/7344014/39372877-eec18b2e-4a02-11e8-991a-1cbb929930ab.png)

### Actual behavior

They turned green, but not bold

![image](https://user-images.githubusercontent.com/7344014/39372843-d3eb9f1a-4a02-11e8-8bd7-024f5c06e169.png)

### Steps to reproduce the bug

`mkdocs serve`

### Package versions

* Python: 2.7.12
* MkDocs: 0.17.2
* Material: 2.6.6

### Project configuration

``` yaml
# Project information
site_name: InertialSense
site_url: http://inertialsense.com

# Repository
repo_url: https://github.com/inertialsense/docs
edit_uri: blob/master/docs/

# Google Analytics
google_analytics: UA-XXXXXXXXXXX
# Configuration
theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'red'
  favicon: 'custom_theme/img/favicon.ico'
  logo: 'custom_theme/img/Logo_Circle_white.svg'
  feature:
    tabs: false
theme_dir: docs/custom_theme

# Customization
extra_css: [custom_theme/extra.css]
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
extra:
  search:
    tokenizer: '[\s\-\.]+'
  font: false

# Extensions
markdown_extensions:
  - mdx_math
  - admonition
  - footnotes
  - toc:
      permalink: True
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - codehilite:
```

### System information

* OS: Ubuntu 16.04
* Browser: Firefox

**Comment by makshh** [comment]
Your CSS specificity is too low, you can read more about this [here](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity).

Try this:

```css
.md-typeset h1,
.md-typeset h2 {
  font-weight: bold;
}
```
