### ISSUE TITLE
404.html redirects to a different language

### ISSUE THREAD

**Issue by mgriff88** [squidfunk/mkdocs-material#7728]
### Description

Some background: Our docs site is available in English and Japanese. Our URL pattern looks like this:
English: https://www.example.com/about/
Japanese: https://www.example.com/ja/about/
So, the English site does not use /en/ in the URL itself, as it is the default language.

![image](https://github.com/user-attachments/assets/ba036aa0-c884-4b4e-9730-01fcdcdc74db)

For some reason, when accessing any broken link, the 404 page changes the entire site's language preference over to Japanese. See the attachment: it changes the Title, HTML Lang, etc.
Then, if you click Home or whatever from there, it brings you to the Japanese home. Even if you were reading the site in English from the start. This forces you to reset your language back to English. Same issue happens when using a custom override of the 404.html template.

Any idea why this might be happening and how to prevent it? Or better yet, any idea how to have separate English and Japanese 404 pages? Since it's not a Markdown file and it's just coming from 404.html, I'm not seeing how to do that.

Here is some of the relevant setup in my mkdocs.yml in case it helps:
```
theme:
  name: material
  custom_dir: overrides
...
  language: en
...
plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: ja
          name: Japanese
          build: true
          site_name: "ドキュメント"
...
extra:
  alternate:
    - name: English
      link: / 
      lang: en
    - name: 日本語
      link: /ja/
      lang: ja
```

### Related links

- [Reporting a docs issue](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/)
-

### Before submitting

- [X] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)
