### ISSUE TITLE
New list type: Steps

### ISSUE THREAD

**Issue by ofek** [squidfunk/mkdocs-material#7760]
### Context

https://squidfunk.github.io/mkdocs-material/reference/lists/

### Description

It would be nice to have a dedicated way to display list items that represent steps the user must follow to achieve a particular task.

### Related links

- https://mintlify.com/docs/content/components/steps
- https://starlight.astro.build/components/steps/

### Use Cases

A user must follow directions to achieve a desired outcome like the installation of a program.

### Visuals

![image](https://github.com/user-attachments/assets/4f1c5e43-11e4-4c94-8933-6d89cef90082)

![image](https://github.com/user-attachments/assets/974b4d75-1b20-4cf2-acde-91bac5e06ffe)

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting! We already have this on our list, and we'll revisit this once we got our current efforts sorted out ☺️

**Comment by A3Bagged** [comment]
I've actually came up with a markdown extension for this.
i was looking for the same thing.

I don't know python well so code could be improved but i've done my best and it works.
I've included it on my `ci.yml` with `pip install stepslist` so that i can use it online.

[Link to repo](https://github.com/A3Bagged/stepslist-extension)

I've tried making it with `<steps>` & `</steps>` tags but after 2 days of tinkering i found out that markdown or mkdocs closes any open html tags so it would actually output as:
``` 
<p><steps></steps></p>
<ol>
<li>

etc..
```

Changing to using `--steps--` & `--!steps--` has allowed me to do this.

These can then be styled with css using the class name `.md-steps` and `::before` `::after` pseudo elements to have something like your example.

Mine currently look like this
![image](https://github.com/user-attachments/assets/495bc591-032f-4184-975c-f9a2a5121074)

**Comment by squidfunk** [comment]
Looks great, thanks for sharing!

**Comment by facelessuser** [comment]
I kind of liked the "steps" idea, so I figured I'd post this. I didn't bother with a specialized "steps" extension or using custom tags and just utilized existing wrapping approaches and standard tags. I provided the necessary CSS so people could mimic this if they'd like. The colors can be overridden with whatever if something else is preferred. It should work with the default light and dark theme.

<img width="719" alt="Screenshot 2025-01-06 at 9 30 51 PM" src="https://github.com/user-attachments/assets/5e2df30a-95d0-4d7f-99ea-ab0f37be1a85" />

```css
:root > * {
	 --md-steps-bg-color: var(--md-code-bg-color);
	 --md-steps-fg-color: var(--md-code-fg-color);
	 --md-steps-border-color: hsla(0, 0%, 75%, 1);
}

:root > *[data-md-color-scheme="slate"] {
	 --md-steps-border-color: hsla(225, 15%, 30%, 1);
}

.md-typeset div.steps > ol {
	 counter-reset: item;
}

.md-typeset div.steps > ol li {
	 position: relative;
	 padding-left: 1em;
	 list-style: none;
}

.md-typeset div.steps > ol li::before {
	 position: absolute;
	 top: 0;
	 left: 0;
	 z-index: -1;
	 display: block;
	 width: 1.75em;
	 height: 1.75em;
	 margin-left: -1.25em;
	 color: var(--md-steps-fg-color);
	 font-weight: 600;
	 font-size: 0.9em;
	 text-align: center;
	 background-color: var(--md-steps-bg-color);
	 border: 1px solid var(--md-steps-border-color);
	 border-radius: 100px;
	 content: counter(item);
	 counter-increment: item;
}

.md-typeset div.steps > ol li::after {
	 position: absolute;
	 top: 0;
	 bottom: 0;
	 left: -0.36em;
	 display: block;
	 width: 1px;
	 margin-top: 2em;
	 border-left: 1px solid var(--md-steps-border-color);
	 content: '';
}
 
```
