### ISSUE TITLE
Github Star/Fork Count are not appearing

### ISSUE THREAD

**Issue by yks0000** [squidfunk/mkdocs-material#777]
## Description

Github stars/fork count are not appearing with version

```
mkdocs==0.17.3
material==2.7.3
```

### Expected behavior

Fork and Start should be visible

<img width="435" alt="image" src="https://user-images.githubusercontent.com/6111679/39826760-5d9b50d2-53d3-11e8-9104-224f66024fb9.png">

### Actual behavior

Only Repo name is visible

<img width="646" alt="image" src="https://user-images.githubusercontent.com/6111679/39826710-2814eae0-53d3-11e8-9cf4-0ea5ad297241.png">

[What is actually happening]

1. Installation

pip install mkdocs==0.17.3
pip install mkdocs-material==2.7.3

2. Configure mkdocs.yml 
3. mkdocs serve

### Package versions

$ python --version
Python 2.7.15
$ mkdocs --version
mkdocs, version 0.17.3
$ pip show mkdocs-material | grep -E ^Version
Version: 2.7.3

### Project configuration

``` yaml
site_name: SRE Python Docs
site_description: Python API Documentation for SRE Module and Reference Documents
docs_dir: docs
theme:
  name: material
  feature:
    tabs: true
  palette:
    primary: blue
    accent: red
  font:
    text: Work Sans
    code: Menlo
  logo:
    icon: home
  favicon: static/images/favicon.ico
extra_css: [static/css/extraCSS.css]
repo_url: "https://github.corp-internal.com/devops/sre-python-docs"
repo_name: 'devops/sre-python-docs'

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

pages:
  - Welcome: index.md
  - DevOps Module:
      - Feature Flag: FeatureFlagUsage.md
      - Reliable Parallel Requests: ReliableParallelRequests.md
  - Python Help:
      - Quick Help: PythonQuickHelp.md
  - Contribute: HowToContribute.md
  - Version: ModuleVersionCheck.md
  - Contact Us: Contact.md

```

### System information

* OS: macOS (10.13.4) High Sierra
* Browser: Safari, Mozilla, Chrome, Opera
