### ISSUE TITLE
Fixing codeblock widths for mobile.

### ISSUE THREAD

**Issue by A3Bagged** [squidfunk/mkdocs-material#7836]
### Context

I noticed that codeblocks extends their width over the viewport edges horizontally.

### Description

Inspecting with DevTools i wasn't able to see any widths or max-width's on these classes, the `width` was greyed out at a set width indicating that there is no width set, thus defaulting to 100% by default.

### Related links

- [Example page for inspecting](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/)
-

### Use Cases

from the original source (main.css, which is a scss file that gets a string name uppon build)
```css
@media screen and (max-width: 44.984375em) {
    .md-content__inner>.highlight {
        margin:1em -.8rem
    }
```

here i changed `-.8rem` to `auto` to center the codeblocks.
```css
@media screen and (max-width: 44.984375em) {
    .md-content__inner>.highlight {
        margin:1em auto
    }
```

(alternative option would be):
```css
@media screen and (max-width: 44.984375em) {
    .md-content__inner>.highlight {
        margin-block: 1em;
        margin-inline: auto;
    }
```

Not sure if the -.8rem was intended but auto makes it a little easier on the eyes without wondering if there is any information off the screen.

### Visuals

Old:
![image](https://github.com/user-attachments/assets/73d26b12-c34d-4c7f-a9e0-1dfb3463c04b)

New:
![image](https://github.com/user-attachments/assets/cae48a28-c50b-4495-ac97-36aef7853cda)

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.
