### ISSUE TITLE
MathJax abnormal rendering with "privacy" plugin

### ISSUE THREAD

**Issue by nicfv** [squidfunk/mkdocs-material#7894]
### Context

MathJax is rendering differently when the `privacy` plugin is enabled.

Without:

![image](https://github.com/user-attachments/assets/0763fb4f-bf5f-471c-9f3a-7f2b75a82529)

With:

![image](https://github.com/user-attachments/assets/d59717f7-9b9e-4332-8aee-e268bcf6be72)

### Bug description

Minimal reproduction:

```yaml
site_name: Example
theme:
  name: material
plugins:
  - privacy
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
```

### Related links

- https://squidfunk.github.io/mkdocs-material/reference/math/?h=math#mathjax-docsjavascriptsmathjaxjs
- https://squidfunk.github.io/mkdocs-material/plugins/privacy/

### Reproduction

[9.5.49-math-rendering.zip](https://github.com/user-attachments/files/18387484/9.5.49-math-rendering.zip)

### Steps to reproduce

See above.

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. As mentioned in our documentation, [MathJax doesn't work with the privacy plugin](https://squidfunk.github.io/mkdocs-material/plugins/privacy/?h=mathjax#config.assets_exclude):

``` yaml
plugins:
  - privacy:
      assets_exclude: 
        - unpkg.com/mathjax@3/*
        - giscus.app/*
```

![Bildschirm­foto 2025-01-12 um 17 07 13](https://github.com/user-attachments/assets/3b77bc1a-09b0-4e9c-aba7-eaeb5077310b)
