### ISSUE TITLE
Allow Local Hosting of Javascript Dependencies for Airgapped Environments

### ISSUE THREAD

**Issue by leonvosidemia** [squidfunk/mkdocs-material#7965]
### Bug description

We are running MkDocs Material in an airgapped environment where external resources cannot be fetched from the internet. Currently, various Javascript libraries are hardcoded - like `mermaid.min.js` - to be loaded from `unpkg.com`, preventing us from using Mermaid diagrams in our documentation.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

mkdocs.yml:

```yaml
site_name: test
theme:
  name: material
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
```

docs/index.md:
```mermaid

flowchart TD
    testing{1234}

```

### Steps to reproduce

1. Create a markdown file which includes any mermaid diagram
2. Build the static files
3. Move the static files to an airgapped environment
4. Open the files in a local browser
5. The build works as expected (e.g. it is working), however the mermaid graph isn't rendered, because the `mermaid.min.js` cannot be fetched

Another usecase we utilize is to build everything within the airgapped environment, which results in the same situation.

### Browser

Firefox

### Before submitting

- [x] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [x] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [x] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [x] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).
