### ISSUE TITLE
Clarify how sources and targets interact in automatic instant previews documentation

### ISSUE THREAD

**Issue by imchairmanm** [squidfunk/mkdocs-material#8001]
### Description

The [documentation for automatic instant previews](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#automatic-previews) describes how to enable automatic previews by setting `sources` and `targets`. However, it's unclear how these two configuration keys work together.

The docs include this example skeleton:

```
markdown_extensions:
  - material.extensions.preview:
      sources: 
        include:
          - ...
        exclude:
          - ...
      targets: 
        include:
          - ...
        exclude:
          - ...
```

My assumption was that the `targets` and `sources` keys would be processed independently:

* You could set a page as a `source` to enable instant previews for all links it contains.
* You could separately set a different page as a `target` to enable instant previews for all links pointing at it.

The reality seems to be that if you use both of these items together, only links from source pages to target pages will have instant previews (targets acts as an additional filters to further reduce the scope) . This was very surprising to me personally and I wasn't able to actually find that information in the docs.

After more research, I discovered I _could_ get those two bullets above working independently, from [this conversation in the initial announcement](https://github.com/squidfunk/mkdocs-material/issues/6704#issuecomment-1986840660)::

```
markdown_extensions:
  - material.extensions.preview:
      configurations:
        - sources:
            include:
              - ...
        - targets:
            include:
              - ...

```

It would be great for this to also be documented since it offers the behavior that I initially thought was available through the other syntax.

### Related links

- [Automatic previews](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#automatic-previews)
- This [conversation on the initial announcement](https://github.com/squidfunk/mkdocs-material/issues/6704#issuecomment-1986840660) contains information about how to process these as independent configurations.

### Before submitting

- [x] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [x] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)
