### ISSUE TITLE
Social Plugin logo causes: RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by mmzeynalli** [squidfunk/mkdocs-material#8006]
### Context

So, basically, even though it has worked for a long time, now I am getting error when building documenattion. However, whenever I comment out social part, it builds just fine.

### Bug description

When I enable social plugin and give logo, build crashes.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

```
site_name: Integrify
site_description: Integrify API inteqrasiyalarını rahatlaşdıran sorğular kitabaxanasıdır.
site_url: https://integrify.mmzeynalli.dev

theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/lightbulb-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to system preference

    icon:
      repo: fontawesome

  logo: assets/logo.svg
  favicon: assets/favicon.ico
  language: az

repo_name: mmzeynalli/integrify
repo_url: https://github.com/mmzeynalli/integrify

plugins:
  # - search
  - social:
      cards_layout_options:
        logo: assets/integrify.png
  # - panzoom:
  #     full_screen: True
  # - mkdocstrings:
  #     default_handler: python
  #     handlers:
  #       python:
  #         paths: [../../src]
  #         options:
  #           show_root_heading: true
  #           show_source: false
  #           show_if_no_docstring: true
  #           inherited_members: true
  #           members_order: source
  #           # separate_signature: true
  #           unwrap_annotated: true
  #           filters:
  #           - '!^_'
  #           merge_init_into_class: true
  #           docstring_section_style: spacy
  #           signature_crossrefs: true
  #           show_symbol_type_heading: true
  #           show_symbol_type_toc: true
  #           extensions:
  #           - griffe_pydantic

nav:
  - Giriş: index.md
  - İnteqrasiya:
      - EPoint:
          - Ümumi məlumat: "integrations/epoint/about.md"
          - API Referansı:
            - API Klient: "integrations/epoint/api-reference/client.md"
            - Schemas:
              - Response: "integrations/epoint/api-reference/response.md"
              - Callback: "integrations/epoint/api-reference/callback.md"
            - Köməkçi funksiyalar: "integrations/epoint/api-reference/helper-functions.md"
      - KapitalBank:
          - Ümumi məlumat: "integrations/kapital/about.md"
          - API Referansı:
            - API Klient: "integrations/kapital/api-reference/client.md"
            - Schemas:
              - Response: "integrations/kapital/api-reference/response.md"
              - Utils & Enums: "integrations/kapital/api-reference/utils.md"
  - Resurslar:
    - Contibuting: "resources/contributing.md"
    - Kod Arxitekturası: "resources/code-architecture.md"
    - API Referansı: "resources/api-reference.md"

# markdown_extensions:
#   - codehilite:
#       guess_lang: false
#   - admonition
#   - pymdownx.details
#   - pymdownx.highlight
#   - pymdownx.tabbed
#   - pymdownx.superfences
#   - abbr
#   - attr_list
#   - footnotes
#   - md_in_html
#   - tables
#   - toc:
#       permalink: true
#   - pymdownx.emoji:
#       emoji_index: !!python/name:material.extensions.emoji.twemoji
#       emoji_generator: !!python/name:material.extensions.emoji.to_svg
#   - pymdownx.betterem:
#       smart_enable: all
#   - pymdownx.caret
#   - pymdownx.highlight:
#       line_spans: __span
#   - pymdownx.inlinehilite
#   - pymdownx.keys
#   - pymdownx.mark
#   - pymdownx.superfences:
#       custom_fences:
#         - name: mermaid
#           class: mermaid
#           format: !!python/name:pymdownx.superfences.fence_code_format
#   - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mmzeynalli/integrify
  analytics:
    provider: goatcounter

extra_css:
  - css/termynal.css
  - css/custom.css

extra_javascript:
  - js/custom.js
  - js/termynal.js
```

### Steps to reproduce

`mkdocs build -d site`

### Before submitting

- [x] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [x] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [x] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [x] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).
