### ISSUE TITLE
Poor validation for analytics configuration

### ISSUE THREAD

**Issue by benjamincburns** [squidfunk/mkdocs-material#8007]
### Context

We tried and failed to enable analytics & feedback in a couple docs pages a while back. It was a quick thing and we didn't have time to investigate, so it sat in an apparently-configured-but-broken state for quite a while. Would've been good if an error had told us we'd configured it wrong.

### Bug description

This config is invalid, but it doesn't trigger any kind of error.

```yaml
extra:
  - analytics:
    provider: google
    property: G-XXXXXXXXXX
  - feedback:
    ...
```

Correct config would be as follows:

```yaml
extra:
  - analytics:
    provider: google
    property: G-XXXXXXXXXX
  - feedback:
    ...
```

### Related links

- [Setting up site analytics | Configuration](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#configuration)

### Reproduction

You don't need this - it's trivial

### Steps to reproduce

As in the description.

### Before submitting

- [x] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [x] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [x] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [x] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by kamilkrzyskow** [comment]
Both of the examples look the same to me.

I believe, I once spoke to squidfunk about adding config validation to the `search` plugin, as it does get run for almost anybody, so it also could be a fitting place to point out configuration mistakes, however, there is this <5% of users that don't enabled the search plugin, and this method wouldn't work. 

Another proposal was to inject code via `__init__.py`, however this was rejected as not the sort of hack to implement here. So the topic kind of died off, without a good answer, because MkDocs doesn't expose anything for themes to run a configuration validation.

I wanted to mention the next solution in a Discussions Show and Tell post soon, but since you've opened up this issue, perhaps now is a good time 🤔 

While working at [Nype](https://npe.cm/) on the [mkdocs-nype](https://github.com/nypesap/mkdocs-nype) theme, I found a good candidate to fix this issue. 

https://github.com/nypesap/mkdocs-nype/blob/main/mkdocs_nype/templates/nype-base.html#L4

```jinja
{% if "nype/nype_tweaks" not in config.plugins %}
    {% if {}.__getitem__('ERROR: The nype_tweaks plugin is required to run the nype theme. Please enable it in mkdocs.yml') %}{% endif %}
{% endif %}
```

Which invokes a `KeyError` on the `{}` and prints the contents of the "key", which is the error message.

I believe this sort of validation could be implemented for the `material` theme as well. Not only for this case specifically, but also for the case where people put `plugins` under the `theme`, and wonder why it doesn't work etc. etc.

The validation could be put in another file and the `include` could be limited to `index.html` to only run once inside the templates.

**Comment by squidfunk** [comment]
Thanks for reporting.

> You don't need this - it's trivial

Thank you're for telling us _how_ to do our work. Yes, we need a reproduction, [and it is mandatory](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#reproduction).

Other than that, please note that Material for MkDocs is a theme that ships some extra plugins. The [`config.extra`](https://www.mkdocs.org/user-guide/configuration/#extra) namespace is "put everything here that does not belong anywhere", provided by MkDocs, not by us. What @kamilkrzyskow suggested is to add unrelated hacks to the templates to let compilation crash. Validation is not the responsibility of themes, or even templates, but of the underlying framework.

You can take this [upstream](https://www.mkdocs.org/), if you want to see it happen. In essence, themes could define configuration schemas for the settings they expect in `config.extra` if MkDocs would then validate them. We'd definitely adopt this, if MkDocs would provide this functionality. Other than that, there's nothing we can do about it. Closing as upstream.

PS: We provide a [JSON schema](https://squidfunk.github.io/mkdocs-material/creating-your-site/#minimal-configuration-visual-studio-code) as a best-effort, as YAML is particularly pesky to support.

**Comment by squidfunk** [comment]
By the way, if you just would've sticked to our documentation, and copy the examples, everything would've worked:

Here's the one for [analytics](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#google-analytics):

``` yaml
extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX
```

Here's the one for [feedback](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#was-this-page-helpful):

``` yaml
extra:
  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
```
