### ISSUE TITLE
Main navigation is broken

### ISSUE THREAD

**Issue by amadfida** [squidfunk/mkdocs-material#806]
## Description

After upgrading to latest version, 2.9.1, we are noticing our navigation to be broken. Its trying to show the TOC on the nav.

### Expected behavior

TOC appears on the right hand side of the content/body

### Actual behavior

TOC is appearing on main menu

<img width="251" alt="screen shot 2018-06-22 at 10 59 55 am" src="https://user-images.githubusercontent.com/2160973/41786556-6e9f950a-760b-11e8-8b9d-16089cbcae12.png">

### Steps to reproduce the bug

Following is our sample page (trimmed) 
```
# Release notes

##5.5.3 - June 22, 2018##

**Release Date**: 06/22/18

This release contains improvements and bug fixes.

<h3>New Features</h3>...
```

### Package versions

* Python: `Python 3.6.3 :: Anaconda, Inc.`
* MkDocs: `mkdocs, version 0.17.3`
* Material: `Version: 2.9.1`

### Project configuration

``` yaml
# Project information
site_name: Documentation
site_url: http://docs.xxx.com

# Copyright
copyright: 'Copyright &copy; 2018 xxx'

# Configuration
theme:
  name: null
  custom_dir: 'theme'
  name: 'material'
  language: 'en'
  logo: 'images/logo.png'
  favicon: 'images/favicon.ico'
  palette:
    primary: 'white'
    accent: 'blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: false

# Styles
extra_css:
  - 'stylesheets/extra.css'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
pages:
  - Home: 'index.md'
  - Release notes: 'release-notes.md'
```

### System information

* OS: mac OS High Sierra 10.13.5
* Browser: Chrome
