### ISSUE TITLE
mermaid.js 11.4.1 Incompatible with mkdocs-material

### ISSUE THREAD

**Issue by AnonContributor1** [squidfunk/mkdocs-material#8096]
### Context

Been a big fan of your work! This is my first contribution.

Been using the latest and greatest mkdocs-material package. Today, my mermaid diagrams are not rendering from the latest mermaid.js code.

Found out mermaid updated their version from 11.4.1 to 11.5.0 yesterday
https://github.com/mermaid-js/mermaid/releases

### Bug description

Workaround is rolling back to last mermaid version in mkdocs.yml.

```
extra_javascript:
  - javascripts/feedback.js
  - https://unpkg.com/mermaid@11.4.1/dist/mermaid.min.js 
```

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [squidfunk Diagrams Page](https://squidfunk.github.io/mkdocs-material/reference/diagrams/?h=mermaid)
- [mermaid configuration solve](https://github.com/squidfunk/mkdocs-material/issues/3171)

### Reproduction

[mkdocs-material-test.zip](https://github.com/user-attachments/files/19258707/mkdocs-material-test.zip)

### Steps to reproduce

1. Deploy mkdocs_doesntwork.yml with latest mermaid.js version to see broken rendering
2. Deploy with mkdocs_works.yml with last mermaid.js version to see fixed rendering

### Before submitting

- [x] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [x] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [x] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [x] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. There seems to be a problem with unpkg.com. If I add the following (update to 11.5.0), it works as expected, so it's not a problem with Mermaid itself:

``` yaml
site_name: My Docs
theme:
  name: material

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com/mermaid@11.5.0/dist/mermaid.min.js 
```

However, when we load `11` (what Material for MkDocs does), a 520 error is returned by CloudFlare:

<img width="1439" alt="Image" src="https://github.com/user-attachments/assets/58e80df0-fbee-446b-929c-11b1cb229b51" />

For this reaso, it's nothing we can fix on our end, but we need to wait until CloudFlare resolves the issue.
