### ISSUE TITLE
I'd like CSS rules for form elements in the body

### ISSUE THREAD

**Issue by emsenn** [squidfunk/mkdocs-material#813]
## Description

This isn't a bug but a request; one you should feel free to ignore; it's a feature I want that I'd be willing to implement myself, I'm just a little short on technical know-how, and think it might be generally more useful.

But, what I'd like is for form elements to have some different styling if used in the body. Right now, they're quite indistinguishable from normal text - I assume that's because of rules for the search bar.

### Expected behavior

Again, this is the expected behavior, I didn't expect a static site theme catered toward documentation to be able to handle stylish forms.

### Actual behavior

Forms look real bland - mostly, nothing has a border, so it doesn't look clearly clickable.

### Steps to reproduce the bug

1. Put a form on your page
2. Render it
3. Get confused trying to find the form.

### Package versions

Using gitlab-ci so I can't check this at a glance, but if it's necessary I'll figure out how to go fetch it.

### Project configuration

``` yaml
site_name: Holistic Project Management 
site_description: A system-agnostic project management method.
site_author: emsenn
repo_name: 'source'
repo_url: https://gitlab.com/emsenn/holistic-project-management/
pages:
    - Home: index.md
theme:
    name: 'material'
    palette:
        primary: 'grey'
        accent: 'teal'
    feature:
        tabs: true
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
```

### System information

* OS: To view? Windows. To build? Alpine, I think.
* Browser: Chrome

---

Again, I wanna stress, please feel free to close this if it's not something you'd like to address. (PS I absolutely love this theme, and how beautiful it looks while leaving the markdown so clean.)
