### ISSUE TITLE
Feature: Allows defining custom page statuses using icons

### ISSUE THREAD

**Issue by ReleTor** [squidfunk/mkdocs-material#8142]
### Description

```yaml
extra:
  status:
    <identifier>:
      description: <description>
      icon: <icon>
```

### Related links

- [setting the page status](https://squidfunk.github.io/mkdocs-material/reference/?h=page+status#setting-the-page-status)

### Use Cases

```yaml
extra:
  status:
    happy:
      description: happy
      icon: material/emoticon-happy
```

### Before submitting

- [x] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [x] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [x] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [x] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.
