### ISSUE TITLE
After specifying the `nav` section `navigation.path` rendering fails

### ISSUE THREAD

**Issue by milovanovicdusan** [squidfunk/mkdocs-material#8199]
### Context

Specifying in the `mkdocs.yml` configuration file both the `navigation-path` feature of the Material for MkDocs Insiders theme and the `nav` section, an upstream MkDocs dependency.

### Bug description

After adding `nav` section to the `mkdocs.yml`, the breadcrumbs navigation tree (`navigation.path` feature of the Material for MkDocs Insiders) is no longer rendered for (1) the first-level menu items and (2) second-level menu items that have no children (leaf second-level menu items). Compared to the breadcrumb navigation path rendering before specifying the `nav` section in the `mkdocs.yml` file, the breadcrumb navigation paths are partially rendered for the second-level menu items with children, and for all their children down the hierarchy tree &mdash; the leading homepage and the trailing menus fore the current (opened) page are omitted from the path.

❌ Breadcrumbs navigation path is not rendered for the first-level menu items:

![Image](https://github.com/user-attachments/assets/12817fef-d6fa-4724-aace-460eca754d1a)

❌ Breadcrumbs navigation path is not rendered for the leaf second-level menu item, that without children:

![Image](https://github.com/user-attachments/assets/2c98e689-2f1c-4bed-84d8-d5f8472524b2)

❌ Breadcrumbs navigation path is partially rendered for the current (open) page:

![Image](https://github.com/user-attachments/assets/42fd3a95-06b5-4598-b4be-ccd138ddd400)

### Related links

Links to relevant documentation:
- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Material for MkDocs - Setup - Setting up navigation - Configuration - Navigation path Breadcrumbs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-path)
- [Material for MkDocs - Setup - Setting up navigation - Configuration - Section index pages](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages)
- [MkDocs User Guide - Configuration - Documentation layout - nav](https://www.mkdocs.org/user-guide/configuration/#nav)
- [MkDocs User Guide - Writing Your Docs - Configure Pages and Navigation](https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation)- 
- [MkDocs User Guide - Writing Your Docs - Meta-Data](https://www.mkdocs.org/user-guide/writing-your-docs/#meta-data)

Links to relevant discussions:
- https://github.com/squidfunk/mkdocs-material/discussions/4099
- https://github.com/squidfunk/mkdocs-material/discussions/8198

### Reproduction

The upload here failed with the following message:
`<!-- Failed to upload "9.6.12+insiders.4.53.16-navigation-path-rendering-issue.zip" -->`

The built-in info plugin automatically created the `.zip` file containing the reproduction of the issue, as explained in the reproduction steps below. Its size is way larger than the maximum 1 MB allowed:

![Image](https://github.com/user-attachments/assets/6fad7eca-9702-4150-b208-3bb81f8f3d2e)

I provided detailed steps, including the step-wise configuration of `mkdocs.yml` and stepwise testing of the breadcrumbs navigation path rendering. I can send the larger-than-acceptable `.zip` file by email or using any other convenient means for you. 

### Steps to reproduce

1. Install the latest release of the **Material for MkDocs Insiders**:
```sh
pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
```
2. Create a reproduction directory:
```sh
mkdir reproduction
```
3. Make the reproduction directory a working directory:
```sh
cd reproduction
```
4. Bootstrap a new documentation project in the working directory:
```sh
mkdocs new .
```
The working directory looks like this now:

![Image](https://github.com/user-attachments/assets/9a586719-999f-4b9d-a789-fdc895b73648)

✅ Python virtual environment is installed and running in the working directory.
✅ MkDocs initialised the working directory with `/docs` subdirectory and `mkdocs.yml` configuration file  

5. Test if the live-reloading web page from MkDocs dev-server works:
```
mkdocs serve
```
✅ Live-reloading web page from MkDocs dev-server works:

![Image](https://github.com/user-attachments/assets/6b279df4-0a85-410d-ac5e-02a877a05991)
 
6. Create a minimal `mkdocs.yml` configuration to enable the Material for MkDocs Insiders theme:
```yaml 
site_name: episteme
site_url: https://episteme-association.github.io/documentation

theme:
    name: material
``` 
7. Check the live-reloading web page to test if the Material for MkDocs Insiders theme is enabled:

✅ Material for MkDocs Insiders theme is enabled:

![Image](https://github.com/user-attachments/assets/4d8ca624-9742-4df3-bc80-2a64d1501871)

8. Create a subdirectory structure within the `docs/` directory:
> -  _the subdirectory structure had to be detailed as it is below to recreate and analyse the reported issue_
> - _the content of `index.md` files (just a Markdown header level 1) is provided in the `reproduction.zip` file_

```{ .sh .no-copy }
.
├── About-Us
│   └── index.md
├── Continuous-Innovations
│   ├── Advanced-Analytics-Operationalisation
│   │   └── index.md
│   ├── Knowledge-Models
│   │   └── index.md
│   ├── Web-of-Data-Components
│   │   └── index.md
│   ├── Web-of-Data-Search-Engine
│   │   └── index.md
│   └── index.md
├── Health-Intelligence-Network
│   ├── Governance
│   │   └── index.md
│   ├── Health-Intelligence-Services
│   │   └── index.md
│   ├── Partnership-Project
│   │   └── index.md
│   └── index.md
├── Knowledge-Base
│   ├── Health-Emergencies
│   │   └── index.md
│   ├── Health-Intelligence
│   │   ├── Actionable-Intelligence
│   │   │   └── index.md
│   │   ├── Contextual-Analysis
│   │   │   └── index.md
│   │   ├── Surveillance
│   │   │   └── index.md
│   │   ├── Threats-and-Opportunities-Assessment
│   │   │   └── index.md
│   │   └── index.md
│   └── index.md
├── Services
│   ├── Health-Intelligence
│   │   └── index.md
│   ├── Health-Intelligence-Network-Governance
│   │   └── index.md
│   ├── Health-Intelligence-Partnership-Project-Coordination
│   │   └── index.md
│   ├── Solution-Design
│   │   └── index.md
│   └── index.md
├── Solutions
│   ├── Healthcare
│   │   ├── Clinical-Decision-Support
│   │   │   └── index.md
│   │   ├── Self-observation
│   │   │   ├── Personal-glucose-monitor
│   │   │   │   └── index.md
│   │   │   ├── Personal-seizure-diary
│   │   │   │   └── index.md
│   │   │   └── index.md
│   │   └── index.md
│   ├── Public-Health
│   │   ├── Early-Warning-and-Alerting
│   │   │   └── index.md
│   │   ├── Health-Information-Exchange
│   │   │   └── index.md
│   │   ├── Human-Intelligence
│   │   │   └── index.md
│   │   ├── Integrated-Disease-Surveillance
│   │   │   └── index.md
│   │   ├── Open-Source-Intelligence
│   │   │   └── index.md
│   │   ├── Pandemic-Simulator
│   │   │   └── index.md
│   │   └── index.md
│   └── index.md
└── index.md
``` 
9. Check the live-reloading web page to test if the subdirectories are rendered as menu items:
> _`Association Episteme` is the home page (the header level 1 in the `docs/index.md`)_

✅ All subdirectories of the /docs directory are rendered as menu items:

![Image](https://github.com/user-attachments/assets/83e45e90-e1c9-4e32-837c-8d1a98296988)

10. Configure _breadcrumbs navigation_ by specifying `navigation.path` feature for the `material` theme in the `mkdocs.yml`:
```yaml
site_name: episteme
site_url: https://episteme-association.github.io/documentation

theme:
    name: material
    features:
        - navigation.path
```
11. Check the live-reloading web page to test if the _breadcrumbs navigation_ is appropriately rendered:
> _`Association Episteme` is the home page (the header level 1 in the `docs/index.md`)_

✅ Breadcrumbs navigation paths are appropriately rendered:

![Image](https://github.com/user-attachments/assets/302c3dc7-5b2b-4f59-b1af-ae3016f0ac7b)

> Rendering of the breadcrumbs navigation works. The path starts with the Markdown header level 1 of the homepage (`docs/index.md` -> `Association Episteme`) and ends with the name of the subdirectory that contains the current (opened) page (`docs/.../Open-Source-Intelligence/index.md` -> `Open Source Intelligence`)

12. To make navigation more user-friendly, let's now configure _navigation tabs_ by specifying the `navigation.tabs` feature for the `material` theme in the `mkdocs.yml`:
```yaml
site_name: episteme
site_url: https://episteme-association.github.io/documentation

theme:
    name: material
    features:
        - navigation.path
        - navigation.tabs
``` 
13. Check the live-reloading web page to test if the _navigation tabs_ are appropriately rendered:
> _`Association Episteme` is the home page (the header level 1 in the `docs/index.md`)_

✅ Navigation tabs are appropriately rendered in the web page header:

![Image](https://github.com/user-attachments/assets/9e2c43cd-ba0f-445f-9038-6dd93e89921f)

> Rendering of the navigation tabs works. Top-level menus are rendered in a menu layer below the header. They are named after the homepage's markdown header level 1 (`Association Episteme`) and top-level subdirectories of the `docs/` directory.

14. To improve the user-friendliness of the navigation, let's now configure grouping of web pages in the top-level sections (level 2 menu items), for each level 1 menu item already rendered in the top menu, by specifying the `navigation.sections` feature for the `material` theme in the `mkdocs.yml`:
```yaml
site_name: episteme
site_url: https://episteme-association.github.io/documentation

theme:
    name: material
    features:
        - navigation.path
        - navigation.tabs
        - navigation.sections
``` 
15. Check the live-reloading web page to test if the _navigation sections_ are appropriately rendered:

✅ Navigation sections in the left menu bar are appropriately rendered:

![Image](https://github.com/user-attachments/assets/17c99266-4550-4da7-adb8-9b463e2ec42f)

> Rendering of the sections in the left navigation bar for level 2 navigation items tabs works. They are named after the level 2 subdirectories in the `docs/` directory.

16.  To further improve the user-friendliness of the navigation, let's now attach section overview pages (`subfolder/index.md`) directly to the section menu items in the left menu bar by specifying the `navigation.index` feature for the `material` theme in the `mkdocs.yml`:
```yaml
site_name: episteme
site_url: https://episteme-association.github.io/documentation

theme:
    name: material
    features:
        - navigation.path
        - navigation.tabs
        - navigation.sections
        - navigation.indexes
``` 

17. Check the live-reloading web page to test if the section overview pages are attached directly to the section menu items:

✅ Section overview pages are attached directly to the section menu items:

![Image](https://github.com/user-attachments/assets/b493d422-a3a4-48e4-a8d5-76ae5c0acf3d)

> Section overview pages are successfully attached directly to the section menus in the left menu bar.

18. The configuration has been successful until now, including using the Material for MkDocs Insiders `navigation.path` feature for configuring breadcrumb navigation paths. However, by default, MkDocs sorts menu items alphabetically by name. Different, logical sorting of the menu items on top and other levels is needed to improve user friendliness and the user experience.

❗Menu items are sorted alphabetically. They need to be sorted logically to improve the user experience:

![Image](https://github.com/user-attachments/assets/b493d422-a3a4-48e4-a8d5-76ae5c0acf3d)

To change the order of appearance of menu items, let's configure upstream Material for MkDocs dependency coming from the MkDocs, the `nav` section in the `mkdocs.yml`:

```yaml
site_name: episteme
site_url: https://episteme-association.github.io/documentation

theme:
    name: material
    features:
        - navigation.path
        - navigation.tabs
        - navigation.sections
        - navigation.indexes

nav:
    - Home:
        - index.md 
    - About Us:
        - About-Us/index.md
    - Services:
        - Services/index.md
            - Health Intelligence Partnership Project Coordination: Services/Health-Intelligence-Partnership-Project-Coordination/index.md
            - Health Intelligence Network Governance: Services/Health-Intelligence-Network-Governance/index.md
            - Solution Design: Services/Solution-Design/index.md
            - Health Intelligence: Services/Health-Intelligence/index.md
    - Solutions:
        - Solutions/index.md
        - Public Health:
            - Solutions/Public-Health/index.md
            - Human Intelligence: Solutions/Public-Health/Human-Intelligence/index.md
            - Open Source Intelligence: Solutions/Public-Health/Open-Source-Intelligence/index.md
            - Early Warning and Alerting: Solutions/Public-Health/Early-Warning-and-Alerting/index.md
            - Integrated Disease Surveillance: Solutions/Public-Health/Integrated-Disease-Surveillance/index.md
            - Health Information Exchange: Solutions/Public-Health/Health-Information-Exchange/index.md
            - Pandemic Simulator: Solutions/Public-Health/Pandemic-Simulator/index.md
        - Healthcare:
            - Solutions/Healthcare/index.md
            - Self-observation:
                - Solutions/Healthcare/Self-observation/index.md
                    - Personal Seizure Diary: Solutions/Healthcare/Self-observation/Personal-seizure-diary/index.md
                    - Personal Glucose Monitor: Solutions/Healthcare/Self-observation/Personal-glucose-monitor/index.md
            - Clinical Decision Support: Solutions/Healthcare/Clinical-Decision-Support/index.md
    - Health Intelligence Network:
        - Health-Intelligence-Network/index.md
        - Health Intelligence Partnership Project: Health-Intelligence-Network/Partnership-Project/index.md
        - Health Intelligence Network Governance: Health-Intelligence-Network/Governance/index.md
        - Health Intelligence Services: Health-Intelligence-Network/Health-Intelligence-Services/index.md
    - Continuous Innovations:
        - Continuous-Innovations/index.md
        - Knowledge Models: Continuous-Innovations/Knowledge-Models/index.md
        - Web of Data Components: Continuous-Innovations/Web-of-Data-Components/index.md
        - Health Intelligence Network Search Engine: Continuous-Innovations/Web-of-Data-Search-Engine/index.md
        - Advanced Analytics Operationalisation: Continuous-Innovations/Advanced-Analytics-Operationalisation/index.md
    - Knowledge Base:
        - Knowledge-Base/index.md
        - Health Emergencies: Knowledge-Base/Health-Emergencies/index.md
        - Health Intelligence:
            - Knowledge-Base/Health-Intelligence/index.md
            - Surveillance: Knowledge-Base/Health-Intelligence/Surveillance/index.md
            - Contextual Analysis: Knowledge-Base/Health-Intelligence/Contextual-Analysis/index.md
            - Assessment: Knowledge-Base/Health-Intelligence/Threats-and-Opportunities-Assessment/index.md
            - Actionable Intelligence: Knowledge-Base/Health-Intelligence/Actionable-Intelligence/index.md
``` 
19. Check the live-reloading web page to test if the menu items are sorted as specified in the `nav` section in the `mkdocs.yml` configuration file:

✅ Order of appearance of the menu items is correctly rendered, as configured using MkDocs `nav` section
❌ **Breadcrumbs navigation paths are now broken!**

![Image](https://github.com/user-attachments/assets/42fd3a95-06b5-4598-b4be-ccd138ddd400)

As can be seen from the example screenshot above, the breadcrumbs navigation path (`navigation.path` feature of the Material for MkDocs Insiders theme) after adding nav section to the mkdocs.yml (an upstream dependency from MkDocs), is not rendered fully compared to the rendering before adding the `nav` section - the leading homepage and the trailing menu item for the current (opened) page are omitted.

As can be seen from the following two example screenshots, after adding the `nav` section, the breadcrumbs navigation path is not rendered at all for the overview pages belonging to the first-level menu items and for the overview pages of those second-level menu items that don't have children. As explained above, the breadcrumbs navigation paths are partially rendered for the second-level menu items with children, and for their children down the hierarchy tree.

❌ **Breadcrumbs navigation path is not rendered for the first-level menu items:**

![Image](https://github.com/user-attachments/assets/12817fef-d6fa-4724-aace-460eca754d1a)

❌ **Breadcrumbs navigation path is not rendered for the leaf second-level menu items**

![Image](https://github.com/user-attachments/assets/2c98e689-2f1c-4bed-84d8-d5f8472524b2)

### Before submitting

- [x] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [x] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [x] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [x] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).
