### ISSUE TITLE
Printing page with annotation includes list marker and annotation number

### ISSUE THREAD

**Issue by joapuiib** [squidfunk/mkdocs-material#8204]
### Bug description

Both `::marker` and `::before` are shown in annotations when printing a page using `pymdownx.fancylists` extension.

```yml
markdown_extensions:
  - attr_list
  - pymdownx.fancylists
```

__Printed content__:
![Image](https://github.com/user-attachments/assets/a067e423-aa13-44ac-8bf5-f410de0f8baa)

---
This is due because `pymdownx.fancylists` sets lists `type`. The current CSS rule for handling these overrides the annotation styles.

```css
.md-typeset ol[type], .md-typeset ul[type] {
    list-style-type: revert-layer;
}

.md-typeset .md-annotation-list {
    counter-reset: xxx;
    list-style: none;
}
```

---
Possible fix:
```css
.md-typeset .md-annotation-list {
    counter-reset: xxx;
    list-style: none !important;
}
```

### Related links

- https://github.com/squidfunk/mkdocs-material/issues/7542
- https://facelessuser.github.io/pymdown-extensions/extensions/fancylists/

### Reproduction

[9.6.12-annotations-number-print.zip](https://github.com/user-attachments/files/20060488/9.6.12-annotations-number-print.zip)

### Steps to reproduce

1. Print the landing page.
    > Also, `window.dispatchEvent(new Event("beforeprint"));` shows the issue. 
2. Check that the annotation has both `::marker` and `::before`.

### Browser

Chrome

### Before submitting

- [x] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [x] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [x] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [x] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).
