### ISSUE TITLE
Collapse do not work.

### ISSUE THREAD

**Issue by shinji62** [squidfunk/mkdocs-material#821]
## Description
Collapse section doesn't work. 

Just code the raw code like 

```
??? note "Phasellus posuere in sem ut cursus"
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et euismod
    nulla. Curabitur feugiat, tortor non consequat finibus, justo purus auctor
    massa, nec semper lorem quam in massa.

```

### Expected behavior

To have the collapse working

### Actual behavior

Just code the raw code like 

```
??? note "Phasellus posuere in sem ut cursus"
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et euismod
    nulla. Curabitur feugiat, tortor non consequat finibus, justo purus auctor
    massa, nec semper lorem quam in massa.

```

### Steps to reproduce the bug
Just use the code above
Just code the raw code like 

```
??? note "Phasellus posuere in sem ut cursus"
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et euismod
    nulla. Curabitur feugiat, tortor non consequat finibus, justo purus auctor
    massa, nec semper lorem quam in massa.

```

### Package versions

I am using the latest docker image

### Project configuration

``` yaml
site_name: test-one
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue'

markdown_extensions:
  - codehilite
  - admonition

pages:
- 'Home': index.md
- 'Requirements': Requirements.md
```

### System information

* OS: MAC
* Browser: google chrome
