### ISSUE TITLE
Disable overflow feature in the sidebar and table of contents

### ISSUE THREAD

**Issue by ju5t** [squidfunk/mkdocs-material#824]
## Description

We would like to disable the overflow of the sidebar and table of contents on our pages.

### Expected behavior

A floating sidebar that scrolls down but doesn't use overflow to add a scrollbar and therefore fixes it to a specific height.

### Actual behavior

It adds a scrollbar via overflow if the menu grows larger.

### Steps to reproduce the bug

I wouldn't class this as a bug, more a feature request. Unfortunately I'm not great with CSS/JavaScript.

### Package versions

* Python: 3.6
* MkDocs: 0.17.4
* Material: 2.9.1

### Project configuration

``` yaml
# Theme
theme:
  name: 'material'
  custom_dir: 'theme'

plugins:
  - search
  - awesome-pages

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - meta
  - toc:
      permalink: true
```

### System information

* OS: Docker Container running Alpine, testing on MacOS
* Browser: Safari & Chrome
