### ISSUE TITLE
Code block parsing error while using highlight.js

### ISSUE THREAD

**Issue by CX330Blake** [squidfunk/mkdocs-material#8272]
### Bug description

The code does not parsed from the ```, here's the photo of wrong parsed rendering.

![Image](https://github.com/user-attachments/assets/5ed08a1a-26d3-4ac3-8e3b-cb394afed614)

I do turn pygments off and import the external js/css

```yml
markdown_extensions:
    - pymdownx.highlight:
          use_pygments: false
          # anchor_linenums: true
          # line_spans: __span
          # pygments_lang_class: true
          # auto_title: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - def_list
    - pymdownx.tasklist:
          custom_checkbox: true
    - mdx_truly_sane_lists
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
```

```yml
extra_css:
    - stylesheets/extra.css
    - stylesheets/dracula.css

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
    - js/highlight.js
```

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Highlight](https://arc.net/l/quote/bkgtqaty)

### Reproduction

[reproduction.zip](https://github.com/user-attachments/files/20832331/reproduction.zip)

### Steps to reproduce

`mkdocs serve --dev-addr 0.0.0.0:8000` and see the website

### Browser

Other

### Before submitting

- [x] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [x] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [x] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [x] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).
