### ISSUE TITLE
There's no 404 page

### ISSUE THREAD

**Issue by csandanov** [squidfunk/mkdocs-material#829]
## Description

There's no 404 page (e.g. https://docs.wodby.com/qwerqwe), I've tried to copy `404.html` to my `custom_dir` (where I rewrite some partials) and specifying under `theme.static_templates` but it didn't help.

### Expected behavior

To get 404 not found like https://squidfunk.github.io/mkdocs-material/asdfsadf

### Actual behavior

Homepage rendered instead of 404 or broken page (https://docs.wodby.com/stacks/asdfewrq)

### Steps to reproduce the bug

Visit any non-existing page under https://docs.wodby.com/qwerqwe

### Package versions

* Python: `3.6`
* MkDocs: `0.17.5`
* Material: `2.9.4`

### Project configuration

``` yaml
site_name: Wodby documentation
site_description: Wodby documentation
site_author: Wodby, Inc.
site_url: https://docs.wodby.com

repo_name: wodby/docs
repo_url: https://github.com/wodby/docs

copyright: Wodby, Inc.

extra:
  social:
    - type: globe
      link: https://wodby.com
    - type: github-alt
      link: https://github.com/wodby
    - type: twitter
      link: https://twitter.com/WodbyHQ

theme:
  name: material
  feature:
    tabs: true
  palette:
    primary: 'indigo'
    accent: 'indigo'
  custom_dir: 'theme'

  # 404 page
  static_templates:
    - 404.html

extra_css: ["assets/wodby.css"]
extra_javascript: ["assets/intercom.js","assets/wodby.js"]

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - markdown_include.include:
      base_path: docs

pages:
...
```

### System information

* OS: Alpine Linux
* Browser: Chrome 67 macOS
