### ISSUE TITLE
Navigation Broken since 2.9.4

### ISSUE THREAD

**Issue by shinji62** [squidfunk/mkdocs-material#831]
## Description

Navigation trought the slide menu is not working anymore.

```
http://localhost:8000/day1/concourse_arch/day1/concept/day1/concourse_arch/day1/concept/day1/concourse_arch/day1/pcf-bg/day2/install_docker_compose/
```

Path seems to be accumulating  to each other.

### Expected behavior

First time 
I click on `Architecture` I should go to `http://localhost:8000/day1/concourse_arch/`
then I click to `Hello Concourse ` I should go to `http://localhost:8000/day1/hello-concourse/`

### Actual behavior
First time 
I click on `Architecture` I go to `http://localhost:8000/day1/concourse_arch/`
then I click to `Hello Concourse ` I go to `http://localhost:8000/day1/concourse_arch/day1/hello-concourse/` which lead to 404 ..

### Steps to reproduce the bug
Steps are same as Actual Behavior
### Package versions
Use the latest Docker image

### Project configuration

``` yaml
site_name:  Worshop
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue'

markdown_extensions:
  - codehilite:
      use_pygments: false
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.superfences
  - pymdownx.mark

extra_javascript:
  - 'assets/js/highlight/highlight.pack.js'
  - 'assets/js/highlight/init.highlight.js'

extra_css:
  -  'assets/js/highlight/styles/atom-one-light.css'

pages:
- 'Home': index.md
- 'Requirements': Requirements.md
- 'Day 1 Basic':
  - 'Architecture': day1/concourse_arch.md
  - 'Concept': day1/concept.md
  - 'Hello concourse': day1/hello-concourse.md
  - 'Blue Green deployment on PCF - PAS': day1/pcf-bg.md
  - 'Credhub with Concourse': day1/credhub.md
  - 'Vault with Concourse': day1/vault.md
  - '👷TroubleShooting Concourse': under-construction.md
- 'Day 2 Operating Concourse':
  - 'Installing Concourse using Docker compose': day2/install_docker_compose.md
  - 👷Installing Concourse using bosh ': under-construction.md
  - 👷Monitoring Concourse using Prometheus': day2/prometheus-monitoring.md
- 'Day 3 Platform Automation':
  - 'Automating PCF installation': day3/plat-automation.md
  - '👷Update Your Platform': day3/plat-update.md
  - 'Repaving PCF': day3/repave-diego-cell.md

```
I tried replace `pages` by `nav` but result is the same.

### System information

* OS: macOS
* Browser:  Chrome
