### ISSUE TITLE
Additional path levels added to extra CSS and JavaScript

### ISSUE THREAD

**Issue by martinbira** [squidfunk/mkdocs-material#841]
## Description
When building a site using `mkdocs build` (and a specified output directory), the relative paths to extra JavaScript and CSS have more added levels. This disables the extra JavaScript and CSS on all pages that are not at root level.

### Expected behavior

Building a site to the `site` directory from `docs` with folders for `stylesheets` and `javascripts` placed within `docs` will produce a structure in the style of:
`file:///C:/MKDocs/site/api/index.html`
`file:///C:/MKDocs/site/stylesheets/extra.css`
`file:///C:/MKDocs/site/javascripts/extra.js`

The source-code of `file:///C:/MKDocs/site/api/index.html` should include the following:

```html
<link rel="stylesheet" href="../stylesheets/application-custom.palette.css">
<link rel="stylesheet" href="../stylesheets/custom-extra.css">
...
<script>app.initialize({version:"1.0",url:{base:".."}})</script>
<script src="../javascripts/extra.js"></script>
```

### Actual behavior

The source-code of `file:///C:/MKDocs/site/api/index.html` includes the following:

```html
<link rel="stylesheet" href="../../stylesheets/application-custom.palette.css">
<link rel="stylesheet" href="../../stylesheets/custom-extra.css">
...
<script>app.initialize({version:"1.0",url:{base:".."}})</script>
<script src="../../javascripts/extra.js"></script>
```

### Steps to reproduce the bug

1. Add CSS and JavaScript files to respective folders placed withing the `docs` folder.
2. Have a multi-level page structure.
3. Build site to desired directory.

### Package versions

* Python: `3.6.1`
* MkDocs: `1.0`
* Material: `3.0.2`

### Project configuration

``` yaml
site_dir: 'site'
use_directory_urls: true
...
theme: 
    name: 'material'
    palette:
      primary: 'custom'
      accent: 'custom'
...
extra_css:
  - 'stylesheets/application-custom.palette.css'
  - 'stylesheets/extra.css'
extra_javascript:
  - 'javascripts/extra.js'
...
nav:
    - API:
      - Overview: api/index.md
...
```

### System information

* OS: Win 10
