### ISSUE TITLE
Links created in navbar/searchbar not working in Mkdocs 1.0

### ISSUE THREAD

**Issue by simoneddeland** [squidfunk/mkdocs-material#842]
## Description

Links do not start from root, they keep building on the current adress. Lets say that I start from my index page and my navbar contains a link to about

```
nav:
    - About: about
```

The first time I click it I will go to "about". If I click the about-link in the navbar again, I will go to "about/about" which does not exist.

This also affects the links that are created when using the Search-function.

I have only been (trying) to use Mkdocs for a few days, but I have not found anyone else with the same problem. Maybe this has something to do with the [breaking changes in Mkdocs 1.0?](https://www.mkdocs.org/about/release-notes/#internal-refactor-of-pages-files-and-navigation)

**Edit:** I downgraded my Mkdocs to 0.17 and I have no problems with the links in either the navbar or the searches now (though I have to write the mkdocs.yml file a bit differently). Definately seems like a problem with mkdocs 1.0.

**NOTE 1**: Links work fine for me in the navbar/searches created when using the default theme or the readthedocs theme.

**NOTE 2**: A way to fix the navbar problem for me is to prepend a "/" to every link, this does however not fix the broken links created when using the searchbar. I.e. using
```
nav:
    - About: /about
```
works fine for the navbar.

### Expected behavior

Going to "about" when I click it the second time.

### Actual behavior

Going to "about/about" when I click it the second time.

### Steps to reproduce the bug

1. Add `- About: about` to the nav.
2. Click it once
3. Click it again

### Package versions

* Python: 3.7.0
* MkDocs: 1.0
* Material: 2.9.4

### Project configuration

``` yaml
site_name: PS
nav:
    - Start: /
    - About: about
    - Kapitel 3: kapitel/tre
    - Kapitel 4: kapitel/fyra
theme:
  name: 'material'
  palette:
    primary: 'red'
  language: 'sv'

markdown_extensions:
  - toc:
      baselevel: 1
extra:
  search:
    lang: 'sv, en'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
```

### System information

* OS: Windows 10 (tried it when deploying to my RPi running Raspian, same problem)
* Browser: Chrome
