### ISSUE TITLE
Mathjax not rendered in toc on the side

### ISSUE THREAD

**Issue by Ir1d** [squidfunk/mkdocs-material#849]
## Description

Mathjax not rendered in toc on the side.

```
### $A_i$
```

It works fine in the article, but was not rendered in the toc.

### Steps to reproduce the bug

1. `## $A_i$`

### Package versions

* Python: Python 3.6.5 :: Anaconda, Inc.
* MkDocs: mkdocs, version 1.0 from /home/XD/.local/lib/python3.6/site-packages/mkdocs (Python 3.6)
* Material: Version: 3.0.3

### Config
```
  - admonition
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
```
