### ISSUE TITLE
Side TOC not showing up for some pages

### ISSUE THREAD

**Issue by mlevit** [squidfunk/mkdocs-material#854]
## Description

The automatic table of contents is not showing up on certain pages but is on others.

Working: 
<img width="1337" alt="screen shot 2018-08-23 at 3 21 49 pm" src="https://user-images.githubusercontent.com/233717/44506262-e5091000-a6e8-11e8-9da1-b304ea130c1c.png">

Not working:
<img width="1337" alt="screen shot 2018-08-23 at 3 21 34 pm" src="https://user-images.githubusercontent.com/233717/44506260-e3d7e300-a6e8-11e8-845e-fdb9a9bce3d4.png">

### Expected behavior

TOC to show up on all pages which have headings.

### Actual behavior

TOC not showing up on pages with headings.

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Package versions

* Python: `2.7.15`
* MkDocs: `1.0.1`
* Material: `3.0.3`

### Project configuration

``` yaml
# Project information
site_name: Mɛta 1.0.0
site_description: 
site_author: Marat Levit
site_url: https://localhost.com

# Repository
repo_name: <blanked>
repo_url: <blanked>
edit_uri: ""

# Copyright
copyright: <blanked>

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: true
  logo:
    icon: 'code'
docs_dir: docs
site_dir: docs_html
use_directory_urls: true

# Customization
extra:
  social:
    - type: globe
      link: <blanked>
    - type: twitter
      link: <blanked>
    - type: linkedin
      link: <blanked>

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

# Page tree
nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - Metadata:
    - Operational: metadata/operational.md
    - Technical: metadata/technical.md
    - Business: metadata/business.md
  - Frameworks:
    #- Extract: framework/extract.md
    #- Transform: framework/transform.md
    #- Load: framework/load.md
    - Change Data Capture: framework/cdc.md
    - Alerting & Monitoring: framework/alerting_monitoring.md
    - Technical Reconciliation: framework/technical_reconciliation.md
  - Parameters:
    - Artefact: parameters/artefact.md
    - Process: parameters/process.md
    #- Batch: parameters/batch.md
  - API:
      - Run-time Objects API: api/run_time_objects_api.md
      - Design-time Objects API: api/design_time_objects_api.md
  - Changelog: changelog.md
  - License: license.md
```

### System information

* OS: macOS Mojava 10.14
* Browser: Chrome
