### ISSUE TITLE
Progressbar is not rendered

### ISSUE THREAD

**Issue by SUlbrichA** [squidfunk/mkdocs-material#862]
## Description

Progressbar extension shows only the label. E.g., `[= 30% "30%"]` or `[= 30% "30%"]{: .thin}` renders only as `30%`.

### Expected behavior

The progressbar is rendered.

### Actual behavior

The progressbar is not rendered

### Steps to reproduce the bug

1. write `[= 30% "30%"]` into md file

### Package versions

* Python: `python --version` Python 3.6.5
* MkDocs: `mkdocs --version` mkdocs, version 1.0.2
* Material: `pip show mkdocs-material | grep -E ^Version` Version: 3.0.3

### Project configuration

``` yaml
markdown_extensions:
  - attr_list
  - admonition
  - codehilite
  - footnotes
  - def_list
  - toc:
      permalink: true

  - pymdownx.progressbar:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.keys

theme:
  name: 'material'
  favicon: 'img/neuron.ico'

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
```

### System information

* OS: [The operating system you're running] Ubuntu 18.04
* Browser: [The browser used, if relevant] Chromium 68.0.3440.106 (Official Build)
