### ISSUE TITLE
docker social icon

### ISSUE THREAD

**Issue by vsoch** [squidfunk/mkdocs-material#864]
Hey @squidfunk ! Hopefully this is a simple issue to resolve! I am wanting to get the font awesome icon for Docker Hub (this one --> https://fontawesome.com/icons/docker?style%5C=brands&style=brands) to link to our Docker organization under social extra. 

```
extra:
  social:
    - type: 'github'
      link: 'https://github.com/openbases'
    - type: 'docker'
      link: 'http://hub.docker.com/r/openbases'
    - type: 'twitter'
      link: 'https://twitter.com/vsoch'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/vsochat'
```

It doesn't seem to render. I noticed that the font awesome icons also designate `fa-docker fab` so I added fab, and that didn't render either. 

![image](https://user-images.githubusercontent.com/814322/44739986-42c1a180-aac7-11e8-9d30-581a405201bf.png)

Is there a way to support the icon?
