### ISSUE TITLE
"previous" "next" button produce incorrect url

### ISSUE THREAD

**Issue by zorgrian** [squidfunk/mkdocs-material#870]
## Description

The buttons at the bottom for previous and next article bow do not work with mkdocs, version 1.0.2

### Expected behavior

We expect the generated URL to be collected from the YAML file Nav: list. This was working correctly but now does not
### Actual behavior

What actually occurs is a mixup of the current URL and the URL collected from the YAML file Nav: list.

### Steps to reproduce the bug

Try this on any YAML setup that was previously working and you will see that it now does not function correctly 

### Package versions

* Python: `python Python 3.7.0
& Python 2.7.15
`
* MkDocs: `mkdocs version 1.0.2`
* Material: `Version: 3.0.3`

### Project configuration

``` yaml
site_name: YooFab™ - Join The Makerspace Revolution
site_description: Doumentation for YooFab™ kits, guides and information on making electronic projects, working with materials, setting up a workshop and more...

nav:
- HOME: 'index.md'
- SHOP: 'http://www.macrovend.com'
- ABOUT:
    - 'About YooFab': 'about/about.md'
    - 'Contact': 'about/contact.md'
    - 'Disclaimer': 'about/disclaimer.md'
- KITS:
    - 'The YooFab 40 Meter regenerative receiver': 'kits/regenReceiver/regenKitMk7.md'
    - 'The YooFab QRP Headphone amplifier': 'kits/amplifier/headphone.md'
- LEARN:
    - 'Learn with Yoofab': 'learn/learn.md'
    - 'Makerspace workshops': 'learn/workshop.md'
    - ARDUINO:
       - 'List of Arduino types': 'learn/arduino/arduinoTypes.md'
       - 'The Arduino derivatives': 'learn/arduino/arduinoDerivatives.md'
       - 'Arduino code': 'learn/arduino/arduinoCode.md'
       - 'Arduino projects': 'learn/arduino/projects.md'
    - SOLDERING:
        - 'An introduction to soldering': 'learn/soldering/basicSolder.md'
    - ELECTRONICS:
        - 'Introduction to the electronics learn section': 'learn/electronics/introduction.md'
        - 'Basics of electricity and electronics': 'learn/electrics.md'
        - 'Back to Basics Tutorial - Voltage & Current in capacitors & inductors': 'learn/electronics/currentVoltageCL.md'
        - COMPONENTS:
            - 'Resistors': 'learn/electronics/components/resistor.md'
            - 'Capacitors': 'stub.md'
            - 'Does current flow through a capacitor?': 'learn/electronics/components/currentCap.md'
            - 'Inductors': 'stub.md'
        - ANALOGUE:
            - 'Introduction to analogue electronics': 'stub.md'
        - DIGITAL:
            - 'Introduction to digital electronics': 'stub.md'
            - 'Using a ROM to replace combined logic circuits': learn/electronics/digital/usingRomToRplace.md
        - CIRCUIT BLOCKS:
            - 'Introduction to circuit blocks': 'learn/electronics/blocks/introduction.md'
            - ELECTRONIC BLOCKS:
                - 'Introduction to basic electronic knowledge': 'stub.md'
                - 'Detectors (Radio)': 'learn/electronics/blocks/detector.md'
                - VOLTAGE SUPPLY & REGULATION:
                    - 'Introduction to VOLTAGE SUPPLY & REGULATION': 'stub.md'
                - TRANSISTOR AMPLIFIER STAGES:
                    - 'Introduction to TRANSISTOR AMPLIFIER STAGES': 'stub.md'
                - OSCILLATORS:
                    - 'Introduction to OSCILLATORS': 'learn/electronics/blocks/oscillators/oscillators.md'
                - PREAMPLIFIERS:
                    - 'A universal Preamplifier': 'learn/electronics/blocks/amplifiers/universalPreamp.md'
                -  DIFFERENTIAL AMPLIFIERS:
                    - 'What is a differential amplifier?': 'learn/electronics/blocks/diff/diffWhat.md'
                    - 'The long tail pair': 'learn/electronics/blocks/diff/longTail.md'
    - RADIO:
            - 'QRP receiver schematics and notes': 'learn/radio/schematics.md'
            - 'QRP on the web': 'learn/radio/web.md'
            - 'QRP DDS and clock sources': 'learn/radio/ddsClock.md'
            - 'Crystal grinding, adjusting and scribbling': 'learn/radio/grind.md'
            - TRF & CRYSTAL SET RADIOS:
                - "The MK484 - TA4672": 'learn/radio/TRF/MK484.md'
- OFF-TOPIC:
    - KNOWLEDGE & POWER:
        - 'The evolution of knowledge': 'off-topic/ThenextStep.md'
markdown_extensions:
  - admonition
  - meta
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets
theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'Blue Grey'
  logo: 'images/logo.svg'
  favicon: 'images/favicon.ico'

```

### System information

* OS: [The operating system you're running]
* Browser: [The browser used, if relevant]
