### ISSUE TITLE
Feature tab for external link in nav item

### ISSUE THREAD

**Issue by ngtrian** [squidfunk/mkdocs-material#889]
I set nav Home is "http://mysite.com/", I have enable feature tab  then tab **Home** not appear.
How can I add a tab **Home** to the menubar?

```yaml
theme: 
    name: 'material'
    feature:
        tabs: true

nav:
    - Home: "http://mysite.com/"
    - Javascript:
        - Intro: javascript/index.md
```

**Comment by martinbira** [comment]
I'm not sure MkDocs is supposed to work with an external page as the first item of a nav.

See https://www.mkdocs.org/user-guide/writing-your-docs/#index-pages, https://www.mkdocs.org/user-guide/configuration/#documentation-layout,  and https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation

Also, see the `site_url` property.

**Comment by ngtrian** [comment]
If disable feature tab, nav with custom link working done.

**Comment by ngtrian** [comment]
Can you intergrate this feature?My external link is site_url with another subfolder.

I am creating a document page with a lot of content categories.
And because material does not support searching for content under the current tab, I created each separate mkdocs page located in different subfolders of the domain and linked them in the feature tab.

**Comment by squidfunk** [comment]
I'm afraid no, it's not possible with MkDocs. You can override the theme as already stated.

**Comment by squidfunk** [comment]
Closing this as answered. It's not supported by MkDocs but can easily be solved via theme extension.

**Comment by ngtrian** [comment]
I have resolve with **nested** based on your suggestion
```yaml
theme: 
    name: 'material'
    feature:
        tabs: true

nav:
    - Home: 
        - Intro: "http://mysite.com/"
    - Javascript:
        - Intro: javascript/index.md
```

**Comment by gtmsingh** [comment]
Also, if this helps, you can open the link in new tab by using the following construct:

```yaml
theme: 
    name: 'material'
    feature:
        tabs: true

nav:
    - Home: 
        - Intro: http://mysite.com/" target="_blank
    - Javascript:
        - Intro: javascript/index.md
```
Note: There are missing quotes in the external link value. It works like SQL injection where we inject this in anchor tag.
