### ISSUE TITLE
UTF-8 in TOC

### ISSUE THREAD

**Issue by DorKeinath** [squidfunk/mkdocs-material#893]
In my table of contents (german "Inhaltsverzeichnis") entries including "äöü" are listed correctly ("Übung" like here: https://xcosx.de/u/vkm/konvergenz/) and sometimes reduced to "aou" ("Übung" becomes "Ubung" hier: https://xcosx.de/u/vkm/reihen_def_u_bspe/). Can sombody see my bug?

### Package versions

* Python: `python --version` 3.7.0
* MkDocs: `mkdocs --version` 1.0.4
* Material: `pip show mkdocs-material | grep -E ^Version` 3.0.4

### Project configuration

``` yaml
site_name:  DesKeinaths Unterricht
site_description: 'Unterrichtsstunden zu Ethik Mathematik und Informatik'
site_author: DorKeinath
site_url: https://xcosx.de/

nav:
    - Intro: index.md
...
    - 'VkM':
        - Intro: vkm/index.md
        - 'Zertifikatsklausur': vkm/zertifikatsklausur.md
        - 'Griechisches Alphabet': vkm/griechisches_alphabet.md
        - 'Vollständige Induktion': vkm/vollstaendige_induktion.md
        - 'Lösen von (Un-)Gleichungen':
            - 'Polynomgleichungen': vkm/polynomgleichungen.md
            - 'Polynomungleichungen': vkm/polynomungleichungen.md
            - 'Bruch(un)gleichungen': vkm/bruchgleichungen.md
            - 'Wurzelgleichungen': vkm/wurzelgleichungen.md
            - 'Betrags(un)gleichungen': vkm/betragsgleichungen.md
        - 'Folgen und Reihen':
            - 'Folgenglieder darstellen': vkm/folgenglieder.md
            - 'Grenzwertsätze': vkm/grenzwertsaetze.md
            - 'Monotonie von Folgen': vkm/monotonie.md
            - 'Beschränktheit von Folgen': vkm/beschraenktheit.md
            - 'Konvergenz von Folgen': vkm/konvergenz.md
            - 'Besondere Folgen': vkm/besondere_folgen.md
            - 'Reihen': vkm/reihen_def_u_bspe.md
            - 'Partialbruchzerlegung': vkm/partialbruchzerlegung.md
            - 'Grenzwert von Reihen': vkm/reihen_grenzwert.md
            - 'Konvergenz von Reihen': vkm/reihen_konvergenz.md
        - 'Integration':
            - 'Integration durch Partialbruchzerlegung': vkm/int_integration_durch_partialbruchzerlegung.md
            - 'Produktintegration': vkm/int_produktintegration.md
            - 'Integration durch Substitution': vkm/int_integration_durch_substitution.md

theme:
    name: material
    palette:
        primary: amber
        accent: pink
    language: de
    feature:
        tabs: true
    font: false
    logo:
        icon: school

markdown_extensions:
    - pymdownx.arithmatex
    - toc:
        permalink: true
    - pymdownx.betterem:
        smart_enable: all
    - admonition # https://squidfunk.github.io/mkdocs-material/extensions/admonition/
    - pymdownx.details
    - codehilite:
        linenums: true # https://squidfunk.github.io/mkdocs-material/extensions/codehilite/#highlighting-specific-lines
        guess_lang: true
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true

extra_javascript:
    - assets/extra.js
    - https://xcosx.de/MathJax/MathJax.js?config=TeX-AMS_SVG-full #if only used TeX
MML_HTMLorMML

extra_css:
    - assets/extra.css

```

### System information

* OS: AntergOS

### Markdown-files
https://xcosx.de/u/u_md.zip
