### ISSUE TITLE
Link to external url on site_name

### ISSUE THREAD

**Issue by ncarboni** [squidfunk/mkdocs-material#896]
I am using mkdocs and material theme for sharing the documentation of a project. It is, currently, hosted in a subdomain accessible by a link in the homepage of the project.   
However, if I can access the documentation website from the main project website, I do not have a way to point to the project website while browsing my documentation.  
I wonder if it is possible to being redirect to the project website (external url) when clicking on the site_name of the header.
Alternatively, do you have in mind any other solutions to resolve the issue?

**Comment by squidfunk** [comment]
You're can always customize the theme, see https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme

**Comment by ncarboni** [comment]
Umh, I don't understand, the `name` is already there. Should I put it somewhere else? 
Full mkdocs.tml

```yml
site_name: Data docs
repo_url: https://example.com/docs
site_description: documentation

# Customization
extra:
  social:
    - type: globe
      link: https://example.com/
    - type: github-alt
      link: https://example.com/
    - type: wikipedia-w
      link:https://example.com/
    - type: twitter
      link: https://example.com/
  

# pagination  
pages:
    - Data Harmonization: index.md
    - Patterns:
        - General patterns: modelling.md
        - Temporal pattern: temporal.md
        - Physical pattern: physical.md
#        - Conceptual pattern: conceptual.md
    - Entity type:
      - Actor : et/actor.md
    - Time: time.md
    - Images: images.md
    - Bibliographic Data: bibliographic_data.md
    - Tools: 
        - Info: tool/index.md
        - X3ML: tool/mapping.md
 

theme: 
  name: material
  logo: 'images/logo_image.svg'
  palette:
    primary: 'white'
  favicon: 'images/favicon.ico'
  custom_dir: 'theme/'
extra_css:
  - 'stylesheets/extra.css'

markdown_extensions:
  - pymdownx.smartsymbols
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.superfences
  - meta
  - footnotes
  - admonition
  - toc:
      permalink: true
  - codehilite:
      linenums: true
```
