### ISSUE TITLE
Search freeze on first search

### ISSUE THREAD

**Issue by gridphp** [squidfunk/mkdocs-material#904]
## Description

When ever we open the page first time and click on search box, it freezes for almost 10 seconds.

### Expected behavior

Should be instant like in other themes OR show what it is doing.

### Actual behavior

Freezing the whole window

### Steps to reproduce the bug

1. I've around 20 MD files with 5000 lines of text. 
2. Open main page and click search box
3. Wait and enjoy the slow speed.

In this screencast, i pressed button instantly but results were way too late.
https://i.imgur.com/KZU3G66.gifv

I changed theme to readthedocs, and tried as well which does not freeze.
Let me know what i am missing.

### Package versions

* Python: `3.7`
* MkDocs: `1.0.4`
* Material: `3.0.4`

### Project configuration

``` yaml
site_name: ................
site_description: .......... Documentation
# site_url:
site_author: '..............'
site_url: 'https://........../docs'

# Copyright
copyright: 'Copyright &copy; 2010 - 2018'

nav:
    - Getting Started:
      - 'Setup' : 'index.md'
      - 'Creating' : 'creating.md'
    - Customization:
      - 'Selecting Columns' : 'selecting-columns.md'
      - 'Column Options' : 'column-options.md'
      - 'Options' : 'options.md'
    - Features:
      - 'Master Detail' : 'master-detail.md'
      - 'Sub' : 'sub.md'
      - 'Exporting Data' : 'exporting-data.md'
      - 'Importing Data' : 'importing-data.md'
      - 'Conditional Formatting' : 'conditional-formatting.md'
      - 'Grouping' : 'grouping.md'
      - 'Grouping Headers' : 'grouping-headers.md'
      - 'Search' : 'search.md'
      - 'Events' : 'events.md'
      - 'Validation' : 'validation.md'
      - 'Upload Files' : 'upload-files.md'
      - 'Summary' : 'summary.md'
      - 'Autocomplete' : 'autocomplete.md'
    - Layout & UI:
      - 'Responsive Design' : 'responsive-design.md'
      - 'Localization' : 'localization.md'
      - 'Themes' : 'themes.md'
    - Databases:
      - 'Connecting with SQL Server' : 'connecting-with-sql-server.md'
      - 'Connecting with Postgres' : 'connecting-with-postgres.md'
      - 'Connecting with Oracle' : 'connecting-with-oracle.md'
      - 'Debug Mode' : 'debug-mode.md'
    - FAQs:
      - 'General' : 'faq-general.md'
      - 'Appearance' : 'faq-appearance.md'
      - 'Column Appearance' : 'faq-column-appearance.md'
      - 'Column Settings' : 'faq-column-settings.md'
      - 'Dialog Customization' : 'faq-dialog-customization.md'
      - 'Javascript API' : 'faq-javascript-api.md'
      - 'Databases' : 'faq-databases.md'
      - 'Master Detail' : 'faq-master-detail.md'
      - 'Export' : 'faq-export.md'
      - 'Misc' : 'faq-misc.md'
theme:
    logo: 'https://.............png'
    name: material
    favicon: 'css/favicon.gif'

# Customization
extra:
  feature:  
    tabs: true
  search:
  #   tokenizer: '[\s\-\.]+'
    language: 'en'
    # prebuild_index: true

site_dir: ../docs
docs_dir: md


extra_css:
    - extra/extra.css
extra_javascript:
    - extra/extra.js
```

### System information

* OS: Win10
* Browser: Chrome Version 70.0.3538.67 (Official Build) (64-bit)
