### ISSUE TITLE
Can not use the search box on some pages

### ISSUE THREAD

**Issue by ngtrian** [squidfunk/mkdocs-material#905]
## Description

There are some pages (nav) that can not be clicked to expand the search box, and there are bugs in the browser's console
```
Uncaught TypeError: Cannot read property 'offsetTop' of undefined
    at e.update (application.583bbe55.js:1)
    at e.setup (application.583bbe55.js:1)
    at e.listen (application.583bbe55.js:1)
    at e.o.handler_ (application.583bbe55.js:1)
    at new e (application.583bbe55.js:1)
    at Object.i [as initialize] (application.583bbe55.js:1)
    at (index):1583
```
Specific link: http: //docs.nopviet.com/nopcommerce/user-guide/cong-cu-quang-cao/

### Expected behavior

Can not use the search function on that page in link: http: //docs.nopviet.com/nopcommerce/user-guide/cong-cu-quang-cao/  when accessing the URL using the Chrome browser

### Steps to reproduce the bug

1. Open Chrome
2. Open URL: http: //docs.nopviet.com/nopcommerce/user-guide/cong-cu-quang-cao/ 
3. Click search box --> no expand search box
4. Open Developer tools > Console > an error as above
5. If scroll page, Other errors appear in the console
```
Uncaught TypeError: Cannot read property 'offsetTop' of undefined
    at e.update (application.583bbe55.js:1)
    at update_ (application.583bbe55.js:1)
```

### Package versions

* Python: Python 2.7.15rc1
* MkDocs: mkdocs, version 1.0.4 
* Material: 3.0.4

### Project configuration

``` yaml
site_name: Hướng dẫn sử dụng nopCommerce
site_url: http://docs.nopviet.com/
site_description: Hướng dẫn sử dụng nopCommerce trên Nopviet docs
site_author: nopViet Team
repo_url: https://nopviet.com
repo_name: nopviet.com

site_dir: ../site/nopcommerce

theme:
  name: 'material'
  #custom_dir: custom_theme
  logo:
    icon: 'code'
  feature:
    tabs: true
  favicon: ../../favicon.png
  language: 'vi'

extra_css:
  #- lib/extra.css

extra:
  social:
    - type: globe
      link: http://nopviet.com
    - type: facebook-official
      link: https://www.facebook.com/nopvietclub/
    - type: twitter
      link: https://twitter.com/nopviet
    - type: skype
      link: skype:ngtrian?chat
  #fb_comment: 1626994820900489
    
google_analytics:
  - 'UA-39056872-8'
  - 'auto'

# Copyright
copyright: 'Copyright &copy; 2018 <a href="http://nopviet.com/" title="Cộng đồng web, server và công nghệ"> NOPVIET.COM - Cộng đồng web, server và công nghệ</a>'

# Extensions
markdown_extensions:
  - extra
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: "#"
      # Xử lý ký tự "đ" khi tạo header id
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.magiclink # Tự động nhận diện link, bắt đầu với http[s]:\\ hoặc ftp:\\
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde # Dấu gạch chéo giữa chữ, sử dụng ~text~
  
nav:
  - nopCommerce: 
      - Sử dụng nopCommerce: 
        - Bắt đầu: index.md
        - Cài đặt nopCommerce: user-guide/cai-dat-nopcommerce.md
        - Thiết lập cửa hàng:
          - Giao diện trang quản trị: user-guide/giao-dien-quan-tri.md
          - Thiết lập cửa hàng:
            - Thiết lập cơ bản: user-guide/thiet-lap-co-ban.md
            - Thiết lập thanh toán: user-guide/thiet-lap-thanh-toan.md
            - Thiết lập thuế: user-guide/thiet-lap-thue.md
            - Thiết lập giao hàng: user-guide/thiet-lap-giao-hang.md
            - Thiết lập khách hàng: user-guide/thiet-lap-khach-hang.md
            - Tất cả thiết lập (nâng cao): user-guide/thiet-lap-nang-cao.md
          - Quản trị hệ thống: user-guide/quan-tri-he-thong.md
          - Giao diện nopCommerce: user-guide/giao-dien-nopcommerce.md
        - Khởi chạy cửa hàng:
          - Quản lý sản phẩm:
            - Danh mục: user-guide/danh-muc.md
            - Nhà sản xuất: user-guide/nha-san-xuat.md
            - Thuộc tính: user-guide/thuoc-tinh.md
            - Sản phẩm: user-guide/san-pham.md
            - Thiết lập danh mục: user-guide/thiet-lap-danh-muc.md
          - Quản lý đơn hàng:
            - Đơn hàng: user-guide/don-hang.md
            - Giao hàng: user-guide/giao-hang.md
            - Trả hàng: user-guide/tra-hang.md
            - Giỏ hàng: user-guide/gio-hang.md
            - Danh sách yêu thích: user-guide/danh-sach-yeu-thich.md
            - Quản lý hàng tồn kho: user-guide/quan-ly-hang-ton-kho.md
          - Quản lý khách hàng: user-guide/quan-ly-khach-hang.md
          - Lập báo cáo: user-guide/lap-bao-cao.md
        - Tiếp thị cửa hàng:
          - Công cụ quảng cáo: user-guide/cong-cu-quang-cao.md
          - Quản lý nội dung: user-guide/quan-ly-noi-dung.md
        - Tài liệu hướng dẫn cho các version cũ: user-guide/tai-lieu-nopcommerce-khac.md
        - Các câu hỏi thường gặp (FAQ): faq-nopcommerce.md
      - Phát triển nopCommerce: 
        - Hướng dẫn thiết kế giao diện: developer-guide/huong-dan-thiet-ke.md
        - Bài hướng dẫn phát triển: developer-guide/tut-developer.md
        - Tạo plugin nopCommerce: developer-guide/tao-plugin-nopcommerce.md
```

### System information

* OS: Ubuntu 18.04.1 LTS
* Browser: Chrome 70
