### ISSUE TITLE
Next and Previous Pages Result on 404 Error

### ISSUE THREAD

**Issue by rei-vilo** [squidfunk/mkdocs-material#908]
## Description

Next and Previous pages result in `Error 404`.

### Expected behavior

Go the next or previous page.

### Actual behavior

`Error 404`

The link includes the path to the current page + the path to the next or previous page.

On page Forewords, clicking on **Next** looks for the path `https://mywebsite.com/About/Chapter1/Section1/` instead of `https://mywebsite.com/Chapter1/Section1/`.

### Steps to reproduce the bug

1. Press on Next and Previous pages

On page Forewords, clicking on **Next** looks for the path `https://mywebsite.com/About/Chapter1/Section1/` instead of `https://mywebsite.com/Chapter1/Section1/`.

### Package versions

* Python: `python --version` Python 2.7.15
* MkDocs: `mkdocs --version` mkdocs, version 1.0.4 from /usr/local/lib/python2.7/site-packages/mkdocs (Python 2.7)
* Material: `pip show mkdocs-material | grep -E ^Version` Version: 3.0.5

### Project configuration

``` yaml
site_name: My Website
site_url: https://mywebsite.com/

nav:
- Table of content: index.md
- Forewords: About.md
- Install embedXcode:
    - Learn about frameworks: Chapter1/Section1.md
    - Install Xcode: Chapter1/Section2.md
    - Install the Wiring / Arduino framework: Chapter1/Section4.md
    - Install embedXcode: Chapter1/Section3.md
    - Install optional self-documentation tools: Chapter1/Section5.md
```

### System information

* OS: mac 10.14
* Browser: Safari
