### ISSUE TITLE
Indented code in ordered list

### ISSUE THREAD

**Issue by pglira** [squidfunk/mkdocs-material#945]
## Description

I can not reproduce the example from the specimen with the **indented code within an ordered list**. As you can see in the screenshots below the code is displayed not as block but in a single line. What could be the reason for this issue?

### Expected behavior

![image](https://user-images.githubusercontent.com/14214284/50627542-30071f80-0f34-11e9-8730-afbd92e55c94.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/14214284/50627557-41e8c280-0f34-11e9-8674-4ff78b123868.png)

### Steps to reproduce the bug

...

### Package versions

* Python: Python 3.4.3
* MkDocs: mkdocs, version 1.0.4 from /usr/local/lib/python3.4/dist-packages/mkdocs (Python 3.4)
* Material: Version: 3.2.0

### Project configuration

``` yaml
# Project information
site_name: xxx
site_description: 'xxx'
site_author: 'xxx'
site_url: null

# pages:
nav:
- Start: 'index.md'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

# For rendering of equations
extra_javascript:
  - 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML'
```

### System information

* OS: Ubuntu 14.04
* Browser: Google Chrome
