### ISSUE TITLE
"uslugify" breaks header anchors list

### ISSUE THREAD

**Issue by CMTV** [squidfunk/mkdocs-material#972]
## Description

Setting custom slugify function "uslugify" from pymodown breaks header anchors block at the right.

```yml
markdown_extensions:
    ...
    - toc:
          permalink: '#'
          slugify: !!python/name:pymdownx.slugs.uslugify
    ...
```

### Expected behavior

When scrolling down headers are fading out. This gives a visual understanding of current position on the page.

### Actual behavior

When scrolling, the browser console spams the following error:
![error](https://user-images.githubusercontent.com/25921286/51799426-d98ab980-2231-11e9-8bb9-02590ed9dd64.png)

![error2](https://user-images.githubusercontent.com/25921286/51799494-266e9000-2232-11e9-9334-7ad571773735.png)

### Steps to reproduce the bug

1. In `mkdocs.yml` set a custom slugify function ("uslugify" in my case)
2. Add some cyrillic headers in `index.md`
3. Anchor links are not fading and the console spams the error when scrolling the page
