### ISSUE TITLE
Issue with getting tabs working

### ISSUE THREAD

**Issue by andrewschott** [squidfunk/mkdocs-material#988]
## Description

The tabs feature only plops two tabs up, not the 4 I have defined in my nav section.  I am not deployed with this, rather using "mkdocs serve" to test out the theme.  To see a fully functional (minus the tweaks to make your theme work) site, hitup schotty.com and see the menus working fine.

### Expected behavior

Tabs to be correct

### Actual behavior

2 Tabs

### Package versions

$ python --version
Python 2.7.15

$ mkdocs --version
mkdocs, version 1.0.4 from /usr/lib/python2.7/site-packages/mkdocs (Python 2.7)

$ pip show mkdocs-material | grep -E ^Version
Version: 3.3.0

$ pip show mkdocs | grep -E ^Version
Version: 1.0.4
 

### Project configuration

``` yaml
site_name: Schotty.com
site_author: Schotty
site_url: https://www.schotty.com/
copyright: '©2019 Andrew Schott (Schotty).  Powered by mkDocs & CentOS Linux.'
theme: 
  name: material
  palette:
    primary: 'red'
    accent: 'red'
  logo: 'img/favicon.ico'
  favicon: 'img/favicon.ico'
  feature:
    tabs: true
  include_sidebar: yes
  include_search_page: false
  search_index_only: true

nav:
  - Blog: index.md
  - Documentation: Documentation_Links.md
  - Services:
    - Site Resources: Services/Site_Resources.md
    - Videos: Services/Videos.md
  - Contact: Services/Contact.md

extra:
  prev_next_enabled: false

plugins: 
  - search

google_analytics: 
  - ["UA-81841123-1"]
  - auto
```

### System information

* OS: [Fedora 28, 29, RHEL 7.5, CentOS 7 (latest updates)]
* Browser: [Chrome AND Firefox, tried both to see if it was a cache or browser issue]

### Screenshot of issue
![screenshot from 2019-02-08 21-14-56](https://user-images.githubusercontent.com/14102747/52515846-aa3b5b80-2be6-11e9-95a7-b2064f9404cb.png)
